// 
// Decompiled by Procyon v0.5.36
// 

package org.apache.commons.imaging.formats.tiff.constants;

import java.util.Collections;
import java.util.Arrays;
import org.apache.commons.imaging.formats.tiff.taginfos.TagInfo;
import java.util.List;
import org.apache.commons.imaging.formats.tiff.taginfos.TagInfoDoubles;
import org.apache.commons.imaging.formats.tiff.taginfos.TagInfoFloats;
import org.apache.commons.imaging.formats.tiff.taginfos.TagInfoLongs;
import org.apache.commons.imaging.formats.tiff.taginfos.TagInfoUndefineds;
import org.apache.commons.imaging.formats.tiff.taginfos.TagInfoLong;
import org.apache.commons.imaging.formats.tiff.taginfos.TagInfoRational;
import org.apache.commons.imaging.formats.tiff.taginfos.TagInfoSRational;
import org.apache.commons.imaging.formats.tiff.taginfos.TagInfoShortOrRational;
import org.apache.commons.imaging.formats.tiff.taginfos.TagInfoRationals;
import org.apache.commons.imaging.formats.tiff.taginfos.TagInfoShortOrLong;
import org.apache.commons.imaging.formats.tiff.taginfos.TagInfoSRationals;
import org.apache.commons.imaging.formats.tiff.taginfos.TagInfoShortOrLongOrRational;
import org.apache.commons.imaging.formats.tiff.taginfos.TagInfoShorts;
import org.apache.commons.imaging.formats.tiff.taginfos.TagInfoShort;
import org.apache.commons.imaging.formats.tiff.taginfos.TagInfoAsciiOrByte;
import org.apache.commons.imaging.formats.tiff.taginfos.TagInfoAscii;
import org.apache.commons.imaging.formats.tiff.taginfos.TagInfoBytes;

public final class DngTagConstants
{
    public static final TagInfoBytes EXIF_TAG_DNG_VERSION;
    public static final TagInfoBytes EXIF_TAG_DNG_BACKWARD_VERSION;
    public static final TagInfoAscii EXIF_TAG_UNIQUE_CAMERA_MODEL;
    public static final TagInfoAsciiOrByte EXIF_TAG_LOCALIZED_CAMERA_MODEL;
    public static final TagInfoBytes EXIF_TAG_CFAPLANE_COLOR;
    public static final TagInfoShort EXIF_TAG_CFALAYOUT;
    public static final int CFALAYOUT_VALUE_RECTANGULAR = 1;
    public static final int CFALAYOUT_VALUE_EVEN_COLUMNS_OFFSET_DOWN_1_2_ROW = 2;
    public static final int CFALAYOUT_VALUE_EVEN_COLUMNS_OFFSET_UP_1_2_ROW = 3;
    public static final int CFALAYOUT_VALUE_EVEN_ROWS_OFFSET_RIGHT_1_2_COLUMN = 4;
    public static final int CFALAYOUT_VALUE_EVEN_ROWS_OFFSET_LEFT_1_2_COLUMN = 5;
    public static final int CFALAYOUT_VALUE_EVEN_ROWS_OFFSET_UP_1_2_ROW_EVEN_COLUMNS_OFFSET_LEFT_1_2_COLUMN = 6;
    public static final int CFALAYOUT_VALUE_EVEN_ROWS_OFFSET_UP_1_2_ROW_EVEN_COLUMNS_OFFSET_RIGHT_1_2_COLUMN = 7;
    public static final int CFALAYOUT_VALUE_EVEN_ROWS_OFFSET_DOWN_1_2_ROW_EVEN_COLUMNS_OFFSET_LEFT_1_2_COLUMN = 8;
    public static final int CFALAYOUT_VALUE_EVEN_ROWS_OFFSET_DOWN_1_2_ROW_EVEN_COLUMNS_OFFSET_RIGHT_1_2_COLUMN = 9;
    public static final TagInfoShorts EXIF_TAG_LINEARIZATION_TABLE;
    public static final TagInfoShorts EXIF_TAG_BLACK_LEVEL_REPEAT_DIM;
    public static final TagInfoShortOrLongOrRational EXIF_TAG_BLACK_LEVEL;
    public static final TagInfoSRationals EXIF_TAG_BLACK_LEVEL_DELTA_H;
    public static final TagInfoSRationals EXIF_TAG_BLACK_LEVEL_DELTA_V;
    public static final TagInfoShortOrLong EXIF_TAG_WHITE_LEVEL;
    public static final TagInfoRationals EXIF_TAG_DEFAULT_SCALE;
    public static final TagInfoShortOrLongOrRational EXIF_TAG_DEFAULT_CROP_ORIGIN;
    public static final TagInfoShortOrLongOrRational EXIF_TAG_DEFAULT_CROP_SIZE;
    public static final TagInfoSRationals EXIF_TAG_COLOR_MATRIX_1;
    public static final TagInfoSRationals EXIF_TAG_COLOR_MATRIX_2;
    public static final TagInfoSRationals EXIF_TAG_CAMERA_CALIBRATION_1;
    public static final TagInfoSRationals EXIF_TAG_CAMERA_CALIBRATION_2;
    public static final TagInfoSRationals EXIF_TAG_REDUCTION_MATRIX_1;
    public static final TagInfoSRationals EXIF_TAG_REDUCTION_MATRIX_2;
    public static final TagInfoRationals EXIF_TAG_ANALOG_BALANCE;
    public static final TagInfoShortOrRational EXIF_TAG_AS_SHOT_NEUTRAL;
    public static final TagInfoRationals EXIF_TAG_AS_SHOT_WHITE_XY;
    public static final TagInfoSRational EXIF_TAG_BASELINE_EXPOSURE;
    public static final TagInfoRational EXIF_TAG_BASELINE_NOISE;
    public static final TagInfoRational EXIF_TAG_BASELINE_SHARPNESS;
    public static final TagInfoLong EXIF_TAG_BAYER_GREEN_SPLIT;
    public static final TagInfoRational EXIF_TAG_LINEAR_RESPONSE_LIMIT;
    public static final TagInfoAscii EXIF_TAG_CAMERA_SERIAL_NUMBER;
    public static final TagInfoRationals EXIF_TAG_DNG_LENS_INFO;
    public static final TagInfoRational EXIF_TAG_CHROMA_BLUR_RADIUS;
    public static final TagInfoRational EXIF_TAG_ANTI_ALIAS_STRENGTH;
    public static final TagInfoRational EXIF_TAG_SHADOW_SCALE;
    public static final TagInfoBytes EXIF_TAG_DNG_PRIVATE_DATA;
    public static final TagInfoShort EXIF_TAG_MAKER_NOTE_SAFETY;
    public static final int MAKER_NOTE_SAFETY_VALUE_UNSAFE = 0;
    public static final int MAKER_NOTE_SAFETY_VALUE_SAFE = 1;
    public static final TagInfoShort EXIF_TAG_CALIBRATION_ILLUMINANT_1;
    public static final int CALIBRATION_ILLUMINANT_1_VALUE_DAYLIGHT = 1;
    public static final int CALIBRATION_ILLUMINANT_1_VALUE_FLUORESCENT = 2;
    public static final int CALIBRATION_ILLUMINANT_1_VALUE_TUNGSTEN = 3;
    public static final int CALIBRATION_ILLUMINANT_1_VALUE_FLASH = 4;
    public static final int CALIBRATION_ILLUMINANT_1_VALUE_FINE_WEATHER = 9;
    public static final int CALIBRATION_ILLUMINANT_1_VALUE_CLOUDY = 10;
    public static final int CALIBRATION_ILLUMINANT_1_VALUE_SHADE = 11;
    public static final int CALIBRATION_ILLUMINANT_1_VALUE_DAYLIGHT_FLUORESCENT = 12;
    public static final int CALIBRATION_ILLUMINANT_1_VALUE_DAY_WHITE_FLUORESCENT = 13;
    public static final int CALIBRATION_ILLUMINANT_1_VALUE_COOL_WHITE_FLUORESCENT = 14;
    public static final int CALIBRATION_ILLUMINANT_1_VALUE_WHITE_FLUORESCENT = 15;
    public static final int CALIBRATION_ILLUMINANT_1_VALUE_STANDARD_LIGHT_A = 17;
    public static final int CALIBRATION_ILLUMINANT_1_VALUE_STANDARD_LIGHT_B = 18;
    public static final int CALIBRATION_ILLUMINANT_1_VALUE_STANDARD_LIGHT_C = 19;
    public static final int CALIBRATION_ILLUMINANT_1_VALUE_D55 = 20;
    public static final int CALIBRATION_ILLUMINANT_1_VALUE_D65 = 21;
    public static final int CALIBRATION_ILLUMINANT_1_VALUE_D75 = 22;
    public static final int CALIBRATION_ILLUMINANT_1_VALUE_D50 = 23;
    public static final int CALIBRATION_ILLUMINANT_1_VALUE_ISO_STUDIO_TUNGSTEN = 24;
    public static final int CALIBRATION_ILLUMINANT_1_VALUE_OTHER = 255;
    public static final TagInfoShort EXIF_TAG_CALIBRATION_ILLUMINANT_2;
    public static final int CALIBRATION_ILLUMINANT_2_VALUE_DAYLIGHT = 1;
    public static final int CALIBRATION_ILLUMINANT_2_VALUE_FLUORESCENT = 2;
    public static final int CALIBRATION_ILLUMINANT_2_VALUE_TUNGSTEN = 3;
    public static final int CALIBRATION_ILLUMINANT_2_VALUE_FLASH = 4;
    public static final int CALIBRATION_ILLUMINANT_2_VALUE_FINE_WEATHER = 9;
    public static final int CALIBRATION_ILLUMINANT_2_VALUE_CLOUDY = 10;
    public static final int CALIBRATION_ILLUMINANT_2_VALUE_SHADE = 11;
    public static final int CALIBRATION_ILLUMINANT_2_VALUE_DAYLIGHT_FLUORESCENT = 12;
    public static final int CALIBRATION_ILLUMINANT_2_VALUE_DAY_WHITE_FLUORESCENT = 13;
    public static final int CALIBRATION_ILLUMINANT_2_VALUE_COOL_WHITE_FLUORESCENT = 14;
    public static final int CALIBRATION_ILLUMINANT_2_VALUE_WHITE_FLUORESCENT = 15;
    public static final int CALIBRATION_ILLUMINANT_2_VALUE_STANDARD_LIGHT_A = 17;
    public static final int CALIBRATION_ILLUMINANT_2_VALUE_STANDARD_LIGHT_B = 18;
    public static final int CALIBRATION_ILLUMINANT_2_VALUE_STANDARD_LIGHT_C = 19;
    public static final int CALIBRATION_ILLUMINANT_2_VALUE_D55 = 20;
    public static final int CALIBRATION_ILLUMINANT_2_VALUE_D65 = 21;
    public static final int CALIBRATION_ILLUMINANT_2_VALUE_D75 = 22;
    public static final int CALIBRATION_ILLUMINANT_2_VALUE_D50 = 23;
    public static final int CALIBRATION_ILLUMINANT_2_VALUE_ISO_STUDIO_TUNGSTEN = 24;
    public static final int CALIBRATION_ILLUMINANT_2_VALUE_OTHER = 255;
    public static final TagInfoRational EXIF_TAG_BEST_QUALITY_SCALE;
    public static final TagInfoBytes EXIF_TAG_RAW_DATA_UNIQUE_ID;
    public static final TagInfoAsciiOrByte EXIF_TAG_ORIGINAL_RAW_FILE_NAME;
    public static final TagInfoUndefineds EXIF_TAG_ORIGINAL_RAW_FILE_DATA;
    public static final TagInfoShortOrLong EXIF_TAG_ACTIVE_AREA;
    public static final TagInfoShortOrLong EXIF_TAG_MASKED_AREAS;
    public static final TagInfoUndefineds EXIF_TAG_AS_SHOT_ICCPROFILE;
    public static final TagInfoSRationals EXIF_TAG_AS_SHOT_PRE_PROFILE_MATRIX;
    public static final TagInfoUndefineds EXIF_TAG_CURRENT_ICCPROFILE;
    public static final TagInfoSRationals EXIF_TAG_CURRENT_PRE_PROFILE_MATRIX;
    public static final TagInfoShort EXIF_TAG_COLORIMETRIC_REFERENCE;
    public static final short COLORIMETRIC_REFERENCE_VALUE_SCENE_REFERRED = 0;
    public static final short COLORIMETRIC_REFERENCE_VALUE_OUTPUT_REFERRED = 1;
    public static final TagInfoAsciiOrByte EXIF_TAG_CAMERA_CALIBRATION_SIGNATURE;
    public static final TagInfoAsciiOrByte EXIF_TAG_PROFILE_CALIBRATION_SIGNATURE;
    public static final TagInfoLongs EXIF_TAG_EXTRA_CAMERA_PROFILES;
    public static final TagInfoAsciiOrByte EXIF_TAG_AS_SHOT_PROFILE_NAME;
    public static final TagInfoRational EXIF_TAG_NOISE_REDUCTION_APPLIED;
    public static final TagInfoAscii EXIF_TAG_PROFILE_NAME;
    public static final TagInfoLongs EXIF_TAG_PROFILE_HUE_SAT_MAP_DIMS;
    public static final TagInfoFloats EXIF_TAG_PROFILE_HUE_SAT_MAP_DATA1;
    public static final TagInfoFloats EXIF_TAG_PROFILE_HUE_SAT_MAP_DATA2;
    public static final TagInfoFloats EXIF_TAG_PROFILE_TONE_CURVE;
    public static final TagInfoLong EXIF_TAG_PROFILE_EMBED_POLICY;
    public static final int PROFILE_EMBED_POLICY_VALUE_ALLOW_COPYING = 0;
    public static final int PROFILE_EMBED_POLICY_VALUE_EMBED_IF_USED = 1;
    public static final int PROFILE_EMBED_POLICY_VALUE_EMBED_NEVER = 2;
    public static final int PROFILE_EMBED_POLICY_VALUE_NO_RESTRICTIONS = 3;
    public static final TagInfoAsciiOrByte EXIF_TAG_PROFILE_COPYRIGHT;
    public static final TagInfoSRationals EXIF_TAG_FORWARD_MATRIX1;
    public static final TagInfoSRationals EXIF_TAG_FORWARD_MATRIX2;
    public static final TagInfoAsciiOrByte EXIF_TAG_PREVIEW_APPLICATION_NAME;
    public static final TagInfoAsciiOrByte EXIF_TAG_PREVIEW_APPLICATION_VERSION;
    public static final TagInfoAsciiOrByte EXIF_TAG_PREVIEW_SETTINGS_NAME;
    public static final TagInfoBytes EXIF_TAG_PREVIEW_SETTINGS_DIGEST;
    public static final TagInfoLong EXIF_TAG_PREVIEW_COLORSPACE;
    public static final int PREVIEW_COLORSPACE_VALUE_UNKNOWN = 0;
    public static final int PREVIEW_COLORSPACE_VALUE_GRAY_GAMMA_2_2 = 1;
    public static final int PREVIEW_COLORSPACE_VALUE_sRGB = 2;
    public static final int PREVIEW_COLORSPACE_VALUE_ADOBE_RGB = 3;
    public static final int PREVIEW_COLORSPACE_VALUE_PROPHOTO_RGB = 4;
    public static final TagInfoAscii EXIF_TAG_PREVIEW_DATE_TIME;
    public static final TagInfoBytes EXIF_TAG_RAW_IMAGE_DIGEST;
    public static final TagInfoBytes EXIF_TAG_ORIGINAL_RAW_FILE_DIGEST;
    public static final TagInfoShortOrLong EXIF_TAG_SUB_TILE_BLOCK_SIZE;
    public static final TagInfoShortOrLong EXIF_TAG_ROW_INTERLEAVE_FACTOR;
    public static final TagInfoLongs EXIF_TAG_PROFILE_LOOK_TABLE_DIMS;
    public static final TagInfoFloats EXIF_TAG_PROFILE_LOOK_TABLE_DATA;
    public static final TagInfoUndefineds EXIF_TAG_OPCODE_LIST_1;
    public static final TagInfoUndefineds EXIF_TAG_OPCODE_LIST_2;
    public static final TagInfoUndefineds EXIF_TAG_OPCODE_LIST_3;
    public static final TagInfoDoubles EXIF_TAG_NOISE_PROFILE;
    public static final List<TagInfo> ALL_DNG_TAGS;
    
    private DngTagConstants() {
    }
    
    static {
        EXIF_TAG_DNG_VERSION = new TagInfoBytes("DNGVersion", 50706, 4, TiffDirectoryType.EXIF_DIRECTORY_IFD0);
        EXIF_TAG_DNG_BACKWARD_VERSION = new TagInfoBytes("DNGBackwardVersion", 50707, 4, TiffDirectoryType.EXIF_DIRECTORY_IFD0);
        EXIF_TAG_UNIQUE_CAMERA_MODEL = new TagInfoAscii("UniqueCameraModel", 50708, -1, TiffDirectoryType.EXIF_DIRECTORY_IFD0);
        EXIF_TAG_LOCALIZED_CAMERA_MODEL = new TagInfoAsciiOrByte("LocalizedCameraModel", 50709, -1, TiffDirectoryType.EXIF_DIRECTORY_IFD0);
        EXIF_TAG_CFAPLANE_COLOR = new TagInfoBytes("CFAPlaneColor", 50710, -1, TiffDirectoryType.EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_CFALAYOUT = new TagInfoShort("CFALayout", 50711, TiffDirectoryType.EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_LINEARIZATION_TABLE = new TagInfoShorts("LinearizationTable", 50712, -1, TiffDirectoryType.EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_BLACK_LEVEL_REPEAT_DIM = new TagInfoShorts("BlackLevelRepeatDim", 50713, 2, TiffDirectoryType.EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_BLACK_LEVEL = new TagInfoShortOrLongOrRational("BlackLevel", 50714, -1, TiffDirectoryType.EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_BLACK_LEVEL_DELTA_H = new TagInfoSRationals("BlackLevelDeltaH", 50715, -1, TiffDirectoryType.EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_BLACK_LEVEL_DELTA_V = new TagInfoSRationals("BlackLevelDeltaV", 50716, -1, TiffDirectoryType.EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_WHITE_LEVEL = new TagInfoShortOrLong("WhiteLevel", 50717, -1, TiffDirectoryType.EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_DEFAULT_SCALE = new TagInfoRationals("DefaultScale", 50718, 2, TiffDirectoryType.EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_DEFAULT_CROP_ORIGIN = new TagInfoShortOrLongOrRational("DefaultCropOrigin", 50719, 2, TiffDirectoryType.EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_DEFAULT_CROP_SIZE = new TagInfoShortOrLongOrRational("DefaultCropSize", 50720, 2, TiffDirectoryType.EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_COLOR_MATRIX_1 = new TagInfoSRationals("ColorMatrix1", 50721, -1, TiffDirectoryType.EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_COLOR_MATRIX_2 = new TagInfoSRationals("ColorMatrix2", 50722, -1, TiffDirectoryType.EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_CAMERA_CALIBRATION_1 = new TagInfoSRationals("CameraCalibration1", 50723, -1, TiffDirectoryType.EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_CAMERA_CALIBRATION_2 = new TagInfoSRationals("CameraCalibration2", 50724, -1, TiffDirectoryType.EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_REDUCTION_MATRIX_1 = new TagInfoSRationals("ReductionMatrix1", 50725, -1, TiffDirectoryType.EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_REDUCTION_MATRIX_2 = new TagInfoSRationals("ReductionMatrix2", 50726, -1, TiffDirectoryType.EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_ANALOG_BALANCE = new TagInfoRationals("AnalogBalance", 50727, -1, TiffDirectoryType.EXIF_DIRECTORY_IFD0);
        EXIF_TAG_AS_SHOT_NEUTRAL = new TagInfoShortOrRational("AsShotNeutral", 50728, -1, TiffDirectoryType.EXIF_DIRECTORY_IFD0);
        EXIF_TAG_AS_SHOT_WHITE_XY = new TagInfoRationals("AsShotWhiteXY", 50729, 2, TiffDirectoryType.EXIF_DIRECTORY_IFD0);
        EXIF_TAG_BASELINE_EXPOSURE = new TagInfoSRational("BaselineExposure", 50730, TiffDirectoryType.EXIF_DIRECTORY_IFD0);
        EXIF_TAG_BASELINE_NOISE = new TagInfoRational("BaselineNoise", 50731, TiffDirectoryType.EXIF_DIRECTORY_IFD0);
        EXIF_TAG_BASELINE_SHARPNESS = new TagInfoRational("BaselineSharpness", 50732, TiffDirectoryType.EXIF_DIRECTORY_IFD0);
        EXIF_TAG_BAYER_GREEN_SPLIT = new TagInfoLong("BayerGreenSplit", 50733, TiffDirectoryType.EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_LINEAR_RESPONSE_LIMIT = new TagInfoRational("LinearResponseLimit", 50734, TiffDirectoryType.EXIF_DIRECTORY_IFD0);
        EXIF_TAG_CAMERA_SERIAL_NUMBER = new TagInfoAscii("CameraSerialNumber", 50735, -1, TiffDirectoryType.EXIF_DIRECTORY_IFD0);
        EXIF_TAG_DNG_LENS_INFO = new TagInfoRationals("DNGLensInfo", 50736, 4, TiffDirectoryType.EXIF_DIRECTORY_IFD0);
        EXIF_TAG_CHROMA_BLUR_RADIUS = new TagInfoRational("ChromaBlurRadius", 50737, TiffDirectoryType.EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_ANTI_ALIAS_STRENGTH = new TagInfoRational("AntiAliasStrength", 50738, TiffDirectoryType.EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_SHADOW_SCALE = new TagInfoRational("ShadowScale", 50739, TiffDirectoryType.EXIF_DIRECTORY_IFD0);
        EXIF_TAG_DNG_PRIVATE_DATA = new TagInfoBytes("DNGPrivateData", 50740, -1, TiffDirectoryType.EXIF_DIRECTORY_IFD0);
        EXIF_TAG_MAKER_NOTE_SAFETY = new TagInfoShort("MakerNoteSafety", 50741, TiffDirectoryType.EXIF_DIRECTORY_IFD0);
        EXIF_TAG_CALIBRATION_ILLUMINANT_1 = new TagInfoShort("CalibrationIlluminant1", 50778, TiffDirectoryType.EXIF_DIRECTORY_IFD0);
        EXIF_TAG_CALIBRATION_ILLUMINANT_2 = new TagInfoShort("CalibrationIlluminant2", 50779, TiffDirectoryType.EXIF_DIRECTORY_IFD0);
        EXIF_TAG_BEST_QUALITY_SCALE = new TagInfoRational("BestQualityScale", 50780, TiffDirectoryType.EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_RAW_DATA_UNIQUE_ID = new TagInfoBytes("RawDataUniqueID", 50781, 16, TiffDirectoryType.EXIF_DIRECTORY_IFD0);
        EXIF_TAG_ORIGINAL_RAW_FILE_NAME = new TagInfoAsciiOrByte("OriginalRawFileName", 50827, -1, TiffDirectoryType.EXIF_DIRECTORY_IFD0);
        EXIF_TAG_ORIGINAL_RAW_FILE_DATA = new TagInfoUndefineds("OriginalRawFileData", 50828, -1, TiffDirectoryType.EXIF_DIRECTORY_IFD0);
        EXIF_TAG_ACTIVE_AREA = new TagInfoShortOrLong("ActiveArea", 50829, 4, TiffDirectoryType.EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_MASKED_AREAS = new TagInfoShortOrLong("MaskedAreas", 50830, 4, TiffDirectoryType.EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_AS_SHOT_ICCPROFILE = new TagInfoUndefineds("AsShotICCProfile", 50831, -1, TiffDirectoryType.EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_AS_SHOT_PRE_PROFILE_MATRIX = new TagInfoSRationals("AsShotPreProfileMatrix", 50832, -1, TiffDirectoryType.EXIF_DIRECTORY_IFD0);
        EXIF_TAG_CURRENT_ICCPROFILE = new TagInfoUndefineds("CurrentICCProfile", 50833, -1, TiffDirectoryType.EXIF_DIRECTORY_IFD0);
        EXIF_TAG_CURRENT_PRE_PROFILE_MATRIX = new TagInfoSRationals("CurrentPreProfileMatrix", 50834, -1, TiffDirectoryType.EXIF_DIRECTORY_IFD0);
        EXIF_TAG_COLORIMETRIC_REFERENCE = new TagInfoShort("ColorimetricReference", 50879, TiffDirectoryType.EXIF_DIRECTORY_IFD0);
        EXIF_TAG_CAMERA_CALIBRATION_SIGNATURE = new TagInfoAsciiOrByte("CameraCalibrationSignature", 50931, -1, TiffDirectoryType.EXIF_DIRECTORY_IFD0);
        EXIF_TAG_PROFILE_CALIBRATION_SIGNATURE = new TagInfoAsciiOrByte("ProfileCalibrationSignature", 50932, -1, TiffDirectoryType.EXIF_DIRECTORY_IFD0);
        EXIF_TAG_EXTRA_CAMERA_PROFILES = new TagInfoLongs("ExtraCameraProfiles", 50933, -1, TiffDirectoryType.EXIF_DIRECTORY_IFD0);
        EXIF_TAG_AS_SHOT_PROFILE_NAME = new TagInfoAsciiOrByte("AsShotProfileName", 50934, -1, TiffDirectoryType.EXIF_DIRECTORY_IFD0);
        EXIF_TAG_NOISE_REDUCTION_APPLIED = new TagInfoRational("NoiseReductionApplied", 50935, TiffDirectoryType.EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_PROFILE_NAME = new TagInfoAscii("ProfileName", 50936, -1, TiffDirectoryType.EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_PROFILE_HUE_SAT_MAP_DIMS = new TagInfoLongs("ProfileHueSatMapDims", 50937, 3, TiffDirectoryType.EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_PROFILE_HUE_SAT_MAP_DATA1 = new TagInfoFloats("ProfileHueSatMapData1", 50938, -1, TiffDirectoryType.EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_PROFILE_HUE_SAT_MAP_DATA2 = new TagInfoFloats("ProfileHueSatMapData2", 50939, -1, TiffDirectoryType.EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_PROFILE_TONE_CURVE = new TagInfoFloats("ProfileToneCurve", 50940, -1, TiffDirectoryType.EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_PROFILE_EMBED_POLICY = new TagInfoLong("ProfileEmbedPolicy", 50941, TiffDirectoryType.EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_PROFILE_COPYRIGHT = new TagInfoAsciiOrByte("ProfileCopyright", 50942, -1, TiffDirectoryType.EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_FORWARD_MATRIX1 = new TagInfoSRationals("ForwardMatrix1", 50964, -1, TiffDirectoryType.EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_FORWARD_MATRIX2 = new TagInfoSRationals("ForwardMatrix2", 50965, -1, TiffDirectoryType.EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_PREVIEW_APPLICATION_NAME = new TagInfoAsciiOrByte("PreviewApplicationName", 50966, -1, TiffDirectoryType.EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_PREVIEW_APPLICATION_VERSION = new TagInfoAsciiOrByte("PreviewApplicationVersion", 50967, -1, TiffDirectoryType.EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_PREVIEW_SETTINGS_NAME = new TagInfoAsciiOrByte("PreviewSettingsName", 50968, -1, TiffDirectoryType.EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_PREVIEW_SETTINGS_DIGEST = new TagInfoBytes("PreviewSettingsDigest", 50969, 16, TiffDirectoryType.EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_PREVIEW_COLORSPACE = new TagInfoLong("PreviewColorspace", 50970, TiffDirectoryType.EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_PREVIEW_DATE_TIME = new TagInfoAscii("PreviewDateTime", 50971, -1, TiffDirectoryType.EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_RAW_IMAGE_DIGEST = new TagInfoBytes("RawImageDigest", 50972, 16, TiffDirectoryType.EXIF_DIRECTORY_IFD0);
        EXIF_TAG_ORIGINAL_RAW_FILE_DIGEST = new TagInfoBytes("OriginalRawFileDigest", 50973, 16, TiffDirectoryType.EXIF_DIRECTORY_IFD0);
        EXIF_TAG_SUB_TILE_BLOCK_SIZE = new TagInfoShortOrLong("SubTileBlockSize", 50974, 2, TiffDirectoryType.EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_ROW_INTERLEAVE_FACTOR = new TagInfoShortOrLong("RowInterleaveFactor", 50975, 1, TiffDirectoryType.EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_PROFILE_LOOK_TABLE_DIMS = new TagInfoLongs("ProfileLookTableDims", 50981, 3, TiffDirectoryType.EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_PROFILE_LOOK_TABLE_DATA = new TagInfoFloats("ProfileLookTableData", 50982, -1, TiffDirectoryType.EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_OPCODE_LIST_1 = new TagInfoUndefineds("OpcodeList1", 51008, -1, TiffDirectoryType.EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_OPCODE_LIST_2 = new TagInfoUndefineds("OpcodeList2", 51009, -1, TiffDirectoryType.EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_OPCODE_LIST_3 = new TagInfoUndefineds("OpcodeList3", 51022, -1, TiffDirectoryType.EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_NOISE_PROFILE = new TagInfoDoubles("NoiseProfile", 51041, -1, TiffDirectoryType.EXIF_DIRECTORY_UNKNOWN);
        ALL_DNG_TAGS = Collections.unmodifiableList((List<? extends TagInfo>)Arrays.asList(DngTagConstants.EXIF_TAG_DNG_VERSION, DngTagConstants.EXIF_TAG_DNG_BACKWARD_VERSION, DngTagConstants.EXIF_TAG_UNIQUE_CAMERA_MODEL, DngTagConstants.EXIF_TAG_LOCALIZED_CAMERA_MODEL, DngTagConstants.EXIF_TAG_CFAPLANE_COLOR, DngTagConstants.EXIF_TAG_CFALAYOUT, DngTagConstants.EXIF_TAG_LINEARIZATION_TABLE, DngTagConstants.EXIF_TAG_BLACK_LEVEL_REPEAT_DIM, DngTagConstants.EXIF_TAG_BLACK_LEVEL, DngTagConstants.EXIF_TAG_BLACK_LEVEL_DELTA_H, DngTagConstants.EXIF_TAG_BLACK_LEVEL_DELTA_V, DngTagConstants.EXIF_TAG_WHITE_LEVEL, DngTagConstants.EXIF_TAG_DEFAULT_SCALE, DngTagConstants.EXIF_TAG_DEFAULT_CROP_ORIGIN, DngTagConstants.EXIF_TAG_DEFAULT_CROP_SIZE, DngTagConstants.EXIF_TAG_COLOR_MATRIX_1, DngTagConstants.EXIF_TAG_COLOR_MATRIX_2, DngTagConstants.EXIF_TAG_CAMERA_CALIBRATION_1, DngTagConstants.EXIF_TAG_CAMERA_CALIBRATION_2, DngTagConstants.EXIF_TAG_REDUCTION_MATRIX_1, DngTagConstants.EXIF_TAG_REDUCTION_MATRIX_2, DngTagConstants.EXIF_TAG_ANALOG_BALANCE, DngTagConstants.EXIF_TAG_AS_SHOT_NEUTRAL, DngTagConstants.EXIF_TAG_AS_SHOT_WHITE_XY, DngTagConstants.EXIF_TAG_BASELINE_EXPOSURE, DngTagConstants.EXIF_TAG_BASELINE_NOISE, DngTagConstants.EXIF_TAG_BASELINE_SHARPNESS, DngTagConstants.EXIF_TAG_BAYER_GREEN_SPLIT, DngTagConstants.EXIF_TAG_LINEAR_RESPONSE_LIMIT, DngTagConstants.EXIF_TAG_CAMERA_SERIAL_NUMBER, DngTagConstants.EXIF_TAG_DNG_LENS_INFO, DngTagConstants.EXIF_TAG_CHROMA_BLUR_RADIUS, DngTagConstants.EXIF_TAG_ANTI_ALIAS_STRENGTH, DngTagConstants.EXIF_TAG_SHADOW_SCALE, DngTagConstants.EXIF_TAG_DNG_PRIVATE_DATA, DngTagConstants.EXIF_TAG_MAKER_NOTE_SAFETY, DngTagConstants.EXIF_TAG_CALIBRATION_ILLUMINANT_1, DngTagConstants.EXIF_TAG_CALIBRATION_ILLUMINANT_2, DngTagConstants.EXIF_TAG_BEST_QUALITY_SCALE, DngTagConstants.EXIF_TAG_RAW_DATA_UNIQUE_ID, DngTagConstants.EXIF_TAG_ORIGINAL_RAW_FILE_NAME, DngTagConstants.EXIF_TAG_ORIGINAL_RAW_FILE_DATA, DngTagConstants.EXIF_TAG_ACTIVE_AREA, DngTagConstants.EXIF_TAG_MASKED_AREAS, DngTagConstants.EXIF_TAG_AS_SHOT_ICCPROFILE, DngTagConstants.EXIF_TAG_AS_SHOT_PRE_PROFILE_MATRIX, DngTagConstants.EXIF_TAG_CURRENT_ICCPROFILE, DngTagConstants.EXIF_TAG_CURRENT_PRE_PROFILE_MATRIX, DngTagConstants.EXIF_TAG_COLORIMETRIC_REFERENCE, DngTagConstants.EXIF_TAG_CAMERA_CALIBRATION_SIGNATURE, DngTagConstants.EXIF_TAG_PROFILE_CALIBRATION_SIGNATURE, DngTagConstants.EXIF_TAG_EXTRA_CAMERA_PROFILES, DngTagConstants.EXIF_TAG_AS_SHOT_PROFILE_NAME, DngTagConstants.EXIF_TAG_NOISE_REDUCTION_APPLIED, DngTagConstants.EXIF_TAG_PROFILE_NAME, DngTagConstants.EXIF_TAG_PROFILE_HUE_SAT_MAP_DIMS, DngTagConstants.EXIF_TAG_PROFILE_HUE_SAT_MAP_DATA1, DngTagConstants.EXIF_TAG_PROFILE_HUE_SAT_MAP_DATA2, DngTagConstants.EXIF_TAG_PROFILE_TONE_CURVE, DngTagConstants.EXIF_TAG_PROFILE_EMBED_POLICY, DngTagConstants.EXIF_TAG_PROFILE_COPYRIGHT, DngTagConstants.EXIF_TAG_FORWARD_MATRIX1, DngTagConstants.EXIF_TAG_FORWARD_MATRIX2, DngTagConstants.EXIF_TAG_PREVIEW_APPLICATION_NAME, DngTagConstants.EXIF_TAG_PREVIEW_APPLICATION_VERSION, DngTagConstants.EXIF_TAG_PREVIEW_SETTINGS_NAME, DngTagConstants.EXIF_TAG_PREVIEW_SETTINGS_DIGEST, DngTagConstants.EXIF_TAG_PREVIEW_COLORSPACE, DngTagConstants.EXIF_TAG_PREVIEW_DATE_TIME, DngTagConstants.EXIF_TAG_RAW_IMAGE_DIGEST, DngTagConstants.EXIF_TAG_ORIGINAL_RAW_FILE_DIGEST, DngTagConstants.EXIF_TAG_SUB_TILE_BLOCK_SIZE, DngTagConstants.EXIF_TAG_ROW_INTERLEAVE_FACTOR, DngTagConstants.EXIF_TAG_PROFILE_LOOK_TABLE_DIMS, DngTagConstants.EXIF_TAG_PROFILE_LOOK_TABLE_DATA, DngTagConstants.EXIF_TAG_OPCODE_LIST_1, DngTagConstants.EXIF_TAG_OPCODE_LIST_2, DngTagConstants.EXIF_TAG_OPCODE_LIST_3, DngTagConstants.EXIF_TAG_NOISE_PROFILE));
    }
}
