/* * SPDX-License-Identifier: AGPL-3.0-or-later * * C Copyright 2023 Regione Piemonte * */

// Generated 25-mar-2015 10.40.31 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Al758Cross generated by hbm2java
 */
@Entity
@Table(name = "AL758_CROSS")
public class Al758Cross implements java.io.Serializable {

	private static final long serialVersionUID = -4815990497988734930L;
	
	private Al758CrossId id;

	public Al758Cross() {
	}

	public Al758Cross(Al758CrossId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "nomeFattura", column = @Column(name = "NOME_FATTURA", nullable = false, length = 50)),
			@AttributeOverride(name = "numeroFattura", column = @Column(name = "NUMERO_FATTURA", length = 50)),
			@AttributeOverride(name = "codiceCommessa", column = @Column(name = "CODICE_COMMESSA", length = 50)),
			@AttributeOverride(name = "cig", column = @Column(name = "CIG", length = 50)) })
	public Al758CrossId getId() {
		return this.id;
	}

	public void setId(Al758CrossId id) {
		this.id = id;
	}

}
