/* * SPDX-License-Identifier: AGPL-3.0-or-later * * C Copyright 2023 Regione Piemonte * */
// Generated 3-giu-2015 10.18.55 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * DmtDocumentiLotto generated by hbm2java
 */
@Entity
@Table(name = "DMT_DOCUMENTI_LOTTO")
public class DmtDocumentiLotto implements java.io.Serializable {

	private static final long serialVersionUID = 4821957385576027138L;

	private DmtDocumentiLottoId id;

	private DmtLottiDocumenti dmtLottiDocumenti;

	private BigDecimal idDoc;

	private Long nroDocumento;

	private Date tsDocumento;

	private Date tsPubblicazione;

	private String codStato;

	private Date tsLastUpdStato;

	private String note;

	private BigDecimal idUd;

	private Boolean flgHidden;

	private Boolean flgLocked;

	private Boolean flgAnn;

	private Date tsIns;

	private BigDecimal idUserIns;

	private Date tsLastUpd;

	private BigDecimal idUserLastUpd;

	public DmtDocumentiLotto() {
	}

	public DmtDocumentiLotto(DmtDocumentiLottoId id, DmtLottiDocumenti dmtLottiDocumenti, Long nroDocumento) {
		this.id = id;
		this.dmtLottiDocumenti = dmtLottiDocumenti;
		this.nroDocumento = nroDocumento;
	}

	public DmtDocumentiLotto(DmtDocumentiLottoId id, DmtLottiDocumenti dmtLottiDocumenti, BigDecimal idDoc, Long nroDocumento,
			Date tsDocumento, Date tsPubblicazione, String codStato, Date tsLastUpdStato, String note, BigDecimal idUd, Boolean flgHidden,
			Boolean flgLocked, Boolean flgAnn, Date tsIns, BigDecimal idUserIns, Date tsLastUpd, BigDecimal idUserLastUpd) {
		this.id = id;
		this.dmtLottiDocumenti = dmtLottiDocumenti;
		this.idDoc = idDoc;
		this.nroDocumento = nroDocumento;
		this.tsDocumento = tsDocumento;
		this.tsPubblicazione = tsPubblicazione;
		this.codStato = codStato;
		this.tsLastUpdStato = tsLastUpdStato;
		this.note = note;
		this.idUd = idUd;
		this.flgHidden = flgHidden;
		this.flgLocked = flgLocked;
		this.flgAnn = flgAnn;
		this.tsIns = tsIns;
		this.idUserIns = idUserIns;
		this.tsLastUpd = tsLastUpd;
		this.idUserLastUpd = idUserLastUpd;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "idLotto", column = @Column(name = "ID_LOTTO", nullable = false, length = 64)),
			@AttributeOverride(name = "idDocLotto", column = @Column(name = "ID_DOC_LOTTO", nullable = false, length = 64)) })
	public DmtDocumentiLottoId getId() {
		return this.id;
	}

	public void setId(DmtDocumentiLottoId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "ID_LOTTO", nullable = false, insertable = false, updatable = false)
	public DmtLottiDocumenti getDmtLottiDocumenti() {
		return this.dmtLottiDocumenti;
	}

	public void setDmtLottiDocumenti(DmtLottiDocumenti dmtLottiDocumenti) {
		this.dmtLottiDocumenti = dmtLottiDocumenti;
	}

	@Column(name = "ID_DOC", precision = 22, scale = 0)
	public BigDecimal getIdDoc() {
		return this.idDoc;
	}

	public void setIdDoc(BigDecimal idDoc) {
		this.idDoc = idDoc;
	}

	@Column(name = "NRO_DOCUMENTO", precision = 10, scale = 0)
	public Long getNroDocumento() {
		return this.nroDocumento;
	}

	public void setNroDocumento(Long nroDocumento) {
		this.nroDocumento = nroDocumento;
	}

	@Column(name = "TS_DOCUMENTO", length = 7)
	public Date getTsDocumento() {
		return this.tsDocumento;
	}

	public void setTsDocumento(Date tsDocumento) {
		this.tsDocumento = tsDocumento;
	}

	@Column(name = "TS_PUBBLICAZIONE", length = 7)
	public Date getTsPubblicazione() {
		return this.tsPubblicazione;
	}

	public void setTsPubblicazione(Date tsPubblicazione) {
		this.tsPubblicazione = tsPubblicazione;
	}

	@Column(name = "COD_STATO", length = 2)
	public String getCodStato() {
		return this.codStato;
	}

	public void setCodStato(String codStato) {
		this.codStato = codStato;
	}

	@Column(name = "TS_LAST_UPD_STATO", length = 7)
	public Date getTsLastUpdStato() {
		return this.tsLastUpdStato;
	}

	public void setTsLastUpdStato(Date tsLastUpdStato) {
		this.tsLastUpdStato = tsLastUpdStato;
	}

	@Column(name = "NOTE", length = 4000)
	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	@Column(name = "ID_UD", precision = 22, scale = 0)
	public BigDecimal getIdUd() {
		return this.idUd;
	}

	public void setIdUd(BigDecimal idUd) {
		this.idUd = idUd;
	}

	@Column(name = "FLG_HIDDEN", precision = 1, scale = 0)
	public Boolean getFlgHidden() {
		return this.flgHidden;
	}

	public void setFlgHidden(Boolean flgHidden) {
		this.flgHidden = flgHidden;
	}

	@Column(name = "FLG_LOCKED", precision = 1, scale = 0)
	public Boolean getFlgLocked() {
		return this.flgLocked;
	}

	public void setFlgLocked(Boolean flgLocked) {
		this.flgLocked = flgLocked;
	}

	@Column(name = "FLG_ANN", precision = 1, scale = 0)
	public Boolean getFlgAnn() {
		return this.flgAnn;
	}

	public void setFlgAnn(Boolean flgAnn) {
		this.flgAnn = flgAnn;
	}

	@Column(name = "TS_INS", length = 7)
	public Date getTsIns() {
		return this.tsIns;
	}

	public void setTsIns(Date tsIns) {
		this.tsIns = tsIns;
	}

	@Column(name = "ID_USER_INS", precision = 22, scale = 0)
	public BigDecimal getIdUserIns() {
		return this.idUserIns;
	}

	public void setIdUserIns(BigDecimal idUserIns) {
		this.idUserIns = idUserIns;
	}

	@Column(name = "TS_LAST_UPD", length = 7)
	public Date getTsLastUpd() {
		return this.tsLastUpd;
	}

	public void setTsLastUpd(Date tsLastUpd) {
		this.tsLastUpd = tsLastUpd;
	}

	@Column(name = "ID_USER_LAST_UPD", precision = 22, scale = 0)
	public BigDecimal getIdUserLastUpd() {
		return this.idUserLastUpd;
	}

	public void setIdUserLastUpd(BigDecimal idUserLastUpd) {
		this.idUserLastUpd = idUserLastUpd;
	}

	@Override
	public String toString() {
		return String
				.format("DmtDocumentiLotto [id=%s, idDoc=%s, nroDocumento=%s, tsDocumento=%s, tsPubblicazione=%s, codStato=%s, tsLastUpdStato=%s, note=%s, idUd=%s, flgHidden=%s, flgLocked=%s, flgAnn=%s, tsIns=%s, idUserIns=%s, tsLastUpd=%s, idUserLastUpd=%s]",
						id, idDoc, nroDocumento, tsDocumento, tsPubblicazione, codStato, tsLastUpdStato, note, idUd, flgHidden, flgLocked,
						flgAnn, tsIns, idUserIns, tsLastUpd, idUserLastUpd);
	}

}
