/* * SPDX-License-Identifier: AGPL-3.0-or-later * * C Copyright 2023 Regione Piemonte * */

// Generated 9-nov-2015 18.18.55 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DmtDocumentiLottoInAttesaId generated by hbm2java
 */
@Embeddable
public class DmtDocumentiLottoInAttesaId implements java.io.Serializable {

	private static final long serialVersionUID = 8920439466715763276L;

	private BigDecimal idSpAoo;

	private String codApplOwner;

	private String codIstApplOwner;

	private String nomeFile;

	public DmtDocumentiLottoInAttesaId() {
	}

	public DmtDocumentiLottoInAttesaId(BigDecimal idSpAoo, String codApplOwner, String codIstApplOwner, String nomeFile) {
		this.idSpAoo = idSpAoo;
		this.codApplOwner = codApplOwner;
		this.codIstApplOwner = codIstApplOwner;
		this.nomeFile = nomeFile;
	}

	@Column(name = "ID_SP_AOO", nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdSpAoo() {
		return this.idSpAoo;
	}

	public void setIdSpAoo(BigDecimal idSpAoo) {
		this.idSpAoo = idSpAoo;
	}

	@Column(name = "COD_APPL_OWNER", nullable = false, length = 30)
	public String getCodApplOwner() {
		return this.codApplOwner;
	}

	public void setCodApplOwner(String codApplOwner) {
		this.codApplOwner = codApplOwner;
	}

	@Column(name = "COD_IST_APPL_OWNER", nullable = false, length = 30)
	public String getCodIstApplOwner() {
		return this.codIstApplOwner;
	}

	public void setCodIstApplOwner(String codIstApplOwner) {
		this.codIstApplOwner = codIstApplOwner;
	}

	@Column(name = "NOME_FILE", nullable = false, length = 256)
	public String getNomeFile() {
		return this.nomeFile;
	}

	public void setNomeFile(String nomeFile) {
		this.nomeFile = nomeFile;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DmtDocumentiLottoInAttesaId))
			return false;
		DmtDocumentiLottoInAttesaId castOther = (DmtDocumentiLottoInAttesaId) other;

		return ((this.getIdSpAoo() == castOther.getIdSpAoo()) || (this.getIdSpAoo() != null && castOther.getIdSpAoo() != null && this
				.getIdSpAoo().equals(castOther.getIdSpAoo())))
				&& ((this.getCodApplOwner() == castOther.getCodApplOwner()) || (this.getCodApplOwner() != null
						&& castOther.getCodApplOwner() != null && this.getCodApplOwner().equals(castOther.getCodApplOwner())))
				&& ((this.getCodIstApplOwner() == castOther.getCodIstApplOwner()) || (this.getCodIstApplOwner() != null
						&& castOther.getCodIstApplOwner() != null && this.getCodIstApplOwner().equals(castOther.getCodIstApplOwner())))
				&& ((this.getNomeFile() == castOther.getNomeFile()) || (this.getNomeFile() != null && castOther.getNomeFile() != null && this
						.getNomeFile().equals(castOther.getNomeFile())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getIdSpAoo() == null ? 0 : this.getIdSpAoo().hashCode());
		result = 37 * result + (getCodApplOwner() == null ? 0 : this.getCodApplOwner().hashCode());
		result = 37 * result + (getCodIstApplOwner() == null ? 0 : this.getCodIstApplOwner().hashCode());
		result = 37 * result + (getNomeFile() == null ? 0 : this.getNomeFile().hashCode());
		return result;
	}

	@Override
	public String toString() {
		return String.format("DmtDocumentiLottoInAttesaId [idSpAoo=%s, codApplOwner=%s, codIstApplOwner=%s, nomeFile=%s]", idSpAoo,
				codApplOwner, codIstApplOwner, nomeFile);
	}

}
