/* * SPDX-License-Identifier: AGPL-3.0-or-later * * C Copyright 2023 Regione Piemonte * */

// Generated 10-nov-2015 17.23.57 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * DmtDocumentiLottoInAttesa generated by hbm2java
 */
@Entity
@Table(name = "DMT_DOCUMENTI_LOTTO_IN_ATTESA", uniqueConstraints = @UniqueConstraint(columnNames = "ID_UD"))
public class DmtDocumentiLottoInAttesa implements java.io.Serializable {

	private static final long serialVersionUID = 3995972367604133567L;

	private DmtDocumentiLottoInAttesaId id;

	private String idLotto;

	private String idDocLotto;

	private String nomeLotto;

	private BigDecimal idUd;

	private BigDecimal idDoc;

	private String sezionale;

	private Short anno;

	private Long nroDocumento;

	private Date tsIns;

	private Date tsLastUpd;

	public DmtDocumentiLottoInAttesa() {
	}

	public DmtDocumentiLottoInAttesa(DmtDocumentiLottoInAttesaId id, 
			String idLotto, String idDocLotto, String nomeLotto, Date tsIns, Date tsLastUpd) {
		this.id = id;
		this.idLotto = idLotto;
		this.idDocLotto = idDocLotto;
		this.nomeLotto = nomeLotto;
		this.tsIns = tsIns;
		this.tsLastUpd = tsLastUpd;
	}

	public DmtDocumentiLottoInAttesa(DmtDocumentiLottoInAttesaId id, 
			String idLotto, String idDocLotto, String nomeLotto, BigDecimal idUd, BigDecimal idDoc, 
			String sezionale, Short anno, Long nroDocumento, 
			Date tsIns, Date tsLastUpd) {
		this.id = id;
		this.idLotto = idLotto;
		this.idDocLotto = idDocLotto;
		this.nomeLotto = nomeLotto;
		this.idUd = idUd;
		this.idDoc = idDoc;
		this.sezionale = sezionale;
		this.anno = anno;
		this.nroDocumento = nroDocumento;
		this.tsIns = tsIns;
		this.tsLastUpd = tsLastUpd;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "idSpAoo", column = @Column(name = "ID_SP_AOO", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "codApplOwner", column = @Column(name = "COD_APPL_OWNER", nullable = false, length = 30)),
			@AttributeOverride(name = "codIstApplOwner", column = @Column(name = "COD_IST_APPL_OWNER", nullable = false, length = 30)),
			@AttributeOverride(name = "nomeFile", column = @Column(name = "NOME_FILE", nullable = false, length = 256)) })
	public DmtDocumentiLottoInAttesaId getId() {
		return this.id;
	}

	public void setId(DmtDocumentiLottoInAttesaId id) {
		this.id = id;
	}

	@Column(name = "ID_LOTTO", nullable = false, length = 64)
	public String getIdLotto() {
		return this.idLotto;
	}

	public void setIdLotto(String idLotto) {
		this.idLotto = idLotto;
	}

	@Column(name = "ID_DOC_LOTTO", length = 64)
	public String getIdDocLotto() {
		return this.idDocLotto;
	}

	public void setIdDocLotto(String idDocLotto) {
		this.idDocLotto = idDocLotto;
	}

	@Column(name = "NOME_LOTTO", length = 250)
	public String getNomeLotto() {
		return this.nomeLotto;
	}

	public void setNomeLotto(String nomeLotto) {
		this.nomeLotto = nomeLotto;
	}

	@Column(name = "ID_UD", unique = true, precision = 22, scale = 0)
	public BigDecimal getIdUd() {
		return this.idUd;
	}

	public void setIdUd(BigDecimal idUd) {
		this.idUd = idUd;
	}

	@Column(name = "ID_DOC", unique = true, precision = 22, scale = 0)
	public BigDecimal getIdDoc() {
		return this.idDoc;
	}

	public void setIdDoc(BigDecimal idDoc) {
		this.idDoc = idDoc;
	}

	@Column(name = "SEZIONALE", length = 30)
	public String getSezionale() {
		return this.sezionale;
	}

	public void setSezionale(String sezionale) {
		this.sezionale = sezionale;
	}

	@Column(name = "ANNO", precision = 4, scale = 0)
	public Short getAnno() {
		return this.anno;
	}

	public void setAnno(Short anno) {
		this.anno = anno;
	}

	@Column(name = "NRO_DOCUMENTO", precision = 10, scale = 0)
	public Long getNroDocumento() {
		return this.nroDocumento;
	}

	public void setNroDocumento(Long nroDocumento) {
		this.nroDocumento = nroDocumento;
	}

	@Column(name = "TS_INS", nullable = false, length = 7)
	public Date getTsIns() {
		return this.tsIns;
	}

	public void setTsIns(Date tsIns) {
		this.tsIns = tsIns;
	}

	@Column(name = "TS_LAST_UPD", nullable = false, length = 7)
	public Date getTsLastUpd() {
		return this.tsLastUpd;
	}

	public void setTsLastUpd(Date tsLastUpd) {
		this.tsLastUpd = tsLastUpd;
	}

	@Override
	public String toString() {
		return String
				.format("DmtDocumentiLottoInAttesa [id=%s, idLotto=%s, idDocLotto=%s, nomeLotto=%s, idUd=%s, idDoc=%s, sezionale=%s, anno=%s, nroDocumento=%s, tsIns=%s, tsLastUpd=%s]",
						id, idLotto, idDocLotto, nomeLotto, idUd, idDoc, sezionale, anno, nroDocumento, tsIns, tsLastUpd);
	}

}
