/* * SPDX-License-Identifier: AGPL-3.0-or-later * * C Copyright 2023 Regione Piemonte * */

// Generated 7-apr-2015 9.45.30 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * DmtUsers generated by hbm2java
 */
@Entity
@Table(name = "DMT_USERS", uniqueConstraints = { @UniqueConstraint(columnNames = "INFO_STORICO"),
		@UniqueConstraint(columnNames = "USERNAME"), @UniqueConstraint(columnNames = "DELEGHE"),
		@UniqueConstraint(columnNames = "REL_STRUTT_ORG"), @UniqueConstraint(columnNames = "DOMINI_AUT"),
		@UniqueConstraint(columnNames = "ALTRI_ATTRIBUTI"), @UniqueConstraint(columnNames = "ACL_PREDEFINITE"),
		@UniqueConstraint(columnNames = "CREDENZ_AUT_EXT"), @UniqueConstraint(columnNames = "OLD_PASSWORDS") })
public class DmtUsers implements java.io.Serializable {

	private static final long serialVersionUID = -7397830026074655650L;

	private BigDecimal idUser;

	private BigDecimal idSpAoo;

	private String desUser;

	private String username;

	private String password;

	private Date dtInizioVld;

	private Date dtFineVld;

	private Date dominiAut;

	private BigDecimal idUserInRubrica;

	private Date relStruttOrg;

	private Date deleghe;

	private Date oldPasswords;

	private String EMail;

	private String qualifica;

	private String nroMatricola;

	private String titolo;

	private Boolean flgNoAccSis;

	private Date credenzAutExt;

	private Date aclPredefinite;

	private Date altriAttributi;

	private Date infoStorico;

	private String codRapido;

	private String provCiUser;

	private Boolean flgLocked;

	private Date tsIns;

	private BigDecimal idUserIns;

	private Date tsLastUpd;

	private BigDecimal idUserLastUpd;

	public DmtUsers() {
	}

	public DmtUsers(BigDecimal idUser, String desUser, String username) {
		this.idUser = idUser;
		this.desUser = desUser;
		this.username = username;
	}

	public DmtUsers(BigDecimal idUser, BigDecimal idSpAoo, String desUser, String username, String password, Date dtInizioVld,
			Date dtFineVld, Date dominiAut, BigDecimal idUserInRubrica, Date relStruttOrg, Date deleghe, Date oldPasswords, String EMail,
			String qualifica, String nroMatricola, String titolo, Boolean flgNoAccSis, Date credenzAutExt, Date aclPredefinite,
			Date altriAttributi, Date infoStorico, String codRapido, String provCiUser, Boolean flgLocked, Date tsIns,
			BigDecimal idUserIns, Date tsLastUpd, BigDecimal idUserLastUpd) {
		this.idUser = idUser;
		this.idSpAoo = idSpAoo;
		this.desUser = desUser;
		this.username = username;
		this.password = password;
		this.dtInizioVld = dtInizioVld;
		this.dtFineVld = dtFineVld;
		this.dominiAut = dominiAut;
		this.idUserInRubrica = idUserInRubrica;
		this.relStruttOrg = relStruttOrg;
		this.deleghe = deleghe;
		this.oldPasswords = oldPasswords;
		this.EMail = EMail;
		this.qualifica = qualifica;
		this.nroMatricola = nroMatricola;
		this.titolo = titolo;
		this.flgNoAccSis = flgNoAccSis;
		this.credenzAutExt = credenzAutExt;
		this.aclPredefinite = aclPredefinite;
		this.altriAttributi = altriAttributi;
		this.infoStorico = infoStorico;
		this.codRapido = codRapido;
		this.provCiUser = provCiUser;
		this.flgLocked = flgLocked;
		this.tsIns = tsIns;
		this.idUserIns = idUserIns;
		this.tsLastUpd = tsLastUpd;
		this.idUserLastUpd = idUserLastUpd;
	}

	@Id
	@Column(name = "ID_USER", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdUser() {
		return this.idUser;
	}

	public void setIdUser(BigDecimal idUser) {
		this.idUser = idUser;
	}

	@Column(name = "ID_SP_AOO", precision = 22, scale = 0)
	public BigDecimal getIdSpAoo() {
		return this.idSpAoo;
	}

	public void setIdSpAoo(BigDecimal idSpAoo) {
		this.idSpAoo = idSpAoo;
	}

	@Column(name = "DES_USER", nullable = false, length = 150)
	public String getDesUser() {
		return this.desUser;
	}

	public void setDesUser(String desUser) {
		this.desUser = desUser;
	}

	@Column(name = "USERNAME", unique = true, nullable = false, length = 30)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "PASSWORD", length = 30)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "DT_INIZIO_VLD", length = 7)
	public Date getDtInizioVld() {
		return this.dtInizioVld;
	}

	public void setDtInizioVld(Date dtInizioVld) {
		this.dtInizioVld = dtInizioVld;
	}

	@Column(name = "DT_FINE_VLD", length = 7)
	public Date getDtFineVld() {
		return this.dtFineVld;
	}

	public void setDtFineVld(Date dtFineVld) {
		this.dtFineVld = dtFineVld;
	}

	@Column(name = "DOMINI_AUT", unique = true)
	public Date getDominiAut() {
		return this.dominiAut;
	}

	public void setDominiAut(Date dominiAut) {
		this.dominiAut = dominiAut;
	}

	@Column(name = "ID_USER_IN_RUBRICA", precision = 22, scale = 0)
	public BigDecimal getIdUserInRubrica() {
		return this.idUserInRubrica;
	}

	public void setIdUserInRubrica(BigDecimal idUserInRubrica) {
		this.idUserInRubrica = idUserInRubrica;
	}

	@Column(name = "REL_STRUTT_ORG", unique = true)
	public Date getRelStruttOrg() {
		return this.relStruttOrg;
	}

	public void setRelStruttOrg(Date relStruttOrg) {
		this.relStruttOrg = relStruttOrg;
	}

	@Column(name = "DELEGHE", unique = true)
	public Date getDeleghe() {
		return this.deleghe;
	}

	public void setDeleghe(Date deleghe) {
		this.deleghe = deleghe;
	}

	@Column(name = "OLD_PASSWORDS", unique = true)
	public Date getOldPasswords() {
		return this.oldPasswords;
	}

	public void setOldPasswords(Date oldPasswords) {
		this.oldPasswords = oldPasswords;
	}

	@Column(name = "E_MAIL", length = 100)
	public String getEMail() {
		return this.EMail;
	}

	public void setEMail(String EMail) {
		this.EMail = EMail;
	}

	@Column(name = "QUALIFICA", length = 100)
	public String getQualifica() {
		return this.qualifica;
	}

	public void setQualifica(String qualifica) {
		this.qualifica = qualifica;
	}

	@Column(name = "NRO_MATRICOLA", length = 30)
	public String getNroMatricola() {
		return this.nroMatricola;
	}

	public void setNroMatricola(String nroMatricola) {
		this.nroMatricola = nroMatricola;
	}

	@Column(name = "TITOLO", length = 30)
	public String getTitolo() {
		return this.titolo;
	}

	public void setTitolo(String titolo) {
		this.titolo = titolo;
	}

	@Column(name = "FLG_NO_ACC_SIS", precision = 1, scale = 0)
	public Boolean getFlgNoAccSis() {
		return this.flgNoAccSis;
	}

	public void setFlgNoAccSis(Boolean flgNoAccSis) {
		this.flgNoAccSis = flgNoAccSis;
	}

	@Column(name = "CREDENZ_AUT_EXT", unique = true)
	public Date getCredenzAutExt() {
		return this.credenzAutExt;
	}

	public void setCredenzAutExt(Date credenzAutExt) {
		this.credenzAutExt = credenzAutExt;
	}

	@Column(name = "ACL_PREDEFINITE", unique = true)
	public Date getAclPredefinite() {
		return this.aclPredefinite;
	}

	public void setAclPredefinite(Date aclPredefinite) {
		this.aclPredefinite = aclPredefinite;
	}

	@Column(name = "ALTRI_ATTRIBUTI", unique = true)
	public Date getAltriAttributi() {
		return this.altriAttributi;
	}

	public void setAltriAttributi(Date altriAttributi) {
		this.altriAttributi = altriAttributi;
	}

	@Column(name = "INFO_STORICO", unique = true)
	public Date getInfoStorico() {
		return this.infoStorico;
	}

	public void setInfoStorico(Date infoStorico) {
		this.infoStorico = infoStorico;
	}

	@Column(name = "COD_RAPIDO", length = 30)
	public String getCodRapido() {
		return this.codRapido;
	}

	public void setCodRapido(String codRapido) {
		this.codRapido = codRapido;
	}

	@Column(name = "PROV_CI_USER", length = 50)
	public String getProvCiUser() {
		return this.provCiUser;
	}

	public void setProvCiUser(String provCiUser) {
		this.provCiUser = provCiUser;
	}

	@Column(name = "FLG_LOCKED", precision = 1, scale = 0)
	public Boolean getFlgLocked() {
		return this.flgLocked;
	}

	public void setFlgLocked(Boolean flgLocked) {
		this.flgLocked = flgLocked;
	}

	@Column(name = "TS_INS", length = 7)
	public Date getTsIns() {
		return this.tsIns;
	}

	public void setTsIns(Date tsIns) {
		this.tsIns = tsIns;
	}

	@Column(name = "ID_USER_INS", precision = 22, scale = 0)
	public BigDecimal getIdUserIns() {
		return this.idUserIns;
	}

	public void setIdUserIns(BigDecimal idUserIns) {
		this.idUserIns = idUserIns;
	}

	@Column(name = "TS_LAST_UPD", length = 7)
	public Date getTsLastUpd() {
		return this.tsLastUpd;
	}

	public void setTsLastUpd(Date tsLastUpd) {
		this.tsLastUpd = tsLastUpd;
	}

	@Column(name = "ID_USER_LAST_UPD", precision = 22, scale = 0)
	public BigDecimal getIdUserLastUpd() {
		return this.idUserLastUpd;
	}

	public void setIdUserLastUpd(BigDecimal idUserLastUpd) {
		this.idUserLastUpd = idUserLastUpd;
	}

}
