/* * SPDX-License-Identifier: AGPL-3.0-or-later * * C Copyright 2023 Regione Piemonte * */

// Generated 21-gen-2015 9.57.07 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * DmvDatiClientiFatt generated by hbm2java
 */
@Entity
@Table(name = "DMV_DATI_CLIENTI_FATT")
public class DmvDatiClientiFatt implements java.io.Serializable {

	private static final long serialVersionUID = 7499582166339701526L;
	
	private DmvDatiClientiFattId id;

	public DmvDatiClientiFatt() {
	}

	public DmvDatiClientiFatt(DmvDatiClientiFattId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "idSpAoo", column = @Column(name = "ID_SP_AOO", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "chiave", column = @Column(name = "CHIAVE", nullable = false, length = 100)),
			@AttributeOverride(name = "valore", column = @Column(name = "VALORE", nullable = false, length = 500)),
			@AttributeOverride(name = "codAppl", column = @Column(name = "COD_APPL", length = 30)),
			@AttributeOverride(name = "codIstAppl", column = @Column(name = "COD_IST_APPL", length = 30)) })
	public DmvDatiClientiFattId getId() {
		return this.id;
	}

	public void setId(DmvDatiClientiFattId id) {
		this.id = id;
	}

}
