/* * SPDX-License-Identifier: AGPL-3.0-or-later * * C Copyright 2023 Regione Piemonte * */

// Generated 4-feb-2015 15.27.45 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DmvRicevuteSdiFattureId generated by hbm2java
 */
@Embeddable
public class DmvRicevuteSdiFattureId implements java.io.Serializable {

	private static final long serialVersionUID = 1059671731309643459L;

	
	private String codApplOwner;

	private String codIstApplOwner;

	private BigDecimal idDocRicevuta;


	public DmvRicevuteSdiFattureId() {
	}

	public DmvRicevuteSdiFattureId(String codApplOwner, String codIstApplOwner, String tipoRicevuta, BigDecimal idUdRicevuta,
			BigDecimal idDocRicevuta, Date tsArrivoRicevuta, String uriRicevuta, String denomProduttore, String codFiscaleProduttore,
			String connToken, String intitolazioneFattura, String flgAttivaPassiva, String idTrasmittente, String progrTrasmSdi,
			String nroFattura, String annoFattura, Date fattData, BigDecimal importoFattura, String fattDenomDest, String fattCodIpaDest,
			String fattIdFiscDest, String codStatoDettFatt) {
		this.codApplOwner = codApplOwner;
		this.codIstApplOwner = codIstApplOwner;
		this.idDocRicevuta = idDocRicevuta;
	}

	@Column(name = "COD_APPL_OWNER", length = 30)
	public String getCodApplOwner() {
		return this.codApplOwner;
	}

	public void setCodApplOwner(String codApplOwner) {
		this.codApplOwner = codApplOwner;
	}

	@Column(name = "COD_IST_APPL_OWNER", length = 30)
	public String getCodIstApplOwner() {
		return this.codIstApplOwner;
	}

	public void setCodIstApplOwner(String codIstApplOwner) {
		this.codIstApplOwner = codIstApplOwner;
	}

	@Column(name = "ID_DOC_RICEVUTA", nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdDocRicevuta() {
		return this.idDocRicevuta;
	}

	public void setIdDocRicevuta(BigDecimal idDocRicevuta) {
		this.idDocRicevuta = idDocRicevuta;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DmvRicevuteSdiFattureId))
			return false;
		DmvRicevuteSdiFattureId castOther = (DmvRicevuteSdiFattureId) other;

		return ((this.getCodApplOwner() == castOther.getCodApplOwner()) || (this.getCodApplOwner() != null
				&& castOther.getCodApplOwner() != null && this.getCodApplOwner().equals(castOther.getCodApplOwner())))
				&& ((this.getCodIstApplOwner() == castOther.getCodIstApplOwner()) || (this.getCodIstApplOwner() != null
						&& castOther.getCodIstApplOwner() != null && this.getCodIstApplOwner().equals(castOther.getCodIstApplOwner())))
				&& ((this.getIdDocRicevuta() == castOther.getIdDocRicevuta()) || (this.getIdDocRicevuta() != null
						&& castOther.getIdDocRicevuta() != null && this.getIdDocRicevuta().equals(castOther.getIdDocRicevuta())));
	}

	public int hashCode() {
		int result = 3;

		result = 37 * result + (getCodApplOwner() == null ? 0 : this.getCodApplOwner().hashCode());
		result = 37 * result + (getCodIstApplOwner() == null ? 0 : this.getCodIstApplOwner().hashCode());
		result = 37 * result + (getIdDocRicevuta() == null ? 0 : this.getIdDocRicevuta().hashCode());
		return result;
	}

	@Override
	public String toString() {
		return String.format("DmvRicevuteSdiFattureId [codApplOwner=%s, codIstApplOwner=%s, idDocRicevuta=%s]", 
				codApplOwner, codIstApplOwner, idDocRicevuta);
	}

}
