/* * SPDX-License-Identifier: AGPL-3.0-or-later * * C Copyright 2023 Regione Piemonte * */

// Generated 26-giu-2015 10.27.27 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * DmvSocieta generated by hbm2java
 */
@Entity
@Table(name = "DMV_SOCIETA")
public class DmvSocieta implements java.io.Serializable {

	private static final long serialVersionUID = -8357871048957256744L;
	
	private DmvSocietaId id;
	
	private String codFiscale;

	private String piva;

	private String userid;

	private String password;

	private String descrizione;

	private String cifratura;

	private String chiaveCifratura;

	private String connToken;

	private BigDecimal flgNoInvioSdi;

	private BigDecimal flgAttivaConsFatt;

	private String nomeSistemaCsEsterno;

	private String useridSistemaCsEsterno;

	private String passwordSistemaCsEsterno;

	private BigDecimal flgAttivaInvioFattCliente;

	private BigDecimal flgFeAttivaFtp;

	public DmvSocieta() {
	}

	public DmvSocieta(DmvSocietaId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "idSpAoo", column = @Column(name = "ID_SP_AOO", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "ciApplicazione", column = @Column(name = "CI_APPLICAZIONE", nullable = false, length = 30)),
			@AttributeOverride(name = "ciIstanzaApplicazione", column = @Column(name = "CI_ISTANZA_APPLICAZIONE", length = 30))})
	public DmvSocietaId getId() {
		return this.id;
	}

	public void setId(DmvSocietaId id) {
		this.id = id;
	}

	@Column(name = "COD_FISCALE", length = 4000)
	public String getCodFiscale() {
		return this.codFiscale;
	}

	public void setCodFiscale(String codFiscale) {
		this.codFiscale = codFiscale;
	}

	@Column(name = "PIVA", length = 4000)
	public String getPiva() {
		return this.piva;
	}

	public void setPiva(String piva) {
		this.piva = piva;
	}

	@Column(name = "USERID", length = 4000)
	public String getUserid() {
		return this.userid;
	}

	public void setUserid(String userid) {
		this.userid = userid;
	}

	@Column(name = "PASSWORD", length = 4000)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "DESCRIZIONE", length = 1000)
	public String getDescrizione() {
		return this.descrizione;
	}

	public void setDescrizione(String descrizione) {
		this.descrizione = descrizione;
	}

	@Column(name = "CIFRATURA", length = 4000)
	public String getCifratura() {
		return this.cifratura;
	}

	public void setCifratura(String cifratura) {
		this.cifratura = cifratura;
	}

	@Column(name = "CHIAVE_CIFRATURA", length = 4000)
	public String getChiaveCifratura() {
		return this.chiaveCifratura;
	}

	public void setChiaveCifratura(String chiaveCifratura) {
		this.chiaveCifratura = chiaveCifratura;
	}

	@Column(name = "CONN_TOKEN", length = 4000)
	public String getConnToken() {
		return this.connToken;
	}

	public void setConnToken(String connToken) {
		this.connToken = connToken;
	}

	@Column(name = "FLG_NO_INVIO_SDI", precision = 22, scale = 0)
	public BigDecimal getFlgNoInvioSdi() {
		return this.flgNoInvioSdi;
	}

	public void setFlgNoInvioSdi(BigDecimal flgNoInvioSdi) {
		this.flgNoInvioSdi = flgNoInvioSdi;
	}

	@Column(name = "FLG_ATTIVA_CONS_FATT", precision = 22, scale = 0)
	public BigDecimal getFlgAttivaConsFatt() {
		return this.flgAttivaConsFatt;
	}

	public void setFlgAttivaConsFatt(BigDecimal flgAttivaConsFatt) {
		this.flgAttivaConsFatt = flgAttivaConsFatt;
	}

	@Column(name = "NOME_SISTEMA_CS_ESTERNO", length = 4000)
	public String getNomeSistemaCsEsterno() {
		return this.nomeSistemaCsEsterno;
	}

	public void setNomeSistemaCsEsterno(String nomeSistemaCsEsterno) {
		this.nomeSistemaCsEsterno = nomeSistemaCsEsterno;
	}

	@Column(name = "USERID_SISTEMA_CS_ESTERNO", length = 4000)
	public String getUseridSistemaCsEsterno() {
		return this.useridSistemaCsEsterno;
	}

	public void setUseridSistemaCsEsterno(String useridSistemaCsEsterno) {
		this.useridSistemaCsEsterno = useridSistemaCsEsterno;
	}

	@Column(name = "PASSWORD_SISTEMA_CS_ESTERNO", length = 4000)
	public String getPasswordSistemaCsEsterno() {
		return this.passwordSistemaCsEsterno;
	}

	public void setPasswordSistemaCsEsterno(String passwordSistemaCsEsterno) {
		this.passwordSistemaCsEsterno = passwordSistemaCsEsterno;
	}

	@Column(name = "FLG_ATTIVA_INVIO_FATT_CLIENTE", precision = 22, scale = 0)
	public BigDecimal getFlgAttivaInvioFattCliente() {
		return this.flgAttivaInvioFattCliente;
	}

	public void setFlgAttivaInvioFattCliente(BigDecimal flgAttivaInvioFattCliente) {
		this.flgAttivaInvioFattCliente = flgAttivaInvioFattCliente;
	}

	@Column(name = "FLG_FE_ATTIVA_FTP", precision = 22, scale = 0)
	public BigDecimal getFlgFeAttivaFtp() {
		return this.flgFeAttivaFtp;
	}

	public void setFlgFeAttivaFtp(BigDecimal flgFeAttivaFtp) {
		this.flgFeAttivaFtp = flgFeAttivaFtp;
	}

	@Override
	public String toString() {
		return String
				.format("DmvSocieta [id=%s, codFiscale=%s, piva=%s, userid=%s, password=%s, descrizione=%s, cifratura=%s, chiaveCifratura=%s, connToken=%s, flgNoInvioSdi=%s, flgAttivaConsFatt=%s, nomeSistemaCsEsterno=%s, useridSistemaCsEsterno=%s, passwordSistemaCsEsterno=%s, flgAttivaInvioFattCliente=%s, flgFeAttivaFtp=%s]",
						id, codFiscale, piva, userid, password, descrizione, cifratura, chiaveCifratura, connToken, flgNoInvioSdi,
						flgAttivaConsFatt, nomeSistemaCsEsterno, useridSistemaCsEsterno, passwordSistemaCsEsterno,
						flgAttivaInvioFattCliente, flgFeAttivaFtp);
	}


}
