/* * SPDX-License-Identifier: AGPL-3.0-or-later * * C Copyright 2023 Regione Piemonte * */

// Generated 6-feb-2015 16.51.43 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Mailbox generated by hbm2java
 */
@Entity
@Table(name = "MAILBOX", uniqueConstraints = { @UniqueConstraint(columnNames = "NAME"),
		@UniqueConstraint(columnNames = { "ID_ACCOUNT", "FOLDER" }) })
public class Mailbox implements java.io.Serializable {

	private static final long serialVersionUID = -6322074792367949829L;

	private String idMailbox;

	private String description;

	private String name;

	private String processFlow;

	private String status;

	private String folder;

	private String idAccount;

	private Set<MailboxMessage> mailboxMessages = new HashSet<MailboxMessage>(0);

	public Mailbox() {
	}

	public Mailbox(String idMailbox, String name, String processFlow, String status, String folder) {
		this.idMailbox = idMailbox;
		this.name = name;
		this.processFlow = processFlow;
		this.status = status;
		this.folder = folder;
	}

	public Mailbox(String idMailbox, String description, String name, String processFlow, String status, String folder,
			String idAccount, Set<MailboxMessage> mailboxMessages) {
		this.idMailbox = idMailbox;
		this.description = description;
		this.name = name;
		this.processFlow = processFlow;
		this.status = status;
		this.folder = folder;
		this.idAccount = idAccount;
		this.mailboxMessages = mailboxMessages;
	}

	@Id
	@Column(name = "ID_MAILBOX", unique = true, nullable = false, length = 40)
	public String getIdMailbox() {
		return this.idMailbox;
	}

	public void setIdMailbox(String idMailbox) {
		this.idMailbox = idMailbox;
	}

	@Column(name = "DESCRIPTION", length = 250)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "NAME", unique = true, nullable = false, length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "PROCESS_FLOW", nullable = false)
	public String getProcessFlow() {
		return this.processFlow;
	}

	public void setProcessFlow(String processFlow) {
		this.processFlow = processFlow;
	}

	@Column(name = "STATUS", nullable = false, length = 10)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "FOLDER", nullable = false, length = 50)
	public String getFolder() {
		return this.folder;
	}

	public void setFolder(String folder) {
		this.folder = folder;
	}

	@Column(name = "ID_ACCOUNT", length = 40)
	public String getIdAccount() {
		return this.idAccount;
	}

	public void setIdAccount(String idAccount) {
		this.idAccount = idAccount;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mailbox")
	public Set<MailboxMessage> getMailboxMessages() {
		return this.mailboxMessages;
	}

	public void setMailboxMessages(Set<MailboxMessage> mailboxMessages) {
		this.mailboxMessages = mailboxMessages;
	}

}
