/* * SPDX-License-Identifier: AGPL-3.0-or-later * * C Copyright 2023 Regione Piemonte * */

// Generated 7-mag-2015 16.52.13 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * TClassiDocCsAruba generated by hbm2java
 */
@Entity
@Table(name = "T_CLASSI_DOC_CS_ARUBA")
public class TClassiDocCsAruba implements java.io.Serializable {

	private static final long serialVersionUID = -1409580473811243545L;

	private TClassiDocCsArubaId id;

	private String codAruba;

	public TClassiDocCsAruba() {
	}

	public TClassiDocCsAruba(TClassiDocCsArubaId id, String codAruba) {
		this.id = id;
		this.codAruba = codAruba;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "useridApplicazione", column = @Column(name = "USERID_APPLICAZIONE", nullable = false, length = 50)),
			@AttributeOverride(name = "nomeClasseDoc", column = @Column(name = "NOME_CLASSE_DOC", nullable = false, length = 100)) })
	public TClassiDocCsArubaId getId() {
		return this.id;
	}

	public void setId(TClassiDocCsArubaId id) {
		this.id = id;
	}

	@Column(name = "COD_ARUBA", nullable = false, length = 50)
	public String getCodAruba() {
		return this.codAruba;
	}

	public void setCodAruba(String codAruba) {
		this.codAruba = codAruba;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((codAruba == null) ? 0 : codAruba.hashCode());
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		TClassiDocCsAruba other = (TClassiDocCsAruba) obj;
		if (codAruba == null) {
			if (other.codAruba != null)
				return false;
		} else if (!codAruba.equals(other.codAruba))
			return false;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		return true;
	}

	@Override
	public String toString() {
		return String.format("TClassiDocCsAruba [id=%s, codAruba=%s]", id, codAruba);
	}

}
