/* * SPDX-License-Identifier: AGPL-3.0-or-later * * C Copyright 2023 Regione Piemonte * */
// Generated 15-set-2017 15.23.59 by Hibernate Tools 3.6.0.Final

import java.math.BigDecimal;
import java.sql.Clob;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * TPdvDocfly generated by hbm2java
 */
@Entity
@Table(name = "T_PDV_DOCFLY")
public class TPdvDocfly implements java.io.Serializable {

	private static final long serialVersionUID = -5111881590435022709L;
	
	private BigDecimal idPdv;
	private String nomeFilePdv;
	private Clob contenutoFilePdv;
	//private Set<TDocDaInviareDocfly> TDocDaInviareDocflies = new HashSet<TDocDaInviareDocfly>(0);
	//private Set<TRicsdiDaInviareDocfly> TRicsdiDaInviareDocflies = new HashSet<TRicsdiDaInviareDocfly>(0);

	public TPdvDocfly() {
	}

	public TPdvDocfly(BigDecimal idPdv, String nomeFilePdv, Clob contenutoFilePdv) {
		this.idPdv = idPdv;
		this.nomeFilePdv = nomeFilePdv;
		this.contenutoFilePdv = contenutoFilePdv;
	}

	/*public TPdvDocfly(BigDecimal idPdv, String nomeFilePdv, Clob contenutoFilePdv,
			Set<TDocDaInviareDocfly> TDocDaInviareDocflies, Set<TRicsdiDaInviareDocfly> TRicsdiDaInviareDocflies) {
		this.idPdv = idPdv;
		this.nomeFilePdv = nomeFilePdv;
		this.contenutoFilePdv = contenutoFilePdv;
		this.TDocDaInviareDocflies = TDocDaInviareDocflies;
		this.TRicsdiDaInviareDocflies = TRicsdiDaInviareDocflies;
	}*/

	@Id
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="SEQ_ID_PDV")
	@SequenceGenerator(
			name="SEQ_ID_PDV", 
			sequenceName="DMS_IDPDVDOCFLY",
			allocationSize=1)
	@Column(name = "ID_PDV", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdPdv() {
		return this.idPdv;
	}

	public void setIdPdv(BigDecimal idPdv) {
		this.idPdv = idPdv;
	}

	@Column(name = "NOME_FILE_PDV", nullable = false, length = 256)
	public String getNomeFilePdv() {
		return this.nomeFilePdv;
	}

	public void setNomeFilePdv(String nomeFilePdv) {
		this.nomeFilePdv = nomeFilePdv;
	}

	@Column(name = "CONTENUTO_FILE_PDV", nullable = false)
	public Clob getContenutoFilePdv() {
		return this.contenutoFilePdv;
	}

	public void setContenutoFilePdv(Clob contenutoFilePdv) {
		this.contenutoFilePdv = contenutoFilePdv;
	}

	/*@OneToMany(fetch = FetchType.LAZY, mappedBy = "TPdvDocfly")
	public Set<TDocDaInviareDocfly> getTDocDaInviareDocflies() {
		return this.TDocDaInviareDocflies;
	}

	public void setTDocDaInviareDocflies(Set<TDocDaInviareDocfly> TDocDaInviareDocflies) {
		this.TDocDaInviareDocflies = TDocDaInviareDocflies;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TPdvDocfly")
	public Set<TRicsdiDaInviareDocfly> getTRicsdiDaInviareDocflies() {
		return this.TRicsdiDaInviareDocflies;
	}

	public void setTRicsdiDaInviareDocflies(Set<TRicsdiDaInviareDocfly> TRicsdiDaInviareDocflies) {
		this.TRicsdiDaInviareDocflies = TRicsdiDaInviareDocflies;
	}*/

}
