/* * SPDX-License-Identifier: AGPL-3.0-or-later * * C Copyright 2023 Regione Piemonte * */

// Generated 20-mag-2015 13.22.27 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * X3appAnagsezionale generated by hbm2java
 */
@Entity
@Table(name = "X3APP_ANAGSEZIONALE")
public class X3appAnagsezionale implements java.io.Serializable {

	private static final long serialVersionUID = 1304167215739148358L;
	
	private String idsezionale;
	private String descrizione;
	private BigDecimal rangeDa;
	private BigDecimal rangeA;
	private Date dataIns;

	public X3appAnagsezionale() {
	}

	public X3appAnagsezionale(String idsezionale) {
		this.idsezionale = idsezionale;
	}

	public X3appAnagsezionale(String idsezionale, String descrizione,
			BigDecimal rangeDa, BigDecimal rangeA, Date dataIns) {
		this.idsezionale = idsezionale;
		this.descrizione = descrizione;
		this.rangeDa = rangeDa;
		this.rangeA = rangeA;
		this.dataIns = dataIns;
	}

	@Id
	@Column(name = "IDSEZIONALE", nullable = false, length = 50)
	public String getIdsezionale() {
		return this.idsezionale;
	}

	public void setIdsezionale(String idsezionale) {
		this.idsezionale = idsezionale;
	}

	@Column(name = "DESCRIZIONE", length = 1000)
	public String getDescrizione() {
		return this.descrizione;
	}

	public void setDescrizione(String descrizione) {
		this.descrizione = descrizione;
	}

	@Column(name = "RANGE_DA", precision = 22, scale = 0)
	public BigDecimal getRangeDa() {
		return this.rangeDa;
	}

	public void setRangeDa(BigDecimal rangeDa) {
		this.rangeDa = rangeDa;
	}

	@Column(name = "RANGE_A", precision = 22, scale = 0)
	public BigDecimal getRangeA() {
		return this.rangeA;
	}

	public void setRangeA(BigDecimal rangeA) {
		this.rangeA = rangeA;
	}

	@Column(name = "DATA_INS", length = 7)
	public Date getDataIns() {
		return this.dataIns;
	}

	public void setDataIns(Date dataIns) {
		this.dataIns = dataIns;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof X3appAnagsezionale))
			return false;
		X3appAnagsezionale castOther = (X3appAnagsezionale) other;

		return ((this.getIdsezionale() == castOther.getIdsezionale()) || (this
				.getIdsezionale() != null && castOther.getIdsezionale() != null && this
				.getIdsezionale().equals(castOther.getIdsezionale())))
				&& ((this.getDescrizione() == castOther.getDescrizione()) || (this
						.getDescrizione() != null
						&& castOther.getDescrizione() != null && this
						.getDescrizione().equals(castOther.getDescrizione())))
				&& ((this.getRangeDa() == castOther.getRangeDa()) || (this
						.getRangeDa() != null && castOther.getRangeDa() != null && this
						.getRangeDa().equals(castOther.getRangeDa())))
				&& ((this.getRangeA() == castOther.getRangeA()) || (this
						.getRangeA() != null && castOther.getRangeA() != null && this
						.getRangeA().equals(castOther.getRangeA())))
				&& ((this.getDataIns() == castOther.getDataIns()) || (this
						.getDataIns() != null && castOther.getDataIns() != null && this
						.getDataIns().equals(castOther.getDataIns())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getIdsezionale() == null ? 0 : this.getIdsezionale()
						.hashCode());
		result = 37
				* result
				+ (getDescrizione() == null ? 0 : this.getDescrizione()
						.hashCode());
		result = 37 * result
				+ (getRangeDa() == null ? 0 : this.getRangeDa().hashCode());
		result = 37 * result
				+ (getRangeA() == null ? 0 : this.getRangeA().hashCode());
		result = 37 * result
				+ (getDataIns() == null ? 0 : this.getDataIns().hashCode());
		return result;
	}

	@Override
	public String toString() {
		return String.format("X3appAnagsezionale [idsezionale=%s, descrizione=%s, rangeDa=%s, rangeA=%s, dataIns=%s]", idsezionale,
				descrizione, rangeDa, rangeA, dataIns);
	}
}
