
package it.doqui.dosign.dosign.business.session.dosign.remotev2;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "DosignInvalidModeException", targetNamespace = "http://remotev2.dosign.session.business.dosign.dosign.doqui.it/")
public class DosignInvalidModeException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private DosignInvalidModeException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public DosignInvalidModeException_Exception(String message, DosignInvalidModeException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public DosignInvalidModeException_Exception(String message, DosignInvalidModeException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: it.doqui.dosign.dosign.business.session.dosign.remotev2.DosignInvalidModeException
     */
    public DosignInvalidModeException getFaultInfo() {
        return faultInfo;
    }

}
