/* * SPDX-License-Identifier: AGPL-3.0-or-later * * C Copyright 2023 Regione Piemonte * */
// Generated 30-mar-2017 14.13.19 by Hibernate Tools 3.4.0.CR1


import java.math.BigDecimal;
import java.sql.Clob;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ElaborazioneScansioniLog generated by hbm2java
 */
@Entity
@Table(name="T_CODA_FILE_DA_MARCARE"
)
public class CodaFileDaMarcare  implements java.io.Serializable {


    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private BigDecimal idDoc;
	private BigDecimal idUd;
	private Date tsFirma;
    private String tipoBustaCritt;
    private Date tsLastTry;
    private Integer numTry;
    private Clob errMsg;

    public CodaFileDaMarcare() {
    }

    @Id 
	@Column(name="ID_DOC", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getIdDoc() {
    	return this.idDoc;
    }
   
   public void setIdDoc(BigDecimal idDoc) {
       this.idDoc = idDoc;
   }
   
   @Column(name="ID_UD", unique=true, nullable=false, precision=22, scale=0)
   public BigDecimal getIdUd() {
	   return this.idUd;
   }

   public void setIdUd(BigDecimal idUd) {
	   this.idUd = idUd;
   }
   
   @Column(name="TIPO_BUSTA_CRITT", nullable=true, length=100)
   public String getTipoBustaCritt() {
	   return tipoBustaCritt;
   }

   public void setTipoBustaCritt(String tipoBustaCritt) {
	   this.tipoBustaCritt = tipoBustaCritt;
   }

   @Column(name="ERR_MSG")
   public Clob getErrMsg() {
	   return errMsg;
   }

   public void setErrMsg(Clob errMsg) {
	   this.errMsg = errMsg;
   }

   @Column(name="TS_FIRMA", nullable=false)
   public Date getTsFirma() {
	   return tsFirma;
   }

   public void setTsFirma(Date tsFirma) {
	   this.tsFirma = tsFirma;
   }

   @Column(name="TS_LAST_TRY", nullable=false)
   public Date getTsLastTry() {
	   return tsLastTry;
   }

   public void setTsLastTry(Date tsLastTry) {
	   this.tsLastTry = tsLastTry;
   }

   @Column(name="NUM_TRY")
   public Integer getNumTry() {
	   return numTry;
   }

   public void setNumTry(Integer numTry) {
	   this.numTry = numTry;
   }
    
}


