/* * SPDX-License-Identifier: AGPL-3.0-or-later * * C Copyright 2023 Regione Piemonte * */
 Copyright (c) 2003-2020, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or https://ckeditor.com/legal/ckeditor-oss-license
*/
(function(){function v(a){for(var c=0,n=0,m=0,b,p=a.$.rows.length;m<p;m++){b=a.$.rows[m];for(var d=c=0,e,f=b.cells.length;d<f;d++)e=b.cells[d],c+=e.colSpan;c>n&&(n=c)}return n}function r(a){return function(){var c=this.getValue(),c=!!(CKEDITOR.dialog.validate.integer().call(this,c)&&0<c);c||(alert(a),this.select());return c}}function q(a,c){var n=function(b){return new CKEDITOR.dom.element(b,a.document)},q=a.editable();return{title:a.lang.table.title,minWidth:310,minHeight:CKEDITOR.env.ie?310:280,
getModel:function(b){return"tableProperties"!==this.dialog.getName()?null:(b=(b=b.getSelection())&&b.getRanges()[0])?b._getTableElement({table:1}):null},onLoad:function(){var b=this,a=b.getContentElement("advanced","advStyles");if(a)a.on("change",function(){var a=this.getStyle("width",""),e=b.getContentElement("info","txtWidth");e&&e.setValue(a,!0);a=this.getStyle("height","");(e=b.getContentElement("info","txtHeight"))&&e.setValue(a,!0)})},onShow:function(){var b=a.getSelection(),p=b.getRanges(),
d,e=this.getContentElement("info","txtRows"),f=this.getContentElement("info","txtCols"),t=this.getContentElement("info","txtWidth"),k=this.getContentElement("info","txtHeight");"tableProperties"==c&&((b=b.getSelectedElement())&&b.is("table")?d=b:0<p.length&&(CKEDITOR.env.webkit&&p[0].shrink(CKEDITOR.NODE_ELEMENT),d=a.elementPath(p[0].getCommonAncestor(!0)).contains("table",1)),this._.selectedElement=d);d?(this.setupContent(d),e&&e.disable(),f&&f.disable()):(e&&e.enable(),f&&f.enable());t&&t.onChange();
k&&k.onChange()},onOk:function(){var b=a.getSelection(),p=this._.selectedElement&&b.createBookmarks(),d=this._.selectedElement||n("table"),e={};this.commitContent(e,d);if(e.info){e=e.info;if(!this._.selectedElement)for(var f=d.append(n("tbody")),c=parseInt(e.txtRows,10)||0,k=parseInt(e.txtCols,10)||0,h=0;h<c;h++)for(var g=f.append(n("tr")),l=0;l<k;l++)g.append(n("td")).appendBogus();c=e.selHeaders;if(!d.$.tHead&&("row"==c||"both"==c)){g=d.getElementsByTag("thead").getItem(0);f=d.getElementsByTag("tbody").getItem(0);
k=f.getElementsByTag("tr").getItem(0);g||(g=new CKEDITOR.dom.element("thead"),g.insertBefore(f));for(h=0;h<k.getChildCount();h++)f=k.getChild(h),f.type!=CKEDITOR.NODE_ELEMENT||f.data("cke-bookmark")||(f.renameNode("th"),f.setAttribute("scope","col"));g.append(k.remove())}if(null!==d.$.tHead&&"row"!=c&&"both"!=c){g=new CKEDITOR.dom.element(d.$.tHead);for(f=d.getElementsByTag("tbody").getItem(0);0<g.getChildCount();){k=g.getFirst();for(h=0;h<k.getChildCount();h++)l=k.getChild(h),l.type==CKEDITOR.NODE_ELEMENT&&
(l.renameNode("td"),l.removeAttribute("scope"));f.append(k,!0)}g.remove()}if(!this.hasColumnHeaders&&("col"==c||"both"==c))for(g=0;g<d.$.rows.length;g++)l=new CKEDITOR.dom.element(d.$.rows[g].cells[0]),l.renameNode("th"),l.setAttribute("scope","row");if(this.hasColumnHeaders&&"col"!=c&&"both"!=c)for(h=0;h<d.$.rows.length;h++)g=new CKEDITOR.dom.element(d.$.rows[h]),"tbody"==g.getParent().getName()&&(l=new CKEDITOR.dom.element(g.$.cells[0]),l.renameNode("td"),l.removeAttribute("scope"));e.txtHeight?
d.setStyle("height",e.txtHeight):d.removeStyle("height");e.txtWidth?d.setStyle("width",e.txtWidth):d.removeStyle("width");d.getAttribute("style")||d.removeAttribute("style")}if(this._.selectedElement)try{b.selectBookmarks(p)}catch(m){}else a.insertElement(d),setTimeout(function(){var b=new CKEDITOR.dom.element(d.$.rows[0].cells[0]),e=a.createRange();e.moveToPosition(b,CKEDITOR.POSITION_AFTER_START);e.select()},0)},contents:[{id:"info",label:a.lang.table.title,elements:[{type:"hbox",widths:[null,null],
styles:["vertical-align:top"],children:[{type:"vbox",padding:0,children:[{type:"text",id:"txtRows","default":3,label:a.lang.table.rows,required:!0,controlStyle:"width:5em",validate:r(a.lang.table.invalidRows),setup:function(b){this.setValue(b.$.rows.length)},commit:m},{type:"text",id:"txtCols","default":2,label:a.lang.table.columns,required:!0,controlStyle:"width:5em",validate:r(a.lang.table.invalidCols),setup:function(b){this.setValue(v(b))},commit:m},{type:"html",html:"\x26nbsp;"},{type:"select",
id:"selHeaders",requiredContent:"th",hidden:!0,"default":"",label:a.lang.table.headers,items:[[a.lang.table.headersNone,""],[a.lang.table.headersRow,"row"],[a.lang.table.headersColumn,"col"],[a.lang.table.headersBoth,"both"]],setup:function(b){var a=this.getDialog();a.hasColumnHeaders=!0;for(var d=0;d<b.$.rows.length;d++){var e=b.$.rows[d].cells[0];if(e&&"th"!=e.nodeName.toLowerCase()){a.hasColumnHeaders=!1;break}}null!==b.$.tHead?this.setValue(a.hasColumnHeaders?"both":"row"):this.setValue(a.hasColumnHeaders?
"col":"")},commit:m},{type:"hbox",widths:["5em"],children:[{type:"text",id:"txtHeight",requiredContent:"table{height}",hidden:!0,controlStyle:"width:5em",label:a.lang.common.height,title:a.lang.common.cssLengthTooltip,"default":"",getValue:u,validate:CKEDITOR.dialog.validate.cssLength(a.lang.common.invalidCssLength.replace("%1",a.lang.common.height)),onChange:function(){var b=this.getDialog().getContentElement("advanced","advStyles");b&&b.updateStyle("height",this.getValue())},setup:function(b){(b=
b.getStyle("height"))&&this.setValue(b)},commit:m}]},{id:"cmbAlign",type:"select",requiredContent:"table[align]",hidden:!0,"default":"",label:a.lang.common.align,items:[[a.lang.common.notSet,""],[a.lang.common.left,"left"],[a.lang.common.center,"center"],[a.lang.common.right,"right"]],setup:function(b){this.setValue(b.getAttribute("align")||"")},commit:function(b,a){this.getValue()?a.setAttribute("align",this.getValue()):a.removeAttribute("align")}}]},{type:"vbox",padding:0,children:[{type:"hbox",
widths:["5em"],children:[{type:"text",id:"txtWidth",requiredContent:"table{width}",controlStyle:"width:5em",label:a.lang.common.width,title:a.lang.common.cssLengthTooltip,"default":a.filter.check("table{width}")?500>q.getSize("width")?"100%":500:0,getValue:u,validate:CKEDITOR.dialog.validate.cssLength(a.lang.common.invalidCssLength.replace("%1",a.lang.common.width)),onChange:function(){var b=this.getDialog().getContentElement("advanced","advStyles");b&&b.updateStyle("width",this.getValue())},setup:function(b){b=
b.getStyle("width");this.setValue(b)},commit:m}]},{type:"text",id:"txtBorder",requiredContent:"table[border]","default":a.filter.check("table[border]")?1:0,label:a.lang.table.border,controlStyle:"width:3em",validate:CKEDITOR.dialog.validate.number(a.lang.table.invalidBorder),setup:function(b){this.setValue(b.getAttribute("border")||"")},commit:function(b,a){this.getValue()?a.setAttribute("border",this.getValue()):a.removeAttribute("border")}},{type:"html",html:"\x26nbsp;"},{type:"text",id:"txtCellSpace",
requiredContent:"table[cellspacing]",hidden:!0,controlStyle:"width:3em",label:a.lang.table.cellSpace,"default":a.filter.check("table[cellspacing]")?1:0,validate:CKEDITOR.dialog.validate.number(a.lang.table.invalidCellSpacing),setup:function(a){this.setValue(a.getAttribute("cellSpacing")||"")},commit:function(a,c){this.getValue()?c.setAttribute("cellSpacing",this.getValue()):c.removeAttribute("cellSpacing")}},{type:"text",id:"txtCellPad",requiredContent:"table[cellpadding]",hidden:!0,controlStyle:"width:3em",
label:a.lang.table.cellPad,"default":a.filter.check("table[cellpadding]")?1:0,validate:CKEDITOR.dialog.validate.number(a.lang.table.invalidCellPadding),setup:function(a){this.setValue(a.getAttribute("cellPadding")||"")},commit:function(a,c){this.getValue()?c.setAttribute("cellPadding",this.getValue()):c.removeAttribute("cellPadding")}}]}]},{type:"html",align:"right",html:""},{type:"vbox",padding:0,children:[{type:"text",id:"txtCaption",requiredContent:"caption",hidden:!0,label:a.lang.table.caption,
setup:function(a){this.enable();a=a.getElementsByTag("caption");if(0<a.count()){a=a.getItem(0);var c=a.getFirst(CKEDITOR.dom.walker.nodeType(CKEDITOR.NODE_ELEMENT));c&&!c.equals(a.getBogus())?(this.disable(),this.setValue(a.getText())):(a=CKEDITOR.tools.trim(a.getText()),this.setValue(a))}},commit:function(b,c){if(this.isEnabled()){var d=this.getValue(),e=c.getElementsByTag("caption");if(d)0<e.count()?(e=e.getItem(0),e.setHtml("")):(e=new CKEDITOR.dom.element("caption",a.document),c.append(e,!0)),
e.append(new CKEDITOR.dom.text(d,a.document));else if(0<e.count())for(d=e.count()-1;0<=d;d--)e.getItem(d).remove()}}},{type:"text",id:"txtSummary",bidi:!0,requiredContent:"table[summary]",hidden:!0,label:a.lang.table.summary,setup:function(a){this.setValue(a.getAttribute("summary")||"")},commit:function(a,c){this.getValue()?c.setAttribute("summary",this.getValue()):c.removeAttribute("summary")}}]}]}]}}var u=CKEDITOR.tools.cssLength,m=function(a){var c=this.id;a.info||(a.info={});a.info[c]=this.getValue()};
CKEDITOR.dialog.add("table",function(a){return q(a,"table")});CKEDITOR.dialog.add("tableProperties",function(a){return q(a,"tableProperties")})})();