// 
// Decompiled by Procyon v0.5.36
// 

package poraservice;

import richieste.pora.types.prontoweb.eng.it.FiltriProdotto;
import autolettura.pora.types.prontoweb.eng.it.PERIODO;
import richieste.pora.types.prontoweb.eng.it.DATIINSERIMENTORICHIESTA;
import registrazione.pora.types.prontoweb.eng.it.DATISOGGETTOEXT;
import filtri.types.pora.types.prontoweb.eng.it.FiltroRichiesta;
import registrazione.pora.types.prontoweb.eng.it.ArrayOfCONSENSO;
import registrazione.pora.types.prontoweb.eng.it.DATISOGGETTO;
import richieste.pora.types.prontoweb.eng.it.IndRecType;
import richieste.pora.types.prontoweb.eng.it.IndUbiType;
import pora.types.prontoweb.eng.it.ArrayOfSTATOFORNITURA;
import allegati.pora.types.prontoweb.eng.it.ALLEGATORICHIESTA;
import lettureconsumi.pora.types.prontoweb.eng.it.TIPOFILE;
import pora.types.prontoweb.eng.it.ArrayOfFORNITURACP;
import autolettura.pora.types.prontoweb.eng.it.TIPOAUTOLETTURA;
import javax.xml.datatype.XMLGregorianCalendar;
import pora.types.prontoweb.eng.it.ArrayOfRUOLO;
import domiciliazione.pora.types.prontoweb.eng.it.DOMICILIAZIONE;
import pora.types.prontoweb.eng.it.RESULTMSG;
import pora.types.prontoweb.eng.it.PWEBTABLEFILTER;
import multicompany.pora.types.prontoweb.eng.it.INFOMULTICOMPANY;
import java.math.BigDecimal;
import java.net.MalformedURLException;
import java.net.URL;
import java.io.File;
import javax.xml.namespace.QName;

public final class PORAPWEBService_BasicHttpBindingPORAPWEBService_Client
{
    private static final QName SERVICE_NAME;
    
    static {
        SERVICE_NAME = new QName("http://poraservice/", "PORAPWEBService");
    }
    
    private PORAPWEBService_BasicHttpBindingPORAPWEBService_Client() {
    }
    
    public static void main(final String[] args) throws Exception {
        URL wsdlURL = PORAPWEBService_Service.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            final File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                }
                else {
                    wsdlURL = new URL(args[0]);
                }
            }
            catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
        final PORAPWEBService_Service ss = new PORAPWEBService_Service(wsdlURL, PORAPWEBService_BasicHttpBindingPORAPWEBService_Client.SERVICE_NAME);
        final PORAPWEBService port = ss.getBasicHttpBindingPORAPWEBService();
        System.out.println("Invoking getDocumentiPagare...");
        final INFOMULTICOMPANY _getDocumentiPagare_multicompany = null;
        final PWEBTABLEFILTER _getDocumentiPagare_filterTbl = null;
        final String _getDocumentiPagare_soggettoCod = "";
        final String _getDocumentiPagare_fornituraCod = "";
        final RESULTMSG _getDocumentiPagare__return = port.getDocumentiPagare(_getDocumentiPagare_multicompany, _getDocumentiPagare_filterTbl, _getDocumentiPagare_soggettoCod, _getDocumentiPagare_fornituraCod);
        System.out.println("getDocumentiPagare.result=" + _getDocumentiPagare__return);
        System.out.println("Invoking attivaDomiciliazione...");
        final INFOMULTICOMPANY _attivaDomiciliazione_multicompany = null;
        final String _attivaDomiciliazione_soggettoCod = "";
        final String _attivaDomiciliazione_forntituraCod = "";
        final DOMICILIAZIONE _attivaDomiciliazione_domiciliazione = null;
        final RESULTMSG _attivaDomiciliazione__return = port.attivaDomiciliazione(_attivaDomiciliazione_multicompany, _attivaDomiciliazione_soggettoCod, _attivaDomiciliazione_forntituraCod, _attivaDomiciliazione_domiciliazione);
        System.out.println("attivaDomiciliazione.result=" + _attivaDomiciliazione__return);
        System.out.println("Invoking autenticaTOKEN...");
        final INFOMULTICOMPANY _autenticaTOKEN_multicompany = null;
        final String _autenticaTOKEN_token = "";
        final ArrayOfRUOLO _autenticaTOKEN_ruoli = null;
        final RESULTMSG _autenticaTOKEN__return = port.autenticaTOKEN(_autenticaTOKEN_multicompany, _autenticaTOKEN_token, _autenticaTOKEN_ruoli);
        System.out.println("autenticaTOKEN.result=" + _autenticaTOKEN__return);
        System.out.println("Invoking setAutoletturaFlusso...");
        final INFOMULTICOMPANY _setAutoletturaFlusso_multicompany = null;
        final String _setAutoletturaFlusso_fornituraCod = "";
        final String _setAutoletturaFlusso_matricolaMis = "";
        final BigDecimal _setAutoletturaFlusso_valoreLetturaMis = new BigDecimal("0");
        final String _setAutoletturaFlusso_matricolaCorr = "";
        final BigDecimal _setAutoletturaFlusso_valoreLetturaCorr = new BigDecimal("0");
        final XMLGregorianCalendar _setAutoletturaFlusso_dataLettura = null;
        final TIPOAUTOLETTURA _setAutoletturaFlusso_tipoAutoLettura = null;
        final RESULTMSG _setAutoletturaFlusso__return = port.setAutoletturaFlusso(_setAutoletturaFlusso_multicompany, _setAutoletturaFlusso_fornituraCod, _setAutoletturaFlusso_matricolaMis, _setAutoletturaFlusso_valoreLetturaMis, _setAutoletturaFlusso_matricolaCorr, _setAutoletturaFlusso_valoreLetturaCorr, _setAutoletturaFlusso_dataLettura, _setAutoletturaFlusso_tipoAutoLettura);
        System.out.println("setAutoletturaFlusso.result=" + _setAutoletturaFlusso__return);
        System.out.println("Invoking downloadCurvePrelievo...");
        final INFOMULTICOMPANY _downloadCurvePrelievo_multicompany = null;
        final ArrayOfFORNITURACP _downloadCurvePrelievo_elencoForniture = null;
        final XMLGregorianCalendar _downloadCurvePrelievo_periodoIni = null;
        final XMLGregorianCalendar _downloadCurvePrelievo_periodoFin = null;
        final TIPOFILE _downloadCurvePrelievo_tipoFile = null;
        final RESULTMSG _downloadCurvePrelievo__return = port.downloadCurvePrelievo(_downloadCurvePrelievo_multicompany, _downloadCurvePrelievo_elencoForniture, _downloadCurvePrelievo_periodoIni, _downloadCurvePrelievo_periodoFin, _downloadCurvePrelievo_tipoFile);
        System.out.println("downloadCurvePrelievo.result=" + _downloadCurvePrelievo__return);
        System.out.println("Invoking getTipiServizio...");
        final INFOMULTICOMPANY _getTipiServizio_multicompany = null;
        final RESULTMSG _getTipiServizio__return = port.getTipiServizio(_getTipiServizio_multicompany);
        System.out.println("getTipiServizio.result=" + _getTipiServizio__return);
        System.out.println("Invoking getTipiRichiesta...");
        final INFOMULTICOMPANY _getTipiRichiesta_multicompany = null;
        final RESULTMSG _getTipiRichiesta__return = port.getTipiRichiesta(_getTipiRichiesta_multicompany);
        System.out.println("getTipiRichiesta.result=" + _getTipiRichiesta__return);
        System.out.println("Invoking disattivaPaperless...");
        final INFOMULTICOMPANY _disattivaPaperless_multicompany = null;
        final String _disattivaPaperless_codFornitura = "";
        final RESULTMSG _disattivaPaperless__return = port.disattivaPaperless(_disattivaPaperless_multicompany, _disattivaPaperless_codFornitura);
        System.out.println("disattivaPaperless.result=" + _disattivaPaperless__return);
        System.out.println("Invoking uploadAllegato...");
        final INFOMULTICOMPANY _uploadAllegato_multicompany = null;
        final ALLEGATORICHIESTA _uploadAllegato_filtro = null;
        final RESULTMSG _uploadAllegato__return = port.uploadAllegato(_uploadAllegato_multicompany, _uploadAllegato_filtro);
        System.out.println("uploadAllegato.result=" + _uploadAllegato__return);
        System.out.println("Invoking getServiziLight...");
        final INFOMULTICOMPANY _getServiziLight_multicompany = null;
        final String _getServiziLight_soggettoCOD = "";
        final String _getServiziLight_ruolosoggCOD = "";
        final String _getServiziLight_nominativo = "";
        final String _getServiziLight_codiceFiscale = "";
        final String _getServiziLight_partitaIVA = "";
        final String _getServiziLight_soggCodAmm = "";
        final String _getServiziLight_tipoServizioCod = "";
        final String _getServiziLight_codicePDRPOR = "";
        final String _getServiziLight_fornituraCod = "";
        final String _getServiziLight_contrattoNum = "";
        final String _getServiziLight_prodottoCod = "";
        final ArrayOfSTATOFORNITURA _getServiziLight_elencoStati = null;
        final PWEBTABLEFILTER _getServiziLight_filter = null;
        final RESULTMSG _getServiziLight__return = port.getServiziLight(_getServiziLight_multicompany, _getServiziLight_soggettoCOD, _getServiziLight_ruolosoggCOD, _getServiziLight_nominativo, _getServiziLight_codiceFiscale, _getServiziLight_partitaIVA, _getServiziLight_soggCodAmm, _getServiziLight_tipoServizioCod, _getServiziLight_codicePDRPOR, _getServiziLight_fornituraCod, _getServiziLight_contrattoNum, _getServiziLight_prodottoCod, _getServiziLight_elencoStati, _getServiziLight_filter);
        System.out.println("getServiziLight.result=" + _getServiziLight__return);
        System.out.println("Invoking normalizzaIndirizzoUbiGeoCall...");
        final INFOMULTICOMPANY _normalizzaIndirizzoUbiGeoCall_multicompany = null;
        final IndUbiType _normalizzaIndirizzoUbiGeoCall_indirizzo = null;
        final RESULTMSG _normalizzaIndirizzoUbiGeoCall__return = port.normalizzaIndirizzoUbiGeoCall(_normalizzaIndirizzoUbiGeoCall_multicompany, _normalizzaIndirizzoUbiGeoCall_indirizzo);
        System.out.println("normalizzaIndirizzoUbiGeoCall.result=" + _normalizzaIndirizzoUbiGeoCall__return);
        System.out.println("Invoking getPDFNETA...");
        final INFOMULTICOMPANY _getPDFNETA_multicompany = null;
        final String _getPDFNETA_documentoID = "";
        final RESULTMSG _getPDFNETA__return = port.getPDFNETA(_getPDFNETA_multicompany, _getPDFNETA_documentoID);
        System.out.println("getPDFNETA.result=" + _getPDFNETA__return);
        System.out.println("Invoking login...");
        final INFOMULTICOMPANY _login_multicompany = null;
        final String _login_account = "";
        final String _login_password = "";
        final ArrayOfRUOLO _login_ruoli = null;
        final RESULTMSG _login__return = port.login(_login_multicompany, _login_account, _login_password, _login_ruoli);
        System.out.println("login.result=" + _login__return);
        System.out.println("Invoking getCurrentVersion...");
        final RESULTMSG _getCurrentVersion__return = port.getCurrentVersion();
        System.out.println("getCurrentVersion.result=" + _getCurrentVersion__return);
        System.out.println("Invoking sbloccaAccount...");
        final INFOMULTICOMPANY _sbloccaAccount_multicompany = null;
        final String _sbloccaAccount_token = "";
        final ArrayOfRUOLO _sbloccaAccount_ruoli = null;
        final RESULTMSG _sbloccaAccount__return = port.sbloccaAccount(_sbloccaAccount_multicompany, _sbloccaAccount_token, _sbloccaAccount_ruoli);
        System.out.println("sbloccaAccount.result=" + _sbloccaAccount__return);
        System.out.println("Invoking downloadEstrattoContoGenerale...");
        final INFOMULTICOMPANY _downloadEstrattoContoGenerale_multicompany = null;
        final String _downloadEstrattoContoGenerale_soggettoCod = "";
        final String _downloadEstrattoContoGenerale_ruoloSoggettoCod = "";
        final String _downloadEstrattoContoGenerale_nominativo = "";
        final String _downloadEstrattoContoGenerale_codiceFiscale = "";
        final String _downloadEstrattoContoGenerale_fornituraCod = "";
        final String _downloadEstrattoContoGenerale_contrattoNum = "";
        final String _downloadEstrattoContoGenerale_prodottoCod = "";
        final ArrayOfSTATOFORNITURA _downloadEstrattoContoGenerale_elencoStati = null;
        final String _downloadEstrattoContoGenerale_soggettoCodAmm = "";
        final String _downloadEstrattoContoGenerale_partitaIVA = "";
        final String _downloadEstrattoContoGenerale_tipoServizioCod = "";
        final String _downloadEstrattoContoGenerale_codicePODPDR = "";
        final RESULTMSG _downloadEstrattoContoGenerale__return = port.downloadEstrattoContoGenerale(_downloadEstrattoContoGenerale_multicompany, _downloadEstrattoContoGenerale_soggettoCod, _downloadEstrattoContoGenerale_ruoloSoggettoCod, _downloadEstrattoContoGenerale_nominativo, _downloadEstrattoContoGenerale_codiceFiscale, _downloadEstrattoContoGenerale_fornituraCod, _downloadEstrattoContoGenerale_contrattoNum, _downloadEstrattoContoGenerale_prodottoCod, _downloadEstrattoContoGenerale_elencoStati, _downloadEstrattoContoGenerale_soggettoCodAmm, _downloadEstrattoContoGenerale_partitaIVA, _downloadEstrattoContoGenerale_tipoServizioCod, _downloadEstrattoContoGenerale_codicePODPDR);
        System.out.println("downloadEstrattoContoGenerale.result=" + _downloadEstrattoContoGenerale__return);
        System.out.println("Invoking cambioPassword...");
        final INFOMULTICOMPANY _cambioPassword_multicompany = null;
        final String _cambioPassword_account = "";
        final String _cambioPassword_password = "";
        final String _cambioPassword_nuovoAccount = "";
        final String _cambioPassword_nuovaPassword = "";
        final String _cambioPassword_token = "";
        final ArrayOfRUOLO _cambioPassword_ruoli = null;
        final RESULTMSG _cambioPassword__return = port.cambioPassword(_cambioPassword_multicompany, _cambioPassword_account, _cambioPassword_password, _cambioPassword_nuovoAccount, _cambioPassword_nuovaPassword, _cambioPassword_token, _cambioPassword_ruoli);
        System.out.println("cambioPassword.result=" + _cambioPassword__return);
        System.out.println("Invoking getTipoVia...");
        final INFOMULTICOMPANY _getTipoVia_multicompany = null;
        final String _getTipoVia_criterioRicerca = "";
        final RESULTMSG _getTipoVia__return = port.getTipoVia(_getTipoVia_multicompany, _getTipoVia_criterioRicerca);
        System.out.println("getTipoVia.result=" + _getTipoVia__return);
        System.out.println("Invoking normalizzaIndirizzoRecGeoCall...");
        final INFOMULTICOMPANY _normalizzaIndirizzoRecGeoCall_multicompany = null;
        final IndRecType _normalizzaIndirizzoRecGeoCall_indirizzo = null;
        final RESULTMSG _normalizzaIndirizzoRecGeoCall__return = port.normalizzaIndirizzoRecGeoCall(_normalizzaIndirizzoRecGeoCall_multicompany, _normalizzaIndirizzoRecGeoCall_indirizzo);
        System.out.println("normalizzaIndirizzoRecGeoCall.result=" + _normalizzaIndirizzoRecGeoCall__return);
        System.out.println("Invoking recuperaPassword...");
        final INFOMULTICOMPANY _recuperaPassword_multicompany = null;
        final DATISOGGETTO _recuperaPassword_soggetto = null;
        final RESULTMSG _recuperaPassword__return = port.recuperaPassword(_recuperaPassword_multicompany, _recuperaPassword_soggetto);
        System.out.println("recuperaPassword.result=" + _recuperaPassword__return);
        System.out.println("Invoking setRegistrazione...");
        final INFOMULTICOMPANY _setRegistrazione_multicompany = null;
        final String _setRegistrazione_username = "";
        final String _setRegistrazione_password = "";
        final DATISOGGETTO _setRegistrazione_soggetto = null;
        final ArrayOfCONSENSO _setRegistrazione_consensi = null;
        final ArrayOfRUOLO _setRegistrazione_ruoli = null;
        final RESULTMSG _setRegistrazione__return = port.setRegistrazione(_setRegistrazione_multicompany, _setRegistrazione_username, _setRegistrazione_password, _setRegistrazione_soggetto, _setRegistrazione_consensi, _setRegistrazione_ruoli);
        System.out.println("setRegistrazione.result=" + _setRegistrazione__return);
        System.out.println("Invoking getConsensiSoggetto...");
        final INFOMULTICOMPANY _getConsensiSoggetto_multicompany = null;
        final String _getConsensiSoggetto_soggettoCod = "";
        final RESULTMSG _getConsensiSoggetto__return = port.getConsensiSoggetto(_getConsensiSoggetto_multicompany, _getConsensiSoggetto_soggettoCod);
        System.out.println("getConsensiSoggetto.result=" + _getConsensiSoggetto__return);
        System.out.println("Invoking getLineeProdotto...");
        final INFOMULTICOMPANY _getLineeProdotto_multicompany = null;
        final RESULTMSG _getLineeProdotto__return = port.getLineeProdotto(_getLineeProdotto_multicompany);
        System.out.println("getLineeProdotto.result=" + _getLineeProdotto__return);
        System.out.println("Invoking getSituazioneDebitoria...");
        final INFOMULTICOMPANY _getSituazioneDebitoria_multicompany = null;
        final PWEBTABLEFILTER _getSituazioneDebitoria_filterTbl = null;
        final String _getSituazioneDebitoria_soggettoCOD = "";
        final String _getSituazioneDebitoria_fornituraCOD = "";
        final String _getSituazioneDebitoria_ruoloSoggettoCod = "";
        final String _getSituazioneDebitoria_nominativo = "";
        final String _getSituazioneDebitoria_podpdrCod = "";
        final XMLGregorianCalendar _getSituazioneDebitoria_dataIniEmis = null;
        final Boolean _getSituazioneDebitoria_nonPagati = null;
        final Boolean _getSituazioneDebitoria_ultimaFatt = null;
        final RESULTMSG _getSituazioneDebitoria__return = port.getSituazioneDebitoria(_getSituazioneDebitoria_multicompany, _getSituazioneDebitoria_filterTbl, _getSituazioneDebitoria_soggettoCOD, _getSituazioneDebitoria_fornituraCOD, _getSituazioneDebitoria_ruoloSoggettoCod, _getSituazioneDebitoria_nominativo, _getSituazioneDebitoria_podpdrCod, _getSituazioneDebitoria_dataIniEmis, _getSituazioneDebitoria_nonPagati, _getSituazioneDebitoria_ultimaFatt);
        System.out.println("getSituazioneDebitoria.result=" + _getSituazioneDebitoria__return);
        System.out.println("Invoking getSoggetti...");
        final INFOMULTICOMPANY _getSoggetti_multicompany = null;
        final String _getSoggetti_soggettoCOD = "";
        final String _getSoggetti_ruolosoggCOD = "";
        final String _getSoggetti_nominativo = "";
        final String _getSoggetti_codiceFiscale = "";
        final String _getSoggetti_partitaIVA = "";
        final String _getSoggetti_soggCodAmm = "";
        final String _getSoggetti_codicePDRPOR = "";
        final String _getSoggetti_fornituraCod = "";
        final String _getSoggetti_contrattoNum = "";
        final ArrayOfSTATOFORNITURA _getSoggetti_elencoStati = null;
        final PWEBTABLEFILTER _getSoggetti_filter = null;
        final RESULTMSG _getSoggetti__return = port.getSoggetti(_getSoggetti_multicompany, _getSoggetti_soggettoCOD, _getSoggetti_ruolosoggCOD, _getSoggetti_nominativo, _getSoggetti_codiceFiscale, _getSoggetti_partitaIVA, _getSoggetti_soggCodAmm, _getSoggetti_codicePDRPOR, _getSoggetti_fornituraCod, _getSoggetti_contrattoNum, _getSoggetti_elencoStati, _getSoggetti_filter);
        System.out.println("getSoggetti.result=" + _getSoggetti__return);
        System.out.println("Invoking getServizi...");
        final INFOMULTICOMPANY _getServizi_multicompany = null;
        final String _getServizi_soggettoCOD = "";
        final String _getServizi_ruolosoggCOD = "";
        final String _getServizi_nominativo = "";
        final String _getServizi_codiceFiscale = "";
        final String _getServizi_partitaIVA = "";
        final String _getServizi_soggCodAmm = "";
        final String _getServizi_tipoServizioCod = "";
        final String _getServizi_codicePDRPOR = "";
        final String _getServizi_fornituraCod = "";
        final String _getServizi_contrattoNum = "";
        final String _getServizi_prodottoCod = "";
        final ArrayOfSTATOFORNITURA _getServizi_elencoStati = null;
        final PWEBTABLEFILTER _getServizi_filter = null;
        final RESULTMSG _getServizi__return = port.getServizi(_getServizi_multicompany, _getServizi_soggettoCOD, _getServizi_ruolosoggCOD, _getServizi_nominativo, _getServizi_codiceFiscale, _getServizi_partitaIVA, _getServizi_soggCodAmm, _getServizi_tipoServizioCod, _getServizi_codicePDRPOR, _getServizi_fornituraCod, _getServizi_contrattoNum, _getServizi_prodottoCod, _getServizi_elencoStati, _getServizi_filter);
        System.out.println("getServizi.result=" + _getServizi__return);
        System.out.println("Invoking updateSoggettoProspect...");
        final INFOMULTICOMPANY _updateSoggettoProspect_multicompany = null;
        final DATISOGGETTO _updateSoggettoProspect_soggettoProspect = null;
        final ArrayOfCONSENSO _updateSoggettoProspect_consensi = null;
        final RESULTMSG _updateSoggettoProspect__return = port.updateSoggettoProspect(_updateSoggettoProspect_multicompany, _updateSoggettoProspect_soggettoProspect, _updateSoggettoProspect_consensi);
        System.out.println("updateSoggettoProspect.result=" + _updateSoggettoProspect__return);
        System.out.println("Invoking getSituazioneDebitoriaExt...");
        final INFOMULTICOMPANY _getSituazioneDebitoriaExt_multicompany = null;
        final PWEBTABLEFILTER _getSituazioneDebitoriaExt_filterTbl = null;
        final String _getSituazioneDebitoriaExt_soggettoCOD = "";
        final String _getSituazioneDebitoriaExt_fornituraCOD = "";
        final String _getSituazioneDebitoriaExt_ruoloSoggettoCod = "";
        final String _getSituazioneDebitoriaExt_nominativo = "";
        final String _getSituazioneDebitoriaExt_podpdrCod = "";
        final XMLGregorianCalendar _getSituazioneDebitoriaExt_dataIniEmis = null;
        final Boolean _getSituazioneDebitoriaExt_nonPagati = null;
        final Boolean _getSituazioneDebitoriaExt_ultimaFatt = null;
        final String _getSituazioneDebitoriaExt_codiceFiscale = "";
        final String _getSituazioneDebitoriaExt_partitaIVA = "";
        final XMLGregorianCalendar _getSituazioneDebitoriaExt_dataScadenzaIni = null;
        final XMLGregorianCalendar _getSituazioneDebitoriaExt_dataScadenzaFin = null;
        final RESULTMSG _getSituazioneDebitoriaExt__return = port.getSituazioneDebitoriaExt(_getSituazioneDebitoriaExt_multicompany, _getSituazioneDebitoriaExt_filterTbl, _getSituazioneDebitoriaExt_soggettoCOD, _getSituazioneDebitoriaExt_fornituraCOD, _getSituazioneDebitoriaExt_ruoloSoggettoCod, _getSituazioneDebitoriaExt_nominativo, _getSituazioneDebitoriaExt_podpdrCod, _getSituazioneDebitoriaExt_dataIniEmis, _getSituazioneDebitoriaExt_nonPagati, _getSituazioneDebitoriaExt_ultimaFatt, _getSituazioneDebitoriaExt_codiceFiscale, _getSituazioneDebitoriaExt_partitaIVA, _getSituazioneDebitoriaExt_dataScadenzaIni, _getSituazioneDebitoriaExt_dataScadenzaFin);
        System.out.println("getSituazioneDebitoriaExt.result=" + _getSituazioneDebitoriaExt__return);
        System.out.println("Invoking setAutolettura...");
        final INFOMULTICOMPANY _setAutolettura_multicompany = null;
        final String _setAutolettura_fornituraCod = "";
        final XMLGregorianCalendar _setAutolettura_dataLettura = null;
        final BigDecimal _setAutolettura_valore = new BigDecimal("0");
        final Boolean _setAutolettura_forzaPeriodo = null;
        final Boolean _setAutolettura_forzaConsumo = null;
        final RESULTMSG _setAutolettura__return = port.setAutolettura(_setAutolettura_multicompany, _setAutolettura_fornituraCod, _setAutolettura_dataLettura, _setAutolettura_valore, _setAutolettura_forzaPeriodo, _setAutolettura_forzaConsumo);
        System.out.println("setAutolettura.result=" + _setAutolettura__return);
        System.out.println("Invoking getConsensiSocieta...");
        final INFOMULTICOMPANY _getConsensiSocieta_multicompany = null;
        final RESULTMSG _getConsensiSocieta__return = port.getConsensiSocieta(_getConsensiSocieta_multicompany);
        System.out.println("getConsensiSocieta.result=" + _getConsensiSocieta__return);
        System.out.println("Invoking getLetturaPrecedenteExt...");
        final INFOMULTICOMPANY _getLetturaPrecedenteExt_multicompany = null;
        final PWEBTABLEFILTER _getLetturaPrecedenteExt_filter = null;
        final String _getLetturaPrecedenteExt_soggettoCOD = "";
        final String _getLetturaPrecedenteExt_tipoServizioCod = "";
        final String _getLetturaPrecedenteExt_codicePDRPOR = "";
        final String _getLetturaPrecedenteExt_fornituracod = "";
        final String _getLetturaPrecedenteExt_contrattoNum = "";
        final String _getLetturaPrecedenteExt_prodottoCod = "";
        final ArrayOfSTATOFORNITURA _getLetturaPrecedenteExt_elencoStati = null;
        final XMLGregorianCalendar _getLetturaPrecedenteExt_dataRiferimento = null;
        final RESULTMSG _getLetturaPrecedenteExt__return = port.getLetturaPrecedenteExt(_getLetturaPrecedenteExt_multicompany, _getLetturaPrecedenteExt_filter, _getLetturaPrecedenteExt_soggettoCOD, _getLetturaPrecedenteExt_tipoServizioCod, _getLetturaPrecedenteExt_codicePDRPOR, _getLetturaPrecedenteExt_fornituracod, _getLetturaPrecedenteExt_contrattoNum, _getLetturaPrecedenteExt_prodottoCod, _getLetturaPrecedenteExt_elencoStati, _getLetturaPrecedenteExt_dataRiferimento);
        System.out.println("getLetturaPrecedenteExt.result=" + _getLetturaPrecedenteExt__return);
        System.out.println("Invoking getEstrattoContoServizio...");
        final INFOMULTICOMPANY _getEstrattoContoServizio_multicompany = null;
        final PWEBTABLEFILTER _getEstrattoContoServizio_filterTbl = null;
        final String _getEstrattoContoServizio_soggettoCod = "";
        final String _getEstrattoContoServizio_ruoloSoggettoCod = "";
        final String _getEstrattoContoServizio_nominativo = "";
        final String _getEstrattoContoServizio_codiceFiscale = "";
        final String _getEstrattoContoServizio_fornituraCod = "";
        final String _getEstrattoContoServizio_contrattoNum = "";
        final String _getEstrattoContoServizio_prodottoCod = "";
        final ArrayOfSTATOFORNITURA _getEstrattoContoServizio_elencoStati = null;
        final String _getEstrattoContoServizio_soggettoCodAmm = "";
        final String _getEstrattoContoServizio_partitaIVA = "";
        final String _getEstrattoContoServizio_tipoServizioCod = "";
        final String _getEstrattoContoServizio_codicePODPDR = "";
        final RESULTMSG _getEstrattoContoServizio__return = port.getEstrattoContoServizio(_getEstrattoContoServizio_multicompany, _getEstrattoContoServizio_filterTbl, _getEstrattoContoServizio_soggettoCod, _getEstrattoContoServizio_ruoloSoggettoCod, _getEstrattoContoServizio_nominativo, _getEstrattoContoServizio_codiceFiscale, _getEstrattoContoServizio_fornituraCod, _getEstrattoContoServizio_contrattoNum, _getEstrattoContoServizio_prodottoCod, _getEstrattoContoServizio_elencoStati, _getEstrattoContoServizio_soggettoCodAmm, _getEstrattoContoServizio_partitaIVA, _getEstrattoContoServizio_tipoServizioCod, _getEstrattoContoServizio_codicePODPDR);
        System.out.println("getEstrattoContoServizio.result=" + _getEstrattoContoServizio__return);
        System.out.println("Invoking getUtentiNewsletter...");
        final INFOMULTICOMPANY _getUtentiNewsletter_multicompany = null;
        final PWEBTABLEFILTER _getUtentiNewsletter_filter = null;
        final RESULTMSG _getUtentiNewsletter__return = port.getUtentiNewsletter(_getUtentiNewsletter_multicompany, _getUtentiNewsletter_filter);
        System.out.println("getUtentiNewsletter.result=" + _getUtentiNewsletter__return);
        System.out.println("Invoking getSottotipi...");
        final INFOMULTICOMPANY _getSottotipi_multicompany = null;
        final String _getSottotipi_tipoRichiesta = "";
        final String _getSottotipi_codLineaProdotto = "";
        final RESULTMSG _getSottotipi__return = port.getSottotipi(_getSottotipi_multicompany, _getSottotipi_tipoRichiesta, _getSottotipi_codLineaProdotto);
        System.out.println("getSottotipi.result=" + _getSottotipi__return);
        System.out.println("Invoking getComuniCatasto...");
        final INFOMULTICOMPANY _getComuniCatasto_multicompany = null;
        final String _getComuniCatasto_criterioRicerca = "";
        final RESULTMSG _getComuniCatasto__return = port.getComuniCatasto(_getComuniCatasto_multicompany, _getComuniCatasto_criterioRicerca);
        System.out.println("getComuniCatasto.result=" + _getComuniCatasto__return);
        System.out.println("Invoking downloadSituazioneDebitoria...");
        final INFOMULTICOMPANY _downloadSituazioneDebitoria_multicompany = null;
        final String _downloadSituazioneDebitoria_soggettoCOD = "";
        final String _downloadSituazioneDebitoria_fornituraCOD = "";
        final String _downloadSituazioneDebitoria_ruoloSoggettoCod = "";
        final String _downloadSituazioneDebitoria_nominativo = "";
        final String _downloadSituazioneDebitoria_podpdrCod = "";
        final XMLGregorianCalendar _downloadSituazioneDebitoria_dataIniEmis = null;
        final Boolean _downloadSituazioneDebitoria_nonPagati = null;
        final Boolean _downloadSituazioneDebitoria_ultimaFatt = null;
        final String _downloadSituazioneDebitoria_codiceFiscale = "";
        final String _downloadSituazioneDebitoria_partitaIVA = "";
        final XMLGregorianCalendar _downloadSituazioneDebitoria_dataScadenzaIni = null;
        final XMLGregorianCalendar _downloadSituazioneDebitoria_dataScadenzaFin = null;
        final RESULTMSG _downloadSituazioneDebitoria__return = port.downloadSituazioneDebitoria(_downloadSituazioneDebitoria_multicompany, _downloadSituazioneDebitoria_soggettoCOD, _downloadSituazioneDebitoria_fornituraCOD, _downloadSituazioneDebitoria_ruoloSoggettoCod, _downloadSituazioneDebitoria_nominativo, _downloadSituazioneDebitoria_podpdrCod, _downloadSituazioneDebitoria_dataIniEmis, _downloadSituazioneDebitoria_nonPagati, _downloadSituazioneDebitoria_ultimaFatt, _downloadSituazioneDebitoria_codiceFiscale, _downloadSituazioneDebitoria_partitaIVA, _downloadSituazioneDebitoria_dataScadenzaIni, _downloadSituazioneDebitoria_dataScadenzaFin);
        System.out.println("downloadSituazioneDebitoria.result=" + _downloadSituazioneDebitoria__return);
        System.out.println("Invoking getTOKEN...");
        final INFOMULTICOMPANY _getTOKEN_multicompany = null;
        final String _getTOKEN_soggettoCOD = "";
        final RESULTMSG _getTOKEN__return = port.getTOKEN(_getTOKEN_multicompany, _getTOKEN_soggettoCOD);
        System.out.println("getTOKEN.result=" + _getTOKEN__return);
        System.out.println("Invoking getComuniLocalita...");
        final INFOMULTICOMPANY _getComuniLocalita_multicompany = null;
        final String _getComuniLocalita_criterioRicerca = "";
        final RESULTMSG _getComuniLocalita__return = port.getComuniLocalita(_getComuniLocalita_multicompany, _getComuniLocalita_criterioRicerca);
        System.out.println("getComuniLocalita.result=" + _getComuniLocalita__return);
        System.out.println("Invoking downloadCurvePrelievoOrarieEEExt...");
        final INFOMULTICOMPANY _downloadCurvePrelievoOrarieEEExt_multicompany = null;
        final String _downloadCurvePrelievoOrarieEEExt_soggettoCod = "";
        final String _downloadCurvePrelievoOrarieEEExt_ruolosoggCod = "";
        final String _downloadCurvePrelievoOrarieEEExt_nominativo = "";
        final String _downloadCurvePrelievoOrarieEEExt_codiceFiscale = "";
        final String _downloadCurvePrelievoOrarieEEExt_partitaIva = "";
        final String _downloadCurvePrelievoOrarieEEExt_soggCodAmm = "";
        final String _downloadCurvePrelievoOrarieEEExt_tipoServizioCod = "";
        final String _downloadCurvePrelievoOrarieEEExt_codicePDRPOD = "";
        final String _downloadCurvePrelievoOrarieEEExt_fornituraCod = "";
        final String _downloadCurvePrelievoOrarieEEExt_contrattoNum = "";
        final String _downloadCurvePrelievoOrarieEEExt_prodottoCod = "";
        final ArrayOfSTATOFORNITURA _downloadCurvePrelievoOrarieEEExt_elencoStati = null;
        final XMLGregorianCalendar _downloadCurvePrelievoOrarieEEExt_periodoIni = null;
        final XMLGregorianCalendar _downloadCurvePrelievoOrarieEEExt_periodoFin = null;
        final TIPOFILE _downloadCurvePrelievoOrarieEEExt_tipoFile = null;
        final RESULTMSG _downloadCurvePrelievoOrarieEEExt__return = port.downloadCurvePrelievoOrarieEEExt(_downloadCurvePrelievoOrarieEEExt_multicompany, _downloadCurvePrelievoOrarieEEExt_soggettoCod, _downloadCurvePrelievoOrarieEEExt_ruolosoggCod, _downloadCurvePrelievoOrarieEEExt_nominativo, _downloadCurvePrelievoOrarieEEExt_codiceFiscale, _downloadCurvePrelievoOrarieEEExt_partitaIva, _downloadCurvePrelievoOrarieEEExt_soggCodAmm, _downloadCurvePrelievoOrarieEEExt_tipoServizioCod, _downloadCurvePrelievoOrarieEEExt_codicePDRPOD, _downloadCurvePrelievoOrarieEEExt_fornituraCod, _downloadCurvePrelievoOrarieEEExt_contrattoNum, _downloadCurvePrelievoOrarieEEExt_prodottoCod, _downloadCurvePrelievoOrarieEEExt_elencoStati, _downloadCurvePrelievoOrarieEEExt_periodoIni, _downloadCurvePrelievoOrarieEEExt_periodoFin, _downloadCurvePrelievoOrarieEEExt_tipoFile);
        System.out.println("downloadCurvePrelievoOrarieEEExt.result=" + _downloadCurvePrelievoOrarieEEExt__return);
        System.out.println("Invoking getProvince...");
        final INFOMULTICOMPANY _getProvince_multicompany = null;
        final String _getProvince_nazioneCod = "";
        final String _getProvince_regioneCod = "";
        final String _getProvince_criterioRicerca = "";
        final RESULTMSG _getProvince__return = port.getProvince(_getProvince_multicompany, _getProvince_nazioneCod, _getProvince_regioneCod, _getProvince_criterioRicerca);
        System.out.println("getProvince.result=" + _getProvince__return);
        System.out.println("Invoking verificaAttivazionePaperless...");
        final INFOMULTICOMPANY _verificaAttivazionePaperless_multicompany = null;
        final String _verificaAttivazionePaperless_codFornitura = "";
        final RESULTMSG _verificaAttivazionePaperless__return = port.verificaAttivazionePaperless(_verificaAttivazionePaperless_multicompany, _verificaAttivazionePaperless_codFornitura);
        System.out.println("verificaAttivazionePaperless.result=" + _verificaAttivazionePaperless__return);
        System.out.println("Invoking elencoRichiesteExt...");
        final INFOMULTICOMPANY _elencoRichiesteExt_multicompany = null;
        final String _elencoRichiesteExt_soggettoCod = "";
        final PWEBTABLEFILTER _elencoRichiesteExt_filter = null;
        final FiltroRichiesta _elencoRichiesteExt_filtroRichiesta = null;
        final RESULTMSG _elencoRichiesteExt__return = port.elencoRichiesteExt(_elencoRichiesteExt_multicompany, _elencoRichiesteExt_soggettoCod, _elencoRichiesteExt_filter, _elencoRichiesteExt_filtroRichiesta);
        System.out.println("elencoRichiesteExt.result=" + _elencoRichiesteExt__return);
        System.out.println("Invoking getTotaliConsumoFatturatoPagato...");
        final INFOMULTICOMPANY _getTotaliConsumoFatturatoPagato_multicompany = null;
        final PWEBTABLEFILTER _getTotaliConsumoFatturatoPagato_filterTbl = null;
        final Integer _getTotaliConsumoFatturatoPagato_annoRiferimento = null;
        final String _getTotaliConsumoFatturatoPagato_soggettoCodAmm = "";
        final String _getTotaliConsumoFatturatoPagato_soggettoCod = "";
        final String _getTotaliConsumoFatturatoPagato_ruoloSoggettoCod = "";
        final String _getTotaliConsumoFatturatoPagato_codiceFiscale = "";
        final String _getTotaliConsumoFatturatoPagato_codicePODPDR = "";
        final String _getTotaliConsumoFatturatoPagato_fornituraCod = "";
        final ArrayOfSTATOFORNITURA _getTotaliConsumoFatturatoPagato_elencoStati = null;
        final RESULTMSG _getTotaliConsumoFatturatoPagato__return = port.getTotaliConsumoFatturatoPagato(_getTotaliConsumoFatturatoPagato_multicompany, _getTotaliConsumoFatturatoPagato_filterTbl, _getTotaliConsumoFatturatoPagato_annoRiferimento, _getTotaliConsumoFatturatoPagato_soggettoCodAmm, _getTotaliConsumoFatturatoPagato_soggettoCod, _getTotaliConsumoFatturatoPagato_ruoloSoggettoCod, _getTotaliConsumoFatturatoPagato_codiceFiscale, _getTotaliConsumoFatturatoPagato_codicePODPDR, _getTotaliConsumoFatturatoPagato_fornituraCod, _getTotaliConsumoFatturatoPagato_elencoStati);
        System.out.println("getTotaliConsumoFatturatoPagato.result=" + _getTotaliConsumoFatturatoPagato__return);
        System.out.println("Invoking getPlayer...");
        final INFOMULTICOMPANY _getPlayer_multicompany = null;
        final String _getPlayer_funzioneCod = "";
        final String _getPlayer_lineaProdottoCod = "";
        final String _getPlayer_tipoServizioCod = "";
        final RESULTMSG _getPlayer__return = port.getPlayer(_getPlayer_multicompany, _getPlayer_funzioneCod, _getPlayer_lineaProdottoCod, _getPlayer_tipoServizioCod);
        System.out.println("getPlayer.result=" + _getPlayer__return);
        System.out.println("Invoking elencoRichieste...");
        final INFOMULTICOMPANY _elencoRichieste_multicompany = null;
        final String _elencoRichieste_soggettoCod = "";
        final PWEBTABLEFILTER _elencoRichieste_filter = null;
        final RESULTMSG _elencoRichieste__return = port.elencoRichieste(_elencoRichieste_multicompany, _elencoRichieste_soggettoCod, _elencoRichieste_filter);
        System.out.println("elencoRichieste.result=" + _elencoRichieste__return);
        System.out.println("Invoking getEmailProspect...");
        final INFOMULTICOMPANY _getEmailProspect_multicompany = null;
        final RESULTMSG _getEmailProspect__return = port.getEmailProspect(_getEmailProspect_multicompany);
        System.out.println("getEmailProspect.result=" + _getEmailProspect__return);
        System.out.println("Invoking getEstrattoContoGenerale...");
        final INFOMULTICOMPANY _getEstrattoContoGenerale_multicompany = null;
        final PWEBTABLEFILTER _getEstrattoContoGenerale_filterTbl = null;
        final String _getEstrattoContoGenerale_soggettoCod = "";
        final String _getEstrattoContoGenerale_ruoloSoggettoCod = "";
        final String _getEstrattoContoGenerale_nominativo = "";
        final String _getEstrattoContoGenerale_codiceFiscale = "";
        final String _getEstrattoContoGenerale_fornituraCod = "";
        final String _getEstrattoContoGenerale_contrattoNum = "";
        final String _getEstrattoContoGenerale_prodottoCod = "";
        final ArrayOfSTATOFORNITURA _getEstrattoContoGenerale_elencoStati = null;
        final String _getEstrattoContoGenerale_soggettoCodAmm = "";
        final String _getEstrattoContoGenerale_partitaIVA = "";
        final String _getEstrattoContoGenerale_tipoServizioCod = "";
        final String _getEstrattoContoGenerale_codicePODPDR = "";
        final RESULTMSG _getEstrattoContoGenerale__return = port.getEstrattoContoGenerale(_getEstrattoContoGenerale_multicompany, _getEstrattoContoGenerale_filterTbl, _getEstrattoContoGenerale_soggettoCod, _getEstrattoContoGenerale_ruoloSoggettoCod, _getEstrattoContoGenerale_nominativo, _getEstrattoContoGenerale_codiceFiscale, _getEstrattoContoGenerale_fornituraCod, _getEstrattoContoGenerale_contrattoNum, _getEstrattoContoGenerale_prodottoCod, _getEstrattoContoGenerale_elencoStati, _getEstrattoContoGenerale_soggettoCodAmm, _getEstrattoContoGenerale_partitaIVA, _getEstrattoContoGenerale_tipoServizioCod, _getEstrattoContoGenerale_codicePODPDR);
        System.out.println("getEstrattoContoGenerale.result=" + _getEstrattoContoGenerale__return);
        System.out.println("Invoking getLetturaPrecedente...");
        final INFOMULTICOMPANY _getLetturaPrecedente_multicompany = null;
        final PWEBTABLEFILTER _getLetturaPrecedente_filter = null;
        final String _getLetturaPrecedente_fornituracod = "";
        final XMLGregorianCalendar _getLetturaPrecedente_dataRiferimento = null;
        final RESULTMSG _getLetturaPrecedente__return = port.getLetturaPrecedente(_getLetturaPrecedente_multicompany, _getLetturaPrecedente_filter, _getLetturaPrecedente_fornituracod, _getLetturaPrecedente_dataRiferimento);
        System.out.println("getLetturaPrecedente.result=" + _getLetturaPrecedente__return);
        System.out.println("Invoking getListaAlert...");
        final INFOMULTICOMPANY _getListaAlert_multicompany = null;
        final PWEBTABLEFILTER _getListaAlert_filterTbldateProssBoll = null;
        final PWEBTABLEFILTER _getListaAlert_filterTblConsStim = null;
        final PWEBTABLEFILTER _getListaAlert_filterTbldocPagare = null;
        final String _getListaAlert_soggettoCod = "";
        final String _getListaAlert_fornituraCod = "";
        final RESULTMSG _getListaAlert__return = port.getListaAlert(_getListaAlert_multicompany, _getListaAlert_filterTbldateProssBoll, _getListaAlert_filterTblConsStim, _getListaAlert_filterTbldocPagare, _getListaAlert_soggettoCod, _getListaAlert_fornituraCod);
        System.out.println("getListaAlert.result=" + _getListaAlert__return);
        System.out.println("Invoking getConsumoStimatoProssimaBolletta...");
        final INFOMULTICOMPANY _getConsumoStimatoProssimaBolletta_multicompany = null;
        final PWEBTABLEFILTER _getConsumoStimatoProssimaBolletta_filter = null;
        final String _getConsumoStimatoProssimaBolletta_soggettoCod = "";
        final String _getConsumoStimatoProssimaBolletta_fornituraCod = "";
        final RESULTMSG _getConsumoStimatoProssimaBolletta__return = port.getConsumoStimatoProssimaBolletta(_getConsumoStimatoProssimaBolletta_multicompany, _getConsumoStimatoProssimaBolletta_filter, _getConsumoStimatoProssimaBolletta_soggettoCod, _getConsumoStimatoProssimaBolletta_fornituraCod);
        System.out.println("getConsumoStimatoProssimaBolletta.result=" + _getConsumoStimatoProssimaBolletta__return);
        System.out.println("Invoking getInfoMulticompany...");
        final INFOMULTICOMPANY _getInfoMulticompany_mcomp = null;
        final RESULTMSG _getInfoMulticompany__return = port.getInfoMulticompany(_getInfoMulticompany_mcomp);
        System.out.println("getInfoMulticompany.result=" + _getInfoMulticompany__return);
        System.out.println("Invoking setNewsletter...");
        final INFOMULTICOMPANY _setNewsletter_multicompany = null;
        final String _setNewsletter_soggettoCOD = "";
        final Boolean _setNewsletter_adesioneNewsLetter = null;
        final RESULTMSG _setNewsletter__return = port.setNewsletter(_setNewsletter_multicompany, _setNewsletter_soggettoCOD, _setNewsletter_adesioneNewsLetter);
        System.out.println("setNewsletter.result=" + _setNewsletter__return);
        System.out.println("Invoking attivaPaperless...");
        final INFOMULTICOMPANY _attivaPaperless_multicompany = null;
        final String _attivaPaperless_codFornitura = "";
        final String _attivaPaperless_email = "";
        final RESULTMSG _attivaPaperless__return = port.attivaPaperless(_attivaPaperless_multicompany, _attivaPaperless_codFornitura, _attivaPaperless_email);
        System.out.println("attivaPaperless.result=" + _attivaPaperless__return);
        System.out.println("Invoking getElencoLingue...");
        final INFOMULTICOMPANY _getElencoLingue_multicompany = null;
        final RESULTMSG _getElencoLingue__return = port.getElencoLingue(_getElencoLingue_multicompany);
        System.out.println("getElencoLingue.result=" + _getElencoLingue__return);
        System.out.println("Invoking getDettaglioServizio...");
        final INFOMULTICOMPANY _getDettaglioServizio_multicompany = null;
        final String _getDettaglioServizio_fornituraCOD = "";
        final RESULTMSG _getDettaglioServizio__return = port.getDettaglioServizio(_getDettaglioServizio_multicompany, _getDettaglioServizio_fornituraCOD);
        System.out.println("getDettaglioServizio.result=" + _getDettaglioServizio__return);
        System.out.println("Invoking getServiziRaggr...");
        final INFOMULTICOMPANY _getServiziRaggr_multicompany = null;
        final PWEBTABLEFILTER _getServiziRaggr_filterTbl = null;
        final ArrayOfSTATOFORNITURA _getServiziRaggr_filterStatiForn = null;
        final String _getServiziRaggr_fornituraCod = "";
        final RESULTMSG _getServiziRaggr__return = port.getServiziRaggr(_getServiziRaggr_multicompany, _getServiziRaggr_filterTbl, _getServiziRaggr_filterStatiForn, _getServiziRaggr_fornituraCod);
        System.out.println("getServiziRaggr.result=" + _getServiziRaggr__return);
        System.out.println("Invoking downloadCurvePrelievoExt...");
        final INFOMULTICOMPANY _downloadCurvePrelievoExt_multicompany = null;
        final String _downloadCurvePrelievoExt_soggettoCod = "";
        final String _downloadCurvePrelievoExt_ruolosoggCod = "";
        final String _downloadCurvePrelievoExt_nominativo = "";
        final String _downloadCurvePrelievoExt_codiceFiscale = "";
        final String _downloadCurvePrelievoExt_partitaIva = "";
        final String _downloadCurvePrelievoExt_soggCodAmm = "";
        final String _downloadCurvePrelievoExt_tipoServizioCod = "";
        final String _downloadCurvePrelievoExt_codicePDRPOD = "";
        final String _downloadCurvePrelievoExt_fornituraCod = "";
        final String _downloadCurvePrelievoExt_contrattoNum = "";
        final String _downloadCurvePrelievoExt_prodottoCod = "";
        final ArrayOfSTATOFORNITURA _downloadCurvePrelievoExt_elencoStati = null;
        final XMLGregorianCalendar _downloadCurvePrelievoExt_periodoIni = null;
        final XMLGregorianCalendar _downloadCurvePrelievoExt_periodoFin = null;
        final TIPOFILE _downloadCurvePrelievoExt_tipoFile = null;
        final RESULTMSG _downloadCurvePrelievoExt__return = port.downloadCurvePrelievoExt(_downloadCurvePrelievoExt_multicompany, _downloadCurvePrelievoExt_soggettoCod, _downloadCurvePrelievoExt_ruolosoggCod, _downloadCurvePrelievoExt_nominativo, _downloadCurvePrelievoExt_codiceFiscale, _downloadCurvePrelievoExt_partitaIva, _downloadCurvePrelievoExt_soggCodAmm, _downloadCurvePrelievoExt_tipoServizioCod, _downloadCurvePrelievoExt_codicePDRPOD, _downloadCurvePrelievoExt_fornituraCod, _downloadCurvePrelievoExt_contrattoNum, _downloadCurvePrelievoExt_prodottoCod, _downloadCurvePrelievoExt_elencoStati, _downloadCurvePrelievoExt_periodoIni, _downloadCurvePrelievoExt_periodoFin, _downloadCurvePrelievoExt_tipoFile);
        System.out.println("downloadCurvePrelievoExt.result=" + _downloadCurvePrelievoExt__return);
        System.out.println("Invoking getVie...");
        final INFOMULTICOMPANY _getVie_multicompany = null;
        final String _getVie_provinciaCOD = "";
        final String _getVie_comuneCOD = "";
        final String _getVie_localitaCOD = "";
        final String _getVie_criterioRicerca = "";
        final RESULTMSG _getVie__return = port.getVie(_getVie_multicompany, _getVie_provinciaCOD, _getVie_comuneCOD, _getVie_localitaCOD, _getVie_criterioRicerca);
        System.out.println("getVie.result=" + _getVie__return);
        System.out.println("Invoking getCurvePrelievoExt...");
        final INFOMULTICOMPANY _getCurvePrelievoExt_multicompany = null;
        final String _getCurvePrelievoExt_soggettoCod = "";
        final String _getCurvePrelievoExt_ruolosoggCod = "";
        final String _getCurvePrelievoExt_nominativo = "";
        final String _getCurvePrelievoExt_codiceFiscale = "";
        final String _getCurvePrelievoExt_partitaIva = "";
        final String _getCurvePrelievoExt_soggCodAmm = "";
        final String _getCurvePrelievoExt_tipoServizioCod = "";
        final String _getCurvePrelievoExt_codicePDRPOD = "";
        final String _getCurvePrelievoExt_fornituraCod = "";
        final String _getCurvePrelievoExt_contrattoNum = "";
        final String _getCurvePrelievoExt_prodottoCod = "";
        final ArrayOfSTATOFORNITURA _getCurvePrelievoExt_elencoStati = null;
        final XMLGregorianCalendar _getCurvePrelievoExt_periodoIni = null;
        final XMLGregorianCalendar _getCurvePrelievoExt_periodoFin = null;
        final PWEBTABLEFILTER _getCurvePrelievoExt_filter = null;
        final RESULTMSG _getCurvePrelievoExt__return = port.getCurvePrelievoExt(_getCurvePrelievoExt_multicompany, _getCurvePrelievoExt_soggettoCod, _getCurvePrelievoExt_ruolosoggCod, _getCurvePrelievoExt_nominativo, _getCurvePrelievoExt_codiceFiscale, _getCurvePrelievoExt_partitaIva, _getCurvePrelievoExt_soggCodAmm, _getCurvePrelievoExt_tipoServizioCod, _getCurvePrelievoExt_codicePDRPOD, _getCurvePrelievoExt_fornituraCod, _getCurvePrelievoExt_contrattoNum, _getCurvePrelievoExt_prodottoCod, _getCurvePrelievoExt_elencoStati, _getCurvePrelievoExt_periodoIni, _getCurvePrelievoExt_periodoFin, _getCurvePrelievoExt_filter);
        System.out.println("getCurvePrelievoExt.result=" + _getCurvePrelievoExt__return);
        System.out.println("Invoking setAutoletturaEle...");
        final INFOMULTICOMPANY _setAutoletturaEle_multicompany = null;
        final String _setAutoletturaEle_fornituraCod = "";
        final XMLGregorianCalendar _setAutoletturaEle_dataLettura = null;
        final BigDecimal _setAutoletturaEle_valFascia1 = new BigDecimal("0");
        final BigDecimal _setAutoletturaEle_valFascia2 = new BigDecimal("0");
        final BigDecimal _setAutoletturaEle_valFascia3 = new BigDecimal("0");
        final Boolean _setAutoletturaEle_forzaPeriodo = null;
        final Boolean _setAutoletturaEle_forzaConsumo = null;
        final RESULTMSG _setAutoletturaEle__return = port.setAutoletturaEle(_setAutoletturaEle_multicompany, _setAutoletturaEle_fornituraCod, _setAutoletturaEle_dataLettura, _setAutoletturaEle_valFascia1, _setAutoletturaEle_valFascia2, _setAutoletturaEle_valFascia3, _setAutoletturaEle_forzaPeriodo, _setAutoletturaEle_forzaConsumo);
        System.out.println("setAutoletturaEle.result=" + _setAutoletturaEle__return);
        System.out.println("Invoking getTipiCivici...");
        final INFOMULTICOMPANY _getTipiCivici_multicompany = null;
        final String _getTipiCivici_criterioRicerca = "";
        final RESULTMSG _getTipiCivici__return = port.getTipiCivici(_getTipiCivici_multicompany, _getTipiCivici_criterioRicerca);
        System.out.println("getTipiCivici.result=" + _getTipiCivici__return);
        System.out.println("Invoking getStatiForn...");
        final INFOMULTICOMPANY _getStatiForn_multicompany = null;
        final String _getStatiForn_soggettoCOD = "";
        final String _getStatiForn_ruolosoggCOD = "";
        final RESULTMSG _getStatiForn__return = port.getStatiForn(_getStatiForn_multicompany, _getStatiForn_soggettoCOD, _getStatiForn_ruolosoggCOD);
        System.out.println("getStatiForn.result=" + _getStatiForn__return);
        System.out.println("Invoking gestioneSoggettoProspect...");
        final INFOMULTICOMPANY _gestioneSoggettoProspect_multicompany = null;
        final DATISOGGETTOEXT _gestioneSoggettoProspect_soggettoProspect = null;
        final ArrayOfCONSENSO _gestioneSoggettoProspect_consensi = null;
        final RESULTMSG _gestioneSoggettoProspect__return = port.gestioneSoggettoProspect(_gestioneSoggettoProspect_multicompany, _gestioneSoggettoProspect_soggettoProspect, _gestioneSoggettoProspect_consensi);
        System.out.println("gestioneSoggettoProspect.result=" + _gestioneSoggettoProspect__return);
        System.out.println("Invoking getPDF...");
        final INFOMULTICOMPANY _getPDF_multicompany = null;
        final String _getPDF_documentoID = "";
        final RESULTMSG _getPDF__return = port.getPDF(_getPDF_multicompany, _getPDF_documentoID);
        System.out.println("getPDF.result=" + _getPDF__return);
        System.out.println("Invoking getDataProssimaBolletta...");
        final INFOMULTICOMPANY _getDataProssimaBolletta_multicompany = null;
        final PWEBTABLEFILTER _getDataProssimaBolletta_filter = null;
        final String _getDataProssimaBolletta_soggettoCod = "";
        final String _getDataProssimaBolletta_fornituraCod = "";
        final RESULTMSG _getDataProssimaBolletta__return = port.getDataProssimaBolletta(_getDataProssimaBolletta_multicompany, _getDataProssimaBolletta_filter, _getDataProssimaBolletta_soggettoCod, _getDataProssimaBolletta_fornituraCod);
        System.out.println("getDataProssimaBolletta.result=" + _getDataProssimaBolletta__return);
        System.out.println("Invoking setConsensiSoggetto...");
        final INFOMULTICOMPANY _setConsensiSoggetto_multicompany = null;
        final String _setConsensiSoggetto_soggettoCod = "";
        final ArrayOfCONSENSO _setConsensiSoggetto_consensi = null;
        final RESULTMSG _setConsensiSoggetto__return = port.setConsensiSoggetto(_setConsensiSoggetto_multicompany, _setConsensiSoggetto_soggettoCod, _setConsensiSoggetto_consensi);
        System.out.println("setConsensiSoggetto.result=" + _setConsensiSoggetto__return);
        System.out.println("Invoking inserimentoRichiesta...");
        final INFOMULTICOMPANY _inserimentoRichiesta_multicompany = null;
        final DATIINSERIMENTORICHIESTA _inserimentoRichiesta_datiRichiesta = null;
        final RESULTMSG _inserimentoRichiesta__return = port.inserimentoRichiesta(_inserimentoRichiesta_multicompany, _inserimentoRichiesta_datiRichiesta);
        System.out.println("inserimentoRichiesta.result=" + _inserimentoRichiesta__return);
        System.out.println("Invoking downloadCurvePrelievoOrarieEE...");
        final INFOMULTICOMPANY _downloadCurvePrelievoOrarieEE_multicompany = null;
        final ArrayOfFORNITURACP _downloadCurvePrelievoOrarieEE_elencoForniture = null;
        final XMLGregorianCalendar _downloadCurvePrelievoOrarieEE_periodoIni = null;
        final XMLGregorianCalendar _downloadCurvePrelievoOrarieEE_periodoFin = null;
        final TIPOFILE _downloadCurvePrelievoOrarieEE_tipoFile = null;
        final RESULTMSG _downloadCurvePrelievoOrarieEE__return = port.downloadCurvePrelievoOrarieEE(_downloadCurvePrelievoOrarieEE_multicompany, _downloadCurvePrelievoOrarieEE_elencoForniture, _downloadCurvePrelievoOrarieEE_periodoIni, _downloadCurvePrelievoOrarieEE_periodoFin, _downloadCurvePrelievoOrarieEE_tipoFile);
        System.out.println("downloadCurvePrelievoOrarieEE.result=" + _downloadCurvePrelievoOrarieEE__return);
        System.out.println("Invoking getLettureConsumi...");
        final INFOMULTICOMPANY _getLettureConsumi_multicompany = null;
        final PWEBTABLEFILTER _getLettureConsumi_filter = null;
        final String _getLettureConsumi_fornituraCod = "";
        final PERIODO _getLettureConsumi_periodo = null;
        final RESULTMSG _getLettureConsumi__return = port.getLettureConsumi(_getLettureConsumi_multicompany, _getLettureConsumi_filter, _getLettureConsumi_fornituraCod, _getLettureConsumi_periodo);
        System.out.println("getLettureConsumi.result=" + _getLettureConsumi__return);
        System.out.println("Invoking eliminaAccount...");
        final INFOMULTICOMPANY _eliminaAccount_multicompany = null;
        final String _eliminaAccount_account = "";
        final String _eliminaAccount_password = "";
        final RESULTMSG _eliminaAccount__return = port.eliminaAccount(_eliminaAccount_multicompany, _eliminaAccount_account, _eliminaAccount_password);
        System.out.println("eliminaAccount.result=" + _eliminaAccount__return);
        System.out.println("Invoking getNazioni...");
        final INFOMULTICOMPANY _getNazioni_multicompany = null;
        final String _getNazioni_criterioRicerca = "";
        final RESULTMSG _getNazioni__return = port.getNazioni(_getNazioni_multicompany, _getNazioni_criterioRicerca);
        System.out.println("getNazioni.result=" + _getNazioni__return);
        System.out.println("Invoking getProdotti...");
        final INFOMULTICOMPANY _getProdotti_multicompany = null;
        final FiltriProdotto _getProdotti_filtriProdotto = null;
        final RESULTMSG _getProdotti__return = port.getProdotti(_getProdotti_multicompany, _getProdotti_filtriProdotto);
        System.out.println("getProdotti.result=" + _getProdotti__return);
        System.out.println("Invoking inserimentoRichiestaDD...");
        final INFOMULTICOMPANY _inserimentoRichiestaDD_multicompany = null;
        final DATIINSERIMENTORICHIESTA _inserimentoRichiestaDD_datiRichiesta = null;
        final RESULTMSG _inserimentoRichiestaDD__return = port.inserimentoRichiestaDD(_inserimentoRichiestaDD_multicompany, _inserimentoRichiestaDD_datiRichiesta);
        System.out.println("inserimentoRichiestaDD.result=" + _inserimentoRichiestaDD__return);
        System.out.println("Invoking getPeriodoInserimentoAutoletturaFlusso...");
        final INFOMULTICOMPANY _getPeriodoInserimentoAutoletturaFlusso_multicompany = null;
        final String _getPeriodoInserimentoAutoletturaFlusso_fornituraCod = "";
        final XMLGregorianCalendar _getPeriodoInserimentoAutoletturaFlusso_dataLettura = null;
        final TIPOAUTOLETTURA _getPeriodoInserimentoAutoletturaFlusso_tipoAutoLettura = null;
        final RESULTMSG _getPeriodoInserimentoAutoletturaFlusso__return = port.getPeriodoInserimentoAutoletturaFlusso(_getPeriodoInserimentoAutoletturaFlusso_multicompany, _getPeriodoInserimentoAutoletturaFlusso_fornituraCod, _getPeriodoInserimentoAutoletturaFlusso_dataLettura, _getPeriodoInserimentoAutoletturaFlusso_tipoAutoLettura);
        System.out.println("getPeriodoInserimentoAutoletturaFlusso.result=" + _getPeriodoInserimentoAutoletturaFlusso__return);
        System.out.println("Invoking recuperaCredenzialiAccount...");
        final INFOMULTICOMPANY _recuperaCredenzialiAccount_multicompany = null;
        final Boolean _recuperaCredenzialiAccount_recPassword = null;
        final DATISOGGETTO _recuperaCredenzialiAccount_soggetto = null;
        final RESULTMSG _recuperaCredenzialiAccount__return = port.recuperaCredenzialiAccount(_recuperaCredenzialiAccount_multicompany, _recuperaCredenzialiAccount_recPassword, _recuperaCredenzialiAccount_soggetto);
        System.out.println("recuperaCredenzialiAccount.result=" + _recuperaCredenzialiAccount__return);
        System.out.println("Invoking elencoAllegati...");
        final INFOMULTICOMPANY _elencoAllegati_multicompany = null;
        final ALLEGATORICHIESTA _elencoAllegati_filtro = null;
        final RESULTMSG _elencoAllegati__return = port.elencoAllegati(_elencoAllegati_multicompany, _elencoAllegati_filtro);
        System.out.println("elencoAllegati.result=" + _elencoAllegati__return);
        System.out.println("Invoking getPeriodoInserimentoAutolettura...");
        final INFOMULTICOMPANY _getPeriodoInserimentoAutolettura_multicompany = null;
        final String _getPeriodoInserimentoAutolettura_fornituraCod = "";
        final XMLGregorianCalendar _getPeriodoInserimentoAutolettura_dataLettura = null;
        final RESULTMSG _getPeriodoInserimentoAutolettura__return = port.getPeriodoInserimentoAutolettura(_getPeriodoInserimentoAutolettura_multicompany, _getPeriodoInserimentoAutolettura_fornituraCod, _getPeriodoInserimentoAutolettura_dataLettura);
        System.out.println("getPeriodoInserimentoAutolettura.result=" + _getPeriodoInserimentoAutolettura__return);
        System.out.println("Invoking downloadEstrattoContoServizio...");
        final INFOMULTICOMPANY _downloadEstrattoContoServizio_multicompany = null;
        final String _downloadEstrattoContoServizio_soggettoCod = "";
        final String _downloadEstrattoContoServizio_ruoloSoggettoCod = "";
        final String _downloadEstrattoContoServizio_nominativo = "";
        final String _downloadEstrattoContoServizio_codiceFiscale = "";
        final String _downloadEstrattoContoServizio_fornituraCod = "";
        final String _downloadEstrattoContoServizio_contrattoNum = "";
        final String _downloadEstrattoContoServizio_prodottoCod = "";
        final ArrayOfSTATOFORNITURA _downloadEstrattoContoServizio_elencoStati = null;
        final String _downloadEstrattoContoServizio_soggettoCodAmm = "";
        final String _downloadEstrattoContoServizio_partitaIVA = "";
        final String _downloadEstrattoContoServizio_tipoServizioCod = "";
        final String _downloadEstrattoContoServizio_codicePODPDR = "";
        final RESULTMSG _downloadEstrattoContoServizio__return = port.downloadEstrattoContoServizio(_downloadEstrattoContoServizio_multicompany, _downloadEstrattoContoServizio_soggettoCod, _downloadEstrattoContoServizio_ruoloSoggettoCod, _downloadEstrattoContoServizio_nominativo, _downloadEstrattoContoServizio_codiceFiscale, _downloadEstrattoContoServizio_fornituraCod, _downloadEstrattoContoServizio_contrattoNum, _downloadEstrattoContoServizio_prodottoCod, _downloadEstrattoContoServizio_elencoStati, _downloadEstrattoContoServizio_soggettoCodAmm, _downloadEstrattoContoServizio_partitaIVA, _downloadEstrattoContoServizio_tipoServizioCod, _downloadEstrattoContoServizio_codicePODPDR);
        System.out.println("downloadEstrattoContoServizio.result=" + _downloadEstrattoContoServizio__return);
        System.out.println("Invoking getListaAttributiDyn...");
        final INFOMULTICOMPANY _getListaAttributiDyn_multicompany = null;
        final RESULTMSG _getListaAttributiDyn__return = port.getListaAttributiDyn(_getListaAttributiDyn_multicompany);
        System.out.println("getListaAttributiDyn.result=" + _getListaAttributiDyn__return);
        System.out.println("Invoking getCAPDaComune...");
        final INFOMULTICOMPANY _getCAPDaComune_multicompany = null;
        final String _getCAPDaComune_comuneCOD = "";
        final String _getCAPDaComune_localitaCOD = "";
        final RESULTMSG _getCAPDaComune__return = port.getCAPDaComune(_getCAPDaComune_multicompany, _getCAPDaComune_comuneCOD, _getCAPDaComune_localitaCOD);
        System.out.println("getCAPDaComune.result=" + _getCAPDaComune__return);
        System.out.println("Invoking getCurvePrelievo...");
        final INFOMULTICOMPANY _getCurvePrelievo_multicompany = null;
        final ArrayOfFORNITURACP _getCurvePrelievo_elencoForniture = null;
        final XMLGregorianCalendar _getCurvePrelievo_periodoIni = null;
        final XMLGregorianCalendar _getCurvePrelievo_periodoFin = null;
        final PWEBTABLEFILTER _getCurvePrelievo_filter = null;
        final RESULTMSG _getCurvePrelievo__return = port.getCurvePrelievo(_getCurvePrelievo_multicompany, _getCurvePrelievo_elencoForniture, _getCurvePrelievo_periodoIni, _getCurvePrelievo_periodoFin, _getCurvePrelievo_filter);
        System.out.println("getCurvePrelievo.result=" + _getCurvePrelievo__return);
        System.out.println("Invoking downloadAllegato...");
        final INFOMULTICOMPANY _downloadAllegato_multicompany = null;
        final ALLEGATORICHIESTA _downloadAllegato_filtro = null;
        final RESULTMSG _downloadAllegato__return = port.downloadAllegato(_downloadAllegato_multicompany, _downloadAllegato_filtro);
        System.out.println("downloadAllegato.result=" + _downloadAllegato__return);
        System.out.println("Invoking inserimentoSoggettoProspect...");
        final INFOMULTICOMPANY _inserimentoSoggettoProspect_multicompany = null;
        final DATISOGGETTO _inserimentoSoggettoProspect_soggettoProspect = null;
        final ArrayOfCONSENSO _inserimentoSoggettoProspect_consensi = null;
        final RESULTMSG _inserimentoSoggettoProspect__return = port.inserimentoSoggettoProspect(_inserimentoSoggettoProspect_multicompany, _inserimentoSoggettoProspect_soggettoProspect, _inserimentoSoggettoProspect_consensi);
        System.out.println("inserimentoSoggettoProspect.result=" + _inserimentoSoggettoProspect__return);
        System.out.println("Invoking getUtentiNewsletterExt...");
        final INFOMULTICOMPANY _getUtentiNewsletterExt_multicompany = null;
        final PWEBTABLEFILTER _getUtentiNewsletterExt_filter = null;
        final String _getUtentiNewsletterExt_filtroAttrDyn = "";
        final RESULTMSG _getUtentiNewsletterExt__return = port.getUtentiNewsletterExt(_getUtentiNewsletterExt_multicompany, _getUtentiNewsletterExt_filter, _getUtentiNewsletterExt_filtroAttrDyn);
        System.out.println("getUtentiNewsletterExt.result=" + _getUtentiNewsletterExt__return);
        System.out.println("Invoking getRuoli...");
        final INFOMULTICOMPANY _getRuoli_multicompany = null;
        final RESULTMSG _getRuoli__return = port.getRuoli(_getRuoli_multicompany);
        System.out.println("getRuoli.result=" + _getRuoli__return);
        System.out.println("Invoking getGerarchiaSoggetto...");
        final INFOMULTICOMPANY _getGerarchiaSoggetto_multicompany = null;
        final String _getGerarchiaSoggetto_soggettoCod = "";
        final String _getGerarchiaSoggetto_ruolo = "";
        final RESULTMSG _getGerarchiaSoggetto__return = port.getGerarchiaSoggetto(_getGerarchiaSoggetto_multicompany, _getGerarchiaSoggetto_soggettoCod, _getGerarchiaSoggetto_ruolo);
        System.out.println("getGerarchiaSoggetto.result=" + _getGerarchiaSoggetto__return);
        System.exit(0);
    }
}
