/* * SPDX-License-Identifier: AGPL-3.0-or-later * * C Copyright 2023 Regione Piemonte * */
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-b10
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2018.06.23 at 09:47:42 PM CEST
//

package it.eng.auriga.repository2.jaxws.jaxbBean.feedbackOperazioniaurigalottidoc;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="TipoRichiesta" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="ESITO_LOTTO_DOC"/>
 *             &lt;enumeration value="AGG_STATI_NOTIFICA_LOTTI_DOC"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="IdLottoDoc">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}normalizedString">
 *             &lt;minLength value="1"/>
 *             &lt;maxLength value="30"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "RequestFeedbackElabDocsList")
public class RequestFeedbackElabDocsList {

	@XmlAttribute(name = "TipoRichiesta", required = true)
	protected String tipoRichiesta;
	@XmlAttribute(name = "IdLottoDoc")
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String idLottoDoc;

	/**
	 * Gets the value of the tipoRichiesta property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getTipoRichiesta() {
		return tipoRichiesta;
	}

	/**
	 * Sets the value of the tipoRichiesta property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setTipoRichiesta(String value) {
		this.tipoRichiesta = value;
	}

	/**
	 * Gets the value of the idLottoDoc property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getIdLottoDoc() {
		return idLottoDoc;
	}

	/**
	 * Sets the value of the idLottoDoc property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setIdLottoDoc(String value) {
		this.idLottoDoc = value;
	}

}
