/* * SPDX-License-Identifier: AGPL-3.0-or-later * * C Copyright 2023 Regione Piemonte * */

// Generated 22-set-2016 12.14.09 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CvtAnagIndId generated by hbm2java
 */
@Embeddable
public class CvtAnagIndId implements java.io.Serializable {

	private int idAnag;
	private String flgTpInd;
	private Date dtIniInd;

	public CvtAnagIndId() {
	}

	public CvtAnagIndId(int idAnag, String flgTpInd, Date dtIniInd) {
		this.idAnag = idAnag;
		this.flgTpInd = flgTpInd;
		this.dtIniInd = dtIniInd;
	}

	@Column(name = "ID_ANAG", nullable = false, precision = 9, scale = 0)
	public int getIdAnag() {
		return this.idAnag;
	}

	public void setIdAnag(int idAnag) {
		this.idAnag = idAnag;
	}

	@Column(name = "FLG_TP_IND", nullable = false, length = 2)
	public String getFlgTpInd() {
		return this.flgTpInd;
	}

	public void setFlgTpInd(String flgTpInd) {
		this.flgTpInd = flgTpInd;
	}

	@Column(name = "DT_INI_IND", nullable = false, length = 7)
	public Date getDtIniInd() {
		return this.dtIniInd;
	}

	public void setDtIniInd(Date dtIniInd) {
		this.dtIniInd = dtIniInd;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CvtAnagIndId))
			return false;
		CvtAnagIndId castOther = (CvtAnagIndId) other;

		return (this.getIdAnag() == castOther.getIdAnag())
				&& ((this.getFlgTpInd() == castOther.getFlgTpInd()) || (this
						.getFlgTpInd() != null
						&& castOther.getFlgTpInd() != null && this
						.getFlgTpInd().equals(castOther.getFlgTpInd())))
				&& ((this.getDtIniInd() == castOther.getDtIniInd()) || (this
						.getDtIniInd() != null
						&& castOther.getDtIniInd() != null && this
						.getDtIniInd().equals(castOther.getDtIniInd())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdAnag();
		result = 37 * result
				+ (getFlgTpInd() == null ? 0 : this.getFlgTpInd().hashCode());
		result = 37 * result
				+ (getDtIniInd() == null ? 0 : this.getDtIniInd().hashCode());
		return result;
	}

}
