/* * SPDX-License-Identifier: AGPL-3.0-or-later * * C Copyright 2023 Regione Piemonte * */

// Generated 22-set-2016 12.14.09 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CvtDecScadenze generated by hbm2java
 */
@Entity
@Table(name = "CVT_DEC_SCADENZE")
public class CvtDecScadenze implements java.io.Serializable {

	private CvtDecScadenzeId id;
	private String desTpScadenza;
	private String tpFlusso;
	private Byte maxNumIter;
	private String servizio;
	private Date dtIns;
	private Integer uteIns;
	private Date dtUltMod;
	private Integer uteUltMod;
	private Set<CvtScadenziario> cvtScadenziarios = new HashSet<CvtScadenziario>(
			0);

	public CvtDecScadenze() {
	}

	public CvtDecScadenze(CvtDecScadenzeId id, String desTpScadenza) {
		this.id = id;
		this.desTpScadenza = desTpScadenza;
	}

	public CvtDecScadenze(CvtDecScadenzeId id, String desTpScadenza,
			String tpFlusso, Byte maxNumIter, String servizio, Date dtIns,
			Integer uteIns, Date dtUltMod, Integer uteUltMod,
			Set<CvtScadenziario> cvtScadenziarios) {
		this.id = id;
		this.desTpScadenza = desTpScadenza;
		this.tpFlusso = tpFlusso;
		this.maxNumIter = maxNumIter;
		this.servizio = servizio;
		this.dtIns = dtIns;
		this.uteIns = uteIns;
		this.dtUltMod = dtUltMod;
		this.uteUltMod = uteUltMod;
		this.cvtScadenziarios = cvtScadenziarios;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "codTpApplic", column = @Column(name = "COD_TP_APPLIC", nullable = false, length = 1)),
			@AttributeOverride(name = "codTpScadenza", column = @Column(name = "COD_TP_SCADENZA", nullable = false, length = 3)) })
	public CvtDecScadenzeId getId() {
		return this.id;
	}

	public void setId(CvtDecScadenzeId id) {
		this.id = id;
	}

	@Column(name = "DES_TP_SCADENZA", nullable = false, length = 100)
	public String getDesTpScadenza() {
		return this.desTpScadenza;
	}

	public void setDesTpScadenza(String desTpScadenza) {
		this.desTpScadenza = desTpScadenza;
	}

	@Column(name = "TP_FLUSSO", length = 1)
	public String getTpFlusso() {
		return this.tpFlusso;
	}

	public void setTpFlusso(String tpFlusso) {
		this.tpFlusso = tpFlusso;
	}

	@Column(name = "MAX_NUM_ITER", precision = 2, scale = 0)
	public Byte getMaxNumIter() {
		return this.maxNumIter;
	}

	public void setMaxNumIter(Byte maxNumIter) {
		this.maxNumIter = maxNumIter;
	}

	@Column(name = "SERVIZIO", length = 30)
	public String getServizio() {
		return this.servizio;
	}

	public void setServizio(String servizio) {
		this.servizio = servizio;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DT_INS", length = 7)
	public Date getDtIns() {
		return this.dtIns;
	}

	public void setDtIns(Date dtIns) {
		this.dtIns = dtIns;
	}

	@Column(name = "UTE_INS", precision = 6, scale = 0)
	public Integer getUteIns() {
		return this.uteIns;
	}

	public void setUteIns(Integer uteIns) {
		this.uteIns = uteIns;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DT_ULT_MOD", length = 7)
	public Date getDtUltMod() {
		return this.dtUltMod;
	}

	public void setDtUltMod(Date dtUltMod) {
		this.dtUltMod = dtUltMod;
	}

	@Column(name = "UTE_ULT_MOD", precision = 6, scale = 0)
	public Integer getUteUltMod() {
		return this.uteUltMod;
	}

	public void setUteUltMod(Integer uteUltMod) {
		this.uteUltMod = uteUltMod;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cvtDecScadenze")
	public Set<CvtScadenziario> getCvtScadenziarios() {
		return this.cvtScadenziarios;
	}

	public void setCvtScadenziarios(Set<CvtScadenziario> cvtScadenziarios) {
		this.cvtScadenziarios = cvtScadenziarios;
	}

}
