/* * SPDX-License-Identifier: AGPL-3.0-or-later * * C Copyright 2023 Regione Piemonte * */

// Generated 22-set-2016 12.14.09 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CvtEnti generated by hbm2java
 */
@Entity
@Table(name = "CVT_ENTI")
public class CvtEnti implements java.io.Serializable {

	private String codEnte;
	private String desEnte;
	private Date dtIns;
	private Integer uteIns;
	private Date dtUltMod;
	private Integer uteUltMod;
	private Set<PttClobCsv> pttClobCsvs = new HashSet<PttClobCsv>(0);

	public CvtEnti() {
	}

	public CvtEnti(String codEnte) {
		this.codEnte = codEnte;
	}

	public CvtEnti(String codEnte, String desEnte, Date dtIns, Integer uteIns,
			Date dtUltMod, Integer uteUltMod, Set<PttClobCsv> pttClobCsvs) {
		this.codEnte = codEnte;
		this.desEnte = desEnte;
		this.dtIns = dtIns;
		this.uteIns = uteIns;
		this.dtUltMod = dtUltMod;
		this.uteUltMod = uteUltMod;
		this.pttClobCsvs = pttClobCsvs;
	}

	@Id
	@Column(name = "COD_ENTE", unique = true, nullable = false, length = 3)
	public String getCodEnte() {
		return this.codEnte;
	}

	public void setCodEnte(String codEnte) {
		this.codEnte = codEnte;
	}

	@Column(name = "DES_ENTE", length = 100)
	public String getDesEnte() {
		return this.desEnte;
	}

	public void setDesEnte(String desEnte) {
		this.desEnte = desEnte;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DT_INS", length = 7)
	public Date getDtIns() {
		return this.dtIns;
	}

	public void setDtIns(Date dtIns) {
		this.dtIns = dtIns;
	}

	@Column(name = "UTE_INS", precision = 6, scale = 0)
	public Integer getUteIns() {
		return this.uteIns;
	}

	public void setUteIns(Integer uteIns) {
		this.uteIns = uteIns;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DT_ULT_MOD", length = 7)
	public Date getDtUltMod() {
		return this.dtUltMod;
	}

	public void setDtUltMod(Date dtUltMod) {
		this.dtUltMod = dtUltMod;
	}

	@Column(name = "UTE_ULT_MOD", precision = 6, scale = 0)
	public Integer getUteUltMod() {
		return this.uteUltMod;
	}

	public void setUteUltMod(Integer uteUltMod) {
		this.uteUltMod = uteUltMod;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cvtEnti")
	public Set<PttClobCsv> getPttClobCsvs() {
		return this.pttClobCsvs;
	}

	public void setPttClobCsvs(Set<PttClobCsv> pttClobCsvs) {
		this.pttClobCsvs = pttClobCsvs;
	}

}
