/* * SPDX-License-Identifier: AGPL-3.0-or-later * * C Copyright 2023 Regione Piemonte * */

// Generated 22-set-2016 12.14.09 by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * CvtGruppi generated by hbm2java
 */
@Entity
@Table(name = "CVT_GRUPPI", uniqueConstraints = {
		@UniqueConstraint(columnNames = "APPARTENENTI"),
		@UniqueConstraint(columnNames = "NOME_GRUPPO") })
public class CvtGruppi implements java.io.Serializable {

	private int idGruppo;
	private String nomeGruppo;
	private Boolean flgEnabled;
	private Boolean flgDiSistema;
	private Boolean flgDiDefInAcl;
	private Serializable appartenenti;
	private String note;
	private Date dtIns;
	private Integer uteIns;
	private Date dtUltMod;
	private Integer uteUltMod;

	public CvtGruppi() {
	}

	public CvtGruppi(int idGruppo, String nomeGruppo) {
		this.idGruppo = idGruppo;
		this.nomeGruppo = nomeGruppo;
	}

	public CvtGruppi(int idGruppo, String nomeGruppo, Boolean flgEnabled,
			Boolean flgDiSistema, Boolean flgDiDefInAcl,
			Serializable appartenenti, String note, Date dtIns, Integer uteIns,
			Date dtUltMod, Integer uteUltMod) {
		this.idGruppo = idGruppo;
		this.nomeGruppo = nomeGruppo;
		this.flgEnabled = flgEnabled;
		this.flgDiSistema = flgDiSistema;
		this.flgDiDefInAcl = flgDiDefInAcl;
		this.appartenenti = appartenenti;
		this.note = note;
		this.dtIns = dtIns;
		this.uteIns = uteIns;
		this.dtUltMod = dtUltMod;
		this.uteUltMod = uteUltMod;
	}

	@Id
	@Column(name = "ID_GRUPPO", unique = true, nullable = false, precision = 8, scale = 0)
	public int getIdGruppo() {
		return this.idGruppo;
	}

	public void setIdGruppo(int idGruppo) {
		this.idGruppo = idGruppo;
	}

	@Column(name = "NOME_GRUPPO", unique = true, nullable = false, length = 150)
	public String getNomeGruppo() {
		return this.nomeGruppo;
	}

	public void setNomeGruppo(String nomeGruppo) {
		this.nomeGruppo = nomeGruppo;
	}

	@Column(name = "FLG_ENABLED", precision = 1, scale = 0)
	public Boolean getFlgEnabled() {
		return this.flgEnabled;
	}

	public void setFlgEnabled(Boolean flgEnabled) {
		this.flgEnabled = flgEnabled;
	}

	@Column(name = "FLG_DI_SISTEMA", precision = 1, scale = 0)
	public Boolean getFlgDiSistema() {
		return this.flgDiSistema;
	}

	public void setFlgDiSistema(Boolean flgDiSistema) {
		this.flgDiSistema = flgDiSistema;
	}

	@Column(name = "FLG_DI_DEF_IN_ACL", precision = 1, scale = 0)
	public Boolean getFlgDiDefInAcl() {
		return this.flgDiDefInAcl;
	}

	public void setFlgDiDefInAcl(Boolean flgDiDefInAcl) {
		this.flgDiDefInAcl = flgDiDefInAcl;
	}

	@Column(name = "APPARTENENTI", unique = true)
	public Serializable getAppartenenti() {
		return this.appartenenti;
	}

	public void setAppartenenti(Serializable appartenenti) {
		this.appartenenti = appartenenti;
	}

	@Column(name = "NOTE", length = 500)
	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DT_INS", length = 7)
	public Date getDtIns() {
		return this.dtIns;
	}

	public void setDtIns(Date dtIns) {
		this.dtIns = dtIns;
	}

	@Column(name = "UTE_INS", precision = 6, scale = 0)
	public Integer getUteIns() {
		return this.uteIns;
	}

	public void setUteIns(Integer uteIns) {
		this.uteIns = uteIns;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DT_ULT_MOD", length = 7)
	public Date getDtUltMod() {
		return this.dtUltMod;
	}

	public void setDtUltMod(Date dtUltMod) {
		this.dtUltMod = dtUltMod;
	}

	@Column(name = "UTE_ULT_MOD", precision = 6, scale = 0)
	public Integer getUteUltMod() {
		return this.uteUltMod;
	}

	public void setUteUltMod(Integer uteUltMod) {
		this.uteUltMod = uteUltMod;
	}

}
