/* * SPDX-License-Identifier: AGPL-3.0-or-later * * C Copyright 2023 Regione Piemonte * */

// Generated 22-set-2016 12.14.09 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CvtProcedimenti generated by hbm2java
 */
@Entity
@Table(name = "CVT_PROCEDIMENTI")
public class CvtProcedimenti implements java.io.Serializable {

	private int idProc;
	private CvtUo cvtUoByIdUoRsp;
	private CvtUo cvtUoByIdUoRspOper;
	private CvtDecProc cvtDecProc;
	private CvtProcedimenti cvtProcedimenti;
	private Integer idDoc;
	private Byte numCopia;
	private String tpFlusso;
	private String idFlusso;
	private String flgSistema;
	private Date dtAvvio;
	private Date dtDecorr;
	private Date dtSosp;
	private Date dtInterr;
	private Date dtRipresa;
	private Date dtChiusura;
	private Date dtRiapertura;
	private String flgStato;
	private String flgChiusura;
	private Byte nroSosp;
	private Date dtIns;
	private Integer uteIns;
	private Date dtUltMod;
	private Integer uteUltMod;
	private Set<PttSottofasc> pttSottofascs = new HashSet<PttSottofasc>(0);
	private Set<CvtTempiProc> cvtTempiProcs = new HashSet<CvtTempiProc>(0);
	private Set<CvtProcedimenti> cvtProcedimentis = new HashSet<CvtProcedimenti>(
			0);

	public CvtProcedimenti() {
	}

	public CvtProcedimenti(int idProc, CvtUo cvtUoByIdUoRsp,
			CvtUo cvtUoByIdUoRspOper, CvtDecProc cvtDecProc, Date dtAvvio,
			String flgStato) {
		this.idProc = idProc;
		this.cvtUoByIdUoRsp = cvtUoByIdUoRsp;
		this.cvtUoByIdUoRspOper = cvtUoByIdUoRspOper;
		this.cvtDecProc = cvtDecProc;
		this.dtAvvio = dtAvvio;
		this.flgStato = flgStato;
	}

	public CvtProcedimenti(int idProc, CvtUo cvtUoByIdUoRsp,
			CvtUo cvtUoByIdUoRspOper, CvtDecProc cvtDecProc,
			CvtProcedimenti cvtProcedimenti, Integer idDoc, Byte numCopia,
			String tpFlusso, String idFlusso, String flgSistema, Date dtAvvio,
			Date dtDecorr, Date dtSosp, Date dtInterr, Date dtRipresa,
			Date dtChiusura, Date dtRiapertura, String flgStato,
			String flgChiusura, Byte nroSosp, Date dtIns, Integer uteIns,
			Date dtUltMod, Integer uteUltMod, Set<PttSottofasc> pttSottofascs,
			Set<CvtTempiProc> cvtTempiProcs,
			Set<CvtProcedimenti> cvtProcedimentis) {
		this.idProc = idProc;
		this.cvtUoByIdUoRsp = cvtUoByIdUoRsp;
		this.cvtUoByIdUoRspOper = cvtUoByIdUoRspOper;
		this.cvtDecProc = cvtDecProc;
		this.cvtProcedimenti = cvtProcedimenti;
		this.idDoc = idDoc;
		this.numCopia = numCopia;
		this.tpFlusso = tpFlusso;
		this.idFlusso = idFlusso;
		this.flgSistema = flgSistema;
		this.dtAvvio = dtAvvio;
		this.dtDecorr = dtDecorr;
		this.dtSosp = dtSosp;
		this.dtInterr = dtInterr;
		this.dtRipresa = dtRipresa;
		this.dtChiusura = dtChiusura;
		this.dtRiapertura = dtRiapertura;
		this.flgStato = flgStato;
		this.flgChiusura = flgChiusura;
		this.nroSosp = nroSosp;
		this.dtIns = dtIns;
		this.uteIns = uteIns;
		this.dtUltMod = dtUltMod;
		this.uteUltMod = uteUltMod;
		this.pttSottofascs = pttSottofascs;
		this.cvtTempiProcs = cvtTempiProcs;
		this.cvtProcedimentis = cvtProcedimentis;
	}

	@Id
	@Column(name = "ID_PROC", unique = true, nullable = false, precision = 8, scale = 0)
	public int getIdProc() {
		return this.idProc;
	}

	public void setIdProc(int idProc) {
		this.idProc = idProc;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_UO_RSP", nullable = false)
	public CvtUo getCvtUoByIdUoRsp() {
		return this.cvtUoByIdUoRsp;
	}

	public void setCvtUoByIdUoRsp(CvtUo cvtUoByIdUoRsp) {
		this.cvtUoByIdUoRsp = cvtUoByIdUoRsp;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_UO_RSP_OPER", nullable = false)
	public CvtUo getCvtUoByIdUoRspOper() {
		return this.cvtUoByIdUoRspOper;
	}

	public void setCvtUoByIdUoRspOper(CvtUo cvtUoByIdUoRspOper) {
		this.cvtUoByIdUoRspOper = cvtUoByIdUoRspOper;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_TP_PROC", nullable = false)
	public CvtDecProc getCvtDecProc() {
		return this.cvtDecProc;
	}

	public void setCvtDecProc(CvtDecProc cvtDecProc) {
		this.cvtDecProc = cvtDecProc;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_PROC_PARENT")
	public CvtProcedimenti getCvtProcedimenti() {
		return this.cvtProcedimenti;
	}

	public void setCvtProcedimenti(CvtProcedimenti cvtProcedimenti) {
		this.cvtProcedimenti = cvtProcedimenti;
	}

	@Column(name = "ID_DOC", precision = 8, scale = 0)
	public Integer getIdDoc() {
		return this.idDoc;
	}

	public void setIdDoc(Integer idDoc) {
		this.idDoc = idDoc;
	}

	@Column(name = "NUM_COPIA", precision = 2, scale = 0)
	public Byte getNumCopia() {
		return this.numCopia;
	}

	public void setNumCopia(Byte numCopia) {
		this.numCopia = numCopia;
	}

	@Column(name = "TP_FLUSSO", length = 8)
	public String getTpFlusso() {
		return this.tpFlusso;
	}

	public void setTpFlusso(String tpFlusso) {
		this.tpFlusso = tpFlusso;
	}

	@Column(name = "ID_FLUSSO", length = 240)
	public String getIdFlusso() {
		return this.idFlusso;
	}

	public void setIdFlusso(String idFlusso) {
		this.idFlusso = idFlusso;
	}

	@Column(name = "FLG_SISTEMA", length = 2)
	public String getFlgSistema() {
		return this.flgSistema;
	}

	public void setFlgSistema(String flgSistema) {
		this.flgSistema = flgSistema;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DT_AVVIO", nullable = false, length = 7)
	public Date getDtAvvio() {
		return this.dtAvvio;
	}

	public void setDtAvvio(Date dtAvvio) {
		this.dtAvvio = dtAvvio;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DT_DECORR", length = 7)
	public Date getDtDecorr() {
		return this.dtDecorr;
	}

	public void setDtDecorr(Date dtDecorr) {
		this.dtDecorr = dtDecorr;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DT_SOSP", length = 7)
	public Date getDtSosp() {
		return this.dtSosp;
	}

	public void setDtSosp(Date dtSosp) {
		this.dtSosp = dtSosp;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DT_INTERR", length = 7)
	public Date getDtInterr() {
		return this.dtInterr;
	}

	public void setDtInterr(Date dtInterr) {
		this.dtInterr = dtInterr;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DT_RIPRESA", length = 7)
	public Date getDtRipresa() {
		return this.dtRipresa;
	}

	public void setDtRipresa(Date dtRipresa) {
		this.dtRipresa = dtRipresa;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DT_CHIUSURA", length = 7)
	public Date getDtChiusura() {
		return this.dtChiusura;
	}

	public void setDtChiusura(Date dtChiusura) {
		this.dtChiusura = dtChiusura;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DT_RIAPERTURA", length = 7)
	public Date getDtRiapertura() {
		return this.dtRiapertura;
	}

	public void setDtRiapertura(Date dtRiapertura) {
		this.dtRiapertura = dtRiapertura;
	}

	@Column(name = "FLG_STATO", nullable = false, length = 1)
	public String getFlgStato() {
		return this.flgStato;
	}

	public void setFlgStato(String flgStato) {
		this.flgStato = flgStato;
	}

	@Column(name = "FLG_CHIUSURA", length = 1)
	public String getFlgChiusura() {
		return this.flgChiusura;
	}

	public void setFlgChiusura(String flgChiusura) {
		this.flgChiusura = flgChiusura;
	}

	@Column(name = "NRO_SOSP", precision = 2, scale = 0)
	public Byte getNroSosp() {
		return this.nroSosp;
	}

	public void setNroSosp(Byte nroSosp) {
		this.nroSosp = nroSosp;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DT_INS", length = 7)
	public Date getDtIns() {
		return this.dtIns;
	}

	public void setDtIns(Date dtIns) {
		this.dtIns = dtIns;
	}

	@Column(name = "UTE_INS", precision = 6, scale = 0)
	public Integer getUteIns() {
		return this.uteIns;
	}

	public void setUteIns(Integer uteIns) {
		this.uteIns = uteIns;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DT_ULT_MOD", length = 7)
	public Date getDtUltMod() {
		return this.dtUltMod;
	}

	public void setDtUltMod(Date dtUltMod) {
		this.dtUltMod = dtUltMod;
	}

	@Column(name = "UTE_ULT_MOD", precision = 6, scale = 0)
	public Integer getUteUltMod() {
		return this.uteUltMod;
	}

	public void setUteUltMod(Integer uteUltMod) {
		this.uteUltMod = uteUltMod;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cvtProcedimenti")
	public Set<PttSottofasc> getPttSottofascs() {
		return this.pttSottofascs;
	}

	public void setPttSottofascs(Set<PttSottofasc> pttSottofascs) {
		this.pttSottofascs = pttSottofascs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cvtProcedimenti")
	public Set<CvtTempiProc> getCvtTempiProcs() {
		return this.cvtTempiProcs;
	}

	public void setCvtTempiProcs(Set<CvtTempiProc> cvtTempiProcs) {
		this.cvtTempiProcs = cvtTempiProcs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cvtProcedimenti")
	public Set<CvtProcedimenti> getCvtProcedimentis() {
		return this.cvtProcedimentis;
	}

	public void setCvtProcedimentis(Set<CvtProcedimenti> cvtProcedimentis) {
		this.cvtProcedimentis = cvtProcedimentis;
	}

}
