/* * SPDX-License-Identifier: AGPL-3.0-or-later * * C Copyright 2023 Regione Piemonte * */

// Generated 22-set-2016 12.14.09 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CvtProcIndId generated by hbm2java
 */
@Embeddable
public class CvtProcIndId implements java.io.Serializable {

	private int idTpProc;
	private int idIndice;

	public CvtProcIndId() {
	}

	public CvtProcIndId(int idTpProc, int idIndice) {
		this.idTpProc = idTpProc;
		this.idIndice = idIndice;
	}

	@Column(name = "ID_TP_PROC", nullable = false, precision = 8, scale = 0)
	public int getIdTpProc() {
		return this.idTpProc;
	}

	public void setIdTpProc(int idTpProc) {
		this.idTpProc = idTpProc;
	}

	@Column(name = "ID_INDICE", nullable = false, precision = 8, scale = 0)
	public int getIdIndice() {
		return this.idIndice;
	}

	public void setIdIndice(int idIndice) {
		this.idIndice = idIndice;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CvtProcIndId))
			return false;
		CvtProcIndId castOther = (CvtProcIndId) other;

		return (this.getIdTpProc() == castOther.getIdTpProc())
				&& (this.getIdIndice() == castOther.getIdIndice());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdTpProc();
		result = 37 * result + this.getIdIndice();
		return result;
	}

}
