/* * SPDX-License-Identifier: AGPL-3.0-or-later * * C Copyright 2023 Regione Piemonte * */

// Generated 22-set-2016 12.14.09 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CvtProcamm generated by hbm2java
 */
@Entity
@Table(name = "CVT_PROCAMM")
public class CvtProcamm implements java.io.Serializable {

	private CvtProcammId id;
	private CvtUo cvtUo;
	private CvtDecProc cvtDecProc;
	private String flgAbilProt;
	private Date dtIns;
	private Integer uteIns;
	private Date dtUltMod;
	private Integer uteUltMod;

	public CvtProcamm() {
	}

	public CvtProcamm(CvtProcammId id, CvtUo cvtUo, CvtDecProc cvtDecProc) {
		this.id = id;
		this.cvtUo = cvtUo;
		this.cvtDecProc = cvtDecProc;
	}

	public CvtProcamm(CvtProcammId id, CvtUo cvtUo, CvtDecProc cvtDecProc,
			String flgAbilProt, Date dtIns, Integer uteIns, Date dtUltMod,
			Integer uteUltMod) {
		this.id = id;
		this.cvtUo = cvtUo;
		this.cvtDecProc = cvtDecProc;
		this.flgAbilProt = flgAbilProt;
		this.dtIns = dtIns;
		this.uteIns = uteIns;
		this.dtUltMod = dtUltMod;
		this.uteUltMod = uteUltMod;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "idTpProc", column = @Column(name = "ID_TP_PROC", nullable = false, precision = 8, scale = 0)),
			@AttributeOverride(name = "idUo", column = @Column(name = "ID_UO", nullable = false, precision = 8, scale = 0)) })
	public CvtProcammId getId() {
		return this.id;
	}

	public void setId(CvtProcammId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_UO", nullable = false, insertable = false, updatable = false)
	public CvtUo getCvtUo() {
		return this.cvtUo;
	}

	public void setCvtUo(CvtUo cvtUo) {
		this.cvtUo = cvtUo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_TP_PROC", nullable = false, insertable = false, updatable = false)
	public CvtDecProc getCvtDecProc() {
		return this.cvtDecProc;
	}

	public void setCvtDecProc(CvtDecProc cvtDecProc) {
		this.cvtDecProc = cvtDecProc;
	}

	@Column(name = "FLG_ABIL_PROT", length = 1)
	public String getFlgAbilProt() {
		return this.flgAbilProt;
	}

	public void setFlgAbilProt(String flgAbilProt) {
		this.flgAbilProt = flgAbilProt;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DT_INS", length = 7)
	public Date getDtIns() {
		return this.dtIns;
	}

	public void setDtIns(Date dtIns) {
		this.dtIns = dtIns;
	}

	@Column(name = "UTE_INS", precision = 6, scale = 0)
	public Integer getUteIns() {
		return this.uteIns;
	}

	public void setUteIns(Integer uteIns) {
		this.uteIns = uteIns;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DT_ULT_MOD", length = 7)
	public Date getDtUltMod() {
		return this.dtUltMod;
	}

	public void setDtUltMod(Date dtUltMod) {
		this.dtUltMod = dtUltMod;
	}

	@Column(name = "UTE_ULT_MOD", precision = 6, scale = 0)
	public Integer getUteUltMod() {
		return this.uteUltMod;
	}

	public void setUteUltMod(Integer uteUltMod) {
		this.uteUltMod = uteUltMod;
	}

}
