/* * SPDX-License-Identifier: AGPL-3.0-or-later * * C Copyright 2023 Regione Piemonte * */

// Generated 22-set-2016 12.14.09 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CvtRelUo generated by hbm2java
 */
@Entity
@Table(name = "CVT_REL_UO")
public class CvtRelUo implements java.io.Serializable {

	private CvtRelUoId id;
	private Date dtFineVld;
	private String livUo;
	private String livUorel;
	private Date dtIns;
	private Integer uteIns;
	private Date dtUltMod;
	private Integer uteUltMod;
	private Boolean flgInclSottouo;
	private String flgEscludiRiservati;
	private String flgEscludiSensibili;

	public CvtRelUo() {
	}

	public CvtRelUo(CvtRelUoId id) {
		this.id = id;
	}

	public CvtRelUo(CvtRelUoId id, Date dtFineVld, String livUo,
			String livUorel, Date dtIns, Integer uteIns, Date dtUltMod,
			Integer uteUltMod, Boolean flgInclSottouo,
			String flgEscludiRiservati, String flgEscludiSensibili) {
		this.id = id;
		this.dtFineVld = dtFineVld;
		this.livUo = livUo;
		this.livUorel = livUorel;
		this.dtIns = dtIns;
		this.uteIns = uteIns;
		this.dtUltMod = dtUltMod;
		this.uteUltMod = uteUltMod;
		this.flgInclSottouo = flgInclSottouo;
		this.flgEscludiRiservati = flgEscludiRiservati;
		this.flgEscludiSensibili = flgEscludiSensibili;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "idUo", column = @Column(name = "ID_UO", nullable = false, precision = 8, scale = 0)),
			@AttributeOverride(name = "idUorel", column = @Column(name = "ID_UOREL", nullable = false, precision = 8, scale = 0)),
			@AttributeOverride(name = "dtInizioVld", column = @Column(name = "DT_INIZIO_VLD", nullable = false, length = 7)) })
	public CvtRelUoId getId() {
		return this.id;
	}

	public void setId(CvtRelUoId id) {
		this.id = id;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DT_FINE_VLD", length = 7)
	public Date getDtFineVld() {
		return this.dtFineVld;
	}

	public void setDtFineVld(Date dtFineVld) {
		this.dtFineVld = dtFineVld;
	}

	@Column(name = "LIV_UO", length = 25)
	public String getLivUo() {
		return this.livUo;
	}

	public void setLivUo(String livUo) {
		this.livUo = livUo;
	}

	@Column(name = "LIV_UOREL", length = 25)
	public String getLivUorel() {
		return this.livUorel;
	}

	public void setLivUorel(String livUorel) {
		this.livUorel = livUorel;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DT_INS", length = 7)
	public Date getDtIns() {
		return this.dtIns;
	}

	public void setDtIns(Date dtIns) {
		this.dtIns = dtIns;
	}

	@Column(name = "UTE_INS", precision = 6, scale = 0)
	public Integer getUteIns() {
		return this.uteIns;
	}

	public void setUteIns(Integer uteIns) {
		this.uteIns = uteIns;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DT_ULT_MOD", length = 7)
	public Date getDtUltMod() {
		return this.dtUltMod;
	}

	public void setDtUltMod(Date dtUltMod) {
		this.dtUltMod = dtUltMod;
	}

	@Column(name = "UTE_ULT_MOD", precision = 6, scale = 0)
	public Integer getUteUltMod() {
		return this.uteUltMod;
	}

	public void setUteUltMod(Integer uteUltMod) {
		this.uteUltMod = uteUltMod;
	}

	@Column(name = "FLG_INCL_SOTTOUO", precision = 1, scale = 0)
	public Boolean getFlgInclSottouo() {
		return this.flgInclSottouo;
	}

	public void setFlgInclSottouo(Boolean flgInclSottouo) {
		this.flgInclSottouo = flgInclSottouo;
	}

	@Column(name = "FLG_ESCLUDI_RISERVATI", length = 1)
	public String getFlgEscludiRiservati() {
		return this.flgEscludiRiservati;
	}

	public void setFlgEscludiRiservati(String flgEscludiRiservati) {
		this.flgEscludiRiservati = flgEscludiRiservati;
	}

	@Column(name = "FLG_ESCLUDI_SENSIBILI", length = 1)
	public String getFlgEscludiSensibili() {
		return this.flgEscludiSensibili;
	}

	public void setFlgEscludiSensibili(String flgEscludiSensibili) {
		this.flgEscludiSensibili = flgEscludiSensibili;
	}

}
