/* * SPDX-License-Identifier: AGPL-3.0-or-later * * C Copyright 2023 Regione Piemonte * */

// Generated 22-set-2016 12.14.09 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * CvtScadenziario generated by hbm2java
 */
@Entity
@Table(name = "CVT_SCADENZIARIO", uniqueConstraints = @UniqueConstraint(columnNames = {
		"APPLICAZIONE", "ID_OGGETTO_RIF", "COD_TP_SCADENZA", "DT_AVVIO",
		"DT_SCADENZA" }))
public class CvtScadenziario implements java.io.Serializable {

	private int idScadenza;
	private CvtDecScadenze cvtDecScadenze;
	private CvtDecEsitiScad cvtDecEsitiScad;
	private String idTpScadenza;
	private Date dtAvvio;
	private int idOggettoRif;
	private Byte numIter;
	private Byte maxNumIter;
	private String testoRif;
	private String noteEsito;
	private Date dtScadenza;
	private Integer uoAvvio;
	private Date dtIns;
	private Integer uteIns;
	private Date dtUltMod;
	private Integer uteUltMod;
	private BigDecimal flgInvioEmail;
	private String testoEmail;

	public CvtScadenziario() {
	}

	public CvtScadenziario(int idScadenza, int idOggettoRif) {
		this.idScadenza = idScadenza;
		this.idOggettoRif = idOggettoRif;
	}

	public CvtScadenziario(int idScadenza, CvtDecScadenze cvtDecScadenze,
			CvtDecEsitiScad cvtDecEsitiScad, String idTpScadenza, Date dtAvvio,
			int idOggettoRif, Byte numIter, Byte maxNumIter, String testoRif,
			String noteEsito, Date dtScadenza, Integer uoAvvio, Date dtIns,
			Integer uteIns, Date dtUltMod, Integer uteUltMod,
			BigDecimal flgInvioEmail, String testoEmail) {
		this.idScadenza = idScadenza;
		this.cvtDecScadenze = cvtDecScadenze;
		this.cvtDecEsitiScad = cvtDecEsitiScad;
		this.idTpScadenza = idTpScadenza;
		this.dtAvvio = dtAvvio;
		this.idOggettoRif = idOggettoRif;
		this.numIter = numIter;
		this.maxNumIter = maxNumIter;
		this.testoRif = testoRif;
		this.noteEsito = noteEsito;
		this.dtScadenza = dtScadenza;
		this.uoAvvio = uoAvvio;
		this.dtIns = dtIns;
		this.uteIns = uteIns;
		this.dtUltMod = dtUltMod;
		this.uteUltMod = uteUltMod;
		this.flgInvioEmail = flgInvioEmail;
		this.testoEmail = testoEmail;
	}

	@Id
	@Column(name = "ID_SCADENZA", unique = true, nullable = false, precision = 9, scale = 0)
	public int getIdScadenza() {
		return this.idScadenza;
	}

	public void setIdScadenza(int idScadenza) {
		this.idScadenza = idScadenza;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "APPLICAZIONE", referencedColumnName = "COD_TP_APPLIC"),
			@JoinColumn(name = "COD_TP_SCADENZA", referencedColumnName = "COD_TP_SCADENZA") })
	public CvtDecScadenze getCvtDecScadenze() {
		return this.cvtDecScadenze;
	}

	public void setCvtDecScadenze(CvtDecScadenze cvtDecScadenze) {
		this.cvtDecScadenze = cvtDecScadenze;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ESITO")
	public CvtDecEsitiScad getCvtDecEsitiScad() {
		return this.cvtDecEsitiScad;
	}

	public void setCvtDecEsitiScad(CvtDecEsitiScad cvtDecEsitiScad) {
		this.cvtDecEsitiScad = cvtDecEsitiScad;
	}

	@Column(name = "ID_TP_SCADENZA", length = 2)
	public String getIdTpScadenza() {
		return this.idTpScadenza;
	}

	public void setIdTpScadenza(String idTpScadenza) {
		this.idTpScadenza = idTpScadenza;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DT_AVVIO", length = 7)
	public Date getDtAvvio() {
		return this.dtAvvio;
	}

	public void setDtAvvio(Date dtAvvio) {
		this.dtAvvio = dtAvvio;
	}

	@Column(name = "ID_OGGETTO_RIF", nullable = false, precision = 9, scale = 0)
	public int getIdOggettoRif() {
		return this.idOggettoRif;
	}

	public void setIdOggettoRif(int idOggettoRif) {
		this.idOggettoRif = idOggettoRif;
	}

	@Column(name = "NUM_ITER", precision = 2, scale = 0)
	public Byte getNumIter() {
		return this.numIter;
	}

	public void setNumIter(Byte numIter) {
		this.numIter = numIter;
	}

	@Column(name = "MAX_NUM_ITER", precision = 2, scale = 0)
	public Byte getMaxNumIter() {
		return this.maxNumIter;
	}

	public void setMaxNumIter(Byte maxNumIter) {
		this.maxNumIter = maxNumIter;
	}

	@Column(name = "TESTO_RIF", length = 500)
	public String getTestoRif() {
		return this.testoRif;
	}

	public void setTestoRif(String testoRif) {
		this.testoRif = testoRif;
	}

	@Column(name = "NOTE_ESITO", length = 300)
	public String getNoteEsito() {
		return this.noteEsito;
	}

	public void setNoteEsito(String noteEsito) {
		this.noteEsito = noteEsito;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DT_SCADENZA", length = 7)
	public Date getDtScadenza() {
		return this.dtScadenza;
	}

	public void setDtScadenza(Date dtScadenza) {
		this.dtScadenza = dtScadenza;
	}

	@Column(name = "UO_AVVIO", precision = 9, scale = 0)
	public Integer getUoAvvio() {
		return this.uoAvvio;
	}

	public void setUoAvvio(Integer uoAvvio) {
		this.uoAvvio = uoAvvio;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DT_INS", length = 7)
	public Date getDtIns() {
		return this.dtIns;
	}

	public void setDtIns(Date dtIns) {
		this.dtIns = dtIns;
	}

	@Column(name = "UTE_INS", precision = 6, scale = 0)
	public Integer getUteIns() {
		return this.uteIns;
	}

	public void setUteIns(Integer uteIns) {
		this.uteIns = uteIns;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DT_ULT_MOD", length = 7)
	public Date getDtUltMod() {
		return this.dtUltMod;
	}

	public void setDtUltMod(Date dtUltMod) {
		this.dtUltMod = dtUltMod;
	}

	@Column(name = "UTE_ULT_MOD", precision = 6, scale = 0)
	public Integer getUteUltMod() {
		return this.uteUltMod;
	}

	public void setUteUltMod(Integer uteUltMod) {
		this.uteUltMod = uteUltMod;
	}

	@Column(name = "FLG_INVIO_EMAIL", precision = 22, scale = 0)
	public BigDecimal getFlgInvioEmail() {
		return this.flgInvioEmail;
	}

	public void setFlgInvioEmail(BigDecimal flgInvioEmail) {
		this.flgInvioEmail = flgInvioEmail;
	}

	@Column(name = "TESTO_EMAIL", length = 2000)
	public String getTestoEmail() {
		return this.testoEmail;
	}

	public void setTestoEmail(String testoEmail) {
		this.testoEmail = testoEmail;
	}

}
