/* * SPDX-License-Identifier: AGPL-3.0-or-later * * C Copyright 2023 Regione Piemonte * */

// Generated 22-set-2016 12.14.09 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CvtStorUo generated by hbm2java
 */
@Entity
@Table(name = "CVT_STOR_UO")
public class CvtStorUo implements java.io.Serializable {

	private CvtStorUoId id;
	private CvtUtenti cvtUtenti;
	private Date dtFineVld;
	private String desUo;
	private String indirizzo;
	private String tel;
	private String fax;
	private String email;
	private String orarioPubbl;
	private Integer respLeg;
	private Integer respOper;
	private String flgVirtuale;
	private String flgNonMod;
	private String note;
	private Date dtIns;
	private Integer uteIns;
	private int settore;
	private int servizio;
	private int uoc;
	private int uos;
	private int postazione;

	public CvtStorUo() {
	}

	public CvtStorUo(CvtStorUoId id, Date dtFineVld, String desUo, int settore,
			int servizio, int uoc, int uos, int postazione) {
		this.id = id;
		this.dtFineVld = dtFineVld;
		this.desUo = desUo;
		this.settore = settore;
		this.servizio = servizio;
		this.uoc = uoc;
		this.uos = uos;
		this.postazione = postazione;
	}

	public CvtStorUo(CvtStorUoId id, CvtUtenti cvtUtenti, Date dtFineVld,
			String desUo, String indirizzo, String tel, String fax,
			String email, String orarioPubbl, Integer respLeg,
			Integer respOper, String flgVirtuale, String flgNonMod,
			String note, Date dtIns, Integer uteIns, int settore, int servizio,
			int uoc, int uos, int postazione) {
		this.id = id;
		this.cvtUtenti = cvtUtenti;
		this.dtFineVld = dtFineVld;
		this.desUo = desUo;
		this.indirizzo = indirizzo;
		this.tel = tel;
		this.fax = fax;
		this.email = email;
		this.orarioPubbl = orarioPubbl;
		this.respLeg = respLeg;
		this.respOper = respOper;
		this.flgVirtuale = flgVirtuale;
		this.flgNonMod = flgNonMod;
		this.note = note;
		this.dtIns = dtIns;
		this.uteIns = uteIns;
		this.settore = settore;
		this.servizio = servizio;
		this.uoc = uoc;
		this.uos = uos;
		this.postazione = postazione;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "idUo", column = @Column(name = "ID_UO", nullable = false, precision = 8, scale = 0)),
			@AttributeOverride(name = "dtInizioVld", column = @Column(name = "DT_INIZIO_VLD", nullable = false, length = 7)) })
	public CvtStorUoId getId() {
		return this.id;
	}

	public void setId(CvtStorUoId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_UTE")
	public CvtUtenti getCvtUtenti() {
		return this.cvtUtenti;
	}

	public void setCvtUtenti(CvtUtenti cvtUtenti) {
		this.cvtUtenti = cvtUtenti;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DT_FINE_VLD", nullable = false, length = 7)
	public Date getDtFineVld() {
		return this.dtFineVld;
	}

	public void setDtFineVld(Date dtFineVld) {
		this.dtFineVld = dtFineVld;
	}

	@Column(name = "DES_UO", nullable = false, length = 150)
	public String getDesUo() {
		return this.desUo;
	}

	public void setDesUo(String desUo) {
		this.desUo = desUo;
	}

	@Column(name = "INDIRIZZO", length = 75)
	public String getIndirizzo() {
		return this.indirizzo;
	}

	public void setIndirizzo(String indirizzo) {
		this.indirizzo = indirizzo;
	}

	@Column(name = "TEL", length = 20)
	public String getTel() {
		return this.tel;
	}

	public void setTel(String tel) {
		this.tel = tel;
	}

	@Column(name = "FAX", length = 20)
	public String getFax() {
		return this.fax;
	}

	public void setFax(String fax) {
		this.fax = fax;
	}

	@Column(name = "EMAIL", length = 400)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "ORARIO_PUBBL", length = 75)
	public String getOrarioPubbl() {
		return this.orarioPubbl;
	}

	public void setOrarioPubbl(String orarioPubbl) {
		this.orarioPubbl = orarioPubbl;
	}

	@Column(name = "RESP_LEG", precision = 6, scale = 0)
	public Integer getRespLeg() {
		return this.respLeg;
	}

	public void setRespLeg(Integer respLeg) {
		this.respLeg = respLeg;
	}

	@Column(name = "RESP_OPER", precision = 6, scale = 0)
	public Integer getRespOper() {
		return this.respOper;
	}

	public void setRespOper(Integer respOper) {
		this.respOper = respOper;
	}

	@Column(name = "FLG_VIRTUALE", length = 1)
	public String getFlgVirtuale() {
		return this.flgVirtuale;
	}

	public void setFlgVirtuale(String flgVirtuale) {
		this.flgVirtuale = flgVirtuale;
	}

	@Column(name = "FLG_NON_MOD", length = 1)
	public String getFlgNonMod() {
		return this.flgNonMod;
	}

	public void setFlgNonMod(String flgNonMod) {
		this.flgNonMod = flgNonMod;
	}

	@Column(name = "NOTE", length = 250)
	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DT_INS", length = 7)
	public Date getDtIns() {
		return this.dtIns;
	}

	public void setDtIns(Date dtIns) {
		this.dtIns = dtIns;
	}

	@Column(name = "UTE_INS", precision = 6, scale = 0)
	public Integer getUteIns() {
		return this.uteIns;
	}

	public void setUteIns(Integer uteIns) {
		this.uteIns = uteIns;
	}

	@Column(name = "SETTORE", nullable = false, precision = 5, scale = 0)
	public int getSettore() {
		return this.settore;
	}

	public void setSettore(int settore) {
		this.settore = settore;
	}

	@Column(name = "SERVIZIO", nullable = false, precision = 5, scale = 0)
	public int getServizio() {
		return this.servizio;
	}

	public void setServizio(int servizio) {
		this.servizio = servizio;
	}

	@Column(name = "UOC", nullable = false, precision = 5, scale = 0)
	public int getUoc() {
		return this.uoc;
	}

	public void setUoc(int uoc) {
		this.uoc = uoc;
	}

	@Column(name = "UOS", nullable = false, precision = 5, scale = 0)
	public int getUos() {
		return this.uos;
	}

	public void setUos(int uos) {
		this.uos = uos;
	}

	@Column(name = "POSTAZIONE", nullable = false, precision = 5, scale = 0)
	public int getPostazione() {
		return this.postazione;
	}

	public void setPostazione(int postazione) {
		this.postazione = postazione;
	}

}
