/* * SPDX-License-Identifier: AGPL-3.0-or-later * * C Copyright 2023 Regione Piemonte * */

// Generated 22-set-2016 12.14.09 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CvtTempiProcId generated by hbm2java
 */
@Embeddable
public class CvtTempiProcId implements java.io.Serializable {

	private int idProc;
	private String codFase;
	private Date data;
	private String flgTpDt;

	public CvtTempiProcId() {
	}

	public CvtTempiProcId(int idProc, String codFase, Date data, String flgTpDt) {
		this.idProc = idProc;
		this.codFase = codFase;
		this.data = data;
		this.flgTpDt = flgTpDt;
	}

	@Column(name = "ID_PROC", nullable = false, precision = 8, scale = 0)
	public int getIdProc() {
		return this.idProc;
	}

	public void setIdProc(int idProc) {
		this.idProc = idProc;
	}

	@Column(name = "COD_FASE", nullable = false, length = 2)
	public String getCodFase() {
		return this.codFase;
	}

	public void setCodFase(String codFase) {
		this.codFase = codFase;
	}

	@Column(name = "DATA", nullable = false, length = 7)
	public Date getData() {
		return this.data;
	}

	public void setData(Date data) {
		this.data = data;
	}

	@Column(name = "FLG_TP_DT", nullable = false, length = 1)
	public String getFlgTpDt() {
		return this.flgTpDt;
	}

	public void setFlgTpDt(String flgTpDt) {
		this.flgTpDt = flgTpDt;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CvtTempiProcId))
			return false;
		CvtTempiProcId castOther = (CvtTempiProcId) other;

		return (this.getIdProc() == castOther.getIdProc())
				&& ((this.getCodFase() == castOther.getCodFase()) || (this
						.getCodFase() != null && castOther.getCodFase() != null && this
						.getCodFase().equals(castOther.getCodFase())))
				&& ((this.getData() == castOther.getData()) || (this.getData() != null
						&& castOther.getData() != null && this.getData()
						.equals(castOther.getData())))
				&& ((this.getFlgTpDt() == castOther.getFlgTpDt()) || (this
						.getFlgTpDt() != null && castOther.getFlgTpDt() != null && this
						.getFlgTpDt().equals(castOther.getFlgTpDt())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdProc();
		result = 37 * result
				+ (getCodFase() == null ? 0 : this.getCodFase().hashCode());
		result = 37 * result
				+ (getData() == null ? 0 : this.getData().hashCode());
		result = 37 * result
				+ (getFlgTpDt() == null ? 0 : this.getFlgTpDt().hashCode());
		return result;
	}

}
