/* * SPDX-License-Identifier: AGPL-3.0-or-later * * C Copyright 2023 Regione Piemonte * */

// Generated 22-set-2016 12.14.09 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * CvtUoPec generated by hbm2java
 */
@Entity
@Table(name = "CVT_UO_PEC")
public class CvtUoPec implements java.io.Serializable {

	private int idUo;
	private String email;
	private String descrizione;
	private Integer uoAss;
	private String codUo;
	private String pop3Server;
	private String pop3Username;
	private String pop3Password;
	private String pop3Port;
	private String smtpServer;
	private String smtpPort;
	private String smtpUsername;
	private String smtpPassword;
	private String smtpStarttls;
	private String smtpUseAuth;
	private String smtpSsl;
	private String pop3Ssl;
	private String deleteEmail;
	private String pop3Lock;
	private String pop3LockDt;
	private String imapServer;
	private String imapUsername;
	private String imapPassword;
	private String imapPort;
	private String imapSsl;
	private String deleteEmailAdvance;
	private String accInvalidSegnatur;
	private String accettaNonFirmati;
	private String accettaNonVerif;
	private String deleteServerOn;
	private String ggServerBckElab;
	private String deleteEgrOn;
	private String ggEgrBackup;
	private String pecPercQuotaAlert;
	private String backupMailInviate;
	private String ggServerBckScarto;
	private String rifiutaNoPec;
	private String ggServerBackup;
	private Boolean flgDaPubblIpa;

	public CvtUoPec() {
	}

	public CvtUoPec(int idUo) {
		this.idUo = idUo;
	}

	public CvtUoPec(int idUo, String email, String descrizione, Integer uoAss,
			String codUo, String pop3Server, String pop3Username,
			String pop3Password, String pop3Port, String smtpServer,
			String smtpPort, String smtpUsername, String smtpPassword,
			String smtpStarttls, String smtpUseAuth, String smtpSsl,
			String pop3Ssl, String deleteEmail, String pop3Lock,
			String pop3LockDt, String imapServer, String imapUsername,
			String imapPassword, String imapPort, String imapSsl,
			String deleteEmailAdvance, String accInvalidSegnatur,
			String accettaNonFirmati, String accettaNonVerif,
			String deleteServerOn, String ggServerBckElab, String deleteEgrOn,
			String ggEgrBackup, String pecPercQuotaAlert,
			String backupMailInviate, String ggServerBckScarto,
			String rifiutaNoPec, String ggServerBackup, Boolean flgDaPubblIpa) {
		this.idUo = idUo;
		this.email = email;
		this.descrizione = descrizione;
		this.uoAss = uoAss;
		this.codUo = codUo;
		this.pop3Server = pop3Server;
		this.pop3Username = pop3Username;
		this.pop3Password = pop3Password;
		this.pop3Port = pop3Port;
		this.smtpServer = smtpServer;
		this.smtpPort = smtpPort;
		this.smtpUsername = smtpUsername;
		this.smtpPassword = smtpPassword;
		this.smtpStarttls = smtpStarttls;
		this.smtpUseAuth = smtpUseAuth;
		this.smtpSsl = smtpSsl;
		this.pop3Ssl = pop3Ssl;
		this.deleteEmail = deleteEmail;
		this.pop3Lock = pop3Lock;
		this.pop3LockDt = pop3LockDt;
		this.imapServer = imapServer;
		this.imapUsername = imapUsername;
		this.imapPassword = imapPassword;
		this.imapPort = imapPort;
		this.imapSsl = imapSsl;
		this.deleteEmailAdvance = deleteEmailAdvance;
		this.accInvalidSegnatur = accInvalidSegnatur;
		this.accettaNonFirmati = accettaNonFirmati;
		this.accettaNonVerif = accettaNonVerif;
		this.deleteServerOn = deleteServerOn;
		this.ggServerBckElab = ggServerBckElab;
		this.deleteEgrOn = deleteEgrOn;
		this.ggEgrBackup = ggEgrBackup;
		this.pecPercQuotaAlert = pecPercQuotaAlert;
		this.backupMailInviate = backupMailInviate;
		this.ggServerBckScarto = ggServerBckScarto;
		this.rifiutaNoPec = rifiutaNoPec;
		this.ggServerBackup = ggServerBackup;
		this.flgDaPubblIpa = flgDaPubblIpa;
	}

	@Id
	@Column(name = "ID_UO", unique = true, nullable = false, precision = 8, scale = 0)
	public int getIdUo() {
		return this.idUo;
	}

	public void setIdUo(int idUo) {
		this.idUo = idUo;
	}

	@Column(name = "EMAIL", length = 256)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "DESCRIZIONE", length = 256)
	public String getDescrizione() {
		return this.descrizione;
	}

	public void setDescrizione(String descrizione) {
		this.descrizione = descrizione;
	}

	@Column(name = "UO_ASS", precision = 8, scale = 0)
	public Integer getUoAss() {
		return this.uoAss;
	}

	public void setUoAss(Integer uoAss) {
		this.uoAss = uoAss;
	}

	@Column(name = "COD_UO", length = 50)
	public String getCodUo() {
		return this.codUo;
	}

	public void setCodUo(String codUo) {
		this.codUo = codUo;
	}

	@Column(name = "POP3_SERVER", length = 75)
	public String getPop3Server() {
		return this.pop3Server;
	}

	public void setPop3Server(String pop3Server) {
		this.pop3Server = pop3Server;
	}

	@Column(name = "POP3_USERNAME", length = 75)
	public String getPop3Username() {
		return this.pop3Username;
	}

	public void setPop3Username(String pop3Username) {
		this.pop3Username = pop3Username;
	}

	@Column(name = "POP3_PASSWORD", length = 75)
	public String getPop3Password() {
		return this.pop3Password;
	}

	public void setPop3Password(String pop3Password) {
		this.pop3Password = pop3Password;
	}

	@Column(name = "POP3_PORT", length = 75)
	public String getPop3Port() {
		return this.pop3Port;
	}

	public void setPop3Port(String pop3Port) {
		this.pop3Port = pop3Port;
	}

	@Column(name = "SMTP_SERVER", length = 75)
	public String getSmtpServer() {
		return this.smtpServer;
	}

	public void setSmtpServer(String smtpServer) {
		this.smtpServer = smtpServer;
	}

	@Column(name = "SMTP_PORT", length = 75)
	public String getSmtpPort() {
		return this.smtpPort;
	}

	public void setSmtpPort(String smtpPort) {
		this.smtpPort = smtpPort;
	}

	@Column(name = "SMTP_USERNAME", length = 75)
	public String getSmtpUsername() {
		return this.smtpUsername;
	}

	public void setSmtpUsername(String smtpUsername) {
		this.smtpUsername = smtpUsername;
	}

	@Column(name = "SMTP_PASSWORD", length = 75)
	public String getSmtpPassword() {
		return this.smtpPassword;
	}

	public void setSmtpPassword(String smtpPassword) {
		this.smtpPassword = smtpPassword;
	}

	@Column(name = "SMTP_STARTTLS", length = 75)
	public String getSmtpStarttls() {
		return this.smtpStarttls;
	}

	public void setSmtpStarttls(String smtpStarttls) {
		this.smtpStarttls = smtpStarttls;
	}

	@Column(name = "SMTP_USE_AUTH", length = 75)
	public String getSmtpUseAuth() {
		return this.smtpUseAuth;
	}

	public void setSmtpUseAuth(String smtpUseAuth) {
		this.smtpUseAuth = smtpUseAuth;
	}

	@Column(name = "SMTP_SSL", length = 75)
	public String getSmtpSsl() {
		return this.smtpSsl;
	}

	public void setSmtpSsl(String smtpSsl) {
		this.smtpSsl = smtpSsl;
	}

	@Column(name = "POP3_SSL", length = 75)
	public String getPop3Ssl() {
		return this.pop3Ssl;
	}

	public void setPop3Ssl(String pop3Ssl) {
		this.pop3Ssl = pop3Ssl;
	}

	@Column(name = "DELETE_EMAIL", length = 75)
	public String getDeleteEmail() {
		return this.deleteEmail;
	}

	public void setDeleteEmail(String deleteEmail) {
		this.deleteEmail = deleteEmail;
	}

	@Column(name = "POP3_LOCK", length = 1)
	public String getPop3Lock() {
		return this.pop3Lock;
	}

	public void setPop3Lock(String pop3Lock) {
		this.pop3Lock = pop3Lock;
	}

	@Column(name = "POP3_LOCK_DT", length = 20)
	public String getPop3LockDt() {
		return this.pop3LockDt;
	}

	public void setPop3LockDt(String pop3LockDt) {
		this.pop3LockDt = pop3LockDt;
	}

	@Column(name = "IMAP_SERVER", length = 75)
	public String getImapServer() {
		return this.imapServer;
	}

	public void setImapServer(String imapServer) {
		this.imapServer = imapServer;
	}

	@Column(name = "IMAP_USERNAME", length = 75)
	public String getImapUsername() {
		return this.imapUsername;
	}

	public void setImapUsername(String imapUsername) {
		this.imapUsername = imapUsername;
	}

	@Column(name = "IMAP_PASSWORD", length = 75)
	public String getImapPassword() {
		return this.imapPassword;
	}

	public void setImapPassword(String imapPassword) {
		this.imapPassword = imapPassword;
	}

	@Column(name = "IMAP_PORT", length = 75)
	public String getImapPort() {
		return this.imapPort;
	}

	public void setImapPort(String imapPort) {
		this.imapPort = imapPort;
	}

	@Column(name = "IMAP_SSL", length = 75)
	public String getImapSsl() {
		return this.imapSsl;
	}

	public void setImapSsl(String imapSsl) {
		this.imapSsl = imapSsl;
	}

	@Column(name = "DELETE_EMAIL_ADVANCE", length = 5)
	public String getDeleteEmailAdvance() {
		return this.deleteEmailAdvance;
	}

	public void setDeleteEmailAdvance(String deleteEmailAdvance) {
		this.deleteEmailAdvance = deleteEmailAdvance;
	}

	@Column(name = "ACC_INVALID_SEGNATUR", length = 5)
	public String getAccInvalidSegnatur() {
		return this.accInvalidSegnatur;
	}

	public void setAccInvalidSegnatur(String accInvalidSegnatur) {
		this.accInvalidSegnatur = accInvalidSegnatur;
	}

	@Column(name = "ACCETTA_NON_FIRMATI", length = 5)
	public String getAccettaNonFirmati() {
		return this.accettaNonFirmati;
	}

	public void setAccettaNonFirmati(String accettaNonFirmati) {
		this.accettaNonFirmati = accettaNonFirmati;
	}

	@Column(name = "ACCETTA_NON_VERIF", length = 5)
	public String getAccettaNonVerif() {
		return this.accettaNonVerif;
	}

	public void setAccettaNonVerif(String accettaNonVerif) {
		this.accettaNonVerif = accettaNonVerif;
	}

	@Column(name = "DELETE_SERVER_ON", length = 5)
	public String getDeleteServerOn() {
		return this.deleteServerOn;
	}

	public void setDeleteServerOn(String deleteServerOn) {
		this.deleteServerOn = deleteServerOn;
	}

	@Column(name = "GG_SERVER_BCK_ELAB", length = 5)
	public String getGgServerBckElab() {
		return this.ggServerBckElab;
	}

	public void setGgServerBckElab(String ggServerBckElab) {
		this.ggServerBckElab = ggServerBckElab;
	}

	@Column(name = "DELETE_EGR_ON", length = 5)
	public String getDeleteEgrOn() {
		return this.deleteEgrOn;
	}

	public void setDeleteEgrOn(String deleteEgrOn) {
		this.deleteEgrOn = deleteEgrOn;
	}

	@Column(name = "GG_EGR_BACKUP", length = 5)
	public String getGgEgrBackup() {
		return this.ggEgrBackup;
	}

	public void setGgEgrBackup(String ggEgrBackup) {
		this.ggEgrBackup = ggEgrBackup;
	}

	@Column(name = "PEC_PERC_QUOTA_ALERT", length = 2)
	public String getPecPercQuotaAlert() {
		return this.pecPercQuotaAlert;
	}

	public void setPecPercQuotaAlert(String pecPercQuotaAlert) {
		this.pecPercQuotaAlert = pecPercQuotaAlert;
	}

	@Column(name = "BACKUP_MAIL_INVIATE", length = 5)
	public String getBackupMailInviate() {
		return this.backupMailInviate;
	}

	public void setBackupMailInviate(String backupMailInviate) {
		this.backupMailInviate = backupMailInviate;
	}

	@Column(name = "GG_SERVER_BCK_SCARTO", length = 5)
	public String getGgServerBckScarto() {
		return this.ggServerBckScarto;
	}

	public void setGgServerBckScarto(String ggServerBckScarto) {
		this.ggServerBckScarto = ggServerBckScarto;
	}

	@Column(name = "RIFIUTA_NO_PEC", length = 5)
	public String getRifiutaNoPec() {
		return this.rifiutaNoPec;
	}

	public void setRifiutaNoPec(String rifiutaNoPec) {
		this.rifiutaNoPec = rifiutaNoPec;
	}

	@Column(name = "GG_SERVER_BACKUP", length = 5)
	public String getGgServerBackup() {
		return this.ggServerBackup;
	}

	public void setGgServerBackup(String ggServerBackup) {
		this.ggServerBackup = ggServerBackup;
	}

	@Column(name = "FLG_DA_PUBBL_IPA", precision = 1, scale = 0)
	public Boolean getFlgDaPubblIpa() {
		return this.flgDaPubblIpa;
	}

	public void setFlgDaPubblIpa(Boolean flgDaPubblIpa) {
		this.flgDaPubblIpa = flgDaPubblIpa;
	}

}
