/* * SPDX-License-Identifier: AGPL-3.0-or-later * * C Copyright 2023 Regione Piemonte * */

// Generated 22-set-2016 12.14.09 by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PttAllegInf generated by hbm2java
 */
@Entity
@Table(name = "PTT_ALLEG_INF")
public class PttAllegInf implements java.io.Serializable {

	private PttAllegInfId id;
	private PttAllegdoc pttAllegdoc;
	private Serializable filePtr;
	private String flgFirmato;
	private String flgFirmCorr;
	private Date dtIns;
	private Integer uteIns;
	private Date dtUltMod;
	private Integer uteUltMod;
	private String fileName;
	private String impronta;
	private BigDecimal idDocDm;

	public PttAllegInf() {
	}

	public PttAllegInf(PttAllegdoc pttAllegdoc) {
		this.pttAllegdoc = pttAllegdoc;
	}

	public PttAllegInf(PttAllegdoc pttAllegdoc, Serializable filePtr,
			String flgFirmato, String flgFirmCorr, Date dtIns, Integer uteIns,
			Date dtUltMod, Integer uteUltMod, String fileName, String impronta,
			BigDecimal idDocDm) {
		this.pttAllegdoc = pttAllegdoc;
		this.filePtr = filePtr;
		this.flgFirmato = flgFirmato;
		this.flgFirmCorr = flgFirmCorr;
		this.dtIns = dtIns;
		this.uteIns = uteIns;
		this.dtUltMod = dtUltMod;
		this.uteUltMod = uteUltMod;
		this.fileName = fileName;
		this.impronta = impronta;
		this.idDocDm = idDocDm;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "idDoc", column = @Column(name = "ID_DOC", nullable = false, precision = 8, scale = 0)),
			@AttributeOverride(name = "numAlleg", column = @Column(name = "NUM_ALLEG", nullable = false, precision = 4, scale = 0)) })
	public PttAllegInfId getId() {
		return this.id;
	}

	public void setId(PttAllegInfId id) {
		this.id = id;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public PttAllegdoc getPttAllegdoc() {
		return this.pttAllegdoc;
	}

	public void setPttAllegdoc(PttAllegdoc pttAllegdoc) {
		this.pttAllegdoc = pttAllegdoc;
	}

	@Column(name = "FILE_PTR")
	public Serializable getFilePtr() {
		return this.filePtr;
	}

	public void setFilePtr(Serializable filePtr) {
		this.filePtr = filePtr;
	}

	@Column(name = "FLG_FIRMATO", length = 1)
	public String getFlgFirmato() {
		return this.flgFirmato;
	}

	public void setFlgFirmato(String flgFirmato) {
		this.flgFirmato = flgFirmato;
	}

	@Column(name = "FLG_FIRM_CORR", length = 1)
	public String getFlgFirmCorr() {
		return this.flgFirmCorr;
	}

	public void setFlgFirmCorr(String flgFirmCorr) {
		this.flgFirmCorr = flgFirmCorr;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DT_INS", length = 7)
	public Date getDtIns() {
		return this.dtIns;
	}

	public void setDtIns(Date dtIns) {
		this.dtIns = dtIns;
	}

	@Column(name = "UTE_INS", precision = 6, scale = 0)
	public Integer getUteIns() {
		return this.uteIns;
	}

	public void setUteIns(Integer uteIns) {
		this.uteIns = uteIns;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DT_ULT_MOD", length = 7)
	public Date getDtUltMod() {
		return this.dtUltMod;
	}

	public void setDtUltMod(Date dtUltMod) {
		this.dtUltMod = dtUltMod;
	}

	@Column(name = "UTE_ULT_MOD", precision = 6, scale = 0)
	public Integer getUteUltMod() {
		return this.uteUltMod;
	}

	public void setUteUltMod(Integer uteUltMod) {
		this.uteUltMod = uteUltMod;
	}

	@Column(name = "FILE_NAME")
	public String getFileName() {
		return this.fileName;
	}

	public void setFileName(String fileName) {
		this.fileName = fileName;
	}

	@Column(name = "IMPRONTA")
	public String getImpronta() {
		return this.impronta;
	}

	public void setImpronta(String impronta) {
		this.impronta = impronta;
	}

	@Column(name = "ID_DOC_DM", precision = 22, scale = 0)
	public BigDecimal getIdDocDm() {
		return this.idDocDm;
	}

	public void setIdDocDm(BigDecimal idDocDm) {
		this.idDocDm = idDocDm;
	}

}
