/* * SPDX-License-Identifier: AGPL-3.0-or-later * * C Copyright 2023 Regione Piemonte * */

// Generated 22-set-2016 12.14.09 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PttCopieConoscId generated by hbm2java
 */
@Embeddable
public class PttCopieConoscId implements java.io.Serializable {

	private int idUoAss;
	private int idDoc;

	public PttCopieConoscId() {
	}

	public PttCopieConoscId(int idUoAss, int idDoc) {
		this.idUoAss = idUoAss;
		this.idDoc = idDoc;
	}

	@Column(name = "ID_UO_ASS", nullable = false, precision = 8, scale = 0)
	public int getIdUoAss() {
		return this.idUoAss;
	}

	public void setIdUoAss(int idUoAss) {
		this.idUoAss = idUoAss;
	}

	@Column(name = "ID_DOC", nullable = false, precision = 8, scale = 0)
	public int getIdDoc() {
		return this.idDoc;
	}

	public void setIdDoc(int idDoc) {
		this.idDoc = idDoc;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PttCopieConoscId))
			return false;
		PttCopieConoscId castOther = (PttCopieConoscId) other;

		return (this.getIdUoAss() == castOther.getIdUoAss())
				&& (this.getIdDoc() == castOther.getIdDoc());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdUoAss();
		result = 37 * result + this.getIdDoc();
		return result;
	}

}
