/* * SPDX-License-Identifier: AGPL-3.0-or-later * * C Copyright 2023 Regione Piemonte * */

// Generated 22-set-2016 12.14.09 by Hibernate Tools 3.4.0.CR1

import java.sql.Clob;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PttClobCsv generated by hbm2java
 */
@Entity
@Table(name = "PTT_CLOB_CSV")
public class PttClobCsv implements java.io.Serializable {

	private PttClobCsvId id;
	private CvtEnti cvtEnti;
	private Clob foglioDati;
	private String statistiche;

	public PttClobCsv() {
	}

	public PttClobCsv(PttClobCsvId id, CvtEnti cvtEnti) {
		this.id = id;
		this.cvtEnti = cvtEnti;
	}

	public PttClobCsv(PttClobCsvId id, CvtEnti cvtEnti, Clob foglioDati,
			String statistiche) {
		this.id = id;
		this.cvtEnti = cvtEnti;
		this.foglioDati = foglioDati;
		this.statistiche = statistiche;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "codEnte", column = @Column(name = "COD_ENTE", nullable = false, length = 3)),
			@AttributeOverride(name = "idEstrazione", column = @Column(name = "ID_ESTRAZIONE", nullable = false, precision = 22, scale = 0)) })
	public PttClobCsvId getId() {
		return this.id;
	}

	public void setId(PttClobCsvId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "COD_ENTE", nullable = false, insertable = false, updatable = false)
	public CvtEnti getCvtEnti() {
		return this.cvtEnti;
	}

	public void setCvtEnti(CvtEnti cvtEnti) {
		this.cvtEnti = cvtEnti;
	}

	@Column(name = "FOGLIO_DATI")
	public Clob getFoglioDati() {
		return this.foglioDati;
	}

	public void setFoglioDati(Clob foglioDati) {
		this.foglioDati = foglioDati;
	}

	@Column(name = "STATISTICHE", length = 2000)
	public String getStatistiche() {
		return this.statistiche;
	}

	public void setStatistiche(String statistiche) {
		this.statistiche = statistiche;
	}

}
