/* * SPDX-License-Identifier: AGPL-3.0-or-later * * C Copyright 2023 Regione Piemonte * */

// Generated 22-set-2016 12.14.09 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * PttDocumenti generated by hbm2java
 */
@Entity
@Table(name = "PTT_DOCUMENTI", uniqueConstraints = {
		@UniqueConstraint(columnNames = { "TP_PTG", "ANNO_PTG", "NUM_PTG" }),
		@UniqueConstraint(columnNames = { "TP_REG_EMERG", "ANNO_REG_EMERG",
				"NUM_REG_EMERG" }) })
public class PttDocumenti implements java.io.Serializable {

	private int idDoc;
	private PttRepertori pttRepertori;
	private CvtUtenti cvtUtentiByUteRpr;
	private PttDocumenti pttDocumentiByDocAnnPrec;
	private PttProtocolli pttProtocolli;
	private CvtUo cvtUoByUoDest;
	private PttDocumenti pttDocumentiByDocPostAnn;
	private PttSttplog pttSttplog;
	private CvtUo cvtUoByUoAnn;
	private CvtUtenti cvtUtentiByUteAnn;
	private CvtUtenti cvtUtentiByUteProt;
	private PttTpfis pttTpfis;
	private CvtUo cvtUoByUoProt;
	private CvtUo cvtUoByUoRpr;
	private CvtUo cvtUoByUoProv;
	private PttAttiProtDiff pttAttiProtDiff;
	private PttAttiAnn pttAttiAnn;
	private Short annoPtg;
	private Integer numPtg;
	private Short annoRpr;
	private Integer numRpr;
	private String txtOgg;
	private Date dtProt;
	private Date dtRpr;
	private Date dtArrivo;
	private String flgTpProt;
	private String flgCompl;
	private String flgEvd;
	private String flgRsv;
	private String flgNoPubbl;
	private Date dtTermNoPubbl;
	private Date dtTermPp;
	private short nroAlleg;
	private short nroCopie;
	private String rifProv;
	private String protProv;
	private Date dtProv;
	private Integer docRisp;
	private String impronta;
	private String flgMezzo;
	private String noteProtDiff;
	private Date dtTermineReg;
	private String note;
	private String noteAnn;
	private Date dtIns;
	private Integer uteIns;
	private Date dtUltMod;
	private Integer uteUltMod;
	private Date dtDocumento;
	private String tpRegEmerg;
	private Short annoRegEmerg;
	private Integer numRegEmerg;
	private String flgDatiAnn;
	private String flgDetDecr;
	private Date dtRaccomandata;
	private String nroRaccomandata;
	private String repDefinitivo;
	private Integer idDocRepProvv;
	private String flgDatiSensibili;
	private String noteAllegati;
	private String testoOggetto;
	private Set<PttRichInvioPoste> pttRichInvioPostes = new HashSet<PttRichInvioPoste>(
			0);
	private Set<PttEmail> pttEmails = new HashSet<PttEmail>(0);
	private Set<PttDocumenti> pttDocumentisForDocPostAnn = new HashSet<PttDocumenti>(
			0);
	private Set<PttCopie> pttCopies = new HashSet<PttCopie>(0);
	private Set<PttDocInf> pttDocInfs = new HashSet<PttDocInf>(0);
	private PttAclDoc pttAclDoc;
	private Set<PttAttiProtDiff> pttAttiProtDiffs = new HashSet<PttAttiProtDiff>(
			0);
	private Set<PttAttributiOpzDoc> pttAttributiOpzDocs = new HashSet<PttAttributiOpzDoc>(
			0);
	private Set<PttDocAnnullabili> pttDocAnnullabilis = new HashSet<PttDocAnnullabili>(
			0);
	private Set<PttCopieConosc> pttCopieConoscs = new HashSet<PttCopieConosc>(0);
	private Set<PttNomdoc> pttNomdocs = new HashSet<PttNomdoc>(0);
	private Set<PttEmailInvio> pttEmailInvios = new HashSet<PttEmailInvio>(0);
	private Set<PttInformAnn> pttInformAnns = new HashSet<PttInformAnn>(0);
	private Set<PttNomdocAnn> pttNomdocAnns = new HashSet<PttNomdocAnn>(0);
	private Set<PttAllegdoc> pttAllegdocs = new HashSet<PttAllegdoc>(0);
	private Set<PttCopieConoscAnn> pttCopieConoscAnns = new HashSet<PttCopieConoscAnn>(
			0);
	private Set<PttDestIntReg> pttDestIntRegs = new HashSet<PttDestIntReg>(0);
	private Set<PttDocumenti> pttDocumentisForDocAnnPrec = new HashSet<PttDocumenti>(
			0);
	private Set<PttDocInFirma> pttDocInFirmas = new HashSet<PttDocInFirma>(0);
	private Set<PttAssegnIntReg> pttAssegnIntRegs = new HashSet<PttAssegnIntReg>(
			0);
	private Set<PttSyncDocVsAuriga> pttSyncDocVsAurigas = new HashSet<PttSyncDocVsAuriga>(
			0);

	public PttDocumenti() {
	}

	public PttDocumenti(int idDoc, PttRepertori pttRepertori,
			PttProtocolli pttProtocolli, String txtOgg, String flgTpProt,
			short nroAlleg, short nroCopie) {
		this.idDoc = idDoc;
		this.pttRepertori = pttRepertori;
		this.pttProtocolli = pttProtocolli;
		this.txtOgg = txtOgg;
		this.flgTpProt = flgTpProt;
		this.nroAlleg = nroAlleg;
		this.nroCopie = nroCopie;
	}

	public PttDocumenti(int idDoc, PttRepertori pttRepertori,
			CvtUtenti cvtUtentiByUteRpr, PttDocumenti pttDocumentiByDocAnnPrec,
			PttProtocolli pttProtocolli, CvtUo cvtUoByUoDest,
			PttDocumenti pttDocumentiByDocPostAnn, PttSttplog pttSttplog,
			CvtUo cvtUoByUoAnn, CvtUtenti cvtUtentiByUteAnn,
			CvtUtenti cvtUtentiByUteProt, PttTpfis pttTpfis,
			CvtUo cvtUoByUoProt, CvtUo cvtUoByUoRpr, CvtUo cvtUoByUoProv,
			PttAttiProtDiff pttAttiProtDiff, PttAttiAnn pttAttiAnn,
			Short annoPtg, Integer numPtg, Short annoRpr, Integer numRpr,
			String txtOgg, Date dtProt, Date dtRpr, Date dtArrivo,
			String flgTpProt, String flgCompl, String flgEvd, String flgRsv,
			String flgNoPubbl, Date dtTermNoPubbl, Date dtTermPp,
			short nroAlleg, short nroCopie, String rifProv, String protProv,
			Date dtProv, Integer docRisp, String impronta, String flgMezzo,
			String noteProtDiff, Date dtTermineReg, String note,
			String noteAnn, Date dtIns, Integer uteIns, Date dtUltMod,
			Integer uteUltMod, Date dtDocumento, String tpRegEmerg,
			Short annoRegEmerg, Integer numRegEmerg, String flgDatiAnn,
			String flgDetDecr, Date dtRaccomandata, String nroRaccomandata,
			String repDefinitivo, Integer idDocRepProvv,
			String flgDatiSensibili, String noteAllegati, String testoOggetto,
			Set<PttRichInvioPoste> pttRichInvioPostes, Set<PttEmail> pttEmails,
			Set<PttDocumenti> pttDocumentisForDocPostAnn,
			Set<PttCopie> pttCopies, Set<PttDocInf> pttDocInfs,
			PttAclDoc pttAclDoc, Set<PttAttiProtDiff> pttAttiProtDiffs,
			Set<PttAttributiOpzDoc> pttAttributiOpzDocs,
			Set<PttDocAnnullabili> pttDocAnnullabilis,
			Set<PttCopieConosc> pttCopieConoscs, Set<PttNomdoc> pttNomdocs,
			Set<PttEmailInvio> pttEmailInvios, Set<PttInformAnn> pttInformAnns,
			Set<PttNomdocAnn> pttNomdocAnns, Set<PttAllegdoc> pttAllegdocs,
			Set<PttCopieConoscAnn> pttCopieConoscAnns,
			Set<PttDestIntReg> pttDestIntRegs, 
			Set<PttDocumenti> pttDocumentisForDocAnnPrec,
			Set<PttDocInFirma> pttDocInFirmas,
			Set<PttAssegnIntReg> pttAssegnIntRegs,
			Set<PttSyncDocVsAuriga> pttSyncDocVsAurigas) {
		this.idDoc = idDoc;
		this.pttRepertori = pttRepertori;
		this.cvtUtentiByUteRpr = cvtUtentiByUteRpr;
		this.pttDocumentiByDocAnnPrec = pttDocumentiByDocAnnPrec;
		this.pttProtocolli = pttProtocolli;
		this.cvtUoByUoDest = cvtUoByUoDest;
		this.pttDocumentiByDocPostAnn = pttDocumentiByDocPostAnn;
		this.pttSttplog = pttSttplog;
		this.cvtUoByUoAnn = cvtUoByUoAnn;
		this.cvtUtentiByUteAnn = cvtUtentiByUteAnn;
		this.cvtUtentiByUteProt = cvtUtentiByUteProt;
		this.pttTpfis = pttTpfis;
		this.cvtUoByUoProt = cvtUoByUoProt;
		this.cvtUoByUoRpr = cvtUoByUoRpr;
		this.cvtUoByUoProv = cvtUoByUoProv;
		this.pttAttiProtDiff = pttAttiProtDiff;
		this.pttAttiAnn = pttAttiAnn;
		this.annoPtg = annoPtg;
		this.numPtg = numPtg;
		this.annoRpr = annoRpr;
		this.numRpr = numRpr;
		this.txtOgg = txtOgg;
		this.dtProt = dtProt;
		this.dtRpr = dtRpr;
		this.dtArrivo = dtArrivo;
		this.flgTpProt = flgTpProt;
		this.flgCompl = flgCompl;
		this.flgEvd = flgEvd;
		this.flgRsv = flgRsv;
		this.flgNoPubbl = flgNoPubbl;
		this.dtTermNoPubbl = dtTermNoPubbl;
		this.dtTermPp = dtTermPp;
		this.nroAlleg = nroAlleg;
		this.nroCopie = nroCopie;
		this.rifProv = rifProv;
		this.protProv = protProv;
		this.dtProv = dtProv;
		this.docRisp = docRisp;
		this.impronta = impronta;
		this.flgMezzo = flgMezzo;
		this.noteProtDiff = noteProtDiff;
		this.dtTermineReg = dtTermineReg;
		this.note = note;
		this.noteAnn = noteAnn;
		this.dtIns = dtIns;
		this.uteIns = uteIns;
		this.dtUltMod = dtUltMod;
		this.uteUltMod = uteUltMod;
		this.dtDocumento = dtDocumento;
		this.tpRegEmerg = tpRegEmerg;
		this.annoRegEmerg = annoRegEmerg;
		this.numRegEmerg = numRegEmerg;
		this.flgDatiAnn = flgDatiAnn;
		this.flgDetDecr = flgDetDecr;
		this.dtRaccomandata = dtRaccomandata;
		this.nroRaccomandata = nroRaccomandata;
		this.repDefinitivo = repDefinitivo;
		this.idDocRepProvv = idDocRepProvv;
		this.flgDatiSensibili = flgDatiSensibili;
		this.noteAllegati = noteAllegati;
		this.testoOggetto = testoOggetto;
		this.pttRichInvioPostes = pttRichInvioPostes;
		this.pttEmails = pttEmails;
		this.pttDocumentisForDocPostAnn = pttDocumentisForDocPostAnn;
		this.pttCopies = pttCopies;
		this.pttDocInfs = pttDocInfs;
		this.pttAclDoc = pttAclDoc;
		this.pttAttiProtDiffs = pttAttiProtDiffs;
		this.pttAttributiOpzDocs = pttAttributiOpzDocs;
		this.pttDocAnnullabilis = pttDocAnnullabilis;
		this.pttCopieConoscs = pttCopieConoscs;
		this.pttNomdocs = pttNomdocs;
		this.pttEmailInvios = pttEmailInvios;
		this.pttInformAnns = pttInformAnns;
		this.pttNomdocAnns = pttNomdocAnns;
		this.pttAllegdocs = pttAllegdocs;
		this.pttCopieConoscAnns = pttCopieConoscAnns;
		this.pttDestIntRegs = pttDestIntRegs;
		this.pttDocumentisForDocAnnPrec = pttDocumentisForDocAnnPrec;
		this.pttDocInFirmas = pttDocInFirmas;
		this.pttAssegnIntRegs = pttAssegnIntRegs;
		this.pttSyncDocVsAurigas = pttSyncDocVsAurigas;
	}

	@Id
	@Column(name = "ID_DOC", unique = true, nullable = false, precision = 8, scale = 0)
	public int getIdDoc() {
		return this.idDoc;
	}

	public void setIdDoc(int idDoc) {
		this.idDoc = idDoc;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "COD_ENTE", referencedColumnName = "COD_ENTE"),
			@JoinColumn(name = "TP_RPR", referencedColumnName = "TP_REPERTORIO") })
	public PttRepertori getPttRepertori() {
		return this.pttRepertori;
	}

	public void setPttRepertori(PttRepertori pttRepertori) {
		this.pttRepertori = pttRepertori;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "UTE_RPR")
	public CvtUtenti getCvtUtentiByUteRpr() {
		return this.cvtUtentiByUteRpr;
	}

	public void setCvtUtentiByUteRpr(CvtUtenti cvtUtentiByUteRpr) {
		this.cvtUtentiByUteRpr = cvtUtentiByUteRpr;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DOC_ANN_PREC")
	public PttDocumenti getPttDocumentiByDocAnnPrec() {
		return this.pttDocumentiByDocAnnPrec;
	}

	public void setPttDocumentiByDocAnnPrec(
			PttDocumenti pttDocumentiByDocAnnPrec) {
		this.pttDocumentiByDocAnnPrec = pttDocumentiByDocAnnPrec;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "COD_ENTE", referencedColumnName = "COD_ENTE", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "TP_PTG", referencedColumnName = "TP_PROT", nullable = false, insertable = false, updatable = false) })
	public PttProtocolli getPttProtocolli() {
		return this.pttProtocolli;
	}

	public void setPttProtocolli(PttProtocolli pttProtocolli) {
		this.pttProtocolli = pttProtocolli;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "UO_DEST")
	public CvtUo getCvtUoByUoDest() {
		return this.cvtUoByUoDest;
	}

	public void setCvtUoByUoDest(CvtUo cvtUoByUoDest) {
		this.cvtUoByUoDest = cvtUoByUoDest;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DOC_POST_ANN")
	public PttDocumenti getPttDocumentiByDocPostAnn() {
		return this.pttDocumentiByDocPostAnn;
	}

	public void setPttDocumentiByDocPostAnn(
			PttDocumenti pttDocumentiByDocPostAnn) {
		this.pttDocumentiByDocPostAnn = pttDocumentiByDocPostAnn;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "ID_TP_LOG", referencedColumnName = "ID_TP_LOG"),
			@JoinColumn(name = "ID_STTP_LOG", referencedColumnName = "ID_STTP_LOG") })
	public PttSttplog getPttSttplog() {
		return this.pttSttplog;
	}

	public void setPttSttplog(PttSttplog pttSttplog) {
		this.pttSttplog = pttSttplog;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "UO_ANN")
	public CvtUo getCvtUoByUoAnn() {
		return this.cvtUoByUoAnn;
	}

	public void setCvtUoByUoAnn(CvtUo cvtUoByUoAnn) {
		this.cvtUoByUoAnn = cvtUoByUoAnn;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "UTE_ANN")
	public CvtUtenti getCvtUtentiByUteAnn() {
		return this.cvtUtentiByUteAnn;
	}

	public void setCvtUtentiByUteAnn(CvtUtenti cvtUtentiByUteAnn) {
		this.cvtUtentiByUteAnn = cvtUtentiByUteAnn;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "UTE_PROT")
	public CvtUtenti getCvtUtentiByUteProt() {
		return this.cvtUtentiByUteProt;
	}

	public void setCvtUtentiByUteProt(CvtUtenti cvtUtentiByUteProt) {
		this.cvtUtentiByUteProt = cvtUtentiByUteProt;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_TP_FIS")
	public PttTpfis getPttTpfis() {
		return this.pttTpfis;
	}

	public void setPttTpfis(PttTpfis pttTpfis) {
		this.pttTpfis = pttTpfis;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "UO_PROT")
	public CvtUo getCvtUoByUoProt() {
		return this.cvtUoByUoProt;
	}

	public void setCvtUoByUoProt(CvtUo cvtUoByUoProt) {
		this.cvtUoByUoProt = cvtUoByUoProt;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "UO_RPR")
	public CvtUo getCvtUoByUoRpr() {
		return this.cvtUoByUoRpr;
	}

	public void setCvtUoByUoRpr(CvtUo cvtUoByUoRpr) {
		this.cvtUoByUoRpr = cvtUoByUoRpr;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "UO_PROV")
	public CvtUo getCvtUoByUoProv() {
		return this.cvtUoByUoProv;
	}

	public void setCvtUoByUoProv(CvtUo cvtUoByUoProv) {
		this.cvtUoByUoProv = cvtUoByUoProv;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_ATTO")
	public PttAttiProtDiff getPttAttiProtDiff() {
		return this.pttAttiProtDiff;
	}

	public void setPttAttiProtDiff(PttAttiProtDiff pttAttiProtDiff) {
		this.pttAttiProtDiff = pttAttiProtDiff;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_ATTO_ANN")
	public PttAttiAnn getPttAttiAnn() {
		return this.pttAttiAnn;
	}

	public void setPttAttiAnn(PttAttiAnn pttAttiAnn) {
		this.pttAttiAnn = pttAttiAnn;
	}

	@Column(name = "ANNO_PTG", precision = 4, scale = 0)
	public Short getAnnoPtg() {
		return this.annoPtg;
	}

	public void setAnnoPtg(Short annoPtg) {
		this.annoPtg = annoPtg;
	}

	@Column(name = "NUM_PTG", precision = 7, scale = 0)
	public Integer getNumPtg() {
		return this.numPtg;
	}

	public void setNumPtg(Integer numPtg) {
		this.numPtg = numPtg;
	}

	@Column(name = "ANNO_RPR", precision = 4, scale = 0)
	public Short getAnnoRpr() {
		return this.annoRpr;
	}

	public void setAnnoRpr(Short annoRpr) {
		this.annoRpr = annoRpr;
	}

	@Column(name = "NUM_RPR", precision = 7, scale = 0)
	public Integer getNumRpr() {
		return this.numRpr;
	}

	public void setNumRpr(Integer numRpr) {
		this.numRpr = numRpr;
	}

	@Column(name = "TXT_OGG", nullable = false, length = 500)
	public String getTxtOgg() {
		return this.txtOgg;
	}

	public void setTxtOgg(String txtOgg) {
		this.txtOgg = txtOgg;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DT_PROT", length = 7)
	public Date getDtProt() {
		return this.dtProt;
	}

	public void setDtProt(Date dtProt) {
		this.dtProt = dtProt;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DT_RPR", length = 7)
	public Date getDtRpr() {
		return this.dtRpr;
	}

	public void setDtRpr(Date dtRpr) {
		this.dtRpr = dtRpr;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DT_ARRIVO", length = 7)
	public Date getDtArrivo() {
		return this.dtArrivo;
	}

	public void setDtArrivo(Date dtArrivo) {
		this.dtArrivo = dtArrivo;
	}

	@Column(name = "FLG_TP_PROT", nullable = false, length = 2)
	public String getFlgTpProt() {
		return this.flgTpProt;
	}

	public void setFlgTpProt(String flgTpProt) {
		this.flgTpProt = flgTpProt;
	}

	@Column(name = "FLG_COMPL", length = 1)
	public String getFlgCompl() {
		return this.flgCompl;
	}

	public void setFlgCompl(String flgCompl) {
		this.flgCompl = flgCompl;
	}

	@Column(name = "FLG_EVD", length = 1)
	public String getFlgEvd() {
		return this.flgEvd;
	}

	public void setFlgEvd(String flgEvd) {
		this.flgEvd = flgEvd;
	}

	@Column(name = "FLG_RSV", length = 1)
	public String getFlgRsv() {
		return this.flgRsv;
	}

	public void setFlgRsv(String flgRsv) {
		this.flgRsv = flgRsv;
	}

	@Column(name = "FLG_NO_PUBBL", length = 1)
	public String getFlgNoPubbl() {
		return this.flgNoPubbl;
	}

	public void setFlgNoPubbl(String flgNoPubbl) {
		this.flgNoPubbl = flgNoPubbl;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DT_TERM_NO_PUBBL", length = 7)
	public Date getDtTermNoPubbl() {
		return this.dtTermNoPubbl;
	}

	public void setDtTermNoPubbl(Date dtTermNoPubbl) {
		this.dtTermNoPubbl = dtTermNoPubbl;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DT_TERM_PP", length = 7)
	public Date getDtTermPp() {
		return this.dtTermPp;
	}

	public void setDtTermPp(Date dtTermPp) {
		this.dtTermPp = dtTermPp;
	}

	@Column(name = "NRO_ALLEG", nullable = false, precision = 3, scale = 0)
	public short getNroAlleg() {
		return this.nroAlleg;
	}

	public void setNroAlleg(short nroAlleg) {
		this.nroAlleg = nroAlleg;
	}

	@Column(name = "NRO_COPIE", nullable = false, precision = 4, scale = 0)
	public short getNroCopie() {
		return this.nroCopie;
	}

	public void setNroCopie(short nroCopie) {
		this.nroCopie = nroCopie;
	}

	@Column(name = "RIF_PROV", length = 30)
	public String getRifProv() {
		return this.rifProv;
	}

	public void setRifProv(String rifProv) {
		this.rifProv = rifProv;
	}

	@Column(name = "PROT_PROV", length = 20)
	public String getProtProv() {
		return this.protProv;
	}

	public void setProtProv(String protProv) {
		this.protProv = protProv;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DT_PROV", length = 7)
	public Date getDtProv() {
		return this.dtProv;
	}

	public void setDtProv(Date dtProv) {
		this.dtProv = dtProv;
	}

	@Column(name = "DOC_RISP", precision = 8, scale = 0)
	public Integer getDocRisp() {
		return this.docRisp;
	}

	public void setDocRisp(Integer docRisp) {
		this.docRisp = docRisp;
	}

	@Column(name = "IMPRONTA", length = 20)
	public String getImpronta() {
		return this.impronta;
	}

	public void setImpronta(String impronta) {
		this.impronta = impronta;
	}

	@Column(name = "FLG_MEZZO", length = 1)
	public String getFlgMezzo() {
		return this.flgMezzo;
	}

	public void setFlgMezzo(String flgMezzo) {
		this.flgMezzo = flgMezzo;
	}

	@Column(name = "NOTE_PROT_DIFF", length = 250)
	public String getNoteProtDiff() {
		return this.noteProtDiff;
	}

	public void setNoteProtDiff(String noteProtDiff) {
		this.noteProtDiff = noteProtDiff;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DT_TERMINE_REG", length = 7)
	public Date getDtTermineReg() {
		return this.dtTermineReg;
	}

	public void setDtTermineReg(Date dtTermineReg) {
		this.dtTermineReg = dtTermineReg;
	}

	@Column(name = "NOTE", length = 250)
	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	@Column(name = "NOTE_ANN", length = 250)
	public String getNoteAnn() {
		return this.noteAnn;
	}

	public void setNoteAnn(String noteAnn) {
		this.noteAnn = noteAnn;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DT_INS", length = 7)
	public Date getDtIns() {
		return this.dtIns;
	}

	public void setDtIns(Date dtIns) {
		this.dtIns = dtIns;
	}

	@Column(name = "UTE_INS", precision = 6, scale = 0)
	public Integer getUteIns() {
		return this.uteIns;
	}

	public void setUteIns(Integer uteIns) {
		this.uteIns = uteIns;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DT_ULT_MOD", length = 7)
	public Date getDtUltMod() {
		return this.dtUltMod;
	}

	public void setDtUltMod(Date dtUltMod) {
		this.dtUltMod = dtUltMod;
	}

	@Column(name = "UTE_ULT_MOD", precision = 6, scale = 0)
	public Integer getUteUltMod() {
		return this.uteUltMod;
	}

	public void setUteUltMod(Integer uteUltMod) {
		this.uteUltMod = uteUltMod;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DT_DOCUMENTO", length = 7)
	public Date getDtDocumento() {
		return this.dtDocumento;
	}

	public void setDtDocumento(Date dtDocumento) {
		this.dtDocumento = dtDocumento;
	}

	@Column(name = "TP_REG_EMERG", length = 5)
	public String getTpRegEmerg() {
		return this.tpRegEmerg;
	}

	public void setTpRegEmerg(String tpRegEmerg) {
		this.tpRegEmerg = tpRegEmerg;
	}

	@Column(name = "ANNO_REG_EMERG", precision = 4, scale = 0)
	public Short getAnnoRegEmerg() {
		return this.annoRegEmerg;
	}

	public void setAnnoRegEmerg(Short annoRegEmerg) {
		this.annoRegEmerg = annoRegEmerg;
	}

	@Column(name = "NUM_REG_EMERG", precision = 7, scale = 0)
	public Integer getNumRegEmerg() {
		return this.numRegEmerg;
	}

	public void setNumRegEmerg(Integer numRegEmerg) {
		this.numRegEmerg = numRegEmerg;
	}

	@Column(name = "FLG_DATI_ANN", length = 1)
	public String getFlgDatiAnn() {
		return this.flgDatiAnn;
	}

	public void setFlgDatiAnn(String flgDatiAnn) {
		this.flgDatiAnn = flgDatiAnn;
	}

	@Column(name = "FLG_DET_DECR", length = 1)
	public String getFlgDetDecr() {
		return this.flgDetDecr;
	}

	public void setFlgDetDecr(String flgDetDecr) {
		this.flgDetDecr = flgDetDecr;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DT_RACCOMANDATA", length = 7)
	public Date getDtRaccomandata() {
		return this.dtRaccomandata;
	}

	public void setDtRaccomandata(Date dtRaccomandata) {
		this.dtRaccomandata = dtRaccomandata;
	}

	@Column(name = "NRO_RACCOMANDATA", length = 30)
	public String getNroRaccomandata() {
		return this.nroRaccomandata;
	}

	public void setNroRaccomandata(String nroRaccomandata) {
		this.nroRaccomandata = nroRaccomandata;
	}

	@Column(name = "REP_DEFINITIVO", length = 5)
	public String getRepDefinitivo() {
		return this.repDefinitivo;
	}

	public void setRepDefinitivo(String repDefinitivo) {
		this.repDefinitivo = repDefinitivo;
	}

	@Column(name = "ID_DOC_REP_PROVV", precision = 8, scale = 0)
	public Integer getIdDocRepProvv() {
		return this.idDocRepProvv;
	}

	public void setIdDocRepProvv(Integer idDocRepProvv) {
		this.idDocRepProvv = idDocRepProvv;
	}

	@Column(name = "FLG_DATI_SENSIBILI", length = 1)
	public String getFlgDatiSensibili() {
		return this.flgDatiSensibili;
	}

	public void setFlgDatiSensibili(String flgDatiSensibili) {
		this.flgDatiSensibili = flgDatiSensibili;
	}

	@Column(name = "NOTE_ALLEGATI", length = 500)
	public String getNoteAllegati() {
		return this.noteAllegati;
	}

	public void setNoteAllegati(String noteAllegati) {
		this.noteAllegati = noteAllegati;
	}

	@Column(name = "TESTO_OGGETTO", length = 500)
	public String getTestoOggetto() {
		return this.testoOggetto;
	}

	public void setTestoOggetto(String testoOggetto) {
		this.testoOggetto = testoOggetto;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pttDocumenti")
	public Set<PttRichInvioPoste> getPttRichInvioPostes() {
		return this.pttRichInvioPostes;
	}

	public void setPttRichInvioPostes(Set<PttRichInvioPoste> pttRichInvioPostes) {
		this.pttRichInvioPostes = pttRichInvioPostes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pttDocumenti")
	public Set<PttEmail> getPttEmails() {
		return this.pttEmails;
	}

	public void setPttEmails(Set<PttEmail> pttEmails) {
		this.pttEmails = pttEmails;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pttDocumentiByDocPostAnn")
	public Set<PttDocumenti> getPttDocumentisForDocPostAnn() {
		return this.pttDocumentisForDocPostAnn;
	}

	public void setPttDocumentisForDocPostAnn(
			Set<PttDocumenti> pttDocumentisForDocPostAnn) {
		this.pttDocumentisForDocPostAnn = pttDocumentisForDocPostAnn;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pttDocumenti")
	public Set<PttCopie> getPttCopies() {
		return this.pttCopies;
	}

	public void setPttCopies(Set<PttCopie> pttCopies) {
		this.pttCopies = pttCopies;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pttDocumenti")
	public Set<PttDocInf> getPttDocInfs() {
		return this.pttDocInfs;
	}

	public void setPttDocInfs(Set<PttDocInf> pttDocInfs) {
		this.pttDocInfs = pttDocInfs;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "pttDocumenti")
	public PttAclDoc getPttAclDoc() {
		return this.pttAclDoc;
	}

	public void setPttAclDoc(PttAclDoc pttAclDoc) {
		this.pttAclDoc = pttAclDoc;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pttDocumenti")
	public Set<PttAttiProtDiff> getPttAttiProtDiffs() {
		return this.pttAttiProtDiffs;
	}

	public void setPttAttiProtDiffs(Set<PttAttiProtDiff> pttAttiProtDiffs) {
		this.pttAttiProtDiffs = pttAttiProtDiffs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pttDocumenti")
	public Set<PttAttributiOpzDoc> getPttAttributiOpzDocs() {
		return this.pttAttributiOpzDocs;
	}

	public void setPttAttributiOpzDocs(
			Set<PttAttributiOpzDoc> pttAttributiOpzDocs) {
		this.pttAttributiOpzDocs = pttAttributiOpzDocs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pttDocumenti")
	public Set<PttDocAnnullabili> getPttDocAnnullabilis() {
		return this.pttDocAnnullabilis;
	}

	public void setPttDocAnnullabilis(Set<PttDocAnnullabili> pttDocAnnullabilis) {
		this.pttDocAnnullabilis = pttDocAnnullabilis;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pttDocumenti")
	public Set<PttCopieConosc> getPttCopieConoscs() {
		return this.pttCopieConoscs;
	}

	public void setPttCopieConoscs(Set<PttCopieConosc> pttCopieConoscs) {
		this.pttCopieConoscs = pttCopieConoscs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pttDocumenti")
	public Set<PttNomdoc> getPttNomdocs() {
		return this.pttNomdocs;
	}

	public void setPttNomdocs(Set<PttNomdoc> pttNomdocs) {
		this.pttNomdocs = pttNomdocs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pttDocumenti")
	public Set<PttEmailInvio> getPttEmailInvios() {
		return this.pttEmailInvios;
	}

	public void setPttEmailInvios(Set<PttEmailInvio> pttEmailInvios) {
		this.pttEmailInvios = pttEmailInvios;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pttDocumenti")
	public Set<PttInformAnn> getPttInformAnns() {
		return this.pttInformAnns;
	}

	public void setPttInformAnns(Set<PttInformAnn> pttInformAnns) {
		this.pttInformAnns = pttInformAnns;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pttDocumenti")
	public Set<PttNomdocAnn> getPttNomdocAnns() {
		return this.pttNomdocAnns;
	}

	public void setPttNomdocAnns(Set<PttNomdocAnn> pttNomdocAnns) {
		this.pttNomdocAnns = pttNomdocAnns;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pttDocumenti")
	public Set<PttAllegdoc> getPttAllegdocs() {
		return this.pttAllegdocs;
	}

	public void setPttAllegdocs(Set<PttAllegdoc> pttAllegdocs) {
		this.pttAllegdocs = pttAllegdocs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pttDocumenti")
	public Set<PttCopieConoscAnn> getPttCopieConoscAnns() {
		return this.pttCopieConoscAnns;
	}

	public void setPttCopieConoscAnns(Set<PttCopieConoscAnn> pttCopieConoscAnns) {
		this.pttCopieConoscAnns = pttCopieConoscAnns;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pttDocumenti")
	public Set<PttDestIntReg> getPttDestIntRegs() {
		return this.pttDestIntRegs;
	}

	public void setPttDestIntRegs(Set<PttDestIntReg> pttDestIntRegs) {
		this.pttDestIntRegs = pttDestIntRegs;
	}

//	@OneToOne(fetch = FetchType.LAZY, mappedBy = "pttDocumenti")
//	public PttAttiAnn getPttAttiAnn() {
//		return this.pttAttiAnn;
//	}
//
//	public void setPttAttiAnn(PttAttiAnn pttAttiAnn) {
//		this.pttAttiAnn = pttAttiAnn;
//	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pttDocumentiByDocAnnPrec")
	public Set<PttDocumenti> getPttDocumentisForDocAnnPrec() {
		return this.pttDocumentisForDocAnnPrec;
	}

	public void setPttDocumentisForDocAnnPrec(
			Set<PttDocumenti> pttDocumentisForDocAnnPrec) {
		this.pttDocumentisForDocAnnPrec = pttDocumentisForDocAnnPrec;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pttDocumenti")
	public Set<PttDocInFirma> getPttDocInFirmas() {
		return this.pttDocInFirmas;
	}

	public void setPttDocInFirmas(Set<PttDocInFirma> pttDocInFirmas) {
		this.pttDocInFirmas = pttDocInFirmas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pttDocumenti")
	public Set<PttAssegnIntReg> getPttAssegnIntRegs() {
		return this.pttAssegnIntRegs;
	}

	public void setPttAssegnIntRegs(Set<PttAssegnIntReg> pttAssegnIntRegs) {
		this.pttAssegnIntRegs = pttAssegnIntRegs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pttDocumenti")
	public Set<PttSyncDocVsAuriga> getPttSyncDocVsAurigas() {
		return this.pttSyncDocVsAurigas;
	}

	public void setPttSyncDocVsAurigas(
			Set<PttSyncDocVsAuriga> pttSyncDocVsAurigas) {
		this.pttSyncDocVsAurigas = pttSyncDocVsAurigas;
	}

}
