/* * SPDX-License-Identifier: AGPL-3.0-or-later * * C Copyright 2023 Regione Piemonte * */

// Generated 22-set-2016 12.14.09 by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * PttDocInf generated by hbm2java
 */
@Entity
@Table(name = "PTT_DOC_INF", uniqueConstraints = @UniqueConstraint(columnNames = {
		"ID_DOC", "DT_ANN" }))
public class PttDocInf implements java.io.Serializable {

	private PttDocInfId id;
	private PttDocumenti pttDocumenti;
	private Serializable filePtr;
	private Date dtAnn;
	private String flgFirmato;
	private String flgFirmCorr;
	private Date dtIns;
	private Integer uteIns;
	private Date dtUltMod;
	private Integer uteUltMod;
	private String fileName;
	private String impronta;
	private BigDecimal idDocDm;
	private Short nroProgrVerDm;

	public PttDocInf() {
	}

	public PttDocInf(PttDocInfId id, PttDocumenti pttDocumenti) {
		this.id = id;
		this.pttDocumenti = pttDocumenti;
	}

	public PttDocInf(PttDocInfId id, PttDocumenti pttDocumenti,
			Serializable filePtr, Date dtAnn, String flgFirmato,
			String flgFirmCorr, Date dtIns, Integer uteIns, Date dtUltMod,
			Integer uteUltMod, String fileName, String impronta,
			BigDecimal idDocDm, Short nroProgrVerDm) {
		this.id = id;
		this.pttDocumenti = pttDocumenti;
		this.filePtr = filePtr;
		this.dtAnn = dtAnn;
		this.flgFirmato = flgFirmato;
		this.flgFirmCorr = flgFirmCorr;
		this.dtIns = dtIns;
		this.uteIns = uteIns;
		this.dtUltMod = dtUltMod;
		this.uteUltMod = uteUltMod;
		this.fileName = fileName;
		this.impronta = impronta;
		this.idDocDm = idDocDm;
		this.nroProgrVerDm = nroProgrVerDm;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "idDoc", column = @Column(name = "ID_DOC", nullable = false, precision = 8, scale = 0)),
			@AttributeOverride(name = "version", column = @Column(name = "VERSION", nullable = false, precision = 2, scale = 0)) })
	public PttDocInfId getId() {
		return this.id;
	}

	public void setId(PttDocInfId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_DOC", nullable = false, insertable = false, updatable = false)
	public PttDocumenti getPttDocumenti() {
		return this.pttDocumenti;
	}

	public void setPttDocumenti(PttDocumenti pttDocumenti) {
		this.pttDocumenti = pttDocumenti;
	}

	@Column(name = "FILE_PTR")
	public Serializable getFilePtr() {
		return this.filePtr;
	}

	public void setFilePtr(Serializable filePtr) {
		this.filePtr = filePtr;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DT_ANN", length = 7)
	public Date getDtAnn() {
		return this.dtAnn;
	}

	public void setDtAnn(Date dtAnn) {
		this.dtAnn = dtAnn;
	}

	@Column(name = "FLG_FIRMATO", length = 1)
	public String getFlgFirmato() {
		return this.flgFirmato;
	}

	public void setFlgFirmato(String flgFirmato) {
		this.flgFirmato = flgFirmato;
	}

	@Column(name = "FLG_FIRM_CORR", length = 1)
	public String getFlgFirmCorr() {
		return this.flgFirmCorr;
	}

	public void setFlgFirmCorr(String flgFirmCorr) {
		this.flgFirmCorr = flgFirmCorr;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DT_INS", length = 7)
	public Date getDtIns() {
		return this.dtIns;
	}

	public void setDtIns(Date dtIns) {
		this.dtIns = dtIns;
	}

	@Column(name = "UTE_INS", precision = 6, scale = 0)
	public Integer getUteIns() {
		return this.uteIns;
	}

	public void setUteIns(Integer uteIns) {
		this.uteIns = uteIns;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DT_ULT_MOD", length = 7)
	public Date getDtUltMod() {
		return this.dtUltMod;
	}

	public void setDtUltMod(Date dtUltMod) {
		this.dtUltMod = dtUltMod;
	}

	@Column(name = "UTE_ULT_MOD", precision = 6, scale = 0)
	public Integer getUteUltMod() {
		return this.uteUltMod;
	}

	public void setUteUltMod(Integer uteUltMod) {
		this.uteUltMod = uteUltMod;
	}

	@Column(name = "FILE_NAME")
	public String getFileName() {
		return this.fileName;
	}

	public void setFileName(String fileName) {
		this.fileName = fileName;
	}

	@Column(name = "IMPRONTA")
	public String getImpronta() {
		return this.impronta;
	}

	public void setImpronta(String impronta) {
		this.impronta = impronta;
	}

	@Column(name = "ID_DOC_DM", precision = 22, scale = 0)
	public BigDecimal getIdDocDm() {
		return this.idDocDm;
	}

	public void setIdDocDm(BigDecimal idDocDm) {
		this.idDocDm = idDocDm;
	}

	@Column(name = "NRO_PROGR_VER_DM", precision = 4, scale = 0)
	public Short getNroProgrVerDm() {
		return this.nroProgrVerDm;
	}

	public void setNroProgrVerDm(Short nroProgrVerDm) {
		this.nroProgrVerDm = nroProgrVerDm;
	}

}
