/* * SPDX-License-Identifier: AGPL-3.0-or-later * * C Copyright 2023 Regione Piemonte * */

// Generated 22-set-2016 12.14.09 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * PttDefAttributiOpz generated by hbm2java
 */
@Entity
@Table(name = "PTT_DEF_ATTRIBUTI_OPZ", uniqueConstraints = @UniqueConstraint(columnNames = {
		"ID_TITOLAZIONE", "ID_TP_LOG", "ID_STTP_LOG", "ATTR_LABEL" }))
public class PttDefAttributiOpz implements java.io.Serializable {

	private BigDecimal idAttr;
	private PttTitolazioni pttTitolazioni;
	private PttSttplog pttSttplog;
	private String attrLabel;
	private Short attrNumOrder;
	private boolean flgEnabled;
	private String attrType;
	private Boolean flgNullable;
	private Short attrSize;
	private Boolean attrScale;
	private Date dtIns;
	private Integer uteIns;
	private Date dtUltMod;
	private Integer uteUltMod;
	private Set<PttAttributiOpzSf> pttAttributiOpzSfs = new HashSet<PttAttributiOpzSf>(
			0);
	private Set<PttAttributiOpzDoc> pttAttributiOpzDocs = new HashSet<PttAttributiOpzDoc>(
			0);

	public PttDefAttributiOpz() {
	}

	public PttDefAttributiOpz(BigDecimal idAttr, String attrLabel,
			boolean flgEnabled, String attrType) {
		this.idAttr = idAttr;
		this.attrLabel = attrLabel;
		this.flgEnabled = flgEnabled;
		this.attrType = attrType;
	}

	public PttDefAttributiOpz(BigDecimal idAttr, PttTitolazioni pttTitolazioni,
			PttSttplog pttSttplog, String attrLabel, Short attrNumOrder,
			boolean flgEnabled, String attrType, Boolean flgNullable,
			Short attrSize, Boolean attrScale, Date dtIns, Integer uteIns,
			Date dtUltMod, Integer uteUltMod,
			Set<PttAttributiOpzSf> pttAttributiOpzSfs,
			Set<PttAttributiOpzDoc> pttAttributiOpzDocs) {
		this.idAttr = idAttr;
		this.pttTitolazioni = pttTitolazioni;
		this.pttSttplog = pttSttplog;
		this.attrLabel = attrLabel;
		this.attrNumOrder = attrNumOrder;
		this.flgEnabled = flgEnabled;
		this.attrType = attrType;
		this.flgNullable = flgNullable;
		this.attrSize = attrSize;
		this.attrScale = attrScale;
		this.dtIns = dtIns;
		this.uteIns = uteIns;
		this.dtUltMod = dtUltMod;
		this.uteUltMod = uteUltMod;
		this.pttAttributiOpzSfs = pttAttributiOpzSfs;
		this.pttAttributiOpzDocs = pttAttributiOpzDocs;
	}

	@Id
	@Column(name = "ID_ATTR", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdAttr() {
		return this.idAttr;
	}

	public void setIdAttr(BigDecimal idAttr) {
		this.idAttr = idAttr;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_TITOLAZIONE")
	public PttTitolazioni getPttTitolazioni() {
		return this.pttTitolazioni;
	}

	public void setPttTitolazioni(PttTitolazioni pttTitolazioni) {
		this.pttTitolazioni = pttTitolazioni;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "ID_TP_LOG", referencedColumnName = "ID_TP_LOG"),
			@JoinColumn(name = "ID_STTP_LOG", referencedColumnName = "ID_STTP_LOG") })
	public PttSttplog getPttSttplog() {
		return this.pttSttplog;
	}

	public void setPttSttplog(PttSttplog pttSttplog) {
		this.pttSttplog = pttSttplog;
	}

	@Column(name = "ATTR_LABEL", nullable = false, length = 100)
	public String getAttrLabel() {
		return this.attrLabel;
	}

	public void setAttrLabel(String attrLabel) {
		this.attrLabel = attrLabel;
	}

	@Column(name = "ATTR_NUM_ORDER", precision = 3, scale = 0)
	public Short getAttrNumOrder() {
		return this.attrNumOrder;
	}

	public void setAttrNumOrder(Short attrNumOrder) {
		this.attrNumOrder = attrNumOrder;
	}

	@Column(name = "FLG_ENABLED", nullable = false, precision = 1, scale = 0)
	public boolean isFlgEnabled() {
		return this.flgEnabled;
	}

	public void setFlgEnabled(boolean flgEnabled) {
		this.flgEnabled = flgEnabled;
	}

	@Column(name = "ATTR_TYPE", nullable = false, length = 30)
	public String getAttrType() {
		return this.attrType;
	}

	public void setAttrType(String attrType) {
		this.attrType = attrType;
	}

	@Column(name = "FLG_NULLABLE", precision = 1, scale = 0)
	public Boolean getFlgNullable() {
		return this.flgNullable;
	}

	public void setFlgNullable(Boolean flgNullable) {
		this.flgNullable = flgNullable;
	}

	@Column(name = "ATTR_SIZE", precision = 4, scale = 0)
	public Short getAttrSize() {
		return this.attrSize;
	}

	public void setAttrSize(Short attrSize) {
		this.attrSize = attrSize;
	}

	@Column(name = "ATTR_SCALE", precision = 1, scale = 0)
	public Boolean getAttrScale() {
		return this.attrScale;
	}

	public void setAttrScale(Boolean attrScale) {
		this.attrScale = attrScale;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DT_INS", length = 7)
	public Date getDtIns() {
		return this.dtIns;
	}

	public void setDtIns(Date dtIns) {
		this.dtIns = dtIns;
	}

	@Column(name = "UTE_INS", precision = 6, scale = 0)
	public Integer getUteIns() {
		return this.uteIns;
	}

	public void setUteIns(Integer uteIns) {
		this.uteIns = uteIns;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DT_ULT_MOD", length = 7)
	public Date getDtUltMod() {
		return this.dtUltMod;
	}

	public void setDtUltMod(Date dtUltMod) {
		this.dtUltMod = dtUltMod;
	}

	@Column(name = "UTE_ULT_MOD", precision = 6, scale = 0)
	public Integer getUteUltMod() {
		return this.uteUltMod;
	}

	public void setUteUltMod(Integer uteUltMod) {
		this.uteUltMod = uteUltMod;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pttDefAttributiOpz")
	public Set<PttAttributiOpzSf> getPttAttributiOpzSfs() {
		return this.pttAttributiOpzSfs;
	}

	public void setPttAttributiOpzSfs(Set<PttAttributiOpzSf> pttAttributiOpzSfs) {
		this.pttAttributiOpzSfs = pttAttributiOpzSfs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pttDefAttributiOpz")
	public Set<PttAttributiOpzDoc> getPttAttributiOpzDocs() {
		return this.pttAttributiOpzDocs;
	}

	public void setPttAttributiOpzDocs(
			Set<PttAttributiOpzDoc> pttAttributiOpzDocs) {
		this.pttAttributiOpzDocs = pttAttributiOpzDocs;
	}

}
