/* * SPDX-License-Identifier: AGPL-3.0-or-later * * C Copyright 2023 Regione Piemonte * */

// Generated 22-set-2016 12.14.09 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * PttEmailAttach generated by hbm2java
 */
@Entity
@Table(name = "PTT_EMAIL_ATTACH", uniqueConstraints = @UniqueConstraint(columnNames = {
		"ID_EMAIL", "ID" }))
public class PttEmailAttach implements java.io.Serializable {

	private PttEmailAttachId id;
	private PttEmail pttEmail;

	public PttEmailAttach() {
	}

	public PttEmailAttach(PttEmailAttachId id, PttEmail pttEmail) {
		this.id = id;
		this.pttEmail = pttEmail;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "id", column = @Column(name = "ID", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "idEmail", column = @Column(name = "ID_EMAIL", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "nomeAttach", column = @Column(name = "NOME_ATTACH", length = 4000)),
			@AttributeOverride(name = "attach", column = @Column(name = "ATTACH")),
			@AttributeOverride(name = "dtIns", column = @Column(name = "DT_INS", length = 7)),
			@AttributeOverride(name = "idDoc", column = @Column(name = "ID_DOC", precision = 22, scale = 0)) })
	public PttEmailAttachId getId() {
		return this.id;
	}

	public void setId(PttEmailAttachId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_EMAIL", nullable = false, insertable = false, updatable = false)
	public PttEmail getPttEmail() {
		return this.pttEmail;
	}

	public void setPttEmail(PttEmail pttEmail) {
		this.pttEmail = pttEmail;
	}

}
