/* * SPDX-License-Identifier: AGPL-3.0-or-later * * C Copyright 2023 Regione Piemonte * */

// Generated 22-set-2016 12.14.09 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.sql.Blob;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PttEmailAttachId generated by hbm2java
 */
@Embeddable
public class PttEmailAttachId implements java.io.Serializable {

	private BigDecimal id;
	private BigDecimal idEmail;
	private String nomeAttach;
	private Blob attach;
	private Date dtIns;
	private BigDecimal idDoc;

	public PttEmailAttachId() {
	}

	public PttEmailAttachId(BigDecimal id, BigDecimal idEmail) {
		this.id = id;
		this.idEmail = idEmail;
	}

	public PttEmailAttachId(BigDecimal id, BigDecimal idEmail,
			String nomeAttach, Blob attach, Date dtIns, BigDecimal idDoc) {
		this.id = id;
		this.idEmail = idEmail;
		this.nomeAttach = nomeAttach;
		this.attach = attach;
		this.dtIns = dtIns;
		this.idDoc = idDoc;
	}

	@Column(name = "ID", nullable = false, precision = 22, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@Column(name = "ID_EMAIL", nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdEmail() {
		return this.idEmail;
	}

	public void setIdEmail(BigDecimal idEmail) {
		this.idEmail = idEmail;
	}

	@Column(name = "NOME_ATTACH", length = 4000)
	public String getNomeAttach() {
		return this.nomeAttach;
	}

	public void setNomeAttach(String nomeAttach) {
		this.nomeAttach = nomeAttach;
	}

	@Column(name = "ATTACH")
	public Blob getAttach() {
		return this.attach;
	}

	public void setAttach(Blob attach) {
		this.attach = attach;
	}

	@Column(name = "DT_INS", length = 7)
	public Date getDtIns() {
		return this.dtIns;
	}

	public void setDtIns(Date dtIns) {
		this.dtIns = dtIns;
	}

	@Column(name = "ID_DOC", precision = 22, scale = 0)
	public BigDecimal getIdDoc() {
		return this.idDoc;
	}

	public void setIdDoc(BigDecimal idDoc) {
		this.idDoc = idDoc;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PttEmailAttachId))
			return false;
		PttEmailAttachId castOther = (PttEmailAttachId) other;

		return ((this.getId() == castOther.getId()) || (this.getId() != null
				&& castOther.getId() != null && this.getId().equals(
				castOther.getId())))
				&& ((this.getIdEmail() == castOther.getIdEmail()) || (this
						.getIdEmail() != null && castOther.getIdEmail() != null && this
						.getIdEmail().equals(castOther.getIdEmail())))
				&& ((this.getNomeAttach() == castOther.getNomeAttach()) || (this
						.getNomeAttach() != null
						&& castOther.getNomeAttach() != null && this
						.getNomeAttach().equals(castOther.getNomeAttach())))
				&& ((this.getAttach() == castOther.getAttach()) || (this
						.getAttach() != null && castOther.getAttach() != null && this
						.getAttach().equals(castOther.getAttach())))
				&& ((this.getDtIns() == castOther.getDtIns()) || (this
						.getDtIns() != null && castOther.getDtIns() != null && this
						.getDtIns().equals(castOther.getDtIns())))
				&& ((this.getIdDoc() == castOther.getIdDoc()) || (this
						.getIdDoc() != null && castOther.getIdDoc() != null && this
						.getIdDoc().equals(castOther.getIdDoc())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getId() == null ? 0 : this.getId().hashCode());
		result = 37 * result
				+ (getIdEmail() == null ? 0 : this.getIdEmail().hashCode());
		result = 37
				* result
				+ (getNomeAttach() == null ? 0 : this.getNomeAttach()
						.hashCode());
		result = 37 * result
				+ (getAttach() == null ? 0 : this.getAttach().hashCode());
		result = 37 * result
				+ (getDtIns() == null ? 0 : this.getDtIns().hashCode());
		result = 37 * result
				+ (getIdDoc() == null ? 0 : this.getIdDoc().hashCode());
		return result;
	}

}
