/* * SPDX-License-Identifier: AGPL-3.0-or-later * * C Copyright 2023 Regione Piemonte * */

// Generated 22-set-2016 12.14.09 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * PttEmailConferme generated by hbm2java
 */
@Entity
@Table(name = "PTT_EMAIL_CONFERME")
public class PttEmailConferme implements java.io.Serializable {

	private BigDecimal idEmail;
	private PttEmail pttEmail;
	private String codAmm;
	private String codAoo;
	private BigDecimal numReg;
	private Date dtReg;

	public PttEmailConferme() {
	}

	public PttEmailConferme(PttEmail pttEmail) {
		this.pttEmail = pttEmail;
	}

	public PttEmailConferme(PttEmail pttEmail, String codAmm, String codAoo,
			BigDecimal numReg, Date dtReg) {
		this.pttEmail = pttEmail;
		this.codAmm = codAmm;
		this.codAoo = codAoo;
		this.numReg = numReg;
		this.dtReg = dtReg;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "pttEmail"))
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "ID_EMAIL", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdEmail() {
		return this.idEmail;
	}

	public void setIdEmail(BigDecimal idEmail) {
		this.idEmail = idEmail;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public PttEmail getPttEmail() {
		return this.pttEmail;
	}

	public void setPttEmail(PttEmail pttEmail) {
		this.pttEmail = pttEmail;
	}

	@Column(name = "COD_AMM", length = 100)
	public String getCodAmm() {
		return this.codAmm;
	}

	public void setCodAmm(String codAmm) {
		this.codAmm = codAmm;
	}

	@Column(name = "COD_AOO", length = 100)
	public String getCodAoo() {
		return this.codAoo;
	}

	public void setCodAoo(String codAoo) {
		this.codAoo = codAoo;
	}

	@Column(name = "NUM_REG", precision = 22, scale = 0)
	public BigDecimal getNumReg() {
		return this.numReg;
	}

	public void setNumReg(BigDecimal numReg) {
		this.numReg = numReg;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DT_REG", length = 7)
	public Date getDtReg() {
		return this.dtReg;
	}

	public void setDtReg(Date dtReg) {
		this.dtReg = dtReg;
	}

}
