/* * SPDX-License-Identifier: AGPL-3.0-or-later * * C Copyright 2023 Regione Piemonte * */

// Generated 22-set-2016 12.14.09 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PttEmailInvio generated by hbm2java
 */
@Entity
@Table(name = "PTT_EMAIL_INVIO")
public class PttEmailInvio implements java.io.Serializable {

	private PttEmailInvioId id;
	private PttDocumenti pttDocumenti;
	private CvtAnagPd cvtAnagPd;
	private PttEmail pttEmail;
	private String flgCc;
	private String email;

	public PttEmailInvio() {
	}

	public PttEmailInvio(PttEmailInvioId id, PttDocumenti pttDocumenti,
			CvtAnagPd cvtAnagPd, PttEmail pttEmail) {
		this.id = id;
		this.pttDocumenti = pttDocumenti;
		this.cvtAnagPd = cvtAnagPd;
		this.pttEmail = pttEmail;
	}

	public PttEmailInvio(PttEmailInvioId id, PttDocumenti pttDocumenti,
			CvtAnagPd cvtAnagPd, PttEmail pttEmail, String flgCc, String email) {
		this.id = id;
		this.pttDocumenti = pttDocumenti;
		this.cvtAnagPd = cvtAnagPd;
		this.pttEmail = pttEmail;
		this.flgCc = flgCc;
		this.email = email;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "idDoc", column = @Column(name = "ID_DOC", nullable = false, precision = 8, scale = 0)),
			@AttributeOverride(name = "idAnag", column = @Column(name = "ID_ANAG", nullable = false, precision = 9, scale = 0)),
			@AttributeOverride(name = "idEmail", column = @Column(name = "ID_EMAIL", nullable = false, precision = 22, scale = 0)) })
	public PttEmailInvioId getId() {
		return this.id;
	}

	public void setId(PttEmailInvioId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_DOC", nullable = false, insertable = false, updatable = false)
	public PttDocumenti getPttDocumenti() {
		return this.pttDocumenti;
	}

	public void setPttDocumenti(PttDocumenti pttDocumenti) {
		this.pttDocumenti = pttDocumenti;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_ANAG", nullable = false, insertable = false, updatable = false)
	public CvtAnagPd getCvtAnagPd() {
		return this.cvtAnagPd;
	}

	public void setCvtAnagPd(CvtAnagPd cvtAnagPd) {
		this.cvtAnagPd = cvtAnagPd;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_EMAIL", nullable = false, insertable = false, updatable = false)
	public PttEmail getPttEmail() {
		return this.pttEmail;
	}

	public void setPttEmail(PttEmail pttEmail) {
		this.pttEmail = pttEmail;
	}

	@Column(name = "FLG_CC", length = 1)
	public String getFlgCc() {
		return this.flgCc;
	}

	public void setFlgCc(String flgCc) {
		this.flgCc = flgCc;
	}

	@Column(name = "EMAIL", length = 70)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

}
