/* * SPDX-License-Identifier: AGPL-3.0-or-later * * C Copyright 2023 Regione Piemonte * */

// Generated 22-set-2016 12.14.09 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * PttFascicoli generated by hbm2java
 */
@Entity
@Table(name = "PTT_FASCICOLI", uniqueConstraints = @UniqueConstraint(columnNames = {
		"ANNO", "ID_TITOLAZIONE", "PROGR_FASC" }))
public class PttFascicoli implements java.io.Serializable {

	private int idFascicolo;
	private PttTitolazioni pttTitolazioni;
	private CvtUo cvtUo;
	private PttFascicoli pttFascicoli;
	private String codEnte;
	private short anno;
	private int progrFasc;
	private String noteIperfasc;
	private Date dtArch;
	private Date dtPrearch;
	private Date dtVersamento;
	private Date dtPrelievo;
	private Date dtRestituzione;
	private Date dtIns;
	private Integer uteIns;
	private Date dtUltMod;
	private Integer uteUltMod;
	private Set<PttConsultazioni> pttConsultazionis = new HashSet<PttConsultazioni>(
			0);
	private Set<PttSottofasc> pttSottofascs = new HashSet<PttSottofasc>(0);
	private Set<PttFascicoli> pttFascicolis = new HashSet<PttFascicoli>(0);

	public PttFascicoli() {
	}

	public PttFascicoli(int idFascicolo, PttTitolazioni pttTitolazioni,
			String codEnte, short anno, int progrFasc) {
		this.idFascicolo = idFascicolo;
		this.pttTitolazioni = pttTitolazioni;
		this.codEnte = codEnte;
		this.anno = anno;
		this.progrFasc = progrFasc;
	}

	public PttFascicoli(int idFascicolo, PttTitolazioni pttTitolazioni,
			CvtUo cvtUo, PttFascicoli pttFascicoli, String codEnte, short anno,
			int progrFasc, String noteIperfasc, Date dtArch, Date dtPrearch,
			Date dtVersamento, Date dtPrelievo, Date dtRestituzione,
			Date dtIns, Integer uteIns, Date dtUltMod, Integer uteUltMod,
			Set<PttConsultazioni> pttConsultazionis,
			Set<PttSottofasc> pttSottofascs, Set<PttFascicoli> pttFascicolis) {
		this.idFascicolo = idFascicolo;
		this.pttTitolazioni = pttTitolazioni;
		this.cvtUo = cvtUo;
		this.pttFascicoli = pttFascicoli;
		this.codEnte = codEnte;
		this.anno = anno;
		this.progrFasc = progrFasc;
		this.noteIperfasc = noteIperfasc;
		this.dtArch = dtArch;
		this.dtPrearch = dtPrearch;
		this.dtVersamento = dtVersamento;
		this.dtPrelievo = dtPrelievo;
		this.dtRestituzione = dtRestituzione;
		this.dtIns = dtIns;
		this.uteIns = uteIns;
		this.dtUltMod = dtUltMod;
		this.uteUltMod = uteUltMod;
		this.pttConsultazionis = pttConsultazionis;
		this.pttSottofascs = pttSottofascs;
		this.pttFascicolis = pttFascicolis;
	}

	@Id
	@Column(name = "ID_FASCICOLO", unique = true, nullable = false, precision = 8, scale = 0)
	public int getIdFascicolo() {
		return this.idFascicolo;
	}

	public void setIdFascicolo(int idFascicolo) {
		this.idFascicolo = idFascicolo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_TITOLAZIONE", nullable = false)
	public PttTitolazioni getPttTitolazioni() {
		return this.pttTitolazioni;
	}

	public void setPttTitolazioni(PttTitolazioni pttTitolazioni) {
		this.pttTitolazioni = pttTitolazioni;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "UO_CONSULT")
	public CvtUo getCvtUo() {
		return this.cvtUo;
	}

	public void setCvtUo(CvtUo cvtUo) {
		this.cvtUo = cvtUo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_IPERFASC")
	public PttFascicoli getPttFascicoli() {
		return this.pttFascicoli;
	}

	public void setPttFascicoli(PttFascicoli pttFascicoli) {
		this.pttFascicoli = pttFascicoli;
	}

	@Column(name = "COD_ENTE", nullable = false, length = 3)
	public String getCodEnte() {
		return this.codEnte;
	}

	public void setCodEnte(String codEnte) {
		this.codEnte = codEnte;
	}

	@Column(name = "ANNO", nullable = false, precision = 4, scale = 0)
	public short getAnno() {
		return this.anno;
	}

	public void setAnno(short anno) {
		this.anno = anno;
	}

	@Column(name = "PROGR_FASC", nullable = false, precision = 8, scale = 0)
	public int getProgrFasc() {
		return this.progrFasc;
	}

	public void setProgrFasc(int progrFasc) {
		this.progrFasc = progrFasc;
	}

	@Column(name = "NOTE_IPERFASC", length = 250)
	public String getNoteIperfasc() {
		return this.noteIperfasc;
	}

	public void setNoteIperfasc(String noteIperfasc) {
		this.noteIperfasc = noteIperfasc;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DT_ARCH", length = 7)
	public Date getDtArch() {
		return this.dtArch;
	}

	public void setDtArch(Date dtArch) {
		this.dtArch = dtArch;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DT_PREARCH", length = 7)
	public Date getDtPrearch() {
		return this.dtPrearch;
	}

	public void setDtPrearch(Date dtPrearch) {
		this.dtPrearch = dtPrearch;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DT_VERSAMENTO", length = 7)
	public Date getDtVersamento() {
		return this.dtVersamento;
	}

	public void setDtVersamento(Date dtVersamento) {
		this.dtVersamento = dtVersamento;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DT_PRELIEVO", length = 7)
	public Date getDtPrelievo() {
		return this.dtPrelievo;
	}

	public void setDtPrelievo(Date dtPrelievo) {
		this.dtPrelievo = dtPrelievo;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DT_RESTITUZIONE", length = 7)
	public Date getDtRestituzione() {
		return this.dtRestituzione;
	}

	public void setDtRestituzione(Date dtRestituzione) {
		this.dtRestituzione = dtRestituzione;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DT_INS", length = 7)
	public Date getDtIns() {
		return this.dtIns;
	}

	public void setDtIns(Date dtIns) {
		this.dtIns = dtIns;
	}

	@Column(name = "UTE_INS", precision = 6, scale = 0)
	public Integer getUteIns() {
		return this.uteIns;
	}

	public void setUteIns(Integer uteIns) {
		this.uteIns = uteIns;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DT_ULT_MOD", length = 7)
	public Date getDtUltMod() {
		return this.dtUltMod;
	}

	public void setDtUltMod(Date dtUltMod) {
		this.dtUltMod = dtUltMod;
	}

	@Column(name = "UTE_ULT_MOD", precision = 6, scale = 0)
	public Integer getUteUltMod() {
		return this.uteUltMod;
	}

	public void setUteUltMod(Integer uteUltMod) {
		this.uteUltMod = uteUltMod;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pttFascicoli")
	public Set<PttConsultazioni> getPttConsultazionis() {
		return this.pttConsultazionis;
	}

	public void setPttConsultazionis(Set<PttConsultazioni> pttConsultazionis) {
		this.pttConsultazionis = pttConsultazionis;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pttFascicoli")
	public Set<PttSottofasc> getPttSottofascs() {
		return this.pttSottofascs;
	}

	public void setPttSottofascs(Set<PttSottofasc> pttSottofascs) {
		this.pttSottofascs = pttSottofascs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pttFascicoli")
	public Set<PttFascicoli> getPttFascicolis() {
		return this.pttFascicolis;
	}

	public void setPttFascicolis(Set<PttFascicoli> pttFascicolis) {
		this.pttFascicolis = pttFascicolis;
	}

}
