/* * SPDX-License-Identifier: AGPL-3.0-or-later * * C Copyright 2023 Regione Piemonte * */

// Generated 22-set-2016 12.14.09 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PttFlguo generated by hbm2java
 */
@Entity
@Table(name = "PTT_FLGUO")
public class PttFlguo implements java.io.Serializable {

	private int idUo;
	private String flgGestSis;
	private String flgLimiteGest;
	private String flgRsv;
	private String flgInterna;
	private String flgArch;
	private String flgPrearch;
	private String flgAttrEred;
	private String flgAmmEred;
	private String flgAccImplic;
	private String flgPt;
	private String flgPp;
	private String flgRp;
	private String flgUt;
	private String flgId;
	private String flgFs;
	private String flgDl;
	private Date dtIns;
	private Integer uteIns;
	private Date dtUltMod;
	private Integer uteUltMod;
	private Boolean livAccesso;
	private String flgSc;
	private String flgFa;
	private String flgIn;
	private Boolean defLivAccesso;
	private String flgFc;
	private Boolean flgInclUoSupDefLivAcc;
	private Boolean flgInclSottouoDefLivAcc;
	private Boolean defLivMinuta;
	private String flgGestoreAcl;
	private String flgEntrataPg;
	private String flgUscitaPg;
	private String flgTraufficiPg;
	private String flgEntrataPp;
	private String flgUscitaPp;
	private String flgTraufficiPp;
	private String flgVisEmailNoAss;

	public PttFlguo() {
	}

	public PttFlguo(int idUo) {
		this.idUo = idUo;
	}

	public PttFlguo(int idUo, String flgGestSis, String flgLimiteGest,
			String flgRsv, String flgInterna, String flgArch,
			String flgPrearch, String flgAttrEred, String flgAmmEred,
			String flgAccImplic, String flgPt, String flgPp, String flgRp,
			String flgUt, String flgId, String flgFs, String flgDl, Date dtIns,
			Integer uteIns, Date dtUltMod, Integer uteUltMod,
			Boolean livAccesso, String flgSc, String flgFa, String flgIn,
			Boolean defLivAccesso, String flgFc, Boolean flgInclUoSupDefLivAcc,
			Boolean flgInclSottouoDefLivAcc, Boolean defLivMinuta,
			String flgGestoreAcl, String flgEntrataPg, String flgUscitaPg,
			String flgTraufficiPg, String flgEntrataPp, String flgUscitaPp,
			String flgTraufficiPp, String flgVisEmailNoAss) {
		this.idUo = idUo;
		this.flgGestSis = flgGestSis;
		this.flgLimiteGest = flgLimiteGest;
		this.flgRsv = flgRsv;
		this.flgInterna = flgInterna;
		this.flgArch = flgArch;
		this.flgPrearch = flgPrearch;
		this.flgAttrEred = flgAttrEred;
		this.flgAmmEred = flgAmmEred;
		this.flgAccImplic = flgAccImplic;
		this.flgPt = flgPt;
		this.flgPp = flgPp;
		this.flgRp = flgRp;
		this.flgUt = flgUt;
		this.flgId = flgId;
		this.flgFs = flgFs;
		this.flgDl = flgDl;
		this.dtIns = dtIns;
		this.uteIns = uteIns;
		this.dtUltMod = dtUltMod;
		this.uteUltMod = uteUltMod;
		this.livAccesso = livAccesso;
		this.flgSc = flgSc;
		this.flgFa = flgFa;
		this.flgIn = flgIn;
		this.defLivAccesso = defLivAccesso;
		this.flgFc = flgFc;
		this.flgInclUoSupDefLivAcc = flgInclUoSupDefLivAcc;
		this.flgInclSottouoDefLivAcc = flgInclSottouoDefLivAcc;
		this.defLivMinuta = defLivMinuta;
		this.flgGestoreAcl = flgGestoreAcl;
		this.flgEntrataPg = flgEntrataPg;
		this.flgUscitaPg = flgUscitaPg;
		this.flgTraufficiPg = flgTraufficiPg;
		this.flgEntrataPp = flgEntrataPp;
		this.flgUscitaPp = flgUscitaPp;
		this.flgTraufficiPp = flgTraufficiPp;
		this.flgVisEmailNoAss = flgVisEmailNoAss;
	}

	@Id
	@Column(name = "ID_UO", unique = true, nullable = false, precision = 8, scale = 0)
	public int getIdUo() {
		return this.idUo;
	}

	public void setIdUo(int idUo) {
		this.idUo = idUo;
	}

	@Column(name = "FLG_GEST_SIS", length = 1)
	public String getFlgGestSis() {
		return this.flgGestSis;
	}

	public void setFlgGestSis(String flgGestSis) {
		this.flgGestSis = flgGestSis;
	}

	@Column(name = "FLG_LIMITE_GEST", length = 1)
	public String getFlgLimiteGest() {
		return this.flgLimiteGest;
	}

	public void setFlgLimiteGest(String flgLimiteGest) {
		this.flgLimiteGest = flgLimiteGest;
	}

	@Column(name = "FLG_RSV", length = 1)
	public String getFlgRsv() {
		return this.flgRsv;
	}

	public void setFlgRsv(String flgRsv) {
		this.flgRsv = flgRsv;
	}

	@Column(name = "FLG_INTERNA", length = 1)
	public String getFlgInterna() {
		return this.flgInterna;
	}

	public void setFlgInterna(String flgInterna) {
		this.flgInterna = flgInterna;
	}

	@Column(name = "FLG_ARCH", length = 1)
	public String getFlgArch() {
		return this.flgArch;
	}

	public void setFlgArch(String flgArch) {
		this.flgArch = flgArch;
	}

	@Column(name = "FLG_PREARCH", length = 1)
	public String getFlgPrearch() {
		return this.flgPrearch;
	}

	public void setFlgPrearch(String flgPrearch) {
		this.flgPrearch = flgPrearch;
	}

	@Column(name = "FLG_ATTR_ERED", length = 1)
	public String getFlgAttrEred() {
		return this.flgAttrEred;
	}

	public void setFlgAttrEred(String flgAttrEred) {
		this.flgAttrEred = flgAttrEred;
	}

	@Column(name = "FLG_AMM_ERED", length = 1)
	public String getFlgAmmEred() {
		return this.flgAmmEred;
	}

	public void setFlgAmmEred(String flgAmmEred) {
		this.flgAmmEred = flgAmmEred;
	}

	@Column(name = "FLG_ACC_IMPLIC", length = 1)
	public String getFlgAccImplic() {
		return this.flgAccImplic;
	}

	public void setFlgAccImplic(String flgAccImplic) {
		this.flgAccImplic = flgAccImplic;
	}

	@Column(name = "FLG_PT", length = 1)
	public String getFlgPt() {
		return this.flgPt;
	}

	public void setFlgPt(String flgPt) {
		this.flgPt = flgPt;
	}

	@Column(name = "FLG_PP", length = 1)
	public String getFlgPp() {
		return this.flgPp;
	}

	public void setFlgPp(String flgPp) {
		this.flgPp = flgPp;
	}

	@Column(name = "FLG_RP", length = 1)
	public String getFlgRp() {
		return this.flgRp;
	}

	public void setFlgRp(String flgRp) {
		this.flgRp = flgRp;
	}

	@Column(name = "FLG_UT", length = 1)
	public String getFlgUt() {
		return this.flgUt;
	}

	public void setFlgUt(String flgUt) {
		this.flgUt = flgUt;
	}

	@Column(name = "FLG_ID", length = 1)
	public String getFlgId() {
		return this.flgId;
	}

	public void setFlgId(String flgId) {
		this.flgId = flgId;
	}

	@Column(name = "FLG_FS", length = 1)
	public String getFlgFs() {
		return this.flgFs;
	}

	public void setFlgFs(String flgFs) {
		this.flgFs = flgFs;
	}

	@Column(name = "FLG_DL", length = 1)
	public String getFlgDl() {
		return this.flgDl;
	}

	public void setFlgDl(String flgDl) {
		this.flgDl = flgDl;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DT_INS", length = 7)
	public Date getDtIns() {
		return this.dtIns;
	}

	public void setDtIns(Date dtIns) {
		this.dtIns = dtIns;
	}

	@Column(name = "UTE_INS", precision = 6, scale = 0)
	public Integer getUteIns() {
		return this.uteIns;
	}

	public void setUteIns(Integer uteIns) {
		this.uteIns = uteIns;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DT_ULT_MOD", length = 7)
	public Date getDtUltMod() {
		return this.dtUltMod;
	}

	public void setDtUltMod(Date dtUltMod) {
		this.dtUltMod = dtUltMod;
	}

	@Column(name = "UTE_ULT_MOD", precision = 6, scale = 0)
	public Integer getUteUltMod() {
		return this.uteUltMod;
	}

	public void setUteUltMod(Integer uteUltMod) {
		this.uteUltMod = uteUltMod;
	}

	@Column(name = "LIV_ACCESSO", precision = 1, scale = 0)
	public Boolean getLivAccesso() {
		return this.livAccesso;
	}

	public void setLivAccesso(Boolean livAccesso) {
		this.livAccesso = livAccesso;
	}

	@Column(name = "FLG_SC", length = 1)
	public String getFlgSc() {
		return this.flgSc;
	}

	public void setFlgSc(String flgSc) {
		this.flgSc = flgSc;
	}

	@Column(name = "FLG_FA", length = 1)
	public String getFlgFa() {
		return this.flgFa;
	}

	public void setFlgFa(String flgFa) {
		this.flgFa = flgFa;
	}

	@Column(name = "FLG_IN", length = 1)
	public String getFlgIn() {
		return this.flgIn;
	}

	public void setFlgIn(String flgIn) {
		this.flgIn = flgIn;
	}

	@Column(name = "DEF_LIV_ACCESSO", precision = 1, scale = 0)
	public Boolean getDefLivAccesso() {
		return this.defLivAccesso;
	}

	public void setDefLivAccesso(Boolean defLivAccesso) {
		this.defLivAccesso = defLivAccesso;
	}

	@Column(name = "FLG_FC", length = 1)
	public String getFlgFc() {
		return this.flgFc;
	}

	public void setFlgFc(String flgFc) {
		this.flgFc = flgFc;
	}

	@Column(name = "FLG_INCL_UO_SUP_DEF_LIV_ACC", precision = 1, scale = 0)
	public Boolean getFlgInclUoSupDefLivAcc() {
		return this.flgInclUoSupDefLivAcc;
	}

	public void setFlgInclUoSupDefLivAcc(Boolean flgInclUoSupDefLivAcc) {
		this.flgInclUoSupDefLivAcc = flgInclUoSupDefLivAcc;
	}

	@Column(name = "FLG_INCL_SOTTOUO_DEF_LIV_ACC", precision = 1, scale = 0)
	public Boolean getFlgInclSottouoDefLivAcc() {
		return this.flgInclSottouoDefLivAcc;
	}

	public void setFlgInclSottouoDefLivAcc(Boolean flgInclSottouoDefLivAcc) {
		this.flgInclSottouoDefLivAcc = flgInclSottouoDefLivAcc;
	}

	@Column(name = "DEF_LIV_MINUTA", precision = 1, scale = 0)
	public Boolean getDefLivMinuta() {
		return this.defLivMinuta;
	}

	public void setDefLivMinuta(Boolean defLivMinuta) {
		this.defLivMinuta = defLivMinuta;
	}

	@Column(name = "FLG_GESTORE_ACL", length = 1)
	public String getFlgGestoreAcl() {
		return this.flgGestoreAcl;
	}

	public void setFlgGestoreAcl(String flgGestoreAcl) {
		this.flgGestoreAcl = flgGestoreAcl;
	}

	@Column(name = "FLG_ENTRATA_PG", length = 1)
	public String getFlgEntrataPg() {
		return this.flgEntrataPg;
	}

	public void setFlgEntrataPg(String flgEntrataPg) {
		this.flgEntrataPg = flgEntrataPg;
	}

	@Column(name = "FLG_USCITA_PG", length = 1)
	public String getFlgUscitaPg() {
		return this.flgUscitaPg;
	}

	public void setFlgUscitaPg(String flgUscitaPg) {
		this.flgUscitaPg = flgUscitaPg;
	}

	@Column(name = "FLG_TRAUFFICI_PG", length = 1)
	public String getFlgTraufficiPg() {
		return this.flgTraufficiPg;
	}

	public void setFlgTraufficiPg(String flgTraufficiPg) {
		this.flgTraufficiPg = flgTraufficiPg;
	}

	@Column(name = "FLG_ENTRATA_PP", length = 1)
	public String getFlgEntrataPp() {
		return this.flgEntrataPp;
	}

	public void setFlgEntrataPp(String flgEntrataPp) {
		this.flgEntrataPp = flgEntrataPp;
	}

	@Column(name = "FLG_USCITA_PP", length = 1)
	public String getFlgUscitaPp() {
		return this.flgUscitaPp;
	}

	public void setFlgUscitaPp(String flgUscitaPp) {
		this.flgUscitaPp = flgUscitaPp;
	}

	@Column(name = "FLG_TRAUFFICI_PP", length = 1)
	public String getFlgTraufficiPp() {
		return this.flgTraufficiPp;
	}

	public void setFlgTraufficiPp(String flgTraufficiPp) {
		this.flgTraufficiPp = flgTraufficiPp;
	}

	@Column(name = "FLG_VIS_EMAIL_NO_ASS", length = 1)
	public String getFlgVisEmailNoAss() {
		return this.flgVisEmailNoAss;
	}

	public void setFlgVisEmailNoAss(String flgVisEmailNoAss) {
		this.flgVisEmailNoAss = flgVisEmailNoAss;
	}

}
