/* * SPDX-License-Identifier: AGPL-3.0-or-later * * C Copyright 2023 Regione Piemonte * */

// Generated 22-set-2016 12.14.09 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PttInformAnn generated by hbm2java
 */
@Entity
@Table(name = "PTT_INFORM_ANN")
public class PttInformAnn implements java.io.Serializable {

	private PttInformAnnId id;
	private PttDocumenti pttDocumenti;
	private CvtUtenti cvtUtenti;
	private CvtUo cvtUoByUoProv;
	private PttAttiProtDiff pttAttiProtDiff;
	private PttAttiAnn pttAttiAnn;
	private CvtUo cvtUoByUoDest;
	private CvtUo cvtUoByUoAnn;
	private String txtOgg;
	private Date dtArrivo;
	private String protProv;
	private Date dtProv;
	private String tpRegEmerg;
	private Short annoRegEmerg;
	private Integer numRegEmerg;
	private String impronta;
	private String noteProtDiff;
	private Date dtTermineReg;
	private String flgNomAnn;
	private String noteAnn;
	private String flgDocinfAnn;
	private Byte verDocinfAnn;
	private String flgTpProt;

	public PttInformAnn() {
	}

	public PttInformAnn(PttInformAnnId id, PttDocumenti pttDocumenti,
			CvtUtenti cvtUtenti, CvtUo cvtUoByUoAnn) {
		this.id = id;
		this.pttDocumenti = pttDocumenti;
		this.cvtUtenti = cvtUtenti;
		this.cvtUoByUoAnn = cvtUoByUoAnn;
	}

	public PttInformAnn(PttInformAnnId id, PttDocumenti pttDocumenti,
			CvtUtenti cvtUtenti, CvtUo cvtUoByUoProv,
			PttAttiProtDiff pttAttiProtDiff, PttAttiAnn pttAttiAnn,
			CvtUo cvtUoByUoDest, CvtUo cvtUoByUoAnn, String txtOgg,
			Date dtArrivo, String protProv, Date dtProv, String tpRegEmerg,
			Short annoRegEmerg, Integer numRegEmerg, String impronta,
			String noteProtDiff, Date dtTermineReg, String flgNomAnn,
			String noteAnn, String flgDocinfAnn, Byte verDocinfAnn,
			String flgTpProt) {
		this.id = id;
		this.pttDocumenti = pttDocumenti;
		this.cvtUtenti = cvtUtenti;
		this.cvtUoByUoProv = cvtUoByUoProv;
		this.pttAttiProtDiff = pttAttiProtDiff;
		this.pttAttiAnn = pttAttiAnn;
		this.cvtUoByUoDest = cvtUoByUoDest;
		this.cvtUoByUoAnn = cvtUoByUoAnn;
		this.txtOgg = txtOgg;
		this.dtArrivo = dtArrivo;
		this.protProv = protProv;
		this.dtProv = dtProv;
		this.tpRegEmerg = tpRegEmerg;
		this.annoRegEmerg = annoRegEmerg;
		this.numRegEmerg = numRegEmerg;
		this.impronta = impronta;
		this.noteProtDiff = noteProtDiff;
		this.dtTermineReg = dtTermineReg;
		this.flgNomAnn = flgNomAnn;
		this.noteAnn = noteAnn;
		this.flgDocinfAnn = flgDocinfAnn;
		this.verDocinfAnn = verDocinfAnn;
		this.flgTpProt = flgTpProt;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "idDoc", column = @Column(name = "ID_DOC", nullable = false, precision = 8, scale = 0)),
			@AttributeOverride(name = "dtAnn", column = @Column(name = "DT_ANN", nullable = false, length = 7)) })
	public PttInformAnnId getId() {
		return this.id;
	}

	public void setId(PttInformAnnId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_DOC", nullable = false, insertable = false, updatable = false)
	public PttDocumenti getPttDocumenti() {
		return this.pttDocumenti;
	}

	public void setPttDocumenti(PttDocumenti pttDocumenti) {
		this.pttDocumenti = pttDocumenti;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "UTE_ANN", nullable = false)
	public CvtUtenti getCvtUtenti() {
		return this.cvtUtenti;
	}

	public void setCvtUtenti(CvtUtenti cvtUtenti) {
		this.cvtUtenti = cvtUtenti;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "UO_PROV")
	public CvtUo getCvtUoByUoProv() {
		return this.cvtUoByUoProv;
	}

	public void setCvtUoByUoProv(CvtUo cvtUoByUoProv) {
		this.cvtUoByUoProv = cvtUoByUoProv;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_ATTO")
	public PttAttiProtDiff getPttAttiProtDiff() {
		return this.pttAttiProtDiff;
	}

	public void setPttAttiProtDiff(PttAttiProtDiff pttAttiProtDiff) {
		this.pttAttiProtDiff = pttAttiProtDiff;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_ATTO_ANN")
	public PttAttiAnn getPttAttiAnn() {
		return this.pttAttiAnn;
	}

	public void setPttAttiAnn(PttAttiAnn pttAttiAnn) {
		this.pttAttiAnn = pttAttiAnn;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "UO_DEST")
	public CvtUo getCvtUoByUoDest() {
		return this.cvtUoByUoDest;
	}

	public void setCvtUoByUoDest(CvtUo cvtUoByUoDest) {
		this.cvtUoByUoDest = cvtUoByUoDest;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "UO_ANN", nullable = false)
	public CvtUo getCvtUoByUoAnn() {
		return this.cvtUoByUoAnn;
	}

	public void setCvtUoByUoAnn(CvtUo cvtUoByUoAnn) {
		this.cvtUoByUoAnn = cvtUoByUoAnn;
	}

	@Column(name = "TXT_OGG", length = 500)
	public String getTxtOgg() {
		return this.txtOgg;
	}

	public void setTxtOgg(String txtOgg) {
		this.txtOgg = txtOgg;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DT_ARRIVO", length = 7)
	public Date getDtArrivo() {
		return this.dtArrivo;
	}

	public void setDtArrivo(Date dtArrivo) {
		this.dtArrivo = dtArrivo;
	}

	@Column(name = "PROT_PROV", length = 20)
	public String getProtProv() {
		return this.protProv;
	}

	public void setProtProv(String protProv) {
		this.protProv = protProv;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DT_PROV", length = 7)
	public Date getDtProv() {
		return this.dtProv;
	}

	public void setDtProv(Date dtProv) {
		this.dtProv = dtProv;
	}

	@Column(name = "TP_REG_EMERG", length = 5)
	public String getTpRegEmerg() {
		return this.tpRegEmerg;
	}

	public void setTpRegEmerg(String tpRegEmerg) {
		this.tpRegEmerg = tpRegEmerg;
	}

	@Column(name = "ANNO_REG_EMERG", precision = 4, scale = 0)
	public Short getAnnoRegEmerg() {
		return this.annoRegEmerg;
	}

	public void setAnnoRegEmerg(Short annoRegEmerg) {
		this.annoRegEmerg = annoRegEmerg;
	}

	@Column(name = "NUM_REG_EMERG", precision = 7, scale = 0)
	public Integer getNumRegEmerg() {
		return this.numRegEmerg;
	}

	public void setNumRegEmerg(Integer numRegEmerg) {
		this.numRegEmerg = numRegEmerg;
	}

	@Column(name = "IMPRONTA", length = 20)
	public String getImpronta() {
		return this.impronta;
	}

	public void setImpronta(String impronta) {
		this.impronta = impronta;
	}

	@Column(name = "NOTE_PROT_DIFF", length = 250)
	public String getNoteProtDiff() {
		return this.noteProtDiff;
	}

	public void setNoteProtDiff(String noteProtDiff) {
		this.noteProtDiff = noteProtDiff;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DT_TERMINE_REG", length = 7)
	public Date getDtTermineReg() {
		return this.dtTermineReg;
	}

	public void setDtTermineReg(Date dtTermineReg) {
		this.dtTermineReg = dtTermineReg;
	}

	@Column(name = "FLG_NOM_ANN", length = 1)
	public String getFlgNomAnn() {
		return this.flgNomAnn;
	}

	public void setFlgNomAnn(String flgNomAnn) {
		this.flgNomAnn = flgNomAnn;
	}

	@Column(name = "NOTE_ANN", length = 250)
	public String getNoteAnn() {
		return this.noteAnn;
	}

	public void setNoteAnn(String noteAnn) {
		this.noteAnn = noteAnn;
	}

	@Column(name = "FLG_DOCINF_ANN", length = 1)
	public String getFlgDocinfAnn() {
		return this.flgDocinfAnn;
	}

	public void setFlgDocinfAnn(String flgDocinfAnn) {
		this.flgDocinfAnn = flgDocinfAnn;
	}

	@Column(name = "VER_DOCINF_ANN", precision = 2, scale = 0)
	public Byte getVerDocinfAnn() {
		return this.verDocinfAnn;
	}

	public void setVerDocinfAnn(Byte verDocinfAnn) {
		this.verDocinfAnn = verDocinfAnn;
	}

	@Column(name = "FLG_TP_PROT", length = 2)
	public String getFlgTpProt() {
		return this.flgTpProt;
	}

	public void setFlgTpProt(String flgTpProt) {
		this.flgTpProt = flgTpProt;
	}

}
