/* * SPDX-License-Identifier: AGPL-3.0-or-later * * C Copyright 2023 Regione Piemonte * */

// Generated 22-set-2016 12.14.09 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PttIndici generated by hbm2java
 */
@Entity
@Table(name = "PTT_INDICI")
public class PttIndici implements java.io.Serializable {

	private int idIndice;
	private PttTitolazioni pttTitolazioni;
	private CvtUo cvtUo;
	private PttTpDoc pttTpDoc;
	private String desIndice;
	private Date dtInizioVld;
	private Date dtFineVld;
	private Date dtIns;
	private Integer uteIns;
	private Date dtUltMod;
	private Integer uteUltMod;
	private Set<PttCopie> pttCopies = new HashSet<PttCopie>(0);
	private Set<PttAssegnIntReg> pttAssegnIntRegs = new HashSet<PttAssegnIntReg>(
			0);
	private Set<PttRichSpostamento> pttRichSpostamentos = new HashSet<PttRichSpostamento>(
			0);
	private Set<PttDocInFirma> pttDocInFirmas = new HashSet<PttDocInFirma>(0);

	public PttIndici() {
	}

	public PttIndici(int idIndice, PttTitolazioni pttTitolazioni,
			String desIndice, Date dtInizioVld) {
		this.idIndice = idIndice;
		this.pttTitolazioni = pttTitolazioni;
		this.desIndice = desIndice;
		this.dtInizioVld = dtInizioVld;
	}

	public PttIndici(int idIndice, PttTitolazioni pttTitolazioni, CvtUo cvtUo,
			PttTpDoc pttTpDoc, String desIndice, Date dtInizioVld,
			Date dtFineVld, Date dtIns, Integer uteIns, Date dtUltMod,
			Integer uteUltMod, Set<PttCopie> pttCopies,
			Set<PttAssegnIntReg> pttAssegnIntRegs,
			Set<PttRichSpostamento> pttRichSpostamentos,
			Set<PttDocInFirma> pttDocInFirmas) {
		this.idIndice = idIndice;
		this.pttTitolazioni = pttTitolazioni;
		this.cvtUo = cvtUo;
		this.pttTpDoc = pttTpDoc;
		this.desIndice = desIndice;
		this.dtInizioVld = dtInizioVld;
		this.dtFineVld = dtFineVld;
		this.dtIns = dtIns;
		this.uteIns = uteIns;
		this.dtUltMod = dtUltMod;
		this.uteUltMod = uteUltMod;
		this.pttCopies = pttCopies;
		this.pttAssegnIntRegs = pttAssegnIntRegs;
		this.pttRichSpostamentos = pttRichSpostamentos;
		this.pttDocInFirmas = pttDocInFirmas;
	}

	@Id
	@Column(name = "ID_INDICE", unique = true, nullable = false, precision = 8, scale = 0)
	public int getIdIndice() {
		return this.idIndice;
	}

	public void setIdIndice(int idIndice) {
		this.idIndice = idIndice;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_TITOLAZIONE", nullable = false)
	public PttTitolazioni getPttTitolazioni() {
		return this.pttTitolazioni;
	}

	public void setPttTitolazioni(PttTitolazioni pttTitolazioni) {
		this.pttTitolazioni = pttTitolazioni;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_UO")
	public CvtUo getCvtUo() {
		return this.cvtUo;
	}

	public void setCvtUo(CvtUo cvtUo) {
		this.cvtUo = cvtUo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_TP_DOC")
	public PttTpDoc getPttTpDoc() {
		return this.pttTpDoc;
	}

	public void setPttTpDoc(PttTpDoc pttTpDoc) {
		this.pttTpDoc = pttTpDoc;
	}

	@Column(name = "DES_INDICE", nullable = false, length = 250)
	public String getDesIndice() {
		return this.desIndice;
	}

	public void setDesIndice(String desIndice) {
		this.desIndice = desIndice;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DT_INIZIO_VLD", nullable = false, length = 7)
	public Date getDtInizioVld() {
		return this.dtInizioVld;
	}

	public void setDtInizioVld(Date dtInizioVld) {
		this.dtInizioVld = dtInizioVld;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DT_FINE_VLD", length = 7)
	public Date getDtFineVld() {
		return this.dtFineVld;
	}

	public void setDtFineVld(Date dtFineVld) {
		this.dtFineVld = dtFineVld;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DT_INS", length = 7)
	public Date getDtIns() {
		return this.dtIns;
	}

	public void setDtIns(Date dtIns) {
		this.dtIns = dtIns;
	}

	@Column(name = "UTE_INS", precision = 6, scale = 0)
	public Integer getUteIns() {
		return this.uteIns;
	}

	public void setUteIns(Integer uteIns) {
		this.uteIns = uteIns;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DT_ULT_MOD", length = 7)
	public Date getDtUltMod() {
		return this.dtUltMod;
	}

	public void setDtUltMod(Date dtUltMod) {
		this.dtUltMod = dtUltMod;
	}

	@Column(name = "UTE_ULT_MOD", precision = 6, scale = 0)
	public Integer getUteUltMod() {
		return this.uteUltMod;
	}

	public void setUteUltMod(Integer uteUltMod) {
		this.uteUltMod = uteUltMod;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pttIndici")
	public Set<PttCopie> getPttCopies() {
		return this.pttCopies;
	}

	public void setPttCopies(Set<PttCopie> pttCopies) {
		this.pttCopies = pttCopies;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pttIndici")
	public Set<PttAssegnIntReg> getPttAssegnIntRegs() {
		return this.pttAssegnIntRegs;
	}

	public void setPttAssegnIntRegs(Set<PttAssegnIntReg> pttAssegnIntRegs) {
		this.pttAssegnIntRegs = pttAssegnIntRegs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pttIndici")
	public Set<PttRichSpostamento> getPttRichSpostamentos() {
		return this.pttRichSpostamentos;
	}

	public void setPttRichSpostamentos(
			Set<PttRichSpostamento> pttRichSpostamentos) {
		this.pttRichSpostamentos = pttRichSpostamentos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pttIndici")
	public Set<PttDocInFirma> getPttDocInFirmas() {
		return this.pttDocInFirmas;
	}

	public void setPttDocInFirmas(Set<PttDocInFirma> pttDocInFirmas) {
		this.pttDocInFirmas = pttDocInFirmas;
	}

}
