/* * SPDX-License-Identifier: AGPL-3.0-or-later * * C Copyright 2023 Regione Piemonte * */

// Generated 22-set-2016 12.14.09 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PttLogSendmail generated by hbm2java
 */
@Entity
@Table(name = "PTT_LOG_SENDMAIL")
public class PttLogSendmail implements java.io.Serializable {

	private BigDecimal idMail;
	private Date dtInvio;
	private String oggetto;
	private String destAa;
	private String destCc;
	private String destBcc;
	private String bodymail;
	private BigDecimal esito;
	private Set<PttLogMail> pttLogMails = new HashSet<PttLogMail>(0);

	public PttLogSendmail() {
	}

	public PttLogSendmail(BigDecimal idMail, Date dtInvio) {
		this.idMail = idMail;
		this.dtInvio = dtInvio;
	}

	public PttLogSendmail(BigDecimal idMail, Date dtInvio, String oggetto,
			String destAa, String destCc, String destBcc, String bodymail,
			BigDecimal esito, Set<PttLogMail> pttLogMails) {
		this.idMail = idMail;
		this.dtInvio = dtInvio;
		this.oggetto = oggetto;
		this.destAa = destAa;
		this.destCc = destCc;
		this.destBcc = destBcc;
		this.bodymail = bodymail;
		this.esito = esito;
		this.pttLogMails = pttLogMails;
	}

	@Id
	@Column(name = "ID_MAIL", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdMail() {
		return this.idMail;
	}

	public void setIdMail(BigDecimal idMail) {
		this.idMail = idMail;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DT_INVIO", nullable = false, length = 7)
	public Date getDtInvio() {
		return this.dtInvio;
	}

	public void setDtInvio(Date dtInvio) {
		this.dtInvio = dtInvio;
	}

	@Column(name = "OGGETTO", length = 500)
	public String getOggetto() {
		return this.oggetto;
	}

	public void setOggetto(String oggetto) {
		this.oggetto = oggetto;
	}

	@Column(name = "DEST_AA", length = 4000)
	public String getDestAa() {
		return this.destAa;
	}

	public void setDestAa(String destAa) {
		this.destAa = destAa;
	}

	@Column(name = "DEST_CC", length = 4000)
	public String getDestCc() {
		return this.destCc;
	}

	public void setDestCc(String destCc) {
		this.destCc = destCc;
	}

	@Column(name = "DEST_BCC", length = 4000)
	public String getDestBcc() {
		return this.destBcc;
	}

	public void setDestBcc(String destBcc) {
		this.destBcc = destBcc;
	}

	@Column(name = "BODYMAIL", length = 4000)
	public String getBodymail() {
		return this.bodymail;
	}

	public void setBodymail(String bodymail) {
		this.bodymail = bodymail;
	}

	@Column(name = "ESITO", precision = 22, scale = 0)
	public BigDecimal getEsito() {
		return this.esito;
	}

	public void setEsito(BigDecimal esito) {
		this.esito = esito;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pttLogSendmail")
	public Set<PttLogMail> getPttLogMails() {
		return this.pttLogMails;
	}

	public void setPttLogMails(Set<PttLogMail> pttLogMails) {
		this.pttLogMails = pttLogMails;
	}

}
