/* * SPDX-License-Identifier: AGPL-3.0-or-later * * C Copyright 2023 Regione Piemonte * */

// Generated 22-set-2016 12.14.09 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PttLogMail generated by hbm2java
 */
@Entity
@Table(name = "PTT_LOG_MAIL")
public class PttLogMail implements java.io.Serializable {

	private BigDecimal idLog;
	private PttLogSendmail pttLogSendmail;
	private Date dtLog;
	private BigDecimal codErr;
	private String descErr;

	public PttLogMail() {
	}

	public PttLogMail(BigDecimal idLog, Date dtLog) {
		this.idLog = idLog;
		this.dtLog = dtLog;
	}

	public PttLogMail(BigDecimal idLog, PttLogSendmail pttLogSendmail,
			Date dtLog, BigDecimal codErr, String descErr) {
		this.idLog = idLog;
		this.pttLogSendmail = pttLogSendmail;
		this.dtLog = dtLog;
		this.codErr = codErr;
		this.descErr = descErr;
	}

	@Id
	@Column(name = "ID_LOG", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdLog() {
		return this.idLog;
	}

	public void setIdLog(BigDecimal idLog) {
		this.idLog = idLog;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_MAIL")
	public PttLogSendmail getPttLogSendmail() {
		return this.pttLogSendmail;
	}

	public void setPttLogSendmail(PttLogSendmail pttLogSendmail) {
		this.pttLogSendmail = pttLogSendmail;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DT_LOG", nullable = false, length = 7)
	public Date getDtLog() {
		return this.dtLog;
	}

	public void setDtLog(Date dtLog) {
		this.dtLog = dtLog;
	}

	@Column(name = "COD_ERR", precision = 22, scale = 0)
	public BigDecimal getCodErr() {
		return this.codErr;
	}

	public void setCodErr(BigDecimal codErr) {
		this.codErr = codErr;
	}

	@Column(name = "DESC_ERR", length = 1000)
	public String getDescErr() {
		return this.descErr;
	}

	public void setDescErr(String descErr) {
		this.descErr = descErr;
	}

}
