/* * SPDX-License-Identifier: AGPL-3.0-or-later * * C Copyright 2023 Regione Piemonte * */

// Generated 22-set-2016 12.14.09 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PttModelli generated by hbm2java
 */
@Entity
@Table(name = "PTT_MODELLI")
public class PttModelli implements java.io.Serializable {

	private PttModelliId id;
	private String desModello;
	private Date dtInizioVld;
	private Date dtFineVld;
	private BigDecimal idTitolazione;
	private Integer idIndice;
	private Short idTpFis;
	private Short idTpLog;
	private Short idSttpLog;
	private String flgCpf;
	private String flgEvd;
	private String flgPtRep;
	private String flgRsv;
	private String txtOgg;
	private Date dtIns;
	private Integer uteIns;
	private Date dtUltMod;
	private Integer uteUltMod;
	private Integer idUoAssOrig;
	private Integer idUoDest;
	private Integer idUoProv;
	private Date dtRaccomandata;
	private String nroRaccomandata;

	public PttModelli() {
	}

	public PttModelli(PttModelliId id, String desModello, Date dtInizioVld,
			String flgPtRep) {
		this.id = id;
		this.desModello = desModello;
		this.dtInizioVld = dtInizioVld;
		this.flgPtRep = flgPtRep;
	}

	public PttModelli(PttModelliId id, String desModello, Date dtInizioVld,
			Date dtFineVld, BigDecimal idTitolazione, Integer idIndice,
			Short idTpFis, Short idTpLog, Short idSttpLog, String flgCpf,
			String flgEvd, String flgPtRep, String flgRsv, String txtOgg,
			Date dtIns, Integer uteIns, Date dtUltMod, Integer uteUltMod,
			Integer idUoAssOrig, Integer idUoDest, Integer idUoProv,
			Date dtRaccomandata, String nroRaccomandata) {
		this.id = id;
		this.desModello = desModello;
		this.dtInizioVld = dtInizioVld;
		this.dtFineVld = dtFineVld;
		this.idTitolazione = idTitolazione;
		this.idIndice = idIndice;
		this.idTpFis = idTpFis;
		this.idTpLog = idTpLog;
		this.idSttpLog = idSttpLog;
		this.flgCpf = flgCpf;
		this.flgEvd = flgEvd;
		this.flgPtRep = flgPtRep;
		this.flgRsv = flgRsv;
		this.txtOgg = txtOgg;
		this.dtIns = dtIns;
		this.uteIns = uteIns;
		this.dtUltMod = dtUltMod;
		this.uteUltMod = uteUltMod;
		this.idUoAssOrig = idUoAssOrig;
		this.idUoDest = idUoDest;
		this.idUoProv = idUoProv;
		this.dtRaccomandata = dtRaccomandata;
		this.nroRaccomandata = nroRaccomandata;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "idModello", column = @Column(name = "ID_MODELLO", nullable = false, precision = 8, scale = 0)),
			@AttributeOverride(name = "codEnte", column = @Column(name = "COD_ENTE", nullable = false, length = 3)) })
	public PttModelliId getId() {
		return this.id;
	}

	public void setId(PttModelliId id) {
		this.id = id;
	}

	@Column(name = "DES_MODELLO", nullable = false, length = 150)
	public String getDesModello() {
		return this.desModello;
	}

	public void setDesModello(String desModello) {
		this.desModello = desModello;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DT_INIZIO_VLD", nullable = false, length = 7)
	public Date getDtInizioVld() {
		return this.dtInizioVld;
	}

	public void setDtInizioVld(Date dtInizioVld) {
		this.dtInizioVld = dtInizioVld;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DT_FINE_VLD", length = 7)
	public Date getDtFineVld() {
		return this.dtFineVld;
	}

	public void setDtFineVld(Date dtFineVld) {
		this.dtFineVld = dtFineVld;
	}

	@Column(name = "ID_TITOLAZIONE", precision = 25, scale = 0)
	public BigDecimal getIdTitolazione() {
		return this.idTitolazione;
	}

	public void setIdTitolazione(BigDecimal idTitolazione) {
		this.idTitolazione = idTitolazione;
	}

	@Column(name = "ID_INDICE", precision = 8, scale = 0)
	public Integer getIdIndice() {
		return this.idIndice;
	}

	public void setIdIndice(Integer idIndice) {
		this.idIndice = idIndice;
	}

	@Column(name = "ID_TP_FIS", precision = 4, scale = 0)
	public Short getIdTpFis() {
		return this.idTpFis;
	}

	public void setIdTpFis(Short idTpFis) {
		this.idTpFis = idTpFis;
	}

	@Column(name = "ID_TP_LOG", precision = 4, scale = 0)
	public Short getIdTpLog() {
		return this.idTpLog;
	}

	public void setIdTpLog(Short idTpLog) {
		this.idTpLog = idTpLog;
	}

	@Column(name = "ID_STTP_LOG", precision = 4, scale = 0)
	public Short getIdSttpLog() {
		return this.idSttpLog;
	}

	public void setIdSttpLog(Short idSttpLog) {
		this.idSttpLog = idSttpLog;
	}

	@Column(name = "FLG_CPF", length = 1)
	public String getFlgCpf() {
		return this.flgCpf;
	}

	public void setFlgCpf(String flgCpf) {
		this.flgCpf = flgCpf;
	}

	@Column(name = "FLG_EVD", length = 1)
	public String getFlgEvd() {
		return this.flgEvd;
	}

	public void setFlgEvd(String flgEvd) {
		this.flgEvd = flgEvd;
	}

	@Column(name = "FLG_PT_REP", nullable = false, length = 1)
	public String getFlgPtRep() {
		return this.flgPtRep;
	}

	public void setFlgPtRep(String flgPtRep) {
		this.flgPtRep = flgPtRep;
	}

	@Column(name = "FLG_RSV", length = 1)
	public String getFlgRsv() {
		return this.flgRsv;
	}

	public void setFlgRsv(String flgRsv) {
		this.flgRsv = flgRsv;
	}

	@Column(name = "TXT_OGG", length = 500)
	public String getTxtOgg() {
		return this.txtOgg;
	}

	public void setTxtOgg(String txtOgg) {
		this.txtOgg = txtOgg;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DT_INS", length = 7)
	public Date getDtIns() {
		return this.dtIns;
	}

	public void setDtIns(Date dtIns) {
		this.dtIns = dtIns;
	}

	@Column(name = "UTE_INS", precision = 6, scale = 0)
	public Integer getUteIns() {
		return this.uteIns;
	}

	public void setUteIns(Integer uteIns) {
		this.uteIns = uteIns;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DT_ULT_MOD", length = 7)
	public Date getDtUltMod() {
		return this.dtUltMod;
	}

	public void setDtUltMod(Date dtUltMod) {
		this.dtUltMod = dtUltMod;
	}

	@Column(name = "UTE_ULT_MOD", precision = 6, scale = 0)
	public Integer getUteUltMod() {
		return this.uteUltMod;
	}

	public void setUteUltMod(Integer uteUltMod) {
		this.uteUltMod = uteUltMod;
	}

	@Column(name = "ID_UO_ASS_ORIG", precision = 8, scale = 0)
	public Integer getIdUoAssOrig() {
		return this.idUoAssOrig;
	}

	public void setIdUoAssOrig(Integer idUoAssOrig) {
		this.idUoAssOrig = idUoAssOrig;
	}

	@Column(name = "ID_UO_DEST", precision = 8, scale = 0)
	public Integer getIdUoDest() {
		return this.idUoDest;
	}

	public void setIdUoDest(Integer idUoDest) {
		this.idUoDest = idUoDest;
	}

	@Column(name = "ID_UO_PROV", precision = 8, scale = 0)
	public Integer getIdUoProv() {
		return this.idUoProv;
	}

	public void setIdUoProv(Integer idUoProv) {
		this.idUoProv = idUoProv;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DT_RACCOMANDATA", length = 7)
	public Date getDtRaccomandata() {
		return this.dtRaccomandata;
	}

	public void setDtRaccomandata(Date dtRaccomandata) {
		this.dtRaccomandata = dtRaccomandata;
	}

	@Column(name = "NRO_RACCOMANDATA", length = 30)
	public String getNroRaccomandata() {
		return this.nroRaccomandata;
	}

	public void setNroRaccomandata(String nroRaccomandata) {
		this.nroRaccomandata = nroRaccomandata;
	}

}
