/* * SPDX-License-Identifier: AGPL-3.0-or-later * * C Copyright 2023 Regione Piemonte * */

// Generated 22-set-2016 12.14.09 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PttNommodId generated by hbm2java
 */
@Embeddable
public class PttNommodId implements java.io.Serializable {

	private int idModello;
	private String codEnte;
	private Integer idAnag;
	private String flgEsibDestContr;
	private String flgDestCopia;
	private String flgTpInd;
	private Integer idTopon;
	private Integer numCiv;
	private String espCiv;
	private String desInd;
	private Integer idCom;
	private String desCom;
	private Integer cap;
	private Date dtIns;
	private Integer uteIns;
	private Date dtUltMod;
	private Integer uteUltMod;
	private BigDecimal nroOrdine;
	private Short idTpFis;
	private Date dtRaccomandata;
	private String nroRaccomandata;
	private BigDecimal costoSped;
	private String flgNovisStampe;
	private String desAnag;

	public PttNommodId() {
	}

	public PttNommodId(int idModello, String codEnte, String flgTpInd) {
		this.idModello = idModello;
		this.codEnte = codEnte;
		this.flgTpInd = flgTpInd;
	}

	public PttNommodId(int idModello, String codEnte, Integer idAnag,
			String flgEsibDestContr, String flgDestCopia, String flgTpInd,
			Integer idTopon, Integer numCiv, String espCiv, String desInd,
			Integer idCom, String desCom, Integer cap, Date dtIns,
			Integer uteIns, Date dtUltMod, Integer uteUltMod,
			BigDecimal nroOrdine, Short idTpFis, Date dtRaccomandata,
			String nroRaccomandata, BigDecimal costoSped,
			String flgNovisStampe, String desAnag) {
		this.idModello = idModello;
		this.codEnte = codEnte;
		this.idAnag = idAnag;
		this.flgEsibDestContr = flgEsibDestContr;
		this.flgDestCopia = flgDestCopia;
		this.flgTpInd = flgTpInd;
		this.idTopon = idTopon;
		this.numCiv = numCiv;
		this.espCiv = espCiv;
		this.desInd = desInd;
		this.idCom = idCom;
		this.desCom = desCom;
		this.cap = cap;
		this.dtIns = dtIns;
		this.uteIns = uteIns;
		this.dtUltMod = dtUltMod;
		this.uteUltMod = uteUltMod;
		this.nroOrdine = nroOrdine;
		this.idTpFis = idTpFis;
		this.dtRaccomandata = dtRaccomandata;
		this.nroRaccomandata = nroRaccomandata;
		this.costoSped = costoSped;
		this.flgNovisStampe = flgNovisStampe;
		this.desAnag = desAnag;
	}

	@Column(name = "ID_MODELLO", nullable = false, precision = 8, scale = 0)
	public int getIdModello() {
		return this.idModello;
	}

	public void setIdModello(int idModello) {
		this.idModello = idModello;
	}

	@Column(name = "COD_ENTE", nullable = false, length = 3)
	public String getCodEnte() {
		return this.codEnte;
	}

	public void setCodEnte(String codEnte) {
		this.codEnte = codEnte;
	}

	@Column(name = "ID_ANAG", precision = 9, scale = 0)
	public Integer getIdAnag() {
		return this.idAnag;
	}

	public void setIdAnag(Integer idAnag) {
		this.idAnag = idAnag;
	}

	@Column(name = "FLG_ESIB_DEST_CONTR", length = 1)
	public String getFlgEsibDestContr() {
		return this.flgEsibDestContr;
	}

	public void setFlgEsibDestContr(String flgEsibDestContr) {
		this.flgEsibDestContr = flgEsibDestContr;
	}

	@Column(name = "FLG_DEST_COPIA", length = 1)
	public String getFlgDestCopia() {
		return this.flgDestCopia;
	}

	public void setFlgDestCopia(String flgDestCopia) {
		this.flgDestCopia = flgDestCopia;
	}

	@Column(name = "FLG_TP_IND", nullable = false, length = 1)
	public String getFlgTpInd() {
		return this.flgTpInd;
	}

	public void setFlgTpInd(String flgTpInd) {
		this.flgTpInd = flgTpInd;
	}

	@Column(name = "ID_TOPON", precision = 9, scale = 0)
	public Integer getIdTopon() {
		return this.idTopon;
	}

	public void setIdTopon(Integer idTopon) {
		this.idTopon = idTopon;
	}

	@Column(name = "NUM_CIV", precision = 5, scale = 0)
	public Integer getNumCiv() {
		return this.numCiv;
	}

	public void setNumCiv(Integer numCiv) {
		this.numCiv = numCiv;
	}

	@Column(name = "ESP_CIV", length = 12)
	public String getEspCiv() {
		return this.espCiv;
	}

	public void setEspCiv(String espCiv) {
		this.espCiv = espCiv;
	}

	@Column(name = "DES_IND", length = 60)
	public String getDesInd() {
		return this.desInd;
	}

	public void setDesInd(String desInd) {
		this.desInd = desInd;
	}

	@Column(name = "ID_COM", precision = 6, scale = 0)
	public Integer getIdCom() {
		return this.idCom;
	}

	public void setIdCom(Integer idCom) {
		this.idCom = idCom;
	}

	@Column(name = "DES_COM", length = 60)
	public String getDesCom() {
		return this.desCom;
	}

	public void setDesCom(String desCom) {
		this.desCom = desCom;
	}

	@Column(name = "CAP", precision = 5, scale = 0)
	public Integer getCap() {
		return this.cap;
	}

	public void setCap(Integer cap) {
		this.cap = cap;
	}

	@Column(name = "DT_INS", length = 7)
	public Date getDtIns() {
		return this.dtIns;
	}

	public void setDtIns(Date dtIns) {
		this.dtIns = dtIns;
	}

	@Column(name = "UTE_INS", precision = 6, scale = 0)
	public Integer getUteIns() {
		return this.uteIns;
	}

	public void setUteIns(Integer uteIns) {
		this.uteIns = uteIns;
	}

	@Column(name = "DT_ULT_MOD", length = 7)
	public Date getDtUltMod() {
		return this.dtUltMod;
	}

	public void setDtUltMod(Date dtUltMod) {
		this.dtUltMod = dtUltMod;
	}

	@Column(name = "UTE_ULT_MOD", precision = 6, scale = 0)
	public Integer getUteUltMod() {
		return this.uteUltMod;
	}

	public void setUteUltMod(Integer uteUltMod) {
		this.uteUltMod = uteUltMod;
	}

	@Column(name = "NRO_ORDINE", precision = 22, scale = 0)
	public BigDecimal getNroOrdine() {
		return this.nroOrdine;
	}

	public void setNroOrdine(BigDecimal nroOrdine) {
		this.nroOrdine = nroOrdine;
	}

	@Column(name = "ID_TP_FIS", precision = 4, scale = 0)
	public Short getIdTpFis() {
		return this.idTpFis;
	}

	public void setIdTpFis(Short idTpFis) {
		this.idTpFis = idTpFis;
	}

	@Column(name = "DT_RACCOMANDATA", length = 7)
	public Date getDtRaccomandata() {
		return this.dtRaccomandata;
	}

	public void setDtRaccomandata(Date dtRaccomandata) {
		this.dtRaccomandata = dtRaccomandata;
	}

	@Column(name = "NRO_RACCOMANDATA", length = 30)
	public String getNroRaccomandata() {
		return this.nroRaccomandata;
	}

	public void setNroRaccomandata(String nroRaccomandata) {
		this.nroRaccomandata = nroRaccomandata;
	}

	@Column(name = "COSTO_SPED", precision = 11)
	public BigDecimal getCostoSped() {
		return this.costoSped;
	}

	public void setCostoSped(BigDecimal costoSped) {
		this.costoSped = costoSped;
	}

	@Column(name = "FLG_NOVIS_STAMPE", length = 1)
	public String getFlgNovisStampe() {
		return this.flgNovisStampe;
	}

	public void setFlgNovisStampe(String flgNovisStampe) {
		this.flgNovisStampe = flgNovisStampe;
	}

	@Column(name = "DES_ANAG", length = 150)
	public String getDesAnag() {
		return this.desAnag;
	}

	public void setDesAnag(String desAnag) {
		this.desAnag = desAnag;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PttNommodId))
			return false;
		PttNommodId castOther = (PttNommodId) other;

		return (this.getIdModello() == castOther.getIdModello())
				&& ((this.getCodEnte() == castOther.getCodEnte()) || (this
						.getCodEnte() != null && castOther.getCodEnte() != null && this
						.getCodEnte().equals(castOther.getCodEnte())))
				&& ((this.getIdAnag() == castOther.getIdAnag()) || (this
						.getIdAnag() != null && castOther.getIdAnag() != null && this
						.getIdAnag().equals(castOther.getIdAnag())))
				&& ((this.getFlgEsibDestContr() == castOther
						.getFlgEsibDestContr()) || (this.getFlgEsibDestContr() != null
						&& castOther.getFlgEsibDestContr() != null && this
						.getFlgEsibDestContr().equals(
								castOther.getFlgEsibDestContr())))
				&& ((this.getFlgDestCopia() == castOther.getFlgDestCopia()) || (this
						.getFlgDestCopia() != null
						&& castOther.getFlgDestCopia() != null && this
						.getFlgDestCopia().equals(castOther.getFlgDestCopia())))
				&& ((this.getFlgTpInd() == castOther.getFlgTpInd()) || (this
						.getFlgTpInd() != null
						&& castOther.getFlgTpInd() != null && this
						.getFlgTpInd().equals(castOther.getFlgTpInd())))
				&& ((this.getIdTopon() == castOther.getIdTopon()) || (this
						.getIdTopon() != null && castOther.getIdTopon() != null && this
						.getIdTopon().equals(castOther.getIdTopon())))
				&& ((this.getNumCiv() == castOther.getNumCiv()) || (this
						.getNumCiv() != null && castOther.getNumCiv() != null && this
						.getNumCiv().equals(castOther.getNumCiv())))
				&& ((this.getEspCiv() == castOther.getEspCiv()) || (this
						.getEspCiv() != null && castOther.getEspCiv() != null && this
						.getEspCiv().equals(castOther.getEspCiv())))
				&& ((this.getDesInd() == castOther.getDesInd()) || (this
						.getDesInd() != null && castOther.getDesInd() != null && this
						.getDesInd().equals(castOther.getDesInd())))
				&& ((this.getIdCom() == castOther.getIdCom()) || (this
						.getIdCom() != null && castOther.getIdCom() != null && this
						.getIdCom().equals(castOther.getIdCom())))
				&& ((this.getDesCom() == castOther.getDesCom()) || (this
						.getDesCom() != null && castOther.getDesCom() != null && this
						.getDesCom().equals(castOther.getDesCom())))
				&& ((this.getCap() == castOther.getCap()) || (this.getCap() != null
						&& castOther.getCap() != null && this.getCap().equals(
						castOther.getCap())))
				&& ((this.getDtIns() == castOther.getDtIns()) || (this
						.getDtIns() != null && castOther.getDtIns() != null && this
						.getDtIns().equals(castOther.getDtIns())))
				&& ((this.getUteIns() == castOther.getUteIns()) || (this
						.getUteIns() != null && castOther.getUteIns() != null && this
						.getUteIns().equals(castOther.getUteIns())))
				&& ((this.getDtUltMod() == castOther.getDtUltMod()) || (this
						.getDtUltMod() != null
						&& castOther.getDtUltMod() != null && this
						.getDtUltMod().equals(castOther.getDtUltMod())))
				&& ((this.getUteUltMod() == castOther.getUteUltMod()) || (this
						.getUteUltMod() != null
						&& castOther.getUteUltMod() != null && this
						.getUteUltMod().equals(castOther.getUteUltMod())))
				&& ((this.getNroOrdine() == castOther.getNroOrdine()) || (this
						.getNroOrdine() != null
						&& castOther.getNroOrdine() != null && this
						.getNroOrdine().equals(castOther.getNroOrdine())))
				&& ((this.getIdTpFis() == castOther.getIdTpFis()) || (this
						.getIdTpFis() != null && castOther.getIdTpFis() != null && this
						.getIdTpFis().equals(castOther.getIdTpFis())))
				&& ((this.getDtRaccomandata() == castOther.getDtRaccomandata()) || (this
						.getDtRaccomandata() != null
						&& castOther.getDtRaccomandata() != null && this
						.getDtRaccomandata().equals(
								castOther.getDtRaccomandata())))
				&& ((this.getNroRaccomandata() == castOther
						.getNroRaccomandata()) || (this.getNroRaccomandata() != null
						&& castOther.getNroRaccomandata() != null && this
						.getNroRaccomandata().equals(
								castOther.getNroRaccomandata())))
				&& ((this.getCostoSped() == castOther.getCostoSped()) || (this
						.getCostoSped() != null
						&& castOther.getCostoSped() != null && this
						.getCostoSped().equals(castOther.getCostoSped())))
				&& ((this.getFlgNovisStampe() == castOther.getFlgNovisStampe()) || (this
						.getFlgNovisStampe() != null
						&& castOther.getFlgNovisStampe() != null && this
						.getFlgNovisStampe().equals(
								castOther.getFlgNovisStampe())))
				&& ((this.getDesAnag() == castOther.getDesAnag()) || (this
						.getDesAnag() != null && castOther.getDesAnag() != null && this
						.getDesAnag().equals(castOther.getDesAnag())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdModello();
		result = 37 * result
				+ (getCodEnte() == null ? 0 : this.getCodEnte().hashCode());
		result = 37 * result
				+ (getIdAnag() == null ? 0 : this.getIdAnag().hashCode());
		result = 37
				* result
				+ (getFlgEsibDestContr() == null ? 0 : this
						.getFlgEsibDestContr().hashCode());
		result = 37
				* result
				+ (getFlgDestCopia() == null ? 0 : this.getFlgDestCopia()
						.hashCode());
		result = 37 * result
				+ (getFlgTpInd() == null ? 0 : this.getFlgTpInd().hashCode());
		result = 37 * result
				+ (getIdTopon() == null ? 0 : this.getIdTopon().hashCode());
		result = 37 * result
				+ (getNumCiv() == null ? 0 : this.getNumCiv().hashCode());
		result = 37 * result
				+ (getEspCiv() == null ? 0 : this.getEspCiv().hashCode());
		result = 37 * result
				+ (getDesInd() == null ? 0 : this.getDesInd().hashCode());
		result = 37 * result
				+ (getIdCom() == null ? 0 : this.getIdCom().hashCode());
		result = 37 * result
				+ (getDesCom() == null ? 0 : this.getDesCom().hashCode());
		result = 37 * result
				+ (getCap() == null ? 0 : this.getCap().hashCode());
		result = 37 * result
				+ (getDtIns() == null ? 0 : this.getDtIns().hashCode());
		result = 37 * result
				+ (getUteIns() == null ? 0 : this.getUteIns().hashCode());
		result = 37 * result
				+ (getDtUltMod() == null ? 0 : this.getDtUltMod().hashCode());
		result = 37 * result
				+ (getUteUltMod() == null ? 0 : this.getUteUltMod().hashCode());
		result = 37 * result
				+ (getNroOrdine() == null ? 0 : this.getNroOrdine().hashCode());
		result = 37 * result
				+ (getIdTpFis() == null ? 0 : this.getIdTpFis().hashCode());
		result = 37
				* result
				+ (getDtRaccomandata() == null ? 0 : this.getDtRaccomandata()
						.hashCode());
		result = 37
				* result
				+ (getNroRaccomandata() == null ? 0 : this.getNroRaccomandata()
						.hashCode());
		result = 37 * result
				+ (getCostoSped() == null ? 0 : this.getCostoSped().hashCode());
		result = 37
				* result
				+ (getFlgNovisStampe() == null ? 0 : this.getFlgNovisStampe()
						.hashCode());
		result = 37 * result
				+ (getDesAnag() == null ? 0 : this.getDesAnag().hashCode());
		return result;
	}

}
