/* * SPDX-License-Identifier: AGPL-3.0-or-later * * C Copyright 2023 Regione Piemonte * */

// Generated 22-set-2016 12.14.09 by Hibernate Tools 3.4.0.CR1

import java.sql.Clob;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PttOggAnagId generated by hbm2java
 */
@Embeddable
public class PttOggAnagId implements java.io.Serializable {

	private Integer idDoc;
	private Short numCopia;
	private Clob descrizione;
	private Integer idUoAssCc;

	public PttOggAnagId() {
	}

	public PttOggAnagId(Integer idDoc, Short numCopia, Clob descrizione,
			Integer idUoAssCc) {
		this.idDoc = idDoc;
		this.numCopia = numCopia;
		this.descrizione = descrizione;
		this.idUoAssCc = idUoAssCc;
	}

	@Column(name = "ID_DOC", precision = 8, scale = 0)
	public Integer getIdDoc() {
		return this.idDoc;
	}

	public void setIdDoc(Integer idDoc) {
		this.idDoc = idDoc;
	}

	@Column(name = "NUM_COPIA", precision = 4, scale = 0)
	public Short getNumCopia() {
		return this.numCopia;
	}

	public void setNumCopia(Short numCopia) {
		this.numCopia = numCopia;
	}

	@Column(name = "DESCRIZIONE")
	public Clob getDescrizione() {
		return this.descrizione;
	}

	public void setDescrizione(Clob descrizione) {
		this.descrizione = descrizione;
	}

	@Column(name = "ID_UO_ASS_CC", precision = 8, scale = 0)
	public Integer getIdUoAssCc() {
		return this.idUoAssCc;
	}

	public void setIdUoAssCc(Integer idUoAssCc) {
		this.idUoAssCc = idUoAssCc;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PttOggAnagId))
			return false;
		PttOggAnagId castOther = (PttOggAnagId) other;

		return ((this.getIdDoc() == castOther.getIdDoc()) || (this.getIdDoc() != null
				&& castOther.getIdDoc() != null && this.getIdDoc().equals(
				castOther.getIdDoc())))
				&& ((this.getNumCopia() == castOther.getNumCopia()) || (this
						.getNumCopia() != null
						&& castOther.getNumCopia() != null && this
						.getNumCopia().equals(castOther.getNumCopia())))
				&& ((this.getDescrizione() == castOther.getDescrizione()) || (this
						.getDescrizione() != null
						&& castOther.getDescrizione() != null && this
						.getDescrizione().equals(castOther.getDescrizione())))
				&& ((this.getIdUoAssCc() == castOther.getIdUoAssCc()) || (this
						.getIdUoAssCc() != null
						&& castOther.getIdUoAssCc() != null && this
						.getIdUoAssCc().equals(castOther.getIdUoAssCc())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getIdDoc() == null ? 0 : this.getIdDoc().hashCode());
		result = 37 * result
				+ (getNumCopia() == null ? 0 : this.getNumCopia().hashCode());
		result = 37
				* result
				+ (getDescrizione() == null ? 0 : this.getDescrizione()
						.hashCode());
		result = 37 * result
				+ (getIdUoAssCc() == null ? 0 : this.getIdUoAssCc().hashCode());
		return result;
	}

}
