/* * SPDX-License-Identifier: AGPL-3.0-or-later * * C Copyright 2023 Regione Piemonte * */

// Generated 22-set-2016 12.14.09 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * PttPossibiliImpostazioni generated by hbm2java
 */
@Entity
@Table(name = "PTT_POSSIBILI_IMPOSTAZIONI", uniqueConstraints = @UniqueConstraint(columnNames = {
		"TARGET", "DES_VALORE" }))
public class PttPossibiliImpostazioni implements java.io.Serializable {

	private PttPossibiliImpostazioniId id;
	private String desValore;
	private Boolean flgValDett;
	private Set<PttImpostazioniPostaz> pttImpostazioniPostazs = new HashSet<PttImpostazioniPostaz>(
			0);

	public PttPossibiliImpostazioni() {
	}

	public PttPossibiliImpostazioni(PttPossibiliImpostazioniId id,
			String desValore) {
		this.id = id;
		this.desValore = desValore;
	}

	public PttPossibiliImpostazioni(PttPossibiliImpostazioniId id,
			String desValore, Boolean flgValDett,
			Set<PttImpostazioniPostaz> pttImpostazioniPostazs) {
		this.id = id;
		this.desValore = desValore;
		this.flgValDett = flgValDett;
		this.pttImpostazioniPostazs = pttImpostazioniPostazs;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "target", column = @Column(name = "TARGET", nullable = false, length = 100)),
			@AttributeOverride(name = "codValore", column = @Column(name = "COD_VALORE", nullable = false, length = 30)) })
	public PttPossibiliImpostazioniId getId() {
		return this.id;
	}

	public void setId(PttPossibiliImpostazioniId id) {
		this.id = id;
	}

	@Column(name = "DES_VALORE", nullable = false, length = 150)
	public String getDesValore() {
		return this.desValore;
	}

	public void setDesValore(String desValore) {
		this.desValore = desValore;
	}

	@Column(name = "FLG_VAL_DETT", precision = 1, scale = 0)
	public Boolean getFlgValDett() {
		return this.flgValDett;
	}

	public void setFlgValDett(Boolean flgValDett) {
		this.flgValDett = flgValDett;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pttPossibiliImpostazioni")
	public Set<PttImpostazioniPostaz> getPttImpostazioniPostazs() {
		return this.pttImpostazioniPostazs;
	}

	public void setPttImpostazioniPostazs(
			Set<PttImpostazioniPostaz> pttImpostazioniPostazs) {
		this.pttImpostazioniPostazs = pttImpostazioniPostazs;
	}

}
