/* * SPDX-License-Identifier: AGPL-3.0-or-later * * C Copyright 2023 Regione Piemonte * */

// Generated 22-set-2016 12.14.09 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PttRepAssociati generated by hbm2java
 */
@Entity
@Table(name = "PTT_REP_ASSOCIATI")
public class PttRepAssociati implements java.io.Serializable {

	private PttRepAssociatiId id;
	private PttRepertori pttRepertori;
	private String tipologiaRepDef;
	private Date dtIns;
	private Integer uteIns;
	private Date dtUltMod;
	private Integer uteUltMod;

	public PttRepAssociati() {
	}

	public PttRepAssociati(PttRepAssociatiId id, PttRepertori pttRepertori) {
		this.id = id;
		this.pttRepertori = pttRepertori;
	}

	public PttRepAssociati(PttRepAssociatiId id, PttRepertori pttRepertori,
			String tipologiaRepDef, Date dtIns, Integer uteIns, Date dtUltMod,
			Integer uteUltMod) {
		this.id = id;
		this.pttRepertori = pttRepertori;
		this.tipologiaRepDef = tipologiaRepDef;
		this.dtIns = dtIns;
		this.uteIns = uteIns;
		this.dtUltMod = dtUltMod;
		this.uteUltMod = uteUltMod;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "tpRepProvv", column = @Column(name = "TP_REP_PROVV", nullable = false, length = 5)),
			@AttributeOverride(name = "tpRepDef", column = @Column(name = "TP_REP_DEF", nullable = false, length = 5)) })
	public PttRepAssociatiId getId() {
		return this.id;
	}

	public void setId(PttRepAssociatiId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "COD_ENTE", referencedColumnName = "COD_ENTE", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "TP_REP_PROVV", referencedColumnName = "TP_REPERTORIO", nullable = false, insertable = false, updatable = false) })
	public PttRepertori getPttRepertori() {
		return this.pttRepertori;
	}

	public void setPttRepertori(PttRepertori pttRepertori) {
		this.pttRepertori = pttRepertori;
	}

	@Column(name = "TIPOLOGIA_REP_DEF", length = 1)
	public String getTipologiaRepDef() {
		return this.tipologiaRepDef;
	}

	public void setTipologiaRepDef(String tipologiaRepDef) {
		this.tipologiaRepDef = tipologiaRepDef;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DT_INS", length = 7)
	public Date getDtIns() {
		return this.dtIns;
	}

	public void setDtIns(Date dtIns) {
		this.dtIns = dtIns;
	}

	@Column(name = "UTE_INS", precision = 6, scale = 0)
	public Integer getUteIns() {
		return this.uteIns;
	}

	public void setUteIns(Integer uteIns) {
		this.uteIns = uteIns;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DT_ULT_MOD", length = 7)
	public Date getDtUltMod() {
		return this.dtUltMod;
	}

	public void setDtUltMod(Date dtUltMod) {
		this.dtUltMod = dtUltMod;
	}

	@Column(name = "UTE_ULT_MOD", precision = 6, scale = 0)
	public Integer getUteUltMod() {
		return this.uteUltMod;
	}

	public void setUteUltMod(Integer uteUltMod) {
		this.uteUltMod = uteUltMod;
	}

}
