/* * SPDX-License-Identifier: AGPL-3.0-or-later * * C Copyright 2023 Regione Piemonte * */

// Generated 22-set-2016 12.14.09 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PttSyncDocVsAurigaId generated by hbm2java
 */
@Embeddable
public class PttSyncDocVsAurigaId implements java.io.Serializable {

	private BigDecimal idDocEgr;
	private BigDecimal numAllegEgr;
	private BigDecimal idUdAuriga;
	private BigDecimal idDocAuriga;
	private Boolean flgToSynchronize;
	private Date tsLastAggAuriga;
	private Date tsLastErr;
	private BigDecimal errCode;
	private String errMsg;
	private Boolean flgInLavorazione;

	public PttSyncDocVsAurigaId() {
	}

	public PttSyncDocVsAurigaId(BigDecimal idDocEgr, BigDecimal numAllegEgr,
			BigDecimal idUdAuriga, BigDecimal idDocAuriga,
			Boolean flgToSynchronize, Date tsLastAggAuriga, Date tsLastErr,
			BigDecimal errCode, String errMsg, Boolean flgInLavorazione) {
		this.idDocEgr = idDocEgr;
		this.numAllegEgr = numAllegEgr;
		this.idUdAuriga = idUdAuriga;
		this.idDocAuriga = idDocAuriga;
		this.flgToSynchronize = flgToSynchronize;
		this.tsLastAggAuriga = tsLastAggAuriga;
		this.tsLastErr = tsLastErr;
		this.errCode = errCode;
		this.errMsg = errMsg;
		this.flgInLavorazione = flgInLavorazione;
	}

	@Column(name = "ID_DOC_EGR", precision = 22, scale = 0)
	public BigDecimal getIdDocEgr() {
		return this.idDocEgr;
	}

	public void setIdDocEgr(BigDecimal idDocEgr) {
		this.idDocEgr = idDocEgr;
	}

	@Column(name = "NUM_ALLEG_EGR", precision = 22, scale = 0)
	public BigDecimal getNumAllegEgr() {
		return this.numAllegEgr;
	}

	public void setNumAllegEgr(BigDecimal numAllegEgr) {
		this.numAllegEgr = numAllegEgr;
	}

	@Column(name = "ID_UD_AURIGA", precision = 22, scale = 0)
	public BigDecimal getIdUdAuriga() {
		return this.idUdAuriga;
	}

	public void setIdUdAuriga(BigDecimal idUdAuriga) {
		this.idUdAuriga = idUdAuriga;
	}

	@Column(name = "ID_DOC_AURIGA", precision = 22, scale = 0)
	public BigDecimal getIdDocAuriga() {
		return this.idDocAuriga;
	}

	public void setIdDocAuriga(BigDecimal idDocAuriga) {
		this.idDocAuriga = idDocAuriga;
	}

	@Column(name = "FLG_TO_SYNCHRONIZE", precision = 1, scale = 0)
	public Boolean getFlgToSynchronize() {
		return this.flgToSynchronize;
	}

	public void setFlgToSynchronize(Boolean flgToSynchronize) {
		this.flgToSynchronize = flgToSynchronize;
	}

	@Column(name = "TS_LAST_AGG_AURIGA", length = 7)
	public Date getTsLastAggAuriga() {
		return this.tsLastAggAuriga;
	}

	public void setTsLastAggAuriga(Date tsLastAggAuriga) {
		this.tsLastAggAuriga = tsLastAggAuriga;
	}

	@Column(name = "TS_LAST_ERR", length = 7)
	public Date getTsLastErr() {
		return this.tsLastErr;
	}

	public void setTsLastErr(Date tsLastErr) {
		this.tsLastErr = tsLastErr;
	}

	@Column(name = "ERR_CODE", precision = 22, scale = 0)
	public BigDecimal getErrCode() {
		return this.errCode;
	}

	public void setErrCode(BigDecimal errCode) {
		this.errCode = errCode;
	}

	@Column(name = "ERR_MSG", length = 4000)
	public String getErrMsg() {
		return this.errMsg;
	}

	public void setErrMsg(String errMsg) {
		this.errMsg = errMsg;
	}

	@Column(name = "FLG_IN_LAVORAZIONE", precision = 1, scale = 0)
	public Boolean getFlgInLavorazione() {
		return this.flgInLavorazione;
	}

	public void setFlgInLavorazione(Boolean flgInLavorazione) {
		this.flgInLavorazione = flgInLavorazione;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PttSyncDocVsAurigaId))
			return false;
		PttSyncDocVsAurigaId castOther = (PttSyncDocVsAurigaId) other;

		return ((this.getIdDocEgr() == castOther.getIdDocEgr()) || (this
				.getIdDocEgr() != null && castOther.getIdDocEgr() != null && this
				.getIdDocEgr().equals(castOther.getIdDocEgr())))
				&& ((this.getNumAllegEgr() == castOther.getNumAllegEgr()) || (this
						.getNumAllegEgr() != null
						&& castOther.getNumAllegEgr() != null && this
						.getNumAllegEgr().equals(castOther.getNumAllegEgr())))
				&& ((this.getIdUdAuriga() == castOther.getIdUdAuriga()) || (this
						.getIdUdAuriga() != null
						&& castOther.getIdUdAuriga() != null && this
						.getIdUdAuriga().equals(castOther.getIdUdAuriga())))
				&& ((this.getIdDocAuriga() == castOther.getIdDocAuriga()) || (this
						.getIdDocAuriga() != null
						&& castOther.getIdDocAuriga() != null && this
						.getIdDocAuriga().equals(castOther.getIdDocAuriga())))
				&& ((this.getFlgToSynchronize() == castOther
						.getFlgToSynchronize()) || (this.getFlgToSynchronize() != null
						&& castOther.getFlgToSynchronize() != null && this
						.getFlgToSynchronize().equals(
								castOther.getFlgToSynchronize())))
				&& ((this.getTsLastAggAuriga() == castOther
						.getTsLastAggAuriga()) || (this.getTsLastAggAuriga() != null
						&& castOther.getTsLastAggAuriga() != null && this
						.getTsLastAggAuriga().equals(
								castOther.getTsLastAggAuriga())))
				&& ((this.getTsLastErr() == castOther.getTsLastErr()) || (this
						.getTsLastErr() != null
						&& castOther.getTsLastErr() != null && this
						.getTsLastErr().equals(castOther.getTsLastErr())))
				&& ((this.getErrCode() == castOther.getErrCode()) || (this
						.getErrCode() != null && castOther.getErrCode() != null && this
						.getErrCode().equals(castOther.getErrCode())))
				&& ((this.getErrMsg() == castOther.getErrMsg()) || (this
						.getErrMsg() != null && castOther.getErrMsg() != null && this
						.getErrMsg().equals(castOther.getErrMsg())))
				&& ((this.getFlgInLavorazione() == castOther
						.getFlgInLavorazione()) || (this.getFlgInLavorazione() != null
						&& castOther.getFlgInLavorazione() != null && this
						.getFlgInLavorazione().equals(
								castOther.getFlgInLavorazione())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getIdDocEgr() == null ? 0 : this.getIdDocEgr().hashCode());
		result = 37
				* result
				+ (getNumAllegEgr() == null ? 0 : this.getNumAllegEgr()
						.hashCode());
		result = 37
				* result
				+ (getIdUdAuriga() == null ? 0 : this.getIdUdAuriga()
						.hashCode());
		result = 37
				* result
				+ (getIdDocAuriga() == null ? 0 : this.getIdDocAuriga()
						.hashCode());
		result = 37
				* result
				+ (getFlgToSynchronize() == null ? 0 : this
						.getFlgToSynchronize().hashCode());
		result = 37
				* result
				+ (getTsLastAggAuriga() == null ? 0 : this.getTsLastAggAuriga()
						.hashCode());
		result = 37 * result
				+ (getTsLastErr() == null ? 0 : this.getTsLastErr().hashCode());
		result = 37 * result
				+ (getErrCode() == null ? 0 : this.getErrCode().hashCode());
		result = 37 * result
				+ (getErrMsg() == null ? 0 : this.getErrMsg().hashCode());
		result = 37
				* result
				+ (getFlgInLavorazione() == null ? 0 : this
						.getFlgInLavorazione().hashCode());
		return result;
	}

}
