/* * SPDX-License-Identifier: AGPL-3.0-or-later * * C Copyright 2023 Regione Piemonte * */

// Generated 22-set-2016 12.14.09 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PttSyncFascVsAurigaId generated by hbm2java
 */
@Embeddable
public class PttSyncFascVsAurigaId implements java.io.Serializable {

	private BigDecimal idFascEgr;
	private BigDecimal numSfEgr;
	private BigDecimal idFolderAuriga;
	private Boolean flgToSynchronize;
	private Date tsLastAggAuriga;
	private Date tsLastErr;
	private BigDecimal errCode;
	private String errMsg;
	private Boolean flgInLavorazione;

	public PttSyncFascVsAurigaId() {
	}

	public PttSyncFascVsAurigaId(BigDecimal idFascEgr, BigDecimal numSfEgr,
			BigDecimal idFolderAuriga, Boolean flgToSynchronize,
			Date tsLastAggAuriga, Date tsLastErr, BigDecimal errCode,
			String errMsg, Boolean flgInLavorazione) {
		this.idFascEgr = idFascEgr;
		this.numSfEgr = numSfEgr;
		this.idFolderAuriga = idFolderAuriga;
		this.flgToSynchronize = flgToSynchronize;
		this.tsLastAggAuriga = tsLastAggAuriga;
		this.tsLastErr = tsLastErr;
		this.errCode = errCode;
		this.errMsg = errMsg;
		this.flgInLavorazione = flgInLavorazione;
	}

	@Column(name = "ID_FASC_EGR", precision = 22, scale = 0)
	public BigDecimal getIdFascEgr() {
		return this.idFascEgr;
	}

	public void setIdFascEgr(BigDecimal idFascEgr) {
		this.idFascEgr = idFascEgr;
	}

	@Column(name = "NUM_SF_EGR", precision = 22, scale = 0)
	public BigDecimal getNumSfEgr() {
		return this.numSfEgr;
	}

	public void setNumSfEgr(BigDecimal numSfEgr) {
		this.numSfEgr = numSfEgr;
	}

	@Column(name = "ID_FOLDER_AURIGA", precision = 22, scale = 0)
	public BigDecimal getIdFolderAuriga() {
		return this.idFolderAuriga;
	}

	public void setIdFolderAuriga(BigDecimal idFolderAuriga) {
		this.idFolderAuriga = idFolderAuriga;
	}

	@Column(name = "FLG_TO_SYNCHRONIZE", precision = 1, scale = 0)
	public Boolean getFlgToSynchronize() {
		return this.flgToSynchronize;
	}

	public void setFlgToSynchronize(Boolean flgToSynchronize) {
		this.flgToSynchronize = flgToSynchronize;
	}

	@Column(name = "TS_LAST_AGG_AURIGA", length = 7)
	public Date getTsLastAggAuriga() {
		return this.tsLastAggAuriga;
	}

	public void setTsLastAggAuriga(Date tsLastAggAuriga) {
		this.tsLastAggAuriga = tsLastAggAuriga;
	}

	@Column(name = "TS_LAST_ERR", length = 7)
	public Date getTsLastErr() {
		return this.tsLastErr;
	}

	public void setTsLastErr(Date tsLastErr) {
		this.tsLastErr = tsLastErr;
	}

	@Column(name = "ERR_CODE", precision = 22, scale = 0)
	public BigDecimal getErrCode() {
		return this.errCode;
	}

	public void setErrCode(BigDecimal errCode) {
		this.errCode = errCode;
	}

	@Column(name = "ERR_MSG", length = 4000)
	public String getErrMsg() {
		return this.errMsg;
	}

	public void setErrMsg(String errMsg) {
		this.errMsg = errMsg;
	}

	@Column(name = "FLG_IN_LAVORAZIONE", precision = 1, scale = 0)
	public Boolean getFlgInLavorazione() {
		return this.flgInLavorazione;
	}

	public void setFlgInLavorazione(Boolean flgInLavorazione) {
		this.flgInLavorazione = flgInLavorazione;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PttSyncFascVsAurigaId))
			return false;
		PttSyncFascVsAurigaId castOther = (PttSyncFascVsAurigaId) other;

		return ((this.getIdFascEgr() == castOther.getIdFascEgr()) || (this
				.getIdFascEgr() != null && castOther.getIdFascEgr() != null && this
				.getIdFascEgr().equals(castOther.getIdFascEgr())))
				&& ((this.getNumSfEgr() == castOther.getNumSfEgr()) || (this
						.getNumSfEgr() != null
						&& castOther.getNumSfEgr() != null && this
						.getNumSfEgr().equals(castOther.getNumSfEgr())))
				&& ((this.getIdFolderAuriga() == castOther.getIdFolderAuriga()) || (this
						.getIdFolderAuriga() != null
						&& castOther.getIdFolderAuriga() != null && this
						.getIdFolderAuriga().equals(
								castOther.getIdFolderAuriga())))
				&& ((this.getFlgToSynchronize() == castOther
						.getFlgToSynchronize()) || (this.getFlgToSynchronize() != null
						&& castOther.getFlgToSynchronize() != null && this
						.getFlgToSynchronize().equals(
								castOther.getFlgToSynchronize())))
				&& ((this.getTsLastAggAuriga() == castOther
						.getTsLastAggAuriga()) || (this.getTsLastAggAuriga() != null
						&& castOther.getTsLastAggAuriga() != null && this
						.getTsLastAggAuriga().equals(
								castOther.getTsLastAggAuriga())))
				&& ((this.getTsLastErr() == castOther.getTsLastErr()) || (this
						.getTsLastErr() != null
						&& castOther.getTsLastErr() != null && this
						.getTsLastErr().equals(castOther.getTsLastErr())))
				&& ((this.getErrCode() == castOther.getErrCode()) || (this
						.getErrCode() != null && castOther.getErrCode() != null && this
						.getErrCode().equals(castOther.getErrCode())))
				&& ((this.getErrMsg() == castOther.getErrMsg()) || (this
						.getErrMsg() != null && castOther.getErrMsg() != null && this
						.getErrMsg().equals(castOther.getErrMsg())))
				&& ((this.getFlgInLavorazione() == castOther
						.getFlgInLavorazione()) || (this.getFlgInLavorazione() != null
						&& castOther.getFlgInLavorazione() != null && this
						.getFlgInLavorazione().equals(
								castOther.getFlgInLavorazione())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getIdFascEgr() == null ? 0 : this.getIdFascEgr().hashCode());
		result = 37 * result
				+ (getNumSfEgr() == null ? 0 : this.getNumSfEgr().hashCode());
		result = 37
				* result
				+ (getIdFolderAuriga() == null ? 0 : this.getIdFolderAuriga()
						.hashCode());
		result = 37
				* result
				+ (getFlgToSynchronize() == null ? 0 : this
						.getFlgToSynchronize().hashCode());
		result = 37
				* result
				+ (getTsLastAggAuriga() == null ? 0 : this.getTsLastAggAuriga()
						.hashCode());
		result = 37 * result
				+ (getTsLastErr() == null ? 0 : this.getTsLastErr().hashCode());
		result = 37 * result
				+ (getErrCode() == null ? 0 : this.getErrCode().hashCode());
		result = 37 * result
				+ (getErrMsg() == null ? 0 : this.getErrMsg().hashCode());
		result = 37
				* result
				+ (getFlgInLavorazione() == null ? 0 : this
						.getFlgInLavorazione().hashCode());
		return result;
	}

}
