/* * SPDX-License-Identifier: AGPL-3.0-or-later * * C Copyright 2023 Regione Piemonte * */

// Generated 22-set-2016 12.14.09 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PttTpDoc generated by hbm2java
 */
@Entity
@Table(name = "PTT_TP_DOC")
public class PttTpDoc implements java.io.Serializable {

	private int idTpDoc;
	private String desTpDoc;
	private Date dtIns;
	private Integer uteIns;
	private Date dtUltMod;
	private Integer uteUltMod;
	private String flgConservPerm;
	private Short anniMinConserv;
	private Set<PttIndici> pttIndicis = new HashSet<PttIndici>(0);
	private Set<PttCopie> pttCopies = new HashSet<PttCopie>(0);

	public PttTpDoc() {
	}

	public PttTpDoc(int idTpDoc, String desTpDoc) {
		this.idTpDoc = idTpDoc;
		this.desTpDoc = desTpDoc;
	}

	public PttTpDoc(int idTpDoc, String desTpDoc, Date dtIns, Integer uteIns,
			Date dtUltMod, Integer uteUltMod, String flgConservPerm,
			Short anniMinConserv, Set<PttIndici> pttIndicis,
			Set<PttCopie> pttCopies) {
		this.idTpDoc = idTpDoc;
		this.desTpDoc = desTpDoc;
		this.dtIns = dtIns;
		this.uteIns = uteIns;
		this.dtUltMod = dtUltMod;
		this.uteUltMod = uteUltMod;
		this.flgConservPerm = flgConservPerm;
		this.anniMinConserv = anniMinConserv;
		this.pttIndicis = pttIndicis;
		this.pttCopies = pttCopies;
	}

	@Id
	@Column(name = "ID_TP_DOC", unique = true, nullable = false, precision = 5, scale = 0)
	public int getIdTpDoc() {
		return this.idTpDoc;
	}

	public void setIdTpDoc(int idTpDoc) {
		this.idTpDoc = idTpDoc;
	}

	@Column(name = "DES_TP_DOC", nullable = false, length = 250)
	public String getDesTpDoc() {
		return this.desTpDoc;
	}

	public void setDesTpDoc(String desTpDoc) {
		this.desTpDoc = desTpDoc;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DT_INS", length = 7)
	public Date getDtIns() {
		return this.dtIns;
	}

	public void setDtIns(Date dtIns) {
		this.dtIns = dtIns;
	}

	@Column(name = "UTE_INS", precision = 6, scale = 0)
	public Integer getUteIns() {
		return this.uteIns;
	}

	public void setUteIns(Integer uteIns) {
		this.uteIns = uteIns;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DT_ULT_MOD", length = 7)
	public Date getDtUltMod() {
		return this.dtUltMod;
	}

	public void setDtUltMod(Date dtUltMod) {
		this.dtUltMod = dtUltMod;
	}

	@Column(name = "UTE_ULT_MOD", precision = 6, scale = 0)
	public Integer getUteUltMod() {
		return this.uteUltMod;
	}

	public void setUteUltMod(Integer uteUltMod) {
		this.uteUltMod = uteUltMod;
	}

	@Column(name = "FLG_CONSERV_PERM", length = 1)
	public String getFlgConservPerm() {
		return this.flgConservPerm;
	}

	public void setFlgConservPerm(String flgConservPerm) {
		this.flgConservPerm = flgConservPerm;
	}

	@Column(name = "ANNI_MIN_CONSERV", precision = 3, scale = 0)
	public Short getAnniMinConserv() {
		return this.anniMinConserv;
	}

	public void setAnniMinConserv(Short anniMinConserv) {
		this.anniMinConserv = anniMinConserv;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pttTpDoc")
	public Set<PttIndici> getPttIndicis() {
		return this.pttIndicis;
	}

	public void setPttIndicis(Set<PttIndici> pttIndicis) {
		this.pttIndicis = pttIndicis;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pttTpDoc")
	public Set<PttCopie> getPttCopies() {
		return this.pttCopies;
	}

	public void setPttCopies(Set<PttCopie> pttCopies) {
		this.pttCopies = pttCopies;
	}

}
