/* * SPDX-License-Identifier: AGPL-3.0-or-later * * C Copyright 2023 Regione Piemonte * */

// Generated 22-set-2016 12.14.09 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * PttTmpRicECamDest generated by hbm2java
 */
@Entity
@Table(name = "PTT_TMP_RIC_E_CAM_DEST")
public class PttTmpRicECamDest implements java.io.Serializable {

	private PttTmpRicECamDestId id;
	private String flgIntEst;
	private String desDest;
	private String flgPc;
	private String desTipoDest;
	private String idAnag;

	public PttTmpRicECamDest() {
	}

	public PttTmpRicECamDest(PttTmpRicECamDestId id) {
		this.id = id;
	}

	public PttTmpRicECamDest(PttTmpRicECamDestId id, String flgIntEst,
			String desDest, String flgPc, String desTipoDest, String idAnag) {
		this.id = id;
		this.flgIntEst = flgIntEst;
		this.desDest = desDest;
		this.flgPc = flgPc;
		this.desTipoDest = desTipoDest;
		this.idAnag = idAnag;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "idEstrazione", column = @Column(name = "ID_ESTRAZIONE", nullable = false, length = 16)),
			@AttributeOverride(name = "prog", column = @Column(name = "PROG", nullable = false, precision = 22, scale = 0)) })
	public PttTmpRicECamDestId getId() {
		return this.id;
	}

	public void setId(PttTmpRicECamDestId id) {
		this.id = id;
	}

	@Column(name = "FLG_INT_EST", length = 1)
	public String getFlgIntEst() {
		return this.flgIntEst;
	}

	public void setFlgIntEst(String flgIntEst) {
		this.flgIntEst = flgIntEst;
	}

	@Column(name = "DES_DEST", length = 200)
	public String getDesDest() {
		return this.desDest;
	}

	public void setDesDest(String desDest) {
		this.desDest = desDest;
	}

	@Column(name = "FLG_PC", length = 1)
	public String getFlgPc() {
		return this.flgPc;
	}

	public void setFlgPc(String flgPc) {
		this.flgPc = flgPc;
	}

	@Column(name = "DES_TIPO_DEST", length = 1000)
	public String getDesTipoDest() {
		return this.desTipoDest;
	}

	public void setDesTipoDest(String desTipoDest) {
		this.desTipoDest = desTipoDest;
	}

	@Column(name = "ID_ANAG", length = 10)
	public String getIdAnag() {
		return this.idAnag;
	}

	public void setIdAnag(String idAnag) {
		this.idAnag = idAnag;
	}

}
