/* * SPDX-License-Identifier: AGPL-3.0-or-later * * C Copyright 2023 Regione Piemonte * */

// Generated 22-set-2016 12.14.09 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PttTmpUoXCsv generated by hbm2java
 */
@Entity
@Table(name = "PTT_TMP_UO_X_CSV")
public class PttTmpUoXCsv implements java.io.Serializable {

	private PttTmpUoXCsvId id;
	private Integer idUo;
	private Integer settore;
	private Integer servizio;
	private Integer uoc;
	private Integer uos;
	private Integer postazione;
	private String desUo;
	private Integer idUte;
	private Date dtInizioVld;
	private Date dtFineVld;
	private String email;
	private Integer settoreEff;
	private Integer servizioEff;
	private Integer uocEff;
	private Integer uosEff;
	private Integer postazioneEff;
	private String tpRegEm;
	private Integer numRegEm;
	private Short annoRegEm;
	private String codAppEst;

	public PttTmpUoXCsv() {
	}

	public PttTmpUoXCsv(PttTmpUoXCsvId id) {
		this.id = id;
	}

	public PttTmpUoXCsv(PttTmpUoXCsvId id, Integer idUo, Integer settore,
			Integer servizio, Integer uoc, Integer uos, Integer postazione,
			String desUo, Integer idUte, Date dtInizioVld, Date dtFineVld,
			String email, Integer settoreEff, Integer servizioEff,
			Integer uocEff, Integer uosEff, Integer postazioneEff,
			String tpRegEm, Integer numRegEm, Short annoRegEm, String codAppEst) {
		this.id = id;
		this.idUo = idUo;
		this.settore = settore;
		this.servizio = servizio;
		this.uoc = uoc;
		this.uos = uos;
		this.postazione = postazione;
		this.desUo = desUo;
		this.idUte = idUte;
		this.dtInizioVld = dtInizioVld;
		this.dtFineVld = dtFineVld;
		this.email = email;
		this.settoreEff = settoreEff;
		this.servizioEff = servizioEff;
		this.uocEff = uocEff;
		this.uosEff = uosEff;
		this.postazioneEff = postazioneEff;
		this.tpRegEm = tpRegEm;
		this.numRegEm = numRegEm;
		this.annoRegEm = annoRegEm;
		this.codAppEst = codAppEst;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "idEstrazione", column = @Column(name = "ID_ESTRAZIONE", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "progr", column = @Column(name = "PROGR", nullable = false, precision = 22, scale = 0)) })
	public PttTmpUoXCsvId getId() {
		return this.id;
	}

	public void setId(PttTmpUoXCsvId id) {
		this.id = id;
	}

	@Column(name = "ID_UO", precision = 8, scale = 0)
	public Integer getIdUo() {
		return this.idUo;
	}

	public void setIdUo(Integer idUo) {
		this.idUo = idUo;
	}

	@Column(name = "SETTORE", precision = 5, scale = 0)
	public Integer getSettore() {
		return this.settore;
	}

	public void setSettore(Integer settore) {
		this.settore = settore;
	}

	@Column(name = "SERVIZIO", precision = 5, scale = 0)
	public Integer getServizio() {
		return this.servizio;
	}

	public void setServizio(Integer servizio) {
		this.servizio = servizio;
	}

	@Column(name = "UOC", precision = 5, scale = 0)
	public Integer getUoc() {
		return this.uoc;
	}

	public void setUoc(Integer uoc) {
		this.uoc = uoc;
	}

	@Column(name = "UOS", precision = 5, scale = 0)
	public Integer getUos() {
		return this.uos;
	}

	public void setUos(Integer uos) {
		this.uos = uos;
	}

	@Column(name = "POSTAZIONE", precision = 5, scale = 0)
	public Integer getPostazione() {
		return this.postazione;
	}

	public void setPostazione(Integer postazione) {
		this.postazione = postazione;
	}

	@Column(name = "DES_UO", length = 75)
	public String getDesUo() {
		return this.desUo;
	}

	public void setDesUo(String desUo) {
		this.desUo = desUo;
	}

	@Column(name = "ID_UTE", precision = 6, scale = 0)
	public Integer getIdUte() {
		return this.idUte;
	}

	public void setIdUte(Integer idUte) {
		this.idUte = idUte;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DT_INIZIO_VLD", length = 7)
	public Date getDtInizioVld() {
		return this.dtInizioVld;
	}

	public void setDtInizioVld(Date dtInizioVld) {
		this.dtInizioVld = dtInizioVld;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DT_FINE_VLD", length = 7)
	public Date getDtFineVld() {
		return this.dtFineVld;
	}

	public void setDtFineVld(Date dtFineVld) {
		this.dtFineVld = dtFineVld;
	}

	@Column(name = "EMAIL", length = 400)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "SETTORE_EFF", precision = 5, scale = 0)
	public Integer getSettoreEff() {
		return this.settoreEff;
	}

	public void setSettoreEff(Integer settoreEff) {
		this.settoreEff = settoreEff;
	}

	@Column(name = "SERVIZIO_EFF", precision = 5, scale = 0)
	public Integer getServizioEff() {
		return this.servizioEff;
	}

	public void setServizioEff(Integer servizioEff) {
		this.servizioEff = servizioEff;
	}

	@Column(name = "UOC_EFF", precision = 5, scale = 0)
	public Integer getUocEff() {
		return this.uocEff;
	}

	public void setUocEff(Integer uocEff) {
		this.uocEff = uocEff;
	}

	@Column(name = "UOS_EFF", precision = 5, scale = 0)
	public Integer getUosEff() {
		return this.uosEff;
	}

	public void setUosEff(Integer uosEff) {
		this.uosEff = uosEff;
	}

	@Column(name = "POSTAZIONE_EFF", precision = 5, scale = 0)
	public Integer getPostazioneEff() {
		return this.postazioneEff;
	}

	public void setPostazioneEff(Integer postazioneEff) {
		this.postazioneEff = postazioneEff;
	}

	@Column(name = "TP_REG_EM", length = 5)
	public String getTpRegEm() {
		return this.tpRegEm;
	}

	public void setTpRegEm(String tpRegEm) {
		this.tpRegEm = tpRegEm;
	}

	@Column(name = "NUM_REG_EM", precision = 8, scale = 0)
	public Integer getNumRegEm() {
		return this.numRegEm;
	}

	public void setNumRegEm(Integer numRegEm) {
		this.numRegEm = numRegEm;
	}

	@Column(name = "ANNO_REG_EM", precision = 4, scale = 0)
	public Short getAnnoRegEm() {
		return this.annoRegEm;
	}

	public void setAnnoRegEm(Short annoRegEm) {
		this.annoRegEm = annoRegEm;
	}

	@Column(name = "COD_APP_EST", length = 50)
	public String getCodAppEst() {
		return this.codAppEst;
	}

	public void setCodAppEst(String codAppEst) {
		this.codAppEst = codAppEst;
	}

}
