/* * SPDX-License-Identifier: AGPL-3.0-or-later * * C Copyright 2023 Regione Piemonte * */

// Generated 22-set-2016 12.14.09 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * PttTitolazioni generated by hbm2java
 */
@Entity
@Table(name = "PTT_TITOLAZIONI", uniqueConstraints = @UniqueConstraint(columnNames = {
		"TITOLO", "CLASSE", "SOTTOCLASSE", "LIVELLO4", "LIVELLO5",
		"DT_INIZIO_VLD" }))
public class PttTitolazioni implements java.io.Serializable {

	private BigDecimal idTitolazione;
	private short titolo;
	private short classe;
	private short sottoclasse;
	private String desTitolazione;
	private Date dtInizioVld;
	private Date dtFineVld;
	private Date dtIns;
	private Integer uteIns;
	private Date dtUltMod;
	private Integer uteUltMod;
	private short livello4;
	private short livello5;
	private String paroleChiave;
	private String flgClassifParz;
	private Set<PttDefAttributiOpz> pttDefAttributiOpzs = new HashSet<PttDefAttributiOpz>(
			0);
	private Set<PttIndici> pttIndicis = new HashSet<PttIndici>(0);
	private Set<PttFascicoli> pttFascicolis = new HashSet<PttFascicoli>(0);
	private Set<PttTitIndAmm> pttTitIndAmms = new HashSet<PttTitIndAmm>(0);
	private PttIdFasc pttIdFasc;

	public PttTitolazioni() {
	}

	public PttTitolazioni(BigDecimal idTitolazione, short titolo, short classe,
			short sottoclasse, String desTitolazione, Date dtInizioVld,
			short livello4, short livello5) {
		this.idTitolazione = idTitolazione;
		this.titolo = titolo;
		this.classe = classe;
		this.sottoclasse = sottoclasse;
		this.desTitolazione = desTitolazione;
		this.dtInizioVld = dtInizioVld;
		this.livello4 = livello4;
		this.livello5 = livello5;
	}

	public PttTitolazioni(BigDecimal idTitolazione, short titolo, short classe,
			short sottoclasse, String desTitolazione, Date dtInizioVld,
			Date dtFineVld, Date dtIns, Integer uteIns, Date dtUltMod,
			Integer uteUltMod, short livello4, short livello5,
			String paroleChiave, String flgClassifParz,
			Set<PttDefAttributiOpz> pttDefAttributiOpzs,
			Set<PttIndici> pttIndicis, Set<PttFascicoli> pttFascicolis,
			Set<PttTitIndAmm> pttTitIndAmms, PttIdFasc pttIdFasc) {
		this.idTitolazione = idTitolazione;
		this.titolo = titolo;
		this.classe = classe;
		this.sottoclasse = sottoclasse;
		this.desTitolazione = desTitolazione;
		this.dtInizioVld = dtInizioVld;
		this.dtFineVld = dtFineVld;
		this.dtIns = dtIns;
		this.uteIns = uteIns;
		this.dtUltMod = dtUltMod;
		this.uteUltMod = uteUltMod;
		this.livello4 = livello4;
		this.livello5 = livello5;
		this.paroleChiave = paroleChiave;
		this.flgClassifParz = flgClassifParz;
		this.pttDefAttributiOpzs = pttDefAttributiOpzs;
		this.pttIndicis = pttIndicis;
		this.pttFascicolis = pttFascicolis;
		this.pttTitIndAmms = pttTitIndAmms;
		this.pttIdFasc = pttIdFasc;
	}

	@Id
	@Column(name = "ID_TITOLAZIONE", unique = true, nullable = false, precision = 25, scale = 0)
	public BigDecimal getIdTitolazione() {
		return this.idTitolazione;
	}

	public void setIdTitolazione(BigDecimal idTitolazione) {
		this.idTitolazione = idTitolazione;
	}

	@Column(name = "TITOLO", nullable = false, precision = 3, scale = 0)
	public short getTitolo() {
		return this.titolo;
	}

	public void setTitolo(short titolo) {
		this.titolo = titolo;
	}

	@Column(name = "CLASSE", nullable = false, precision = 3, scale = 0)
	public short getClasse() {
		return this.classe;
	}

	public void setClasse(short classe) {
		this.classe = classe;
	}

	@Column(name = "SOTTOCLASSE", nullable = false, precision = 3, scale = 0)
	public short getSottoclasse() {
		return this.sottoclasse;
	}

	public void setSottoclasse(short sottoclasse) {
		this.sottoclasse = sottoclasse;
	}

	@Column(name = "DES_TITOLAZIONE", nullable = false, length = 250)
	public String getDesTitolazione() {
		return this.desTitolazione;
	}

	public void setDesTitolazione(String desTitolazione) {
		this.desTitolazione = desTitolazione;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DT_INIZIO_VLD", nullable = false, length = 7)
	public Date getDtInizioVld() {
		return this.dtInizioVld;
	}

	public void setDtInizioVld(Date dtInizioVld) {
		this.dtInizioVld = dtInizioVld;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DT_FINE_VLD", length = 7)
	public Date getDtFineVld() {
		return this.dtFineVld;
	}

	public void setDtFineVld(Date dtFineVld) {
		this.dtFineVld = dtFineVld;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DT_INS", length = 7)
	public Date getDtIns() {
		return this.dtIns;
	}

	public void setDtIns(Date dtIns) {
		this.dtIns = dtIns;
	}

	@Column(name = "UTE_INS", precision = 6, scale = 0)
	public Integer getUteIns() {
		return this.uteIns;
	}

	public void setUteIns(Integer uteIns) {
		this.uteIns = uteIns;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DT_ULT_MOD", length = 7)
	public Date getDtUltMod() {
		return this.dtUltMod;
	}

	public void setDtUltMod(Date dtUltMod) {
		this.dtUltMod = dtUltMod;
	}

	@Column(name = "UTE_ULT_MOD", precision = 6, scale = 0)
	public Integer getUteUltMod() {
		return this.uteUltMod;
	}

	public void setUteUltMod(Integer uteUltMod) {
		this.uteUltMod = uteUltMod;
	}

	@Column(name = "LIVELLO4", nullable = false, precision = 3, scale = 0)
	public short getLivello4() {
		return this.livello4;
	}

	public void setLivello4(short livello4) {
		this.livello4 = livello4;
	}

	@Column(name = "LIVELLO5", nullable = false, precision = 3, scale = 0)
	public short getLivello5() {
		return this.livello5;
	}

	public void setLivello5(short livello5) {
		this.livello5 = livello5;
	}

	@Column(name = "PAROLE_CHIAVE", length = 1000)
	public String getParoleChiave() {
		return this.paroleChiave;
	}

	public void setParoleChiave(String paroleChiave) {
		this.paroleChiave = paroleChiave;
	}

	@Column(name = "FLG_CLASSIF_PARZ", length = 1)
	public String getFlgClassifParz() {
		return this.flgClassifParz;
	}

	public void setFlgClassifParz(String flgClassifParz) {
		this.flgClassifParz = flgClassifParz;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pttTitolazioni")
	public Set<PttDefAttributiOpz> getPttDefAttributiOpzs() {
		return this.pttDefAttributiOpzs;
	}

	public void setPttDefAttributiOpzs(
			Set<PttDefAttributiOpz> pttDefAttributiOpzs) {
		this.pttDefAttributiOpzs = pttDefAttributiOpzs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pttTitolazioni")
	public Set<PttIndici> getPttIndicis() {
		return this.pttIndicis;
	}

	public void setPttIndicis(Set<PttIndici> pttIndicis) {
		this.pttIndicis = pttIndicis;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pttTitolazioni")
	public Set<PttFascicoli> getPttFascicolis() {
		return this.pttFascicolis;
	}

	public void setPttFascicolis(Set<PttFascicoli> pttFascicolis) {
		this.pttFascicolis = pttFascicolis;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pttTitolazioni")
	public Set<PttTitIndAmm> getPttTitIndAmms() {
		return this.pttTitIndAmms;
	}

	public void setPttTitIndAmms(Set<PttTitIndAmm> pttTitIndAmms) {
		this.pttTitIndAmms = pttTitIndAmms;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "pttTitolazioni")
	public PttIdFasc getPttIdFasc() {
		return this.pttIdFasc;
	}

	public void setPttIdFasc(PttIdFasc pttIdFasc) {
		this.pttIdFasc = pttIdFasc;
	}

}
