/* * SPDX-License-Identifier: AGPL-3.0-or-later * * C Copyright 2023 Regione Piemonte * */

// Generated 22-set-2016 12.14.09 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PttTmpUtentiXCsv generated by hbm2java
 */
@Entity
@Table(name = "PTT_TMP_UTENTI_X_CSV")
public class PttTmpUtentiXCsv implements java.io.Serializable {

	private PttTmpUtentiXCsvId id;
	private Integer idUte;
	private String codEnte;
	private String username;
	private String desUte;
	private String matricola;
	private String flgAmm;
	private Date dtInizioVld;
	private Date dtFineVld;

	public PttTmpUtentiXCsv() {
	}

	public PttTmpUtentiXCsv(PttTmpUtentiXCsvId id) {
		this.id = id;
	}

	public PttTmpUtentiXCsv(PttTmpUtentiXCsvId id, Integer idUte,
			String codEnte, String username, String desUte, String matricola,
			String flgAmm, Date dtInizioVld, Date dtFineVld) {
		this.id = id;
		this.idUte = idUte;
		this.codEnte = codEnte;
		this.username = username;
		this.desUte = desUte;
		this.matricola = matricola;
		this.flgAmm = flgAmm;
		this.dtInizioVld = dtInizioVld;
		this.dtFineVld = dtFineVld;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "idEstrazione", column = @Column(name = "ID_ESTRAZIONE", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "progr", column = @Column(name = "PROGR", nullable = false, precision = 22, scale = 0)) })
	public PttTmpUtentiXCsvId getId() {
		return this.id;
	}

	public void setId(PttTmpUtentiXCsvId id) {
		this.id = id;
	}

	@Column(name = "ID_UTE", precision = 6, scale = 0)
	public Integer getIdUte() {
		return this.idUte;
	}

	public void setIdUte(Integer idUte) {
		this.idUte = idUte;
	}

	@Column(name = "COD_ENTE", length = 3)
	public String getCodEnte() {
		return this.codEnte;
	}

	public void setCodEnte(String codEnte) {
		this.codEnte = codEnte;
	}

	@Column(name = "USERNAME", length = 240)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "DES_UTE", length = 100)
	public String getDesUte() {
		return this.desUte;
	}

	public void setDesUte(String desUte) {
		this.desUte = desUte;
	}

	@Column(name = "MATRICOLA", length = 50)
	public String getMatricola() {
		return this.matricola;
	}

	public void setMatricola(String matricola) {
		this.matricola = matricola;
	}

	@Column(name = "FLG_AMM", length = 1)
	public String getFlgAmm() {
		return this.flgAmm;
	}

	public void setFlgAmm(String flgAmm) {
		this.flgAmm = flgAmm;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DT_INIZIO_VLD", length = 7)
	public Date getDtInizioVld() {
		return this.dtInizioVld;
	}

	public void setDtInizioVld(Date dtInizioVld) {
		this.dtInizioVld = dtInizioVld;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DT_FINE_VLD", length = 7)
	public Date getDtFineVld() {
		return this.dtFineVld;
	}

	public void setDtFineVld(Date dtFineVld) {
		this.dtFineVld = dtFineVld;
	}

}
