/* * SPDX-License-Identifier: AGPL-3.0-or-later * * C Copyright 2023 Regione Piemonte * */

// Generated 22-set-2016 12.14.09 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PttTitIndAmm generated by hbm2java
 */
@Entity
@Table(name = "PTT_TIT_IND_AMM")
public class PttTitIndAmm implements java.io.Serializable {

	private PttTitIndAmmId id;
	private PttTitolazioni pttTitolazioni;
	private CvtUo cvtUo;
	private String flgAbilProt;
	private Date dtIns;
	private Integer uteIns;
	private Date dtUltMod;
	private Integer uteUltMod;
	private String flgAbilApFasc;

	public PttTitIndAmm() {
	}

	public PttTitIndAmm(PttTitIndAmmId id, PttTitolazioni pttTitolazioni,
			CvtUo cvtUo) {
		this.id = id;
		this.pttTitolazioni = pttTitolazioni;
		this.cvtUo = cvtUo;
	}

	public PttTitIndAmm(PttTitIndAmmId id, PttTitolazioni pttTitolazioni,
			CvtUo cvtUo, String flgAbilProt, Date dtIns, Integer uteIns,
			Date dtUltMod, Integer uteUltMod, String flgAbilApFasc) {
		this.id = id;
		this.pttTitolazioni = pttTitolazioni;
		this.cvtUo = cvtUo;
		this.flgAbilProt = flgAbilProt;
		this.dtIns = dtIns;
		this.uteIns = uteIns;
		this.dtUltMod = dtUltMod;
		this.uteUltMod = uteUltMod;
		this.flgAbilApFasc = flgAbilApFasc;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "idTitolazione", column = @Column(name = "ID_TITOLAZIONE", nullable = false, precision = 25, scale = 0)),
			@AttributeOverride(name = "idIndice", column = @Column(name = "ID_INDICE", nullable = false, precision = 8, scale = 0)),
			@AttributeOverride(name = "idUo", column = @Column(name = "ID_UO", nullable = false, precision = 8, scale = 0)) })
	public PttTitIndAmmId getId() {
		return this.id;
	}

	public void setId(PttTitIndAmmId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_TITOLAZIONE", nullable = false, insertable = false, updatable = false)
	public PttTitolazioni getPttTitolazioni() {
		return this.pttTitolazioni;
	}

	public void setPttTitolazioni(PttTitolazioni pttTitolazioni) {
		this.pttTitolazioni = pttTitolazioni;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_UO", nullable = false, insertable = false, updatable = false)
	public CvtUo getCvtUo() {
		return this.cvtUo;
	}

	public void setCvtUo(CvtUo cvtUo) {
		this.cvtUo = cvtUo;
	}

	@Column(name = "FLG_ABIL_PROT", length = 1)
	public String getFlgAbilProt() {
		return this.flgAbilProt;
	}

	public void setFlgAbilProt(String flgAbilProt) {
		this.flgAbilProt = flgAbilProt;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DT_INS", length = 7)
	public Date getDtIns() {
		return this.dtIns;
	}

	public void setDtIns(Date dtIns) {
		this.dtIns = dtIns;
	}

	@Column(name = "UTE_INS", precision = 6, scale = 0)
	public Integer getUteIns() {
		return this.uteIns;
	}

	public void setUteIns(Integer uteIns) {
		this.uteIns = uteIns;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DT_ULT_MOD", length = 7)
	public Date getDtUltMod() {
		return this.dtUltMod;
	}

	public void setDtUltMod(Date dtUltMod) {
		this.dtUltMod = dtUltMod;
	}

	@Column(name = "UTE_ULT_MOD", precision = 6, scale = 0)
	public Integer getUteUltMod() {
		return this.uteUltMod;
	}

	public void setUteUltMod(Integer uteUltMod) {
		this.uteUltMod = uteUltMod;
	}

	@Column(name = "FLG_ABIL_AP_FASC", length = 1)
	public String getFlgAbilApFasc() {
		return this.flgAbilApFasc;
	}

	public void setFlgAbilApFasc(String flgAbilApFasc) {
		this.flgAbilApFasc = flgAbilApFasc;
	}

}
