/* * SPDX-License-Identifier: AGPL-3.0-or-later * * C Copyright 2023 Regione Piemonte * */

// Generated 22-set-2016 12.14.09 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PttTmpDocXCsv generated by hbm2java
 */
@Entity
@Table(name = "PTT_TMP_DOC_X_CSV")
public class PttTmpDocXCsv implements java.io.Serializable {

	private PttTmpDocXCsvId id;
	private String tpReg;
	private Short annoReg;
	private Integer numReg;
	private Short numCopia;
	private String tpReg2;
	private Short annoReg2;
	private Integer numReg2;
	private String tpRegEmerg;
	private Short annoRegEmerg;
	private Integer numRegEmerg;
	private String dtReg;
	private String tipoReg;
	private String dtArrivo;
	private String txtOgg;
	private String mittenti;
	private String destinatari;
	private Short nroAlleg;
	private String rifProv;
	private String protProv;
	private String dtProv;
	private String uoAss;
	private String flgAcc;
	private String desIndice;
	private String classFasc;
	private String flgEvd;
	private String flgRsv;
	private String flgScarto;
	private String flgRegAnn;
	private String flgCopiaAnn;
	private String flgCc;
	private Date dtAcc;
	private String desUteAcc;

	public PttTmpDocXCsv() {
	}

	public PttTmpDocXCsv(PttTmpDocXCsvId id) {
		this.id = id;
	}

	public PttTmpDocXCsv(PttTmpDocXCsvId id, String tpReg, Short annoReg,
			Integer numReg, Short numCopia, String tpReg2, Short annoReg2,
			Integer numReg2, String tpRegEmerg, Short annoRegEmerg,
			Integer numRegEmerg, String dtReg, String tipoReg, String dtArrivo,
			String txtOgg, String mittenti, String destinatari, Short nroAlleg,
			String rifProv, String protProv, String dtProv, String uoAss,
			String flgAcc, String desIndice, String classFasc, String flgEvd,
			String flgRsv, String flgScarto, String flgRegAnn,
			String flgCopiaAnn, String flgCc, Date dtAcc, String desUteAcc) {
		this.id = id;
		this.tpReg = tpReg;
		this.annoReg = annoReg;
		this.numReg = numReg;
		this.numCopia = numCopia;
		this.tpReg2 = tpReg2;
		this.annoReg2 = annoReg2;
		this.numReg2 = numReg2;
		this.tpRegEmerg = tpRegEmerg;
		this.annoRegEmerg = annoRegEmerg;
		this.numRegEmerg = numRegEmerg;
		this.dtReg = dtReg;
		this.tipoReg = tipoReg;
		this.dtArrivo = dtArrivo;
		this.txtOgg = txtOgg;
		this.mittenti = mittenti;
		this.destinatari = destinatari;
		this.nroAlleg = nroAlleg;
		this.rifProv = rifProv;
		this.protProv = protProv;
		this.dtProv = dtProv;
		this.uoAss = uoAss;
		this.flgAcc = flgAcc;
		this.desIndice = desIndice;
		this.classFasc = classFasc;
		this.flgEvd = flgEvd;
		this.flgRsv = flgRsv;
		this.flgScarto = flgScarto;
		this.flgRegAnn = flgRegAnn;
		this.flgCopiaAnn = flgCopiaAnn;
		this.flgCc = flgCc;
		this.dtAcc = dtAcc;
		this.desUteAcc = desUteAcc;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "idEstrazione", column = @Column(name = "ID_ESTRAZIONE", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "progr", column = @Column(name = "PROGR", nullable = false, precision = 22, scale = 0)) })
	public PttTmpDocXCsvId getId() {
		return this.id;
	}

	public void setId(PttTmpDocXCsvId id) {
		this.id = id;
	}

	@Column(name = "TP_REG", length = 5)
	public String getTpReg() {
		return this.tpReg;
	}

	public void setTpReg(String tpReg) {
		this.tpReg = tpReg;
	}

	@Column(name = "ANNO_REG", precision = 4, scale = 0)
	public Short getAnnoReg() {
		return this.annoReg;
	}

	public void setAnnoReg(Short annoReg) {
		this.annoReg = annoReg;
	}

	@Column(name = "NUM_REG", precision = 7, scale = 0)
	public Integer getNumReg() {
		return this.numReg;
	}

	public void setNumReg(Integer numReg) {
		this.numReg = numReg;
	}

	@Column(name = "NUM_COPIA", precision = 4, scale = 0)
	public Short getNumCopia() {
		return this.numCopia;
	}

	public void setNumCopia(Short numCopia) {
		this.numCopia = numCopia;
	}

	@Column(name = "TP_REG_2", length = 5)
	public String getTpReg2() {
		return this.tpReg2;
	}

	public void setTpReg2(String tpReg2) {
		this.tpReg2 = tpReg2;
	}

	@Column(name = "ANNO_REG_2", precision = 4, scale = 0)
	public Short getAnnoReg2() {
		return this.annoReg2;
	}

	public void setAnnoReg2(Short annoReg2) {
		this.annoReg2 = annoReg2;
	}

	@Column(name = "NUM_REG_2", precision = 7, scale = 0)
	public Integer getNumReg2() {
		return this.numReg2;
	}

	public void setNumReg2(Integer numReg2) {
		this.numReg2 = numReg2;
	}

	@Column(name = "TP_REG_EMERG", length = 5)
	public String getTpRegEmerg() {
		return this.tpRegEmerg;
	}

	public void setTpRegEmerg(String tpRegEmerg) {
		this.tpRegEmerg = tpRegEmerg;
	}

	@Column(name = "ANNO_REG_EMERG", precision = 4, scale = 0)
	public Short getAnnoRegEmerg() {
		return this.annoRegEmerg;
	}

	public void setAnnoRegEmerg(Short annoRegEmerg) {
		this.annoRegEmerg = annoRegEmerg;
	}

	@Column(name = "NUM_REG_EMERG", precision = 7, scale = 0)
	public Integer getNumRegEmerg() {
		return this.numRegEmerg;
	}

	public void setNumRegEmerg(Integer numRegEmerg) {
		this.numRegEmerg = numRegEmerg;
	}

	@Column(name = "DT_REG", length = 30)
	public String getDtReg() {
		return this.dtReg;
	}

	public void setDtReg(String dtReg) {
		this.dtReg = dtReg;
	}

	@Column(name = "TIPO_REG", length = 30)
	public String getTipoReg() {
		return this.tipoReg;
	}

	public void setTipoReg(String tipoReg) {
		this.tipoReg = tipoReg;
	}

	@Column(name = "DT_ARRIVO", length = 30)
	public String getDtArrivo() {
		return this.dtArrivo;
	}

	public void setDtArrivo(String dtArrivo) {
		this.dtArrivo = dtArrivo;
	}

	@Column(name = "TXT_OGG", length = 500)
	public String getTxtOgg() {
		return this.txtOgg;
	}

	public void setTxtOgg(String txtOgg) {
		this.txtOgg = txtOgg;
	}

	@Column(name = "MITTENTI", length = 1000)
	public String getMittenti() {
		return this.mittenti;
	}

	public void setMittenti(String mittenti) {
		this.mittenti = mittenti;
	}

	@Column(name = "DESTINATARI", length = 1000)
	public String getDestinatari() {
		return this.destinatari;
	}

	public void setDestinatari(String destinatari) {
		this.destinatari = destinatari;
	}

	@Column(name = "NRO_ALLEG", precision = 3, scale = 0)
	public Short getNroAlleg() {
		return this.nroAlleg;
	}

	public void setNroAlleg(Short nroAlleg) {
		this.nroAlleg = nroAlleg;
	}

	@Column(name = "RIF_PROV", length = 20)
	public String getRifProv() {
		return this.rifProv;
	}

	public void setRifProv(String rifProv) {
		this.rifProv = rifProv;
	}

	@Column(name = "PROT_PROV", length = 20)
	public String getProtProv() {
		return this.protProv;
	}

	public void setProtProv(String protProv) {
		this.protProv = protProv;
	}

	@Column(name = "DT_PROV", length = 30)
	public String getDtProv() {
		return this.dtProv;
	}

	public void setDtProv(String dtProv) {
		this.dtProv = dtProv;
	}

	@Column(name = "UO_ASS", length = 1000)
	public String getUoAss() {
		return this.uoAss;
	}

	public void setUoAss(String uoAss) {
		this.uoAss = uoAss;
	}

	@Column(name = "FLG_ACC", length = 1)
	public String getFlgAcc() {
		return this.flgAcc;
	}

	public void setFlgAcc(String flgAcc) {
		this.flgAcc = flgAcc;
	}

	@Column(name = "DES_INDICE", length = 250)
	public String getDesIndice() {
		return this.desIndice;
	}

	public void setDesIndice(String desIndice) {
		this.desIndice = desIndice;
	}

	@Column(name = "CLASS_FASC", length = 50)
	public String getClassFasc() {
		return this.classFasc;
	}

	public void setClassFasc(String classFasc) {
		this.classFasc = classFasc;
	}

	@Column(name = "FLG_EVD", length = 1)
	public String getFlgEvd() {
		return this.flgEvd;
	}

	public void setFlgEvd(String flgEvd) {
		this.flgEvd = flgEvd;
	}

	@Column(name = "FLG_RSV", length = 1)
	public String getFlgRsv() {
		return this.flgRsv;
	}

	public void setFlgRsv(String flgRsv) {
		this.flgRsv = flgRsv;
	}

	@Column(name = "FLG_SCARTO", length = 1)
	public String getFlgScarto() {
		return this.flgScarto;
	}

	public void setFlgScarto(String flgScarto) {
		this.flgScarto = flgScarto;
	}

	@Column(name = "FLG_REG_ANN", length = 1)
	public String getFlgRegAnn() {
		return this.flgRegAnn;
	}

	public void setFlgRegAnn(String flgRegAnn) {
		this.flgRegAnn = flgRegAnn;
	}

	@Column(name = "FLG_COPIA_ANN", length = 1)
	public String getFlgCopiaAnn() {
		return this.flgCopiaAnn;
	}

	public void setFlgCopiaAnn(String flgCopiaAnn) {
		this.flgCopiaAnn = flgCopiaAnn;
	}

	@Column(name = "FLG_CC", length = 1)
	public String getFlgCc() {
		return this.flgCc;
	}

	public void setFlgCc(String flgCc) {
		this.flgCc = flgCc;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DT_ACC", length = 7)
	public Date getDtAcc() {
		return this.dtAcc;
	}

	public void setDtAcc(Date dtAcc) {
		this.dtAcc = dtAcc;
	}

	@Column(name = "DES_UTE_ACC", length = 100)
	public String getDesUteAcc() {
		return this.desUteAcc;
	}

	public void setDesUteAcc(String desUteAcc) {
		this.desUteAcc = desUteAcc;
	}

}
