/* * SPDX-License-Identifier: AGPL-3.0-or-later * * C Copyright 2023 Regione Piemonte * */

// Generated 22-set-2016 12.14.09 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PttTplog generated by hbm2java
 */
@Entity
@Table(name = "PTT_TPLOG")
public class PttTplog implements java.io.Serializable {

	private short idTpLog;
	private String desTpLog;
	private Date dtIns;
	private Integer uteIns;
	private Date dtUltMod;
	private Integer uteUltMod;
	private Set<PttSttplog> pttSttplogs = new HashSet<PttSttplog>(0);

	public PttTplog() {
	}

	public PttTplog(short idTpLog, String desTpLog) {
		this.idTpLog = idTpLog;
		this.desTpLog = desTpLog;
	}

	public PttTplog(short idTpLog, String desTpLog, Date dtIns, Integer uteIns,
			Date dtUltMod, Integer uteUltMod, Set<PttSttplog> pttSttplogs) {
		this.idTpLog = idTpLog;
		this.desTpLog = desTpLog;
		this.dtIns = dtIns;
		this.uteIns = uteIns;
		this.dtUltMod = dtUltMod;
		this.uteUltMod = uteUltMod;
		this.pttSttplogs = pttSttplogs;
	}

	@Id
	@Column(name = "ID_TP_LOG", unique = true, nullable = false, precision = 4, scale = 0)
	public short getIdTpLog() {
		return this.idTpLog;
	}

	public void setIdTpLog(short idTpLog) {
		this.idTpLog = idTpLog;
	}

	@Column(name = "DES_TP_LOG", nullable = false, length = 50)
	public String getDesTpLog() {
		return this.desTpLog;
	}

	public void setDesTpLog(String desTpLog) {
		this.desTpLog = desTpLog;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DT_INS", length = 7)
	public Date getDtIns() {
		return this.dtIns;
	}

	public void setDtIns(Date dtIns) {
		this.dtIns = dtIns;
	}

	@Column(name = "UTE_INS", precision = 6, scale = 0)
	public Integer getUteIns() {
		return this.uteIns;
	}

	public void setUteIns(Integer uteIns) {
		this.uteIns = uteIns;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DT_ULT_MOD", length = 7)
	public Date getDtUltMod() {
		return this.dtUltMod;
	}

	public void setDtUltMod(Date dtUltMod) {
		this.dtUltMod = dtUltMod;
	}

	@Column(name = "UTE_ULT_MOD", precision = 6, scale = 0)
	public Integer getUteUltMod() {
		return this.uteUltMod;
	}

	public void setUteUltMod(Integer uteUltMod) {
		this.uteUltMod = uteUltMod;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pttTplog")
	public Set<PttSttplog> getPttSttplogs() {
		return this.pttSttplogs;
	}

	public void setPttSttplogs(Set<PttSttplog> pttSttplogs) {
		this.pttSttplogs = pttSttplogs;
	}

}
