/* * SPDX-License-Identifier: AGPL-3.0-or-later * * C Copyright 2023 Regione Piemonte * */

// Generated 22-set-2016 12.14.09 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * PttTmpRicECam generated by hbm2java
 */
@Entity
@Table(name = "PTT_TMP_RIC_E_CAM")
public class PttTmpRicECam implements java.io.Serializable {

	private String idEstrazione;
	private String tipo;
	private String datapg;
	private String oggetto;
	private String numeropg;
	private String anno;
	private String classifica;
	private String numeroallegati;
	private String ricevente;
	private String settoreassegnatario;
	private String servizioassegnatario;
	private String dataaperturafasc;
	private String fascicolo;
	private String sottofascicolo;
	private String oggettofasc;
	private String annofascicolo;
	private String classificafasc;
	private String cognomenome;
	private String notestoria;
	private String tipoprotocollazione;
	private String peraccettazione;

	public PttTmpRicECam() {
	}

	public PttTmpRicECam(String idEstrazione) {
		this.idEstrazione = idEstrazione;
	}

	public PttTmpRicECam(String idEstrazione, String tipo, String datapg,
			String oggetto, String numeropg, String anno, String classifica,
			String numeroallegati, String ricevente,
			String settoreassegnatario, String servizioassegnatario,
			String dataaperturafasc, String fascicolo, String sottofascicolo,
			String oggettofasc, String annofascicolo, String classificafasc,
			String cognomenome, String notestoria, String tipoprotocollazione,
			String peraccettazione) {
		this.idEstrazione = idEstrazione;
		this.tipo = tipo;
		this.datapg = datapg;
		this.oggetto = oggetto;
		this.numeropg = numeropg;
		this.anno = anno;
		this.classifica = classifica;
		this.numeroallegati = numeroallegati;
		this.ricevente = ricevente;
		this.settoreassegnatario = settoreassegnatario;
		this.servizioassegnatario = servizioassegnatario;
		this.dataaperturafasc = dataaperturafasc;
		this.fascicolo = fascicolo;
		this.sottofascicolo = sottofascicolo;
		this.oggettofasc = oggettofasc;
		this.annofascicolo = annofascicolo;
		this.classificafasc = classificafasc;
		this.cognomenome = cognomenome;
		this.notestoria = notestoria;
		this.tipoprotocollazione = tipoprotocollazione;
		this.peraccettazione = peraccettazione;
	}

	@Id
	@Column(name = "ID_ESTRAZIONE", unique = true, nullable = false, length = 16)
	public String getIdEstrazione() {
		return this.idEstrazione;
	}

	public void setIdEstrazione(String idEstrazione) {
		this.idEstrazione = idEstrazione;
	}

	@Column(name = "TIPO", length = 1)
	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	@Column(name = "DATAPG", length = 20)
	public String getDatapg() {
		return this.datapg;
	}

	public void setDatapg(String datapg) {
		this.datapg = datapg;
	}

	@Column(name = "OGGETTO", length = 500)
	public String getOggetto() {
		return this.oggetto;
	}

	public void setOggetto(String oggetto) {
		this.oggetto = oggetto;
	}

	@Column(name = "NUMEROPG", length = 10)
	public String getNumeropg() {
		return this.numeropg;
	}

	public void setNumeropg(String numeropg) {
		this.numeropg = numeropg;
	}

	@Column(name = "ANNO", length = 4)
	public String getAnno() {
		return this.anno;
	}

	public void setAnno(String anno) {
		this.anno = anno;
	}

	@Column(name = "CLASSIFICA", length = 100)
	public String getClassifica() {
		return this.classifica;
	}

	public void setClassifica(String classifica) {
		this.classifica = classifica;
	}

	@Column(name = "NUMEROALLEGATI", length = 5)
	public String getNumeroallegati() {
		return this.numeroallegati;
	}

	public void setNumeroallegati(String numeroallegati) {
		this.numeroallegati = numeroallegati;
	}

	@Column(name = "RICEVENTE", length = 150)
	public String getRicevente() {
		return this.ricevente;
	}

	public void setRicevente(String ricevente) {
		this.ricevente = ricevente;
	}

	@Column(name = "SETTOREASSEGNATARIO", length = 75)
	public String getSettoreassegnatario() {
		return this.settoreassegnatario;
	}

	public void setSettoreassegnatario(String settoreassegnatario) {
		this.settoreassegnatario = settoreassegnatario;
	}

	@Column(name = "SERVIZIOASSEGNATARIO", length = 75)
	public String getServizioassegnatario() {
		return this.servizioassegnatario;
	}

	public void setServizioassegnatario(String servizioassegnatario) {
		this.servizioassegnatario = servizioassegnatario;
	}

	@Column(name = "DATAAPERTURAFASC", length = 16)
	public String getDataaperturafasc() {
		return this.dataaperturafasc;
	}

	public void setDataaperturafasc(String dataaperturafasc) {
		this.dataaperturafasc = dataaperturafasc;
	}

	@Column(name = "FASCICOLO", length = 10)
	public String getFascicolo() {
		return this.fascicolo;
	}

	public void setFascicolo(String fascicolo) {
		this.fascicolo = fascicolo;
	}

	@Column(name = "SOTTOFASCICOLO", length = 10)
	public String getSottofascicolo() {
		return this.sottofascicolo;
	}

	public void setSottofascicolo(String sottofascicolo) {
		this.sottofascicolo = sottofascicolo;
	}

	@Column(name = "OGGETTOFASC", length = 250)
	public String getOggettofasc() {
		return this.oggettofasc;
	}

	public void setOggettofasc(String oggettofasc) {
		this.oggettofasc = oggettofasc;
	}

	@Column(name = "ANNOFASCICOLO", length = 4)
	public String getAnnofascicolo() {
		return this.annofascicolo;
	}

	public void setAnnofascicolo(String annofascicolo) {
		this.annofascicolo = annofascicolo;
	}

	@Column(name = "CLASSIFICAFASC", length = 100)
	public String getClassificafasc() {
		return this.classificafasc;
	}

	public void setClassificafasc(String classificafasc) {
		this.classificafasc = classificafasc;
	}

	@Column(name = "COGNOMENOME", length = 50)
	public String getCognomenome() {
		return this.cognomenome;
	}

	public void setCognomenome(String cognomenome) {
		this.cognomenome = cognomenome;
	}

	@Column(name = "NOTESTORIA", length = 250)
	public String getNotestoria() {
		return this.notestoria;
	}

	public void setNotestoria(String notestoria) {
		this.notestoria = notestoria;
	}

	@Column(name = "TIPOPROTOCOLLAZIONE", length = 2)
	public String getTipoprotocollazione() {
		return this.tipoprotocollazione;
	}

	public void setTipoprotocollazione(String tipoprotocollazione) {
		this.tipoprotocollazione = tipoprotocollazione;
	}

	@Column(name = "PERACCETTAZIONE", length = 150)
	public String getPeraccettazione() {
		return this.peraccettazione;
	}

	public void setPeraccettazione(String peraccettazione) {
		this.peraccettazione = peraccettazione;
	}

}
