/* * SPDX-License-Identifier: AGPL-3.0-or-later * * C Copyright 2023 Regione Piemonte * */

// Generated 22-set-2016 12.14.09 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PttTpalleg generated by hbm2java
 */
@Entity
@Table(name = "PTT_TPALLEG")
public class PttTpalleg implements java.io.Serializable {

	private short idTpAlleg;
	private String desTpAlleg;
	private Integer uteIns;
	private Date dtIns;
	private Integer uteUltMod;
	private Date dtUltMod;
	private Boolean flgVisDocEle;
	private Set<PttScannerImg> pttScannerImgs = new HashSet<PttScannerImg>(0);
	private Set<PttAllegdoc> pttAllegdocs = new HashSet<PttAllegdoc>(0);

	public PttTpalleg() {
	}

	public PttTpalleg(short idTpAlleg, String desTpAlleg) {
		this.idTpAlleg = idTpAlleg;
		this.desTpAlleg = desTpAlleg;
	}

	public PttTpalleg(short idTpAlleg, String desTpAlleg, Integer uteIns,
			Date dtIns, Integer uteUltMod, Date dtUltMod, Boolean flgVisDocEle,
			Set<PttScannerImg> pttScannerImgs, Set<PttAllegdoc> pttAllegdocs) {
		this.idTpAlleg = idTpAlleg;
		this.desTpAlleg = desTpAlleg;
		this.uteIns = uteIns;
		this.dtIns = dtIns;
		this.uteUltMod = uteUltMod;
		this.dtUltMod = dtUltMod;
		this.flgVisDocEle = flgVisDocEle;
		this.pttScannerImgs = pttScannerImgs;
		this.pttAllegdocs = pttAllegdocs;
	}

	@Id
	@Column(name = "ID_TP_ALLEG", unique = true, nullable = false, precision = 4, scale = 0)
	public short getIdTpAlleg() {
		return this.idTpAlleg;
	}

	public void setIdTpAlleg(short idTpAlleg) {
		this.idTpAlleg = idTpAlleg;
	}

	@Column(name = "DES_TP_ALLEG", nullable = false, length = 50)
	public String getDesTpAlleg() {
		return this.desTpAlleg;
	}

	public void setDesTpAlleg(String desTpAlleg) {
		this.desTpAlleg = desTpAlleg;
	}

	@Column(name = "UTE_INS", precision = 6, scale = 0)
	public Integer getUteIns() {
		return this.uteIns;
	}

	public void setUteIns(Integer uteIns) {
		this.uteIns = uteIns;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DT_INS", length = 7)
	public Date getDtIns() {
		return this.dtIns;
	}

	public void setDtIns(Date dtIns) {
		this.dtIns = dtIns;
	}

	@Column(name = "UTE_ULT_MOD", precision = 6, scale = 0)
	public Integer getUteUltMod() {
		return this.uteUltMod;
	}

	public void setUteUltMod(Integer uteUltMod) {
		this.uteUltMod = uteUltMod;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DT_ULT_MOD", length = 7)
	public Date getDtUltMod() {
		return this.dtUltMod;
	}

	public void setDtUltMod(Date dtUltMod) {
		this.dtUltMod = dtUltMod;
	}

	@Column(name = "FLG_VIS_DOC_ELE", precision = 1, scale = 0)
	public Boolean getFlgVisDocEle() {
		return this.flgVisDocEle;
	}

	public void setFlgVisDocEle(Boolean flgVisDocEle) {
		this.flgVisDocEle = flgVisDocEle;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pttTpalleg")
	public Set<PttScannerImg> getPttScannerImgs() {
		return this.pttScannerImgs;
	}

	public void setPttScannerImgs(Set<PttScannerImg> pttScannerImgs) {
		this.pttScannerImgs = pttScannerImgs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pttTpalleg")
	public Set<PttAllegdoc> getPttAllegdocs() {
		return this.pttAllegdocs;
	}

	public void setPttAllegdocs(Set<PttAllegdoc> pttAllegdocs) {
		this.pttAllegdocs = pttAllegdocs;
	}

}
