/* * SPDX-License-Identifier: AGPL-3.0-or-later * * C Copyright 2023 Regione Piemonte * */

// Generated 22-set-2016 12.14.09 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PttUoassmod generated by hbm2java
 */
@Entity
@Table(name = "PTT_UOASSMOD")
public class PttUoassmod implements java.io.Serializable {

	private PttUoassmodId id;
	private String flgAssConosc;
	private Integer idIndice;
	private Date dtIns;
	private Integer uteIns;
	private Date dtUltMod;
	private Integer uteUltMod;
	private BigDecimal nroOrdine;
	private Short idTpFis;
	private Date dtRaccomandata;
	private String nroRaccomandata;

	public PttUoassmod() {
	}

	public PttUoassmod(PttUoassmodId id) {
		this.id = id;
	}

	public PttUoassmod(PttUoassmodId id, String flgAssConosc, Integer idIndice,
			Date dtIns, Integer uteIns, Date dtUltMod, Integer uteUltMod,
			BigDecimal nroOrdine, Short idTpFis, Date dtRaccomandata,
			String nroRaccomandata) {
		this.id = id;
		this.flgAssConosc = flgAssConosc;
		this.idIndice = idIndice;
		this.dtIns = dtIns;
		this.uteIns = uteIns;
		this.dtUltMod = dtUltMod;
		this.uteUltMod = uteUltMod;
		this.nroOrdine = nroOrdine;
		this.idTpFis = idTpFis;
		this.dtRaccomandata = dtRaccomandata;
		this.nroRaccomandata = nroRaccomandata;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "idModello", column = @Column(name = "ID_MODELLO", nullable = false, precision = 8, scale = 0)),
			@AttributeOverride(name = "codEnte", column = @Column(name = "COD_ENTE", nullable = false, length = 3)),
			@AttributeOverride(name = "idUoAss", column = @Column(name = "ID_UO_ASS", nullable = false, precision = 8, scale = 0)) })
	public PttUoassmodId getId() {
		return this.id;
	}

	public void setId(PttUoassmodId id) {
		this.id = id;
	}

	@Column(name = "FLG_ASS_CONOSC", length = 1)
	public String getFlgAssConosc() {
		return this.flgAssConosc;
	}

	public void setFlgAssConosc(String flgAssConosc) {
		this.flgAssConosc = flgAssConosc;
	}

	@Column(name = "ID_INDICE", precision = 8, scale = 0)
	public Integer getIdIndice() {
		return this.idIndice;
	}

	public void setIdIndice(Integer idIndice) {
		this.idIndice = idIndice;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DT_INS", length = 7)
	public Date getDtIns() {
		return this.dtIns;
	}

	public void setDtIns(Date dtIns) {
		this.dtIns = dtIns;
	}

	@Column(name = "UTE_INS", precision = 6, scale = 0)
	public Integer getUteIns() {
		return this.uteIns;
	}

	public void setUteIns(Integer uteIns) {
		this.uteIns = uteIns;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DT_ULT_MOD", length = 7)
	public Date getDtUltMod() {
		return this.dtUltMod;
	}

	public void setDtUltMod(Date dtUltMod) {
		this.dtUltMod = dtUltMod;
	}

	@Column(name = "UTE_ULT_MOD", precision = 6, scale = 0)
	public Integer getUteUltMod() {
		return this.uteUltMod;
	}

	public void setUteUltMod(Integer uteUltMod) {
		this.uteUltMod = uteUltMod;
	}

	@Column(name = "NRO_ORDINE", precision = 22, scale = 0)
	public BigDecimal getNroOrdine() {
		return this.nroOrdine;
	}

	public void setNroOrdine(BigDecimal nroOrdine) {
		this.nroOrdine = nroOrdine;
	}

	@Column(name = "ID_TP_FIS", precision = 4, scale = 0)
	public Short getIdTpFis() {
		return this.idTpFis;
	}

	public void setIdTpFis(Short idTpFis) {
		this.idTpFis = idTpFis;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DT_RACCOMANDATA", length = 7)
	public Date getDtRaccomandata() {
		return this.dtRaccomandata;
	}

	public void setDtRaccomandata(Date dtRaccomandata) {
		this.dtRaccomandata = dtRaccomandata;
	}

	@Column(name = "NRO_RACCOMANDATA", length = 30)
	public String getNroRaccomandata() {
		return this.nroRaccomandata;
	}

	public void setNroRaccomandata(String nroRaccomandata) {
		this.nroRaccomandata = nroRaccomandata;
	}

}
