/* * SPDX-License-Identifier: AGPL-3.0-or-later * * C Copyright 2023 Regione Piemonte * */

// Generated 22-set-2016 12.14.09 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PttUteUoVsAurigaId generated by hbm2java
 */
@Embeddable
public class PttUteUoVsAurigaId implements java.io.Serializable {

	private Integer idUte;
	private Integer idUo;

	public PttUteUoVsAurigaId() {
	}

	public PttUteUoVsAurigaId(Integer idUte, Integer idUo) {
		this.idUte = idUte;
		this.idUo = idUo;
	}

	@Column(name = "ID_UTE", precision = 6, scale = 0)
	public Integer getIdUte() {
		return this.idUte;
	}

	public void setIdUte(Integer idUte) {
		this.idUte = idUte;
	}

	@Column(name = "ID_UO", precision = 8, scale = 0)
	public Integer getIdUo() {
		return this.idUo;
	}

	public void setIdUo(Integer idUo) {
		this.idUo = idUo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PttUteUoVsAurigaId))
			return false;
		PttUteUoVsAurigaId castOther = (PttUteUoVsAurigaId) other;

		return ((this.getIdUte() == castOther.getIdUte()) || (this.getIdUte() != null
				&& castOther.getIdUte() != null && this.getIdUte().equals(
				castOther.getIdUte())))
				&& ((this.getIdUo() == castOther.getIdUo()) || (this.getIdUo() != null
						&& castOther.getIdUo() != null && this.getIdUo()
						.equals(castOther.getIdUo())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getIdUte() == null ? 0 : this.getIdUte().hashCode());
		result = 37 * result
				+ (getIdUo() == null ? 0 : this.getIdUo().hashCode());
		return result;
	}

}
