/* * SPDX-License-Identifier: AGPL-3.0-or-later * * C Copyright 2023 Regione Piemonte * */

// Generated 22-set-2016 12.14.09 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PttWebcomboboxId generated by hbm2java
 */
@Embeddable
public class PttWebcomboboxId implements java.io.Serializable {

	private String codice;
	private String idCampo;
	private String descCampo;
	private BigDecimal posizione;
	private String descrizione;

	public PttWebcomboboxId() {
	}

	public PttWebcomboboxId(String codice, String idCampo, String descCampo,
			BigDecimal posizione, String descrizione) {
		this.codice = codice;
		this.idCampo = idCampo;
		this.descCampo = descCampo;
		this.posizione = posizione;
		this.descrizione = descrizione;
	}

	@Column(name = "CODICE", length = 30)
	public String getCodice() {
		return this.codice;
	}

	public void setCodice(String codice) {
		this.codice = codice;
	}

	@Column(name = "ID_CAMPO", length = 10)
	public String getIdCampo() {
		return this.idCampo;
	}

	public void setIdCampo(String idCampo) {
		this.idCampo = idCampo;
	}

	@Column(name = "DESC_CAMPO", length = 100)
	public String getDescCampo() {
		return this.descCampo;
	}

	public void setDescCampo(String descCampo) {
		this.descCampo = descCampo;
	}

	@Column(name = "POSIZIONE", precision = 22, scale = 0)
	public BigDecimal getPosizione() {
		return this.posizione;
	}

	public void setPosizione(BigDecimal posizione) {
		this.posizione = posizione;
	}

	@Column(name = "DESCRIZIONE", length = 250)
	public String getDescrizione() {
		return this.descrizione;
	}

	public void setDescrizione(String descrizione) {
		this.descrizione = descrizione;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PttWebcomboboxId))
			return false;
		PttWebcomboboxId castOther = (PttWebcomboboxId) other;

		return ((this.getCodice() == castOther.getCodice()) || (this
				.getCodice() != null && castOther.getCodice() != null && this
				.getCodice().equals(castOther.getCodice())))
				&& ((this.getIdCampo() == castOther.getIdCampo()) || (this
						.getIdCampo() != null && castOther.getIdCampo() != null && this
						.getIdCampo().equals(castOther.getIdCampo())))
				&& ((this.getDescCampo() == castOther.getDescCampo()) || (this
						.getDescCampo() != null
						&& castOther.getDescCampo() != null && this
						.getDescCampo().equals(castOther.getDescCampo())))
				&& ((this.getPosizione() == castOther.getPosizione()) || (this
						.getPosizione() != null
						&& castOther.getPosizione() != null && this
						.getPosizione().equals(castOther.getPosizione())))
				&& ((this.getDescrizione() == castOther.getDescrizione()) || (this
						.getDescrizione() != null
						&& castOther.getDescrizione() != null && this
						.getDescrizione().equals(castOther.getDescrizione())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getCodice() == null ? 0 : this.getCodice().hashCode());
		result = 37 * result
				+ (getIdCampo() == null ? 0 : this.getIdCampo().hashCode());
		result = 37 * result
				+ (getDescCampo() == null ? 0 : this.getDescCampo().hashCode());
		result = 37 * result
				+ (getPosizione() == null ? 0 : this.getPosizione().hashCode());
		result = 37
				* result
				+ (getDescrizione() == null ? 0 : this.getDescrizione()
						.hashCode());
		return result;
	}

}
