/* * SPDX-License-Identifier: AGPL-3.0-or-later * * C Copyright 2023 Regione Piemonte * */

// Generated 22-set-2016 12.14.09 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PtvDocSmistatiId generated by hbm2java
 */
@Embeddable
public class PtvDocSmistatiId implements java.io.Serializable {

	private int idDoc;
	private String tpPtg;
	private Short annoPtg;
	private Integer numPtg;
	private String tpRpr;
	private Short annoRpr;
	private Integer numRpr;
	private BigDecimal numCopia;
	private String txtOgg;
	private Date dtProt;
	private Date dtRpr;
	private Date dtArrivo;
	private String flgTpProt;
	private String flgEvd;
	private String flgRsv;
	private BigDecimal uoAss;
	private int uoInCarico;
	private Date dtSped;
	private int uteSped;
	private Integer idIndice;
	private BigDecimal idTitolazione;
	private Integer idFascicolo;
	private BigDecimal numSottofasc;
	private String rifProv;
	private Date dtProv;
	private String protProv;
	private Integer uoProv;
	private Date dtTermPp;
	private short nroAlleg;

	public PtvDocSmistatiId() {
	}

	public PtvDocSmistatiId(int idDoc, String txtOgg, int uoInCarico,
			Date dtSped, int uteSped, short nroAlleg) {
		this.idDoc = idDoc;
		this.txtOgg = txtOgg;
		this.uoInCarico = uoInCarico;
		this.dtSped = dtSped;
		this.uteSped = uteSped;
		this.nroAlleg = nroAlleg;
	}

	public PtvDocSmistatiId(int idDoc, String tpPtg, Short annoPtg,
			Integer numPtg, String tpRpr, Short annoRpr, Integer numRpr,
			BigDecimal numCopia, String txtOgg, Date dtProt, Date dtRpr,
			Date dtArrivo, String flgTpProt, String flgEvd, String flgRsv,
			BigDecimal uoAss, int uoInCarico, Date dtSped, int uteSped,
			Integer idIndice, BigDecimal idTitolazione, Integer idFascicolo,
			BigDecimal numSottofasc, String rifProv, Date dtProv,
			String protProv, Integer uoProv, Date dtTermPp, short nroAlleg) {
		this.idDoc = idDoc;
		this.tpPtg = tpPtg;
		this.annoPtg = annoPtg;
		this.numPtg = numPtg;
		this.tpRpr = tpRpr;
		this.annoRpr = annoRpr;
		this.numRpr = numRpr;
		this.numCopia = numCopia;
		this.txtOgg = txtOgg;
		this.dtProt = dtProt;
		this.dtRpr = dtRpr;
		this.dtArrivo = dtArrivo;
		this.flgTpProt = flgTpProt;
		this.flgEvd = flgEvd;
		this.flgRsv = flgRsv;
		this.uoAss = uoAss;
		this.uoInCarico = uoInCarico;
		this.dtSped = dtSped;
		this.uteSped = uteSped;
		this.idIndice = idIndice;
		this.idTitolazione = idTitolazione;
		this.idFascicolo = idFascicolo;
		this.numSottofasc = numSottofasc;
		this.rifProv = rifProv;
		this.dtProv = dtProv;
		this.protProv = protProv;
		this.uoProv = uoProv;
		this.dtTermPp = dtTermPp;
		this.nroAlleg = nroAlleg;
	}

	@Column(name = "ID_DOC", nullable = false, precision = 8, scale = 0)
	public int getIdDoc() {
		return this.idDoc;
	}

	public void setIdDoc(int idDoc) {
		this.idDoc = idDoc;
	}

	@Column(name = "TP_PTG", length = 5)
	public String getTpPtg() {
		return this.tpPtg;
	}

	public void setTpPtg(String tpPtg) {
		this.tpPtg = tpPtg;
	}

	@Column(name = "ANNO_PTG", precision = 4, scale = 0)
	public Short getAnnoPtg() {
		return this.annoPtg;
	}

	public void setAnnoPtg(Short annoPtg) {
		this.annoPtg = annoPtg;
	}

	@Column(name = "NUM_PTG", precision = 7, scale = 0)
	public Integer getNumPtg() {
		return this.numPtg;
	}

	public void setNumPtg(Integer numPtg) {
		this.numPtg = numPtg;
	}

	@Column(name = "TP_RPR", length = 5)
	public String getTpRpr() {
		return this.tpRpr;
	}

	public void setTpRpr(String tpRpr) {
		this.tpRpr = tpRpr;
	}

	@Column(name = "ANNO_RPR", precision = 4, scale = 0)
	public Short getAnnoRpr() {
		return this.annoRpr;
	}

	public void setAnnoRpr(Short annoRpr) {
		this.annoRpr = annoRpr;
	}

	@Column(name = "NUM_RPR", precision = 7, scale = 0)
	public Integer getNumRpr() {
		return this.numRpr;
	}

	public void setNumRpr(Integer numRpr) {
		this.numRpr = numRpr;
	}

	@Column(name = "NUM_COPIA", precision = 22, scale = 0)
	public BigDecimal getNumCopia() {
		return this.numCopia;
	}

	public void setNumCopia(BigDecimal numCopia) {
		this.numCopia = numCopia;
	}

	@Column(name = "TXT_OGG", nullable = false, length = 500)
	public String getTxtOgg() {
		return this.txtOgg;
	}

	public void setTxtOgg(String txtOgg) {
		this.txtOgg = txtOgg;
	}

	@Column(name = "DT_PROT", length = 7)
	public Date getDtProt() {
		return this.dtProt;
	}

	public void setDtProt(Date dtProt) {
		this.dtProt = dtProt;
	}

	@Column(name = "DT_RPR", length = 7)
	public Date getDtRpr() {
		return this.dtRpr;
	}

	public void setDtRpr(Date dtRpr) {
		this.dtRpr = dtRpr;
	}

	@Column(name = "DT_ARRIVO", length = 7)
	public Date getDtArrivo() {
		return this.dtArrivo;
	}

	public void setDtArrivo(Date dtArrivo) {
		this.dtArrivo = dtArrivo;
	}

	@Column(name = "FLG_TP_PROT", length = 1)
	public String getFlgTpProt() {
		return this.flgTpProt;
	}

	public void setFlgTpProt(String flgTpProt) {
		this.flgTpProt = flgTpProt;
	}

	@Column(name = "FLG_EVD", length = 1)
	public String getFlgEvd() {
		return this.flgEvd;
	}

	public void setFlgEvd(String flgEvd) {
		this.flgEvd = flgEvd;
	}

	@Column(name = "FLG_RSV", length = 1)
	public String getFlgRsv() {
		return this.flgRsv;
	}

	public void setFlgRsv(String flgRsv) {
		this.flgRsv = flgRsv;
	}

	@Column(name = "UO_ASS", precision = 22, scale = 0)
	public BigDecimal getUoAss() {
		return this.uoAss;
	}

	public void setUoAss(BigDecimal uoAss) {
		this.uoAss = uoAss;
	}

	@Column(name = "UO_IN_CARICO", nullable = false, precision = 8, scale = 0)
	public int getUoInCarico() {
		return this.uoInCarico;
	}

	public void setUoInCarico(int uoInCarico) {
		this.uoInCarico = uoInCarico;
	}

	@Column(name = "DT_SPED", nullable = false, length = 7)
	public Date getDtSped() {
		return this.dtSped;
	}

	public void setDtSped(Date dtSped) {
		this.dtSped = dtSped;
	}

	@Column(name = "UTE_SPED", nullable = false, precision = 6, scale = 0)
	public int getUteSped() {
		return this.uteSped;
	}

	public void setUteSped(int uteSped) {
		this.uteSped = uteSped;
	}

	@Column(name = "ID_INDICE", precision = 8, scale = 0)
	public Integer getIdIndice() {
		return this.idIndice;
	}

	public void setIdIndice(Integer idIndice) {
		this.idIndice = idIndice;
	}

	@Column(name = "ID_TITOLAZIONE", precision = 25, scale = 0)
	public BigDecimal getIdTitolazione() {
		return this.idTitolazione;
	}

	public void setIdTitolazione(BigDecimal idTitolazione) {
		this.idTitolazione = idTitolazione;
	}

	@Column(name = "ID_FASCICOLO", precision = 8, scale = 0)
	public Integer getIdFascicolo() {
		return this.idFascicolo;
	}

	public void setIdFascicolo(Integer idFascicolo) {
		this.idFascicolo = idFascicolo;
	}

	@Column(name = "NUM_SOTTOFASC", precision = 22, scale = 0)
	public BigDecimal getNumSottofasc() {
		return this.numSottofasc;
	}

	public void setNumSottofasc(BigDecimal numSottofasc) {
		this.numSottofasc = numSottofasc;
	}

	@Column(name = "RIF_PROV", length = 30)
	public String getRifProv() {
		return this.rifProv;
	}

	public void setRifProv(String rifProv) {
		this.rifProv = rifProv;
	}

	@Column(name = "DT_PROV", length = 7)
	public Date getDtProv() {
		return this.dtProv;
	}

	public void setDtProv(Date dtProv) {
		this.dtProv = dtProv;
	}

	@Column(name = "PROT_PROV", length = 20)
	public String getProtProv() {
		return this.protProv;
	}

	public void setProtProv(String protProv) {
		this.protProv = protProv;
	}

	@Column(name = "UO_PROV", precision = 8, scale = 0)
	public Integer getUoProv() {
		return this.uoProv;
	}

	public void setUoProv(Integer uoProv) {
		this.uoProv = uoProv;
	}

	@Column(name = "DT_TERM_PP", length = 7)
	public Date getDtTermPp() {
		return this.dtTermPp;
	}

	public void setDtTermPp(Date dtTermPp) {
		this.dtTermPp = dtTermPp;
	}

	@Column(name = "NRO_ALLEG", nullable = false, precision = 3, scale = 0)
	public short getNroAlleg() {
		return this.nroAlleg;
	}

	public void setNroAlleg(short nroAlleg) {
		this.nroAlleg = nroAlleg;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PtvDocSmistatiId))
			return false;
		PtvDocSmistatiId castOther = (PtvDocSmistatiId) other;

		return (this.getIdDoc() == castOther.getIdDoc())
				&& ((this.getTpPtg() == castOther.getTpPtg()) || (this
						.getTpPtg() != null && castOther.getTpPtg() != null && this
						.getTpPtg().equals(castOther.getTpPtg())))
				&& ((this.getAnnoPtg() == castOther.getAnnoPtg()) || (this
						.getAnnoPtg() != null && castOther.getAnnoPtg() != null && this
						.getAnnoPtg().equals(castOther.getAnnoPtg())))
				&& ((this.getNumPtg() == castOther.getNumPtg()) || (this
						.getNumPtg() != null && castOther.getNumPtg() != null && this
						.getNumPtg().equals(castOther.getNumPtg())))
				&& ((this.getTpRpr() == castOther.getTpRpr()) || (this
						.getTpRpr() != null && castOther.getTpRpr() != null && this
						.getTpRpr().equals(castOther.getTpRpr())))
				&& ((this.getAnnoRpr() == castOther.getAnnoRpr()) || (this
						.getAnnoRpr() != null && castOther.getAnnoRpr() != null && this
						.getAnnoRpr().equals(castOther.getAnnoRpr())))
				&& ((this.getNumRpr() == castOther.getNumRpr()) || (this
						.getNumRpr() != null && castOther.getNumRpr() != null && this
						.getNumRpr().equals(castOther.getNumRpr())))
				&& ((this.getNumCopia() == castOther.getNumCopia()) || (this
						.getNumCopia() != null
						&& castOther.getNumCopia() != null && this
						.getNumCopia().equals(castOther.getNumCopia())))
				&& ((this.getTxtOgg() == castOther.getTxtOgg()) || (this
						.getTxtOgg() != null && castOther.getTxtOgg() != null && this
						.getTxtOgg().equals(castOther.getTxtOgg())))
				&& ((this.getDtProt() == castOther.getDtProt()) || (this
						.getDtProt() != null && castOther.getDtProt() != null && this
						.getDtProt().equals(castOther.getDtProt())))
				&& ((this.getDtRpr() == castOther.getDtRpr()) || (this
						.getDtRpr() != null && castOther.getDtRpr() != null && this
						.getDtRpr().equals(castOther.getDtRpr())))
				&& ((this.getDtArrivo() == castOther.getDtArrivo()) || (this
						.getDtArrivo() != null
						&& castOther.getDtArrivo() != null && this
						.getDtArrivo().equals(castOther.getDtArrivo())))
				&& ((this.getFlgTpProt() == castOther.getFlgTpProt()) || (this
						.getFlgTpProt() != null
						&& castOther.getFlgTpProt() != null && this
						.getFlgTpProt().equals(castOther.getFlgTpProt())))
				&& ((this.getFlgEvd() == castOther.getFlgEvd()) || (this
						.getFlgEvd() != null && castOther.getFlgEvd() != null && this
						.getFlgEvd().equals(castOther.getFlgEvd())))
				&& ((this.getFlgRsv() == castOther.getFlgRsv()) || (this
						.getFlgRsv() != null && castOther.getFlgRsv() != null && this
						.getFlgRsv().equals(castOther.getFlgRsv())))
				&& ((this.getUoAss() == castOther.getUoAss()) || (this
						.getUoAss() != null && castOther.getUoAss() != null && this
						.getUoAss().equals(castOther.getUoAss())))
				&& (this.getUoInCarico() == castOther.getUoInCarico())
				&& ((this.getDtSped() == castOther.getDtSped()) || (this
						.getDtSped() != null && castOther.getDtSped() != null && this
						.getDtSped().equals(castOther.getDtSped())))
				&& (this.getUteSped() == castOther.getUteSped())
				&& ((this.getIdIndice() == castOther.getIdIndice()) || (this
						.getIdIndice() != null
						&& castOther.getIdIndice() != null && this
						.getIdIndice().equals(castOther.getIdIndice())))
				&& ((this.getIdTitolazione() == castOther.getIdTitolazione()) || (this
						.getIdTitolazione() != null
						&& castOther.getIdTitolazione() != null && this
						.getIdTitolazione()
						.equals(castOther.getIdTitolazione())))
				&& ((this.getIdFascicolo() == castOther.getIdFascicolo()) || (this
						.getIdFascicolo() != null
						&& castOther.getIdFascicolo() != null && this
						.getIdFascicolo().equals(castOther.getIdFascicolo())))
				&& ((this.getNumSottofasc() == castOther.getNumSottofasc()) || (this
						.getNumSottofasc() != null
						&& castOther.getNumSottofasc() != null && this
						.getNumSottofasc().equals(castOther.getNumSottofasc())))
				&& ((this.getRifProv() == castOther.getRifProv()) || (this
						.getRifProv() != null && castOther.getRifProv() != null && this
						.getRifProv().equals(castOther.getRifProv())))
				&& ((this.getDtProv() == castOther.getDtProv()) || (this
						.getDtProv() != null && castOther.getDtProv() != null && this
						.getDtProv().equals(castOther.getDtProv())))
				&& ((this.getProtProv() == castOther.getProtProv()) || (this
						.getProtProv() != null
						&& castOther.getProtProv() != null && this
						.getProtProv().equals(castOther.getProtProv())))
				&& ((this.getUoProv() == castOther.getUoProv()) || (this
						.getUoProv() != null && castOther.getUoProv() != null && this
						.getUoProv().equals(castOther.getUoProv())))
				&& ((this.getDtTermPp() == castOther.getDtTermPp()) || (this
						.getDtTermPp() != null
						&& castOther.getDtTermPp() != null && this
						.getDtTermPp().equals(castOther.getDtTermPp())))
				&& (this.getNroAlleg() == castOther.getNroAlleg());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdDoc();
		result = 37 * result
				+ (getTpPtg() == null ? 0 : this.getTpPtg().hashCode());
		result = 37 * result
				+ (getAnnoPtg() == null ? 0 : this.getAnnoPtg().hashCode());
		result = 37 * result
				+ (getNumPtg() == null ? 0 : this.getNumPtg().hashCode());
		result = 37 * result
				+ (getTpRpr() == null ? 0 : this.getTpRpr().hashCode());
		result = 37 * result
				+ (getAnnoRpr() == null ? 0 : this.getAnnoRpr().hashCode());
		result = 37 * result
				+ (getNumRpr() == null ? 0 : this.getNumRpr().hashCode());
		result = 37 * result
				+ (getNumCopia() == null ? 0 : this.getNumCopia().hashCode());
		result = 37 * result
				+ (getTxtOgg() == null ? 0 : this.getTxtOgg().hashCode());
		result = 37 * result
				+ (getDtProt() == null ? 0 : this.getDtProt().hashCode());
		result = 37 * result
				+ (getDtRpr() == null ? 0 : this.getDtRpr().hashCode());
		result = 37 * result
				+ (getDtArrivo() == null ? 0 : this.getDtArrivo().hashCode());
		result = 37 * result
				+ (getFlgTpProt() == null ? 0 : this.getFlgTpProt().hashCode());
		result = 37 * result
				+ (getFlgEvd() == null ? 0 : this.getFlgEvd().hashCode());
		result = 37 * result
				+ (getFlgRsv() == null ? 0 : this.getFlgRsv().hashCode());
		result = 37 * result
				+ (getUoAss() == null ? 0 : this.getUoAss().hashCode());
		result = 37 * result + this.getUoInCarico();
		result = 37 * result
				+ (getDtSped() == null ? 0 : this.getDtSped().hashCode());
		result = 37 * result + this.getUteSped();
		result = 37 * result
				+ (getIdIndice() == null ? 0 : this.getIdIndice().hashCode());
		result = 37
				* result
				+ (getIdTitolazione() == null ? 0 : this.getIdTitolazione()
						.hashCode());
		result = 37
				* result
				+ (getIdFascicolo() == null ? 0 : this.getIdFascicolo()
						.hashCode());
		result = 37
				* result
				+ (getNumSottofasc() == null ? 0 : this.getNumSottofasc()
						.hashCode());
		result = 37 * result
				+ (getRifProv() == null ? 0 : this.getRifProv().hashCode());
		result = 37 * result
				+ (getDtProv() == null ? 0 : this.getDtProv().hashCode());
		result = 37 * result
				+ (getProtProv() == null ? 0 : this.getProtProv().hashCode());
		result = 37 * result
				+ (getUoProv() == null ? 0 : this.getUoProv().hashCode());
		result = 37 * result
				+ (getDtTermPp() == null ? 0 : this.getDtTermPp().hashCode());
		result = 37 * result + this.getNroAlleg();
		return result;
	}

}
