/* * SPDX-License-Identifier: AGPL-3.0-or-later * * C Copyright 2023 Regione Piemonte * */

// Generated 22-set-2016 12.14.09 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * PtvEventiDaVarUo generated by hbm2java
 */
@Entity
@Table(name = "PTV_EVENTI_DA_VAR_UO")
public class PtvEventiDaVarUo implements java.io.Serializable {

	private PtvEventiDaVarUoId id;

	public PtvEventiDaVarUo() {
	}

	public PtvEventiDaVarUo(PtvEventiDaVarUoId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "livelliStrOld", column = @Column(name = "LIVELLI_STR_OLD", length = 100)),
			@AttributeOverride(name = "desUoOld", column = @Column(name = "DES_UO_OLD", length = 250)),
			@AttributeOverride(name = "livelliStrNew", column = @Column(name = "LIVELLI_STR_NEW", length = 100)),
			@AttributeOverride(name = "desUoNew", column = @Column(name = "DES_UO_NEW", length = 250)),
			@AttributeOverride(name = "flgOrfano", column = @Column(name = "FLG_ORFANO", precision = 1, scale = 0)),
			@AttributeOverride(name = "flgNoSpostDocFasc", column = @Column(name = "FLG_NO_SPOST_DOC_FASC", nullable = false, precision = 1, scale = 0)),
			@AttributeOverride(name = "flgSpostDocFascSottouo", column = @Column(name = "FLG_SPOST_DOC_FASC_SOTTOUO", nullable = false, precision = 1, scale = 0)),
			@AttributeOverride(name = "statoVariazione", column = @Column(name = "STATO_VARIAZIONE", nullable = false, length = 30)),
			@AttributeOverride(name = "progrEvento", column = @Column(name = "PROGR_EVENTO", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "idVariazione", column = @Column(name = "ID_VARIAZIONE", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "tipoEvento", column = @Column(name = "TIPO_EVENTO", nullable = false, length = 30)),
			@AttributeOverride(name = "xmlDatiEvento", column = @Column(name = "XML_DATI_EVENTO", nullable = false)),
			@AttributeOverride(name = "xmlOpzioniRichSinc", column = @Column(name = "XML_OPZIONI_RICH_SINC")),
			@AttributeOverride(name = "stato", column = @Column(name = "STATO", nullable = false, length = 30)),
			@AttributeOverride(name = "tsUltAggStato", column = @Column(name = "TS_ULT_AGG_STATO", nullable = false, length = 7)),
			@AttributeOverride(name = "xmlOutputSincr", column = @Column(name = "XML_OUTPUT_SINCR")),
			@AttributeOverride(name = "tryNum", column = @Column(name = "TRY_NUM", precision = 22, scale = 0)),
			@AttributeOverride(name = "tsIns", column = @Column(name = "TS_INS", nullable = false)) })
	public PtvEventiDaVarUoId getId() {
		return this.id;
	}

	public void setId(PtvEventiDaVarUoId id) {
		this.id = id;
	}

}
