/* * SPDX-License-Identifier: AGPL-3.0-or-later * * C Copyright 2023 Regione Piemonte * */

// Generated 22-set-2016 12.14.09 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * PtvIndici generated by hbm2java
 */
@Entity
@Table(name = "PTV_INDICI")
public class PtvIndici implements java.io.Serializable {

	private PtvIndiciId id;

	public PtvIndici() {
	}

	public PtvIndici(PtvIndiciId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "idIndice", column = @Column(name = "ID_INDICE", nullable = false, precision = 8, scale = 0)),
			@AttributeOverride(name = "idTitolazione", column = @Column(name = "ID_TITOLAZIONE", nullable = false, precision = 25, scale = 0)),
			@AttributeOverride(name = "livelliClassif", column = @Column(name = "LIVELLI_CLASSIF", length = 97)),
			@AttributeOverride(name = "descrizione", column = @Column(name = "DESCRIZIONE", nullable = false, length = 250)),
			@AttributeOverride(name = "desClassif", column = @Column(name = "DES_CLASSIF", nullable = false, length = 250)),
			@AttributeOverride(name = "ordine", column = @Column(name = "ORDINE", length = 15)),
			@AttributeOverride(name = "dtInizioVld", column = @Column(name = "DT_INIZIO_VLD", nullable = false, length = 7)),
			@AttributeOverride(name = "dtFineVld", column = @Column(name = "DT_FINE_VLD", length = 7)) })
	public PtvIndiciId getId() {
		return this.id;
	}

	public void setId(PtvIndiciId id) {
		this.id = id;
	}

}
