/* * SPDX-License-Identifier: AGPL-3.0-or-later * * C Copyright 2023 Regione Piemonte * */

// Generated 22-set-2016 12.14.09 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PtvIndiciId generated by hbm2java
 */
@Embeddable
public class PtvIndiciId implements java.io.Serializable {

	private int idIndice;
	private BigDecimal idTitolazione;
	private String livelliClassif;
	private String descrizione;
	private String desClassif;
	private String ordine;
	private Date dtInizioVld;
	private Date dtFineVld;

	public PtvIndiciId() {
	}

	public PtvIndiciId(int idIndice, BigDecimal idTitolazione,
			String descrizione, String desClassif, Date dtInizioVld) {
		this.idIndice = idIndice;
		this.idTitolazione = idTitolazione;
		this.descrizione = descrizione;
		this.desClassif = desClassif;
		this.dtInizioVld = dtInizioVld;
	}

	public PtvIndiciId(int idIndice, BigDecimal idTitolazione,
			String livelliClassif, String descrizione, String desClassif,
			String ordine, Date dtInizioVld, Date dtFineVld) {
		this.idIndice = idIndice;
		this.idTitolazione = idTitolazione;
		this.livelliClassif = livelliClassif;
		this.descrizione = descrizione;
		this.desClassif = desClassif;
		this.ordine = ordine;
		this.dtInizioVld = dtInizioVld;
		this.dtFineVld = dtFineVld;
	}

	@Column(name = "ID_INDICE", nullable = false, precision = 8, scale = 0)
	public int getIdIndice() {
		return this.idIndice;
	}

	public void setIdIndice(int idIndice) {
		this.idIndice = idIndice;
	}

	@Column(name = "ID_TITOLAZIONE", nullable = false, precision = 25, scale = 0)
	public BigDecimal getIdTitolazione() {
		return this.idTitolazione;
	}

	public void setIdTitolazione(BigDecimal idTitolazione) {
		this.idTitolazione = idTitolazione;
	}

	@Column(name = "LIVELLI_CLASSIF", length = 97)
	public String getLivelliClassif() {
		return this.livelliClassif;
	}

	public void setLivelliClassif(String livelliClassif) {
		this.livelliClassif = livelliClassif;
	}

	@Column(name = "DESCRIZIONE", nullable = false, length = 250)
	public String getDescrizione() {
		return this.descrizione;
	}

	public void setDescrizione(String descrizione) {
		this.descrizione = descrizione;
	}

	@Column(name = "DES_CLASSIF", nullable = false, length = 250)
	public String getDesClassif() {
		return this.desClassif;
	}

	public void setDesClassif(String desClassif) {
		this.desClassif = desClassif;
	}

	@Column(name = "ORDINE", length = 15)
	public String getOrdine() {
		return this.ordine;
	}

	public void setOrdine(String ordine) {
		this.ordine = ordine;
	}

	@Column(name = "DT_INIZIO_VLD", nullable = false, length = 7)
	public Date getDtInizioVld() {
		return this.dtInizioVld;
	}

	public void setDtInizioVld(Date dtInizioVld) {
		this.dtInizioVld = dtInizioVld;
	}

	@Column(name = "DT_FINE_VLD", length = 7)
	public Date getDtFineVld() {
		return this.dtFineVld;
	}

	public void setDtFineVld(Date dtFineVld) {
		this.dtFineVld = dtFineVld;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PtvIndiciId))
			return false;
		PtvIndiciId castOther = (PtvIndiciId) other;

		return (this.getIdIndice() == castOther.getIdIndice())
				&& ((this.getIdTitolazione() == castOther.getIdTitolazione()) || (this
						.getIdTitolazione() != null
						&& castOther.getIdTitolazione() != null && this
						.getIdTitolazione()
						.equals(castOther.getIdTitolazione())))
				&& ((this.getLivelliClassif() == castOther.getLivelliClassif()) || (this
						.getLivelliClassif() != null
						&& castOther.getLivelliClassif() != null && this
						.getLivelliClassif().equals(
								castOther.getLivelliClassif())))
				&& ((this.getDescrizione() == castOther.getDescrizione()) || (this
						.getDescrizione() != null
						&& castOther.getDescrizione() != null && this
						.getDescrizione().equals(castOther.getDescrizione())))
				&& ((this.getDesClassif() == castOther.getDesClassif()) || (this
						.getDesClassif() != null
						&& castOther.getDesClassif() != null && this
						.getDesClassif().equals(castOther.getDesClassif())))
				&& ((this.getOrdine() == castOther.getOrdine()) || (this
						.getOrdine() != null && castOther.getOrdine() != null && this
						.getOrdine().equals(castOther.getOrdine())))
				&& ((this.getDtInizioVld() == castOther.getDtInizioVld()) || (this
						.getDtInizioVld() != null
						&& castOther.getDtInizioVld() != null && this
						.getDtInizioVld().equals(castOther.getDtInizioVld())))
				&& ((this.getDtFineVld() == castOther.getDtFineVld()) || (this
						.getDtFineVld() != null
						&& castOther.getDtFineVld() != null && this
						.getDtFineVld().equals(castOther.getDtFineVld())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdIndice();
		result = 37
				* result
				+ (getIdTitolazione() == null ? 0 : this.getIdTitolazione()
						.hashCode());
		result = 37
				* result
				+ (getLivelliClassif() == null ? 0 : this.getLivelliClassif()
						.hashCode());
		result = 37
				* result
				+ (getDescrizione() == null ? 0 : this.getDescrizione()
						.hashCode());
		result = 37
				* result
				+ (getDesClassif() == null ? 0 : this.getDesClassif()
						.hashCode());
		result = 37 * result
				+ (getOrdine() == null ? 0 : this.getOrdine().hashCode());
		result = 37
				* result
				+ (getDtInizioVld() == null ? 0 : this.getDtInizioVld()
						.hashCode());
		result = 37 * result
				+ (getDtFineVld() == null ? 0 : this.getDtFineVld().hashCode());
		return result;
	}

}
