/* * SPDX-License-Identifier: AGPL-3.0-or-later * * C Copyright 2023 Regione Piemonte * */

// Generated 22-set-2016 12.14.09 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * PtvNomdoc generated by hbm2java
 */
@Entity
@Table(name = "PTV_NOMDOC")
public class PtvNomdoc implements java.io.Serializable {

	private PtvNomdocId id;

	public PtvNomdoc() {
	}

	public PtvNomdoc(PtvNomdocId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "idDoc", column = @Column(name = "ID_DOC", nullable = false, precision = 8, scale = 0)),
			@AttributeOverride(name = "idAnag", column = @Column(name = "ID_ANAG", precision = 9, scale = 0)),
			@AttributeOverride(name = "flgEsibDest", column = @Column(name = "FLG_ESIB_DEST", length = 1)),
			@AttributeOverride(name = "flgAltriNom", column = @Column(name = "FLG_ALTRI_NOM", length = 1)),
			@AttributeOverride(name = "idTopon", column = @Column(name = "ID_TOPON", precision = 9, scale = 0)),
			@AttributeOverride(name = "numCiv", column = @Column(name = "NUM_CIV", precision = 5, scale = 0)),
			@AttributeOverride(name = "espCiv", column = @Column(name = "ESP_CIV", length = 12)),
			@AttributeOverride(name = "desInd", column = @Column(name = "DES_IND", length = 60)),
			@AttributeOverride(name = "idCom", column = @Column(name = "ID_COM", precision = 6, scale = 0)),
			@AttributeOverride(name = "desCom", column = @Column(name = "DES_COM", length = 60)),
			@AttributeOverride(name = "cap", column = @Column(name = "CAP", precision = 5, scale = 0)),
			@AttributeOverride(name = "dtInsNomdoc", column = @Column(name = "DT_INS_NOMDOC", length = 7)),
			@AttributeOverride(name = "uteInsNomdoc", column = @Column(name = "UTE_INS_NOMDOC", precision = 6, scale = 0)),
			@AttributeOverride(name = "dtUltModNomdoc", column = @Column(name = "DT_ULT_MOD_NOMDOC", length = 7)),
			@AttributeOverride(name = "uteUltModNomdoc", column = @Column(name = "UTE_ULT_MOD_NOMDOC", precision = 6, scale = 0)),
			@AttributeOverride(name = "flgDestCopia", column = @Column(name = "FLG_DEST_COPIA", length = 1)),
			@AttributeOverride(name = "idTpFis", column = @Column(name = "ID_TP_FIS", precision = 4, scale = 0)),
			@AttributeOverride(name = "dtRaccomandata", column = @Column(name = "DT_RACCOMANDATA", length = 7)),
			@AttributeOverride(name = "nroRaccomandata", column = @Column(name = "NRO_RACCOMANDATA", length = 30)),
			@AttributeOverride(name = "costoSped", column = @Column(name = "COSTO_SPED", precision = 11)),
			@AttributeOverride(name = "flgNovisStampe", column = @Column(name = "FLG_NOVIS_STAMPE", length = 1)),
			@AttributeOverride(name = "desAnag", column = @Column(name = "DES_ANAG", length = 750)),
			@AttributeOverride(name = "flgTpAnag", column = @Column(name = "FLG_TP_ANAG", length = 1)),
			@AttributeOverride(name = "codFis", column = @Column(name = "COD_FIS", length = 16)),
			@AttributeOverride(name = "parIva", column = @Column(name = "PAR_IVA", length = 11)),
			@AttributeOverride(name = "matAnag", column = @Column(name = "MAT_ANAG", precision = 9, scale = 0)),
			@AttributeOverride(name = "dtIniVld", column = @Column(name = "DT_INI_VLD", length = 7)),
			@AttributeOverride(name = "dtFinVld", column = @Column(name = "DT_FIN_VLD", length = 7)),
			@AttributeOverride(name = "email", column = @Column(name = "EMAIL", length = 400)),
			@AttributeOverride(name = "indicepaCodAmm", column = @Column(name = "INDICEPA_COD_AMM", length = 100)),
			@AttributeOverride(name = "indicepaCodAoo", column = @Column(name = "INDICEPA_COD_AOO", length = 100)) })
	public PtvNomdocId getId() {
		return this.id;
	}

	public void setId(PtvNomdocId id) {
		this.id = id;
	}

}
