/* * SPDX-License-Identifier: AGPL-3.0-or-later * * C Copyright 2023 Regione Piemonte * */

// Generated 22-set-2016 12.14.09 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PtvStampaGiornalieraId generated by hbm2java
 */
@Embeddable
public class PtvStampaGiornalieraId implements java.io.Serializable {

	private Short annoPtg;
	private Integer numPtg;
	private Date dtProt;
	private String codEnte;
	private Date dtProv;
	private String protProv;
	private String tpRegEmerg;
	private Short annoRegEmerg;
	private Integer numRegEmerg;
	private Integer idDoc;
	private String flgTpProt;
	private BigDecimal idIndice;
	private BigDecimal idFascicolo;
	private BigDecimal numSottofasc;
	private BigDecimal titolo;
	private BigDecimal classe;
	private BigDecimal sottoclasse;
	private BigDecimal anno;
	private BigDecimal progrFasc;
	private String rifProv;
	private String txtOgg;
	private Short nroAlleg;
	private BigDecimal uoSped;
	private Integer uteProt;
	private BigDecimal uoAss;
	private String numCopia;
	private Character flgCc;
	private String mittenti;
	private String destinatari;
	private BigDecimal livello4;
	private BigDecimal livello5;
	private String annullato;
	private String classif;
	private String tpPtg;
	private String docricevuto;

	public PtvStampaGiornalieraId() {
	}

	public PtvStampaGiornalieraId(Short annoPtg, Integer numPtg, Date dtProt,
			String codEnte, Date dtProv, String protProv, String tpRegEmerg,
			Short annoRegEmerg, Integer numRegEmerg, Integer idDoc,
			String flgTpProt, BigDecimal idIndice, BigDecimal idFascicolo,
			BigDecimal numSottofasc, BigDecimal titolo, BigDecimal classe,
			BigDecimal sottoclasse, BigDecimal anno, BigDecimal progrFasc,
			String rifProv, String txtOgg, Short nroAlleg, BigDecimal uoSped,
			Integer uteProt, BigDecimal uoAss, String numCopia,
			Character flgCc, String mittenti, String destinatari,
			BigDecimal livello4, BigDecimal livello5, String annullato,
			String classif, String tpPtg, String docricevuto) {
		this.annoPtg = annoPtg;
		this.numPtg = numPtg;
		this.dtProt = dtProt;
		this.codEnte = codEnte;
		this.dtProv = dtProv;
		this.protProv = protProv;
		this.tpRegEmerg = tpRegEmerg;
		this.annoRegEmerg = annoRegEmerg;
		this.numRegEmerg = numRegEmerg;
		this.idDoc = idDoc;
		this.flgTpProt = flgTpProt;
		this.idIndice = idIndice;
		this.idFascicolo = idFascicolo;
		this.numSottofasc = numSottofasc;
		this.titolo = titolo;
		this.classe = classe;
		this.sottoclasse = sottoclasse;
		this.anno = anno;
		this.progrFasc = progrFasc;
		this.rifProv = rifProv;
		this.txtOgg = txtOgg;
		this.nroAlleg = nroAlleg;
		this.uoSped = uoSped;
		this.uteProt = uteProt;
		this.uoAss = uoAss;
		this.numCopia = numCopia;
		this.flgCc = flgCc;
		this.mittenti = mittenti;
		this.destinatari = destinatari;
		this.livello4 = livello4;
		this.livello5 = livello5;
		this.annullato = annullato;
		this.classif = classif;
		this.tpPtg = tpPtg;
		this.docricevuto = docricevuto;
	}

	@Column(name = "ANNO_PTG", precision = 4, scale = 0)
	public Short getAnnoPtg() {
		return this.annoPtg;
	}

	public void setAnnoPtg(Short annoPtg) {
		this.annoPtg = annoPtg;
	}

	@Column(name = "NUM_PTG", precision = 7, scale = 0)
	public Integer getNumPtg() {
		return this.numPtg;
	}

	public void setNumPtg(Integer numPtg) {
		this.numPtg = numPtg;
	}

	@Column(name = "DT_PROT", length = 7)
	public Date getDtProt() {
		return this.dtProt;
	}

	public void setDtProt(Date dtProt) {
		this.dtProt = dtProt;
	}

	@Column(name = "COD_ENTE", length = 3)
	public String getCodEnte() {
		return this.codEnte;
	}

	public void setCodEnte(String codEnte) {
		this.codEnte = codEnte;
	}

	@Column(name = "DT_PROV", length = 7)
	public Date getDtProv() {
		return this.dtProv;
	}

	public void setDtProv(Date dtProv) {
		this.dtProv = dtProv;
	}

	@Column(name = "PROT_PROV", length = 20)
	public String getProtProv() {
		return this.protProv;
	}

	public void setProtProv(String protProv) {
		this.protProv = protProv;
	}

	@Column(name = "TP_REG_EMERG", length = 5)
	public String getTpRegEmerg() {
		return this.tpRegEmerg;
	}

	public void setTpRegEmerg(String tpRegEmerg) {
		this.tpRegEmerg = tpRegEmerg;
	}

	@Column(name = "ANNO_REG_EMERG", precision = 4, scale = 0)
	public Short getAnnoRegEmerg() {
		return this.annoRegEmerg;
	}

	public void setAnnoRegEmerg(Short annoRegEmerg) {
		this.annoRegEmerg = annoRegEmerg;
	}

	@Column(name = "NUM_REG_EMERG", precision = 7, scale = 0)
	public Integer getNumRegEmerg() {
		return this.numRegEmerg;
	}

	public void setNumRegEmerg(Integer numRegEmerg) {
		this.numRegEmerg = numRegEmerg;
	}

	@Column(name = "ID_DOC", precision = 8, scale = 0)
	public Integer getIdDoc() {
		return this.idDoc;
	}

	public void setIdDoc(Integer idDoc) {
		this.idDoc = idDoc;
	}

	@Column(name = "FLG_TP_PROT", length = 2)
	public String getFlgTpProt() {
		return this.flgTpProt;
	}

	public void setFlgTpProt(String flgTpProt) {
		this.flgTpProt = flgTpProt;
	}

	@Column(name = "ID_INDICE", precision = 22, scale = 0)
	public BigDecimal getIdIndice() {
		return this.idIndice;
	}

	public void setIdIndice(BigDecimal idIndice) {
		this.idIndice = idIndice;
	}

	@Column(name = "ID_FASCICOLO", precision = 22, scale = 0)
	public BigDecimal getIdFascicolo() {
		return this.idFascicolo;
	}

	public void setIdFascicolo(BigDecimal idFascicolo) {
		this.idFascicolo = idFascicolo;
	}

	@Column(name = "NUM_SOTTOFASC", precision = 22, scale = 0)
	public BigDecimal getNumSottofasc() {
		return this.numSottofasc;
	}

	public void setNumSottofasc(BigDecimal numSottofasc) {
		this.numSottofasc = numSottofasc;
	}

	@Column(name = "TITOLO", precision = 22, scale = 0)
	public BigDecimal getTitolo() {
		return this.titolo;
	}

	public void setTitolo(BigDecimal titolo) {
		this.titolo = titolo;
	}

	@Column(name = "CLASSE", precision = 22, scale = 0)
	public BigDecimal getClasse() {
		return this.classe;
	}

	public void setClasse(BigDecimal classe) {
		this.classe = classe;
	}

	@Column(name = "SOTTOCLASSE", precision = 22, scale = 0)
	public BigDecimal getSottoclasse() {
		return this.sottoclasse;
	}

	public void setSottoclasse(BigDecimal sottoclasse) {
		this.sottoclasse = sottoclasse;
	}

	@Column(name = "ANNO", precision = 22, scale = 0)
	public BigDecimal getAnno() {
		return this.anno;
	}

	public void setAnno(BigDecimal anno) {
		this.anno = anno;
	}

	@Column(name = "PROGR_FASC", precision = 22, scale = 0)
	public BigDecimal getProgrFasc() {
		return this.progrFasc;
	}

	public void setProgrFasc(BigDecimal progrFasc) {
		this.progrFasc = progrFasc;
	}

	@Column(name = "RIF_PROV", length = 30)
	public String getRifProv() {
		return this.rifProv;
	}

	public void setRifProv(String rifProv) {
		this.rifProv = rifProv;
	}

	@Column(name = "TXT_OGG", length = 500)
	public String getTxtOgg() {
		return this.txtOgg;
	}

	public void setTxtOgg(String txtOgg) {
		this.txtOgg = txtOgg;
	}

	@Column(name = "NRO_ALLEG", precision = 3, scale = 0)
	public Short getNroAlleg() {
		return this.nroAlleg;
	}

	public void setNroAlleg(Short nroAlleg) {
		this.nroAlleg = nroAlleg;
	}

	@Column(name = "UO_SPED", precision = 22, scale = 0)
	public BigDecimal getUoSped() {
		return this.uoSped;
	}

	public void setUoSped(BigDecimal uoSped) {
		this.uoSped = uoSped;
	}

	@Column(name = "UTE_PROT", precision = 6, scale = 0)
	public Integer getUteProt() {
		return this.uteProt;
	}

	public void setUteProt(Integer uteProt) {
		this.uteProt = uteProt;
	}

	@Column(name = "UO_ASS", precision = 22, scale = 0)
	public BigDecimal getUoAss() {
		return this.uoAss;
	}

	public void setUoAss(BigDecimal uoAss) {
		this.uoAss = uoAss;
	}

	@Column(name = "NUM_COPIA", length = 40)
	public String getNumCopia() {
		return this.numCopia;
	}

	public void setNumCopia(String numCopia) {
		this.numCopia = numCopia;
	}

	@Column(name = "FLG_CC", length = 1)
	public Character getFlgCc() {
		return this.flgCc;
	}

	public void setFlgCc(Character flgCc) {
		this.flgCc = flgCc;
	}

	@Column(name = "MITTENTI", length = 4000)
	public String getMittenti() {
		return this.mittenti;
	}

	public void setMittenti(String mittenti) {
		this.mittenti = mittenti;
	}

	@Column(name = "DESTINATARI", length = 4000)
	public String getDestinatari() {
		return this.destinatari;
	}

	public void setDestinatari(String destinatari) {
		this.destinatari = destinatari;
	}

	@Column(name = "LIVELLO4", precision = 22, scale = 0)
	public BigDecimal getLivello4() {
		return this.livello4;
	}

	public void setLivello4(BigDecimal livello4) {
		this.livello4 = livello4;
	}

	@Column(name = "LIVELLO5", precision = 22, scale = 0)
	public BigDecimal getLivello5() {
		return this.livello5;
	}

	public void setLivello5(BigDecimal livello5) {
		this.livello5 = livello5;
	}

	@Column(name = "ANNULLATO", length = 2)
	public String getAnnullato() {
		return this.annullato;
	}

	public void setAnnullato(String annullato) {
		this.annullato = annullato;
	}

	@Column(name = "CLASSIF", length = 4000)
	public String getClassif() {
		return this.classif;
	}

	public void setClassif(String classif) {
		this.classif = classif;
	}

	@Column(name = "TP_PTG", length = 5)
	public String getTpPtg() {
		return this.tpPtg;
	}

	public void setTpPtg(String tpPtg) {
		this.tpPtg = tpPtg;
	}

	@Column(name = "DOCRICEVUTO", length = 71)
	public String getDocricevuto() {
		return this.docricevuto;
	}

	public void setDocricevuto(String docricevuto) {
		this.docricevuto = docricevuto;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PtvStampaGiornalieraId))
			return false;
		PtvStampaGiornalieraId castOther = (PtvStampaGiornalieraId) other;

		return ((this.getAnnoPtg() == castOther.getAnnoPtg()) || (this
				.getAnnoPtg() != null && castOther.getAnnoPtg() != null && this
				.getAnnoPtg().equals(castOther.getAnnoPtg())))
				&& ((this.getNumPtg() == castOther.getNumPtg()) || (this
						.getNumPtg() != null && castOther.getNumPtg() != null && this
						.getNumPtg().equals(castOther.getNumPtg())))
				&& ((this.getDtProt() == castOther.getDtProt()) || (this
						.getDtProt() != null && castOther.getDtProt() != null && this
						.getDtProt().equals(castOther.getDtProt())))
				&& ((this.getCodEnte() == castOther.getCodEnte()) || (this
						.getCodEnte() != null && castOther.getCodEnte() != null && this
						.getCodEnte().equals(castOther.getCodEnte())))
				&& ((this.getDtProv() == castOther.getDtProv()) || (this
						.getDtProv() != null && castOther.getDtProv() != null && this
						.getDtProv().equals(castOther.getDtProv())))
				&& ((this.getProtProv() == castOther.getProtProv()) || (this
						.getProtProv() != null
						&& castOther.getProtProv() != null && this
						.getProtProv().equals(castOther.getProtProv())))
				&& ((this.getTpRegEmerg() == castOther.getTpRegEmerg()) || (this
						.getTpRegEmerg() != null
						&& castOther.getTpRegEmerg() != null && this
						.getTpRegEmerg().equals(castOther.getTpRegEmerg())))
				&& ((this.getAnnoRegEmerg() == castOther.getAnnoRegEmerg()) || (this
						.getAnnoRegEmerg() != null
						&& castOther.getAnnoRegEmerg() != null && this
						.getAnnoRegEmerg().equals(castOther.getAnnoRegEmerg())))
				&& ((this.getNumRegEmerg() == castOther.getNumRegEmerg()) || (this
						.getNumRegEmerg() != null
						&& castOther.getNumRegEmerg() != null && this
						.getNumRegEmerg().equals(castOther.getNumRegEmerg())))
				&& ((this.getIdDoc() == castOther.getIdDoc()) || (this
						.getIdDoc() != null && castOther.getIdDoc() != null && this
						.getIdDoc().equals(castOther.getIdDoc())))
				&& ((this.getFlgTpProt() == castOther.getFlgTpProt()) || (this
						.getFlgTpProt() != null
						&& castOther.getFlgTpProt() != null && this
						.getFlgTpProt().equals(castOther.getFlgTpProt())))
				&& ((this.getIdIndice() == castOther.getIdIndice()) || (this
						.getIdIndice() != null
						&& castOther.getIdIndice() != null && this
						.getIdIndice().equals(castOther.getIdIndice())))
				&& ((this.getIdFascicolo() == castOther.getIdFascicolo()) || (this
						.getIdFascicolo() != null
						&& castOther.getIdFascicolo() != null && this
						.getIdFascicolo().equals(castOther.getIdFascicolo())))
				&& ((this.getNumSottofasc() == castOther.getNumSottofasc()) || (this
						.getNumSottofasc() != null
						&& castOther.getNumSottofasc() != null && this
						.getNumSottofasc().equals(castOther.getNumSottofasc())))
				&& ((this.getTitolo() == castOther.getTitolo()) || (this
						.getTitolo() != null && castOther.getTitolo() != null && this
						.getTitolo().equals(castOther.getTitolo())))
				&& ((this.getClasse() == castOther.getClasse()) || (this
						.getClasse() != null && castOther.getClasse() != null && this
						.getClasse().equals(castOther.getClasse())))
				&& ((this.getSottoclasse() == castOther.getSottoclasse()) || (this
						.getSottoclasse() != null
						&& castOther.getSottoclasse() != null && this
						.getSottoclasse().equals(castOther.getSottoclasse())))
				&& ((this.getAnno() == castOther.getAnno()) || (this.getAnno() != null
						&& castOther.getAnno() != null && this.getAnno()
						.equals(castOther.getAnno())))
				&& ((this.getProgrFasc() == castOther.getProgrFasc()) || (this
						.getProgrFasc() != null
						&& castOther.getProgrFasc() != null && this
						.getProgrFasc().equals(castOther.getProgrFasc())))
				&& ((this.getRifProv() == castOther.getRifProv()) || (this
						.getRifProv() != null && castOther.getRifProv() != null && this
						.getRifProv().equals(castOther.getRifProv())))
				&& ((this.getTxtOgg() == castOther.getTxtOgg()) || (this
						.getTxtOgg() != null && castOther.getTxtOgg() != null && this
						.getTxtOgg().equals(castOther.getTxtOgg())))
				&& ((this.getNroAlleg() == castOther.getNroAlleg()) || (this
						.getNroAlleg() != null
						&& castOther.getNroAlleg() != null && this
						.getNroAlleg().equals(castOther.getNroAlleg())))
				&& ((this.getUoSped() == castOther.getUoSped()) || (this
						.getUoSped() != null && castOther.getUoSped() != null && this
						.getUoSped().equals(castOther.getUoSped())))
				&& ((this.getUteProt() == castOther.getUteProt()) || (this
						.getUteProt() != null && castOther.getUteProt() != null && this
						.getUteProt().equals(castOther.getUteProt())))
				&& ((this.getUoAss() == castOther.getUoAss()) || (this
						.getUoAss() != null && castOther.getUoAss() != null && this
						.getUoAss().equals(castOther.getUoAss())))
				&& ((this.getNumCopia() == castOther.getNumCopia()) || (this
						.getNumCopia() != null
						&& castOther.getNumCopia() != null && this
						.getNumCopia().equals(castOther.getNumCopia())))
				&& ((this.getFlgCc() == castOther.getFlgCc()) || (this
						.getFlgCc() != null && castOther.getFlgCc() != null && this
						.getFlgCc().equals(castOther.getFlgCc())))
				&& ((this.getMittenti() == castOther.getMittenti()) || (this
						.getMittenti() != null
						&& castOther.getMittenti() != null && this
						.getMittenti().equals(castOther.getMittenti())))
				&& ((this.getDestinatari() == castOther.getDestinatari()) || (this
						.getDestinatari() != null
						&& castOther.getDestinatari() != null && this
						.getDestinatari().equals(castOther.getDestinatari())))
				&& ((this.getLivello4() == castOther.getLivello4()) || (this
						.getLivello4() != null
						&& castOther.getLivello4() != null && this
						.getLivello4().equals(castOther.getLivello4())))
				&& ((this.getLivello5() == castOther.getLivello5()) || (this
						.getLivello5() != null
						&& castOther.getLivello5() != null && this
						.getLivello5().equals(castOther.getLivello5())))
				&& ((this.getAnnullato() == castOther.getAnnullato()) || (this
						.getAnnullato() != null
						&& castOther.getAnnullato() != null && this
						.getAnnullato().equals(castOther.getAnnullato())))
				&& ((this.getClassif() == castOther.getClassif()) || (this
						.getClassif() != null && castOther.getClassif() != null && this
						.getClassif().equals(castOther.getClassif())))
				&& ((this.getTpPtg() == castOther.getTpPtg()) || (this
						.getTpPtg() != null && castOther.getTpPtg() != null && this
						.getTpPtg().equals(castOther.getTpPtg())))
				&& ((this.getDocricevuto() == castOther.getDocricevuto()) || (this
						.getDocricevuto() != null
						&& castOther.getDocricevuto() != null && this
						.getDocricevuto().equals(castOther.getDocricevuto())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getAnnoPtg() == null ? 0 : this.getAnnoPtg().hashCode());
		result = 37 * result
				+ (getNumPtg() == null ? 0 : this.getNumPtg().hashCode());
		result = 37 * result
				+ (getDtProt() == null ? 0 : this.getDtProt().hashCode());
		result = 37 * result
				+ (getCodEnte() == null ? 0 : this.getCodEnte().hashCode());
		result = 37 * result
				+ (getDtProv() == null ? 0 : this.getDtProv().hashCode());
		result = 37 * result
				+ (getProtProv() == null ? 0 : this.getProtProv().hashCode());
		result = 37
				* result
				+ (getTpRegEmerg() == null ? 0 : this.getTpRegEmerg()
						.hashCode());
		result = 37
				* result
				+ (getAnnoRegEmerg() == null ? 0 : this.getAnnoRegEmerg()
						.hashCode());
		result = 37
				* result
				+ (getNumRegEmerg() == null ? 0 : this.getNumRegEmerg()
						.hashCode());
		result = 37 * result
				+ (getIdDoc() == null ? 0 : this.getIdDoc().hashCode());
		result = 37 * result
				+ (getFlgTpProt() == null ? 0 : this.getFlgTpProt().hashCode());
		result = 37 * result
				+ (getIdIndice() == null ? 0 : this.getIdIndice().hashCode());
		result = 37
				* result
				+ (getIdFascicolo() == null ? 0 : this.getIdFascicolo()
						.hashCode());
		result = 37
				* result
				+ (getNumSottofasc() == null ? 0 : this.getNumSottofasc()
						.hashCode());
		result = 37 * result
				+ (getTitolo() == null ? 0 : this.getTitolo().hashCode());
		result = 37 * result
				+ (getClasse() == null ? 0 : this.getClasse().hashCode());
		result = 37
				* result
				+ (getSottoclasse() == null ? 0 : this.getSottoclasse()
						.hashCode());
		result = 37 * result
				+ (getAnno() == null ? 0 : this.getAnno().hashCode());
		result = 37 * result
				+ (getProgrFasc() == null ? 0 : this.getProgrFasc().hashCode());
		result = 37 * result
				+ (getRifProv() == null ? 0 : this.getRifProv().hashCode());
		result = 37 * result
				+ (getTxtOgg() == null ? 0 : this.getTxtOgg().hashCode());
		result = 37 * result
				+ (getNroAlleg() == null ? 0 : this.getNroAlleg().hashCode());
		result = 37 * result
				+ (getUoSped() == null ? 0 : this.getUoSped().hashCode());
		result = 37 * result
				+ (getUteProt() == null ? 0 : this.getUteProt().hashCode());
		result = 37 * result
				+ (getUoAss() == null ? 0 : this.getUoAss().hashCode());
		result = 37 * result
				+ (getNumCopia() == null ? 0 : this.getNumCopia().hashCode());
		result = 37 * result
				+ (getFlgCc() == null ? 0 : this.getFlgCc().hashCode());
		result = 37 * result
				+ (getMittenti() == null ? 0 : this.getMittenti().hashCode());
		result = 37
				* result
				+ (getDestinatari() == null ? 0 : this.getDestinatari()
						.hashCode());
		result = 37 * result
				+ (getLivello4() == null ? 0 : this.getLivello4().hashCode());
		result = 37 * result
				+ (getLivello5() == null ? 0 : this.getLivello5().hashCode());
		result = 37 * result
				+ (getAnnullato() == null ? 0 : this.getAnnullato().hashCode());
		result = 37 * result
				+ (getClassif() == null ? 0 : this.getClassif().hashCode());
		result = 37 * result
				+ (getTpPtg() == null ? 0 : this.getTpPtg().hashCode());
		result = 37
				* result
				+ (getDocricevuto() == null ? 0 : this.getDocricevuto()
						.hashCode());
		return result;
	}

}
