/* * SPDX-License-Identifier: AGPL-3.0-or-later * * C Copyright 2023 Regione Piemonte * */

// Generated 22-set-2016 12.14.09 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * PtvUoPostEgr generated by hbm2java
 */
@Entity
@Table(name = "PTV_UO_POST_EGR")
public class PtvUoPostEgr implements java.io.Serializable {

	private PtvUoPostEgrId id;

	public PtvUoPostEgr() {
	}

	public PtvUoPostEgr(PtvUoPostEgrId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "idUo", column = @Column(name = "ID_UO", precision = 8, scale = 0)),
			@AttributeOverride(name = "livelli", column = @Column(name = "LIVELLI", length = 204)),
			@AttributeOverride(name = "descrizione", column = @Column(name = "DESCRIZIONE", length = 303)),
			@AttributeOverride(name = "ordine", column = @Column(name = "ORDINE", length = 25)),
			@AttributeOverride(name = "dtInizioVld", column = @Column(name = "DT_INIZIO_VLD", length = 7)),
			@AttributeOverride(name = "dtFineVld", column = @Column(name = "DT_FINE_VLD", length = 7)) })
	public PtvUoPostEgrId getId() {
		return this.id;
	}

	public void setId(PtvUoPostEgrId id) {
		this.id = id;
	}

}
