/* * SPDX-License-Identifier: AGPL-3.0-or-later * * C Copyright 2023 Regione Piemonte * */

// Generated 29-mar-2012 15.55.01 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Storages generated by hbm2java
 */
@Entity
@Table(name = "storages")
public class Storages implements java.io.Serializable {

	private String idStorage;
	private String tipoStorage;
	private String xmlConfig;
	private Boolean flgDisattivo;
	private Set<UtilizzatoriStorageH> utilizzatoriStorageHs = new HashSet<UtilizzatoriStorageH>(
			0);
	private Set<UtilizzatoriStorage> utilizzatoriStorages = new HashSet<UtilizzatoriStorage>(
			0);

	public Storages() {
	}

	public Storages(String idStorage, String tipoStorage, String xmlConfig,
			Boolean flgDisattivo) {
		this.idStorage = idStorage;
		this.tipoStorage = tipoStorage;
		this.xmlConfig = xmlConfig;
		this.flgDisattivo = flgDisattivo;
	}

	public Storages(String idStorage, String tipoStorage, String xmlConfig,
			Boolean flgDisattivo,
			Set<UtilizzatoriStorageH> utilizzatoriStorageHs,
			Set<UtilizzatoriStorage> utilizzatoriStorages) {
		this.idStorage = idStorage;
		this.tipoStorage = tipoStorage;
		this.xmlConfig = xmlConfig;
		this.flgDisattivo = flgDisattivo;
		this.utilizzatoriStorageHs = utilizzatoriStorageHs;
		this.utilizzatoriStorages = utilizzatoriStorages;
	}

	@Id
	@Column(name = "id_storage", unique = true, nullable = false, length = 50)
	public String getIdStorage() {
		return this.idStorage;
	}

	public void setIdStorage(String idStorage) {
		this.idStorage = idStorage;
	}

	@Column(name = "tipo_storage", nullable = false, length = 20)
	public String getTipoStorage() {
		return this.tipoStorage;
	}

	public void setTipoStorage(String tipoStorage) {
		this.tipoStorage = tipoStorage;
	}

	@Column(name = "xml_config", nullable = false, length = 2000)
	public String getXmlConfig() {
		return this.xmlConfig;
	}

	public void setXmlConfig(String xmlConfig) {
		this.xmlConfig = xmlConfig;
	}

	@Column(name = "flg_disattivo", precision = 1, scale = 0)
	public Boolean getFlgDisattivo() {
		return this.flgDisattivo;
	}

	public void setFlgDisattivo(Boolean flgDisattivo) {
		this.flgDisattivo = flgDisattivo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "storages")
	public Set<UtilizzatoriStorageH> getUtilizzatoriStorageHs() {
		return this.utilizzatoriStorageHs;
	}

	public void setUtilizzatoriStorageHs(
			Set<UtilizzatoriStorageH> utilizzatoriStorageHs) {
		this.utilizzatoriStorageHs = utilizzatoriStorageHs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "storages")
	public Set<UtilizzatoriStorage> getUtilizzatoriStorages() {
		return this.utilizzatoriStorages;
	}

	public void setUtilizzatoriStorages(
			Set<UtilizzatoriStorage> utilizzatoriStorages) {
		this.utilizzatoriStorages = utilizzatoriStorages;
	}

}
