/* * SPDX-License-Identifier: AGPL-3.0-or-later * * C Copyright 2023 Regione Piemonte * */

// Generated 29-mar-2012 15.55.01 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * UtilizzatoriStorage generated by hbm2java
 */
@Entity
@Table(name = "utilizzatori_storage")
public class UtilizzatoriStorage implements java.io.Serializable {

	private String idUtilizzatore;
	private Storages storages;

	public UtilizzatoriStorage() {
	}

	public UtilizzatoriStorage(String idUtilizzatore, Storages storages) {
		this.idUtilizzatore = idUtilizzatore;
		this.storages = storages;
	}

	@Id
	@Column(name = "id_utilizzatore", unique = true, nullable = false, length = 150)
	public String getIdUtilizzatore() {
		return this.idUtilizzatore;
	}

	public void setIdUtilizzatore(String idUtilizzatore) {
		this.idUtilizzatore = idUtilizzatore;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_storage", nullable = false)
	public Storages getStorages() {
		return this.storages;
	}

	public void setStorages(Storages storages) {
		this.storages = storages;
	}

}
