/* * SPDX-License-Identifier: AGPL-3.0-or-later * * C Copyright 2023 Regione Piemonte * */
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-b10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.10.06 at 11:51:24 PM CEST 
//


package it.eng.auriga.repository2.jaxws.webservices.determina;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="Determina">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="IDProposta">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Numero">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}positiveInteger">
 *                                   &lt;totalDigits value="7"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                             &lt;element name="TsRegistrazione" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *                             &lt;element name="Autore" type="{}AutoreType"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="IDAttoDefinitivo" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Numero">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}positiveInteger">
 *                                   &lt;totalDigits value="7"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                             &lt;element name="TsRegistrazione" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="RifAttiPrecedenti" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="OggettoPubbl">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="CIG" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;element name="ConRilevanzaContabile">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;enumeration value="SI"/>
 *                         &lt;enumeration value="NO"/>
 *                         &lt;enumeration value="SI, SENZA VALIDAZIONE/RILASCIO IMPEGNI"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="RegContSuParteCorrente" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                   &lt;element name="RegContInContoCapitale" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                   &lt;element name="Specificita" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;enumeration value="a contrarre tramite gara "/>
 *                         &lt;enumeration value="aggiudicazione di gara"/>
 *                         &lt;enumeration value="rimodulazione spesa gara aggiudicata"/>
 *                         &lt;enumeration value="spese di personale"/>
 *                         &lt;enumeration value="riaccertamento"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="StrutturaProponente" type="{}StrutturaType"/>
 *                   &lt;element name="Adottante" type="{}FirmatarioType"/>
 *                   &lt;element name="ResponsabiliDiConcerto" type="{}FirmatarioType" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;element name="ResponsabiliPEG" type="{}FirmatarioType" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;element name="RdP" type="{}FirmatarioType"/>
 *                   &lt;element name="RUP" type="{}FirmatarioType" minOccurs="0"/>
 *                   &lt;element name="PreverificaRagioneria" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="TsInizio" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *                             &lt;element name="TsCompletamento" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *                             &lt;element name="TipoEsito" minOccurs="0">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                   &lt;enumeration value="OK"/>
 *                                   &lt;enumeration value="KO"/>
 *                                   &lt;enumeration value="W"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="VistoRegolaritaContabile" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="TsRilascio" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *                             &lt;element name="Firmatario" type="{}FirmatarioRestrictedType"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="Pubblicazione" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="DataInizio" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *                             &lt;element name="DataTermine" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="AttachmentFiles" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="File" maxOccurs="unbounded" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="DisplayFilename" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="TipoologiaDoc" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                                       &lt;element name="Descrizione" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *                                       &lt;element name="Dimensione" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
 *                                       &lt;element name="Digest">
 *                                         &lt;complexType>
 *                                           &lt;simpleContent>
 *                                             &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                                               &lt;attribute name="algoritmo" use="required">
 *                                                 &lt;simpleType>
 *                                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                                     &lt;enumeration value="SHA-1"/>
 *                                                     &lt;enumeration value="SHA-256"/>
 *                                                   &lt;/restriction>
 *                                                 &lt;/simpleType>
 *                                               &lt;/attribute>
 *                                               &lt;attribute name="encoding">
 *                                                 &lt;simpleType>
 *                                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                                     &lt;enumeration value="hex"/>
 *                                                     &lt;enumeration value="base64"/>
 *                                                   &lt;/restriction>
 *                                                 &lt;/simpleType>
 *                                               &lt;/attribute>
 *                                             &lt;/extension>
 *                                           &lt;/simpleContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                       &lt;element name="Mimetype" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="Firmato">
 *                                         &lt;complexType>
 *                                           &lt;simpleContent>
 *                                             &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>boolean">
 *                                               &lt;attribute name="tipoFirma">
 *                                                 &lt;simpleType>
 *                                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                                     &lt;pattern value="CAdES"/>
 *                                                     &lt;pattern value="PAdES"/>
 *                                                     &lt;pattern value="XAdES"/>
 *                                                   &lt;/restriction>
 *                                                 &lt;/simpleType>
 *                                               &lt;/attribute>
 *                                             &lt;/extension>
 *                                           &lt;/simpleContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                     &lt;/sequence>
 *                                     &lt;attribute name="nroAttachment" use="required" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
 *                                     &lt;attribute name="rappresenta" use="required">
 *                                       &lt;simpleType>
 *                                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                           &lt;enumeration value="dispositivo"/>
 *                                           &lt;enumeration value="visto_reg_contabile"/>
 *                                           &lt;enumeration value="allegato_parte_integrante"/>
 *                                           &lt;enumeration value="allegato_non_parte_integrante"/>
 *                                         &lt;/restriction>
 *                                       &lt;/simpleType>
 *                                     &lt;/attribute>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="ErrorMessage">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                 &lt;attribute name="codice" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/choice>
 *       &lt;attribute name="esitoRequest" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="OK"/>
 *             &lt;enumeration value="KO"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "determina",
    "errorMessage"
})
@XmlRootElement(name = "ResponseGetDetermina")
public class ResponseGetDetermina implements java.io.Serializable {

    @XmlElement(name = "Determina")
    public ResponseGetDetermina.Determina determina;
    @XmlElement(name = "ErrorMessage")
    protected ResponseGetDetermina.ErrorMessage errorMessage;
    @XmlAttribute(name = "esitoRequest", required = true)
    protected String esitoRequest;

    /**
     * Gets the value of the determina property.
     * 
     * @return
     *     possible object is
     *     {@link ResponseGetDetermina.Determina }
     *     
     */
   /* public ResponseGetDetermina.Determina getDetermina() {
        return determina;
    }*/

    /**
     * Sets the value of the determina property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResponseGetDetermina.Determina }
     *     
     */
    /*public void setDetermina(ResponseGetDetermina.Determina value) {
        this.determina = value;
    }*/
     
    /**
     * Gets the value of the errorMessage property.
     * 
     * @return
     *     possible object is
     *     {@link ResponseGetDetermina.ErrorMessage }
     *     
     */
    public ResponseGetDetermina.ErrorMessage getErrorMessage() {
        return errorMessage;
    }

    

	public ResponseGetDetermina.Determina getDetermina() {
		return determina;
	}



	public void setDetermina(ResponseGetDetermina.Determina determina) {
		this.determina = determina;
	}



	/**
     * Sets the value of the errorMessage property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResponseGetDetermina.ErrorMessage }
     *     
     */
    public void setErrorMessage(ResponseGetDetermina.ErrorMessage value) {
        this.errorMessage = value;
    }

    /**
     * Gets the value of the esitoRequest property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEsitoRequest() {
        return esitoRequest;
    }

    /**
     * Sets the value of the esitoRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEsitoRequest(String value) {
        this.esitoRequest = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="IDProposta">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Numero">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}positiveInteger">
     *                         &lt;totalDigits value="7"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="TsRegistrazione" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
     *                   &lt;element name="Autore" type="{}AutoreType"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="IDAttoDefinitivo" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Numero">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}positiveInteger">
     *                         &lt;totalDigits value="7"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="TsRegistrazione" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="RifAttiPrecedenti" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="OggettoPubbl">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="CIG" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
     *         &lt;element name="ConRilevanzaContabile">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;enumeration value="SI"/>
     *               &lt;enumeration value="NO"/>
     *               &lt;enumeration value="SI, SENZA VALIDAZIONE/RILASCIO IMPEGNI"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="RegContSuParteCorrente" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *         &lt;element name="RegContInContoCapitale" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *         &lt;element name="Specificita" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;enumeration value="a contrarre tramite gara "/>
     *               &lt;enumeration value="aggiudicazione di gara"/>
     *               &lt;enumeration value="rimodulazione spesa gara aggiudicata"/>
     *               &lt;enumeration value="spese di personale"/>
     *               &lt;enumeration value="riaccertamento"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="StrutturaProponente" type="{}StrutturaType"/>
     *         &lt;element name="Adottante" type="{}FirmatarioType"/>
     *         &lt;element name="ResponsabiliDiConcerto" type="{}FirmatarioType" maxOccurs="unbounded" minOccurs="0"/>
     *         &lt;element name="ResponsabiliPEG" type="{}FirmatarioType" maxOccurs="unbounded" minOccurs="0"/>
     *         &lt;element name="RdP" type="{}FirmatarioType"/>
     *         &lt;element name="RUP" type="{}FirmatarioType" minOccurs="0"/>
     *         &lt;element name="PreverificaRagioneria" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="TsInizio" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
     *                   &lt;element name="TsCompletamento" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
     *                   &lt;element name="TipoEsito" minOccurs="0">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;enumeration value="OK"/>
     *                         &lt;enumeration value="KO"/>
     *                         &lt;enumeration value="W"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="VistoRegolaritaContabile" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="TsRilascio" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
     *                   &lt;element name="Firmatario" type="{}FirmatarioRestrictedType"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="Pubblicazione" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="DataInizio" type="{http://www.w3.org/2001/XMLSchema}date"/>
     *                   &lt;element name="DataTermine" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="AttachmentFiles" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="File" maxOccurs="unbounded" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="DisplayFilename" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="TipoologiaDoc" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                             &lt;element name="Descrizione" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
     *                             &lt;element name="Dimensione" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
     *                             &lt;element name="Digest">
     *                               &lt;complexType>
     *                                 &lt;simpleContent>
     *                                   &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                                     &lt;attribute name="algoritmo" use="required">
     *                                       &lt;simpleType>
     *                                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                                           &lt;enumeration value="SHA-1"/>
     *                                           &lt;enumeration value="SHA-256"/>
     *                                         &lt;/restriction>
     *                                       &lt;/simpleType>
     *                                     &lt;/attribute>
     *                                     &lt;attribute name="encoding">
     *                                       &lt;simpleType>
     *                                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                                           &lt;enumeration value="hex"/>
     *                                           &lt;enumeration value="base64"/>
     *                                         &lt;/restriction>
     *                                       &lt;/simpleType>
     *                                     &lt;/attribute>
     *                                   &lt;/extension>
     *                                 &lt;/simpleContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                             &lt;element name="Mimetype" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="Firmato">
     *                               &lt;complexType>
     *                                 &lt;simpleContent>
     *                                   &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>boolean">
     *                                     &lt;attribute name="tipoFirma">
     *                                       &lt;simpleType>
     *                                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                                           &lt;pattern value="CAdES"/>
     *                                           &lt;pattern value="PAdES"/>
     *                                           &lt;pattern value="XAdES"/>
     *                                         &lt;/restriction>
     *                                       &lt;/simpleType>
     *                                     &lt;/attribute>
     *                                   &lt;/extension>
     *                                 &lt;/simpleContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                           &lt;/sequence>
     *                           &lt;attribute name="nroAttachment" use="required" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
     *                           &lt;attribute name="rappresenta" use="required">
     *                             &lt;simpleType>
     *                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                                 &lt;enumeration value="dispositivo"/>
     *                                 &lt;enumeration value="visto_reg_contabile"/>
     *                                 &lt;enumeration value="allegato_parte_integrante"/>
     *                                 &lt;enumeration value="allegato_non_parte_integrante"/>
     *                               &lt;/restriction>
     *                             &lt;/simpleType>
     *                           &lt;/attribute>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "idProposta",
        "idAttoDefinitivo",
        "rifAttiPrecedenti",
        "oggettoPubbl",
        "cig",
        "conRilevanzaContabile",
        "regContSuParteCorrente",
        "regContInContoCapitale",
        "specificita",
        "strutturaProponente",
        "adottante",
        "responsabiliDiConcerto",
        "responsabiliPEG",
        "rdP",
        "rup",
        "preverificaRagioneria",
        "vistoRegolaritaContabile",
        "pubblicazione",
        "attachmentFiles"
    })
    public static class Determina  {

        @XmlElement(name = "IDProposta", required = true)
        protected ResponseGetDetermina.Determina.IDProposta idProposta;
        @XmlElement(name = "IDAttoDefinitivo")
        protected ResponseGetDetermina.Determina.IDAttoDefinitivo idAttoDefinitivo;
        @XmlElement(name = "RifAttiPrecedenti")
        protected String rifAttiPrecedenti;
        @XmlElement(name = "OggettoPubbl", required = true)
        protected String oggettoPubbl;
        @XmlElement(name = "CIG")
        protected List<String> cig;
        @XmlElement(name = "ConRilevanzaContabile", required = true)
        protected String conRilevanzaContabile;
        @XmlElement(name = "RegContSuParteCorrente")
        protected boolean regContSuParteCorrente;
        @XmlElement(name = "RegContInContoCapitale")
        protected boolean regContInContoCapitale;
        @XmlElement(name = "Specificita")
        protected String specificita;
        @XmlElement(name = "StrutturaProponente", required = true)
        protected StrutturaType strutturaProponente;
        @XmlElement(name = "Adottante", required = true)
        protected FirmatarioType adottante;
        @XmlElement(name = "ResponsabiliDiConcerto")
        protected List<FirmatarioType> responsabiliDiConcerto;
        @XmlElement(name = "ResponsabiliPEG")
        protected List<FirmatarioType> responsabiliPEG;
        @XmlElement(name = "RdP", required = true)
        protected FirmatarioType rdP;
        @XmlElement(name = "RUP")
        protected FirmatarioType rup;
        @XmlElement(name = "PreverificaRagioneria")
        protected ResponseGetDetermina.Determina.PreverificaRagioneria preverificaRagioneria;
        @XmlElement(name = "VistoRegolaritaContabile")
        protected ResponseGetDetermina.Determina.VistoRegolaritaContabile vistoRegolaritaContabile;
        @XmlElement(name = "Pubblicazione")
        protected ResponseGetDetermina.Determina.Pubblicazione pubblicazione;
        @XmlElement(name = "AttachmentFiles")
        protected ResponseGetDetermina.Determina.AttachmentFiles attachmentFiles;

        /**
         * Gets the value of the idProposta property.
         * 
         * @return
         *     possible object is
         *     {@link ResponseGetDetermina.Determina.IDProposta }
         *     
         */
        public ResponseGetDetermina.Determina.IDProposta getIDProposta() {
            return idProposta;
        }

        /**
         * Sets the value of the idProposta property.
         * 
         * @param value
         *     allowed object is
         *     {@link ResponseGetDetermina.Determina.IDProposta }
         *     
         */
        public void setIDProposta(ResponseGetDetermina.Determina.IDProposta value) {
            this.idProposta = value;
        }

        /**
         * Gets the value of the idAttoDefinitivo property.
         * 
         * @return
         *     possible object is
         *     {@link ResponseGetDetermina.Determina.IDAttoDefinitivo }
         *     
         */
        public ResponseGetDetermina.Determina.IDAttoDefinitivo getIDAttoDefinitivo() {
            return idAttoDefinitivo;
        }

        /**
         * Sets the value of the idAttoDefinitivo property.
         * 
         * @param value
         *     allowed object is
         *     {@link ResponseGetDetermina.Determina.IDAttoDefinitivo }
         *     
         */
        public void setIDAttoDefinitivo(ResponseGetDetermina.Determina.IDAttoDefinitivo value) {
            this.idAttoDefinitivo = value;
        }

        /**
         * Gets the value of the rifAttiPrecedenti property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRifAttiPrecedenti() {
            return rifAttiPrecedenti;
        }

        /**
         * Sets the value of the rifAttiPrecedenti property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRifAttiPrecedenti(String value) {
            this.rifAttiPrecedenti = value;
        }

        /**
         * Gets the value of the oggettoPubbl property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOggettoPubbl() {
            return oggettoPubbl;
        }

        /**
         * Sets the value of the oggettoPubbl property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOggettoPubbl(String value) {
            this.oggettoPubbl = value;
        }

        /**
         * Gets the value of the cig property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the cig property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getCIG().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getCIG() {
            if (cig == null) {
                cig = new ArrayList<String>();
            }
            return this.cig;
        }

        /**
         * Gets the value of the conRilevanzaContabile property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getConRilevanzaContabile() {
            return conRilevanzaContabile;
        }

        /**
         * Sets the value of the conRilevanzaContabile property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setConRilevanzaContabile(String value) {
            this.conRilevanzaContabile = value;
        }

        /**
         * Gets the value of the regContSuParteCorrente property.
         * 
         */
        public boolean isRegContSuParteCorrente() {
            return regContSuParteCorrente;
        }

        /**
         * Sets the value of the regContSuParteCorrente property.
         * 
         */
        public void setRegContSuParteCorrente(boolean value) {
            this.regContSuParteCorrente = value;
        }

        /**
         * Gets the value of the regContInContoCapitale property.
         * 
         */
        public boolean isRegContInContoCapitale() {
            return regContInContoCapitale;
        }

        /**
         * Sets the value of the regContInContoCapitale property.
         * 
         */
        public void setRegContInContoCapitale(boolean value) {
            this.regContInContoCapitale = value;
        }

        /**
         * Gets the value of the specificita property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSpecificita() {
            return specificita;
        }

        /**
         * Sets the value of the specificita property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSpecificita(String value) {
            this.specificita = value;
        }

        /**
         * Gets the value of the strutturaProponente property.
         * 
         * @return
         *     possible object is
         *     {@link StrutturaType }
         *     
         */
        public StrutturaType getStrutturaProponente() {
            return strutturaProponente;
        }

        /**
         * Sets the value of the strutturaProponente property.
         * 
         * @param value
         *     allowed object is
         *     {@link StrutturaType }
         *     
         */
        public void setStrutturaProponente(StrutturaType value) {
            this.strutturaProponente = value;
        }

        /**
         * Gets the value of the adottante property.
         * 
         * @return
         *     possible object is
         *     {@link FirmatarioType }
         *     
         */
        public FirmatarioType getAdottante() {
            return adottante;
        }

        /**
         * Sets the value of the adottante property.
         * 
         * @param value
         *     allowed object is
         *     {@link FirmatarioType }
         *     
         */
        public void setAdottante(FirmatarioType value) {
            this.adottante = value;
        }

        /**
         * Gets the value of the responsabiliDiConcerto property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the responsabiliDiConcerto property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getResponsabiliDiConcerto().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link FirmatarioType }
         * 
         * 
         */
        public List<FirmatarioType> getResponsabiliDiConcerto() {
            if (responsabiliDiConcerto == null) {
                responsabiliDiConcerto = new ArrayList<FirmatarioType>();
            }
            return this.responsabiliDiConcerto;
        }

        /**
         * Gets the value of the responsabiliPEG property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the responsabiliPEG property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getResponsabiliPEG().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link FirmatarioType }
         * 
         * 
         */
        public List<FirmatarioType> getResponsabiliPEG() {
            if (responsabiliPEG == null) {
                responsabiliPEG = new ArrayList<FirmatarioType>();
            }
            return this.responsabiliPEG;
        }

        /**
         * Gets the value of the rdP property.
         * 
         * @return
         *     possible object is
         *     {@link FirmatarioType }
         *     
         */
        public FirmatarioType getRdP() {
            return rdP;
        }

        /**
         * Sets the value of the rdP property.
         * 
         * @param value
         *     allowed object is
         *     {@link FirmatarioType }
         *     
         */
        public void setRdP(FirmatarioType value) {
            this.rdP = value;
        }

        /**
         * Gets the value of the rup property.
         * 
         * @return
         *     possible object is
         *     {@link FirmatarioType }
         *     
         */
        public FirmatarioType getRUP() {
            return rup;
        }

        /**
         * Sets the value of the rup property.
         * 
         * @param value
         *     allowed object is
         *     {@link FirmatarioType }
         *     
         */
        public void setRUP(FirmatarioType value) {
            this.rup = value;
        }

        /**
         * Gets the value of the preverificaRagioneria property.
         * 
         * @return
         *     possible object is
         *     {@link ResponseGetDetermina.Determina.PreverificaRagioneria }
         *     
         */
        public ResponseGetDetermina.Determina.PreverificaRagioneria getPreverificaRagioneria() {
            return preverificaRagioneria;
        }

        /**
         * Sets the value of the preverificaRagioneria property.
         * 
         * @param value
         *     allowed object is
         *     {@link ResponseGetDetermina.Determina.PreverificaRagioneria }
         *     
         */
        public void setPreverificaRagioneria(ResponseGetDetermina.Determina.PreverificaRagioneria value) {
            this.preverificaRagioneria = value;
        }

        /**
         * Gets the value of the vistoRegolaritaContabile property.
         * 
         * @return
         *     possible object is
         *     {@link ResponseGetDetermina.Determina.VistoRegolaritaContabile }
         *     
         */
        public ResponseGetDetermina.Determina.VistoRegolaritaContabile getVistoRegolaritaContabile() {
            return vistoRegolaritaContabile;
        }

        /**
         * Sets the value of the vistoRegolaritaContabile property.
         * 
         * @param value
         *     allowed object is
         *     {@link ResponseGetDetermina.Determina.VistoRegolaritaContabile }
         *     
         */
        public void setVistoRegolaritaContabile(ResponseGetDetermina.Determina.VistoRegolaritaContabile value) {
            this.vistoRegolaritaContabile = value;
        }

        /**
         * Gets the value of the pubblicazione property.
         * 
         * @return
         *     possible object is
         *     {@link ResponseGetDetermina.Determina.Pubblicazione }
         *     
         */
        public ResponseGetDetermina.Determina.Pubblicazione getPubblicazione() {
            return pubblicazione;
        }

        /**
         * Sets the value of the pubblicazione property.
         * 
         * @param value
         *     allowed object is
         *     {@link ResponseGetDetermina.Determina.Pubblicazione }
         *     
         */
        public void setPubblicazione(ResponseGetDetermina.Determina.Pubblicazione value) {
            this.pubblicazione = value;
        }

        /**
         * Gets the value of the attachmentFiles property.
         * 
         * @return
         *     possible object is
         *     {@link ResponseGetDetermina.Determina.AttachmentFiles }
         *     
         */
        public ResponseGetDetermina.Determina.AttachmentFiles getAttachmentFiles() {
            return attachmentFiles;
        }

        /**
         * Sets the value of the attachmentFiles property.
         * 
         * @param value
         *     allowed object is
         *     {@link ResponseGetDetermina.Determina.AttachmentFiles }
         *     
         */
        public void setAttachmentFiles(ResponseGetDetermina.Determina.AttachmentFiles value) {
            this.attachmentFiles = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="File" maxOccurs="unbounded" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="DisplayFilename" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="TipoologiaDoc" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *                   &lt;element name="Descrizione" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
         *                   &lt;element name="Dimensione" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
         *                   &lt;element name="Digest">
         *                     &lt;complexType>
         *                       &lt;simpleContent>
         *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *                           &lt;attribute name="algoritmo" use="required">
         *                             &lt;simpleType>
         *                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *                                 &lt;enumeration value="SHA-1"/>
         *                                 &lt;enumeration value="SHA-256"/>
         *                               &lt;/restriction>
         *                             &lt;/simpleType>
         *                           &lt;/attribute>
         *                           &lt;attribute name="encoding">
         *                             &lt;simpleType>
         *                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *                                 &lt;enumeration value="hex"/>
         *                                 &lt;enumeration value="base64"/>
         *                               &lt;/restriction>
         *                             &lt;/simpleType>
         *                           &lt;/attribute>
         *                         &lt;/extension>
         *                       &lt;/simpleContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                   &lt;element name="Mimetype" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="Firmato">
         *                     &lt;complexType>
         *                       &lt;simpleContent>
         *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>boolean">
         *                           &lt;attribute name="tipoFirma">
         *                             &lt;simpleType>
         *                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *                                 &lt;pattern value="CAdES"/>
         *                                 &lt;pattern value="PAdES"/>
         *                                 &lt;pattern value="XAdES"/>
         *                               &lt;/restriction>
         *                             &lt;/simpleType>
         *                           &lt;/attribute>
         *                         &lt;/extension>
         *                       &lt;/simpleContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                 &lt;/sequence>
         *                 &lt;attribute name="nroAttachment" use="required" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
         *                 &lt;attribute name="rappresenta" use="required">
         *                   &lt;simpleType>
         *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *                       &lt;enumeration value="dispositivo"/>
         *                       &lt;enumeration value="visto_reg_contabile"/>
         *                       &lt;enumeration value="allegato_parte_integrante"/>
         *                       &lt;enumeration value="allegato_non_parte_integrante"/>
         *                     &lt;/restriction>
         *                   &lt;/simpleType>
         *                 &lt;/attribute>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "file"
        })
        public static class AttachmentFiles {

            @XmlElement(name = "File")
            protected List<ResponseGetDetermina.Determina.AttachmentFiles.File> file;

            /**
             * Gets the value of the file property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the file property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getFile().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link ResponseGetDetermina.Determina.AttachmentFiles.File }
             * 
             * 
             */
            public List<ResponseGetDetermina.Determina.AttachmentFiles.File> getFile() {
                if (file == null) {
                    file = new ArrayList<ResponseGetDetermina.Determina.AttachmentFiles.File>();
                }
                return this.file;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="DisplayFilename" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="TipoologiaDoc" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
             *         &lt;element name="Descrizione" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
             *         &lt;element name="Dimensione" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
             *         &lt;element name="Digest">
             *           &lt;complexType>
             *             &lt;simpleContent>
             *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
             *                 &lt;attribute name="algoritmo" use="required">
             *                   &lt;simpleType>
             *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
             *                       &lt;enumeration value="SHA-1"/>
             *                       &lt;enumeration value="SHA-256"/>
             *                     &lt;/restriction>
             *                   &lt;/simpleType>
             *                 &lt;/attribute>
             *                 &lt;attribute name="encoding">
             *                   &lt;simpleType>
             *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
             *                       &lt;enumeration value="hex"/>
             *                       &lt;enumeration value="base64"/>
             *                     &lt;/restriction>
             *                   &lt;/simpleType>
             *                 &lt;/attribute>
             *               &lt;/extension>
             *             &lt;/simpleContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *         &lt;element name="Mimetype" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="Firmato">
             *           &lt;complexType>
             *             &lt;simpleContent>
             *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>boolean">
             *                 &lt;attribute name="tipoFirma">
             *                   &lt;simpleType>
             *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
             *                       &lt;pattern value="CAdES"/>
             *                       &lt;pattern value="PAdES"/>
             *                       &lt;pattern value="XAdES"/>
             *                     &lt;/restriction>
             *                   &lt;/simpleType>
             *                 &lt;/attribute>
             *               &lt;/extension>
             *             &lt;/simpleContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *       &lt;/sequence>
             *       &lt;attribute name="nroAttachment" use="required" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
             *       &lt;attribute name="rappresenta" use="required">
             *         &lt;simpleType>
             *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
             *             &lt;enumeration value="dispositivo"/>
             *             &lt;enumeration value="visto_reg_contabile"/>
             *             &lt;enumeration value="allegato_parte_integrante"/>
             *             &lt;enumeration value="allegato_non_parte_integrante"/>
             *           &lt;/restriction>
             *         &lt;/simpleType>
             *       &lt;/attribute>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "displayFilename",
                "tipoologiaDoc",
                "descrizione",
                "dimensione",
                "digest",
                "mimetype",
                "firmato"
            })
            public static class File {

                @XmlElement(name = "DisplayFilename", required = true)
                protected String displayFilename;
                @XmlElement(name = "TipoologiaDoc")
                protected String tipoologiaDoc;
                @XmlElement(name = "Descrizione")
                protected Object descrizione;
                @XmlElement(name = "Dimensione", required = true)
                @XmlSchemaType(name = "positiveInteger")
                protected BigInteger dimensione;
                @XmlElement(name = "Digest", required = true)
                protected ResponseGetDetermina.Determina.AttachmentFiles.File.Digest digest;
                @XmlElement(name = "Mimetype", required = true)
                protected String mimetype;
                @XmlElement(name = "Firmato", required = true)
                protected ResponseGetDetermina.Determina.AttachmentFiles.File.Firmato firmato;
                @XmlAttribute(name = "nroAttachment", required = true)
                @XmlSchemaType(name = "positiveInteger")
                protected BigInteger nroAttachment;
                @XmlAttribute(name = "rappresenta", required = true)
                protected String rappresenta;

                /**
                 * Gets the value of the displayFilename property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getDisplayFilename() {
                    return displayFilename;
                }

                /**
                 * Sets the value of the displayFilename property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setDisplayFilename(String value) {
                    this.displayFilename = value;
                }

                /**
                 * Gets the value of the tipoologiaDoc property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getTipoologiaDoc() {
                    return tipoologiaDoc;
                }

                /**
                 * Sets the value of the tipoologiaDoc property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setTipoologiaDoc(String value) {
                    this.tipoologiaDoc = value;
                }

                /**
                 * Gets the value of the descrizione property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Object }
                 *     
                 */
                public Object getDescrizione() {
                    return descrizione;
                }

                /**
                 * Sets the value of the descrizione property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Object }
                 *     
                 */
                public void setDescrizione(Object value) {
                    this.descrizione = value;
                }

                /**
                 * Gets the value of the dimensione property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link BigInteger }
                 *     
                 */
                public BigInteger getDimensione() {
                    return dimensione;
                }

                /**
                 * Sets the value of the dimensione property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link BigInteger }
                 *     
                 */
                public void setDimensione(BigInteger value) {
                    this.dimensione = value;
                }

                /**
                 * Gets the value of the digest property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link ResponseGetDetermina.Determina.AttachmentFiles.File.Digest }
                 *     
                 */
                public ResponseGetDetermina.Determina.AttachmentFiles.File.Digest getDigest() {
                    return digest;
                }

                /**
                 * Sets the value of the digest property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link ResponseGetDetermina.Determina.AttachmentFiles.File.Digest }
                 *     
                 */
                public void setDigest(ResponseGetDetermina.Determina.AttachmentFiles.File.Digest value) {
                    this.digest = value;
                }

                /**
                 * Gets the value of the mimetype property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getMimetype() {
                    return mimetype;
                }

                /**
                 * Sets the value of the mimetype property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setMimetype(String value) {
                    this.mimetype = value;
                }

                /**
                 * Gets the value of the firmato property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link ResponseGetDetermina.Determina.AttachmentFiles.File.Firmato }
                 *     
                 */
                public ResponseGetDetermina.Determina.AttachmentFiles.File.Firmato getFirmato() {
                    return firmato;
                }

                /**
                 * Sets the value of the firmato property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link ResponseGetDetermina.Determina.AttachmentFiles.File.Firmato }
                 *     
                 */
                public void setFirmato(ResponseGetDetermina.Determina.AttachmentFiles.File.Firmato value) {
                    this.firmato = value;
                }

                /**
                 * Gets the value of the nroAttachment property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link BigInteger }
                 *     
                 */
                public BigInteger getNroAttachment() {
                    return nroAttachment;
                }

                /**
                 * Sets the value of the nroAttachment property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link BigInteger }
                 *     
                 */
                public void setNroAttachment(BigInteger value) {
                    this.nroAttachment = value;
                }

                /**
                 * Gets the value of the rappresenta property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getRappresenta() {
                    return rappresenta;
                }

                /**
                 * Sets the value of the rappresenta property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setRappresenta(String value) {
                    this.rappresenta = value;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;simpleContent>
                 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
                 *       &lt;attribute name="algoritmo" use="required">
                 *         &lt;simpleType>
                 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
                 *             &lt;enumeration value="SHA-1"/>
                 *             &lt;enumeration value="SHA-256"/>
                 *           &lt;/restriction>
                 *         &lt;/simpleType>
                 *       &lt;/attribute>
                 *       &lt;attribute name="encoding">
                 *         &lt;simpleType>
                 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
                 *             &lt;enumeration value="hex"/>
                 *             &lt;enumeration value="base64"/>
                 *           &lt;/restriction>
                 *         &lt;/simpleType>
                 *       &lt;/attribute>
                 *     &lt;/extension>
                 *   &lt;/simpleContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "value"
                })
                public static class Digest {

                    @XmlValue
                    protected String value;
                    @XmlAttribute(name = "algoritmo", required = true)
                    protected String algoritmo;
                    @XmlAttribute(name = "encoding")
                    protected String encoding;

                    /**
                     * Gets the value of the value property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getValue() {
                        return value;
                    }

                    /**
                     * Sets the value of the value property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setValue(String value) {
                        this.value = value;
                    }

                    /**
                     * Gets the value of the algoritmo property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getAlgoritmo() {
                        return algoritmo;
                    }

                    /**
                     * Sets the value of the algoritmo property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setAlgoritmo(String value) {
                        this.algoritmo = value;
                    }

                    /**
                     * Gets the value of the encoding property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getEncoding() {
                        return encoding;
                    }

                    /**
                     * Sets the value of the encoding property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setEncoding(String value) {
                        this.encoding = value;
                    }

                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;simpleContent>
                 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>boolean">
                 *       &lt;attribute name="tipoFirma">
                 *         &lt;simpleType>
                 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
                 *             &lt;pattern value="CAdES"/>
                 *             &lt;pattern value="PAdES"/>
                 *             &lt;pattern value="XAdES"/>
                 *           &lt;/restriction>
                 *         &lt;/simpleType>
                 *       &lt;/attribute>
                 *     &lt;/extension>
                 *   &lt;/simpleContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "value"
                })
                public static class Firmato {

                    @XmlValue
                    protected boolean value;
                    @XmlAttribute(name = "tipoFirma")
                    protected String tipoFirma;

                    /**
                     * Gets the value of the value property.
                     * 
                     */
                    public boolean isValue() {
                        return value;
                    }

                    /**
                     * Sets the value of the value property.
                     * 
                     */
                    public void setValue(boolean value) {
                        this.value = value;
                    }

                    /**
                     * Gets the value of the tipoFirma property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getTipoFirma() {
                        return tipoFirma;
                    }

                    /**
                     * Sets the value of the tipoFirma property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setTipoFirma(String value) {
                        this.tipoFirma = value;
                    }

                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Numero">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}positiveInteger">
         *               &lt;totalDigits value="7"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="TsRegistrazione" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "numero",
            "tsRegistrazione"
        })
        public static class IDAttoDefinitivo {

            @XmlElement(name = "Numero", required = true)
            protected BigInteger numero;
            @XmlElement(name = "TsRegistrazione", required = true)
            @XmlSchemaType(name = "dateTime")
            protected XMLGregorianCalendar tsRegistrazione;

            /**
             * Gets the value of the numero property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getNumero() {
                return numero;
            }

            /**
             * Sets the value of the numero property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setNumero(BigInteger value) {
                this.numero = value;
            }

            /**
             * Gets the value of the tsRegistrazione property.
             * 
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public XMLGregorianCalendar getTsRegistrazione() {
                return tsRegistrazione;
            }

            /**
             * Sets the value of the tsRegistrazione property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public void setTsRegistrazione(XMLGregorianCalendar value) {
                this.tsRegistrazione = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Numero">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}positiveInteger">
         *               &lt;totalDigits value="7"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="TsRegistrazione" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
         *         &lt;element name="Autore" type="{}AutoreType"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "numero",
            "tsRegistrazione",
            "autore"
        })
        public static class IDProposta {

            @XmlElement(name = "Numero", required = true)
            protected BigInteger numero;
            @XmlElement(name = "TsRegistrazione", required = true)
            @XmlSchemaType(name = "dateTime")
            protected XMLGregorianCalendar tsRegistrazione;
            @XmlElement(name = "Autore", required = true)
            public AutoreType autore;

            /**
             * Gets the value of the numero property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getNumero() {
                return numero;
            }

            /**
             * Sets the value of the numero property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setNumero(BigInteger value) {
                this.numero = value;
            }

            /**
             * Gets the value of the tsRegistrazione property.
             * 
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public XMLGregorianCalendar getTsRegistrazione() {
                return tsRegistrazione;
            }

            /**
             * Sets the value of the tsRegistrazione property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public void setTsRegistrazione(XMLGregorianCalendar value) {
                this.tsRegistrazione = value;
            }

            /**
             * Gets the value of the autore property.
             * 
             * @return
             *     possible object is
             *     {@link AutoreType }
             *     
             */
            public AutoreType getAutore() {
                return autore;
            }

            /**
             * Sets the value of the autore property.
             * 
             * @param value
             *     allowed object is
             *     {@link AutoreType }
             *     
             */
            public void setAutore(AutoreType value) {
                this.autore = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="TsInizio" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
         *         &lt;element name="TsCompletamento" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
         *         &lt;element name="TipoEsito" minOccurs="0">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;enumeration value="OK"/>
         *               &lt;enumeration value="KO"/>
         *               &lt;enumeration value="W"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "tsInizio",
            "tsCompletamento",
            "tipoEsito"
        })
        public static class PreverificaRagioneria {

            @XmlElement(name = "TsInizio", required = true)
            @XmlSchemaType(name = "dateTime")
            protected XMLGregorianCalendar tsInizio;
            @XmlElement(name = "TsCompletamento")
            @XmlSchemaType(name = "dateTime")
            protected XMLGregorianCalendar tsCompletamento;
            @XmlElement(name = "TipoEsito")
            protected String tipoEsito;

            /**
             * Gets the value of the tsInizio property.
             * 
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            
            
            
            public XMLGregorianCalendar getTsInizio() {
                return tsInizio;
            }

            public PreverificaRagioneria() {
				super();
				// TODO Auto-generated constructor stub
			}

			/**
             * Sets the value of the tsInizio property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public void setTsInizio(XMLGregorianCalendar value) {
                this.tsInizio = value;
            }

            /**
             * Gets the value of the tsCompletamento property.
             * 
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public XMLGregorianCalendar getTsCompletamento() {
                return tsCompletamento;
            }

            /**
             * Sets the value of the tsCompletamento property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public void setTsCompletamento(XMLGregorianCalendar value) {
                this.tsCompletamento = value;
            }

            /**
             * Gets the value of the tipoEsito property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTipoEsito() {
                return tipoEsito;
            }

            /**
             * Sets the value of the tipoEsito property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTipoEsito(String value) {
                this.tipoEsito = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="DataInizio" type="{http://www.w3.org/2001/XMLSchema}date"/>
         *         &lt;element name="DataTermine" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "dataInizio",
            "dataTermine"
        })
        public static class Pubblicazione {

            @XmlElement(name = "DataInizio", required = true)
            @XmlSchemaType(name = "date")
            protected XMLGregorianCalendar dataInizio;
            @XmlElement(name = "DataTermine")
            @XmlSchemaType(name = "date")
            protected XMLGregorianCalendar dataTermine;

            /**
             * Gets the value of the dataInizio property.
             * 
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public XMLGregorianCalendar getDataInizio() {
                return dataInizio;
            }

            /**
             * Sets the value of the dataInizio property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public void setDataInizio(XMLGregorianCalendar value) {
                this.dataInizio = value;
            }

            /**
             * Gets the value of the dataTermine property.
             * 
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public XMLGregorianCalendar getDataTermine() {
                return dataTermine;
            }

            /**
             * Sets the value of the dataTermine property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public void setDataTermine(XMLGregorianCalendar value) {
                this.dataTermine = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="TsRilascio" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
         *         &lt;element name="Firmatario" type="{}FirmatarioRestrictedType"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "tsRilascio",
            "firmatario"
        })
        public static class VistoRegolaritaContabile {

            @XmlElement(name = "TsRilascio", required = true)
            @XmlSchemaType(name = "dateTime")
            protected XMLGregorianCalendar tsRilascio;
            @XmlElement(name = "Firmatario", required = true)
            protected FirmatarioRestrictedType firmatario;

            /**
             * Gets the value of the tsRilascio property.
             * 
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public XMLGregorianCalendar getTsRilascio() {
                return tsRilascio;
            }

            /**
             * Sets the value of the tsRilascio property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public void setTsRilascio(XMLGregorianCalendar value) {
                this.tsRilascio = value;
            }

            /**
             * Gets the value of the firmatario property.
             * 
             * @return
             *     possible object is
             *     {@link FirmatarioRestrictedType }
             *     
             */
            public FirmatarioRestrictedType getFirmatario() {
                return firmatario;
            }

            /**
             * Sets the value of the firmatario property.
             * 
             * @param value
             *     allowed object is
             *     {@link FirmatarioRestrictedType }
             *     
             */
            public void setFirmatario(FirmatarioRestrictedType value) {
                this.firmatario = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *       &lt;attribute name="codice" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class ErrorMessage {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "codice", required = true)
        protected String codice;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the codice property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCodice() {
            return codice;
        }

        /**
         * Sets the value of the codice property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCodice(String value) {
            this.codice = value;
        }

    }

}
