/* * SPDX-License-Identifier: AGPL-3.0-or-later * * C Copyright 2023 Regione Piemonte * */
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-b10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.09.26 at 07:29:15 PM CEST 
//


package it.eng.auriga.repository2.jaxws.webservices.addunitadoc.inputBean;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for DestinatarioEsternoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DestinatarioEsternoType">
 *   &lt;complexContent>
 *     &lt;extension base="{}SoggettoEsternoType">
 *       &lt;sequence>
 *         &lt;element name="PerConoscenza" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *         &lt;element name="IndirizzoDest" type="{}IndirizzoType" minOccurs="0"/>
 *         &lt;element name="IndirizzoEmailDest" type="{}EmailType" minOccurs="0"/>
 *         &lt;element name="DataOraSpedAlDest" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="MezzoTrasmissioneAlDest" type="{}OggDiTabDiSistemaType" minOccurs="0"/>
 *         &lt;element name="DataRaccomandataAlDest" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="NroRaccomandataAlDest" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DestinatarioEsternoType", propOrder = {
    "perConoscenza",
    "indirizzoDest",
    "indirizzoEmailDest",
    "dataOraSpedAlDest",
    "mezzoTrasmissioneAlDest",
    "dataRaccomandataAlDest",
    "nroRaccomandataAlDest"
})
public class DestinatarioEsternoType
    extends SoggettoEsternoType
{

    @XmlElement(name = "PerConoscenza")
    protected Object perConoscenza;
    @XmlElement(name = "IndirizzoDest")
    protected IndirizzoType indirizzoDest;
    @XmlElement(name = "IndirizzoEmailDest")
    protected EmailType indirizzoEmailDest;
    @XmlElement(name = "DataOraSpedAlDest")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar dataOraSpedAlDest;
    @XmlElement(name = "MezzoTrasmissioneAlDest")
    protected OggDiTabDiSistemaType mezzoTrasmissioneAlDest;
    @XmlElement(name = "DataRaccomandataAlDest")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar dataRaccomandataAlDest;
    @XmlElement(name = "NroRaccomandataAlDest")
    protected String nroRaccomandataAlDest;

    /**
     * Gets the value of the perConoscenza property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getPerConoscenza() {
        return perConoscenza;
    }

    /**
     * Sets the value of the perConoscenza property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setPerConoscenza(Object value) {
        this.perConoscenza = value;
    }

    /**
     * Gets the value of the indirizzoDest property.
     * 
     * @return
     *     possible object is
     *     {@link IndirizzoType }
     *     
     */
    public IndirizzoType getIndirizzoDest() {
        return indirizzoDest;
    }

    /**
     * Sets the value of the indirizzoDest property.
     * 
     * @param value
     *     allowed object is
     *     {@link IndirizzoType }
     *     
     */
    public void setIndirizzoDest(IndirizzoType value) {
        this.indirizzoDest = value;
    }

    /**
     * Gets the value of the indirizzoEmailDest property.
     * 
     * @return
     *     possible object is
     *     {@link EmailType }
     *     
     */
    public EmailType getIndirizzoEmailDest() {
        return indirizzoEmailDest;
    }

    /**
     * Sets the value of the indirizzoEmailDest property.
     * 
     * @param value
     *     allowed object is
     *     {@link EmailType }
     *     
     */
    public void setIndirizzoEmailDest(EmailType value) {
        this.indirizzoEmailDest = value;
    }

    /**
     * Gets the value of the dataOraSpedAlDest property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDataOraSpedAlDest() {
        return dataOraSpedAlDest;
    }

    /**
     * Sets the value of the dataOraSpedAlDest property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDataOraSpedAlDest(XMLGregorianCalendar value) {
        this.dataOraSpedAlDest = value;
    }

    /**
     * Gets the value of the mezzoTrasmissioneAlDest property.
     * 
     * @return
     *     possible object is
     *     {@link OggDiTabDiSistemaType }
     *     
     */
    public OggDiTabDiSistemaType getMezzoTrasmissioneAlDest() {
        return mezzoTrasmissioneAlDest;
    }

    /**
     * Sets the value of the mezzoTrasmissioneAlDest property.
     * 
     * @param value
     *     allowed object is
     *     {@link OggDiTabDiSistemaType }
     *     
     */
    public void setMezzoTrasmissioneAlDest(OggDiTabDiSistemaType value) {
        this.mezzoTrasmissioneAlDest = value;
    }

    /**
     * Gets the value of the dataRaccomandataAlDest property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDataRaccomandataAlDest() {
        return dataRaccomandataAlDest;
    }

    /**
     * Sets the value of the dataRaccomandataAlDest property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDataRaccomandataAlDest(XMLGregorianCalendar value) {
        this.dataRaccomandataAlDest = value;
    }

    /**
     * Gets the value of the nroRaccomandataAlDest property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNroRaccomandataAlDest() {
        return nroRaccomandataAlDest;
    }

    /**
     * Sets the value of the nroRaccomandataAlDest property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNroRaccomandataAlDest(String value) {
        this.nroRaccomandataAlDest = value;
    }

}
