/* * SPDX-License-Identifier: AGPL-3.0-or-later * * C Copyright 2023 Regione Piemonte * */

// Generated 2-feb-2017 16.02.31 by Hibernate Tools 3.5.0.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * MailboxOperation generated by hbm2java
 */
@Entity
@Table(name = "MAILBOX_OPERATION")
@org.hibernate.annotations.Entity(dynamicUpdate = true, dynamicInsert = true)
public class MailboxOperation implements java.io.Serializable {

	private static final long serialVersionUID = -5454197284108599975L;
	private String idMailboxOperation;
	private Mailbox mailbox;
	private String operationName;
	private Set<MailboxOperationConfig> mailboxOperationConfigs = new HashSet<MailboxOperationConfig>(0);
	private Set<MailboxMessageOperation> mailboxMessageOperations = new HashSet<MailboxMessageOperation>(0);

	public MailboxOperation() {
	}

	public MailboxOperation(String idMailboxOperation, Mailbox mailbox, String operationName) {
		this.idMailboxOperation = idMailboxOperation;
		this.mailbox = mailbox;
		this.operationName = operationName;
	}

	public MailboxOperation(String idMailboxOperation, Mailbox mailbox, String operationName, Set<MailboxOperationConfig> mailboxOperationConfigs,
			Set<MailboxMessageOperation> mailboxMessageOperations) {
		this.idMailboxOperation = idMailboxOperation;
		this.mailbox = mailbox;
		this.operationName = operationName;
		this.mailboxOperationConfigs = mailboxOperationConfigs;
		this.mailboxMessageOperations = mailboxMessageOperations;
	}

	@Id
	@Column(name = "ID_MAILBOX_OPERATION", unique = true, nullable = false, length = 45)
	public String getIdMailboxOperation() {
		return this.idMailboxOperation;
	}

	public void setIdMailboxOperation(String idMailboxOperation) {
		this.idMailboxOperation = idMailboxOperation;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_MAILBOX", nullable = false)
	public Mailbox getMailbox() {
		return this.mailbox;
	}

	public void setMailbox(Mailbox mailbox) {
		this.mailbox = mailbox;
	}

	@Column(name = "OPERATION_NAME", nullable = false, length = 45)
	public String getOperationName() {
		return this.operationName;
	}

	public void setOperationName(String operationName) {
		this.operationName = operationName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mailboxOperation")
	public Set<MailboxOperationConfig> getMailboxOperationConfigs() {
		return this.mailboxOperationConfigs;
	}

	public void setMailboxOperationConfigs(Set<MailboxOperationConfig> mailboxOperationConfigs) {
		this.mailboxOperationConfigs = mailboxOperationConfigs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mailboxOperation")
	public Set<MailboxMessageOperation> getMailboxMessageOperations() {
		return this.mailboxMessageOperations;
	}

	public void setMailboxMessageOperations(Set<MailboxMessageOperation> mailboxMessageOperations) {
		this.mailboxMessageOperations = mailboxMessageOperations;
	}

}
