/* * SPDX-License-Identifier: AGPL-3.0-or-later * * C Copyright 2023 Regione Piemonte * */
// Generated 14-apr-2017 14.35.28 by Hibernate Tools 3.5.0.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * MailboxInfo generated by hbm2java
 */
@Entity
@Table(name = "MAILBOX_INFO")
public class MailboxInfo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5267123246721445736L;
	private MailboxInfoId id;
	private Mailbox mailbox;
	private String infoValue;

	public MailboxInfo() {
	}

	public MailboxInfo(MailboxInfoId id, Mailbox mailbox) {
		this.id = id;
		this.mailbox = mailbox;
	}

	public MailboxInfo(MailboxInfoId id, Mailbox mailbox, String infoValue) {
		this.id = id;
		this.mailbox = mailbox;
		this.infoValue = infoValue;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "infoKey", column = @Column(name = "INFO_KEY", nullable = false, length = 100)),
			@AttributeOverride(name = "idMailbox", column = @Column(name = "ID_MAILBOX", nullable = false, length = 40)) })
	public MailboxInfoId getId() {
		return this.id;
	}

	public void setId(MailboxInfoId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_MAILBOX", nullable = false, insertable = false, updatable = false)
	public Mailbox getMailbox() {
		return this.mailbox;
	}

	public void setMailbox(Mailbox mailbox) {
		this.mailbox = mailbox;
	}

	@Column(name = "INFO_VALUE", length = 400)
	public String getInfoValue() {
		return this.infoValue;
	}

	public void setInfoValue(String infoValue) {
		this.infoValue = infoValue;
	}

}
