/* * SPDX-License-Identifier: AGPL-3.0-or-later * * C Copyright 2023 Regione Piemonte * */

// Generated 2-feb-2017 16.02.31 by Hibernate Tools 3.5.0.Final

import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * MailboxMessageOperation generated by hbm2java
 */
@Entity
@Table(name = "MAILBOX_MESSAGE_OPERATION")
@org.hibernate.annotations.Entity(dynamicUpdate = true, dynamicInsert = true)
public class MailboxMessageOperation implements java.io.Serializable {

	private static final long serialVersionUID = -915040069506160861L;
	private MailboxMessageOperationId id;
	private MailboxMessage mailboxMessage;
	private MailboxOperation mailboxOperation;
	private String operationStatus;
	private short operationTryNum;
	private String operationValue;
	private String operationVariableValue;
	private Date dateOperation;

	public MailboxMessageOperation() {
	}

	public MailboxMessageOperation(MailboxMessageOperationId id, MailboxMessage mailboxMessage, MailboxOperation mailboxOperation, String operationStatus,
			short operationTryNum, Date dateOperation) {
		this.id = id;
		this.mailboxMessage = mailboxMessage;
		this.mailboxOperation = mailboxOperation;
		this.operationStatus = operationStatus;
		this.operationTryNum = operationTryNum;
		this.dateOperation = dateOperation;
	}

	public MailboxMessageOperation(MailboxMessageOperationId id, MailboxMessage mailboxMessage, MailboxOperation mailboxOperation, String operationStatus,
			short operationTryNum, String operationValue, String operationVariableValue, Date dateOperation) {
		this.id = id;
		this.mailboxMessage = mailboxMessage;
		this.mailboxOperation = mailboxOperation;
		this.operationStatus = operationStatus;
		this.operationTryNum = operationTryNum;
		this.operationValue = operationValue;
		this.operationVariableValue = operationVariableValue;
		this.dateOperation = dateOperation;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "idMailboxoperation", column = @Column(name = "ID_MAILBOXOPERATION", nullable = false, length = 45)),
			@AttributeOverride(name = "messageId", column = @Column(name = "MESSAGE_ID", nullable = false, length = 400)),
			@AttributeOverride(name = "idMailbox", column = @Column(name = "ID_MAILBOX", nullable = false, length = 40)) })
	public MailboxMessageOperationId getId() {
		return this.id;
	}

	public void setId(MailboxMessageOperationId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({ @JoinColumn(name = "MESSAGE_ID", referencedColumnName = "MESSAGE_ID", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "ID_MAILBOX", referencedColumnName = "ID_MAILBOX", nullable = false, insertable = false, updatable = false) })
	public MailboxMessage getMailboxMessage() {
		return this.mailboxMessage;
	}

	public void setMailboxMessage(MailboxMessage mailboxMessage) {
		this.mailboxMessage = mailboxMessage;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_MAILBOXOPERATION", nullable = false, insertable = false, updatable = false)
	public MailboxOperation getMailboxOperation() {
		return this.mailboxOperation;
	}

	public void setMailboxOperation(MailboxOperation mailboxOperation) {
		this.mailboxOperation = mailboxOperation;
	}

	@Column(name = "OPERATION_STATUS", nullable = false, length = 30)
	public String getOperationStatus() {
		return this.operationStatus;
	}

	public void setOperationStatus(String operationStatus) {
		this.operationStatus = operationStatus;
	}

	@Column(name = "OPERATION_TRY_NUM", nullable = false, precision = 3, scale = 0)
	public short getOperationTryNum() {
		return this.operationTryNum;
	}

	public void setOperationTryNum(short operationTryNum) {
		this.operationTryNum = operationTryNum;
	}

	@Column(name = "OPERATION_VALUE")
	public String getOperationValue() {
		return this.operationValue;
	}

	public void setOperationValue(String operationValue) {
		this.operationValue = operationValue;
	}

	@Column(name = "OPERATION_VARIABLE_VALUE", length = 500)
	public String getOperationVariableValue() {
		return this.operationVariableValue;
	}

	public void setOperationVariableValue(String operationVariableValue) {
		this.operationVariableValue = operationVariableValue;
	}

	@Column(name = "DATE_OPERATION", nullable = false, length = 7)
	public Date getDateOperation() {
		return this.dateOperation;
	}

	public void setDateOperation(Date dateOperation) {
		this.dateOperation = dateOperation;
	}

}
