/* * SPDX-License-Identifier: AGPL-3.0-or-later * * C Copyright 2023 Regione Piemonte * */

// Generated 2-feb-2017 16.02.31 by Hibernate Tools 3.5.0.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * MailboxAccount generated by hbm2java
 */
@Entity
@Table(name = "MAILBOX_ACCOUNT", uniqueConstraints = @UniqueConstraint(columnNames = "ACCOUNT"))
@org.hibernate.annotations.Entity(dynamicUpdate = true, dynamicInsert = true)
public class MailboxAccount implements java.io.Serializable {

	private static final long serialVersionUID = 8395229412275004120L;
	private String idAccount;
	private String account;
	private Set<TEmailMgo> TEmailMgos = new HashSet<TEmailMgo>(0);
	private Set<Mailbox> mailboxes = new HashSet<Mailbox>(0);
	private Set<TFolderCaselle> TFolderCaselles = new HashSet<TFolderCaselle>(0);
	private Set<TRelCaselleFruitori> TRelCaselleFruitoris = new HashSet<TRelCaselleFruitori>(0);
	private Set<MailboxAccountConfig> mailboxAccountConfigs = new HashSet<MailboxAccountConfig>(0);

	public MailboxAccount() {
	}

	public MailboxAccount(String idAccount, String account) {
		this.idAccount = idAccount;
		this.account = account;
	}

	public MailboxAccount(String idAccount, String account, Set<TEmailMgo> TEmailMgos, Set<Mailbox> mailboxes, Set<TFolderCaselle> TFolderCaselles,
			Set<TRelCaselleFruitori> TRelCaselleFruitoris, Set<MailboxAccountConfig> mailboxAccountConfigs) {
		this.idAccount = idAccount;
		this.account = account;
		this.TEmailMgos = TEmailMgos;
		this.mailboxes = mailboxes;
		this.TFolderCaselles = TFolderCaselles;
		this.TRelCaselleFruitoris = TRelCaselleFruitoris;
		this.mailboxAccountConfigs = mailboxAccountConfigs;
	}

	@Id
	@Column(name = "ID_ACCOUNT", unique = true, nullable = false, length = 40)
	public String getIdAccount() {
		return this.idAccount;
	}

	public void setIdAccount(String idAccount) {
		this.idAccount = idAccount;
	}

	@Column(name = "ACCOUNT", unique = true, nullable = false, length = 100)
	public String getAccount() {
		return this.account;
	}

	public void setAccount(String account) {
		this.account = account;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mailboxAccount")
	public Set<TEmailMgo> getTEmailMgos() {
		return this.TEmailMgos;
	}

	public void setTEmailMgos(Set<TEmailMgo> TEmailMgos) {
		this.TEmailMgos = TEmailMgos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mailboxAccount")
	public Set<Mailbox> getMailboxes() {
		return this.mailboxes;
	}

	public void setMailboxes(Set<Mailbox> mailboxes) {
		this.mailboxes = mailboxes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mailboxAccount")
	public Set<TFolderCaselle> getTFolderCaselles() {
		return this.TFolderCaselles;
	}

	public void setTFolderCaselles(Set<TFolderCaselle> TFolderCaselles) {
		this.TFolderCaselles = TFolderCaselles;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mailboxAccount")
	public Set<TRelCaselleFruitori> getTRelCaselleFruitoris() {
		return this.TRelCaselleFruitoris;
	}

	public void setTRelCaselleFruitoris(Set<TRelCaselleFruitori> TRelCaselleFruitoris) {
		this.TRelCaselleFruitoris = TRelCaselleFruitoris;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mailboxAccount")
	public Set<MailboxAccountConfig> getMailboxAccountConfigs() {
		return this.mailboxAccountConfigs;
	}

	public void setMailboxAccountConfigs(Set<MailboxAccountConfig> mailboxAccountConfigs) {
		this.mailboxAccountConfigs = mailboxAccountConfigs;
	}

}
