/* * SPDX-License-Identifier: AGPL-3.0-or-later * * C Copyright 2023 Regione Piemonte * */

// Generated 2-feb-2017 16.02.31 by Hibernate Tools 3.5.0.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TAnagFruitoriCaselle generated by hbm2java
 */
@Entity
@Table(name = "T_ANAG_FRUITORI_CASELLE")
@org.hibernate.annotations.Entity(dynamicUpdate = true, dynamicInsert = true)
public class TAnagFruitoriCaselle implements java.io.Serializable {

	private static final long serialVersionUID = 522016352060882132L;
	private String idFruitoreCasella;
	private TAnagFruitoriCaselle TAnagFruitoriCaselleByIdEnteAoo;
	private TAnagFruitoriCaselle TAnagFruitoriCaselleByIdFruitoreSup;
	private String tipo;
	private String denominazione;
	private String codice;
	private boolean flgAttivo;
	private String codiceCompleto;
	private String denominazioneCompleta;
	private String idProvFruitore;
	private Date tsIns;
	private String idUteIns;
	private Date tsUltimoAgg;
	private String idUteUltimoAgg;
	private Set<TAnagFruitoriCaselle> TAnagFruitoriCasellesForIdFruitoreSup = new HashSet<TAnagFruitoriCaselle>(0);
	private Set<TAssegnEmail> TAssegnEmails = new HashSet<TAssegnEmail>(0);
	private Set<TAnagFruitoriCaselle> TAnagFruitoriCasellesForIdEnteAoo = new HashSet<TAnagFruitoriCaselle>(0);
	private Set<TRelUtentiVsFruitori> TRelUtentiVsFruitoris = new HashSet<TRelUtentiVsFruitori>(0);
	private Set<TEmailMgo> TEmailMgos = new HashSet<TEmailMgo>(0);
	private Set<TRubricaEmail> TRubricaEmails = new HashSet<TRubricaEmail>(0);
	private Set<TRelCaselleFruitori> TRelCaselleFruitoris = new HashSet<TRelCaselleFruitori>(0);

	public TAnagFruitoriCaselle() {
	}

	public TAnagFruitoriCaselle(String idFruitoreCasella, String tipo, String denominazione, boolean flgAttivo, String denominazioneCompleta, Date tsIns,
			Date tsUltimoAgg) {
		this.idFruitoreCasella = idFruitoreCasella;
		this.tipo = tipo;
		this.denominazione = denominazione;
		this.flgAttivo = flgAttivo;
		this.denominazioneCompleta = denominazioneCompleta;
		this.tsIns = tsIns;
		this.tsUltimoAgg = tsUltimoAgg;
	}

	public TAnagFruitoriCaselle(String idFruitoreCasella, TAnagFruitoriCaselle TAnagFruitoriCaselleByIdEnteAoo,
			TAnagFruitoriCaselle TAnagFruitoriCaselleByIdFruitoreSup, String tipo, String denominazione, String codice, boolean flgAttivo,
			String codiceCompleto, String denominazioneCompleta, String idProvFruitore, Date tsIns, String idUteIns, Date tsUltimoAgg, String idUteUltimoAgg,
			Set<TAnagFruitoriCaselle> TAnagFruitoriCasellesForIdFruitoreSup, Set<TAssegnEmail> TAssegnEmails,
			Set<TAnagFruitoriCaselle> TAnagFruitoriCasellesForIdEnteAoo, Set<TRelUtentiVsFruitori> TRelUtentiVsFruitoris, Set<TEmailMgo> TEmailMgos,
			Set<TRubricaEmail> TRubricaEmails, Set<TRelCaselleFruitori> TRelCaselleFruitoris) {
		this.idFruitoreCasella = idFruitoreCasella;
		this.TAnagFruitoriCaselleByIdEnteAoo = TAnagFruitoriCaselleByIdEnteAoo;
		this.TAnagFruitoriCaselleByIdFruitoreSup = TAnagFruitoriCaselleByIdFruitoreSup;
		this.tipo = tipo;
		this.denominazione = denominazione;
		this.codice = codice;
		this.flgAttivo = flgAttivo;
		this.codiceCompleto = codiceCompleto;
		this.denominazioneCompleta = denominazioneCompleta;
		this.idProvFruitore = idProvFruitore;
		this.tsIns = tsIns;
		this.idUteIns = idUteIns;
		this.tsUltimoAgg = tsUltimoAgg;
		this.idUteUltimoAgg = idUteUltimoAgg;
		this.TAnagFruitoriCasellesForIdFruitoreSup = TAnagFruitoriCasellesForIdFruitoreSup;
		this.TAssegnEmails = TAssegnEmails;
		this.TAnagFruitoriCasellesForIdEnteAoo = TAnagFruitoriCasellesForIdEnteAoo;
		this.TRelUtentiVsFruitoris = TRelUtentiVsFruitoris;
		this.TEmailMgos = TEmailMgos;
		this.TRubricaEmails = TRubricaEmails;
		this.TRelCaselleFruitoris = TRelCaselleFruitoris;
	}

	@Id
	@Column(name = "ID_FRUITORE_CASELLA", unique = true, nullable = false, length = 64)
	public String getIdFruitoreCasella() {
		return this.idFruitoreCasella;
	}

	public void setIdFruitoreCasella(String idFruitoreCasella) {
		this.idFruitoreCasella = idFruitoreCasella;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_ENTE_AOO")
	public TAnagFruitoriCaselle getTAnagFruitoriCaselleByIdEnteAoo() {
		return this.TAnagFruitoriCaselleByIdEnteAoo;
	}

	public void setTAnagFruitoriCaselleByIdEnteAoo(TAnagFruitoriCaselle TAnagFruitoriCaselleByIdEnteAoo) {
		this.TAnagFruitoriCaselleByIdEnteAoo = TAnagFruitoriCaselleByIdEnteAoo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_FRUITORE_SUP")
	public TAnagFruitoriCaselle getTAnagFruitoriCaselleByIdFruitoreSup() {
		return this.TAnagFruitoriCaselleByIdFruitoreSup;
	}

	public void setTAnagFruitoriCaselleByIdFruitoreSup(TAnagFruitoriCaselle TAnagFruitoriCaselleByIdFruitoreSup) {
		this.TAnagFruitoriCaselleByIdFruitoreSup = TAnagFruitoriCaselleByIdFruitoreSup;
	}

	@Column(name = "TIPO", nullable = false, length = 30)
	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	@Column(name = "DENOMINAZIONE", nullable = false, length = 250)
	public String getDenominazione() {
		return this.denominazione;
	}

	public void setDenominazione(String denominazione) {
		this.denominazione = denominazione;
	}

	@Column(name = "CODICE", length = 30)
	public String getCodice() {
		return this.codice;
	}

	public void setCodice(String codice) {
		this.codice = codice;
	}

	@Column(name = "FLG_ATTIVO", nullable = false, precision = 1, scale = 0)
	public boolean isFlgAttivo() {
		return this.flgAttivo;
	}

	public void setFlgAttivo(boolean flgAttivo) {
		this.flgAttivo = flgAttivo;
	}

	@Column(name = "CODICE_COMPLETO", length = 250)
	public String getCodiceCompleto() {
		return this.codiceCompleto;
	}

	public void setCodiceCompleto(String codiceCompleto) {
		this.codiceCompleto = codiceCompleto;
	}

	@Column(name = "DENOMINAZIONE_COMPLETA", nullable = false, length = 2000)
	public String getDenominazioneCompleta() {
		return this.denominazioneCompleta;
	}

	public void setDenominazioneCompleta(String denominazioneCompleta) {
		this.denominazioneCompleta = denominazioneCompleta;
	}

	@Column(name = "ID_PROV_FRUITORE", length = 100)
	public String getIdProvFruitore() {
		return this.idProvFruitore;
	}

	public void setIdProvFruitore(String idProvFruitore) {
		this.idProvFruitore = idProvFruitore;
	}

	@Column(name = "TS_INS", nullable = false)
	public Date getTsIns() {
		return this.tsIns;
	}

	public void setTsIns(Date tsIns) {
		this.tsIns = tsIns;
	}

	@Column(name = "ID_UTE_INS", length = 64)
	public String getIdUteIns() {
		return this.idUteIns;
	}

	public void setIdUteIns(String idUteIns) {
		this.idUteIns = idUteIns;
	}

	@Column(name = "TS_ULTIMO_AGG", nullable = false)
	public Date getTsUltimoAgg() {
		return this.tsUltimoAgg;
	}

	public void setTsUltimoAgg(Date tsUltimoAgg) {
		this.tsUltimoAgg = tsUltimoAgg;
	}

	@Column(name = "ID_UTE_ULTIMO_AGG", length = 64)
	public String getIdUteUltimoAgg() {
		return this.idUteUltimoAgg;
	}

	public void setIdUteUltimoAgg(String idUteUltimoAgg) {
		this.idUteUltimoAgg = idUteUltimoAgg;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TAnagFruitoriCaselleByIdFruitoreSup")
	public Set<TAnagFruitoriCaselle> getTAnagFruitoriCasellesForIdFruitoreSup() {
		return this.TAnagFruitoriCasellesForIdFruitoreSup;
	}

	public void setTAnagFruitoriCasellesForIdFruitoreSup(Set<TAnagFruitoriCaselle> TAnagFruitoriCasellesForIdFruitoreSup) {
		this.TAnagFruitoriCasellesForIdFruitoreSup = TAnagFruitoriCasellesForIdFruitoreSup;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TAnagFruitoriCaselle")
	public Set<TAssegnEmail> getTAssegnEmails() {
		return this.TAssegnEmails;
	}

	public void setTAssegnEmails(Set<TAssegnEmail> TAssegnEmails) {
		this.TAssegnEmails = TAssegnEmails;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TAnagFruitoriCaselleByIdEnteAoo")
	public Set<TAnagFruitoriCaselle> getTAnagFruitoriCasellesForIdEnteAoo() {
		return this.TAnagFruitoriCasellesForIdEnteAoo;
	}

	public void setTAnagFruitoriCasellesForIdEnteAoo(Set<TAnagFruitoriCaselle> TAnagFruitoriCasellesForIdEnteAoo) {
		this.TAnagFruitoriCasellesForIdEnteAoo = TAnagFruitoriCasellesForIdEnteAoo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TAnagFruitoriCaselle")
	public Set<TRelUtentiVsFruitori> getTRelUtentiVsFruitoris() {
		return this.TRelUtentiVsFruitoris;
	}

	public void setTRelUtentiVsFruitoris(Set<TRelUtentiVsFruitori> TRelUtentiVsFruitoris) {
		this.TRelUtentiVsFruitoris = TRelUtentiVsFruitoris;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TAnagFruitoriCaselle")
	public Set<TEmailMgo> getTEmailMgos() {
		return this.TEmailMgos;
	}

	public void setTEmailMgos(Set<TEmailMgo> TEmailMgos) {
		this.TEmailMgos = TEmailMgos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TAnagFruitoriCaselle")
	public Set<TRubricaEmail> getTRubricaEmails() {
		return this.TRubricaEmails;
	}

	public void setTRubricaEmails(Set<TRubricaEmail> TRubricaEmails) {
		this.TRubricaEmails = TRubricaEmails;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TAnagFruitoriCaselle")
	public Set<TRelCaselleFruitori> getTRelCaselleFruitoris() {
		return this.TRelCaselleFruitoris;
	}

	public void setTRelCaselleFruitoris(Set<TRelCaselleFruitori> TRelCaselleFruitoris) {
		this.TRelCaselleFruitoris = TRelCaselleFruitoris;
	}

}
