/* * SPDX-License-Identifier: AGPL-3.0-or-later * * C Copyright 2023 Regione Piemonte * */

// Generated 2-feb-2017 16.02.31 by Hibernate Tools 3.5.0.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * TApplicazioniModPec generated by hbm2java
 */
@Entity
@Table(name = "T_APPLICAZIONI_MOD_PEC", uniqueConstraints = { @UniqueConstraint(columnNames = "NOME"), @UniqueConstraint(columnNames = "COD_APPLICAZIONE") })
@org.hibernate.annotations.Entity(dynamicUpdate = true, dynamicInsert = true)
public class TApplicazioniModPec implements java.io.Serializable {

	private static final long serialVersionUID = -5016201428989975540L;
	private String idApplicazione;
	private String codApplicazione;
	private String nome;
	private String password;
	private String descrizione;
	private boolean flgAttiva;
	private Date tsIns;
	private String idUteIns;
	private Date tsUltimoAgg;
	private String idUteUltimoAgg;

	public TApplicazioniModPec() {
	}

	public TApplicazioniModPec(String idApplicazione, String codApplicazione, String nome, String password, boolean flgAttiva, Date tsIns, Date tsUltimoAgg) {
		this.idApplicazione = idApplicazione;
		this.codApplicazione = codApplicazione;
		this.nome = nome;
		this.password = password;
		this.flgAttiva = flgAttiva;
		this.tsIns = tsIns;
		this.tsUltimoAgg = tsUltimoAgg;
	}

	public TApplicazioniModPec(String idApplicazione, String codApplicazione, String nome, String password, String descrizione, boolean flgAttiva, Date tsIns,
			String idUteIns, Date tsUltimoAgg, String idUteUltimoAgg) {
		this.idApplicazione = idApplicazione;
		this.codApplicazione = codApplicazione;
		this.nome = nome;
		this.password = password;
		this.descrizione = descrizione;
		this.flgAttiva = flgAttiva;
		this.tsIns = tsIns;
		this.idUteIns = idUteIns;
		this.tsUltimoAgg = tsUltimoAgg;
		this.idUteUltimoAgg = idUteUltimoAgg;
	}

	@Id
	@Column(name = "ID_APPLICAZIONE", unique = true, nullable = false, length = 64)
	public String getIdApplicazione() {
		return this.idApplicazione;
	}

	public void setIdApplicazione(String idApplicazione) {
		this.idApplicazione = idApplicazione;
	}

	@Column(name = "COD_APPLICAZIONE", unique = true, nullable = false, length = 30)
	public String getCodApplicazione() {
		return this.codApplicazione;
	}

	public void setCodApplicazione(String codApplicazione) {
		this.codApplicazione = codApplicazione;
	}

	@Column(name = "NOME", unique = true, nullable = false, length = 150)
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@Column(name = "PASSWORD", nullable = false, length = 100)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "DESCRIZIONE", length = 500)
	public String getDescrizione() {
		return this.descrizione;
	}

	public void setDescrizione(String descrizione) {
		this.descrizione = descrizione;
	}

	@Column(name = "FLG_ATTIVA", nullable = false, precision = 1, scale = 0)
	public boolean isFlgAttiva() {
		return this.flgAttiva;
	}

	public void setFlgAttiva(boolean flgAttiva) {
		this.flgAttiva = flgAttiva;
	}

	@Column(name = "TS_INS", nullable = false)
	public Date getTsIns() {
		return this.tsIns;
	}

	public void setTsIns(Date tsIns) {
		this.tsIns = tsIns;
	}

	@Column(name = "ID_UTE_INS", length = 64)
	public String getIdUteIns() {
		return this.idUteIns;
	}

	public void setIdUteIns(String idUteIns) {
		this.idUteIns = idUteIns;
	}

	@Column(name = "TS_ULTIMO_AGG", nullable = false)
	public Date getTsUltimoAgg() {
		return this.tsUltimoAgg;
	}

	public void setTsUltimoAgg(Date tsUltimoAgg) {
		this.tsUltimoAgg = tsUltimoAgg;
	}

	@Column(name = "ID_UTE_ULTIMO_AGG", length = 64)
	public String getIdUteUltimoAgg() {
		return this.idUteUltimoAgg;
	}

	public void setIdUteUltimoAgg(String idUteUltimoAgg) {
		this.idUteUltimoAgg = idUteUltimoAgg;
	}

}
