/* * SPDX-License-Identifier: AGPL-3.0-or-later * * C Copyright 2023 Regione Piemonte * */

// Generated 2-feb-2017 16.02.31 by Hibernate Tools 3.5.0.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * TCapFrazioni generated by hbm2java
 */
@Entity
@Table(name = "T_CAP_FRAZIONI")
@org.hibernate.annotations.Entity(dynamicUpdate = true, dynamicInsert = true)
public class TCapFrazioni implements java.io.Serializable {

	private static final long serialVersionUID = 7447510911064626745L;
	private TCapFrazioniId id;
	private String targaProvincia;

	public TCapFrazioni() {
	}

	public TCapFrazioni(TCapFrazioniId id) {
		this.id = id;
	}

	public TCapFrazioni(TCapFrazioniId id, String targaProvincia) {
		this.id = id;
		this.targaProvincia = targaProvincia;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "cap", column = @Column(name = "CAP", nullable = false, length = 5)),
			@AttributeOverride(name = "frazione", column = @Column(name = "FRAZIONE", nullable = false, length = 50)),
			@AttributeOverride(name = "nomeComune", column = @Column(name = "NOME_COMUNE", nullable = false, length = 50)) })
	public TCapFrazioniId getId() {
		return this.id;
	}

	public void setId(TCapFrazioniId id) {
		this.id = id;
	}

	@Column(name = "TARGA_PROVINCIA", length = 2)
	public String getTargaProvincia() {
		return this.targaProvincia;
	}

	public void setTargaProvincia(String targaProvincia) {
		this.targaProvincia = targaProvincia;
	}

}
