/* * SPDX-License-Identifier: AGPL-3.0-or-later * * C Copyright 2023 Regione Piemonte * */

// Generated 2-feb-2017 16.02.31 by Hibernate Tools 3.5.0.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * TDestinatariEmailMgo generated by hbm2java
 */
@Entity
@Table(name = "T_DESTINATARI_EMAIL_MGO", uniqueConstraints = @UniqueConstraint(columnNames = { "ID_EMAIL", "FLG_TIPO_DESTINATARIO", "ACCOUNT_DESTINATARIO",
		"ID_VOCE_RUBRICA_DEST" }))
@org.hibernate.annotations.Entity(dynamicUpdate = true, dynamicInsert = true)
public class TDestinatariEmailMgo implements java.io.Serializable {

	private static final long serialVersionUID = -4167221574772106811L;
	private String idDestinatarioEmail;
	private TRubricaEmail TRubricaEmail;
	private TEmailMgo TEmailMgo;
	private boolean flgDestOrigInvio;
	private String flgTipoDestinatario;
	private String accountDestinatario;
	private boolean flgDestEffettivo;
	private String statoConsolidamento;
	private boolean flgNotifInteropAnn;
	private boolean flgNotifInteropEcc;
	private boolean flgNotifInteropConf;
	private boolean flgNotifInteropAgg;
	private Date tsIns;
	private String idUteIns;
	private Date tsUltimoAgg;
	private String idUteUltimoAgg;
	private String accountDestinatarioCtx;
	private String statoConsegna;
	private Set<TRegEstVsEmail> TRegEstVsEmails = new HashSet<TRegEstVsEmail>(0);
	private Set<TRelEmailMgo> TRelEmailMgos = new HashSet<TRelEmailMgo>(0);

	public TDestinatariEmailMgo() {
	}

	public TDestinatariEmailMgo(String idDestinatarioEmail, TEmailMgo TEmailMgo, boolean flgDestOrigInvio, String flgTipoDestinatario, boolean flgDestEffettivo,
			boolean flgNotifInteropAnn, boolean flgNotifInteropEcc, boolean flgNotifInteropConf, boolean flgNotifInteropAgg, Date tsIns, Date tsUltimoAgg) {
		this.idDestinatarioEmail = idDestinatarioEmail;
		this.TEmailMgo = TEmailMgo;
		this.flgDestOrigInvio = flgDestOrigInvio;
		this.flgTipoDestinatario = flgTipoDestinatario;
		this.flgDestEffettivo = flgDestEffettivo;
		this.flgNotifInteropAnn = flgNotifInteropAnn;
		this.flgNotifInteropEcc = flgNotifInteropEcc;
		this.flgNotifInteropConf = flgNotifInteropConf;
		this.flgNotifInteropAgg = flgNotifInteropAgg;
		this.tsIns = tsIns;
		this.tsUltimoAgg = tsUltimoAgg;
	}

	public TDestinatariEmailMgo(String idDestinatarioEmail, TRubricaEmail TRubricaEmail, TEmailMgo TEmailMgo, boolean flgDestOrigInvio,
			String flgTipoDestinatario, String accountDestinatario, boolean flgDestEffettivo, String statoConsolidamento, boolean flgNotifInteropAnn,
			boolean flgNotifInteropEcc, boolean flgNotifInteropConf, boolean flgNotifInteropAgg, Date tsIns, String idUteIns, Date tsUltimoAgg,
			String idUteUltimoAgg, String accountDestinatarioCtx, String statoConsegna, Set<TRegEstVsEmail> TRegEstVsEmails, Set<TRelEmailMgo> TRelEmailMgos) {
		this.idDestinatarioEmail = idDestinatarioEmail;
		this.TRubricaEmail = TRubricaEmail;
		this.TEmailMgo = TEmailMgo;
		this.flgDestOrigInvio = flgDestOrigInvio;
		this.flgTipoDestinatario = flgTipoDestinatario;
		this.accountDestinatario = accountDestinatario;
		this.flgDestEffettivo = flgDestEffettivo;
		this.statoConsolidamento = statoConsolidamento;
		this.flgNotifInteropAnn = flgNotifInteropAnn;
		this.flgNotifInteropEcc = flgNotifInteropEcc;
		this.flgNotifInteropConf = flgNotifInteropConf;
		this.flgNotifInteropAgg = flgNotifInteropAgg;
		this.tsIns = tsIns;
		this.idUteIns = idUteIns;
		this.tsUltimoAgg = tsUltimoAgg;
		this.idUteUltimoAgg = idUteUltimoAgg;
		this.accountDestinatarioCtx = accountDestinatarioCtx;
		this.statoConsegna = statoConsegna;
		this.TRegEstVsEmails = TRegEstVsEmails;
		this.TRelEmailMgos = TRelEmailMgos;
	}

	@Id
	@Column(name = "ID_DESTINATARIO_EMAIL", unique = true, nullable = false, length = 64)
	public String getIdDestinatarioEmail() {
		return this.idDestinatarioEmail;
	}

	public void setIdDestinatarioEmail(String idDestinatarioEmail) {
		this.idDestinatarioEmail = idDestinatarioEmail;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_VOCE_RUBRICA_DEST")
	public TRubricaEmail getTRubricaEmail() {
		return this.TRubricaEmail;
	}

	public void setTRubricaEmail(TRubricaEmail TRubricaEmail) {
		this.TRubricaEmail = TRubricaEmail;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_EMAIL", nullable = false)
	public TEmailMgo getTEmailMgo() {
		return this.TEmailMgo;
	}

	public void setTEmailMgo(TEmailMgo TEmailMgo) {
		this.TEmailMgo = TEmailMgo;
	}

	@Column(name = "FLG_DEST_ORIG_INVIO", nullable = false, precision = 1, scale = 0)
	public boolean isFlgDestOrigInvio() {
		return this.flgDestOrigInvio;
	}

	public void setFlgDestOrigInvio(boolean flgDestOrigInvio) {
		this.flgDestOrigInvio = flgDestOrigInvio;
	}

	@Column(name = "FLG_TIPO_DESTINATARIO", nullable = false, length = 3)
	public String getFlgTipoDestinatario() {
		return this.flgTipoDestinatario;
	}

	public void setFlgTipoDestinatario(String flgTipoDestinatario) {
		this.flgTipoDestinatario = flgTipoDestinatario;
	}

	@Column(name = "ACCOUNT_DESTINATARIO", length = 1000)
	public String getAccountDestinatario() {
		return this.accountDestinatario;
	}

	public void setAccountDestinatario(String accountDestinatario) {
		this.accountDestinatario = accountDestinatario;
	}

	@Column(name = "FLG_DEST_EFFETTIVO", nullable = false, precision = 1, scale = 0)
	public boolean isFlgDestEffettivo() {
		return this.flgDestEffettivo;
	}

	public void setFlgDestEffettivo(boolean flgDestEffettivo) {
		this.flgDestEffettivo = flgDestEffettivo;
	}

	@Column(name = "STATO_CONSOLIDAMENTO", length = 30)
	public String getStatoConsolidamento() {
		return this.statoConsolidamento;
	}

	public void setStatoConsolidamento(String statoConsolidamento) {
		this.statoConsolidamento = statoConsolidamento;
	}

	@Column(name = "FLG_NOTIF_INTEROP_ANN", nullable = false, precision = 1, scale = 0)
	public boolean isFlgNotifInteropAnn() {
		return this.flgNotifInteropAnn;
	}

	public void setFlgNotifInteropAnn(boolean flgNotifInteropAnn) {
		this.flgNotifInteropAnn = flgNotifInteropAnn;
	}

	@Column(name = "FLG_NOTIF_INTEROP_ECC", nullable = false, precision = 1, scale = 0)
	public boolean isFlgNotifInteropEcc() {
		return this.flgNotifInteropEcc;
	}

	public void setFlgNotifInteropEcc(boolean flgNotifInteropEcc) {
		this.flgNotifInteropEcc = flgNotifInteropEcc;
	}

	@Column(name = "FLG_NOTIF_INTEROP_CONF", nullable = false, precision = 1, scale = 0)
	public boolean isFlgNotifInteropConf() {
		return this.flgNotifInteropConf;
	}

	public void setFlgNotifInteropConf(boolean flgNotifInteropConf) {
		this.flgNotifInteropConf = flgNotifInteropConf;
	}

	@Column(name = "FLG_NOTIF_INTEROP_AGG", nullable = false, precision = 1, scale = 0)
	public boolean isFlgNotifInteropAgg() {
		return this.flgNotifInteropAgg;
	}

	public void setFlgNotifInteropAgg(boolean flgNotifInteropAgg) {
		this.flgNotifInteropAgg = flgNotifInteropAgg;
	}

	@Column(name = "TS_INS", nullable = false)
	public Date getTsIns() {
		return this.tsIns;
	}

	public void setTsIns(Date tsIns) {
		this.tsIns = tsIns;
	}

	@Column(name = "ID_UTE_INS", length = 64)
	public String getIdUteIns() {
		return this.idUteIns;
	}

	public void setIdUteIns(String idUteIns) {
		this.idUteIns = idUteIns;
	}

	@Column(name = "TS_ULTIMO_AGG", nullable = false)
	public Date getTsUltimoAgg() {
		return this.tsUltimoAgg;
	}

	public void setTsUltimoAgg(Date tsUltimoAgg) {
		this.tsUltimoAgg = tsUltimoAgg;
	}

	@Column(name = "ID_UTE_ULTIMO_AGG", length = 64)
	public String getIdUteUltimoAgg() {
		return this.idUteUltimoAgg;
	}

	public void setIdUteUltimoAgg(String idUteUltimoAgg) {
		this.idUteUltimoAgg = idUteUltimoAgg;
	}

	@Column(name = "ACCOUNT_DESTINATARIO_CTX", length = 1000)
	public String getAccountDestinatarioCtx() {
		return this.accountDestinatarioCtx;
	}

	public void setAccountDestinatarioCtx(String accountDestinatarioCtx) {
		this.accountDestinatarioCtx = accountDestinatarioCtx;
	}

	@Column(name = "STATO_CONSEGNA", length = 2)
	public String getStatoConsegna() {
		return this.statoConsegna;
	}

	public void setStatoConsegna(String statoConsegna) {
		this.statoConsegna = statoConsegna;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TDestinatariEmailMgo")
	public Set<TRegEstVsEmail> getTRegEstVsEmails() {
		return this.TRegEstVsEmails;
	}

	public void setTRegEstVsEmails(Set<TRegEstVsEmail> TRegEstVsEmails) {
		this.TRegEstVsEmails = TRegEstVsEmails;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TDestinatariEmailMgo")
	public Set<TRelEmailMgo> getTRelEmailMgos() {
		return this.TRelEmailMgos;
	}

	public void setTRelEmailMgos(Set<TRelEmailMgo> TRelEmailMgos) {
		this.TRelEmailMgos = TRelEmailMgos;
	}

}
