/* * SPDX-License-Identifier: AGPL-3.0-or-later * * C Copyright 2023 Regione Piemonte * */

// Generated 2-feb-2017 16.02.31 by Hibernate Tools 3.5.0.Final

import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * TEmailVsUtenti generated by hbm2java
 */
@Entity
@Table(name = "T_EMAIL_VS_UTENTI", uniqueConstraints = @UniqueConstraint(columnNames = { "ID_UTENTE", "ID_EMAIL" }))
public class TEmailVsUtenti implements java.io.Serializable {

	private static final long serialVersionUID = 3909471844163580919L;
	private TEmailVsUtentiId id;
	private TValDizionario TValDizionario;
	private TUtentiModPec TUtentiModPec;
	private TEmailMgo TEmailMgo;
	private Date tsAggStato;
	private Date tsIns;
	private String idUteIns;
	private Date tsUltimoAgg;
	private String idUteUltimoAgg;

	public TEmailVsUtenti() {
	}

	public TEmailVsUtenti(TEmailVsUtentiId id, TValDizionario TValDizionario, TUtentiModPec TUtentiModPec, TEmailMgo TEmailMgo, Date tsAggStato, Date tsIns,
			Date tsUltimoAgg) {
		this.id = id;
		this.TValDizionario = TValDizionario;
		this.TUtentiModPec = TUtentiModPec;
		this.TEmailMgo = TEmailMgo;
		this.tsAggStato = tsAggStato;
		this.tsIns = tsIns;
		this.tsUltimoAgg = tsUltimoAgg;
	}

	public TEmailVsUtenti(TEmailVsUtentiId id, TValDizionario TValDizionario, TUtentiModPec TUtentiModPec, TEmailMgo TEmailMgo, Date tsAggStato, Date tsIns,
			String idUteIns, Date tsUltimoAgg, String idUteUltimoAgg) {
		this.id = id;
		this.TValDizionario = TValDizionario;
		this.TUtentiModPec = TUtentiModPec;
		this.TEmailMgo = TEmailMgo;
		this.tsAggStato = tsAggStato;
		this.tsIns = tsIns;
		this.idUteIns = idUteIns;
		this.tsUltimoAgg = tsUltimoAgg;
		this.idUteUltimoAgg = idUteUltimoAgg;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "idEmail", column = @Column(name = "ID_EMAIL", nullable = false, length = 64)),
			@AttributeOverride(name = "idUtente", column = @Column(name = "ID_UTENTE", nullable = false, length = 64)) })
	public TEmailVsUtentiId getId() {
		return this.id;
	}

	public void setId(TEmailVsUtentiId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_REC_DIZ_STATO_EMAIL", nullable = false)
	public TValDizionario getTValDizionario() {
		return this.TValDizionario;
	}

	public void setTValDizionario(TValDizionario TValDizionario) {
		this.TValDizionario = TValDizionario;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_UTENTE", nullable = false, insertable = false, updatable = false)
	public TUtentiModPec getTUtentiModPec() {
		return this.TUtentiModPec;
	}

	public void setTUtentiModPec(TUtentiModPec TUtentiModPec) {
		this.TUtentiModPec = TUtentiModPec;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_EMAIL", nullable = false, insertable = false, updatable = false)
	public TEmailMgo getTEmailMgo() {
		return this.TEmailMgo;
	}

	public void setTEmailMgo(TEmailMgo TEmailMgo) {
		this.TEmailMgo = TEmailMgo;
	}

	@Column(name = "TS_AGG_STATO", nullable = false, length = 7)
	public Date getTsAggStato() {
		return this.tsAggStato;
	}

	public void setTsAggStato(Date tsAggStato) {
		this.tsAggStato = tsAggStato;
	}

	@Column(name = "TS_INS", nullable = false)
	public Date getTsIns() {
		return this.tsIns;
	}

	public void setTsIns(Date tsIns) {
		this.tsIns = tsIns;
	}

	@Column(name = "ID_UTE_INS", length = 64)
	public String getIdUteIns() {
		return this.idUteIns;
	}

	public void setIdUteIns(String idUteIns) {
		this.idUteIns = idUteIns;
	}

	@Column(name = "TS_ULTIMO_AGG", nullable = false)
	public Date getTsUltimoAgg() {
		return this.tsUltimoAgg;
	}

	public void setTsUltimoAgg(Date tsUltimoAgg) {
		this.tsUltimoAgg = tsUltimoAgg;
	}

	@Column(name = "ID_UTE_ULTIMO_AGG", length = 64)
	public String getIdUteUltimoAgg() {
		return this.idUteUltimoAgg;
	}

	public void setIdUteUltimoAgg(String idUteUltimoAgg) {
		this.idUteUltimoAgg = idUteUltimoAgg;
	}

}
