/* * SPDX-License-Identifier: AGPL-3.0-or-later * * C Copyright 2023 Regione Piemonte * */

// Generated 2-feb-2017 16.02.31 by Hibernate Tools 3.5.0.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import org.apache.commons.lang3.StringUtils;

/**
 * TEmailMgo generated by hbm2java
 */
@Entity
@Table(name = "T_EMAIL_MGO", uniqueConstraints = @UniqueConstraint(columnNames = { "MESSAGE_ID", "ID_CASELLA" }))
@org.hibernate.annotations.Entity(dynamicUpdate = true, dynamicInsert = true)
public class TEmailMgo implements java.io.Serializable {

	private static final long serialVersionUID = 5149579325738595295L;
	private String idEmail;
	private TUtentiModPec TUtentiModPecByIdUtenteAggStatoLav;
	private TUtentiModPec TUtentiModPecByIdUtenteLock;
	private TUtentiModPec TUtentiModPecByIdUtenteAssegn;
	private TValDizionario TValDizionarioByIdRecDizOperLock;
	private TValDizionario TValDizionarioByIdRecDizContrassegno;
	private TAnagFruitoriCaselle TAnagFruitoriCaselle;
	private MailboxAccount mailboxAccount;
	private String messageId;
	private String flgIo;
	private String categoria;
	private long dimensione;
	private String uriEmail;
	private boolean flgSpam;
	private String flgStatoSpam;
	private String flgRicevutaCbs;
	private String statoConsolidamento;
	private short nroAllegati;
	private short nroAllegatiFirmati;
	private boolean flgEmailFirmata;
	private boolean flgNoAssocAuto;
	private String accountMittente;
	private String oggetto;
	private String corpo;
	private String avvertimenti;
	private Date tsLock;
	private boolean flgRichConferma;
	private Date tsRicezione;
	private Date tsInvio;
	private Date tsInvioClient;
	private Date tsAssegn;
	private boolean flgInviataRisposta;
	private boolean flgInoltrata;
	private String flgStatoProt;
	private boolean flgNotifInteropEcc;
	private boolean flgNotifInteropConf;
	private boolean flgNotifInteropAgg;
	private boolean flgNotifInteropAnn;
	private Long livPriorita;
	private Date tsLettura;
	private Date tsIns;
	private String idUteIns;
	private Date tsUltimoAgg;
	private String idUteUltimoAgg;
	private String accountMittenteCtx;
	private String oggettoCtx;
	private String corpoCtx;
	private String siglaRegistroMitt;
	private Integer numRegMitt;
	private Short annoRegMitt;
	private Date tsRegMitt;
	private String oggettoRegMitt;
	private String oggettoRegMittCtx;
	private String statoLavorazione;
	private boolean flgRichConfLettura;
	private String messageIdTrasporto;
	private String codAzioneDaFare;
	private String dettAzioneDaFare;
	private BigDecimal progrMsg;
	private BigDecimal annoProgrMsg;
	private String registroProgrMsg;
	private Date tsAggStatoLavorazione;
	private String statoInvio;
	private String statoAccettazione;
	private String statoConsegna;
	private String motivoEccezione;
	private BigDecimal progrBozza;
	private Short annoProgrBozza;
	private String messageIdRif;
	private String errMessageRicPec;
	private Boolean flgUriRicevuta;		// Modifica necessaria per bypassare il problema del valore della colonna di default a Milano.
	private String nroRichiestaMassivaInvio;
	private Set<TAssegnEmail> TAssegnEmails = new HashSet<TAssegnEmail>(0);
	private Set<TRegEstVsEmail> TRegEstVsEmailsForIdEmailInviata = new HashSet<TRegEstVsEmail>(0);
	private Set<TSchedeDocVsEmail> TSchedeDocVsEmails = new HashSet<TSchedeDocVsEmail>(0);
	private Set<TEmailVsUtenti> TEmailVsUtentis = new HashSet<TEmailVsUtenti>(0);
	private Set<TRelEmailFolder> TRelEmailFolders = new HashSet<TRelEmailFolder>(0);
	private Set<TRegProtVsEmail> TRegProtVsEmails = new HashSet<TRegProtVsEmail>(0);
	private Set<TRelEmailMgo> TRelEmailMgosForIdEmail1 = new HashSet<TRelEmailMgo>(0);
	private Set<TRelEmailMgo> TRelEmailMgosForIdEmail2 = new HashSet<TRelEmailMgo>(0);
	private Set<TRegEstVsEmail> TRegEstVsEmailsForIdEmailRicevuta = new HashSet<TRegEstVsEmail>(0);
	private Set<TAttachEmailMgo> TAttachEmailMgos = new HashSet<TAttachEmailMgo>(0);
	private Set<TDestinatariEmailMgo> TDestinatariEmailMgos = new HashSet<TDestinatariEmailMgo>(0);

	/*
	AURIGA-581
	Gestire tag reply-to nell'operazione di risposta delle mail 
	inviate da mailui + salvarlo in campo REPLY_TO della T_EMAIL_MGO
	*/
	private String replyTo;
	
	/*
	AURIGA-600
	conversione testo mail in pdf
	*/
	private String uriCorpo;

	private String errArchUriCorpo;
	private String scCorpoMail;

	
	public TEmailMgo() {
	}

	public TEmailMgo(String idEmail, MailboxAccount mailboxAccount, String messageId, String categoria, long dimensione, String uriEmail, boolean flgSpam,
			short nroAllegati, short nroAllegatiFirmati, boolean flgEmailFirmata, boolean flgNoAssocAuto, boolean flgRichConferma, boolean flgInviataRisposta,
			boolean flgInoltrata, boolean flgNotifInteropEcc, boolean flgNotifInteropConf, boolean flgNotifInteropAgg, boolean flgNotifInteropAnn, Date tsIns,
			Date tsUltimoAgg, boolean flgRichConfLettura) {
		this.idEmail = idEmail;
		this.mailboxAccount = mailboxAccount;
		this.messageId = messageId;
		this.categoria = categoria;
		this.dimensione = dimensione;
		this.uriEmail = uriEmail;
		this.flgSpam = flgSpam;
		this.nroAllegati = nroAllegati;
		this.nroAllegatiFirmati = nroAllegatiFirmati;
		this.flgEmailFirmata = flgEmailFirmata;
		this.flgNoAssocAuto = flgNoAssocAuto;
		this.flgRichConferma = flgRichConferma;
		this.flgInviataRisposta = flgInviataRisposta;
		this.flgInoltrata = flgInoltrata;
		this.flgNotifInteropEcc = flgNotifInteropEcc;
		this.flgNotifInteropConf = flgNotifInteropConf;
		this.flgNotifInteropAgg = flgNotifInteropAgg;
		this.flgNotifInteropAnn = flgNotifInteropAnn;
		this.tsIns = tsIns;
		this.tsUltimoAgg = tsUltimoAgg;
		this.flgRichConfLettura = flgRichConfLettura;
	}

	public TEmailMgo(String idEmail, TUtentiModPec TUtentiModPecByIdUtenteAggStatoLav, TUtentiModPec TUtentiModPecByIdUtenteLock,
			TUtentiModPec TUtentiModPecByIdUtenteAssegn, TValDizionario TValDizionarioByIdRecDizOperLock, TValDizionario TValDizionarioByIdRecDizContrassegno,
			TAnagFruitoriCaselle TAnagFruitoriCaselle, MailboxAccount mailboxAccount, String messageId, String flgIo, String categoria, long dimensione,
			String uriEmail, boolean flgSpam, String flgStatoSpam, String flgRicevutaCbs, String statoConsolidamento, short nroAllegati,
			short nroAllegatiFirmati, boolean flgEmailFirmata, boolean flgNoAssocAuto, String accountMittente, String oggetto, String corpo,
			String avvertimenti, Date tsLock, boolean flgRichConferma, Date tsRicezione, Date tsInvio, Date tsInvioClient, Date tsAssegn,
			boolean flgInviataRisposta, boolean flgInoltrata, String flgStatoProt, boolean flgNotifInteropEcc, boolean flgNotifInteropConf,
			boolean flgNotifInteropAgg, boolean flgNotifInteropAnn, Long livPriorita, Date tsLettura, Date tsIns, String idUteIns, Date tsUltimoAgg,
			String idUteUltimoAgg, String accountMittenteCtx, String oggettoCtx, String corpoCtx, String siglaRegistroMitt, Integer numRegMitt,
			Short annoRegMitt, Date tsRegMitt, String oggettoRegMitt, String oggettoRegMittCtx, String statoLavorazione, boolean flgRichConfLettura,
			String messageIdTrasporto, String codAzioneDaFare, String dettAzioneDaFare, BigDecimal progrMsg, BigDecimal annoProgrMsg, String registroProgrMsg,
			Date tsAggStatoLavorazione, String statoInvio, String statoAccettazione, String statoConsegna, String motivoEccezione, BigDecimal progrBozza,
			Short annoProgrBozza, String messageIdRif, String errMessageRicPec, Boolean flgUriRicevuta, Set<TAssegnEmail> TAssegnEmails,
			Set<TRegEstVsEmail> TRegEstVsEmailsForIdEmailInviata, Set<TSchedeDocVsEmail> TSchedeDocVsEmails, Set<TEmailVsUtenti> TEmailVsUtentis,
			Set<TRelEmailFolder> TRelEmailFolders, Set<TRegProtVsEmail> TRegProtVsEmails, Set<TRelEmailMgo> TRelEmailMgosForIdEmail1,
			Set<TRelEmailMgo> TRelEmailMgosForIdEmail2, Set<TRegEstVsEmail> TRegEstVsEmailsForIdEmailRicevuta, Set<TAttachEmailMgo> TAttachEmailMgos,
			Set<TDestinatariEmailMgo> TDestinatariEmailMgos) {
		this.idEmail = idEmail;
		this.TUtentiModPecByIdUtenteAggStatoLav = TUtentiModPecByIdUtenteAggStatoLav;
		this.TUtentiModPecByIdUtenteLock = TUtentiModPecByIdUtenteLock;
		this.TUtentiModPecByIdUtenteAssegn = TUtentiModPecByIdUtenteAssegn;
		this.TValDizionarioByIdRecDizOperLock = TValDizionarioByIdRecDizOperLock;
		this.TValDizionarioByIdRecDizContrassegno = TValDizionarioByIdRecDizContrassegno;
		this.TAnagFruitoriCaselle = TAnagFruitoriCaselle;
		this.mailboxAccount = mailboxAccount;
		this.messageId = messageId;
		this.flgIo = flgIo;
		this.categoria = categoria;
		this.dimensione = dimensione;
		this.uriEmail = uriEmail;
		this.flgSpam = flgSpam;
		this.flgStatoSpam = flgStatoSpam;
		this.flgRicevutaCbs = flgRicevutaCbs;
		this.statoConsolidamento = statoConsolidamento;
		this.nroAllegati = nroAllegati;
		this.nroAllegatiFirmati = nroAllegatiFirmati;
		this.flgEmailFirmata = flgEmailFirmata;
		this.flgNoAssocAuto = flgNoAssocAuto;
		this.accountMittente = accountMittente;
		this.oggetto = oggetto;
		this.corpo = corpo;
		this.avvertimenti = avvertimenti;
		this.tsLock = tsLock;
		this.flgRichConferma = flgRichConferma;
		this.tsRicezione = tsRicezione;
		this.tsInvio = tsInvio;
		this.tsInvioClient = tsInvioClient;
		this.tsAssegn = tsAssegn;
		this.flgInviataRisposta = flgInviataRisposta;
		this.flgInoltrata = flgInoltrata;
		this.flgStatoProt = flgStatoProt;
		this.flgNotifInteropEcc = flgNotifInteropEcc;
		this.flgNotifInteropConf = flgNotifInteropConf;
		this.flgNotifInteropAgg = flgNotifInteropAgg;
		this.flgNotifInteropAnn = flgNotifInteropAnn;
		this.livPriorita = livPriorita;
		this.tsLettura = tsLettura;
		this.tsIns = tsIns;
		this.idUteIns = idUteIns;
		this.tsUltimoAgg = tsUltimoAgg;
		this.idUteUltimoAgg = idUteUltimoAgg;
		this.accountMittenteCtx = accountMittenteCtx;
		this.oggettoCtx = oggettoCtx;
		this.corpoCtx = corpoCtx;
		this.siglaRegistroMitt = siglaRegistroMitt;
		this.numRegMitt = numRegMitt;
		this.annoRegMitt = annoRegMitt;
		this.tsRegMitt = tsRegMitt;
		this.oggettoRegMitt = oggettoRegMitt;
		this.oggettoRegMittCtx = oggettoRegMittCtx;
		this.statoLavorazione = statoLavorazione;
		this.flgRichConfLettura = flgRichConfLettura;
		this.messageIdTrasporto = messageIdTrasporto;
		this.codAzioneDaFare = codAzioneDaFare;
		this.dettAzioneDaFare = dettAzioneDaFare;
		this.progrMsg = progrMsg;
		this.annoProgrMsg = annoProgrMsg;
		this.registroProgrMsg = registroProgrMsg;
		this.tsAggStatoLavorazione = tsAggStatoLavorazione;
		this.statoInvio = statoInvio;
		this.statoAccettazione = statoAccettazione;
		this.statoConsegna = statoConsegna;
		this.motivoEccezione = motivoEccezione;
		this.progrBozza = progrBozza;
		this.annoProgrBozza = annoProgrBozza;
		this.messageIdRif = messageIdRif;
		this.errMessageRicPec = errMessageRicPec;
		if (flgUriRicevuta != null) {
			this.flgUriRicevuta = flgUriRicevuta;
		} else {
			flgUriRicevuta = false;
		}
		this.TAssegnEmails = TAssegnEmails;
		this.TRegEstVsEmailsForIdEmailInviata = TRegEstVsEmailsForIdEmailInviata;
		this.TSchedeDocVsEmails = TSchedeDocVsEmails;
		this.TEmailVsUtentis = TEmailVsUtentis;
		this.TRelEmailFolders = TRelEmailFolders;
		this.TRegProtVsEmails = TRegProtVsEmails;
		this.TRelEmailMgosForIdEmail1 = TRelEmailMgosForIdEmail1;
		this.TRelEmailMgosForIdEmail2 = TRelEmailMgosForIdEmail2;
		this.TRegEstVsEmailsForIdEmailRicevuta = TRegEstVsEmailsForIdEmailRicevuta;
		this.TAttachEmailMgos = TAttachEmailMgos;
		this.TDestinatariEmailMgos = TDestinatariEmailMgos;
	}

	@Id

	@Column(name = "ID_EMAIL", unique = true, nullable = false, length = 64)
	public String getIdEmail() {
		return this.idEmail;
	}

	public void setIdEmail(String idEmail) {
		this.idEmail = idEmail;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_UTENTE_AGG_STATO_LAV")
	public TUtentiModPec getTUtentiModPecByIdUtenteAggStatoLav() {
		return this.TUtentiModPecByIdUtenteAggStatoLav;
	}

	public void setTUtentiModPecByIdUtenteAggStatoLav(TUtentiModPec TUtentiModPecByIdUtenteAggStatoLav) {
		this.TUtentiModPecByIdUtenteAggStatoLav = TUtentiModPecByIdUtenteAggStatoLav;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_UTENTE_LOCK")
	public TUtentiModPec getTUtentiModPecByIdUtenteLock() {
		return this.TUtentiModPecByIdUtenteLock;
	}

	public void setTUtentiModPecByIdUtenteLock(TUtentiModPec TUtentiModPecByIdUtenteLock) {
		this.TUtentiModPecByIdUtenteLock = TUtentiModPecByIdUtenteLock;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_UTENTE_ASSEGN")
	public TUtentiModPec getTUtentiModPecByIdUtenteAssegn() {
		return this.TUtentiModPecByIdUtenteAssegn;
	}

	public void setTUtentiModPecByIdUtenteAssegn(TUtentiModPec TUtentiModPecByIdUtenteAssegn) {
		this.TUtentiModPecByIdUtenteAssegn = TUtentiModPecByIdUtenteAssegn;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_REC_DIZ_OPER_LOCK")
	public TValDizionario getTValDizionarioByIdRecDizOperLock() {
		return this.TValDizionarioByIdRecDizOperLock;
	}

	public void setTValDizionarioByIdRecDizOperLock(TValDizionario TValDizionarioByIdRecDizOperLock) {
		this.TValDizionarioByIdRecDizOperLock = TValDizionarioByIdRecDizOperLock;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_REC_DIZ_CONTRASSEGNO")
	public TValDizionario getTValDizionarioByIdRecDizContrassegno() {
		return this.TValDizionarioByIdRecDizContrassegno;
	}

	public void setTValDizionarioByIdRecDizContrassegno(TValDizionario TValDizionarioByIdRecDizContrassegno) {
		this.TValDizionarioByIdRecDizContrassegno = TValDizionarioByIdRecDizContrassegno;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_UO_ASSEGN")
	public TAnagFruitoriCaselle getTAnagFruitoriCaselle() {
		return this.TAnagFruitoriCaselle;
	}

	public void setTAnagFruitoriCaselle(TAnagFruitoriCaselle TAnagFruitoriCaselle) {
		this.TAnagFruitoriCaselle = TAnagFruitoriCaselle;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_CASELLA", nullable = false)
	public MailboxAccount getMailboxAccount() {
		return this.mailboxAccount;
	}

	public void setMailboxAccount(MailboxAccount mailboxAccount) {
		this.mailboxAccount = mailboxAccount;
	}

	@Column(name = "MESSAGE_ID", nullable = false, length = 500)
	public String getMessageId() {
		return this.messageId;
	}

	public void setMessageId(String messageId) {
		this.messageId = messageId;
	}

	@Column(name = "FLG_IO", length = 1)
	public String getFlgIo() {
		return this.flgIo;
	}

	public void setFlgIo(String flgIo) {
		this.flgIo = flgIo;
	}

	@Column(name = "CATEGORIA", nullable = false, length = 30)
	public String getCategoria() {
		return this.categoria;
	}

	public void setCategoria(String categoria) {
		this.categoria = categoria;
	}

	@Column(name = "DIMENSIONE", nullable = false, precision = 10, scale = 0)
	public long getDimensione() {
		return this.dimensione;
	}

	public void setDimensione(long dimensione) {
		this.dimensione = dimensione;
	}

	@Column(name = "URI_EMAIL", nullable = false, length = 2000)
	public String getUriEmail() {
		return this.uriEmail;
	}

	public void setUriEmail(String uriEmail) {
		this.uriEmail = uriEmail;
	}

	@Column(name = "FLG_SPAM", nullable = false, precision = 1, scale = 0)
	public boolean isFlgSpam() {
		return this.flgSpam;
	}

	public void setFlgSpam(boolean flgSpam) {
		this.flgSpam = flgSpam;
	}

	@Column(name = "FLG_STATO_SPAM", length = 2)
	public String getFlgStatoSpam() {
		return this.flgStatoSpam;
	}

	public void setFlgStatoSpam(String flgStatoSpam) {
		this.flgStatoSpam = flgStatoSpam;
	}

	@Column(name = "FLG_RICEVUTA_CBS", length = 1)
	public String getFlgRicevutaCbs() {
		return this.flgRicevutaCbs;
	}

	public void setFlgRicevutaCbs(String flgRicevutaCbs) {
		this.flgRicevutaCbs = flgRicevutaCbs;
	}

	@Column(name = "STATO_CONSOLIDAMENTO", length = 30)
	public String getStatoConsolidamento() {
		return this.statoConsolidamento;
	}

	public void setStatoConsolidamento(String statoConsolidamento) {
		this.statoConsolidamento = statoConsolidamento;
	}

	@Column(name = "NRO_ALLEGATI", nullable = false, precision = 4, scale = 0)
	public short getNroAllegati() {
		return this.nroAllegati;
	}

	public void setNroAllegati(short nroAllegati) {
		this.nroAllegati = nroAllegati;
	}

	@Column(name = "NRO_ALLEGATI_FIRMATI", nullable = false, precision = 4, scale = 0)
	public short getNroAllegatiFirmati() {
		return this.nroAllegatiFirmati;
	}

	public void setNroAllegatiFirmati(short nroAllegatiFirmati) {
		this.nroAllegatiFirmati = nroAllegatiFirmati;
	}

	@Column(name = "FLG_EMAIL_FIRMATA", nullable = false, precision = 1, scale = 0)
	public boolean isFlgEmailFirmata() {
		return this.flgEmailFirmata;
	}

	public void setFlgEmailFirmata(boolean flgEmailFirmata) {
		this.flgEmailFirmata = flgEmailFirmata;
	}

	@Column(name = "FLG_NO_ASSOC_AUTO", nullable = false, precision = 1, scale = 0)
	public boolean isFlgNoAssocAuto() {
		return this.flgNoAssocAuto;
	}

	public void setFlgNoAssocAuto(boolean flgNoAssocAuto) {
		this.flgNoAssocAuto = flgNoAssocAuto;
	}

	@Column(name = "ACCOUNT_MITTENTE", length = 150)
	public String getAccountMittente() {
		return this.accountMittente;
	}

	public void setAccountMittente(String accountMittente) {
		this.accountMittente = accountMittente;
	}

	@Column(name = "OGGETTO", length = 4000)
	public String getOggetto() {
		return this.oggetto;
	}

	public void setOggetto(String oggetto) {
		this.oggetto = oggetto;
	}

	@Column(name = "CORPO")
	public String getCorpo() {
		return this.corpo;
	}

	public void setCorpo(String corpo) {
		this.corpo = corpo;
	}

	@Column(name = "AVVERTIMENTI", length = 4000)
	public String getAvvertimenti() {
		return this.avvertimenti;
	}

	public void setAvvertimenti(String avvertimenti) {
		// Tronco gli avvertimenti a 4000
		if (StringUtils.isNotEmpty(avvertimenti) && avvertimenti.length() > 4000) {
			avvertimenti = avvertimenti.substring(0, 4000);
		}
		this.avvertimenti = avvertimenti;
	}

	@Column(name = "TS_LOCK", length = 7)
	public Date getTsLock() {
		return this.tsLock;
	}

	public void setTsLock(Date tsLock) {
		this.tsLock = tsLock;
	}

	@Column(name = "FLG_RICH_CONFERMA", nullable = false, precision = 1, scale = 0)
	public boolean isFlgRichConferma() {
		return this.flgRichConferma;
	}

	public void setFlgRichConferma(boolean flgRichConferma) {
		this.flgRichConferma = flgRichConferma;
	}

	@Column(name = "TS_RICEZIONE", length = 7)
	public Date getTsRicezione() {
		return this.tsRicezione;
	}

	public void setTsRicezione(Date tsRicezione) {
		this.tsRicezione = tsRicezione;
	}

	@Column(name = "TS_INVIO", length = 7)
	public Date getTsInvio() {
		return this.tsInvio;
	}

	public void setTsInvio(Date tsInvio) {
		this.tsInvio = tsInvio;
	}

	@Column(name = "TS_INVIO_CLIENT", length = 7)
	public Date getTsInvioClient() {
		return this.tsInvioClient;
	}

	public void setTsInvioClient(Date tsInvioClient) {
		this.tsInvioClient = tsInvioClient;
	}

	@Column(name = "TS_ASSEGN", length = 7)
	public Date getTsAssegn() {
		return this.tsAssegn;
	}

	public void setTsAssegn(Date tsAssegn) {
		this.tsAssegn = tsAssegn;
	}

	@Column(name = "FLG_INVIATA_RISPOSTA", nullable = false, precision = 1, scale = 0)
	public boolean isFlgInviataRisposta() {
		return this.flgInviataRisposta;
	}

	public void setFlgInviataRisposta(boolean flgInviataRisposta) {
		this.flgInviataRisposta = flgInviataRisposta;
	}

	@Column(name = "FLG_INOLTRATA", nullable = false, precision = 1, scale = 0)
	public boolean isFlgInoltrata() {
		return this.flgInoltrata;
	}

	public void setFlgInoltrata(boolean flgInoltrata) {
		this.flgInoltrata = flgInoltrata;
	}

	@Column(name = "FLG_STATO_PROT", length = 1)
	public String getFlgStatoProt() {
		return this.flgStatoProt;
	}

	public void setFlgStatoProt(String flgStatoProt) {
		this.flgStatoProt = flgStatoProt;
	}

	@Column(name = "FLG_NOTIF_INTEROP_ECC", nullable = false, precision = 1, scale = 0)
	public boolean isFlgNotifInteropEcc() {
		return this.flgNotifInteropEcc;
	}

	public void setFlgNotifInteropEcc(boolean flgNotifInteropEcc) {
		this.flgNotifInteropEcc = flgNotifInteropEcc;
	}

	@Column(name = "FLG_NOTIF_INTEROP_CONF", nullable = false, precision = 1, scale = 0)
	public boolean isFlgNotifInteropConf() {
		return this.flgNotifInteropConf;
	}

	public void setFlgNotifInteropConf(boolean flgNotifInteropConf) {
		this.flgNotifInteropConf = flgNotifInteropConf;
	}

	@Column(name = "FLG_NOTIF_INTEROP_AGG", nullable = false, precision = 1, scale = 0)
	public boolean isFlgNotifInteropAgg() {
		return this.flgNotifInteropAgg;
	}

	public void setFlgNotifInteropAgg(boolean flgNotifInteropAgg) {
		this.flgNotifInteropAgg = flgNotifInteropAgg;
	}

	@Column(name = "FLG_NOTIF_INTEROP_ANN", nullable = false, precision = 1, scale = 0)
	public boolean isFlgNotifInteropAnn() {
		return this.flgNotifInteropAnn;
	}

	public void setFlgNotifInteropAnn(boolean flgNotifInteropAnn) {
		this.flgNotifInteropAnn = flgNotifInteropAnn;
	}

	@Column(name = "LIV_PRIORITA", precision = 10, scale = 0)
	public Long getLivPriorita() {
		return this.livPriorita;
	}

	public void setLivPriorita(Long livPriorita) {
		this.livPriorita = livPriorita;
	}

	@Column(name = "TS_LETTURA", length = 7)
	public Date getTsLettura() {
		return this.tsLettura;
	}

	public void setTsLettura(Date tsLettura) {
		this.tsLettura = tsLettura;
	}

	@Column(name = "TS_INS", nullable = false)
	public Date getTsIns() {
		return this.tsIns;
	}

	public void setTsIns(Date tsIns) {
		this.tsIns = tsIns;
	}

	@Column(name = "ID_UTE_INS", length = 64)
	public String getIdUteIns() {
		return this.idUteIns;
	}

	public void setIdUteIns(String idUteIns) {
		this.idUteIns = idUteIns;
	}

	@Column(name = "TS_ULTIMO_AGG", nullable = false)
	public Date getTsUltimoAgg() {
		return this.tsUltimoAgg;
	}

	public void setTsUltimoAgg(Date tsUltimoAgg) {
		this.tsUltimoAgg = tsUltimoAgg;
	}

	@Column(name = "ID_UTE_ULTIMO_AGG", length = 64)
	public String getIdUteUltimoAgg() {
		return this.idUteUltimoAgg;
	}

	public void setIdUteUltimoAgg(String idUteUltimoAgg) {
		this.idUteUltimoAgg = idUteUltimoAgg;
	}

	@Column(name = "ACCOUNT_MITTENTE_CTX", length = 200)
	public String getAccountMittenteCtx() {
		return this.accountMittenteCtx;
	}

	public void setAccountMittenteCtx(String accountMittenteCtx) {
		this.accountMittenteCtx = accountMittenteCtx;
	}

	@Column(name = "OGGETTO_CTX", length = 4000)
	public String getOggettoCtx() {
		return this.oggettoCtx;
	}

	public void setOggettoCtx(String oggettoCtx) {
		this.oggettoCtx = oggettoCtx;
	}

	@Column(name = "CORPO_CTX")
	public String getCorpoCtx() {
		return this.corpoCtx;
	}

	public void setCorpoCtx(String corpoCtx) {
		this.corpoCtx = corpoCtx;
	}

	@Column(name = "SIGLA_REGISTRO_MITT", length = 100)
	public String getSiglaRegistroMitt() {
		return this.siglaRegistroMitt;
	}

	public void setSiglaRegistroMitt(String siglaRegistroMitt) {
		this.siglaRegistroMitt = siglaRegistroMitt;
	}

	@Column(name = "NUM_REG_MITT", precision = 7, scale = 0)
	public Integer getNumRegMitt() {
		return this.numRegMitt;
	}

	public void setNumRegMitt(Integer numRegMitt) {
		this.numRegMitt = numRegMitt;
	}

	@Column(name = "ANNO_REG_MITT", precision = 4, scale = 0)
	public Short getAnnoRegMitt() {
		return this.annoRegMitt;
	}

	public void setAnnoRegMitt(Short annoRegMitt) {
		this.annoRegMitt = annoRegMitt;
	}

	@Column(name = "TS_REG_MITT", length = 7)
	public Date getTsRegMitt() {
		return this.tsRegMitt;
	}

	public void setTsRegMitt(Date tsRegMitt) {
		this.tsRegMitt = tsRegMitt;
	}

	@Column(name = "OGGETTO_REG_MITT")
	public String getOggettoRegMitt() {
		return this.oggettoRegMitt;
	}

	public void setOggettoRegMitt(String oggettoRegMitt) {
		this.oggettoRegMitt = oggettoRegMitt;
	}

	@Column(name = "OGGETTO_REG_MITT_CTX")
	public String getOggettoRegMittCtx() {
		return this.oggettoRegMittCtx;
	}

	public void setOggettoRegMittCtx(String oggettoRegMittCtx) {
		this.oggettoRegMittCtx = oggettoRegMittCtx;
	}

	@Column(name = "STATO_LAVORAZIONE", length = 30)
	public String getStatoLavorazione() {
		return this.statoLavorazione;
	}

	public void setStatoLavorazione(String statoLavorazione) {
		this.statoLavorazione = statoLavorazione;
	}

	@Column(name = "FLG_RICH_CONF_LETTURA", nullable = false, precision = 1, scale = 0)
	public boolean isFlgRichConfLettura() {
		return this.flgRichConfLettura;
	}

	public void setFlgRichConfLettura(boolean flgRichConfLettura) {
		this.flgRichConfLettura = flgRichConfLettura;
	}

	@Column(name = "MESSAGE_ID_TRASPORTO", length = 500)
	public String getMessageIdTrasporto() {
		return this.messageIdTrasporto;
	}

	public void setMessageIdTrasporto(String messageIdTrasporto) {
		this.messageIdTrasporto = messageIdTrasporto;
	}

	@Column(name = "COD_AZIONE_DA_FARE", length = 10)
	public String getCodAzioneDaFare() {
		return this.codAzioneDaFare;
	}

	public void setCodAzioneDaFare(String codAzioneDaFare) {
		this.codAzioneDaFare = codAzioneDaFare;
	}

	@Column(name = "DETT_AZIONE_DA_FARE", length = 4000)
	public String getDettAzioneDaFare() {
		return this.dettAzioneDaFare;
	}

	public void setDettAzioneDaFare(String dettAzioneDaFare) {
		this.dettAzioneDaFare = dettAzioneDaFare;
	}

	@Column(name = "PROGR_MSG", precision = 22, scale = 0)
	public BigDecimal getProgrMsg() {
		return this.progrMsg;
	}

	public void setProgrMsg(BigDecimal progrMsg) {
		this.progrMsg = progrMsg;
	}

	@Column(name = "ANNO_PROGR_MSG", precision = 22, scale = 0)
	public BigDecimal getAnnoProgrMsg() {
		return this.annoProgrMsg;
	}

	public void setAnnoProgrMsg(BigDecimal annoProgrMsg) {
		this.annoProgrMsg = annoProgrMsg;
	}

	@Column(name = "REGISTRO_PROGR_MSG", length = 10)
	public String getRegistroProgrMsg() {
		return this.registroProgrMsg;
	}

	public void setRegistroProgrMsg(String registroProgrMsg) {
		this.registroProgrMsg = registroProgrMsg;
	}

	@Column(name = "TS_AGG_STATO_LAVORAZIONE", length = 7)
	public Date getTsAggStatoLavorazione() {
		return this.tsAggStatoLavorazione;
	}

	public void setTsAggStatoLavorazione(Date tsAggStatoLavorazione) {
		this.tsAggStatoLavorazione = tsAggStatoLavorazione;
	}

	@Column(name = "STATO_INVIO", length = 2)
	public String getStatoInvio() {
		return this.statoInvio;
	}

	public void setStatoInvio(String statoInvio) {
		this.statoInvio = statoInvio;
	}

	@Column(name = "STATO_ACCETTAZIONE", length = 2)
	public String getStatoAccettazione() {
		return this.statoAccettazione;
	}

	public void setStatoAccettazione(String statoAccettazione) {
		this.statoAccettazione = statoAccettazione;
	}

	@Column(name = "STATO_CONSEGNA", length = 2)
	public String getStatoConsegna() {
		return this.statoConsegna;
	}

	public void setStatoConsegna(String statoConsegna) {
		this.statoConsegna = statoConsegna;
	}

	@Column(name = "MOTIVO_ECCEZIONE")
	public String getMotivoEccezione() {
		return this.motivoEccezione;
	}

	public void setMotivoEccezione(String motivoEccezione) {
		this.motivoEccezione = motivoEccezione;
	}

	@Column(name = "PROGR_BOZZA", precision = 22, scale = 0)
	public BigDecimal getProgrBozza() {
		return this.progrBozza;
	}

	public void setProgrBozza(BigDecimal progrBozza) {
		this.progrBozza = progrBozza;
	}

	@Column(name = "ANNO_PROGR_BOZZA", precision = 4, scale = 0)
	public Short getAnnoProgrBozza() {
		return this.annoProgrBozza;
	}

	public void setAnnoProgrBozza(Short annoProgrBozza) {
		this.annoProgrBozza = annoProgrBozza;
	}

	@Column(name = "MESSAGE_ID_RIF", length = 500)
	public String getMessageIdRif() {
		return this.messageIdRif;
	}

	public void setMessageIdRif(String messageIdRif) {
		this.messageIdRif = messageIdRif;
	}

	@Column(name = "ERR_MESSAGE_RIC_PEC")
	public String getErrMessageRicPec() {
		return this.errMessageRicPec;
	}

	public void setErrMessageRicPec(String errMessageRicPec) {
		this.errMessageRicPec = errMessageRicPec;
	}

	@Column(name = "FLG_URI_RICEVUTA", /*nullable = false,*/ precision = 1, scale = 0)
	public Boolean isFlgUriRicevuta() {
		return this.flgUriRicevuta;
	}

	public void setFlgUriRicevuta(Boolean flgUriRicevuta) {
		this.flgUriRicevuta = flgUriRicevuta;
	}

	@Column(name = "NRO_RICHIESTA_MASSIVA_INVIO", length = 100)
	public String getNroRichiestaMassivaInvio() {
		return this.nroRichiestaMassivaInvio;
	}

	public void setNroRichiestaMassivaInvio(String nroRichiestaMassivaInvio) {
		this.nroRichiestaMassivaInvio = nroRichiestaMassivaInvio;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TEmailMgo")
	public Set<TAssegnEmail> getTAssegnEmails() {
		return this.TAssegnEmails;
	}

	public void setTAssegnEmails(Set<TAssegnEmail> TAssegnEmails) {
		this.TAssegnEmails = TAssegnEmails;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TEmailMgoByIdEmailInviata")
	public Set<TRegEstVsEmail> getTRegEstVsEmailsForIdEmailInviata() {
		return this.TRegEstVsEmailsForIdEmailInviata;
	}

	public void setTRegEstVsEmailsForIdEmailInviata(Set<TRegEstVsEmail> TRegEstVsEmailsForIdEmailInviata) {
		this.TRegEstVsEmailsForIdEmailInviata = TRegEstVsEmailsForIdEmailInviata;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TEmailMgo")
	public Set<TSchedeDocVsEmail> getTSchedeDocVsEmails() {
		return this.TSchedeDocVsEmails;
	}

	public void setTSchedeDocVsEmails(Set<TSchedeDocVsEmail> TSchedeDocVsEmails) {
		this.TSchedeDocVsEmails = TSchedeDocVsEmails;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TEmailMgo")
	public Set<TEmailVsUtenti> getTEmailVsUtentis() {
		return this.TEmailVsUtentis;
	}

	public void setTEmailVsUtentis(Set<TEmailVsUtenti> TEmailVsUtentis) {
		this.TEmailVsUtentis = TEmailVsUtentis;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TEmailMgo")
	public Set<TRelEmailFolder> getTRelEmailFolders() {
		return this.TRelEmailFolders;
	}

	public void setTRelEmailFolders(Set<TRelEmailFolder> TRelEmailFolders) {
		this.TRelEmailFolders = TRelEmailFolders;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TEmailMgo")
	public Set<TRegProtVsEmail> getTRegProtVsEmails() {
		return this.TRegProtVsEmails;
	}

	public void setTRegProtVsEmails(Set<TRegProtVsEmail> TRegProtVsEmails) {
		this.TRegProtVsEmails = TRegProtVsEmails;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TEmailMgoByIdEmail1")
	public Set<TRelEmailMgo> getTRelEmailMgosForIdEmail1() {
		return this.TRelEmailMgosForIdEmail1;
	}

	public void setTRelEmailMgosForIdEmail1(Set<TRelEmailMgo> TRelEmailMgosForIdEmail1) {
		this.TRelEmailMgosForIdEmail1 = TRelEmailMgosForIdEmail1;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TEmailMgoByIdEmail2")
	public Set<TRelEmailMgo> getTRelEmailMgosForIdEmail2() {
		return this.TRelEmailMgosForIdEmail2;
	}

	public void setTRelEmailMgosForIdEmail2(Set<TRelEmailMgo> TRelEmailMgosForIdEmail2) {
		this.TRelEmailMgosForIdEmail2 = TRelEmailMgosForIdEmail2;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TEmailMgoByIdEmailRicevuta")
	public Set<TRegEstVsEmail> getTRegEstVsEmailsForIdEmailRicevuta() {
		return this.TRegEstVsEmailsForIdEmailRicevuta;
	}

	public void setTRegEstVsEmailsForIdEmailRicevuta(Set<TRegEstVsEmail> TRegEstVsEmailsForIdEmailRicevuta) {
		this.TRegEstVsEmailsForIdEmailRicevuta = TRegEstVsEmailsForIdEmailRicevuta;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TEmailMgo")
	public Set<TAttachEmailMgo> getTAttachEmailMgos() {
		return this.TAttachEmailMgos;
	}

	public void setTAttachEmailMgos(Set<TAttachEmailMgo> TAttachEmailMgos) {
		this.TAttachEmailMgos = TAttachEmailMgos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TEmailMgo")
	public Set<TDestinatariEmailMgo> getTDestinatariEmailMgos() {
		return this.TDestinatariEmailMgos;
	}

	public void setTDestinatariEmailMgos(Set<TDestinatariEmailMgo> TDestinatariEmailMgos) {
		this.TDestinatariEmailMgos = TDestinatariEmailMgos;
	}
	
	@Column(name = "REPLY_TO", length = 1000)
	public String getReplyTo() {
		return replyTo;
	}

	public void setReplyTo(String replyTo) {
		this.replyTo = replyTo;
	}

	@Column(name = "URI_CORPO", length = 1000)
	public String getUriCorpo() {
		return uriCorpo;
	}

	public void setUriCorpo(String uriCorpo) {
		this.uriCorpo = uriCorpo;
	}
	
	@Column(name = "ERR_ARCH_URI_CORPO")
	public String getErrArchUriCorpo() {
		return errArchUriCorpo;
	}

	public void setErrArchUriCorpo(String errArchUriCorpo) {
		this.errArchUriCorpo = errArchUriCorpo;
	}
	
	@Column(name = "SC_CORPO_MAIL")
	public String getScCorpoMail() {
		return scCorpoMail;
	}

	public void setScCorpoMail(String scCorpoMail) {
		this.scCorpoMail = scCorpoMail;
	}

	@Override
	public String toString() {
		return "TEmailMgo [idEmail=" + idEmail + ", TUtentiModPecByIdUtenteAggStatoLav="
				+ TUtentiModPecByIdUtenteAggStatoLav + ", TUtentiModPecByIdUtenteLock=" + TUtentiModPecByIdUtenteLock
				+ ", TUtentiModPecByIdUtenteAssegn=" + TUtentiModPecByIdUtenteAssegn
				+ ", TValDizionarioByIdRecDizOperLock=" + TValDizionarioByIdRecDizOperLock
				+ ", TValDizionarioByIdRecDizContrassegno=" + TValDizionarioByIdRecDizContrassegno
				+ ", TAnagFruitoriCaselle=" + TAnagFruitoriCaselle + ", mailboxAccount=" + mailboxAccount
				+ ", messageId=" + messageId + ", flgIo=" + flgIo + ", categoria=" + categoria + ", dimensione="
				+ dimensione + ", uriEmail=" + uriEmail + ", flgSpam=" + flgSpam + ", flgStatoSpam=" + flgStatoSpam
				+ ", flgRicevutaCbs=" + flgRicevutaCbs + ", statoConsolidamento=" + statoConsolidamento
				+ ", nroAllegati=" + nroAllegati + ", nroAllegatiFirmati=" + nroAllegatiFirmati + ", flgEmailFirmata="
				+ flgEmailFirmata + ", flgNoAssocAuto=" + flgNoAssocAuto + ", accountMittente=" + accountMittente
				+ ", oggetto=" + oggetto + ", corpo=" + corpo + ", avvertimenti=" + avvertimenti + ", tsLock=" + tsLock
				+ ", flgRichConferma=" + flgRichConferma + ", tsRicezione=" + tsRicezione + ", tsInvio=" + tsInvio
				+ ", tsInvioClient=" + tsInvioClient + ", tsAssegn=" + tsAssegn + ", flgInviataRisposta="
				+ flgInviataRisposta + ", flgInoltrata=" + flgInoltrata + ", flgStatoProt=" + flgStatoProt
				+ ", flgNotifInteropEcc=" + flgNotifInteropEcc + ", flgNotifInteropConf=" + flgNotifInteropConf
				+ ", flgNotifInteropAgg=" + flgNotifInteropAgg + ", flgNotifInteropAnn=" + flgNotifInteropAnn
				+ ", livPriorita=" + livPriorita + ", tsLettura=" + tsLettura + ", tsIns=" + tsIns + ", idUteIns="
				+ idUteIns + ", tsUltimoAgg=" + tsUltimoAgg + ", idUteUltimoAgg=" + idUteUltimoAgg
				+ ", accountMittenteCtx=" + accountMittenteCtx + ", oggettoCtx=" + oggettoCtx + ", corpoCtx=" + corpoCtx
				+ ", siglaRegistroMitt=" + siglaRegistroMitt + ", numRegMitt=" + numRegMitt + ", annoRegMitt="
				+ annoRegMitt + ", tsRegMitt=" + tsRegMitt + ", oggettoRegMitt=" + oggettoRegMitt
				+ ", oggettoRegMittCtx=" + oggettoRegMittCtx + ", statoLavorazione=" + statoLavorazione
				+ ", flgRichConfLettura=" + flgRichConfLettura + ", messageIdTrasporto=" + messageIdTrasporto
				+ ", codAzioneDaFare=" + codAzioneDaFare + ", dettAzioneDaFare=" + dettAzioneDaFare + ", progrMsg="
				+ progrMsg + ", annoProgrMsg=" + annoProgrMsg + ", registroProgrMsg=" + registroProgrMsg
				+ ", tsAggStatoLavorazione=" + tsAggStatoLavorazione + ", statoInvio=" + statoInvio
				+ ", statoAccettazione=" + statoAccettazione + ", statoConsegna=" + statoConsegna + ", motivoEccezione="
				+ motivoEccezione + ", progrBozza=" + progrBozza + ", annoProgrBozza=" + annoProgrBozza
				+ ", messageIdRif=" + messageIdRif + ", errMessageRicPec=" + errMessageRicPec + ", flgUriRicevuta="
				+ flgUriRicevuta + ", nroRichiestaMassivaInvio=" + nroRichiestaMassivaInvio + ", TAssegnEmails="
				+ TAssegnEmails + ", TRegEstVsEmailsForIdEmailInviata=" + TRegEstVsEmailsForIdEmailInviata
				+ ", TSchedeDocVsEmails=" + TSchedeDocVsEmails + ", TEmailVsUtentis=" + TEmailVsUtentis
				+ ", TRelEmailFolders=" + TRelEmailFolders + ", TRegProtVsEmails=" + TRegProtVsEmails
				+ ", TRelEmailMgosForIdEmail1=" + TRelEmailMgosForIdEmail1 + ", TRelEmailMgosForIdEmail2="
				+ TRelEmailMgosForIdEmail2 + ", TRegEstVsEmailsForIdEmailRicevuta=" + TRegEstVsEmailsForIdEmailRicevuta
				+ ", TAttachEmailMgos=" + TAttachEmailMgos + ", TDestinatariEmailMgos=" + TDestinatariEmailMgos
				+ ", replyTo=" + replyTo + ", uriCorpo=" + uriCorpo+ ", errArchUriCorpo=" + errArchUriCorpo+ ", scCorpoMail=" + scCorpoMail + "]";
	}

}
