/* * SPDX-License-Identifier: AGPL-3.0-or-later * * C Copyright 2023 Regione Piemonte * */

// Generated 2-feb-2017 16.02.31 by Hibernate Tools 3.5.0.Final

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TParameters generated by hbm2java
 */
@Entity(name = "it.eng.aurigamailbusiness.database.mail.TParameters")
@Table(name = "T_PARAMETERS")
public class TParameters implements java.io.Serializable {

	private static final long serialVersionUID = 6832809211460819171L;
	private String parKey;
	private String strValue;
	private Date dateValue;
	private BigDecimal numValue;
	private Date settingTime;
	private Date tsIns;
	private String meaning;

	public TParameters() {
	}

	public TParameters(String parKey, Date tsIns, String meaning) {
		this.parKey = parKey;
		this.tsIns = tsIns;
		this.meaning = meaning;
	}

	public TParameters(String parKey, String strValue, Date dateValue, BigDecimal numValue, Date settingTime, Date tsIns, String meaning) {
		this.parKey = parKey;
		this.strValue = strValue;
		this.dateValue = dateValue;
		this.numValue = numValue;
		this.settingTime = settingTime;
		this.tsIns = tsIns;
		this.meaning = meaning;
	}

	@Id
	@Column(name = "PAR_KEY", unique = true, nullable = false, length = 50)
	public String getParKey() {
		return this.parKey;
	}

	public void setParKey(String parKey) {
		this.parKey = parKey;
	}

	@Column(name = "STR_VALUE", length = 1000)
	public String getStrValue() {
		return this.strValue;
	}

	public void setStrValue(String strValue) {
		this.strValue = strValue;
	}

	@Column(name = "DATE_VALUE", length = 7)
	public Date getDateValue() {
		return this.dateValue;
	}

	public void setDateValue(Date dateValue) {
		this.dateValue = dateValue;
	}

	@Column(name = "NUM_VALUE", precision = 22, scale = 0)
	public BigDecimal getNumValue() {
		return this.numValue;
	}

	public void setNumValue(BigDecimal numValue) {
		this.numValue = numValue;
	}

	@Column(name = "SETTING_TIME")
	public Date getSettingTime() {
		return this.settingTime;
	}

	public void setSettingTime(Date settingTime) {
		this.settingTime = settingTime;
	}

	@Column(name = "TS_INS", nullable = false)
	public Date getTsIns() {
		return this.tsIns;
	}

	public void setTsIns(Date tsIns) {
		this.tsIns = tsIns;
	}

	@Column(name = "MEANING", nullable = false, length = 4000)
	public String getMeaning() {
		return this.meaning;
	}

	public void setMeaning(String meaning) {
		this.meaning = meaning;
	}

}
