/* * SPDX-License-Identifier: AGPL-3.0-or-later * * C Copyright 2023 Regione Piemonte * */

// Generated 2-feb-2017 16.02.31 by Hibernate Tools 3.5.0.Final

import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TProfiliUtentiMgo generated by hbm2java
 */
@Entity
@Table(name = "T_PROFILI_UTENTI_MGO")
public class TProfiliUtentiMgo implements java.io.Serializable {

	private static final long serialVersionUID = -2908629550760740694L;
	private TProfiliUtentiMgoId id;
	private TRelUtentiVsFruitori TRelUtentiVsFruitori;
	private TRelCaselleFruitori TRelCaselleFruitori;
	private boolean flgAnn;
	private Date tsIns;
	private String idUteIns;
	private Date tsUltimoAgg;
	private String idUteUltimoAgg;

	public TProfiliUtentiMgo() {
	}

	public TProfiliUtentiMgo(TProfiliUtentiMgoId id, TRelUtentiVsFruitori TRelUtentiVsFruitori, TRelCaselleFruitori TRelCaselleFruitori, boolean flgAnn,
			Date tsIns, Date tsUltimoAgg) {
		this.id = id;
		this.TRelUtentiVsFruitori = TRelUtentiVsFruitori;
		this.TRelCaselleFruitori = TRelCaselleFruitori;
		this.flgAnn = flgAnn;
		this.tsIns = tsIns;
		this.tsUltimoAgg = tsUltimoAgg;
	}

	public TProfiliUtentiMgo(TProfiliUtentiMgoId id, TRelUtentiVsFruitori TRelUtentiVsFruitori, TRelCaselleFruitori TRelCaselleFruitori, boolean flgAnn,
			Date tsIns, String idUteIns, Date tsUltimoAgg, String idUteUltimoAgg) {
		this.id = id;
		this.TRelUtentiVsFruitori = TRelUtentiVsFruitori;
		this.TRelCaselleFruitori = TRelCaselleFruitori;
		this.flgAnn = flgAnn;
		this.tsIns = tsIns;
		this.idUteIns = idUteIns;
		this.tsUltimoAgg = tsUltimoAgg;
		this.idUteUltimoAgg = idUteUltimoAgg;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "idRelUtenteFruitore", column = @Column(name = "ID_REL_UTENTE_FRUITORE", nullable = false, length = 64)),
			@AttributeOverride(name = "profilo", column = @Column(name = "PROFILO", nullable = false, length = 100)),
			@AttributeOverride(name = "idRelFruitoreCasella", column = @Column(name = "ID_REL_FRUITORE_CASELLA", nullable = false, length = 64)) })
	public TProfiliUtentiMgoId getId() {
		return this.id;
	}

	public void setId(TProfiliUtentiMgoId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_REL_UTENTE_FRUITORE", nullable = false, insertable = false, updatable = false)
	public TRelUtentiVsFruitori getTRelUtentiVsFruitori() {
		return this.TRelUtentiVsFruitori;
	}

	public void setTRelUtentiVsFruitori(TRelUtentiVsFruitori TRelUtentiVsFruitori) {
		this.TRelUtentiVsFruitori = TRelUtentiVsFruitori;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_REL_FRUITORE_CASELLA", nullable = false, insertable = false, updatable = false)
	public TRelCaselleFruitori getTRelCaselleFruitori() {
		return this.TRelCaselleFruitori;
	}

	public void setTRelCaselleFruitori(TRelCaselleFruitori TRelCaselleFruitori) {
		this.TRelCaselleFruitori = TRelCaselleFruitori;
	}

	@Column(name = "FLG_ANN", nullable = false, precision = 1, scale = 0)
	public boolean isFlgAnn() {
		return this.flgAnn;
	}

	public void setFlgAnn(boolean flgAnn) {
		this.flgAnn = flgAnn;
	}

	@Column(name = "TS_INS", nullable = false)
	public Date getTsIns() {
		return this.tsIns;
	}

	public void setTsIns(Date tsIns) {
		this.tsIns = tsIns;
	}

	@Column(name = "ID_UTE_INS", length = 64)
	public String getIdUteIns() {
		return this.idUteIns;
	}

	public void setIdUteIns(String idUteIns) {
		this.idUteIns = idUteIns;
	}

	@Column(name = "TS_ULTIMO_AGG", nullable = false)
	public Date getTsUltimoAgg() {
		return this.tsUltimoAgg;
	}

	public void setTsUltimoAgg(Date tsUltimoAgg) {
		this.tsUltimoAgg = tsUltimoAgg;
	}

	@Column(name = "ID_UTE_ULTIMO_AGG", length = 64)
	public String getIdUteUltimoAgg() {
		return this.idUteUltimoAgg;
	}

	public void setIdUteUltimoAgg(String idUteUltimoAgg) {
		this.idUteUltimoAgg = idUteUltimoAgg;
	}

}
