/* * SPDX-License-Identifier: AGPL-3.0-or-later * * C Copyright 2023 Regione Piemonte * */

// Generated 2-feb-2017 16.02.31 by Hibernate Tools 3.5.0.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * TRegProtVsEmail generated by hbm2java
 */
@Entity
@Table(name = "T_REG_PROT_VS_EMAIL", uniqueConstraints = @UniqueConstraint(columnNames = { "ID_EMAIL", "CATEGORIA_REG", "SIGLA_REGISTRO", "ANNO_REG",
		"NUM_REG" }))
public class TRegProtVsEmail implements java.io.Serializable {

	private static final long serialVersionUID = 4077037713743821699L;
	private String idRegProtEmail;
	private TEmailMgo TEmailMgo;
	private String categoriaReg;
	private String siglaRegistro;
	private short annoReg;
	private BigDecimal numReg;
	private Date tsReg;
	private String idProvReg;
	private Date tsIns;
	private String idUteIns;
	private Date tsUltimoAgg;
	private String idUteUltimoAgg;
	private Set<TAttachEmailMgo> TAttachEmailMgos = new HashSet<TAttachEmailMgo>(0);

	public TRegProtVsEmail() {
	}

	public TRegProtVsEmail(String idRegProtEmail, TEmailMgo TEmailMgo, String categoriaReg, short annoReg, BigDecimal numReg, Date tsIns, Date tsUltimoAgg) {
		this.idRegProtEmail = idRegProtEmail;
		this.TEmailMgo = TEmailMgo;
		this.categoriaReg = categoriaReg;
		this.annoReg = annoReg;
		this.numReg = numReg;
		this.tsIns = tsIns;
		this.tsUltimoAgg = tsUltimoAgg;
	}

	public TRegProtVsEmail(String idRegProtEmail, TEmailMgo TEmailMgo, String categoriaReg, String siglaRegistro, short annoReg, BigDecimal numReg, Date tsReg,
			String idProvReg, Date tsIns, String idUteIns, Date tsUltimoAgg, String idUteUltimoAgg, Set<TAttachEmailMgo> TAttachEmailMgos) {
		this.idRegProtEmail = idRegProtEmail;
		this.TEmailMgo = TEmailMgo;
		this.categoriaReg = categoriaReg;
		this.siglaRegistro = siglaRegistro;
		this.annoReg = annoReg;
		this.numReg = numReg;
		this.tsReg = tsReg;
		this.idProvReg = idProvReg;
		this.tsIns = tsIns;
		this.idUteIns = idUteIns;
		this.tsUltimoAgg = tsUltimoAgg;
		this.idUteUltimoAgg = idUteUltimoAgg;
		this.TAttachEmailMgos = TAttachEmailMgos;
	}

	@Id
	@Column(name = "ID_REG_PROT_EMAIL", unique = true, nullable = false, length = 64)
	public String getIdRegProtEmail() {
		return this.idRegProtEmail;
	}

	public void setIdRegProtEmail(String idRegProtEmail) {
		this.idRegProtEmail = idRegProtEmail;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_EMAIL", nullable = false)
	public TEmailMgo getTEmailMgo() {
		return this.TEmailMgo;
	}

	public void setTEmailMgo(TEmailMgo TEmailMgo) {
		this.TEmailMgo = TEmailMgo;
	}

	@Column(name = "CATEGORIA_REG", nullable = false, length = 2)
	public String getCategoriaReg() {
		return this.categoriaReg;
	}

	public void setCategoriaReg(String categoriaReg) {
		this.categoriaReg = categoriaReg;
	}

	@Column(name = "SIGLA_REGISTRO", length = 30)
	public String getSiglaRegistro() {
		return this.siglaRegistro;
	}

	public void setSiglaRegistro(String siglaRegistro) {
		this.siglaRegistro = siglaRegistro;
	}

	@Column(name = "ANNO_REG", nullable = false, precision = 4, scale = 0)
	public short getAnnoReg() {
		return this.annoReg;
	}

	public void setAnnoReg(short annoReg) {
		this.annoReg = annoReg;
	}

	@Column(name = "NUM_REG", nullable = false, precision = 22, scale = 0)
	public BigDecimal getNumReg() {
		return this.numReg;
	}

	public void setNumReg(BigDecimal numReg) {
		this.numReg = numReg;
	}

	@Column(name = "TS_REG", length = 7)
	public Date getTsReg() {
		return this.tsReg;
	}

	public void setTsReg(Date tsReg) {
		this.tsReg = tsReg;
	}

	@Column(name = "ID_PROV_REG", length = 150)
	public String getIdProvReg() {
		return this.idProvReg;
	}

	public void setIdProvReg(String idProvReg) {
		this.idProvReg = idProvReg;
	}

	@Column(name = "TS_INS", nullable = false)
	public Date getTsIns() {
		return this.tsIns;
	}

	public void setTsIns(Date tsIns) {
		this.tsIns = tsIns;
	}

	@Column(name = "ID_UTE_INS", length = 64)
	public String getIdUteIns() {
		return this.idUteIns;
	}

	public void setIdUteIns(String idUteIns) {
		this.idUteIns = idUteIns;
	}

	@Column(name = "TS_ULTIMO_AGG", nullable = false)
	public Date getTsUltimoAgg() {
		return this.tsUltimoAgg;
	}

	public void setTsUltimoAgg(Date tsUltimoAgg) {
		this.tsUltimoAgg = tsUltimoAgg;
	}

	@Column(name = "ID_UTE_ULTIMO_AGG", length = 64)
	public String getIdUteUltimoAgg() {
		return this.idUteUltimoAgg;
	}

	public void setIdUteUltimoAgg(String idUteUltimoAgg) {
		this.idUteUltimoAgg = idUteUltimoAgg;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TRegProtVsEmail")
	public Set<TAttachEmailMgo> getTAttachEmailMgos() {
		return this.TAttachEmailMgos;
	}

	public void setTAttachEmailMgos(Set<TAttachEmailMgo> TAttachEmailMgos) {
		this.TAttachEmailMgos = TAttachEmailMgos;
	}

}
