/* * SPDX-License-Identifier: AGPL-3.0-or-later * * C Copyright 2023 Regione Piemonte * */

// Generated 2-feb-2017 16.02.31 by Hibernate Tools 3.5.0.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TRelEmailFolderId generated by hbm2java
 */
@Embeddable
public class TRelEmailFolderId implements java.io.Serializable {

	private static final long serialVersionUID = -5042864573500011749L;
	private String idFolderCasella;
	private String idEmail;

	public TRelEmailFolderId() {
	}

	public TRelEmailFolderId(String idFolderCasella, String idEmail) {
		this.idFolderCasella = idFolderCasella;
		this.idEmail = idEmail;
	}

	@Column(name = "ID_FOLDER_CASELLA", nullable = false, length = 64)
	public String getIdFolderCasella() {
		return this.idFolderCasella;
	}

	public void setIdFolderCasella(String idFolderCasella) {
		this.idFolderCasella = idFolderCasella;
	}

	@Column(name = "ID_EMAIL", nullable = false, length = 64)
	public String getIdEmail() {
		return this.idEmail;
	}

	public void setIdEmail(String idEmail) {
		this.idEmail = idEmail;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TRelEmailFolderId))
			return false;
		TRelEmailFolderId castOther = (TRelEmailFolderId) other;

		return ((this.getIdFolderCasella() == castOther.getIdFolderCasella()) || (this.getIdFolderCasella() != null && castOther.getIdFolderCasella() != null
				&& this.getIdFolderCasella().equals(castOther.getIdFolderCasella())))
				&& ((this.getIdEmail() == castOther.getIdEmail())
						|| (this.getIdEmail() != null && castOther.getIdEmail() != null && this.getIdEmail().equals(castOther.getIdEmail())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getIdFolderCasella() == null ? 0 : this.getIdFolderCasella().hashCode());
		result = 37 * result + (getIdEmail() == null ? 0 : this.getIdEmail().hashCode());
		return result;
	}

}
