/* * SPDX-License-Identifier: AGPL-3.0-or-later * * C Copyright 2023 Regione Piemonte * */

// Generated 2-feb-2017 16.02.31 by Hibernate Tools 3.5.0.Final

import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TRelEmailFolder generated by hbm2java
 */
@Entity
@Table(name = "T_REL_EMAIL_FOLDER")
public class TRelEmailFolder implements java.io.Serializable {

	private static final long serialVersionUID = 2064522880407358006L;
	private TRelEmailFolderId id;
	private TFolderCaselle TFolderCaselle;
	private TEmailMgo TEmailMgo;
	private Date tsIns;
	private String idUteIns;
	private Date tsUltimoAgg;
	private String idUteUltimoAgg;

	public TRelEmailFolder() {
	}

	public TRelEmailFolder(TRelEmailFolderId id, TFolderCaselle TFolderCaselle, TEmailMgo TEmailMgo, Date tsIns, Date tsUltimoAgg) {
		this.id = id;
		this.TFolderCaselle = TFolderCaselle;
		this.TEmailMgo = TEmailMgo;
		this.tsIns = tsIns;
		this.tsUltimoAgg = tsUltimoAgg;
	}

	public TRelEmailFolder(TRelEmailFolderId id, TFolderCaselle TFolderCaselle, TEmailMgo TEmailMgo, Date tsIns, String idUteIns, Date tsUltimoAgg,
			String idUteUltimoAgg) {
		this.id = id;
		this.TFolderCaselle = TFolderCaselle;
		this.TEmailMgo = TEmailMgo;
		this.tsIns = tsIns;
		this.idUteIns = idUteIns;
		this.tsUltimoAgg = tsUltimoAgg;
		this.idUteUltimoAgg = idUteUltimoAgg;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "idFolderCasella", column = @Column(name = "ID_FOLDER_CASELLA", nullable = false, length = 64)),
			@AttributeOverride(name = "idEmail", column = @Column(name = "ID_EMAIL", nullable = false, length = 64)) })
	public TRelEmailFolderId getId() {
		return this.id;
	}

	public void setId(TRelEmailFolderId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_FOLDER_CASELLA", nullable = false, insertable = false, updatable = false)
	public TFolderCaselle getTFolderCaselle() {
		return this.TFolderCaselle;
	}

	public void setTFolderCaselle(TFolderCaselle TFolderCaselle) {
		this.TFolderCaselle = TFolderCaselle;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_EMAIL", nullable = false, insertable = false, updatable = false)
	public TEmailMgo getTEmailMgo() {
		return this.TEmailMgo;
	}

	public void setTEmailMgo(TEmailMgo TEmailMgo) {
		this.TEmailMgo = TEmailMgo;
	}

	@Column(name = "TS_INS", nullable = false)
	public Date getTsIns() {
		return this.tsIns;
	}

	public void setTsIns(Date tsIns) {
		this.tsIns = tsIns;
	}

	@Column(name = "ID_UTE_INS", length = 64)
	public String getIdUteIns() {
		return this.idUteIns;
	}

	public void setIdUteIns(String idUteIns) {
		this.idUteIns = idUteIns;
	}

	@Column(name = "TS_ULTIMO_AGG", nullable = false)
	public Date getTsUltimoAgg() {
		return this.tsUltimoAgg;
	}

	public void setTsUltimoAgg(Date tsUltimoAgg) {
		this.tsUltimoAgg = tsUltimoAgg;
	}

	@Column(name = "ID_UTE_ULTIMO_AGG", length = 64)
	public String getIdUteUltimoAgg() {
		return this.idUteUltimoAgg;
	}

	public void setIdUteUltimoAgg(String idUteUltimoAgg) {
		this.idUteUltimoAgg = idUteUltimoAgg;
	}

}
