/* * SPDX-License-Identifier: AGPL-3.0-or-later * * C Copyright 2023 Regione Piemonte * */

// Generated 2-feb-2017 16.02.31 by Hibernate Tools 3.5.0.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * TRelEmailMgo generated by hbm2java
 */
@Entity
@Table(name = "T_REL_EMAIL_MGO", uniqueConstraints = @UniqueConstraint(columnNames = { "ID_EMAIL_1", "ID_REC_DIZ_RUOLO_1_VS_2", "ID_REC_DIZ_CATEG_REL",
		"ID_EMAIL_2" }))
public class TRelEmailMgo implements java.io.Serializable {

	private static final long serialVersionUID = 4909145840573698812L;
	private String idRelEmail;
	private TEmailMgo TEmailMgoByIdEmail2;
	private TEmailMgo TEmailMgoByIdEmail1;
	private TDestinatariEmailMgo TDestinatariEmailMgo;
	private TValDizionario TValDizionarioByIdRecDizCategRel;
	private TValDizionario TValDizionarioByIdRecDizRuolo1Vs2;
	private String dettRelazione;
	private boolean flgRelAutomatica;
	private Date tsIns;
	private String idUteIns;
	private Date tsUltimoAgg;
	private String idUteUltimoAgg;

	public TRelEmailMgo() {
	}

	public TRelEmailMgo(String idRelEmail, TEmailMgo TEmailMgoByIdEmail2, TEmailMgo TEmailMgoByIdEmail1, boolean flgRelAutomatica, Date tsIns,
			Date tsUltimoAgg) {
		this.idRelEmail = idRelEmail;
		this.TEmailMgoByIdEmail2 = TEmailMgoByIdEmail2;
		this.TEmailMgoByIdEmail1 = TEmailMgoByIdEmail1;
		this.flgRelAutomatica = flgRelAutomatica;
		this.tsIns = tsIns;
		this.tsUltimoAgg = tsUltimoAgg;
	}

	public TRelEmailMgo(String idRelEmail, TEmailMgo TEmailMgoByIdEmail2, TEmailMgo TEmailMgoByIdEmail1, TDestinatariEmailMgo TDestinatariEmailMgo,
			TValDizionario TValDizionarioByIdRecDizCategRel, TValDizionario TValDizionarioByIdRecDizRuolo1Vs2, String dettRelazione, boolean flgRelAutomatica,
			Date tsIns, String idUteIns, Date tsUltimoAgg, String idUteUltimoAgg) {
		this.idRelEmail = idRelEmail;
		this.TEmailMgoByIdEmail2 = TEmailMgoByIdEmail2;
		this.TEmailMgoByIdEmail1 = TEmailMgoByIdEmail1;
		this.TDestinatariEmailMgo = TDestinatariEmailMgo;
		this.TValDizionarioByIdRecDizCategRel = TValDizionarioByIdRecDizCategRel;
		this.TValDizionarioByIdRecDizRuolo1Vs2 = TValDizionarioByIdRecDizRuolo1Vs2;
		this.dettRelazione = dettRelazione;
		this.flgRelAutomatica = flgRelAutomatica;
		this.tsIns = tsIns;
		this.idUteIns = idUteIns;
		this.tsUltimoAgg = tsUltimoAgg;
		this.idUteUltimoAgg = idUteUltimoAgg;
	}

	@Id
	@Column(name = "ID_REL_EMAIL", unique = true, nullable = false, length = 64)
	public String getIdRelEmail() {
		return this.idRelEmail;
	}

	public void setIdRelEmail(String idRelEmail) {
		this.idRelEmail = idRelEmail;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_EMAIL_2", nullable = false)
	public TEmailMgo getTEmailMgoByIdEmail2() {
		return this.TEmailMgoByIdEmail2;
	}

	public void setTEmailMgoByIdEmail2(TEmailMgo TEmailMgoByIdEmail2) {
		this.TEmailMgoByIdEmail2 = TEmailMgoByIdEmail2;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_EMAIL_1", nullable = false)
	public TEmailMgo getTEmailMgoByIdEmail1() {
		return this.TEmailMgoByIdEmail1;
	}

	public void setTEmailMgoByIdEmail1(TEmailMgo TEmailMgoByIdEmail1) {
		this.TEmailMgoByIdEmail1 = TEmailMgoByIdEmail1;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_DESTINATARIO_EMAIL_2")
	public TDestinatariEmailMgo getTDestinatariEmailMgo() {
		return this.TDestinatariEmailMgo;
	}

	public void setTDestinatariEmailMgo(TDestinatariEmailMgo TDestinatariEmailMgo) {
		this.TDestinatariEmailMgo = TDestinatariEmailMgo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_REC_DIZ_CATEG_REL")
	public TValDizionario getTValDizionarioByIdRecDizCategRel() {
		return this.TValDizionarioByIdRecDizCategRel;
	}

	public void setTValDizionarioByIdRecDizCategRel(TValDizionario TValDizionarioByIdRecDizCategRel) {
		this.TValDizionarioByIdRecDizCategRel = TValDizionarioByIdRecDizCategRel;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_REC_DIZ_RUOLO_1_VS_2")
	public TValDizionario getTValDizionarioByIdRecDizRuolo1Vs2() {
		return this.TValDizionarioByIdRecDizRuolo1Vs2;
	}

	public void setTValDizionarioByIdRecDizRuolo1Vs2(TValDizionario TValDizionarioByIdRecDizRuolo1Vs2) {
		this.TValDizionarioByIdRecDizRuolo1Vs2 = TValDizionarioByIdRecDizRuolo1Vs2;
	}

	@Column(name = "DETT_RELAZIONE", length = 1000)
	public String getDettRelazione() {
		return this.dettRelazione;
	}

	public void setDettRelazione(String dettRelazione) {
		this.dettRelazione = dettRelazione;
	}

	@Column(name = "FLG_REL_AUTOMATICA", nullable = false, precision = 1, scale = 0)
	public boolean isFlgRelAutomatica() {
		return this.flgRelAutomatica;
	}

	public void setFlgRelAutomatica(boolean flgRelAutomatica) {
		this.flgRelAutomatica = flgRelAutomatica;
	}

	@Column(name = "TS_INS", nullable = false)
	public Date getTsIns() {
		return this.tsIns;
	}

	public void setTsIns(Date tsIns) {
		this.tsIns = tsIns;
	}

	@Column(name = "ID_UTE_INS", length = 64)
	public String getIdUteIns() {
		return this.idUteIns;
	}

	public void setIdUteIns(String idUteIns) {
		this.idUteIns = idUteIns;
	}

	@Column(name = "TS_ULTIMO_AGG", nullable = false)
	public Date getTsUltimoAgg() {
		return this.tsUltimoAgg;
	}

	public void setTsUltimoAgg(Date tsUltimoAgg) {
		this.tsUltimoAgg = tsUltimoAgg;
	}

	@Column(name = "ID_UTE_ULTIMO_AGG", length = 64)
	public String getIdUteUltimoAgg() {
		return this.idUteUltimoAgg;
	}

	public void setIdUteUltimoAgg(String idUteUltimoAgg) {
		this.idUteUltimoAgg = idUteUltimoAgg;
	}

}
