/* * SPDX-License-Identifier: AGPL-3.0-or-later * * C Copyright 2023 Regione Piemonte * */

// Generated 2-feb-2017 16.02.31 by Hibernate Tools 3.5.0.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TRubricaEmail generated by hbm2java
 */
@Entity
@Table(name = "T_RUBRICA_EMAIL")
public class TRubricaEmail implements java.io.Serializable {

	private static final long serialVersionUID = -3501918096700632490L;
	private String idVoceRubricaEmail;
	private TAnagFruitoriCaselle TAnagFruitoriCaselle;
	private boolean flgMailingList;
	private String descrizioneVoce;
	private String accountEmail;
	private String tipoAccount;
	private boolean flgPecVerificata;
	private boolean flgPresenteInIpa;
	private String tipoSoggRif;
	private String idProvSoggRif;
	private String codAmministrazione;
	private String codAoo;
	private boolean flgAnn;
	private Date tsIns;
	private String idUteIns;
	private Date tsUltimoAgg;
	private String idUteUltimoAgg;
	private String accountEmailCtx;
	private String descrizioneVoceRft;
	private Set<TMembriMailingList> TMembriMailingListsForIdVoceRubricaMailingList = new HashSet<TMembriMailingList>(0);
	private Set<TMembriMailingList> TMembriMailingListsForIdVoceRubricaMembro = new HashSet<TMembriMailingList>(0);
	private Set<TDestinatariEmailMgo> TDestinatariEmailMgos = new HashSet<TDestinatariEmailMgo>(0);

	public TRubricaEmail() {
	}

	public TRubricaEmail(String idVoceRubricaEmail, boolean flgMailingList, String descrizioneVoce, boolean flgPecVerificata, boolean flgPresenteInIpa,
			boolean flgAnn, Date tsIns, Date tsUltimoAgg) {
		this.idVoceRubricaEmail = idVoceRubricaEmail;
		this.flgMailingList = flgMailingList;
		this.descrizioneVoce = descrizioneVoce;
		this.flgPecVerificata = flgPecVerificata;
		this.flgPresenteInIpa = flgPresenteInIpa;
		this.flgAnn = flgAnn;
		this.tsIns = tsIns;
		this.tsUltimoAgg = tsUltimoAgg;
	}

	public TRubricaEmail(String idVoceRubricaEmail, TAnagFruitoriCaselle TAnagFruitoriCaselle, boolean flgMailingList, String descrizioneVoce,
			String accountEmail, String tipoAccount, boolean flgPecVerificata, boolean flgPresenteInIpa, String tipoSoggRif, String idProvSoggRif,
			String codAmministrazione, String codAoo, boolean flgAnn, Date tsIns, String idUteIns, Date tsUltimoAgg, String idUteUltimoAgg,
			String accountEmailCtx, String descrizioneVoceRft, Set<TMembriMailingList> TMembriMailingListsForIdVoceRubricaMailingList,
			Set<TMembriMailingList> TMembriMailingListsForIdVoceRubricaMembro, Set<TDestinatariEmailMgo> TDestinatariEmailMgos) {
		this.idVoceRubricaEmail = idVoceRubricaEmail;
		this.TAnagFruitoriCaselle = TAnagFruitoriCaselle;
		this.flgMailingList = flgMailingList;
		this.descrizioneVoce = descrizioneVoce;
		this.accountEmail = accountEmail;
		this.tipoAccount = tipoAccount;
		this.flgPecVerificata = flgPecVerificata;
		this.flgPresenteInIpa = flgPresenteInIpa;
		this.tipoSoggRif = tipoSoggRif;
		this.idProvSoggRif = idProvSoggRif;
		this.codAmministrazione = codAmministrazione;
		this.codAoo = codAoo;
		this.flgAnn = flgAnn;
		this.tsIns = tsIns;
		this.idUteIns = idUteIns;
		this.tsUltimoAgg = tsUltimoAgg;
		this.idUteUltimoAgg = idUteUltimoAgg;
		this.accountEmailCtx = accountEmailCtx;
		this.descrizioneVoceRft = descrizioneVoceRft;
		this.TMembriMailingListsForIdVoceRubricaMailingList = TMembriMailingListsForIdVoceRubricaMailingList;
		this.TMembriMailingListsForIdVoceRubricaMembro = TMembriMailingListsForIdVoceRubricaMembro;
		this.TDestinatariEmailMgos = TDestinatariEmailMgos;
	}

	@Id
	@Column(name = "ID_VOCE_RUBRICA_EMAIL", unique = true, nullable = false, length = 64)
	public String getIdVoceRubricaEmail() {
		return this.idVoceRubricaEmail;
	}

	public void setIdVoceRubricaEmail(String idVoceRubricaEmail) {
		this.idVoceRubricaEmail = idVoceRubricaEmail;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_FRUITORE_CASELLA")
	public TAnagFruitoriCaselle getTAnagFruitoriCaselle() {
		return this.TAnagFruitoriCaselle;
	}

	public void setTAnagFruitoriCaselle(TAnagFruitoriCaselle TAnagFruitoriCaselle) {
		this.TAnagFruitoriCaselle = TAnagFruitoriCaselle;
	}

	@Column(name = "FLG_MAILING_LIST", nullable = false, precision = 1, scale = 0)
	public boolean isFlgMailingList() {
		return this.flgMailingList;
	}

	public void setFlgMailingList(boolean flgMailingList) {
		this.flgMailingList = flgMailingList;
	}

	@Column(name = "DESCRIZIONE_VOCE", nullable = false, length = 1000)
	public String getDescrizioneVoce() {
		return this.descrizioneVoce;
	}

	public void setDescrizioneVoce(String descrizioneVoce) {
		this.descrizioneVoce = descrizioneVoce;
	}

	@Column(name = "ACCOUNT_EMAIL", length = 1000)
	public String getAccountEmail() {
		return this.accountEmail;
	}

	public void setAccountEmail(String accountEmail) {
		this.accountEmail = accountEmail;
	}

	@Column(name = "TIPO_ACCOUNT", length = 1)
	public String getTipoAccount() {
		return this.tipoAccount;
	}

	public void setTipoAccount(String tipoAccount) {
		this.tipoAccount = tipoAccount;
	}

	@Column(name = "FLG_PEC_VERIFICATA", nullable = false, precision = 1, scale = 0)
	public boolean isFlgPecVerificata() {
		return this.flgPecVerificata;
	}

	public void setFlgPecVerificata(boolean flgPecVerificata) {
		this.flgPecVerificata = flgPecVerificata;
	}

	@Column(name = "FLG_PRESENTE_IN_IPA", nullable = false, precision = 1, scale = 0)
	public boolean isFlgPresenteInIpa() {
		return this.flgPresenteInIpa;
	}

	public void setFlgPresenteInIpa(boolean flgPresenteInIpa) {
		this.flgPresenteInIpa = flgPresenteInIpa;
	}

	@Column(name = "TIPO_SOGG_RIF", length = 5)
	public String getTipoSoggRif() {
		return this.tipoSoggRif;
	}

	public void setTipoSoggRif(String tipoSoggRif) {
		this.tipoSoggRif = tipoSoggRif;
	}

	@Column(name = "ID_PROV_SOGG_RIF", length = 30)
	public String getIdProvSoggRif() {
		return this.idProvSoggRif;
	}

	public void setIdProvSoggRif(String idProvSoggRif) {
		this.idProvSoggRif = idProvSoggRif;
	}

	@Column(name = "COD_AMMINISTRAZIONE", length = 150)
	public String getCodAmministrazione() {
		return this.codAmministrazione;
	}

	public void setCodAmministrazione(String codAmministrazione) {
		this.codAmministrazione = codAmministrazione;
	}

	@Column(name = "COD_AOO", length = 150)
	public String getCodAoo() {
		return this.codAoo;
	}

	public void setCodAoo(String codAoo) {
		this.codAoo = codAoo;
	}

	@Column(name = "FLG_ANN", nullable = false, precision = 1, scale = 0)
	public boolean isFlgAnn() {
		return this.flgAnn;
	}

	public void setFlgAnn(boolean flgAnn) {
		this.flgAnn = flgAnn;
	}

	@Column(name = "TS_INS", nullable = false)
	public Date getTsIns() {
		return this.tsIns;
	}

	public void setTsIns(Date tsIns) {
		this.tsIns = tsIns;
	}

	@Column(name = "ID_UTE_INS", length = 64)
	public String getIdUteIns() {
		return this.idUteIns;
	}

	public void setIdUteIns(String idUteIns) {
		this.idUteIns = idUteIns;
	}

	@Column(name = "TS_ULTIMO_AGG", nullable = false)
	public Date getTsUltimoAgg() {
		return this.tsUltimoAgg;
	}

	public void setTsUltimoAgg(Date tsUltimoAgg) {
		this.tsUltimoAgg = tsUltimoAgg;
	}

	@Column(name = "ID_UTE_ULTIMO_AGG", length = 64)
	public String getIdUteUltimoAgg() {
		return this.idUteUltimoAgg;
	}

	public void setIdUteUltimoAgg(String idUteUltimoAgg) {
		this.idUteUltimoAgg = idUteUltimoAgg;
	}

	@Column(name = "ACCOUNT_EMAIL_CTX", length = 1000)
	public String getAccountEmailCtx() {
		return this.accountEmailCtx;
	}

	public void setAccountEmailCtx(String accountEmailCtx) {
		this.accountEmailCtx = accountEmailCtx;
	}

	@Column(name = "DESCRIZIONE_VOCE_RFT", length = 1000)
	public String getDescrizioneVoceRft() {
		return this.descrizioneVoceRft;
	}

	public void setDescrizioneVoceRft(String descrizioneVoceRft) {
		this.descrizioneVoceRft = descrizioneVoceRft;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TRubricaEmailByIdVoceRubricaMailingList")
	public Set<TMembriMailingList> getTMembriMailingListsForIdVoceRubricaMailingList() {
		return this.TMembriMailingListsForIdVoceRubricaMailingList;
	}

	public void setTMembriMailingListsForIdVoceRubricaMailingList(Set<TMembriMailingList> TMembriMailingListsForIdVoceRubricaMailingList) {
		this.TMembriMailingListsForIdVoceRubricaMailingList = TMembriMailingListsForIdVoceRubricaMailingList;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TRubricaEmailByIdVoceRubricaMembro")
	public Set<TMembriMailingList> getTMembriMailingListsForIdVoceRubricaMembro() {
		return this.TMembriMailingListsForIdVoceRubricaMembro;
	}

	public void setTMembriMailingListsForIdVoceRubricaMembro(Set<TMembriMailingList> TMembriMailingListsForIdVoceRubricaMembro) {
		this.TMembriMailingListsForIdVoceRubricaMembro = TMembriMailingListsForIdVoceRubricaMembro;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TRubricaEmail")
	public Set<TDestinatariEmailMgo> getTDestinatariEmailMgos() {
		return this.TDestinatariEmailMgos;
	}

	public void setTDestinatariEmailMgos(Set<TDestinatariEmailMgo> TDestinatariEmailMgos) {
		this.TDestinatariEmailMgos = TDestinatariEmailMgos;
	}

}
