/* * SPDX-License-Identifier: AGPL-3.0-or-later * * C Copyright 2023 Regione Piemonte * */

// Generated 2-feb-2017 16.02.31 by Hibernate Tools 3.5.0.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * TSchedeDocVsEmail generated by hbm2java
 */
@Entity
@Table(name = "T_SCHEDE_DOC_VS_EMAIL", uniqueConstraints = @UniqueConstraint(columnNames = { "ID_PROV_SCHEDA_DOC", "ID_EMAIL" }))
public class TSchedeDocVsEmail implements java.io.Serializable {

	private static final long serialVersionUID = 1964195817149166599L;
	private String idSchedaDocEmail;
	private TEmailMgo TEmailMgo;
	private String idProvSchedaDoc;
	private Date tsIns;
	private String idUteIns;
	private Date tsUltimoAgg;
	private String idUteUltimoAgg;
	private Set<TAttachEmailMgo> TAttachEmailMgos = new HashSet<TAttachEmailMgo>(0);

	public TSchedeDocVsEmail() {
	}

	public TSchedeDocVsEmail(String idSchedaDocEmail, TEmailMgo TEmailMgo, String idProvSchedaDoc, Date tsIns, Date tsUltimoAgg) {
		this.idSchedaDocEmail = idSchedaDocEmail;
		this.TEmailMgo = TEmailMgo;
		this.idProvSchedaDoc = idProvSchedaDoc;
		this.tsIns = tsIns;
		this.tsUltimoAgg = tsUltimoAgg;
	}

	public TSchedeDocVsEmail(String idSchedaDocEmail, TEmailMgo TEmailMgo, String idProvSchedaDoc, Date tsIns, String idUteIns, Date tsUltimoAgg,
			String idUteUltimoAgg, Set<TAttachEmailMgo> TAttachEmailMgos) {
		this.idSchedaDocEmail = idSchedaDocEmail;
		this.TEmailMgo = TEmailMgo;
		this.idProvSchedaDoc = idProvSchedaDoc;
		this.tsIns = tsIns;
		this.idUteIns = idUteIns;
		this.tsUltimoAgg = tsUltimoAgg;
		this.idUteUltimoAgg = idUteUltimoAgg;
		this.TAttachEmailMgos = TAttachEmailMgos;
	}

	@Id
	@Column(name = "ID_SCHEDA_DOC_EMAIL", unique = true, nullable = false, length = 64)
	public String getIdSchedaDocEmail() {
		return this.idSchedaDocEmail;
	}

	public void setIdSchedaDocEmail(String idSchedaDocEmail) {
		this.idSchedaDocEmail = idSchedaDocEmail;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_EMAIL", nullable = false)
	public TEmailMgo getTEmailMgo() {
		return this.TEmailMgo;
	}

	public void setTEmailMgo(TEmailMgo TEmailMgo) {
		this.TEmailMgo = TEmailMgo;
	}

	@Column(name = "ID_PROV_SCHEDA_DOC", nullable = false, length = 150)
	public String getIdProvSchedaDoc() {
		return this.idProvSchedaDoc;
	}

	public void setIdProvSchedaDoc(String idProvSchedaDoc) {
		this.idProvSchedaDoc = idProvSchedaDoc;
	}

	@Column(name = "TS_INS", nullable = false)
	public Date getTsIns() {
		return this.tsIns;
	}

	public void setTsIns(Date tsIns) {
		this.tsIns = tsIns;
	}

	@Column(name = "ID_UTE_INS", length = 64)
	public String getIdUteIns() {
		return this.idUteIns;
	}

	public void setIdUteIns(String idUteIns) {
		this.idUteIns = idUteIns;
	}

	@Column(name = "TS_ULTIMO_AGG", nullable = false)
	public Date getTsUltimoAgg() {
		return this.tsUltimoAgg;
	}

	public void setTsUltimoAgg(Date tsUltimoAgg) {
		this.tsUltimoAgg = tsUltimoAgg;
	}

	@Column(name = "ID_UTE_ULTIMO_AGG", length = 64)
	public String getIdUteUltimoAgg() {
		return this.idUteUltimoAgg;
	}

	public void setIdUteUltimoAgg(String idUteUltimoAgg) {
		this.idUteUltimoAgg = idUteUltimoAgg;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TSchedeDocVsEmail")
	public Set<TAttachEmailMgo> getTAttachEmailMgos() {
		return this.TAttachEmailMgos;
	}

	public void setTAttachEmailMgos(Set<TAttachEmailMgo> TAttachEmailMgos) {
		this.TAttachEmailMgos = TAttachEmailMgos;
	}

}
