/* * SPDX-License-Identifier: AGPL-3.0-or-later * * C Copyright 2023 Regione Piemonte * */
// Generated 26-giu-2018 13.53.14 by Hibernate Tools 3.6.0.Final

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * TUserPreferences generated by hbm2java
 */
@Entity
@Table(name = "T_USER_PREFERENCES")
public class TUserPreferences implements java.io.Serializable {

	private static final long serialVersionUID = -12099220310579323L;
	private TUserPreferencesId id;
	private String value;
	private Date settingTime;
	private BigDecimal idUo;
	private Boolean flgVisibSottouo;
	private Boolean flgGestSottouo;

	public TUserPreferences() {
	}

	public TUserPreferences(TUserPreferencesId id, Date settingTime) {
		this.id = id;
		this.settingTime = settingTime;
	}

	public TUserPreferences(TUserPreferencesId id, String value, Date settingTime, BigDecimal idUo, Boolean flgVisibSottouo, Boolean flgGestSottouo) {
		this.id = id;
		this.value = value;
		this.settingTime = settingTime;
		this.idUo = idUo;
		this.flgVisibSottouo = flgVisibSottouo;
		this.flgGestSottouo = flgGestSottouo;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "userid", column = @Column(name = "USERID", nullable = false, length = 64)),
			@AttributeOverride(name = "prefKey", column = @Column(name = "PREF_KEY", nullable = false, length = 150)),
			@AttributeOverride(name = "prefName", column = @Column(name = "PREF_NAME", nullable = false, length = 150)) })
	public TUserPreferencesId getId() {
		return this.id;
	}

	public void setId(TUserPreferencesId id) {
		this.id = id;
	}

	@Column(name = "VALUE")
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	@Column(name = "SETTING_TIME", nullable = false)
	public Date getSettingTime() {
		return this.settingTime;
	}

	public void setSettingTime(Date settingTime) {
		this.settingTime = settingTime;
	}

	@Column(name = "ID_UO", precision = 22, scale = 0)
	public BigDecimal getIdUo() {
		return this.idUo;
	}

	public void setIdUo(BigDecimal idUo) {
		this.idUo = idUo;
	}

	@Column(name = "FLG_VISIB_SOTTOUO", precision = 1, scale = 0)
	public Boolean getFlgVisibSottouo() {
		return this.flgVisibSottouo;
	}

	public void setFlgVisibSottouo(Boolean flgVisibSottouo) {
		this.flgVisibSottouo = flgVisibSottouo;
	}

	@Column(name = "FLG_GEST_SOTTOUO", precision = 1, scale = 0)
	public Boolean getFlgGestSottouo() {
		return this.flgGestSottouo;
	}

	public void setFlgGestSottouo(Boolean flgGestSottouo) {
		this.flgGestSottouo = flgGestSottouo;
	}

}
