/* * SPDX-License-Identifier: AGPL-3.0-or-later * * C Copyright 2023 Regione Piemonte * */

// Generated 27-nov-2015 12.05.58 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * BmtJobParameters generated by hbm2java
 */
@Entity
@Table(name = "BMT_JOB_PARAMETERS")
public class BmtJobParameters implements java.io.Serializable {

	private BmtJobParametersId id;
	private BmtJobs bmtJobs;
	private String parameterValue;
	private String parameterDir;
	private String parameterType;
	private String parameterSubtype;

	public BmtJobParameters() {
	}

	public BmtJobParameters(BmtJobParametersId id, BmtJobs bmtJobs,
			String parameterDir, String parameterType) {
		this.id = id;
		this.bmtJobs = bmtJobs;
		this.parameterDir = parameterDir;
		this.parameterType = parameterType;
	}

	public BmtJobParameters(BmtJobParametersId id, BmtJobs bmtJobs,
			String parameterValue, String parameterDir, String parameterType,
			String parameterSubtype) {
		this.id = id;
		this.bmtJobs = bmtJobs;
		this.parameterValue = parameterValue;
		this.parameterDir = parameterDir;
		this.parameterType = parameterType;
		this.parameterSubtype = parameterSubtype;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "idJob", column = @Column(name = "ID_JOB", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "parameterId", column = @Column(name = "PARAMETER_ID", nullable = false, precision = 22, scale = 0)) })
	public BmtJobParametersId getId() {
		return this.id;
	}

	public void setId(BmtJobParametersId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_JOB", nullable = false, insertable = false, updatable = false)
	public BmtJobs getBmtJobs() {
		return this.bmtJobs;
	}

	public void setBmtJobs(BmtJobs bmtJobs) {
		this.bmtJobs = bmtJobs;
	}

	@Column(name = "PARAMETER_VALUE")
	public String getParameterValue() {
		return this.parameterValue;
	}

	public void setParameterValue(String parameterValue) {
		this.parameterValue = parameterValue;
	}

	@Column(name = "PARAMETER_DIR", nullable = false, length = 3)
	public String getParameterDir() {
		return this.parameterDir;
	}

	public void setParameterDir(String parameterDir) {
		this.parameterDir = parameterDir;
	}

	@Column(name = "PARAMETER_TYPE", nullable = false, length = 150)
	public String getParameterType() {
		return this.parameterType;
	}

	public void setParameterType(String parameterType) {
		this.parameterType = parameterType;
	}

	@Column(name = "PARAMETER_SUBTYPE", length = 30)
	public String getParameterSubtype() {
		return this.parameterSubtype;
	}

	public void setParameterSubtype(String parameterSubtype) {
		this.parameterSubtype = parameterSubtype;
	}

}
