/* * SPDX-License-Identifier: AGPL-3.0-or-later * * C Copyright 2023 Regione Piemonte * */
// Generated 8-gen-2018 16.02.18 by Hibernate Tools 3.6.0.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * BnlLogAnomalie generated by hbm2java
 */
@Entity
@Table(name = "BNL_LOG_ANOMALIE")
public class BnlLogAnomalie implements java.io.Serializable {

	private static final long serialVersionUID = 3655995959975359216L;

	//Identificativo univoco (UUID) del log
	private String idLog;
	//Timestamp in cui si è verificata la situazione di anomalia/errore registrata dal record
	private Date tsLog; 
	//Indica il tipo di evento registrato nel log, ovvero la situazione di anomalia/errore. Valori possibili da apposita voce di dizionario (DICTIONARY_ENTRY = TIPO_LOG_GAE)
	private String codTipoEvento; 
	//Indica il/i codici di errore riscontrati. Se più di uno sono separati da ";". I valori dei cod. errore sono codificati in apposita voce di dizionario (DICTIONARY_ENTRY = COD_ERRORI_GAE)
	private String codiciErrore; 
	//Messaggio con i dettagli dell'errore/situazione anomala rilevata
	private String msgLog; 
	//Indica lo stato dell'eventuale mail di notifica della situazione di anomalia/errore tracciata nel log. Valori possibili: da_inviare, invio_non_previsto, inviata, invio_fallito
	private String statoNotif; 
	//Timestamp di invio della mail di notifica
	private Date tsInvioNotif; 
	//Identificativo univoco (UUID) della sottoscrizione di notifica mail in base alla quale la situazione di anomalia/errore è stata notificata via e-mail (FK vs BNL_SOTTOSCRIZIONI_NOTIF_EMAIL.ID_SOTTOSCRIZIONE)
	private String idSottoscrizioneNotif; 
	//Messaggio a corredo del fallito invio della mail di notifica
	private String msgFallitoInvioNotif; 
	//URI a cui recuperare la mail di notifica (con notazione di storageUtil)
	private String uriEmailNotif; 
	//Indirizzi e-mail destinatari principali della notifica (se più di uno sono separati da ;)
	private String destinatariPrincipNotif; 
	//Indirizzi e-mail destinatari in cc della notifica (se più di uno sono separati da ;)
	private String destinatariCcNotif; 
	//Oggetto della mail di notifica
	private String subjectNotif; 
	//Testo (il corpo) html della mail di notifica
	private String bodyNotif; 
	//Id. del batch di export da SD a GAE cui si riferisce il log (FK vs BNL_BATCH.ID_BATCH)
	private String idBatch; 
	//Id. del lotto di export da SD a GAE cui si riferisce il log (FK vs BNL_LOTTO.ID_LOTTO)
	private String idLotto; 
	//Id. del Pacchetto di Versamento cui si riferisce il log (FK vs DMT_PDV_X_CONSERV.ID_PDV)
	private String idPdv; 
	//Id. del file di eventi di conservazione cui si riferisce il log (FK vs BNL_FILE_EVENTI_SUCC.ID_FILE)
	private String idFileEvtSucc; 
	//Timestamp di registrazione della situazione di anomalia/errore
	private Date tsIns; 
	//Timestamp in cui il record è stato preso in carico da un thread del job di invio segnalazioni (che lo sta ancora elaborando)
	private Date tsLock; 

	public BnlLogAnomalie() {
	}

	public BnlLogAnomalie(String idLog, Date tsLog, String codTipoEvento, String msgLog, Date tsIns) {
		this.idLog = idLog;
		this.tsLog = tsLog;
		this.codTipoEvento = codTipoEvento;
		this.msgLog = msgLog;
		this.tsIns = tsIns;
	}

	public BnlLogAnomalie(String idLog, Date tsLog, String codTipoEvento, String codiciErrore, String msgLog,
			String statoNotif, Date tsInvioNotif, String msgFallitoInvioNotif, String uriEmailNotif,
			String idSottoscrizioneNotif, String destinatariPrincipNotif, String destinatariCcNotif,
			String subjectNotif, String bodyNotif, String idBatch, String idLotto, String idPdv, String idFileEvtSucc,
			Date tsIns, Date tsLock) {
		this.idLog = idLog;
		this.tsLog = tsLog;
		this.codTipoEvento = codTipoEvento;
		this.codiciErrore = codiciErrore;
		this.msgLog = msgLog;
		this.statoNotif = statoNotif;
		this.tsInvioNotif = tsInvioNotif;
		this.msgFallitoInvioNotif = msgFallitoInvioNotif;
		this.uriEmailNotif = uriEmailNotif;
		this.idSottoscrizioneNotif = idSottoscrizioneNotif;
		this.destinatariPrincipNotif = destinatariPrincipNotif;
		this.destinatariCcNotif = destinatariCcNotif;
		this.subjectNotif = subjectNotif;
		this.bodyNotif = bodyNotif;
		this.idBatch = idBatch;
		this.idLotto = idLotto;
		this.idPdv = idPdv;
		this.idFileEvtSucc = idFileEvtSucc;
		this.tsIns = tsIns;
		this.tsLock = tsLock;
	}

	@Id

	@Column(name = "ID_LOG", unique = true, nullable = false, length = 64)
	public String getIdLog() {
		return this.idLog;
	}

	public void setIdLog(String idLog) {
		this.idLog = idLog;
	}

	@Column(name = "TS_LOG", nullable = false)
	public Date getTsLog() {
		return this.tsLog;
	}

	public void setTsLog(Date tsLog) {
		this.tsLog = tsLog;
	}

	@Column(name = "COD_TIPO_EVENTO", nullable = false, length = 10)
	public String getCodTipoEvento() {
		return this.codTipoEvento;
	}

	public void setCodTipoEvento(String codTipoEvento) {
		this.codTipoEvento = codTipoEvento;
	}

	@Column(name = "CODICI_ERRORE", length = 1000)
	public String getCodiciErrore() {
		return this.codiciErrore;
	}

	public void setCodiciErrore(String codiciErrore) {
		this.codiciErrore = codiciErrore;
	}

	@Column(name = "MSG_LOG", nullable = false)
	public String getMsgLog() {
		return this.msgLog;
	}

	public void setMsgLog(String msgLog) {
		this.msgLog = msgLog;
	}

	@Column(name = "STATO_NOTIF", length = 100)
	public String getStatoNotif() {
		return this.statoNotif;
	}

	public void setStatoNotif(String statoNotif) {
		this.statoNotif = statoNotif;
	}

	@Column(name = "TS_INVIO_NOTIF")
	public Date getTsInvioNotif() {
		return this.tsInvioNotif;
	}

	public void setTsInvioNotif(Date tsInvioNotif) {
		this.tsInvioNotif = tsInvioNotif;
	}

	@Column(name = "MSG_FALLITO_INVIO_NOTIF")
	public String getMsgFallitoInvioNotif() {
		return this.msgFallitoInvioNotif;
	}

	public void setMsgFallitoInvioNotif(String msgFallitoInvioNotif) {
		this.msgFallitoInvioNotif = msgFallitoInvioNotif;
	}

	@Column(name = "URI_EMAIL_NOTIF", length = 1000)
	public String getUriEmailNotif() {
		return this.uriEmailNotif;
	}

	public void setUriEmailNotif(String uriEmailNotif) {
		this.uriEmailNotif = uriEmailNotif;
	}

	@Column(name = "ID_SOTTOSCRIZIONE_NOTIF", length = 64)
	public String getIdSottoscrizioneNotif() {
		return this.idSottoscrizioneNotif;
	}

	public void setIdSottoscrizioneNotif(String idSottoscrizioneNotif) {
		this.idSottoscrizioneNotif = idSottoscrizioneNotif;
	}

	@Column(name = "DESTINATARI_PRINCIP_NOTIF", length = 4000)
	public String getDestinatariPrincipNotif() {
		return this.destinatariPrincipNotif;
	}

	public void setDestinatariPrincipNotif(String destinatariPrincipNotif) {
		this.destinatariPrincipNotif = destinatariPrincipNotif;
	}

	@Column(name = "DESTINATARI_CC_NOTIF", length = 4000)
	public String getDestinatariCcNotif() {
		return this.destinatariCcNotif;
	}

	public void setDestinatariCcNotif(String destinatariCcNotif) {
		this.destinatariCcNotif = destinatariCcNotif;
	}

	@Column(name = "SUBJECT_NOTIF", length = 1000)
	public String getSubjectNotif() {
		return this.subjectNotif;
	}

	public void setSubjectNotif(String subjectNotif) {
		this.subjectNotif = subjectNotif;
	}

	@Column(name = "BODY_NOTIF")
	public String getBodyNotif() {
		return this.bodyNotif;
	}

	public void setBodyNotif(String bodyNotif) {
		this.bodyNotif = bodyNotif;
	}

	@Column(name = "ID_BATCH", length = 64)
	public String getIdBatch() {
		return this.idBatch;
	}

	public void setIdBatch(String idBatch) {
		this.idBatch = idBatch;
	}

	@Column(name = "ID_LOTTO", length = 64)
	public String getIdLotto() {
		return this.idLotto;
	}

	public void setIdLotto(String idLotto) {
		this.idLotto = idLotto;
	}

	@Column(name = "ID_PDV", length = 64)
	public String getIdPdv() {
		return this.idPdv;
	}

	public void setIdPdv(String idPdv) {
		this.idPdv = idPdv;
	}

	@Column(name = "ID_FILE_EVT_SUCC", length = 64)
	public String getIdFileEvtSucc() {
		return this.idFileEvtSucc;
	}

	public void setIdFileEvtSucc(String idFileEvtSucc) {
		this.idFileEvtSucc = idFileEvtSucc;
	}

	@Column(name = "TS_INS", nullable = false)
	public Date getTsIns() {
		return this.tsIns;
	}

	public void setTsIns(Date tsIns) {
		this.tsIns = tsIns;
	}

	@Column(name = "TS_LOCK")
	public Date getTsLock() {
		return this.tsLock;
	}

	public void setTsLock(Date tsLock) {
		this.tsLock = tsLock;
	}

	@Override
	public String toString() {
		return String.format(
				"BnlLogAnomalie [idLog=%s, tsLog=%s, codTipoEvento=%s, codiciErrore=%s, msgLog=%s, statoNotif=%s, tsInvioNotif=%s, idSottoscrizioneNotif=%s, msgFallitoInvioNotif=%s, uriEmailNotif=%s, destinatariPrincipNotif=%s, destinatariCcNotif=%s, subjectNotif=%s, bodyNotif=%s, idBatch=%s, idLotto=%s, idPdv=%s, idFileEvtSucc=%s, tsIns=%s, tsLock=%s]",
				idLog, tsLog, codTipoEvento, codiciErrore, msgLog, statoNotif, tsInvioNotif, idSottoscrizioneNotif,
				msgFallitoInvioNotif, uriEmailNotif, destinatariPrincipNotif, destinatariCcNotif, subjectNotif,
				bodyNotif, idBatch, idLotto, idPdv, idFileEvtSucc, tsIns, tsLock);
	}

}
