/* * SPDX-License-Identifier: AGPL-3.0-or-later * * C Copyright 2023 Regione Piemonte * */
// Generated 16-ott-2020 19.10.48 by Hibernate Tools 3.6.0.Final

import java.util.Date;
import java.math.BigDecimal;
import java.sql.Clob;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * DmtCodaProcWfToStart generated by hbm2java
 */
@Entity
@Table(name = "DMT_CODA_PROC_WF_TO_START")
public class DmtCodaProcWfToStart implements java.io.Serializable {

	private DmtCodaProcWfToStartId id;
	private String tipoFlusso;
	private String procDefId;
	private String procInstId;
	private Date tsIns;
	private Date tsStartProc;
	private BigDecimal tryNum;
	private String esitoElab;
	private Clob errMsg;

	public DmtCodaProcWfToStart() {
	}
    
	

	public DmtCodaProcWfToStart(DmtCodaProcWfToStartId id, String tipoFlusso, String procDefId, String procInstId,
			Date tsIns, Date tsStartProc, BigDecimal tryNum, String esitoElab, Clob errMsg) {
		super();
		this.id = id;
		this.tipoFlusso = tipoFlusso;
		this.procDefId = procDefId;
		this.procInstId = procInstId;
		this.tsIns = tsIns;
		this.tsStartProc = tsStartProc;
		this.tryNum = tryNum;
		this.esitoElab = esitoElab;
		this.errMsg = errMsg;
	}



	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "tyObj", column = @Column(name = "TY_OBJ", nullable = false, length = 1)),
			@AttributeOverride(name = "idObj", column = @Column(name = "ID_OBJ", nullable = false, precision = 22, scale = 0)) })
	public DmtCodaProcWfToStartId getId() {
		return this.id;
	}

	public void setId(DmtCodaProcWfToStartId id) {
		this.id = id;
	}

	@Column(name = "TIPO_FLUSSO", nullable = false, length = 250)
	public String getTipoFlusso() {
		return this.tipoFlusso;
	}

	public void setTipoFlusso(String tipoFlusso) {
		this.tipoFlusso = tipoFlusso;
	}

	@Column(name = "PROC_DEF_ID_", length = 64)
	public String getProcDefId() {
		return this.procDefId;
	}

	public void setProcDefId(String procDefId) {
		this.procDefId = procDefId;
	}

	@Column(name = "PROC_INST_ID_", length = 64)
	public String getProcInstId() {
		return this.procInstId;
	}

	public void setProcInstId(String procInstId) {
		this.procInstId = procInstId;
	}

	@Column(name = "TS_INS", nullable = false)
	public Date getTsIns() {
		return this.tsIns;
	}

	public void setTsIns(Date tsIns) {
		this.tsIns = tsIns;
	}

	@Column(name = "TS_START_PROC")
	public Date getTsStartProc() {
		return this.tsStartProc;
	}

	public void setTsStartProc(Date tsStartProc) {
		this.tsStartProc = tsStartProc;
	}

	@Column(name = "TRY_NUM", nullable = false, precision = 22, scale = 0)
	public BigDecimal getTryNum() {
		return this.tryNum;
	}

	public void setTryNum(BigDecimal tryNum) {
		this.tryNum = tryNum;
	}

	@Column(name = "ESITO_ELAB", length = 2)
	public String getEsitoElab() {
		return this.esitoElab;
	}

	public void setEsitoElab(String esitoElab) {
		this.esitoElab = esitoElab;
	}

	@Column(name = "ERR_MSG")
	public Clob getErrMsg() {
		return this.errMsg;
	}

	public void setErrMsg(Clob errMsg) {
		this.errMsg = errMsg;
	}

}
