/* * SPDX-License-Identifier: AGPL-3.0-or-later * * C Copyright 2023 Regione Piemonte * */

// Generated 18-dic-2014 17.26.45 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * DmtCorrispettiviQuad generated by hbm2java
 */
@Entity
@Table(name = "DMT_CORRISPETTIVI_QUAD")
public class DmtCorrispettiviQuad implements java.io.Serializable {

	private DmtCorrispettiviQuadId id;

	public DmtCorrispettiviQuad() {
	}

	public DmtCorrispettiviQuad(DmtCorrispettiviQuadId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "idQuadratura", column = @Column(name = "ID_QUADRATURA", precision = 22, scale = 0)),
			@AttributeOverride(name = "anno", column = @Column(name = "ANNO", precision = 22, scale = 0)),
			@AttributeOverride(name = "mese", column = @Column(name = "MESE", precision = 22, scale = 0)),
			@AttributeOverride(name = "orderSource", column = @Column(name = "ORDER_SOURCE", length = 20)), @AttributeOverride(name = "taxRate", column = @Column(name = "TAX_RATE", precision = 12)),
			@AttributeOverride(name = "taxLine", column = @Column(name = "TAX_LINE", precision = 22, scale = 0)),
			@AttributeOverride(name = "amount", column = @Column(name = "AMOUNT", precision = 12)), @AttributeOverride(name = "idUd", column = @Column(name = "ID_UD", precision = 22, scale = 0)),
			@AttributeOverride(name = "descrAde", column = @Column(name = "DESCR_ADE", length = 50)) })
	public DmtCorrispettiviQuadId getId() {
		return this.id;
	}

	public void setId(DmtCorrispettiviQuadId id) {
		this.id = id;
	}

}
