/* * SPDX-License-Identifier: AGPL-3.0-or-later * * C Copyright 2023 Regione Piemonte * */

// Generated 3-giu-2015 17.52.53 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * DmtDocumentiLottoInElab generated by hbm2java
 */
@Entity
@Table(name = "DMT_DOCUMENTI_LOTTO_IN_ELAB")
public class DmtDocumentiLottoInElab implements java.io.Serializable {

	private static final long serialVersionUID = 4304183463000913917L;

	private DmtDocumentiLottoInElabId id;

	private BigDecimal idSpAoo;

	private String codApplOwner;

	private String codIstApplOwner;

	private String nomeLotto;

	private String nomeFileDoc;

	private String rigaLotto;

	public DmtDocumentiLottoInElab() {
	}

	public DmtDocumentiLottoInElab(DmtDocumentiLottoInElabId id, String nomeLotto, String nomeFileDoc, String rigaLotto) {
		this.id = id;
		this.nomeLotto = nomeLotto;
		this.nomeFileDoc = nomeFileDoc;
		this.rigaLotto = rigaLotto;
	}

	public DmtDocumentiLottoInElab(DmtDocumentiLottoInElabId id, BigDecimal idSpAoo, String codApplOwner, String codIstApplOwner, String nomeLotto, String nomeFileDoc, String rigaLotto) {
		this.id = id;
		this.idSpAoo = idSpAoo;
		this.codApplOwner = codApplOwner;
		this.codIstApplOwner = codIstApplOwner;
		this.nomeLotto = nomeLotto;
		this.nomeFileDoc = nomeFileDoc;
		this.rigaLotto = rigaLotto;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "idLotto", column = @Column(name = "ID_LOTTO", nullable = false, length = 64)),
			@AttributeOverride(name = "numRigaLotto", column = @Column(name = "NUM_RIGA_LOTTO", nullable = false, precision = 22, scale = 0)) })
	public DmtDocumentiLottoInElabId getId() {
		return this.id;
	}

	public void setId(DmtDocumentiLottoInElabId id) {
		this.id = id;
	}

	@Column(name = "ID_SP_AOO", precision = 22, scale = 0)
	public BigDecimal getIdSpAoo() {
		return this.idSpAoo;
	}

	public void setIdSpAoo(BigDecimal idSpAoo) {
		this.idSpAoo = idSpAoo;
	}

	@Column(name = "COD_APPL_OWNER", nullable = false, length = 30)
	public String getCodApplOwner() {
		return this.codApplOwner;
	}

	public void setCodApplOwner(String codApplOwner) {
		this.codApplOwner = codApplOwner;
	}

	@Column(name = "COD_IST_APPL_OWNER", nullable = false, length = 30)
	public String getCodIstApplOwner() {
		return this.codIstApplOwner;
	}

	public void setCodIstApplOwner(String codIstApplOwner) {
		this.codIstApplOwner = codIstApplOwner;
	}

	@Column(name = "NOME_LOTTO", nullable = false, length = 250)
	public String getNomeLotto() {
		return this.nomeLotto;
	}

	public void setNomeLotto(String nomeLotto) {
		this.nomeLotto = nomeLotto;
	}

	@Column(name = "NOME_FILE_DOC", length = 256)
	public String getNomeFileDoc() {
		return this.nomeFileDoc;
	}

	public void setNomeFileDoc(String nomeFileDoc) {
		this.nomeFileDoc = nomeFileDoc;
	}

	@Column(name = "RIGA_LOTTO", nullable = false)
	public String getRigaLotto() {
		return this.rigaLotto;
	}

	public void setRigaLotto(String rigaLotto) {
		this.rigaLotto = rigaLotto;
	}

	@Override
	public String toString() {
		return String.format(
				"DmtDocumentiLottoInElab [id=%s, idSpAoo=%s, codApplOwner=%s, codIstApplOwner=%s, nomeLotto=%s, nomeFileDoc=%s, rigaLotto=%s]",
				id, idSpAoo, codApplOwner, codIstApplOwner, nomeLotto, nomeFileDoc, rigaLotto);
	}

}
