/* * SPDX-License-Identifier: AGPL-3.0-or-later * * C Copyright 2023 Regione Piemonte * */

// Generated 17-giu-2015 11.14.10 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * DmtSezionali generated by hbm2java
 */
@Entity
@Table(name = "DMT_SEZIONALI")
public class DmtSezionali implements java.io.Serializable {

	private static final long serialVersionUID = 107987846930117389L;

	private DmtSezionaliId id;

	private String codApplOwner;

	private String codIstApplOwner;

	private String descrizione;

	private BigDecimal rangeDa;

	private BigDecimal rangeA;

	private Boolean flgHidden;

	private Boolean flgLocked;

	private Boolean flgAnn;

	private Date tsIns;

	private BigDecimal idUserIns;

	private Date tsLastUpd;

	private BigDecimal idUserLastUpd;

	public DmtSezionali() {
	}

	public DmtSezionali(DmtSezionaliId id) {
		this.id = id;
	}

	public DmtSezionali(DmtSezionaliId id, String codApplOwner, String codIstApplOwner, String descrizione, BigDecimal rangeDa, BigDecimal rangeA,
			Boolean flgHidden, Boolean flgLocked, Boolean flgAnn, Date tsIns, BigDecimal idUserIns, Date tsLastUpd, BigDecimal idUserLastUpd) {
		this.id = id;
		this.codApplOwner = codApplOwner;
		this.codIstApplOwner = codIstApplOwner;
		this.descrizione = descrizione;
		this.rangeDa = rangeDa;
		this.rangeA = rangeA;
		this.flgHidden = flgHidden;
		this.flgLocked = flgLocked;
		this.flgAnn = flgAnn;
		this.tsIns = tsIns;
		this.idUserIns = idUserIns;
		this.tsLastUpd = tsLastUpd;
		this.idUserLastUpd = idUserLastUpd;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "idSpAoo", column = @Column(name = "ID_SP_AOO", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "idSezionale", column = @Column(name = "ID_SEZIONALE", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "codSezionale", column = @Column(name = "COD_SEZIONALE", nullable = false, length = 5)),
			@AttributeOverride(name = "anno", column = @Column(name = "ANNO", nullable = false, precision = 22, scale = 0)) })
	public DmtSezionaliId getId() {
		return this.id;
	}

	public void setId(DmtSezionaliId id) {
		this.id = id;
	}

	@Column(name = "COD_APPL_OWNER", nullable = false, length = 30)
	public String getCodApplOwner() {
		return this.codApplOwner;
	}

	public void setCodApplOwner(String codApplOwner) {
		this.codApplOwner = codApplOwner;
	}

	@Column(name = "COD_IST_APPL_OWNER", nullable = false, length = 30)
	public String getCodIstApplOwner() {
		return this.codIstApplOwner;
	}

	public void setCodIstApplOwner(String codIstApplOwner) {
		this.codIstApplOwner = codIstApplOwner;
	}

	@Column(name = "DESCRIZIONE", length = 4000)
	public String getDescrizione() {
		return this.descrizione;
	}

	public void setDescrizione(String descrizione) {
		this.descrizione = descrizione;
	}

	@Column(name = "RANGE_DA", precision = 22, scale = 0)
	public BigDecimal getRangeDa() {
		return this.rangeDa;
	}

	public void setRangeDa(BigDecimal rangeDa) {
		this.rangeDa = rangeDa;
	}

	@Column(name = "RANGE_A", precision = 22, scale = 0)
	public BigDecimal getRangeA() {
		return this.rangeA;
	}

	public void setRangeA(BigDecimal rangeA) {
		this.rangeA = rangeA;
	}

	@Column(name = "FLG_HIDDEN", precision = 1, scale = 0)
	public Boolean getFlgHidden() {
		return this.flgHidden;
	}

	public void setFlgHidden(Boolean flgHidden) {
		this.flgHidden = flgHidden;
	}

	@Column(name = "FLG_LOCKED", precision = 1, scale = 0)
	public Boolean getFlgLocked() {
		return this.flgLocked;
	}

	public void setFlgLocked(Boolean flgLocked) {
		this.flgLocked = flgLocked;
	}

	@Column(name = "FLG_ANN", precision = 1, scale = 0)
	public Boolean getFlgAnn() {
		return this.flgAnn;
	}

	public void setFlgAnn(Boolean flgAnn) {
		this.flgAnn = flgAnn;
	}

	@Column(name = "TS_INS", length = 7)
	public Date getTsIns() {
		return this.tsIns;
	}

	public void setTsIns(Date tsIns) {
		this.tsIns = tsIns;
	}

	@Column(name = "ID_USER_INS", precision = 22, scale = 0)
	public BigDecimal getIdUserIns() {
		return this.idUserIns;
	}

	public void setIdUserIns(BigDecimal idUserIns) {
		this.idUserIns = idUserIns;
	}

	@Column(name = "TS_LAST_UPD", length = 7)
	public Date getTsLastUpd() {
		return this.tsLastUpd;
	}

	public void setTsLastUpd(Date tsLastUpd) {
		this.tsLastUpd = tsLastUpd;
	}

	@Column(name = "ID_USER_LAST_UPD", precision = 22, scale = 0)
	public BigDecimal getIdUserLastUpd() {
		return this.idUserLastUpd;
	}

	public void setIdUserLastUpd(BigDecimal idUserLastUpd) {
		this.idUserLastUpd = idUserLastUpd;
	}

	@Override
	public String toString() {
		return String
				.format("DmtSezionali [id=%s, codApplOwner=%s, codIstApplOwner=%s, descrizione=%s, rangeDa=%s, rangeA=%s, flgHidden=%s, flgLocked=%s, flgAnn=%s, tsIns=%s, idUserIns=%s, tsLastUpd=%s, idUserLastUpd=%s]",
						id, codApplOwner, codIstApplOwner, descrizione, rangeDa, rangeA, flgHidden, flgLocked, flgAnn, tsIns, idUserIns,
						tsLastUpd, idUserLastUpd);
	}

}
