/* * SPDX-License-Identifier: AGPL-3.0-or-later * * C Copyright 2023 Regione Piemonte * */

//Generated 4-feb-2015 9.30.32 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * DmvFatture generated by hbm2java modificato da denis.bragato
 */
@Entity
@Table(name = "DMV_FATTURE")
public class DmvFatture implements java.io.Serializable {

	private static final long serialVersionUID = 5672113174693634003L;
	

	private DmvFattureId id;

	private String denomProduttore;

	private String codFiscaleProduttore;

	private String connToken;
	
	private BigDecimal idUd;

	private String intitolazioneFattura;

	private String flgAttivaPassiva;

	private String idTrasmittente;

	private String progrTrasmSdi;

	private String nroFattura;

	private String annoFattura;

	private Date fattData;
	
	private BigDecimal importoFattura;

	private String fattDenomDest;

	private String fattCodIpaDest;

	private String fattIdFiscDest;

	private String codStatoDett;

	private Date tsLastUpdStato;

	private String msgScarto;

	private String msgEsito;

	private BigDecimal flgInviatoReport;

	private String uri;

	private String displayFilename;

	private String mimeType;

	private BigDecimal flgAnn;

	private BigDecimal flgInvioInConserv;

	private Date tsInvioInConserv;
	
	private BigDecimal idLottoInvioInConserv;
	
	private String idInConserv;
	
	private String errMsgInvioInConserv;
	
	private String statoConservazione;


	public DmvFatture() {
	}

	public DmvFatture(DmvFattureId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "codApplOwner", column = @Column(name = "COD_APPL_OWNER", length = 30)),
			@AttributeOverride(name = "codIstApplOwner", column = @Column(name = "COD_IST_APPL_OWNER", length = 30)),
			@AttributeOverride(name = "idDoc", column = @Column(name = "ID_DOC", nullable = false, precision = 22, scale = 0)) })
	public DmvFattureId getId() {
		return this.id;
	}

	public void setId(DmvFattureId id) {
		this.id = id;
	}

	@Column(name = "CONN_TOKEN", length = 4000)
	public String getConnToken() {
		return this.connToken;
	}

	public void setConnToken(String connToken) {
		this.connToken = connToken;
	}

	@Column(name = "DENOM_PRODUTTORE", length = 1000)
	public String getDenomProduttore() {
		return this.denomProduttore;
	}

	public void setDenomProduttore(String denomProduttore) {
		this.denomProduttore = denomProduttore;
	}

	@Column(name = "COD_FISCALE_PRODUTTORE", length = 150)
	public String getCodFiscaleProduttore() {
		return this.codFiscaleProduttore;
	}

	public void setCodFiscaleProduttore(String codFiscaleProduttore) {
		this.codFiscaleProduttore = codFiscaleProduttore;
	}

	@Column(name = "ID_UD", nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdUd() {
		return this.idUd;
	}

	public void setIdUd(BigDecimal idUd) {
		this.idUd = idUd;
	}

	@Column(name = "INTITOLAZIONE_FATTURA", nullable = false, length = 100)
	public String getIntitolazioneFattura() {
		return this.intitolazioneFattura;
	}

	public void setIntitolazioneFattura(String intitolazioneFattura) {
		this.intitolazioneFattura = intitolazioneFattura;
	}

	@Column(name = "FLG_ATTIVA_PASSIVA", length = 7)
	public String getFlgAttivaPassiva() {
		return this.flgAttivaPassiva;
	}

	public void setFlgAttivaPassiva(String flgAttivaPassiva) {
		this.flgAttivaPassiva = flgAttivaPassiva;
	}

	@Column(name = "ID_TRASMITTENTE", length = 4000)
	public String getIdTrasmittente() {
		return this.idTrasmittente;
	}

	public void setIdTrasmittente(String idTrasmittente) {
		this.idTrasmittente = idTrasmittente;
	}

	@Column(name = "PROGR_TRASM_SDI", length = 4000)
	public String getProgrTrasmSdi() {
		return this.progrTrasmSdi;
	}

	public void setProgrTrasmSdi(String progrTrasmSdi) {
		this.progrTrasmSdi = progrTrasmSdi;
	}

	@Column(name = "NRO_FATTURA", length = 4000)
	public String getNroFattura() {
		return this.nroFattura;
	}

	public void setNroFattura(String nroFattura) {
		this.nroFattura = nroFattura;
	}

	@Column(name = "ANNO_FATTURA", length = 4)
	public String getAnnoFattura() {
		return this.annoFattura;
	}

	public void setAnnoFattura(String annoFattura) {
		this.annoFattura = annoFattura;
	}

	@Column(name = "FATT_DATA", length = 7)
	public Date getFattData() {
		return this.fattData;
	}

	public void setFattData(Date fattData) {
		this.fattData = fattData;
	}

	@Column(name = "IMPORTO_FATTURA", precision = 22, scale = 0)
	public BigDecimal getImportoFattura() {
		return this.importoFattura;
	}

	public void setImportoFattura(BigDecimal importoFattura) {
		this.importoFattura = importoFattura;
	}

	@Column(name = "FATT_DENOM_DEST", length = 4000)
	public String getFattDenomDest() {
		return this.fattDenomDest;
	}

	public void setFattDenomDest(String fattDenomDest) {
		this.fattDenomDest = fattDenomDest;
	}

	@Column(name = "FATT_COD_IPA_DEST", length = 4000)
	public String getFattCodIpaDest() {
		return this.fattCodIpaDest;
	}

	public void setFattCodIpaDest(String fattCodIpaDest) {
		this.fattCodIpaDest = fattCodIpaDest;
	}

	@Column(name = "FATT_ID_FISC_DEST", length = 4000)
	public String getFattIdFiscDest() {
		return this.fattIdFiscDest;
	}

	public void setFattIdFiscDest(String fattIdFiscDest) {
		this.fattIdFiscDest = fattIdFiscDest;
	}

	@Column(name = "COD_STATO_DETT", length = 10)
	public String getCodStatoDett() {
		return this.codStatoDett;
	}

	public void setCodStatoDett(String codStatoDett) {
		this.codStatoDett = codStatoDett;
	}

	@Column(name = "TS_LAST_UPD_STATO", length = 7)
	public Date getTsLastUpdStato() {
		return this.tsLastUpdStato;
	}

	public void setTsLastUpdStato(Date tsLastUpdStato) {
		this.tsLastUpdStato = tsLastUpdStato;
	}

	@Column(name = "MSG_SCARTO")
	public String getMsgScarto() {
		return this.msgScarto;
	}

	public void setMsgScarto(String msgScarto) {
		this.msgScarto = msgScarto;
	}

	@Column(name = "MSG_ESITO")
	public String getMsgEsito() {
		return this.msgEsito;
	}

	public void setMsgEsito(String msgEsito) {
		this.msgEsito = msgEsito;
	}

	@Column(name = "FLG_INVIATO_REPORT", precision = 22, scale = 0)
	public BigDecimal getFlgInviatoReport() {
		return this.flgInviatoReport;
	}

	public void setFlgInviatoReport(BigDecimal flgInviatoReport) {
		this.flgInviatoReport = flgInviatoReport;
	}

	@Column(name = "URI", length = 1000)
	public String getUri() {
		return this.uri;
	}

	public void setUri(String uri) {
		this.uri = uri;
	}

	@Column(name = "DISPLAY_FILENAME", length = 1000)
	public String getDisplayFilename() {
		return displayFilename;
	}

	public void setDisplayFilename(String displayFilename) {
		this.displayFilename = displayFilename;
	}

	@Column(name = "MIMETYPE", length = 250)
	public String getMimetype() {
		return mimeType;
	}

	public void setMimetype(String mimeType) {
		this.mimeType = mimeType;
	}

	@Column(name = "FLG_ANN", precision = 22, scale = 0)
	public BigDecimal getFlgAnn() {
		return this.flgAnn;
	}

	public void setFlgAnn(BigDecimal flgAnn) {
		this.flgAnn = flgAnn;
	}

	@Column(name = "FLG_INVIO_IN_CONSERV", precision = 22, scale = 0)
	public BigDecimal getFlgInvioInConserv() {
		return this.flgInvioInConserv;
	}

	public void setFlgInvioInConserv(BigDecimal flgInvioInConserv) {
		this.flgInvioInConserv = flgInvioInConserv;
	}

	@Column(name = "TS_INVIO_IN_CONSERV", length = 7)
	public Date getTsInvioInConserv() {
		return tsInvioInConserv;
	}

	public void setTsInvioInConserv(Date tsInvioInConserv) {
		this.tsInvioInConserv = tsInvioInConserv;
	}

	@Column(name = "ID_LOTTO_INVIO_IN_CONSERV", precision = 22, scale = 0)
	public BigDecimal getIdLottoInvioInConserv() {
		return idLottoInvioInConserv;
	}

	public void setIdLottoInvioInConserv(BigDecimal idLottoInvioInConserv) {
		this.idLottoInvioInConserv = idLottoInvioInConserv;
	}

	@Column(name = "ID_IN_CONSERVAZIONE", length = 250)
	public String getIdInConserv() {
		return idInConserv;
	}

	public void setIdInConserv(String idInConserv) {
		this.idInConserv = idInConserv;
	}

	@Column(name = "ERR_MSG_INVIO_IN_CONSERV", length = 4000)
	public String getErrMsgInvioInConserv() {
		return errMsgInvioInConserv;
	}

	public void setErrMsgInvioInConserv(String errMsgInvioInConserv) {
		this.errMsgInvioInConserv = errMsgInvioInConserv;
	}

	@Column(name = "STATO_CONSERVAZIONE", length = 30)
	public String getStatoConservazione() {
		return statoConservazione;
	}

	public void setStatoConservazione(String statoConservazione) {
		this.statoConservazione = statoConservazione;
	}

	@Override
	public String toString() {
		return String
				.format("DmvFatture [id=%s, denomProduttore=%s, codFiscaleProduttore=%s, connToken=%s, idUd=%s, intitolazioneFattura=%s, flgAttivaPassiva=%s, idTrasmittente=%s, progrTrasmSdi=%s, nroFattura=%s, annoFattura=%s, fattData=%s, importoFattura=%s, fattDenomDest=%s, fattCodIpaDest=%s, fattIdFiscDest=%s, codStatoDett=%s, tsLastUpdStato=%s, msgScarto=%s, msgEsito=%s, flgInviatoReport=%s, uri=%s, displayFilename=%s, mimeType=%s, flgAnn=%s, flgInvioInConserv=%s, tsInvioInConserv=%s, idLottoInvioInConserv=%s, idInConserv=%s, errMsgInvioInConserv=%s, statoConservazione=%s]",
						id, denomProduttore, codFiscaleProduttore, connToken, idUd, intitolazioneFattura, flgAttivaPassiva, idTrasmittente,
						progrTrasmSdi, nroFattura, annoFattura, fattData, importoFattura, fattDenomDest, fattCodIpaDest, fattIdFiscDest,
						codStatoDett, tsLastUpdStato, msgScarto, msgEsito, flgInviatoReport, uri, displayFilename, mimeType, flgAnn,
						flgInvioInConserv, tsInvioInConserv, idLottoInvioInConserv, idInConserv, errMsgInvioInConserv, statoConservazione);
	}

}
