/* * SPDX-License-Identifier: AGPL-3.0-or-later * * C Copyright 2023 Regione Piemonte * */

// Generated 4-feb-2015 15.27.45 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * DmvRicevuteSdiFatture generated by hbm2java
 */
@Entity
@Table(name = "DMV_RICEVUTE_SDI_FATTURE")
public class DmvRicevuteSdiFatture implements java.io.Serializable {

	private static final long serialVersionUID = 111304107524642761L;
	
	private DmvRicevuteSdiFattureId id;

	private String tipoRicevuta;

	private BigDecimal idUdRicevuta;
	
	private Date tsArrivoRicevuta;

	private String uriRicevuta;

	private String displayFilenameRicevuta;
	
	private String mimetypeRicevuta;

	private BigDecimal idDocFattura;

	private String denomProduttore;

	private String codFiscaleProduttore;

	private String connToken;

	private String intitolazioneFattura;

	private String flgAttivaPassiva;

	private String idTrasmittente;

	private String progrTrasmSdi;

	private String nroFattura;

	private String annoFattura;

	private Date fattData;

	private BigDecimal importoFattura;

	private String fattDenomDest;

	private String fattCodIpaDest;

	private String fattIdFiscDest;

	private String codStatoDettFatt;

	private BigDecimal flgInvioInConservFattura;

	private Date tsInvioInConservFattura;
	
	private String statoConservazioneFattura;

	private BigDecimal flgInvioInConserv;

	private Date tsInvioInConserv;
	
	private BigDecimal idLottoInvioInConserv;
	
	private String idInConserv;
	
	private String errMsgInvioInConserv;

	private String statoConservazione;

	
	public DmvRicevuteSdiFatture() {
	}

	public DmvRicevuteSdiFatture(DmvRicevuteSdiFattureId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "codApplOwner", column = @Column(name = "COD_APPL_OWNER", length = 30)),
			@AttributeOverride(name = "codIstApplOwner", column = @Column(name = "COD_IST_APPL_OWNER", length = 30)),
			@AttributeOverride(name = "idDocRicevuta", column = @Column(name = "ID_DOC_RICEVUTA", nullable = false, precision = 22, scale = 0))})
	public DmvRicevuteSdiFattureId getId() {
		return this.id;
	}

	public void setId(DmvRicevuteSdiFattureId id) {
		this.id = id;
	}

	@Column(name = "TIPO_RICEVUTA", length = 100)
	public String getTipoRicevuta() {
		return this.tipoRicevuta;
	}

	public void setTipoRicevuta(String tipoRicevuta) {
		this.tipoRicevuta = tipoRicevuta;
	}

	@Column(name = "ID_UD_RICEVUTA", precision = 22, scale = 0)
	public BigDecimal getIdUdRicevuta() {
		return this.idUdRicevuta;
	}

	public void setIdUdRicevuta(BigDecimal idUdRicevuta) {
		this.idUdRicevuta = idUdRicevuta;
	}

	@Column(name = "TS_ARRIVO_RICEVUTA", length = 7)
	public Date getTsArrivoRicevuta() {
		return this.tsArrivoRicevuta;
	}

	public void setTsArrivoRicevuta(Date tsArrivoRicevuta) {
		this.tsArrivoRicevuta = tsArrivoRicevuta;
	}

	@Column(name = "URI_RICEVUTA", length = 1000)
	public String getUriRicevuta() {
		return this.uriRicevuta;
	}

	public void setUriRicevuta(String uriRicevuta) {
		this.uriRicevuta = uriRicevuta;
	}

	@Column(name = "DISPLAY_FILENAME_RICEVUTA", length = 1000)
	public String getDisplayFilenameRicevuta() {
		return displayFilenameRicevuta;
	}

	public void setDisplayFilenameRicevuta(String displayFilenameRicevuta) {
		this.displayFilenameRicevuta = displayFilenameRicevuta;
	}

	@Column(name = "MIMETYPE_RICEVUTA", length = 250)
	public String getMimetypeRicevuta() {
		return mimetypeRicevuta;
	}

	public void setMimetypeRicevuta(String mimetypeRicevuta) {
		this.mimetypeRicevuta = mimetypeRicevuta;
	}

	@Column(name = "ID_DOC_FATTURA", precision = 22, scale = 0)
	public BigDecimal getIdDocFattura() {
		return this.idDocFattura;
	}

	public void setIdDocFattura(BigDecimal idDocFattura) {
		this.idDocFattura = idDocFattura;
	}

	@Column(name = "DENOM_PRODUTTORE", length = 1000)
	public String getDenomProduttore() {
		return this.denomProduttore;
	}

	public void setDenomProduttore(String denomProduttore) {
		this.denomProduttore = denomProduttore;
	}

	@Column(name = "COD_FISCALE_PRODUTTORE", length = 4000)
	public String getCodFiscaleProduttore() {
		return this.codFiscaleProduttore;
	}

	public void setCodFiscaleProduttore(String codFiscaleProduttore) {
		this.codFiscaleProduttore = codFiscaleProduttore;
	}

	@Column(name = "CONN_TOKEN", length = 4000)
	public String getConnToken() {
		return this.connToken;
	}

	public void setConnToken(String connToken) {
		this.connToken = connToken;
	}

	@Column(name = "INTITOLAZIONE_FATTURA", nullable = false, length = 100)
	public String getIntitolazioneFattura() {
		return this.intitolazioneFattura;
	}

	public void setIntitolazioneFattura(String intitolazioneFattura) {
		this.intitolazioneFattura = intitolazioneFattura;
	}

	@Column(name = "FLG_ATTIVA_PASSIVA", length = 7)
	public String getFlgAttivaPassiva() {
		return this.flgAttivaPassiva;
	}

	public void setFlgAttivaPassiva(String flgAttivaPassiva) {
		this.flgAttivaPassiva = flgAttivaPassiva;
	}

	@Column(name = "ID_TRASMITTENTE", length = 4000)
	public String getIdTrasmittente() {
		return this.idTrasmittente;
	}

	public void setIdTrasmittente(String idTrasmittente) {
		this.idTrasmittente = idTrasmittente;
	}

	@Column(name = "PROGR_TRASM_SDI", length = 4000)
	public String getProgrTrasmSdi() {
		return this.progrTrasmSdi;
	}

	public void setProgrTrasmSdi(String progrTrasmSdi) {
		this.progrTrasmSdi = progrTrasmSdi;
	}

	@Column(name = "NRO_FATTURA", length = 4000)
	public String getNroFattura() {
		return this.nroFattura;
	}

	public void setNroFattura(String nroFattura) {
		this.nroFattura = nroFattura;
	}

	@Column(name = "ANNO_FATTURA", length = 4)
	public String getAnnoFattura() {
		return this.annoFattura;
	}

	public void setAnnoFattura(String annoFattura) {
		this.annoFattura = annoFattura;
	}

	@Column(name = "FATT_DATA", length = 7)
	public Date getFattData() {
		return this.fattData;
	}

	public void setFattData(Date fattData) {
		this.fattData = fattData;
	}

	@Column(name = "IMPORTO_FATTURA", precision = 22, scale = 0)
	public BigDecimal getImportoFattura() {
		return this.importoFattura;
	}

	public void setImportoFattura(BigDecimal importoFattura) {
		this.importoFattura = importoFattura;
	}

	@Column(name = "FATT_DENOM_DEST", length = 4000)
	public String getFattDenomDest() {
		return this.fattDenomDest;
	}

	public void setFattDenomDest(String fattDenomDest) {
		this.fattDenomDest = fattDenomDest;
	}

	@Column(name = "FATT_COD_IPA_DEST", length = 4000)
	public String getFattCodIpaDest() {
		return this.fattCodIpaDest;
	}

	public void setFattCodIpaDest(String fattCodIpaDest) {
		this.fattCodIpaDest = fattCodIpaDest;
	}

	@Column(name = "FATT_ID_FISC_DEST", length = 4000)
	public String getFattIdFiscDest() {
		return this.fattIdFiscDest;
	}

	public void setFattIdFiscDest(String fattIdFiscDest) {
		this.fattIdFiscDest = fattIdFiscDest;
	}

	@Column(name = "COD_STATO_DETT_FATT", length = 10)
	public String getCodStatoDettFatt() {
		return this.codStatoDettFatt;
	}

	public void setCodStatoDettFatt(String codStatoDettFatt) {
		this.codStatoDettFatt = codStatoDettFatt;
	}

	@Column(name = "FLG_INVIO_IN_CONSERV_FATTURA", precision = 22, scale = 0)
	public BigDecimal getFlgInvioInConservFattura() {
		return this.flgInvioInConservFattura;
	}

	public void setFlgInvioInConservFattura(BigDecimal flgInvioInConservFattura) {
		this.flgInvioInConservFattura = flgInvioInConservFattura;
	}

	@Column(name = "TS_INVIO_IN_CONSERV_FATTURA", length = 7)
	public Date getTsInvioInConservFattura() {
		return tsInvioInConservFattura;
	}

	public void setTsInvioInConservFattura(Date tsInvioInConservFattura) {
		this.tsInvioInConservFattura = tsInvioInConservFattura;
	}

	@Column(name = "STATO_CONSERVAZIONE_FATTURA", length = 30)
	public String getStatoConservazioneFattura() {
		return statoConservazioneFattura;
	}

	public void setStatoConservazioneFattura(String statoConservazioneFattura) {
		this.statoConservazioneFattura = statoConservazioneFattura;
	}

	@Column(name = "FLG_INVIO_IN_CONSERV", precision = 22, scale = 0)
	public BigDecimal getFlgInvioInConserv() {
		return this.flgInvioInConserv;
	}

	public void setFlgInvioInConserv(BigDecimal flgInvioInConserv) {
		this.flgInvioInConserv = flgInvioInConserv;
	}

	@Column(name = "TS_INVIO_IN_CONSERV", length = 7)
	public Date getTsInvioInConserv() {
		return tsInvioInConserv;
	}

	public void setTsInvioInConserv(Date tsInvioInConserv) {
		this.tsInvioInConserv = tsInvioInConserv;
	}

	@Column(name = "ID_LOTTO_INVIO_IN_CONSERV", precision = 22, scale = 0)
	public BigDecimal getIdLottoInvioInConserv() {
		return idLottoInvioInConserv;
	}

	public void setIdLottoInvioInConserv(BigDecimal idLottoInvioInConserv) {
		this.idLottoInvioInConserv = idLottoInvioInConserv;
	}

	@Column(name = "ID_IN_CONSERVAZIONE", length = 250)
	public String getIdInConserv() {
		return idInConserv;
	}

	public void setIdInConserv(String idInConserv) {
		this.idInConserv = idInConserv;
	}

	@Column(name = "ERR_MSG_INVIO_IN_CONSERV", length = 4000)
	public String getErrMsgInvioInConserv() {
		return errMsgInvioInConserv;
	}

	public void setErrMsgInvioInConserv(String errMsgInvioInConserv) {
		this.errMsgInvioInConserv = errMsgInvioInConserv;
	}

	@Column(name = "STATO_CONSERVAZIONE", length = 30)
	public String getStatoConservazione() {
		return statoConservazione;
	}

	public void setStatoConservazione(String statoConservazione) {
		this.statoConservazione = statoConservazione;
	}

	@Override
	public String toString() {
		return String
				.format("DmvRicevuteSdiFatture [id=%s, tipoRicevuta=%s, idUdRicevuta=%s, tsArrivoRicevuta=%s, uriRicevuta=%s, displayFilenameRicevuta=%s, mimetypeRicevuta=%s, idDocFattura=%s, denomProduttore=%s, codFiscaleProduttore=%s, connToken=%s, intitolazioneFattura=%s, flgAttivaPassiva=%s, idTrasmittente=%s, progrTrasmSdi=%s, nroFattura=%s, annoFattura=%s, fattData=%s, importoFattura=%s, fattDenomDest=%s, fattCodIpaDest=%s, fattIdFiscDest=%s, codStatoDettFatt=%s, flgInvioInConservFattura=%s, tsInvioInConservFattura=%s, statoConservazioneFattura=%s, flgInvioInConserv=%s, tsInvioInConserv=%s, idLottoInvioInConserv=%s, idInConserv=%s, errMsgInvioInConserv=%s, statoConservazione=%s]",
						id, tipoRicevuta, idUdRicevuta, tsArrivoRicevuta, uriRicevuta, displayFilenameRicevuta, mimetypeRicevuta,
						idDocFattura, denomProduttore, codFiscaleProduttore, connToken, intitolazioneFattura, flgAttivaPassiva,
						idTrasmittente, progrTrasmSdi, nroFattura, annoFattura, fattData, importoFattura, fattDenomDest, fattCodIpaDest,
						fattIdFiscDest, codStatoDettFatt, flgInvioInConservFattura, tsInvioInConservFattura, statoConservazioneFattura,
						flgInvioInConserv, tsInvioInConserv, idLottoInvioInConserv, idInConserv, errMsgInvioInConserv, statoConservazione);
	}

}
