/* * SPDX-License-Identifier: AGPL-3.0-or-later * * C Copyright 2023 Regione Piemonte * */

// Generated 2-mar-2015 16.42.48 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.Table;

import org.hibernate.annotations.Where;

/**
 * DmvScontrini generated by hbm2java
 */
@Entity
@Table(name = "DMV_SCONTRINI")
@Where(clause = "RUOLO_DOC = 'P'")
public class DmvScontrini implements java.io.Serializable {

	private static final long serialVersionUID = -5335203761069281635L;

	private BigDecimal idDoc;

	private String codApplOwner;

	private String codIstApplOwner;

	private String connToken;

	private BigDecimal idUd;

	private BigDecimal idDocType;

	private String ruoloDoc;

	private String codStatoDett;

	private Date tsLastUpdStato;

	private String oggetto;

	private String nroOrdine;

	private String nroScontrino;

	private String codCliente;

	private Date dataEmissione;

	private BigDecimal nroFattura;

	private BigDecimal annoFattura;

	private String uri;

	private String displayFilename;

	private String emailDestinatario;
	
	private DmvScontriniAllegato allegato;

	public DmvScontrini() {
	}

	public DmvScontrini(BigDecimal idDoc, BigDecimal idUd) {
		this.idDoc = idDoc;
		this.idUd = idUd;
	}

	public DmvScontrini(BigDecimal idDoc, String codApplOwner, String codIstApplOwner, String connToken, BigDecimal idUd,
			BigDecimal idDocType, String ruoloDoc, String codStatoDett, Date tsLastUpdStato, String oggetto, String nroOrdine,
			String nroScontrino, String codCliente, Date dataEmissione, BigDecimal nroFattura, BigDecimal annoFattura, String uri,
			String displayFilename, String emailDestinatario, DmvScontriniAllegato allegato) {
		this.idDoc = idDoc;
		this.codApplOwner = codApplOwner;
		this.codIstApplOwner = codIstApplOwner;
		this.connToken = connToken;
		this.idUd = idUd;
		this.idDocType = idDocType;
		this.ruoloDoc = ruoloDoc;
		this.codStatoDett = codStatoDett;
		this.tsLastUpdStato = tsLastUpdStato;
		this.oggetto = oggetto;
		this.nroOrdine = nroOrdine;
		this.nroScontrino = nroScontrino;
		this.codCliente = codCliente;
		this.dataEmissione = dataEmissione;
		this.nroFattura = nroFattura;
		this.annoFattura = annoFattura;
		this.uri = uri;
		this.displayFilename = displayFilename;
		this.emailDestinatario = emailDestinatario;
		this.allegato = allegato;
	}

	@Id
	@Column(name = "ID_DOC", nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdDoc() {
		return this.idDoc;
	}

	public void setIdDoc(BigDecimal idDoc) {
		this.idDoc = idDoc;
	}

	@Column(name = "COD_APPL_OWNER", length = 30)
	public String getCodApplOwner() {
		return this.codApplOwner;
	}

	public void setCodApplOwner(String codApplOwner) {
		this.codApplOwner = codApplOwner;
	}

	@Column(name = "COD_IST_APPL_OWNER", length = 30)
	public String getCodIstApplOwner() {
		return this.codIstApplOwner;
	}

	public void setCodIstApplOwner(String codIstApplOwner) {
		this.codIstApplOwner = codIstApplOwner;
	}

	@Column(name = "CONN_TOKEN", length = 4000)
	public String getConnToken() {
		return this.connToken;
	}

	public void setConnToken(String connToken) {
		this.connToken = connToken;
	}

	@Column(name = "ID_UD", nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdUd() {
		return this.idUd;
	}

	public void setIdUd(BigDecimal idUd) {
		this.idUd = idUd;
	}

	@Column(name = "ID_DOC_TYPE", precision = 22, scale = 0)
	public BigDecimal getIdDocType() {
		return this.idDocType;
	}

	public void setIdDocType(BigDecimal idDocType) {
		this.idDocType = idDocType;
	}

	@Column(name = "RUOLO_DOC", length = 10)
	public String getRuoloDoc() {
		return this.ruoloDoc;
	}

	public void setRuoloDoc(String ruoloDoc) {
		this.ruoloDoc = ruoloDoc;
	}

	@Column(name = "COD_STATO_DETT", length = 10)
	public String getCodStatoDett() {
		return this.codStatoDett;
	}

	public void setCodStatoDett(String codStatoDett) {
		this.codStatoDett = codStatoDett;
	}

	@Column(name = "TS_LAST_UPD_STATO", length = 7)
	public Date getTsLastUpdStato() {
		return this.tsLastUpdStato;
	}

	public void setTsLastUpdStato(Date tsLastUpdStato) {
		this.tsLastUpdStato = tsLastUpdStato;
	}

	@Column(name = "OGGETTO", length = 4000)
	public String getOggetto() {
		return this.oggetto;
	}

	public void setOggetto(String oggetto) {
		this.oggetto = oggetto;
	}

	@Column(name = "NRO_ORDINE", length = 4000)
	public String getNroOrdine() {
		return this.nroOrdine;
	}

	public void setNroOrdine(String nroOrdine) {
		this.nroOrdine = nroOrdine;
	}

	@Column(name = "NRO_SCONTRINO", length = 4000)
	public String getNroScontrino() {
		return this.nroScontrino;
	}

	public void setNroScontrino(String nroScontrino) {
		this.nroScontrino = nroScontrino;
	}

	@Column(name = "COD_CLIENTE", length = 4000)
	public String getCodCliente() {
		return this.codCliente;
	}

	public void setCodCliente(String codCliente) {
		this.codCliente = codCliente;
	}

	@Column(name = "DATA_EMISSIONE", length = 7)
	public Date getDataEmissione() {
		return this.dataEmissione;
	}

	public void setDataEmissione(Date dataEmissione) {
		this.dataEmissione = dataEmissione;
	}

	@Column(name = "NRO_FATTURA", precision = 22, scale = 0)
	public BigDecimal getNroFattura() {
		return this.nroFattura;
	}

	public void setNroFattura(BigDecimal nroFattura) {
		this.nroFattura = nroFattura;
	}

	@Column(name = "ANNO_FATTURA", precision = 22, scale = 0)
	public BigDecimal getAnnoFattura() {
		return this.annoFattura;
	}

	public void setAnnoFattura(BigDecimal annoFattura) {
		this.annoFattura = annoFattura;
	}

	@Column(name = "URI", length = 1000)
	public String getUri() {
		return this.uri;
	}

	public void setUri(String uri) {
		this.uri = uri;
	}

	@Column(name = "DISPLAY_FILENAME", length = 1000)
	public String getDisplayFilename() {
		return this.displayFilename;
	}

	public void setDisplayFilename(String displayFilename) {
		this.displayFilename = displayFilename;
	}

	@Column(name = "EMAIL_DESTINATARIO", length = 4000)
	public String getEmailDestinatario() {
		return this.emailDestinatario;
	}

	public void setEmailDestinatario(String emailDestinatario) {
		this.emailDestinatario = emailDestinatario;
	}

	@OneToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "ID_UD", referencedColumnName = "ID_UD", nullable = false, insertable = false, updatable = false)
	public DmvScontriniAllegato getAllegato() {
		return allegato;
	}

	public void setAllegato(DmvScontriniAllegato allegato) {
		this.allegato = allegato;
	}

}
