/* * SPDX-License-Identifier: AGPL-3.0-or-later * * C Copyright 2023 Regione Piemonte * */
// Generated 30-mar-2017 14.13.19 by Hibernate Tools 3.4.0.CR1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * ElaborazioneScansioniLog generated by hbm2java
 */
@Entity
@Table(name="ELABORAZIONE_SCANSIONI_LOG"
)
public class ElaborazioneScansioniLog  implements java.io.Serializable {


     private BigDecimal idLog;
     private String nomeScansione;
     private String nomeScansioneElaborata;
     private String pathInputFolder;
     private String barcode;
     private Date dataElaborazione;
     private String nomeFileOutput;
     private Boolean barcodeValido;
     private Date dataAssociazione;
     private Boolean esitoAssociazione;
     private String erroreAssociazione;
     private String categoria;
     private String codice;
     private String anno;
     private BigDecimal numeroAllegato;
     private String tipo;
     private String sigla;
     private String subNumRegistrazione;
     private String sezioneFascicolo;
     private Boolean esitoElaborazione;
     private String erroreElaborazione;
     private Boolean opzionePrimaPagina;
     private String patternBarcode;
     private BigDecimal numeroPagine;
     private Date dataFileScansione;
     private BigDecimal dimensioneFile;

    public ElaborazioneScansioniLog() {
    }

	
    public ElaborazioneScansioniLog(BigDecimal idLog, String nomeScansione, String pathInputFolder, Date dataElaborazione) {
        this.idLog = idLog;
        this.nomeScansione = nomeScansione;
        this.pathInputFolder = pathInputFolder;
        this.dataElaborazione = dataElaborazione;
    }
    public ElaborazioneScansioniLog(BigDecimal idLog, String nomeScansione, String pathInputFolder, String barcode, Date dataElaborazione, 
    		String nomeFileOutput, Boolean barcodeValido, Date dataAssociazione, Boolean esitoAssociazione, String erroreAssociazione, 
    		String categoria, String codice, String anno, BigDecimal numeroAllegato, Boolean esitoElaborazione, String erroreElaborazione, 
    		Boolean opzionePrimaPagina, String patternBarcode, BigDecimal numeroPagine) {
       this.idLog = idLog;
       this.nomeScansione = nomeScansione;
       this.pathInputFolder = pathInputFolder;
       this.barcode = barcode;
       this.dataElaborazione = dataElaborazione;
       this.nomeFileOutput = nomeFileOutput;
       this.barcodeValido = barcodeValido;
       this.dataAssociazione = dataAssociazione;
       this.esitoAssociazione = esitoAssociazione;
       this.erroreAssociazione = erroreAssociazione;
       this.categoria = categoria;
       this.codice = codice;
       this.anno = anno;
       this.numeroAllegato = numeroAllegato;
       this.esitoElaborazione = esitoElaborazione;
       this.erroreElaborazione = erroreElaborazione;
       this.opzionePrimaPagina = opzionePrimaPagina;
       this.patternBarcode = patternBarcode;
       this.numeroPagine = numeroPagine;
    }
   
    @Id 
    @GeneratedValue(strategy=GenerationType.SEQUENCE, generator="S_ELABORAZIONE_SCANSIONI_LOG")
	@SequenceGenerator(
			name="S_ELABORAZIONE_SCANSIONI_LOG", 
			sequenceName="S_ELABORAZIONE_SCANSIONI_LOG",
			allocationSize=1)
    @Column(name="ID_LOG", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getIdLog() {
        return this.idLog;
    }
    
    public void setIdLog(BigDecimal idLog) {
        this.idLog = idLog;
    }

    
    @Column(name="NOME_SCANSIONE", nullable=false, length=100)
    public String getNomeScansione() {
        return this.nomeScansione;
    }
    
    public void setNomeScansione(String nomeScansione) {
        this.nomeScansione = nomeScansione;
    }
    
    @Column(name="NOME_SCANSIONE_ELABORATA", nullable=true, length=100)
    public String getNomeScansioneElaborata() {
        return this.nomeScansioneElaborata;
    }
    
    public void setNomeScansioneElaborata(String nomeScansioneElaborata) {
        this.nomeScansioneElaborata = nomeScansioneElaborata;
    }

    
    @Column(name="PATH_INPUT_FOLDER", nullable=false, length=250)
    public String getPathInputFolder() {
        return this.pathInputFolder;
    }
    
    public void setPathInputFolder(String pathInputFolder) {
        this.pathInputFolder = pathInputFolder;
    }

    
    @Column(name="BARCODE", length=50)
    public String getBarcode() {
        return this.barcode;
    }
    
    public void setBarcode(String barcode) {
        this.barcode = barcode;
    }

    
    @Column(name="DATA_ELABORAZIONE", nullable=false)
    public Date getDataElaborazione() {
        return this.dataElaborazione;
    }
    
    public void setDataElaborazione(Date dataElaborazione) {
        this.dataElaborazione = dataElaborazione;
    }

    
    @Column(name="NOME_FILE_OUTPUT", length=100)
    public String getNomeFileOutput() {
        return this.nomeFileOutput;
    }
    
    public void setNomeFileOutput(String nomeFileOutput) {
        this.nomeFileOutput = nomeFileOutput;
    }

    
    @Column(name="BARCODE_VALIDO", precision=1, scale=0)
    public Boolean getBarcodeValido() {
        return this.barcodeValido;
    }
    
    public void setBarcodeValido(Boolean barcodeValido) {
        this.barcodeValido = barcodeValido;
    }

    
    @Column(name="DATA_ASSOCIAZIONE")
    public Date getDataAssociazione() {
        return this.dataAssociazione;
    }
    
    public void setDataAssociazione(Date dataAssociazione) {
        this.dataAssociazione = dataAssociazione;
    }

    
    @Column(name="ESITO_ASSOCIAZIONE", precision=1, scale=0)
    public Boolean getEsitoAssociazione() {
        return this.esitoAssociazione;
    }
    
    public void setEsitoAssociazione(Boolean esitoAssociazione) {
        this.esitoAssociazione = esitoAssociazione;
    }

    
    @Column(name="ERRORE_ASSOCIAZIONE", length=250)
    public String getErroreAssociazione() {
        return this.erroreAssociazione;
    }
    
    public void setErroreAssociazione(String erroreAssociazione) {
        this.erroreAssociazione = erroreAssociazione;
    }

    
    @Column(name="CATEGORIA", length=20)
    public String getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(String categoria) {
        this.categoria = categoria;
    }

    
    @Column(name="CODICE", length=20)
    public String getCodice() {
        return this.codice;
    }
    
    public void setCodice(String codice) {
        this.codice = codice;
    }

    
    @Column(name="ANNO", length=10)
    public String getAnno() {
        return this.anno;
    }
    
    public void setAnno(String anno) {
        this.anno = anno;
    }

    
    @Column(name="NUMERO_ALLEGATO", precision=22, scale=0)
    public BigDecimal getNumeroAllegato() {
        return this.numeroAllegato;
    }
    
    public void setNumeroAllegato(BigDecimal numeroAllegato) {
        this.numeroAllegato = numeroAllegato;
    }

    
    @Column(name="ESITO_ELABORAZIONE", precision=1, scale=0)
    public Boolean getEsitoElaborazione() {
        return this.esitoElaborazione;
    }
    
    public void setEsitoElaborazione(Boolean esitoElaborazione) {
        this.esitoElaborazione = esitoElaborazione;
    }

    
    @Column(name="ERRORE_ELABORAZIONE", length=250)
    public String getErroreElaborazione() {
        return this.erroreElaborazione;
    }
    
    public void setErroreElaborazione(String erroreElaborazione) {
        this.erroreElaborazione = erroreElaborazione;
    }

    
    @Column(name="OPZIONE_PRIMA_PAGINA", precision=1, scale=0)
    public Boolean getOpzionePrimaPagina() {
        return this.opzionePrimaPagina;
    }
    
    public void setOpzionePrimaPagina(Boolean opzionePrimaPagina) {
        this.opzionePrimaPagina = opzionePrimaPagina;
    }

    @Column(name="PATTERN_BARCODE", length=100)
    public String getPatternBarcode() {
        return this.patternBarcode;
    }
    
    public void setPatternBarcode(String patternBarcode) {
        this.patternBarcode = patternBarcode;
    }

    @Column(name="NUMERO_PAGINE", precision=22, scale=0)
    public BigDecimal getNumeroPagine() {
        return this.numeroPagine;
    }
    
    public void setNumeroPagine(BigDecimal numeroPagine) {
        this.numeroPagine = numeroPagine;
    }
    
    @Column(name="TIPO", length=20)
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    
    @Column(name="SIGLA", length=20)
    public String getSigla() {
        return this.sigla;
    }
    
    public void setSigla(String sigla) {
        this.sigla = sigla;
    }
    
    @Column(name="SUB_NUMERO_REG", length=20)
    public String getSubNumRegistrazione() {
        return this.subNumRegistrazione;
    }
    
    public void setSubNumRegistrazione(String subNumRegistrazione) {
        this.subNumRegistrazione = subNumRegistrazione;
    }
    
    @Column(name="SEZIONE_FASCICOLO", length=100)
    public String getSezioneFascicolo() {
        return this.sezioneFascicolo;
    }
    
    public void setSezioneFascicolo(String sezioneFascicolo) {
        this.sezioneFascicolo = sezioneFascicolo;
    }
    
    @Column(name="TS_FILE_SCANSIONE")
    public Date getDataFileScansione() {
        return this.dataFileScansione;
    }
    
    public void setDataFileScansione(Date dataFileScansione) {
        this.dataFileScansione = dataFileScansione;
    }
    
    @Column(name="DIM_FILE_SCANSIONE", precision=38, scale=0)
    public BigDecimal getDimensioneFileScansione() {
        return this.dimensioneFile;
    }
    
    public void setDimensioneFileScansione(BigDecimal dimensioneFile) {
        this.dimensioneFile = dimensioneFile;
    }
}


