/* * SPDX-License-Identifier: AGPL-3.0-or-later * * C Copyright 2023 Regione Piemonte * */

// Generated 16-feb-2015 13.08.58 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * TAlEsigibilitaIva generated by hbm2java
 */
@Entity
@Table(name = "T_AL_ESIGIBILITA_IVA")
public class TAlEsigibilitaIva implements java.io.Serializable {

	private static final long serialVersionUID = 750497219460682839L;

	private TAlEsigibilitaIvaId id;

	public TAlEsigibilitaIva() {
	}

	public TAlEsigibilitaIva(TAlEsigibilitaIvaId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "idSpAoo", column = @Column(name = "ID_SP_AOO", nullable = false)),
			@AttributeOverride(name = "esigibilitaIva", column = @Column(name = "ESIGIBILITA_IVA", nullable = false, length = 20)),
			@AttributeOverride(name = "natura", column = @Column(name = "NATURA", nullable = false)) })
	public TAlEsigibilitaIvaId getId() {
		return this.id;
	}

	public void setId(TAlEsigibilitaIvaId id) {
		this.id = id;
	}

}
