/* * SPDX-License-Identifier: AGPL-3.0-or-later * * C Copyright 2023 Regione Piemonte * */

package it.eng.entity;

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TCodaOperConWf generated by hbm2java
 */
@Entity
@Table(name = "T_CODA_OPER_CON_WF")
public class TCodaOperConWf implements java.io.Serializable {

	private static final long serialVersionUID = -641374143275144571L;

	private String idOperazione;
	private Date tsIns;
	private String tipoOperazione;
	private String dipendeDaOper;
	private BigDecimal idProcess;
	private String taskInstanceId;
	private String taskDefKey;
	private String tyObj;
	private BigDecimal idObj;
	private Date tsLastTry;
	private BigDecimal numTry;
	private BigDecimal errCode;
	private String errMsg;
	private String esitoElab;
	private BigDecimal idEventType;
	private String attrEventType;
	private BigDecimal idUserIns;
	private BigDecimal idUserAnomeDi;
	private String ciConnectionToken;
    private String msgComplTask;
    private BigDecimal idDominio;
	
	public TCodaOperConWf() {
	}

	public TCodaOperConWf(String idOperazione, Date tsIns, String tipoOperazione, BigDecimal numTry) {
		this.idOperazione = idOperazione;
		this.tsIns = tsIns;
		this.tipoOperazione = tipoOperazione;
		this.numTry = numTry;
	}

	public TCodaOperConWf(String idOperazione, Date tsIns, String tipoOperazione, String dipendeDaOper,
			BigDecimal idProcess, String taskInstanceId, String taskDefKey, String tyObj, BigDecimal idObj,
			Date tsLastTry, BigDecimal numTry, BigDecimal errCode, String errMsg, String esitoElab, BigDecimal idEventType, String attrEventType) {
		this.idOperazione = idOperazione;
		this.tsIns = tsIns;
		this.tipoOperazione = tipoOperazione;
		this.dipendeDaOper = dipendeDaOper;
		this.idProcess = idProcess;
		this.taskInstanceId = taskInstanceId;
		this.taskDefKey = taskDefKey;
		this.tyObj = tyObj;
		this.idObj = idObj;
		this.tsLastTry = tsLastTry;
		this.numTry = numTry;
		this.errCode = errCode;
		this.errMsg = errMsg;
		this.esitoElab = esitoElab;
		this.idEventType = idEventType;
		this.attrEventType = attrEventType;
	}

	@Id
	@Column(name = "ID_OPERAZIONE", unique = true, nullable = false, length = 64)
	public String getIdOperazione() {
		return this.idOperazione;
	}

	public void setIdOperazione(String idOperazione) {
		this.idOperazione = idOperazione;
	}

	@Column(name = "TS_INS", nullable = false)
	public Date getTsIns() {
		return this.tsIns;
	}

	public void setTsIns(Date tsIns) {
		this.tsIns = tsIns;
	}

	@Column(name = "TIPO_OPERAZIONE", nullable = false, length = 100)
	public String getTipoOperazione() {
		return this.tipoOperazione;
	}

	public void setTipoOperazione(String tipoOperazione) {
		this.tipoOperazione = tipoOperazione;
	}

	@Column(name = "DIPENDE_DA_OPER", length = 64)
	public String getDipendeDaOper() {
		return this.dipendeDaOper;
	}

	public void setDipendeDaOper(String dipendeDaOper) {
		this.dipendeDaOper = dipendeDaOper;
	}

	@Column(name = "ID_PROCESS", precision = 22, scale = 0)
	public BigDecimal getIdProcess() {
		return this.idProcess;
	}

	public void setIdProcess(BigDecimal idProcess) {
		this.idProcess = idProcess;
	}

	@Column(name = "TASK_INSTANCE_ID", length = 500)
	public String getTaskInstanceId() {
		return this.taskInstanceId;
	}

	public void setTaskInstanceId(String taskInstanceId) {
		this.taskInstanceId = taskInstanceId;
	}

	@Column(name = "TASK_DEF_KEY", length = 500)
	public String getTaskDefKey() {
		return this.taskDefKey;
	}

	public void setTaskDefKey(String taskDefKey) {
		this.taskDefKey = taskDefKey;
	}

	@Column(name = "TY_OBJ", length = 10)
	public String getTyObj() {
		return this.tyObj;
	}

	public void setTyObj(String tyObj) {
		this.tyObj = tyObj;
	}

	@Column(name = "ID_OBJ", precision = 22, scale = 0)
	public BigDecimal getIdObj() {
		return this.idObj;
	}

	public void setIdObj(BigDecimal idObj) {
		this.idObj = idObj;
	}

	@Column(name = "TS_LAST_TRY")
	public Date getTsLastTry() {
		return this.tsLastTry;
	}

	public void setTsLastTry(Date tsLastTry) {
		this.tsLastTry = tsLastTry;
	}

	@Column(name = "NUM_TRY", nullable = false, precision = 22, scale = 0)
	public BigDecimal getNumTry() {
		return this.numTry;
	}

	public void setNumTry(BigDecimal numTry) {
		this.numTry = numTry;
	}

	@Column(name = "ERR_CODE", precision = 22, scale = 0)
	public BigDecimal getErrCode() {
		return this.errCode;
	}

	public void setErrCode(BigDecimal errCode) {
		this.errCode = errCode;
	}

	@Column(name = "ERR_MSG")
	public String getErrMsg() {
		return this.errMsg;
	}

	public void setErrMsg(String errMsg) {
		this.errMsg = errMsg;
	}

	@Column(name = "ESITO_ELAB", length = 2)
	public String getEsitoElab() {
		return this.esitoElab;
	}

	public void setEsitoElab(String esitoElab) {
		this.esitoElab = esitoElab;
	}

	@Column(name = "ID_EVENT_TYPE", precision = 38, scale = 0)
	public BigDecimal getIdEventType() {
		return this.idEventType;
	}

	public void setIdEventType(BigDecimal idEventType) {
		this.idEventType = idEventType;
	}
	@Column(name = "ATTR_EVENT_TYPE")
	public String getAttrEventType() {
		return this.attrEventType;
	}

	public void setAttrEventType(String attrEventType) {
		this.attrEventType = attrEventType;
	}
    
	@Column(name = "ID_USER_INS", precision = 22, scale = 0)
	public BigDecimal getIdUserIns() {
		return idUserIns;
	}


	public void setIdUserIns(BigDecimal idUserIns) {
		this.idUserIns = idUserIns;
	}
	
	@Column(name = "ID_DOMINIO", precision = 22, scale = 0)
	public BigDecimal getIdDominio() {
		return idDominio;
	}

	public void setIdDominio(BigDecimal idDominio) {
		this.idDominio = idDominio;
	}

	@Column(name = "ID_USER_A_NOME_DI", precision = 22, scale = 0)
	public BigDecimal getIdUserAnomeDi() {
		return idUserAnomeDi;
	}

	public void setIdUserAnomeDi(BigDecimal idUserAnomeDi) {
		this.idUserAnomeDi = idUserAnomeDi;
	}
    
	
	@Column(name = "CI_CONNECTION_TOKEN")
	public String getCiConnectionToken() {
		return ciConnectionToken;
	}

	public void setCiConnectionToken(String ciConnectionToken) {
		this.ciConnectionToken = ciConnectionToken;
	}

	@Column(name = "MSG_COMPL_TASK")
	public String getMsgComplTask() {
		return msgComplTask;
	}

	public void setMsgComplTask(String msgComplTask) {
		this.msgComplTask = msgComplTask;
	}
	
	
	@Override
	public String toString() {
		return "TCodaOperConWf [idOperazione=" + idOperazione + ", tsIns=" + tsIns + ", tipoOperazione="
				+ tipoOperazione + ", dipendeDaOper=" + dipendeDaOper + ", idProcess=" + idProcess + ", taskInstanceId="
				+ taskInstanceId + ", taskDefKey=" + taskDefKey + ", tyObj=" + tyObj + ", idObj=" + idObj
				+ ", tsLastTry=" + tsLastTry + ", numTry=" + numTry + ", errCode=" + errCode + ", errMsg=" + errMsg
				+ ", esitoElab=" + esitoElab + ", idEventType=" + idEventType + ", attrEventType=" + attrEventType
				+ ", idUserIns=" + idUserIns + ", idUserAnomeDi=" + idUserAnomeDi + ", ciConnectionToken="
				+ ciConnectionToken + ", msgComplTask=" + msgComplTask + "]";
	}

}
