/* * SPDX-License-Identifier: AGPL-3.0-or-later * * C Copyright 2023 Regione Piemonte * */
// Generated 15-set-2017 15.23.59 by Hibernate Tools 3.6.0.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * TDocDaInviareDocfly generated by hbm2java
 */
@Entity
@Table(name = "T_DOC_DA_INVIARE_DOCFLY", uniqueConstraints = @UniqueConstraint(columnNames = { "ID_UD", "ID_DOC" }))
public class TDocDaInviareDocfly implements java.io.Serializable {

	private static final long serialVersionUID = 3312019627859264292L;

	private BigDecimal idDoc;
	private TPdvDocfly TPdvDocfly;
	private BigDecimal idSpAoo;
	private String codApplOwner;
	private String codIstApplOwner;
	private BigDecimal idUd;
	private String intitolazioneFattura;
	private String flgAttivaPassiva;
	private String nroFattura;
	private Date fattData;
	private String fattIdFiscDest;
	private String fattDenomDest;
	private String progrTrasmSdi;
	private String displayFilename;
	private Boolean statoLavorazione;
	private Date tsUltimoTentativo;

	public TDocDaInviareDocfly() {
	}

	public TDocDaInviareDocfly(BigDecimal idDoc) {
		this.idDoc = idDoc;
	}

	public TDocDaInviareDocfly(BigDecimal idDoc, TPdvDocfly TPdvDocfly, BigDecimal idSpAoo, String codApplOwner,
			String codIstApplOwner, BigDecimal idUd, String intitolazioneFattura, String flgAttivaPassiva,
			String nroFattura, Date fattData, String fattIdFiscDest, String fattDenomDest, String progrTrasmSdi,
			String displayFilename, Boolean statoLavorazione, Date tsUltimoTentativo) {
		this.idDoc = idDoc;
		this.TPdvDocfly = TPdvDocfly;
		this.idSpAoo = idSpAoo;
		this.codApplOwner = codApplOwner;
		this.codIstApplOwner = codIstApplOwner;
		this.idUd = idUd;
		this.intitolazioneFattura = intitolazioneFattura;
		this.flgAttivaPassiva = flgAttivaPassiva;
		this.nroFattura = nroFattura;
		this.fattData = fattData;
		this.fattIdFiscDest = fattIdFiscDest;
		this.fattDenomDest = fattDenomDest;
		this.progrTrasmSdi = progrTrasmSdi;
		this.displayFilename = displayFilename;
		this.statoLavorazione = statoLavorazione;
		this.tsUltimoTentativo = tsUltimoTentativo;
	}

	@Id

	@Column(name = "ID_DOC", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdDoc() {
		return this.idDoc;
	}

	public void setIdDoc(BigDecimal idDoc) {
		this.idDoc = idDoc;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "ID_PDV")
	public TPdvDocfly getTPdvDocfly() {
		return this.TPdvDocfly;
	}

	public void setTPdvDocfly(TPdvDocfly TPdvDocfly) {
		this.TPdvDocfly = TPdvDocfly;
	}

	@Column(name = "ID_SP_AOO", precision = 22, scale = 0)
	public BigDecimal getIdSpAoo() {
		return this.idSpAoo;
	}

	public void setIdSpAoo(BigDecimal idSpAoo) {
		this.idSpAoo = idSpAoo;
	}

	@Column(name = "COD_APPL_OWNER", length = 30)
	public String getCodApplOwner() {
		return this.codApplOwner;
	}

	public void setCodApplOwner(String codApplOwner) {
		this.codApplOwner = codApplOwner;
	}

	@Column(name = "COD_IST_APPL_OWNER", length = 30)
	public String getCodIstApplOwner() {
		return this.codIstApplOwner;
	}

	public void setCodIstApplOwner(String codIstApplOwner) {
		this.codIstApplOwner = codIstApplOwner;
	}

	@Column(name = "ID_UD", precision = 22, scale = 0)
	public BigDecimal getIdUd() {
		return this.idUd;
	}

	public void setIdUd(BigDecimal idUd) {
		this.idUd = idUd;
	}

	@Column(name = "INTITOLAZIONE_FATTURA", length = 100)
	public String getIntitolazioneFattura() {
		return this.intitolazioneFattura;
	}

	public void setIntitolazioneFattura(String intitolazioneFattura) {
		this.intitolazioneFattura = intitolazioneFattura;
	}

	@Column(name = "FLG_ATTIVA_PASSIVA", length = 10)
	public String getFlgAttivaPassiva() {
		return this.flgAttivaPassiva;
	}

	public void setFlgAttivaPassiva(String flgAttivaPassiva) {
		this.flgAttivaPassiva = flgAttivaPassiva;
	}

	@Column(name = "NRO_FATTURA", length = 100)
	public String getNroFattura() {
		return this.nroFattura;
	}

	public void setNroFattura(String nroFattura) {
		this.nroFattura = nroFattura;
	}

	@Column(name = "FATT_DATA", length = 7)
	public Date getFattData() {
		return this.fattData;
	}

	public void setFattData(Date fattData) {
		this.fattData = fattData;
	}

	@Column(name = "FATT_ID_FISC_DEST", length = 100)
	public String getFattIdFiscDest() {
		return this.fattIdFiscDest;
	}

	public void setFattIdFiscDest(String fattIdFiscDest) {
		this.fattIdFiscDest = fattIdFiscDest;
	}

	@Column(name = "FATT_DENOM_DEST", length = 1000)
	public String getFattDenomDest() {
		return this.fattDenomDest;
	}

	public void setFattDenomDest(String fattDenomDest) {
		this.fattDenomDest = fattDenomDest;
	}

	@Column(name = "PROGR_TRASM_SDI", length = 10)
	public String getProgrTrasmSdi() {
		return this.progrTrasmSdi;
	}

	public void setProgrTrasmSdi(String progrTrasmSdi) {
		this.progrTrasmSdi = progrTrasmSdi;
	}

	@Column(name = "DISPLAY_FILENAME", length = 1000)
	public String getDisplayFilename() {
		return this.displayFilename;
	}

	public void setDisplayFilename(String displayFilename) {
		this.displayFilename = displayFilename;
	}

	@Column(name = "STATO_LAVORAZIONE", precision = 1, scale = 0)
	public Boolean getStatoLavorazione() {
		return this.statoLavorazione;
	}

	public void setStatoLavorazione(Boolean statoLavorazione) {
		this.statoLavorazione = statoLavorazione;
	}

	@Column(name = "TS_ULTIMO_TENTATIVO")
	public Date getTsUltimoTentativo() {
		return this.tsUltimoTentativo;
	}

	public void setTsUltimoTentativo(Date tsUltimoTentativo) {
		this.tsUltimoTentativo = tsUltimoTentativo;
	}

}
