/* * SPDX-License-Identifier: AGPL-3.0-or-later * * C Copyright 2023 Regione Piemonte * */

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * TEmailMgo generated by hbm2java
 */
@Entity
@Table(name = "T_EMAIL_MGO", uniqueConstraints = @UniqueConstraint(columnNames = { "MESSAGE_ID", "ID_CASELLA" }))
@org.hibernate.annotations.Entity(dynamicUpdate = true, dynamicInsert = true)
public class TEmailMgo implements java.io.Serializable {

	private static final long serialVersionUID = -7759890728860497057L;
	private String idEmail;
	private String messageId;
	private String idCasella;
	private String flgIo;
	private String categoria;
	private long dimensione;
	private String uriEmail;
	private boolean flgSpam;
	private String flgStatoSpam;
	private String flgRicevutaCbs;
	private String statoConsolidamento;
	private short nroAllegati;
	private short nroAllegatiFirmati;
	private boolean flgEmailFirmata;
	private boolean flgNoAssocAuto;
	private String accountMittente;
	private String oggetto;
	private String corpo;
	private String avvertimenti;
	private Date tsLock;
	private String idUtenteLock;
	private String idRecDizOperLock;
	private boolean flgRichConferma;
	private Date tsRicezione;
	private Date tsInvio;
	private Date tsInvioClient;
	private Date tsAssegn;
	private String idUoAssegn;
	private String idUtenteAssegn;
	private boolean flgInviataRisposta;
	private boolean flgInoltrata;
	private String flgStatoProt;
	private String idRecDizContrassegno;
	private boolean flgNotifInteropEcc;
	private boolean flgNotifInteropConf;
	private boolean flgNotifInteropAgg;
	private boolean flgNotifInteropAnn;
	private Long livPriorita;
	private Date tsLettura;
	private Date tsIns;
	private String idUteIns;
	private Date tsUltimoAgg;
	private String idUteUltimoAgg;
	private String accountMittenteCtx;
	private String oggettoCtx;
	private String corpoCtx;
	private String siglaRegistroMitt;
	private Integer numRegMitt;
	private Short annoRegMitt;
	private Date tsRegMitt;
	private String oggettoRegMitt;
	private String oggettoRegMittCtx;
	private String statoLavorazione;
	private boolean flgRichConfLettura;
	private String messageIdTrasporto;
	private String codAzioneDaFare;
	private String dettAzioneDaFare;
	private BigDecimal progrMsg;
	private BigDecimal annoProgrMsg;
	private String registroProgrMsg;
	private Date tsAggStatoLavorazione;
	private String statoInvio;
	private String statoAccettazione;
	private String statoConsegna;
	private String motivoEccezione;
	private BigDecimal progrBozza;
	private Short annoProgrBozza;
	private String idUtenteAggStatoLav;
	private TEmailCompressione TEmailCompressione;

	public TEmailMgo() {
	}

	public TEmailMgo(String idEmail, String messageId, String idCasella, String categoria, long dimensione,
			String uriEmail, boolean flgSpam, short nroAllegati, short nroAllegatiFirmati, boolean flgEmailFirmata,
			boolean flgNoAssocAuto, boolean flgRichConferma, boolean flgInviataRisposta, boolean flgInoltrata,
			boolean flgNotifInteropEcc, boolean flgNotifInteropConf, boolean flgNotifInteropAgg,
			boolean flgNotifInteropAnn, Date tsIns, Date tsUltimoAgg, boolean flgRichConfLettura) {
		this.idEmail = idEmail;
		this.messageId = messageId;
		this.idCasella = idCasella;
		this.categoria = categoria;
		this.dimensione = dimensione;
		this.uriEmail = uriEmail;
		this.flgSpam = flgSpam;
		this.nroAllegati = nroAllegati;
		this.nroAllegatiFirmati = nroAllegatiFirmati;
		this.flgEmailFirmata = flgEmailFirmata;
		this.flgNoAssocAuto = flgNoAssocAuto;
		this.flgRichConferma = flgRichConferma;
		this.flgInviataRisposta = flgInviataRisposta;
		this.flgInoltrata = flgInoltrata;
		this.flgNotifInteropEcc = flgNotifInteropEcc;
		this.flgNotifInteropConf = flgNotifInteropConf;
		this.flgNotifInteropAgg = flgNotifInteropAgg;
		this.flgNotifInteropAnn = flgNotifInteropAnn;
		this.tsIns = tsIns;
		this.tsUltimoAgg = tsUltimoAgg;
		this.flgRichConfLettura = flgRichConfLettura;
	}

	public TEmailMgo(String idEmail, String messageId, String idCasella, String flgIo, String categoria,
			long dimensione, String uriEmail, boolean flgSpam, String flgStatoSpam, String flgRicevutaCbs,
			String statoConsolidamento, short nroAllegati, short nroAllegatiFirmati, boolean flgEmailFirmata,
			boolean flgNoAssocAuto, String accountMittente, String oggetto, String corpo, String avvertimenti,
			Date tsLock, String idUtenteLock, String idRecDizOperLock, boolean flgRichConferma, Date tsRicezione,
			Date tsInvio, Date tsInvioClient, Date tsAssegn, String idUoAssegn, String idUtenteAssegn,
			boolean flgInviataRisposta, boolean flgInoltrata, String flgStatoProt, String idRecDizContrassegno,
			boolean flgNotifInteropEcc, boolean flgNotifInteropConf, boolean flgNotifInteropAgg,
			boolean flgNotifInteropAnn, Long livPriorita, Date tsLettura, Date tsIns, String idUteIns, Date tsUltimoAgg,
			String idUteUltimoAgg, String accountMittenteCtx, String oggettoCtx, String corpoCtx,
			String siglaRegistroMitt, Integer numRegMitt, Short annoRegMitt, Date tsRegMitt, String oggettoRegMitt,
			String oggettoRegMittCtx, String statoLavorazione, boolean flgRichConfLettura, String messageIdTrasporto,
			String codAzioneDaFare, String dettAzioneDaFare, BigDecimal progrMsg, BigDecimal annoProgrMsg,
			String registroProgrMsg, Date tsAggStatoLavorazione, String statoInvio, String statoAccettazione,
			String statoConsegna, String motivoEccezione, BigDecimal progrBozza, Short annoProgrBozza,
			String idUtenteAggStatoLav, TEmailCompressione TEmailCompressione) {
		this.idEmail = idEmail;
		this.messageId = messageId;
		this.idCasella = idCasella;
		this.flgIo = flgIo;
		this.categoria = categoria;
		this.dimensione = dimensione;
		this.uriEmail = uriEmail;
		this.flgSpam = flgSpam;
		this.flgStatoSpam = flgStatoSpam;
		this.flgRicevutaCbs = flgRicevutaCbs;
		this.statoConsolidamento = statoConsolidamento;
		this.nroAllegati = nroAllegati;
		this.nroAllegatiFirmati = nroAllegatiFirmati;
		this.flgEmailFirmata = flgEmailFirmata;
		this.flgNoAssocAuto = flgNoAssocAuto;
		this.accountMittente = accountMittente;
		this.oggetto = oggetto;
		this.corpo = corpo;
		this.avvertimenti = avvertimenti;
		this.tsLock = tsLock;
		this.idUtenteLock = idUtenteLock;
		this.idRecDizOperLock = idRecDizOperLock;
		this.flgRichConferma = flgRichConferma;
		this.tsRicezione = tsRicezione;
		this.tsInvio = tsInvio;
		this.tsInvioClient = tsInvioClient;
		this.tsAssegn = tsAssegn;
		this.idUoAssegn = idUoAssegn;
		this.idUtenteAssegn = idUtenteAssegn;
		this.flgInviataRisposta = flgInviataRisposta;
		this.flgInoltrata = flgInoltrata;
		this.flgStatoProt = flgStatoProt;
		this.idRecDizContrassegno = idRecDizContrassegno;
		this.flgNotifInteropEcc = flgNotifInteropEcc;
		this.flgNotifInteropConf = flgNotifInteropConf;
		this.flgNotifInteropAgg = flgNotifInteropAgg;
		this.flgNotifInteropAnn = flgNotifInteropAnn;
		this.livPriorita = livPriorita;
		this.tsLettura = tsLettura;
		this.tsIns = tsIns;
		this.idUteIns = idUteIns;
		this.tsUltimoAgg = tsUltimoAgg;
		this.idUteUltimoAgg = idUteUltimoAgg;
		this.accountMittenteCtx = accountMittenteCtx;
		this.oggettoCtx = oggettoCtx;
		this.corpoCtx = corpoCtx;
		this.siglaRegistroMitt = siglaRegistroMitt;
		this.numRegMitt = numRegMitt;
		this.annoRegMitt = annoRegMitt;
		this.tsRegMitt = tsRegMitt;
		this.oggettoRegMitt = oggettoRegMitt;
		this.oggettoRegMittCtx = oggettoRegMittCtx;
		this.statoLavorazione = statoLavorazione;
		this.flgRichConfLettura = flgRichConfLettura;
		this.messageIdTrasporto = messageIdTrasporto;
		this.codAzioneDaFare = codAzioneDaFare;
		this.dettAzioneDaFare = dettAzioneDaFare;
		this.progrMsg = progrMsg;
		this.annoProgrMsg = annoProgrMsg;
		this.registroProgrMsg = registroProgrMsg;
		this.tsAggStatoLavorazione = tsAggStatoLavorazione;
		this.statoInvio = statoInvio;
		this.statoAccettazione = statoAccettazione;
		this.statoConsegna = statoConsegna;
		this.motivoEccezione = motivoEccezione;
		this.progrBozza = progrBozza;
		this.annoProgrBozza = annoProgrBozza;
		this.idUtenteAggStatoLav = idUtenteAggStatoLav;
		this.TEmailCompressione = TEmailCompressione;
	}

	@Id

	@Column(name = "ID_EMAIL", unique = true, nullable = false, length = 64)
	public String getIdEmail() {
		return this.idEmail;
	}

	public void setIdEmail(String idEmail) {
		this.idEmail = idEmail;
	}

	@Column(name = "MESSAGE_ID", nullable = false, length = 500)
	public String getMessageId() {
		return this.messageId;
	}

	public void setMessageId(String messageId) {
		this.messageId = messageId;
	}

	@Column(name = "ID_CASELLA", nullable = false, length = 64)
	public String getIdCasella() {
		return this.idCasella;
	}

	public void setIdCasella(String idCasella) {
		this.idCasella = idCasella;
	}

	@Column(name = "FLG_IO", length = 1)
	public String getFlgIo() {
		return this.flgIo;
	}

	public void setFlgIo(String flgIo) {
		this.flgIo = flgIo;
	}

	@Column(name = "CATEGORIA", nullable = false, length = 30)
	public String getCategoria() {
		return this.categoria;
	}

	public void setCategoria(String categoria) {
		this.categoria = categoria;
	}

	@Column(name = "DIMENSIONE", nullable = false, precision = 10, scale = 0)
	public long getDimensione() {
		return this.dimensione;
	}

	public void setDimensione(long dimensione) {
		this.dimensione = dimensione;
	}

	@Column(name = "URI_EMAIL", nullable = false, length = 2000)
	public String getUriEmail() {
		return this.uriEmail;
	}

	public void setUriEmail(String uriEmail) {
		this.uriEmail = uriEmail;
	}

	@Column(name = "FLG_SPAM", nullable = false, precision = 1, scale = 0)
	public boolean isFlgSpam() {
		return this.flgSpam;
	}

	public void setFlgSpam(boolean flgSpam) {
		this.flgSpam = flgSpam;
	}

	@Column(name = "FLG_STATO_SPAM", length = 2)
	public String getFlgStatoSpam() {
		return this.flgStatoSpam;
	}

	public void setFlgStatoSpam(String flgStatoSpam) {
		this.flgStatoSpam = flgStatoSpam;
	}

	@Column(name = "FLG_RICEVUTA_CBS", length = 1)
	public String getFlgRicevutaCbs() {
		return this.flgRicevutaCbs;
	}

	public void setFlgRicevutaCbs(String flgRicevutaCbs) {
		this.flgRicevutaCbs = flgRicevutaCbs;
	}

	@Column(name = "STATO_CONSOLIDAMENTO", length = 30)
	public String getStatoConsolidamento() {
		return this.statoConsolidamento;
	}

	public void setStatoConsolidamento(String statoConsolidamento) {
		this.statoConsolidamento = statoConsolidamento;
	}

	@Column(name = "NRO_ALLEGATI", nullable = false, precision = 4, scale = 0)
	public short getNroAllegati() {
		return this.nroAllegati;
	}

	public void setNroAllegati(short nroAllegati) {
		this.nroAllegati = nroAllegati;
	}

	@Column(name = "NRO_ALLEGATI_FIRMATI", nullable = false, precision = 4, scale = 0)
	public short getNroAllegatiFirmati() {
		return this.nroAllegatiFirmati;
	}

	public void setNroAllegatiFirmati(short nroAllegatiFirmati) {
		this.nroAllegatiFirmati = nroAllegatiFirmati;
	}

	@Column(name = "FLG_EMAIL_FIRMATA", nullable = false, precision = 1, scale = 0)
	public boolean isFlgEmailFirmata() {
		return this.flgEmailFirmata;
	}

	public void setFlgEmailFirmata(boolean flgEmailFirmata) {
		this.flgEmailFirmata = flgEmailFirmata;
	}

	@Column(name = "FLG_NO_ASSOC_AUTO", nullable = false, precision = 1, scale = 0)
	public boolean isFlgNoAssocAuto() {
		return this.flgNoAssocAuto;
	}

	public void setFlgNoAssocAuto(boolean flgNoAssocAuto) {
		this.flgNoAssocAuto = flgNoAssocAuto;
	}

	@Column(name = "ACCOUNT_MITTENTE", length = 150)
	public String getAccountMittente() {
		return this.accountMittente;
	}

	public void setAccountMittente(String accountMittente) {
		this.accountMittente = accountMittente;
	}

	@Column(name = "OGGETTO", length = 4000)
	public String getOggetto() {
		return this.oggetto;
	}

	public void setOggetto(String oggetto) {
		this.oggetto = oggetto;
	}

	@Column(name = "CORPO")
	public String getCorpo() {
		return this.corpo;
	}

	public void setCorpo(String corpo) {
		this.corpo = corpo;
	}

	@Column(name = "AVVERTIMENTI", length = 4000)
	public String getAvvertimenti() {
		return this.avvertimenti;
	}

	public void setAvvertimenti(String avvertimenti) {
		this.avvertimenti = avvertimenti;
	}

	@Column(name = "TS_LOCK", length = 7)
	public Date getTsLock() {
		return this.tsLock;
	}

	public void setTsLock(Date tsLock) {
		this.tsLock = tsLock;
	}

	@Column(name = "ID_UTENTE_LOCK", length = 64)
	public String getIdUtenteLock() {
		return this.idUtenteLock;
	}

	public void setIdUtenteLock(String idUtenteLock) {
		this.idUtenteLock = idUtenteLock;
	}

	@Column(name = "ID_REC_DIZ_OPER_LOCK", length = 64)
	public String getIdRecDizOperLock() {
		return this.idRecDizOperLock;
	}

	public void setIdRecDizOperLock(String idRecDizOperLock) {
		this.idRecDizOperLock = idRecDizOperLock;
	}

	@Column(name = "FLG_RICH_CONFERMA", nullable = false, precision = 1, scale = 0)
	public boolean isFlgRichConferma() {
		return this.flgRichConferma;
	}

	public void setFlgRichConferma(boolean flgRichConferma) {
		this.flgRichConferma = flgRichConferma;
	}

	@Column(name = "TS_RICEZIONE", length = 7)
	public Date getTsRicezione() {
		return this.tsRicezione;
	}

	public void setTsRicezione(Date tsRicezione) {
		this.tsRicezione = tsRicezione;
	}

	@Column(name = "TS_INVIO", length = 7)
	public Date getTsInvio() {
		return this.tsInvio;
	}

	public void setTsInvio(Date tsInvio) {
		this.tsInvio = tsInvio;
	}

	@Column(name = "TS_INVIO_CLIENT", length = 7)
	public Date getTsInvioClient() {
		return this.tsInvioClient;
	}

	public void setTsInvioClient(Date tsInvioClient) {
		this.tsInvioClient = tsInvioClient;
	}

	@Column(name = "TS_ASSEGN", length = 7)
	public Date getTsAssegn() {
		return this.tsAssegn;
	}

	public void setTsAssegn(Date tsAssegn) {
		this.tsAssegn = tsAssegn;
	}

	@Column(name = "ID_UO_ASSEGN", length = 64)
	public String getIdUoAssegn() {
		return this.idUoAssegn;
	}

	public void setIdUoAssegn(String idUoAssegn) {
		this.idUoAssegn = idUoAssegn;
	}

	@Column(name = "ID_UTENTE_ASSEGN", length = 64)
	public String getIdUtenteAssegn() {
		return this.idUtenteAssegn;
	}

	public void setIdUtenteAssegn(String idUtenteAssegn) {
		this.idUtenteAssegn = idUtenteAssegn;
	}

	@Column(name = "FLG_INVIATA_RISPOSTA", nullable = false, precision = 1, scale = 0)
	public boolean isFlgInviataRisposta() {
		return this.flgInviataRisposta;
	}

	public void setFlgInviataRisposta(boolean flgInviataRisposta) {
		this.flgInviataRisposta = flgInviataRisposta;
	}

	@Column(name = "FLG_INOLTRATA", nullable = false, precision = 1, scale = 0)
	public boolean isFlgInoltrata() {
		return this.flgInoltrata;
	}

	public void setFlgInoltrata(boolean flgInoltrata) {
		this.flgInoltrata = flgInoltrata;
	}

	@Column(name = "FLG_STATO_PROT", length = 1)
	public String getFlgStatoProt() {
		return this.flgStatoProt;
	}

	public void setFlgStatoProt(String flgStatoProt) {
		this.flgStatoProt = flgStatoProt;
	}

	@Column(name = "ID_REC_DIZ_CONTRASSEGNO", length = 64)
	public String getIdRecDizContrassegno() {
		return this.idRecDizContrassegno;
	}

	public void setIdRecDizContrassegno(String idRecDizContrassegno) {
		this.idRecDizContrassegno = idRecDizContrassegno;
	}

	@Column(name = "FLG_NOTIF_INTEROP_ECC", nullable = false, precision = 1, scale = 0)
	public boolean isFlgNotifInteropEcc() {
		return this.flgNotifInteropEcc;
	}

	public void setFlgNotifInteropEcc(boolean flgNotifInteropEcc) {
		this.flgNotifInteropEcc = flgNotifInteropEcc;
	}

	@Column(name = "FLG_NOTIF_INTEROP_CONF", nullable = false, precision = 1, scale = 0)
	public boolean isFlgNotifInteropConf() {
		return this.flgNotifInteropConf;
	}

	public void setFlgNotifInteropConf(boolean flgNotifInteropConf) {
		this.flgNotifInteropConf = flgNotifInteropConf;
	}

	@Column(name = "FLG_NOTIF_INTEROP_AGG", nullable = false, precision = 1, scale = 0)
	public boolean isFlgNotifInteropAgg() {
		return this.flgNotifInteropAgg;
	}

	public void setFlgNotifInteropAgg(boolean flgNotifInteropAgg) {
		this.flgNotifInteropAgg = flgNotifInteropAgg;
	}

	@Column(name = "FLG_NOTIF_INTEROP_ANN", nullable = false, precision = 1, scale = 0)
	public boolean isFlgNotifInteropAnn() {
		return this.flgNotifInteropAnn;
	}

	public void setFlgNotifInteropAnn(boolean flgNotifInteropAnn) {
		this.flgNotifInteropAnn = flgNotifInteropAnn;
	}

	@Column(name = "LIV_PRIORITA", precision = 10, scale = 0)
	public Long getLivPriorita() {
		return this.livPriorita;
	}

	public void setLivPriorita(Long livPriorita) {
		this.livPriorita = livPriorita;
	}

	@Column(name = "TS_LETTURA", length = 7)
	public Date getTsLettura() {
		return this.tsLettura;
	}

	public void setTsLettura(Date tsLettura) {
		this.tsLettura = tsLettura;
	}

	@Column(name = "TS_INS", nullable = false)
	public Date getTsIns() {
		return this.tsIns;
	}

	public void setTsIns(Date tsIns) {
		this.tsIns = tsIns;
	}

	@Column(name = "ID_UTE_INS", length = 64)
	public String getIdUteIns() {
		return this.idUteIns;
	}

	public void setIdUteIns(String idUteIns) {
		this.idUteIns = idUteIns;
	}

	@Column(name = "TS_ULTIMO_AGG", nullable = false)
	public Date getTsUltimoAgg() {
		return this.tsUltimoAgg;
	}

	public void setTsUltimoAgg(Date tsUltimoAgg) {
		this.tsUltimoAgg = tsUltimoAgg;
	}

	@Column(name = "ID_UTE_ULTIMO_AGG", length = 64)
	public String getIdUteUltimoAgg() {
		return this.idUteUltimoAgg;
	}

	public void setIdUteUltimoAgg(String idUteUltimoAgg) {
		this.idUteUltimoAgg = idUteUltimoAgg;
	}

	@Column(name = "ACCOUNT_MITTENTE_CTX", length = 200)
	public String getAccountMittenteCtx() {
		return this.accountMittenteCtx;
	}

	public void setAccountMittenteCtx(String accountMittenteCtx) {
		this.accountMittenteCtx = accountMittenteCtx;
	}

	@Column(name = "OGGETTO_CTX", length = 4000)
	public String getOggettoCtx() {
		return this.oggettoCtx;
	}

	public void setOggettoCtx(String oggettoCtx) {
		this.oggettoCtx = oggettoCtx;
	}

	@Column(name = "CORPO_CTX")
	public String getCorpoCtx() {
		return this.corpoCtx;
	}

	public void setCorpoCtx(String corpoCtx) {
		this.corpoCtx = corpoCtx;
	}

	@Column(name = "SIGLA_REGISTRO_MITT", length = 100)
	public String getSiglaRegistroMitt() {
		return this.siglaRegistroMitt;
	}

	public void setSiglaRegistroMitt(String siglaRegistroMitt) {
		this.siglaRegistroMitt = siglaRegistroMitt;
	}

	@Column(name = "NUM_REG_MITT", precision = 7, scale = 0)
	public Integer getNumRegMitt() {
		return this.numRegMitt;
	}

	public void setNumRegMitt(Integer numRegMitt) {
		this.numRegMitt = numRegMitt;
	}

	@Column(name = "ANNO_REG_MITT", precision = 4, scale = 0)
	public Short getAnnoRegMitt() {
		return this.annoRegMitt;
	}

	public void setAnnoRegMitt(Short annoRegMitt) {
		this.annoRegMitt = annoRegMitt;
	}

	@Column(name = "TS_REG_MITT", length = 7)
	public Date getTsRegMitt() {
		return this.tsRegMitt;
	}

	public void setTsRegMitt(Date tsRegMitt) {
		this.tsRegMitt = tsRegMitt;
	}

	@Column(name = "OGGETTO_REG_MITT")
	public String getOggettoRegMitt() {
		return this.oggettoRegMitt;
	}

	public void setOggettoRegMitt(String oggettoRegMitt) {
		this.oggettoRegMitt = oggettoRegMitt;
	}

	@Column(name = "OGGETTO_REG_MITT_CTX")
	public String getOggettoRegMittCtx() {
		return this.oggettoRegMittCtx;
	}

	public void setOggettoRegMittCtx(String oggettoRegMittCtx) {
		this.oggettoRegMittCtx = oggettoRegMittCtx;
	}

	@Column(name = "STATO_LAVORAZIONE", length = 30)
	public String getStatoLavorazione() {
		return this.statoLavorazione;
	}

	public void setStatoLavorazione(String statoLavorazione) {
		this.statoLavorazione = statoLavorazione;
	}

	@Column(name = "FLG_RICH_CONF_LETTURA", nullable = false, precision = 1, scale = 0)
	public boolean isFlgRichConfLettura() {
		return this.flgRichConfLettura;
	}

	public void setFlgRichConfLettura(boolean flgRichConfLettura) {
		this.flgRichConfLettura = flgRichConfLettura;
	}

	@Column(name = "MESSAGE_ID_TRASPORTO", length = 500)
	public String getMessageIdTrasporto() {
		return this.messageIdTrasporto;
	}

	public void setMessageIdTrasporto(String messageIdTrasporto) {
		this.messageIdTrasporto = messageIdTrasporto;
	}

	@Column(name = "COD_AZIONE_DA_FARE", length = 10)
	public String getCodAzioneDaFare() {
		return this.codAzioneDaFare;
	}

	public void setCodAzioneDaFare(String codAzioneDaFare) {
		this.codAzioneDaFare = codAzioneDaFare;
	}

	@Column(name = "DETT_AZIONE_DA_FARE", length = 4000)
	public String getDettAzioneDaFare() {
		return this.dettAzioneDaFare;
	}

	public void setDettAzioneDaFare(String dettAzioneDaFare) {
		this.dettAzioneDaFare = dettAzioneDaFare;
	}

	@Column(name = "PROGR_MSG", precision = 22, scale = 0)
	public BigDecimal getProgrMsg() {
		return this.progrMsg;
	}

	public void setProgrMsg(BigDecimal progrMsg) {
		this.progrMsg = progrMsg;
	}

	@Column(name = "ANNO_PROGR_MSG", precision = 22, scale = 0)
	public BigDecimal getAnnoProgrMsg() {
		return this.annoProgrMsg;
	}

	public void setAnnoProgrMsg(BigDecimal annoProgrMsg) {
		this.annoProgrMsg = annoProgrMsg;
	}

	@Column(name = "REGISTRO_PROGR_MSG", length = 10)
	public String getRegistroProgrMsg() {
		return this.registroProgrMsg;
	}

	public void setRegistroProgrMsg(String registroProgrMsg) {
		this.registroProgrMsg = registroProgrMsg;
	}

	@Column(name = "TS_AGG_STATO_LAVORAZIONE", length = 7)
	public Date getTsAggStatoLavorazione() {
		return this.tsAggStatoLavorazione;
	}

	public void setTsAggStatoLavorazione(Date tsAggStatoLavorazione) {
		this.tsAggStatoLavorazione = tsAggStatoLavorazione;
	}

	@Column(name = "STATO_INVIO", length = 2)
	public String getStatoInvio() {
		return this.statoInvio;
	}

	public void setStatoInvio(String statoInvio) {
		this.statoInvio = statoInvio;
	}

	@Column(name = "STATO_ACCETTAZIONE", length = 2)
	public String getStatoAccettazione() {
		return this.statoAccettazione;
	}

	public void setStatoAccettazione(String statoAccettazione) {
		this.statoAccettazione = statoAccettazione;
	}

	@Column(name = "STATO_CONSEGNA", length = 2)
	public String getStatoConsegna() {
		return this.statoConsegna;
	}

	public void setStatoConsegna(String statoConsegna) {
		this.statoConsegna = statoConsegna;
	}

	@Column(name = "MOTIVO_ECCEZIONE")
	public String getMotivoEccezione() {
		return this.motivoEccezione;
	}

	public void setMotivoEccezione(String motivoEccezione) {
		this.motivoEccezione = motivoEccezione;
	}

	@Column(name = "PROGR_BOZZA", precision = 22, scale = 0)
	public BigDecimal getProgrBozza() {
		return this.progrBozza;
	}

	public void setProgrBozza(BigDecimal progrBozza) {
		this.progrBozza = progrBozza;
	}

	@Column(name = "ANNO_PROGR_BOZZA", precision = 4, scale = 0)
	public Short getAnnoProgrBozza() {
		return this.annoProgrBozza;
	}

	public void setAnnoProgrBozza(Short annoProgrBozza) {
		this.annoProgrBozza = annoProgrBozza;
	}

	@Column(name = "ID_UTENTE_AGG_STATO_LAV", length = 64)
	public String getIdUtenteAggStatoLav() {
		return this.idUtenteAggStatoLav;
	}

	public void setIdUtenteAggStatoLav(String idUtenteAggStatoLav) {
		this.idUtenteAggStatoLav = idUtenteAggStatoLav;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "TEmailMgo")
	public TEmailCompressione getTEmailCompressione() {
		return this.TEmailCompressione;
	}

	public void setTEmailCompressione(TEmailCompressione TEmailCompressione) {
		this.TEmailCompressione = TEmailCompressione;
	}

}
