/* * SPDX-License-Identifier: AGPL-3.0-or-later * * C Copyright 2023 Regione Piemonte * */

// Generated 27-mag-2015 12.25.14 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TFileLettiDaSftpId generated by hbm2java
 */
@Embeddable
public class TFileLettiDaSftpId implements java.io.Serializable {

	private static final long serialVersionUID = -7733248753989124505L;
	
	private BigDecimal idSpAoo;
	private String nomeFileOrig;
	private String impronta;


	public TFileLettiDaSftpId() {
	}

	public TFileLettiDaSftpId(BigDecimal idSpAoo, String nomeFileOrig, String impronta) {
		this.idSpAoo = idSpAoo;
		this.nomeFileOrig = nomeFileOrig;
		this.impronta = impronta;
	}

	@Column(name = "ID_SP_AOO", nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdSpAoo() {
		return this.idSpAoo;
	}

	public void setIdSpAoo(BigDecimal idSpAoo) {
		this.idSpAoo = idSpAoo;
	}

	@Column(name = "NOME_FILE_ORIG", nullable = false, length = 500)
	public String getNomeFileOrig() {
		return this.nomeFileOrig;
	}

	public void setNomeFileOrig(String nomeFileOrig) {
		this.nomeFileOrig = nomeFileOrig;
	}

	@Column(name = "IMPRONTA", length = 255)
	public String getImpronta() {
		return this.impronta;
	}

	public void setImpronta(String impronta) {
		this.impronta = impronta;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TFileLettiDaSftpId))
			return false;
		TFileLettiDaSftpId castOther = (TFileLettiDaSftpId) other;

		return ((this.getIdSpAoo() == castOther.getIdSpAoo()) || (this.getIdSpAoo() != null && castOther.getIdSpAoo() != null && this
				.getIdSpAoo().equals(castOther.getIdSpAoo())))
				&& ((this.getNomeFileOrig() == castOther.getNomeFileOrig()) || (this.getNomeFileOrig() != null
						&& castOther.getNomeFileOrig() != null && this.getNomeFileOrig().equals(castOther.getNomeFileOrig())))
				&& ((this.getImpronta() == castOther.getImpronta()) || (this.getImpronta() != null && castOther.getImpronta() != null && this
						.getImpronta().equals(castOther.getImpronta())))
						;
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getIdSpAoo() == null ? 0 : this.getIdSpAoo().hashCode());
		result = 37 * result + (getNomeFileOrig() == null ? 0 : this.getNomeFileOrig().hashCode());
		result = 37 * result + (getImpronta() == null ? 0 : this.getImpronta().hashCode());
		return result;
	}

	@Override
	public String toString() {
		return String.format("TFileLettiDaSftpId [idSpAoo=%s, nomeFileOrig=%s, impronta=%s]", idSpAoo, nomeFileOrig, impronta);
	}

}
