/* * SPDX-License-Identifier: AGPL-3.0-or-later * * C Copyright 2023 Regione Piemonte * */

// Generated 21-feb-2014 15.59.26 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TNotificheSdi generated by hbm2java
 */
@Entity
@Table(name = "T_NOTIFICHE_SDI")
@org.hibernate.annotations.Entity(dynamicUpdate = true, dynamicInsert = true)
public class TNotificheSdI implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8521228592097825146L;
	private BigDecimal idMsgNotifica;
	private String tipoNotifica;
	private String nomeFileNotifica;
	private String messaggio;
	private BigDecimal idMsgTrasmesso;
	private String nomeFileTrasmesso;
	private BigDecimal idFileFattura;
	private String nomeFileFattura;
	private String nroFattura;
	private Short annoFattura;
	private BigDecimal posFattura;
	private Date tsIns;
	private Date tsUltimoAgg;	
	private BigDecimal idDoc;
	private boolean flgCarVerAuriga;
	private Date tsCarAuriga;
	private Date tsErrCarAuriga;
	private String errMsgCarAuriga;
	private boolean flgRecuperataDaFs;
	private Date tsRicDaSdi;
	
	public TNotificheSdI() {
	}

	public TNotificheSdI(BigDecimal idMsgNotifica, String tipoNotifica, String nomeFileNotifica, String messaggio, Date tsIns, Date tsUltimoAgg, 
			             BigDecimal idDoc, boolean flgCarVerAuriga, Date tsCarAuriga, Date tsErrCarAuriga, String errMsgCarAuriga, boolean flgRecuperataDaFs) {
		this.idMsgNotifica = idMsgNotifica;
		this.tipoNotifica = tipoNotifica;
		this.nomeFileNotifica = nomeFileNotifica;
		this.messaggio = messaggio;
		this.tsIns = tsIns;
		this.tsUltimoAgg = tsUltimoAgg;		
		this.idDoc = idDoc;
		this.flgCarVerAuriga = flgCarVerAuriga;		
		this.tsCarAuriga = tsCarAuriga;
		this.tsErrCarAuriga = tsErrCarAuriga;
		this.errMsgCarAuriga = errMsgCarAuriga;
		this.flgRecuperataDaFs = flgRecuperataDaFs;
	}

	public TNotificheSdI(BigDecimal idMsgNotifica, String tipoNotifica, String nomeFileNotifica, String messaggio, BigDecimal idMsgTrasmesso, String nomeFileTrasmesso, 
			             BigDecimal idFileFattura, String nomeFileFattura, String nroFattura, Short annoFattura, BigDecimal posFattura, Date tsIns, Date tsUltimoAgg, 
			             BigDecimal idDoc, boolean flgCarVerAuriga, Date tsCarAuriga, Date tsErrCarAuriga, String errMsgCarAuriga, boolean flgRecuperataDaFs, Date tsRicDaSdi) {
		this.idMsgNotifica = idMsgNotifica;
		this.tipoNotifica = tipoNotifica;
		this.nomeFileNotifica = nomeFileNotifica;
		this.messaggio = messaggio;
		this.idMsgTrasmesso = idMsgTrasmesso;
		this.nomeFileTrasmesso = nomeFileTrasmesso;
		this.idFileFattura = idFileFattura;
		this.nomeFileFattura = nomeFileFattura;
		this.nroFattura = nroFattura;
		this.annoFattura = annoFattura;
		this.posFattura = posFattura;
		this.tsIns = tsIns;
		this.tsUltimoAgg = tsUltimoAgg;
		this.idDoc = idDoc;
		this.flgCarVerAuriga = flgCarVerAuriga;		
		this.tsCarAuriga = tsCarAuriga;
		this.tsErrCarAuriga = tsErrCarAuriga;
		this.errMsgCarAuriga = errMsgCarAuriga;
		this.flgRecuperataDaFs = flgRecuperataDaFs;
		this.tsRicDaSdi = tsRicDaSdi;
	}

	@Id
	@Column(name = "ID_MSG_NOTIFICA", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdMsgNotifica() {
		return this.idMsgNotifica;
	}

	public void setIdMsgNotifica(BigDecimal idMsgNotifica) {
		this.idMsgNotifica = idMsgNotifica;
	}

	@Column(name = "TIPO_NOTIFICA", nullable = false, length = 30)
	public String getTipoNotifica() {
		return this.tipoNotifica;
	}

	public void setTipoNotifica(String tipoNotifica) {
		this.tipoNotifica = tipoNotifica;
	}

	@Column(name = "NOME_FILE_NOTIFICA", nullable = false, length = 50)
	public String getNomeFileNotifica() {
		return this.nomeFileNotifica;
	}

	public void setNomeFileNotifica(String nomeFileNotifica) {
		this.nomeFileNotifica = nomeFileNotifica;
	}

	@Column(name = "MESSAGGIO", nullable = false)
	public String getMessaggio() {
		return this.messaggio;
	}

	public void setMessaggio(String messaggio) {
		this.messaggio = messaggio;
	}

	@Column(name = "ID_MSG_TRASMESSO", precision = 22, scale = 0)
	public BigDecimal getIdMsgTrasmesso() {
		return this.idMsgTrasmesso;
	}

	public void setIdMsgTrasmesso(BigDecimal idMsgTrasmesso) {
		this.idMsgTrasmesso = idMsgTrasmesso;
	}

	@Column(name = "NOME_FILE_TRASMESSO", length = 50)
	public String getNomeFileTrasmesso() {
		return this.nomeFileTrasmesso;
	}

	public void setNomeFileTrasmesso(String nomeFileTrasmesso) {
		this.nomeFileTrasmesso = nomeFileTrasmesso;
	}

	@Column(name = "ID_FILE_FATTURA", precision = 22, scale = 0)
	public BigDecimal getIdFileFattura() {
		return this.idFileFattura;
	}

	public void setIdFileFattura(BigDecimal idFileFattura) {
		this.idFileFattura = idFileFattura;
	}

	@Column(name = "NOME_FILE_FATTURA", length = 50)
	public String getNomeFileFattura() {
		return this.nomeFileFattura;
	}

	public void setNomeFileFattura(String nomeFileFattura) {
		this.nomeFileFattura = nomeFileFattura;
	}

	@Column(name = "NRO_FATTURA", length = 20)
	public String getNroFattura() {
		return this.nroFattura;
	}

	public void setNroFattura(String nroFattura) {
		this.nroFattura = nroFattura;
	}

	@Column(name = "ANNO_FATTURA", precision = 4, scale = 0)
	public Short getAnnoFattura() {
		return this.annoFattura;
	}

	public void setAnnoFattura(Short annoFattura) {
		this.annoFattura = annoFattura;
	}

	@Column(name = "POS_FATTURA", precision = 22, scale = 0)
	public BigDecimal getPosFattura() {
		return this.posFattura;
	}

	public void setPosFattura(BigDecimal posFattura) {
		this.posFattura = posFattura;
	}

	@Column(name = "TS_INS", nullable = false)
	public Date getTsIns() {
		return this.tsIns;
	}

	public void setTsIns(Date tsIns) {
		this.tsIns = tsIns;
	}

	@Column(name = "TS_ULTIMO_AGG", nullable = false)
	public Date getTsUltimoAgg() {
		return this.tsUltimoAgg;
	}

	public void setTsUltimoAgg(Date tsUltimoAgg) {
		this.tsUltimoAgg = tsUltimoAgg;
	}
	
	@Column(name = "ID_DOC", precision = 22, scale = 0)
	public BigDecimal getIdDoc() {
		return this.idDoc;
	}

	public void setIdDoc(BigDecimal idDoc) {
		this.idDoc = idDoc;
	}
	
	@Column(name = "FLG_CAR_VER_AURIGA", nullable = false, precision = 1, scale = 0)
	public boolean isFlgCarVerAuriga() {
		return this.flgCarVerAuriga;
	}

	public void setFlgCarVerAuriga(boolean flgCarVerAuriga) {
		this.flgCarVerAuriga = flgCarVerAuriga;
	}
	
	@Column(name = "TS_CAR_AURIGA")
	public Date getTsCarAuriga() {
		return this.tsCarAuriga;
	}

	public void setTsCarAuriga(Date tsCarAuriga) {
		this.tsCarAuriga = tsCarAuriga;
	}
	
	@Column(name = "TS_ERR_CAR_AURIGA")
	public Date getTsErrCarAuriga() {
		return this.tsErrCarAuriga;
	}

	public void setTsErrCarAuriga(Date tsErrCarAuriga) {
		this.tsErrCarAuriga = tsErrCarAuriga;
	}
	
	@Column(name = "ERR_MSG_CAR_AURIGA")
	public String getErrMsgCarAuriga() {
		return this.errMsgCarAuriga;
	}

	public void setErrMsgCarAuriga(String errMsgCarAuriga) {
		this.errMsgCarAuriga = errMsgCarAuriga;
	}
	
	@Column(name = "FLG_RECUPERATA_DA_FS", nullable = false, precision = 1, scale = 0)
	public boolean isFlgRecuperataDaFs() {
		return this.flgRecuperataDaFs;
	}

	public void setFlgRecuperataDaFs(boolean flgRecuperataDaFs) {
		this.flgRecuperataDaFs = flgRecuperataDaFs;
	}

	@Column(name = "TS_RIC_DA_SDI", length = 7)
	public Date getTsRicDaSdi() {
		return this.tsRicDaSdi;
	}

	public void setTsRicDaSdi(Date tsRicDaSdi) {
		this.tsRicDaSdi = tsRicDaSdi;
	}

	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("TNotificheSdi [idMsgNotifica=");
		builder.append(idMsgNotifica);
		builder.append(", tipoNotifica=");
		builder.append(tipoNotifica);
		builder.append(", nomeFileNotifica=");
		builder.append(nomeFileNotifica);
		builder.append(", messaggio=");
		builder.append(messaggio);
		builder.append(", idMsgTrasmesso=");
		builder.append(idMsgTrasmesso);
		builder.append(", nomeFileTrasmesso=");
		builder.append(nomeFileTrasmesso);
		builder.append(", idFileFattura=");
		builder.append(idFileFattura);
		builder.append(", nomeFileFattura=");
		builder.append(nomeFileFattura);
		builder.append(", nroFattura=");
		builder.append(nroFattura);
		builder.append(", annoFattura=");
		builder.append(annoFattura);
		builder.append(", posFattura=");
		builder.append(posFattura);
		builder.append(", tsIns=");
		builder.append(tsIns);
		builder.append(", tsUltimoAgg=");
		builder.append(tsUltimoAgg);		
		builder.append(", idDoc=");
		builder.append(idDoc);
		builder.append(", flgCarVerAuriga=");
		builder.append(flgCarVerAuriga);		
		builder.append(", tsCarAuriga=");
		builder.append(tsCarAuriga);
		builder.append(", tsErrCarAuriga=");
		builder.append(tsErrCarAuriga);
		builder.append(", errMsgCarAuriga=");
		builder.append(errMsgCarAuriga);
		builder.append("]");
		return builder.toString();
	}

}
