/* * SPDX-License-Identifier: AGPL-3.0-or-later * * C Copyright 2023 Regione Piemonte * */

// Generated 19-giu-2014 16.01.15 by Hibernate Tools 3.4.0.CR1

import it.eng.auriga.module.business.dao.beans.UdDaInviareConservBean;

import java.math.BigDecimal;
import java.sql.Clob;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TUdDaInviareConserv generated by hbm2java
 */
@Entity
@Table(name = "T_UD_DA_INVIARE_CONSERV")
@org.hibernate.annotations.Entity(dynamicUpdate = true, dynamicInsert = true)
public class TUdDaInviareConserv implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4815120000545058325L;
	private BigDecimal idUd;
	private String useridAppl;
	private String idSoggVers;
	private Date tsLastTry;
	private BigDecimal tryNum;
	private String msgErrInvio;
	private Date tsInvioConserv;
	private String idSip;
	private Date tsIns;
	private Date tsUltimoAgg;
	private String esitoInvioCs;
	private Date tsRecEsitoCs;
	private Clob xmlRdv;
	//private String fetchSize;
	private BigDecimal ordine;

	public TUdDaInviareConserv() {
	}

	public TUdDaInviareConserv(BigDecimal idUd, String useridAppl,
			String idSoggVers, BigDecimal tryNum, Date tsIns, Date tsUltimoAgg) {
		this.idUd = idUd;
		this.useridAppl = useridAppl;
		this.idSoggVers = idSoggVers;
		this.tryNum = tryNum;
		this.tsIns = tsIns;
		this.tsUltimoAgg = tsUltimoAgg;
	}

	public TUdDaInviareConserv(BigDecimal idUd, String useridAppl,
			String idSoggVers, Date tsLastTry, BigDecimal tryNum,
			String msgErrInvio, Date tsInvioConserv, String idSip, Date tsIns,
			Date tsUltimoAgg) {
		this.idUd = idUd;
		this.useridAppl = useridAppl;
		this.idSoggVers = idSoggVers;
		this.tsLastTry = tsLastTry;
		this.tryNum = tryNum;
		this.msgErrInvio = msgErrInvio;
		this.tsInvioConserv = tsInvioConserv;
		this.idSip = idSip;
		this.tsIns = tsIns;
		this.tsUltimoAgg = tsUltimoAgg;
	}

	@Id
	@Column(name = "ID_UD", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdUd() {
		return this.idUd;
	}

	public void setIdUd(BigDecimal idUd) {
		this.idUd = idUd;
	}

	@Column(name = "USERID_APPL", nullable = false, length = 30)
	public String getUseridAppl() {
		return this.useridAppl;
	}

	public void setUseridAppl(String useridAppl) {
		this.useridAppl = useridAppl;
	}

	@Column(name = "ID_SOGG_VERS", nullable = false, length = 64)
	public String getIdSoggVers() {
		return this.idSoggVers;
	}

	public void setIdSoggVers(String idSoggVers) {
		this.idSoggVers = idSoggVers;
	}

	@Column(name = "TS_LAST_TRY", length = 7)
	public Date getTsLastTry() {
		return this.tsLastTry;
	}

	public void setTsLastTry(Date tsLastTry) {
		this.tsLastTry = tsLastTry;
	}

	@Column(name = "TRY_NUM", nullable = false, precision = 22, scale = 0)
	public BigDecimal getTryNum() {
		return this.tryNum;
	}

	public void setTryNum(BigDecimal tryNum) {
		this.tryNum = tryNum;
	}

	@Column(name = "MSG_ERR_INVIO", length = 4000)
	public String getMsgErrInvio() {
		return this.msgErrInvio;
	}

	public void setMsgErrInvio(String msgErrInvio) {
		this.msgErrInvio = msgErrInvio;
	}

	@Column(name = "TS_INVIO_CONSERV")
	public Date getTsInvioConserv() {
		return this.tsInvioConserv;
	}

	public void setTsInvioConserv(Date tsInvioConserv) {
		this.tsInvioConserv = tsInvioConserv;
	}

	@Column(name = "ID_SIP", length = 64)
	public String getIdSip() {
		return this.idSip;
	}

	public void setIdSip(String idSip) {
		this.idSip = idSip;
	}

	@Column(name = "TS_INS", nullable = false)
	public Date getTsIns() {
		return this.tsIns;
	}

	public void setTsIns(Date tsIns) {
		this.tsIns = tsIns;
	}

	@Column(name = "TS_ULTIMO_AGG", nullable = false)
	public Date getTsUltimoAgg() {
		return this.tsUltimoAgg;
	}

	public void setTsUltimoAgg(Date tsUltimoAgg) {
		this.tsUltimoAgg = tsUltimoAgg;
	}
	
	@Column(name = "ESITO_INVIO_CS", length = 2)
	public String getEsitoInvioCs() {
		return this.esitoInvioCs;
	}

	public void setEsitoInvioCs(String esitoInvioCs) {
		this.esitoInvioCs = esitoInvioCs;
	}

	@Column(name = "TS_REC_ESITO_CS", length = 7)
	public Date getTsRecEsitoCs() {
		return this.tsRecEsitoCs;
	}

	public void setTsRecEsitoCs(Date tsRecEsitoCs) {
		this.tsRecEsitoCs = tsRecEsitoCs;
	}
	
	@Column(name = "XML_RDV")
	public Clob getXmlRdv() {
		return this.xmlRdv;
	}

	public void setXmlRdv(Clob xmlRdv) {
		this.xmlRdv = xmlRdv;
	}
	
	@Column(name = "ORDINE", nullable = false, precision = 22, scale = 0)
	public BigDecimal getOrdine() {
		return this.ordine;
	}

	public void setOrdine(BigDecimal ordine) {
		this.ordine = ordine;
	}
	
//	public String getFetchSize() {
//		return fetchSize;
//	}
//	public void setFetchSize(String fetchSize) {
//		this.fetchSize = fetchSize;
//	}	

	public UdDaInviareConservBean populateBean(){
		UdDaInviareConservBean bean = new UdDaInviareConservBean();
		bean.setIdUd( this.idUd );
		bean.setIdSoggVers( this.idSoggVers );
		bean.setIdSip( this.idSip );
		bean.setTsIns( this.tsIns);
		bean.setTryNum( this.tryNum );
		bean.setTsInvioConserv( this.tsInvioConserv);
		bean.setTsUltimoAgg( this.tsUltimoAgg );
		bean.setTsLastTry( this.tsLastTry);
		bean.setMsgErrInvio( this.msgErrInvio);
		bean.setUseridAppl( this.useridAppl );
		return bean;
	}
}
