/* * SPDX-License-Identifier: AGPL-3.0-or-later * * C Copyright 2023 Regione Piemonte * */

// Generated 20-apr-2015 11.37.14 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * VEmailToResend generated by hbm2java
 */
@Entity
@Table(name = "V_EMAIL_TO_RESEND")
public class VEmailToResend implements java.io.Serializable {

	private static final long serialVersionUID = -5595423508316667587L;

	private String idEmail;
	
	private String idCasella;

	private String idUteIns;

	private Date tsIns;

	private Integer nroTentativi;

	private Date tsUltimoTentativo;

	private String ultimoErroreInvio;

	private TReinvioEmailMgo TReinvioEmailMgo;

	
	public VEmailToResend() {
	}

	public VEmailToResend(String idEmail, String idCasella) {
		this.idEmail = idEmail;
		this.idCasella = idCasella;
	}

	public VEmailToResend(String idEmail, String idCasella, 
			String idUteIns, Date tsIns, 
			Integer nroTentativi, Date tsUltimoTentativo, String ultimoErroreInvio,
			TReinvioEmailMgo TReinvioEmailMgo) {
		this.idEmail = idEmail;
		this.idCasella = idCasella;
		this.idUteIns = idUteIns;
		this.tsIns = tsIns;
		this.nroTentativi = nroTentativi;
		this.tsUltimoTentativo = tsUltimoTentativo;
		this.ultimoErroreInvio = ultimoErroreInvio;
		this.TReinvioEmailMgo = TReinvioEmailMgo;
	}

	@Id
	@Column(name = "ID_EMAIL", nullable = false, length = 64)
	public String getIdEmail() {
		return this.idEmail;
	}

	public void setIdEmail(String idEmail) {
		this.idEmail = idEmail;
	}

	@Column(name = "ID_CASELLA", nullable = false, length = 64)
	public String getIdCasella() {
		return this.idCasella;
	}

	public void setIdCasella(String idCasella) {
		this.idCasella = idCasella;
	}

	@Column(name = "ID_UTE_INS", length = 64)
	public String getIdUteIns() {
		return this.idUteIns;
	}

	public void setIdUteIns(String idUteIns) {
		this.idUteIns = idUteIns;
	}

	@Column(name = "TS_INS")
	public Date getTsIns() {
		return this.tsIns;
	}

	public void setTsIns(Date tsIns) {
		this.tsIns = tsIns;
	}

	@Column(name = "NRO_TENTATIVI", nullable = false, precision = 2, scale = 0)
	public Integer getNroTentativi() {
		return this.nroTentativi;
	}

	public void setNroTentativi(Integer nroTentativi) {
		this.nroTentativi = nroTentativi;
	}

	@Column(name = "TS_ULTIMO_TENTATIVO")
	public Date getTsUltimoTentativo() {
		return this.tsUltimoTentativo;
	}

	public void setTsUltimoTentativo(Date tsUltimoTentativo) {
		this.tsUltimoTentativo = tsUltimoTentativo;
	}

	@Column(name = "ULTIMO_ERRORE_INVIO", length = 4000)
	public String getUltimoErroreInvio() {
		return this.ultimoErroreInvio;
	}

	public void setUltimoErroreInvio(String ultimoErroreInvio) {
		this.ultimoErroreInvio = ultimoErroreInvio;
	}

	@OneToOne(fetch = FetchType.EAGER, mappedBy = "VEmailToResend")
	public TReinvioEmailMgo getTReinvioEmailMgo() {
		return this.TReinvioEmailMgo;
	}

	public void setTReinvioEmailMgo(TReinvioEmailMgo TReinvioEmailMgo) {
		this.TReinvioEmailMgo = TReinvioEmailMgo;
	}

	
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VEmailToResend))
			return false;
		VEmailToResend castOther = (VEmailToResend) other;

		return ((this.getIdEmail() == castOther.getIdEmail()) || (this.getIdEmail() != null && castOther.getIdEmail() != null && this
				.getIdEmail().equals(castOther.getIdEmail())))
				&& ((this.getIdCasella() == castOther.getIdCasella()) || (this.getIdCasella() != null && castOther.getIdCasella() != null && this
					.getIdCasella().equals(castOther.getIdCasella())))
				&& ((this.getIdUteIns() == castOther.getIdUteIns()) || (this.getIdUteIns() != null && castOther.getIdUteIns() != null && this
					.getIdUteIns().equals(castOther.getIdUteIns())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getIdEmail() == null ? 0 : this.getIdEmail().hashCode());
		result = 37 * result + (getIdCasella() == null ? 0 : this.getIdCasella().hashCode());
		result = 37 * result + (getIdUteIns() == null ? 0 : this.getIdUteIns().hashCode());
		return result;
	}

	@Override
	public String toString() {
		return String
				.format("VEmailToResend [idEmail=%s, idCasella=%s, idUteIns=%s, tsIns=%s, nroTentativi=%s, tsUltimoTentativo=%s, ultimoErroreInvio=%s, TReinvioEmailMgo=%s]",
						idEmail, idCasella, idUteIns, tsIns, nroTentativi, tsUltimoTentativo, ultimoErroreInvio, TReinvioEmailMgo);
	}

}
