/* * SPDX-License-Identifier: AGPL-3.0-or-later * * C Copyright 2023 Regione Piemonte * */
// Generated 15-giu-2018 12.03.29 by Hibernate Tools 3.6.0.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * DmtErroriDocLottiElabMass generated by hbm2java
 */
@Entity
@Table(name = "DMT_ERRORI_DOC_LOTTI_ELAB_MASS")
public class DmtErroriDocLottiElabMass implements java.io.Serializable {

	private DmtErroriDocLottiElabMassId id;
	private DmtDocLottiElabMassive dmtDocLottiElabMassive;
	private String errContext;
	private String errCode;
	private String errMsg;

	public DmtErroriDocLottiElabMass() {
	}

	public DmtErroriDocLottiElabMass(DmtErroriDocLottiElabMassId id, DmtDocLottiElabMassive dmtDocLottiElabMassive, String errMsg) {
		this.id = id;
		this.dmtDocLottiElabMassive = dmtDocLottiElabMassive;
		this.errMsg = errMsg;
	}

	public DmtErroriDocLottiElabMass(DmtErroriDocLottiElabMassId id, DmtDocLottiElabMassive dmtDocLottiElabMassive, String errContext, String errCode,
			String errMsg) {
		this.id = id;
		this.dmtDocLottiElabMassive = dmtDocLottiElabMassive;
		this.errContext = errContext;
		this.errCode = errCode;
		this.errMsg = errMsg;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "idJob", column = @Column(name = "ID_JOB", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "nroPosizDoc", column = @Column(name = "NRO_POSIZ_DOC", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "tipoOperazione", column = @Column(name = "TIPO_OPERAZIONE", nullable = false, length = 100)),
			@AttributeOverride(name = "progrErrore", column = @Column(name = "PROGR_ERRORE", nullable = false, precision = 22, scale = 0)) })
	public DmtErroriDocLottiElabMassId getId() {
		return this.id;
	}

	public void setId(DmtErroriDocLottiElabMassId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({ @JoinColumn(name = "ID_JOB", referencedColumnName = "ID_JOB", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "NRO_POSIZ_DOC", referencedColumnName = "NRO_POSIZ_DOC", nullable = false, insertable = false, updatable = false) })
	public DmtDocLottiElabMassive getDmtDocLottiElabMassive() {
		return this.dmtDocLottiElabMassive;
	}

	public void setDmtDocLottiElabMassive(DmtDocLottiElabMassive dmtDocLottiElabMassive) {
		this.dmtDocLottiElabMassive = dmtDocLottiElabMassive;
	}

	@Column(name = "ERR_CONTEXT", length = 250)
	public String getErrContext() {
		return this.errContext;
	}

	public void setErrContext(String errContext) {
		this.errContext = errContext;
	}

	@Column(name = "ERR_CODE", length = 30)
	public String getErrCode() {
		return this.errCode;
	}

	public void setErrCode(String errCode) {
		this.errCode = errCode;
	}

	@Column(name = "ERR_MSG", nullable = false)
	public String getErrMsg() {
		return this.errMsg;
	}

	public void setErrMsg(String errMsg) {
		this.errMsg = errMsg;
	}

}
