/* * SPDX-License-Identifier: AGPL-3.0-or-later * * C Copyright 2023 Regione Piemonte * */
// Generated 15-giu-2018 12.03.29 by Hibernate Tools 3.6.0.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * DmtOperDocLottiElabMass generated by hbm2java
 */
@Entity
@Table(name = "DMT_OPER_DOC_LOTTI_ELAB_MASS")
public class DmtOperDocLottiElabMass implements java.io.Serializable {

	private DmtOperDocLottiElabMassId id;
	private DmtDocLottiElabMassive dmtDocLottiElabMassive;
	private String stato;
	private Date tsOperazione;
	private String operationInfo;
	private BigDecimal nroTentativi;

	public DmtOperDocLottiElabMass() {
	}

	public DmtOperDocLottiElabMass(DmtOperDocLottiElabMassId id, DmtDocLottiElabMassive dmtDocLottiElabMassive, String stato, Date tsOperazione,
			BigDecimal nroTentativi) {
		this.id = id;
		this.dmtDocLottiElabMassive = dmtDocLottiElabMassive;
		this.stato = stato;
		this.tsOperazione = tsOperazione;
		this.nroTentativi = nroTentativi;
	}

	public DmtOperDocLottiElabMass(DmtOperDocLottiElabMassId id, DmtDocLottiElabMassive dmtDocLottiElabMassive, String stato, Date tsOperazione,
			String operationInfo, BigDecimal nroTentativi) {
		this.id = id;
		this.dmtDocLottiElabMassive = dmtDocLottiElabMassive;
		this.stato = stato;
		this.tsOperazione = tsOperazione;
		this.operationInfo = operationInfo;
		this.nroTentativi = nroTentativi;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "idJob", column = @Column(name = "ID_JOB", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "nroPosizDoc", column = @Column(name = "NRO_POSIZ_DOC", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "tipoOperazione", column = @Column(name = "TIPO_OPERAZIONE", nullable = false, length = 100)) })
	public DmtOperDocLottiElabMassId getId() {
		return this.id;
	}

	public void setId(DmtOperDocLottiElabMassId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({ @JoinColumn(name = "ID_JOB", referencedColumnName = "ID_JOB", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "NRO_POSIZ_DOC", referencedColumnName = "NRO_POSIZ_DOC", nullable = false, insertable = false, updatable = false) })
	public DmtDocLottiElabMassive getDmtDocLottiElabMassive() {
		return this.dmtDocLottiElabMassive;
	}

	public void setDmtDocLottiElabMassive(DmtDocLottiElabMassive dmtDocLottiElabMassive) {
		this.dmtDocLottiElabMassive = dmtDocLottiElabMassive;
	}

	@Column(name = "STATO", nullable = false, length = 50)
	public String getStato() {
		return this.stato;
	}

	public void setStato(String stato) {
		this.stato = stato;
	}

	@Column(name = "TS_OPERAZIONE", nullable = false)
	public Date getTsOperazione() {
		return this.tsOperazione;
	}

	public void setTsOperazione(Date tsOperazione) {
		this.tsOperazione = tsOperazione;
	}

	@Column(name = "OPERATION_INFO")
	public String getOperationInfo() {
		return this.operationInfo;
	}

	public void setOperationInfo(String operationInfo) {
		this.operationInfo = operationInfo;
	}

	@Column(name = "NRO_TENTATIVI", nullable = false, precision = 22, scale = 0)
	public BigDecimal getNroTentativi() {
		return this.nroTentativi;
	}

	public void setNroTentativi(BigDecimal nroTentativi) {
		this.nroTentativi = nroTentativi;
	}

}
