/* * SPDX-License-Identifier: AGPL-3.0-or-later * * C Copyright 2023 Regione Piemonte * */
// Generated 20-giu-2018 9.32.53 by Hibernate Tools 3.6.0.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

import org.hibernate.annotations.Immutable;

/**
 * DmvConsumerWs generated by hbm2java
 */
@Entity
@Immutable
@Table(name = "DMV_CONSUMER_WS")
public class DmvConsumerWs implements java.io.Serializable {

	private DmvConsumerWsId id;

	public DmvConsumerWs() {
	}

	public DmvConsumerWs(DmvConsumerWsId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "idSpAoo", column = @Column(name = "ID_SP_AOO", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "userid", column = @Column(name = "USERID", length = 4000)),
			@AttributeOverride(name = "password", column = @Column(name = "PASSWORD", length = 4000)),
			@AttributeOverride(name = "descrizione", column = @Column(name = "DESCRIZIONE", length = 1000)),
			@AttributeOverride(name = "ciApplicazione", column = @Column(name = "CI_APPLICAZIONE", nullable = false, length = 30)),
			@AttributeOverride(name = "ciIstanzaApplicazione", column = @Column(name = "CI_ISTANZA_APPLICAZIONE", length = 30)),
			@AttributeOverride(name = "cifratura", column = @Column(name = "CIFRATURA", length = 4000)),
			@AttributeOverride(name = "chiaveCifratura", column = @Column(name = "CHIAVE_CIFRATURA", length = 4000)),
			@AttributeOverride(name = "connToken", column = @Column(name = "CONN_TOKEN", length = 4000)),
			@AttributeOverride(name = "idUser", column = @Column(name = "ID_USER", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "idUtenteMail", column = @Column(name = "ID_UTENTE_MAIL", length = 64)) })
	public DmvConsumerWsId getId() {
		return this.id;
	}

	public void setId(DmvConsumerWsId id) {
		this.id = id;
	}

}
