/* * SPDX-License-Identifier: AGPL-3.0-or-later * * C Copyright 2023 Regione Piemonte * */

// Generated 27-Aug-2015 17:48:42 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TAvvioIterAttributes generated by hbm2java
 */
@Entity
@Table(name = "T_AVVIO_ITER_ATTRIBUTES")
public class TAvvioIterAttributes implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
		
	private BigDecimal idProcess;
	private String attributeName;
	private String attributeValue;
	private Boolean flgAnn;
	private Date tsUltimoAgg;
	private BigDecimal idUteIns;
	private Date tsIns;
	private BigDecimal idUteUltimoAgg;

	public TAvvioIterAttributes() {
	}

	public TAvvioIterAttributes(BigDecimal idProcess, String attributeName,
			String attributeValue) {
		this.idProcess = idProcess;
		this.attributeName = attributeName;
		this.attributeValue = attributeValue;
	}

	public TAvvioIterAttributes(BigDecimal idProcess, String attributeName,
			String attributeValue, Boolean flgAnn, Date tsUltimoAgg,
			BigDecimal idUteIns, Date tsIns, BigDecimal idUteUltimoAgg) {
		this.idProcess = idProcess;
		this.attributeName = attributeName;
		this.attributeValue = attributeValue;
		this.flgAnn = flgAnn;
		this.tsUltimoAgg = tsUltimoAgg;
		this.idUteIns = idUteIns;
		this.tsIns = tsIns;
		this.idUteUltimoAgg = idUteUltimoAgg;
	}

	@Id
	@Column(name = "ID_PROCESS", unique = true, nullable = false, precision = 22, scale = 0)
	//@GeneratedValue(strategy=GenerationType.AUTO)
	public BigDecimal getIdProcess() {
		return this.idProcess;
	}

	public void setIdProcess(BigDecimal idProcess) {
		this.idProcess = idProcess;
	}

	@Column(name = "ATTRIBUTE_NAME", nullable = false, length = 256)
	public String getAttributeName() {
		return this.attributeName;
	}

	public void setAttributeName(String attributeName) {
		this.attributeName = attributeName;
	}

	@Column(name = "ATTRIBUTE_VALUE", nullable = false, length = 256)
	public String getAttributeValue() {
		return this.attributeValue;
	}

	public void setAttributeValue(String attributeValue) {
		this.attributeValue = attributeValue;
	}

	@Column(name = "FLG_ANN", precision = 1, scale = 0)
	public Boolean getFlgAnn() {
		return this.flgAnn;
	}

	public void setFlgAnn(Boolean flgAnn) {
		this.flgAnn = flgAnn;
	}

	@Column(name = "TS_ULTIMO_AGG", length = 7)
	public Date getTsUltimoAgg() {
		return this.tsUltimoAgg;
	}

	public void setTsUltimoAgg(Date tsUltimoAgg) {
		this.tsUltimoAgg = tsUltimoAgg;
	}

	@Column(name = "ID_UTE_INS", precision = 22, scale = 0)
	public BigDecimal getIdUteIns() {
		return this.idUteIns;
	}

	public void setIdUteIns(BigDecimal idUteIns) {
		this.idUteIns = idUteIns;
	}

	@Column(name = "TS_INS", length = 7)
	public Date getTsIns() {
		return this.tsIns;
	}

	public void setTsIns(Date tsIns) {
		this.tsIns = tsIns;
	}

	@Column(name = "ID_UTE_ULTIMO_AGG", precision = 22, scale = 0)
	public BigDecimal getIdUteUltimoAgg() {
		return this.idUteUltimoAgg;
	}

	public void setIdUteUltimoAgg(BigDecimal idUteUltimoAgg) {
		this.idUteUltimoAgg = idUteUltimoAgg;
	}

}
