/* * SPDX-License-Identifier: AGPL-3.0-or-later * * C Copyright 2023 Regione Piemonte * */
// Generated 29-feb-2016 12.30.48 by Hibernate Tools 3.4.0.CR1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * TDocsRichEmailToSend generated by hbm2java
 */
@Entity
@Table(name="T_DOCS_RICH_EMAIL_TO_SEND"
    , uniqueConstraints = @UniqueConstraint(columnNames={"ID_RICHIESTA", "ID_DOC", "TITLE", "DT_DOC"}) 
)
public class TDocsRichEmailToSend  implements java.io.Serializable {


     private String idDocRichEmailToSend;
     private TRichEmailToSend TRichEmailToSend;
     private String idDoc;
     private String title;
     private Date dtDoc;
     private Date tsIns;
     private Date tsUltimoAgg;

    public TDocsRichEmailToSend() {
    }

	
    public TDocsRichEmailToSend(String idDocRichEmailToSend, TRichEmailToSend TRichEmailToSend, Date tsIns, Date tsUltimoAgg) {
        this.idDocRichEmailToSend = idDocRichEmailToSend;
        this.TRichEmailToSend = TRichEmailToSend;
        this.tsIns = tsIns;
        this.tsUltimoAgg = tsUltimoAgg;
    }
    public TDocsRichEmailToSend(String idDocRichEmailToSend, TRichEmailToSend TRichEmailToSend, String idDoc, String title, Date dtDoc, Date tsIns, Date tsUltimoAgg) {
       this.idDocRichEmailToSend = idDocRichEmailToSend;
       this.TRichEmailToSend = TRichEmailToSend;
       this.idDoc = idDoc;
       this.title = title;
       this.dtDoc = dtDoc;
       this.tsIns = tsIns;
       this.tsUltimoAgg = tsUltimoAgg;
    }
   
     @Id 

    
    @Column(name="ID_DOC_RICH_EMAIL_TO_SEND", unique=true, nullable=false, length=64)
    public String getIdDocRichEmailToSend() {
        return this.idDocRichEmailToSend;
    }
    
    public void setIdDocRichEmailToSend(String idDocRichEmailToSend) {
        this.idDocRichEmailToSend = idDocRichEmailToSend;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_RICHIESTA", nullable=false)
    public TRichEmailToSend getTRichEmailToSend() {
        return this.TRichEmailToSend;
    }
    
    public void setTRichEmailToSend(TRichEmailToSend TRichEmailToSend) {
        this.TRichEmailToSend = TRichEmailToSend;
    }

    
    @Column(name="ID_DOC", length=250)
    public String getIdDoc() {
        return this.idDoc;
    }
    
    public void setIdDoc(String idDoc) {
        this.idDoc = idDoc;
    }

    
    @Column(name="TITLE", length=500)
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }

    
    @Column(name="DT_DOC", length=7)
    public Date getDtDoc() {
        return this.dtDoc;
    }
    
    public void setDtDoc(Date dtDoc) {
        this.dtDoc = dtDoc;
    }

    
    @Column(name="TS_INS", nullable=false)
    public Date getTsIns() {
        return this.tsIns;
    }
    
    public void setTsIns(Date tsIns) {
        this.tsIns = tsIns;
    }

    
    @Column(name="TS_ULTIMO_AGG", nullable=false)
    public Date getTsUltimoAgg() {
        return this.tsUltimoAgg;
    }
    
    public void setTsUltimoAgg(Date tsUltimoAgg) {
        this.tsUltimoAgg = tsUltimoAgg;
    }




}


