/* * SPDX-License-Identifier: AGPL-3.0-or-later * * C Copyright 2023 Regione Piemonte * */

// Generated 29-feb-2016 12.30.48 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * TOperRichEmailToSend generated by hbm2java
 */
@Entity
@Table(name = "T_OPER_RICH_EMAIL_TO_SEND", uniqueConstraints = @UniqueConstraint(columnNames = { "ID_RICHIESTA", "OPERTYPE" }))
public class TOperRichEmailToSend implements java.io.Serializable {

	private String idOperRichEmailToSend;
	private TRichEmailToSend TRichEmailToSend;
	private String opertype;
	private String stato;
	private String errMsg;
	private String result;
	private BigDecimal tryNum;
	private Date tsIns;
	private Date tsUltimoAgg;

	public TOperRichEmailToSend() {
	}

	public TOperRichEmailToSend(String idOperRichEmailToSend, TRichEmailToSend TRichEmailToSend, String opertype, String stato,
			BigDecimal tryNum, Date tsIns, Date tsUltimoAgg) {
		this.idOperRichEmailToSend = idOperRichEmailToSend;
		this.TRichEmailToSend = TRichEmailToSend;
		this.opertype = opertype;
		this.stato = stato;
		this.tryNum = tryNum;
		this.tsIns = tsIns;
		this.tsUltimoAgg = tsUltimoAgg;
	}

	public TOperRichEmailToSend(String idOperRichEmailToSend, TRichEmailToSend TRichEmailToSend, String opertype, String stato,
			String errMsg, String result, BigDecimal tryNum, Date tsIns, Date tsUltimoAgg) {
		this.idOperRichEmailToSend = idOperRichEmailToSend;
		this.TRichEmailToSend = TRichEmailToSend;
		this.opertype = opertype;
		this.stato = stato;
		this.errMsg = errMsg;
		this.result = result;
		this.tryNum = tryNum;
		this.tsIns = tsIns;
		this.tsUltimoAgg = tsUltimoAgg;
	}

	@Id
	@Column(name = "ID_OPER_RICH_EMAIL_TO_SEND", unique = true, nullable = false, length = 64)
	public String getIdOperRichEmailToSend() {
		return this.idOperRichEmailToSend;
	}

	public void setIdOperRichEmailToSend(String idOperRichEmailToSend) {
		this.idOperRichEmailToSend = idOperRichEmailToSend;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_RICHIESTA", nullable = false)
	public TRichEmailToSend getTRichEmailToSend() {
		return this.TRichEmailToSend;
	}

	public void setTRichEmailToSend(TRichEmailToSend TRichEmailToSend) {
		this.TRichEmailToSend = TRichEmailToSend;
	}

	@Column(name = "OPERTYPE", nullable = false, length = 150)
	public String getOpertype() {
		return this.opertype;
	}

	public void setOpertype(String opertype) {
		this.opertype = opertype;
	}

	@Column(name = "STATO", nullable = false, length = 30)
	public String getStato() {
		return this.stato;
	}

	public void setStato(String stato) {
		this.stato = stato;
	}

	@Column(name = "ERR_MSG")
	public String getErrMsg() {
		return this.errMsg;
	}

	public void setErrMsg(String errMsg) {
		this.errMsg = errMsg;
	}

	@Column(name = "RESULT")
	public String getResult() {
		return this.result;
	}

	public void setResult(String result) {
		this.result = result;
	}

	@Column(name = "TRY_NUM", nullable = false, precision = 22, scale = 0)
	public BigDecimal getTryNum() {
		return this.tryNum;
	}

	public void setTryNum(BigDecimal tryNum) {
		this.tryNum = tryNum;
	}

	@Column(name = "TS_INS", nullable = false)
	public Date getTsIns() {
		return this.tsIns;
	}

	public void setTsIns(Date tsIns) {
		this.tsIns = tsIns;
	}

	@Column(name = "TS_ULTIMO_AGG", nullable = false)
	public Date getTsUltimoAgg() {
		return this.tsUltimoAgg;
	}

	public void setTsUltimoAgg(Date tsUltimoAgg) {
		this.tsUltimoAgg = tsUltimoAgg;
	}

}
