/* * SPDX-License-Identifier: AGPL-3.0-or-later * * C Copyright 2023 Regione Piemonte * */

// Generated il giorno 29-gen-2013 14.08.02 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * TUserPreferences generated by hbm2java
 */
@Entity
@Table(name = "T_USER_PREFERENCES")
@org.hibernate.annotations.Entity(dynamicUpdate = true, dynamicInsert = true)
public class TUserPreferences implements java.io.Serializable {

	private TUserPreferencesId id;
	private String value;
	private Date settingTime;
	private BigDecimal idUo;
	private Boolean flgVisibSottoUo;
	private Boolean flgGestSottoUo;

	public TUserPreferences() {
	}

	public TUserPreferences(TUserPreferencesId id, Date settingTime) {
		this.id = id;
		this.settingTime = settingTime;
	}

	public TUserPreferences(TUserPreferencesId id, String value, Date settingTime, BigDecimal idUo, Boolean flgVisibSottoUo, Boolean flgGestSottoUo) {
		this.id = id;
		this.value = value;
		this.settingTime = settingTime;
		this.idUo = idUo;
		this.flgVisibSottoUo = flgVisibSottoUo;
		this.flgGestSottoUo = flgGestSottoUo;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "userid", column = @Column(name = "USERID", nullable = false, length = 64)),
			@AttributeOverride(name = "prefKey", column = @Column(name = "PREF_KEY", nullable = false, length = 150)),
			@AttributeOverride(name = "prefName", column = @Column(name = "PREF_NAME", nullable = false, length = 150)) })
	public TUserPreferencesId getId() {
		return this.id;
	}

	public void setId(TUserPreferencesId id) {
		this.id = id;
	}

	@Column(name = "VALUE")
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	@Column(name = "SETTING_TIME", nullable = false)
	public Date getSettingTime() {
		return this.settingTime;
	}

	public void setSettingTime(Date settingTime) {
		this.settingTime = settingTime;
	}

	@Column(name = "ID_UO", precision = 22, scale = 0)
	public BigDecimal getIdUo() {
		return this.idUo;
	}

	public void setIdUo(BigDecimal idUo) {
		this.idUo = idUo;
	}

	@Column(name = "FLG_VISIB_SOTTOUO", precision = 1, scale = 0)
	public Boolean getFlgVisibSottoUo() {
		return this.flgVisibSottoUo;
	}

	public void setFlgVisibSottoUo(Boolean flgVisibSottoUo) {
		this.flgVisibSottoUo = flgVisibSottoUo;
	}

	@Column(name = "FLG_GEST_SOTTOUO", precision = 1, scale = 0)
	public Boolean getFlgGestSottoUo() {
		return this.flgGestSottoUo;
	}

	public void setFlgGestSottoUo(Boolean flgGestSottoUo) {
		this.flgGestSottoUo = flgGestSottoUo;
	}

}
