/* * SPDX-License-Identifier: AGPL-3.0-or-later * * C Copyright 2023 Regione Piemonte * */
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.05.07 at 02:48:35 PM CEST 
//


package it.eng.aurigamailbusiness.daticert;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "mittente",
    "destinatari",
    "risposte",
    "oggetto"
})
@XmlRootElement(name = "intestazione")
public class Intestazione {

    @XmlElement(required = true)
    protected String mittente;
    @XmlElement(required = true)
    protected List<Destinatari> destinatari;
    @XmlElement(required = true)
    protected String risposte;
    protected String oggetto;

    /**
     * Gets the value of the mittente property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMittente() {
        return mittente;
    }

    /**
     * Sets the value of the mittente property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMittente(String value) {
        this.mittente = value;
    }

    /**
     * Gets the value of the destinatari property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the destinatari property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDestinatari().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Destinatari }
     * 
     * 
     */
    public List<Destinatari> getDestinatari() {
        if (destinatari == null) {
            destinatari = new ArrayList<Destinatari>();
        }
        return this.destinatari;
    }

    /**
     * Gets the value of the risposte property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRisposte() {
        return risposte;
    }

    /**
     * Sets the value of the risposte property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRisposte(String value) {
        this.risposte = value;
    }

    /**
     * Gets the value of the oggetto property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOggetto() {
        return oggetto;
    }

    /**
     * Sets the value of the oggetto property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOggetto(String value) {
        this.oggetto = value;
    }

}
