//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.20 at 04:06:38 PM CEST 
//


package it.eng.jaxb.variabili;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the it.eng.jaxb.variabili package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: it.eng.jaxb.variabili
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SezioneCache }
     * 
     */
    public SezioneCache createSezioneCache() {
        return new SezioneCache();
    }

    /**
     * Create an instance of {@link SezioneCache.Variabile }
     * 
     */
    public SezioneCache.Variabile createSezioneCacheVariabile() {
        return new SezioneCache.Variabile();
    }

    /**
     * Create an instance of {@link SezioneCache.Variabile.Lista }
     * 
     */
    public SezioneCache.Variabile.Lista createSezioneCacheVariabileLista() {
        return new SezioneCache.Variabile.Lista();
    }

    /**
     * Create an instance of {@link SezioneCache.Variabile.Lista.Riga }
     * 
     */
    public SezioneCache.Variabile.Lista.Riga createSezioneCacheVariabileListaRiga() {
        return new SezioneCache.Variabile.Lista.Riga();
    }

    /**
     * Create an instance of {@link SezioneCache.Variabile.Lista.Riga.Colonna }
     * 
     */
    public SezioneCache.Variabile.Lista.Riga.Colonna createSezioneCacheVariabileListaRigaColonna() {
        return new SezioneCache.Variabile.Lista.Riga.Colonna();
    }

}
