/* * SPDX-License-Identifier: AGPL-3.0-or-later * * C Copyright 2023 Regione Piemonte * */
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.22 at 10:59:55 AM CET 
//


package it.eng.module.foutility.beans.merge.response;

import javax.activation.DataHandler;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlMimeType;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the it.eng.auriga.repository2.jaxws.jaxbbean.service.mergedocument.response package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ServiceReturn_QNAME = new QName("", "serviceReturn");
    private final static QName _FileAttached_QNAME = new QName("", "fileAttached");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: it.eng.auriga.repository2.jaxws.jaxbbean.service.mergedocument.response
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link MergeResponse }
     * 
     */
    public MergeDocumentResponse createMergeDocumentResponse() {
        return new MergeDocumentResponse();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "serviceReturn")
    public JAXBElement<String> createServiceReturn(String value) {
        return new JAXBElement<String>(_ServiceReturn_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DataHandler }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "fileAttached")
    @XmlMimeType("application/octet-stream")
    public JAXBElement<DataHandler> createFileAttached(DataHandler value) {
        return new JAXBElement<DataHandler>(_FileAttached_QNAME, DataHandler.class, null, value);
    }

}
