/* * SPDX-License-Identifier: AGPL-3.0-or-later * * C Copyright 2023 Regione Piemonte * */
 Copyright (c) 2003-2020, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or https://ckeditor.com/legal/ckeditor-oss-license
*/
(function(){function r(){return!1}var n=CKEDITOR.tools,B=CKEDITOR.plugins.pastetools,t=B.filters.common,h=t.styles,C=t.createAttributeStack,z=t.lists.getElementIndentation,D=["o:p","xml","script","meta","link"],E="v:arc v:curve v:line v:oval v:polyline v:rect v:roundrect v:group".split(" "),A={},y=0,q={},f,p;CKEDITOR.plugins.pastetools.filters.word=q;CKEDITOR.plugins.pastefromword=q;q.rules=function(a,b,c){function d(b){(b.attributes["o:gfxdata"]||"v:group"===b.parent.name)&&k.push(b.attributes.id)}
var e=Boolean(a.match(/mso-list:\s*l\d+\s+level\d+\s+lfo\d+/)),k=[],w={root:function(b){b.filterChildren(c);CKEDITOR.plugins.pastefromword.lists.cleanup(f.createLists(b))},elementNames:[[/^\?xml:namespace$/,""],[/^v:shapetype/,""],[new RegExp(D.join("|")),""]],elements:{a:function(b){if(b.attributes.name){if("_GoBack"==b.attributes.name){delete b.name;return}if(b.attributes.name.match(/^OLE_LINK\d+$/)){delete b.name;return}}if(b.attributes.href&&b.attributes.href.match(/#.+$/)){var a=b.attributes.href.match(/#(.+)$/)[1];
A[a]=b}b.attributes.name&&A[b.attributes.name]&&(b=A[b.attributes.name],b.attributes.href=b.attributes.href.replace(/.*#(.*)$/,"#$1"))},div:function(a){if(b.plugins.pagebreak&&a.attributes["data-cke-pagebreak"])return a;h.createStyleStack(a,c,b)},img:function(b){if(b.parent&&b.parent.attributes){var a=b.parent.attributes;(a=a.style||a.STYLE)&&a.match(/mso\-list:\s?Ignore/)&&(b.attributes["cke-ignored"]=!0)}h.mapCommonStyles(b);b.attributes.src&&b.attributes.src.match(/^file:\/\//)&&b.attributes.alt&&
b.attributes.alt.match(/^https?:\/\//)&&(b.attributes.src=b.attributes.alt);b=b.attributes["v:shapes"]?b.attributes["v:shapes"].split(" "):[];a=CKEDITOR.tools.array.every(b,function(b){return-1<k.indexOf(b)});if(b.length&&a)return!1},p:function(a){a.filterChildren(c);if(a.attributes.style&&a.attributes.style.match(/display:\s*none/i))return!1;if(f.thisIsAListItem(b,a))p.isEdgeListItem(b,a)&&p.cleanupEdgeListItem(a),f.convertToFakeListItem(b,a),n.array.reduce(a.children,function(b,a){"p"===a.name&&
(0<b&&(new CKEDITOR.htmlParser.element("br")).insertBefore(a),a.replaceWithChildren(),b+=1);return b},0);else{var d=a.getAscendant(function(b){return"ul"==b.name||"ol"==b.name}),e=n.parseCssText(a.attributes.style);d&&!d.attributes["cke-list-level"]&&e["mso-list"]&&e["mso-list"].match(/level/)&&(d.attributes["cke-list-level"]=e["mso-list"].match(/level(\d+)/)[1]);b.config.enterMode==CKEDITOR.ENTER_BR&&(delete a.name,a.add(new CKEDITOR.htmlParser.element("br")))}h.createStyleStack(a,c,b)},pre:function(a){f.thisIsAListItem(b,
a)&&f.convertToFakeListItem(b,a);h.createStyleStack(a,c,b)},h1:function(a){f.thisIsAListItem(b,a)&&f.convertToFakeListItem(b,a);h.createStyleStack(a,c,b)},h2:function(a){f.thisIsAListItem(b,a)&&f.convertToFakeListItem(b,a);h.createStyleStack(a,c,b)},h3:function(a){f.thisIsAListItem(b,a)&&f.convertToFakeListItem(b,a);h.createStyleStack(a,c,b)},h4:function(a){f.thisIsAListItem(b,a)&&f.convertToFakeListItem(b,a);h.createStyleStack(a,c,b)},h5:function(a){f.thisIsAListItem(b,a)&&f.convertToFakeListItem(b,
a);h.createStyleStack(a,c,b)},h6:function(a){f.thisIsAListItem(b,a)&&f.convertToFakeListItem(b,a);h.createStyleStack(a,c,b)},font:function(a){if(a.getHtml().match(/^\s*$/))return a.parent.type===CKEDITOR.NODE_ELEMENT&&(new CKEDITOR.htmlParser.text(" ")).insertAfter(a),!1;b&&!0===b.config.pasteFromWordRemoveFontStyles&&a.attributes.size&&delete a.attributes.size;CKEDITOR.dtd.tr[a.parent.name]&&CKEDITOR.tools.arrayCompare(CKEDITOR.tools.object.keys(a.attributes),["class","style"])?h.createStyleStack(a,
c,b):C(a,c)},ul:function(a){if(e)return"li"==a.parent.name&&0===n.indexOf(a.parent.children,a)&&h.setStyle(a.parent,"list-style-type","none"),f.dissolveList(a),!1},li:function(a){p.correctLevelShift(a);e&&(a.attributes.style=h.normalizedStyles(a,b),h.pushStylesLower(a))},ol:function(a){if(e)return"li"==a.parent.name&&0===n.indexOf(a.parent.children,a)&&h.setStyle(a.parent,"list-style-type","none"),f.dissolveList(a),!1},span:function(a){a.filterChildren(c);a.attributes.style=h.normalizedStyles(a,b);
if(!a.attributes.style||a.attributes.style.match(/^mso\-bookmark:OLE_LINK\d+$/)||a.getHtml().match(/^(\s|&nbsp;)+$/))return t.elements.replaceWithChildren(a),!1;a.attributes.style.match(/FONT-FAMILY:\s*Symbol/i)&&a.forEach(function(a){a.value=a.value.replace(/&nbsp;/g,"")},CKEDITOR.NODE_TEXT,!0);h.createStyleStack(a,c,b)},"v:imagedata":r,"v:shape":function(a){var b=!1;if(null===a.getFirst("v:imagedata"))d(a);else{a.parent.find(function(c){"img"==c.name&&c.attributes&&c.attributes["v:shapes"]==a.attributes.id&&
(b=!0)},!0);if(b)return!1;var e="";"v:group"===a.parent.name?d(a):(a.forEach(function(a){a.attributes&&a.attributes.src&&(e=a.attributes.src)},CKEDITOR.NODE_ELEMENT,!0),a.filterChildren(c),a.name="img",a.attributes.src=a.attributes.src||e,delete a.attributes.type)}},style:function(){return!1},object:function(a){return!(!a.attributes||!a.attributes.data)},br:function(a){if(b.plugins.pagebreak&&(a=n.parseCssText(a.attributes.style,!0),"always"===a["page-break-before"]||"page"===a["break-before"]))return a=
CKEDITOR.plugins.pagebreak.createElement(b),CKEDITOR.htmlParser.fragment.fromHtml(a.getOuterHtml()).children[0]}},attributes:{style:function(a,c){return h.normalizedStyles(c,b)||!1},"class":function(a){a=a.replace(/(el\d+)|(font\d+)|msonormal|msolistparagraph\w*/ig,"");return""===a?!1:a},cellspacing:r,cellpadding:r,border:r,"v:shapes":r,"o:spid":r},comment:function(a){a.match(/\[if.* supportFields.*\]/)&&y++;"[endif]"==a&&(y=0<y?y-1:0);return!1},text:function(a,b){if(y)return"";var c=b.parent&&b.parent.parent;
return c&&c.attributes&&c.attributes.style&&c.attributes.style.match(/mso-list:\s*ignore/i)?a.replace(/&nbsp;/g," "):a}};n.array.forEach(E,function(a){w.elements[a]=d});return w};q.lists={thisIsAListItem:function(a,b){return p.isEdgeListItem(a,b)||b.attributes.style&&b.attributes.style.match(/mso\-list:\s?l\d/)&&"li"!==b.parent.name||b.attributes["cke-dissolved"]||b.getHtml().match(/<!\-\-\[if !supportLists]\-\->/)?!0:!1},convertToFakeListItem:function(a,b){p.isDegenerateListItem(a,b)&&p.assignListLevels(a,
b);this.getListItemInfo(b);if(!b.attributes["cke-dissolved"]){var c;b.forEach(function(a){!c&&"img"==a.name&&a.attributes["cke-ignored"]&&"*"==a.attributes.alt&&(c="·",a.remove())},CKEDITOR.NODE_ELEMENT);b.forEach(function(a){c||a.value.match(/^ /)||(c=a.value)},CKEDITOR.NODE_TEXT);if("undefined"==typeof c)return;b.attributes["cke-symbol"]=c.replace(/(?: |&nbsp;).*$/,"");f.removeSymbolText(b)}var d=b.attributes&&n.parseCssText(b.attributes.style);if(d["margin-left"]){var e=d["margin-left"],k=b.attributes["cke-list-level"];
(e=Math.max(CKEDITOR.tools.convertToPx(e)-40*k,0))?d["margin-left"]=e+"px":delete d["margin-left"];b.attributes.style=CKEDITOR.tools.writeCssText(d)}b.name="cke:li"},checkIfRealOrderedList:function(a){if(a&&1<a.length&&(a[0].attributes["cke-symbol"].match(/([\da-np-zA-NP-Z]).?/)||[])[1]&&a[0].attributes["cke-symbol"]==a[1].attributes["cke-symbol"])for(var b=0;b<a.length;b++)a[b].attributes["cke-symbol"]="·";return a},convertToRealListItems:function(a){var b=[];a.forEach(function(a){"cke:li"==a.name&&
(a.name="li",b.push(a))},CKEDITOR.NODE_ELEMENT,!1);this.checkIfRealOrderedList(b);return b},removeSymbolText:function(a){var b=a.attributes["cke-symbol"],c=a.findOne(function(a){return a.value&&-1<a.value.indexOf(b)},!0),d;c&&(c.value=c.value.replace(b,""),d=c.parent,d.getHtml().match(/^(\s|&nbsp;)*$/)&&d!==a?d.remove():c.value||c.remove())},setListSymbol:function(a,b,c){c=c||1;var d=n.parseCssText(a.attributes.style);if("ol"==a.name){if(a.attributes.type||d["list-style-type"])return;var e={"[ivx]":"lower-roman",
"[IVX]":"upper-roman","[a-z]":"lower-alpha","[A-Z]":"upper-alpha","\\d":"decimal"},k;for(k in e)if(f.getSubsectionSymbol(b).match(new RegExp(k))){d["list-style-type"]=e[k];break}a.attributes["cke-list-style-type"]=d["list-style-type"]}else e={"·":"disc",o:"circle","§":"square"},!d["list-style-type"]&&e[b]&&(d["list-style-type"]=e[b]);f.setListSymbol.removeRedundancies(d,c);(a.attributes.style=CKEDITOR.tools.writeCssText(d))||delete a.attributes.style},setListStart:function(a){for(var b=[],c=0,d=0;d<
a.children.length;d++)b.push(a.children[d].attributes["cke-symbol"]||"");b[0]||c++;switch(a.attributes["cke-list-style-type"]){case "lower-roman":case "upper-roman":a.attributes.start=f.toArabic(f.getSubsectionSymbol(b[c]))-c;break;case "lower-alpha":case "upper-alpha":a.attributes.start=f.getSubsectionSymbol(b[c]).replace(/\W/g,"").toLowerCase().charCodeAt(0)-96-c;break;case "decimal":a.attributes.start=parseInt(f.getSubsectionSymbol(b[c]),10)-c||1}"1"==a.attributes.start&&delete a.attributes.start},
numbering:{toNumber:function(a,b){function c(a){a=a.toUpperCase();for(var b=1,c=1;0<a.length;c*=26)b+="ABCDEFGHIJKLMNOPQRSTUVWXYZ".indexOf(a.charAt(a.length-1))*c,a=a.substr(0,a.length-1);return b}function d(a){var b=[[1E3,"M"],[900,"CM"],[500,"D"],[400,"CD"],[100,"C"],[90,"XC"],[50,"L"],[40,"XL"],[10,"X"],[9,"IX"],[5,"V"],[4,"IV"],[1,"I"]];a=a.toUpperCase();for(var c=b.length,d=0,f=0;f<c;++f)for(var l=b[f],u=l[1].length;a.substr(0,u)==l[1];a=a.substr(u))d+=l[0];return d}return"decimal"==b?Number(a):
"upper-roman"==b||"lower-roman"==b?d(a.toUpperCase()):"lower-alpha"==b||"upper-alpha"==b?c(a):1},getStyle:function(a){a=a.slice(0,1);var b={i:"lower-roman",v:"lower-roman",x:"lower-roman",l:"lower-roman",m:"lower-roman",I:"upper-roman",V:"upper-roman",X:"upper-roman",L:"upper-roman",M:"upper-roman"}[a];b||(b="decimal",a.match(/[a-z]/)&&(b="lower-alpha"),a.match(/[A-Z]/)&&(b="upper-alpha"));return b}},getSubsectionSymbol:function(a){return(a.match(/([\da-zA-Z]+).?$/)||["placeholder","1"])[1]},setListDir:function(a){var b=
0,c=0;a.forEach(function(a){"li"==a.name&&("rtl"==(a.attributes.dir||a.attributes.DIR||"").toLowerCase()?c++:b++)},CKEDITOR.ELEMENT_NODE);c>b&&(a.attributes.dir="rtl")},createList:function(a){return(a.attributes["cke-symbol"].match(/([\da-np-zA-NP-Z]).?/)||[])[1]?new CKEDITOR.htmlParser.element("ol"):new CKEDITOR.htmlParser.element("ul")},createLists:function(a){function b(a){return CKEDITOR.tools.array.reduce(a,function(a,b){if(b.attributes&&b.attributes.style)var c=CKEDITOR.tools.parseCssText(b.attributes.style)["margin-left"];
return c?a+parseInt(c,10):a},0)}var c,d,e,k=f.convertToRealListItems(a);if(0===k.length)return[];var h=f.groupLists(k);for(a=0;a<h.length;a++){var m=h[a],g=m[0];for(e=0;e<m.length;e++)if(1==m[e].attributes["cke-list-level"]){g=m[e];break}var g=[f.createList(g)],l=g[0],u=[g[0]];l.insertBefore(m[0]);for(e=0;e<m.length;e++){c=m[e];for(d=c.attributes["cke-list-level"];d>g.length;){var v=f.createList(c),x=l.children;0<x.length?x[x.length-1].add(v):(x=new CKEDITOR.htmlParser.element("li",{style:"list-style-type:none"}),
x.add(v),l.add(x));g.push(v);u.push(v);l=v;d==g.length&&f.setListSymbol(v,c.attributes["cke-symbol"],d)}for(;d<g.length;)g.pop(),l=g[g.length-1],d==g.length&&f.setListSymbol(l,c.attributes["cke-symbol"],d);c.remove();l.add(c)}g[0].children.length&&(e=g[0].children[0].attributes["cke-symbol"],!e&&1<g[0].children.length&&(e=g[0].children[1].attributes["cke-symbol"]),e&&f.setListSymbol(g[0],e));for(e=0;e<u.length;e++)f.setListStart(u[e]);for(e=0;e<m.length;e++)this.determineListItemValue(m[e])}CKEDITOR.tools.array.forEach(k,
function(a){for(var c=[],d=a.parent;d;)"li"===d.name&&c.push(d),d=d.parent;var c=b(c),e;c&&(a.attributes=a.attributes||{},d=CKEDITOR.tools.parseCssText(a.attributes.style),e=d["margin-left"]||0,(e=Math.max(parseInt(e,10)-c,0))?d["margin-left"]=e+"px":delete d["margin-left"],a.attributes.style=CKEDITOR.tools.writeCssText(d))});return k},cleanup:function(a){var b=["cke-list-level","cke-symbol","cke-list-id","cke-indentation","cke-dissolved"],c,d;for(c=0;c<a.length;c++)for(d=0;d<b.length;d++)delete a[c].attributes[b[d]]},
determineListItemValue:function(a){if("ol"===a.parent.name){var b=this.calculateValue(a),c=a.attributes["cke-symbol"].match(/[a-z0-9]+/gi),d;c&&(c=c[c.length-1],d=a.parent.attributes["cke-list-style-type"]||this.numbering.getStyle(c),c=this.numbering.toNumber(c,d),c!==b&&(a.attributes.value=c))}},calculateValue:function(a){if(!a.parent)return 1;var b=a.parent;a=a.getIndex();var c=null,d,e,f;for(f=a;0<=f&&null===c;f--)e=b.children[f],e.attributes&&void 0!==e.attributes.value&&(d=f,c=parseInt(e.attributes.value,
10));null===c&&(c=void 0!==b.attributes.start?parseInt(b.attributes.start,10):1,d=0);return c+(a-d)},dissolveList:function(a){function b(a){return 50<=a?"l"+b(a-50):40<=a?"xl"+b(a-40):10<=a?"x"+b(a-10):9==a?"ix":5<=a?"v"+b(a-5):4==a?"iv":1<=a?"i"+b(a-1):""}function c(a,b){function c(b,d){return b&&b.parent?a(b.parent)?c(b.parent,d+1):c(b.parent,d):d}return c(b,0)}var d=function(a){return function(b){return b.name==a}},e=function(a){return d("ul")(a)||d("ol")(a)},f=CKEDITOR.tools.array,w=[],m,g;a.forEach(function(a){w.push(a)},
CKEDITOR.NODE_ELEMENT,!1);m=f.filter(w,d("li"));var l=f.filter(w,e);f.forEach(l,function(a){var g=a.attributes.type,l=parseInt(a.attributes.start,10)||1,h=c(e,a)+1;g||(g=n.parseCssText(a.attributes.style)["list-style-type"]);f.forEach(f.filter(a.children,d("li")),function(c,d){var e;switch(g){case "disc":e="·";break;case "circle":e="o";break;case "square":e="§";break;case "1":case "decimal":e=l+d+".";break;case "a":case "lower-alpha":e=String.fromCharCode(97+l-1+d)+".";break;case "A":case "upper-alpha":e=
String.fromCharCode(65+l-1+d)+".";break;case "i":case "lower-roman":e=b(l+d)+".";break;case "I":case "upper-roman":e=b(l+d).toUpperCase()+".";break;default:e="ul"==a.name?"·":l+d+"."}c.attributes["cke-symbol"]=e;c.attributes["cke-list-level"]=h})});m=f.reduce(m,function(a,b){var c=b.children[0];if(c&&c.name&&c.attributes.style&&c.attributes.style.match(/mso-list:/i)){h.pushStylesLower(b,{"list-style-type":!0,display:!0});var d=n.parseCssText(c.attributes.style,!0);h.setStyle(b,"mso-list",d["mso-list"],
!0);h.setStyle(c,"mso-list","");delete b["cke-list-level"];(c=d.display?"display":d.DISPLAY?"DISPLAY":"")&&h.setStyle(b,"display",d[c],!0)}if(1===b.children.length&&e(b.children[0]))return a;b.name="p";b.attributes["cke-dissolved"]=!0;a.push(b);return a},[]);for(g=m.length-1;0<=g;g--)m[g].insertAfter(a);for(g=l.length-1;0<=g;g--)delete l[g].name},groupLists:function(a){var b,c,d=[[a[0]]],e=d[0];c=a[0];c.attributes["cke-indentation"]=c.attributes["cke-indentation"]||z(c);for(b=1;b<a.length;b++){c=
a[b];var k=a[b-1];c.attributes["cke-indentation"]=c.attributes["cke-indentation"]||z(c);c.previous!==k&&(f.chopDiscontinuousLists(e,d),d.push(e=[]));e.push(c)}f.chopDiscontinuousLists(e,d);return d},chopDiscontinuousLists:function(a,b){for(var c={},d=[[]],e,k=0;k<a.length;k++){var h=c[a[k].attributes["cke-list-level"]],m=this.getListItemInfo(a[k]),g,l;h?(l=h.type.match(/alpha/)&&7==h.index?"alpha":l,l="o"==a[k].attributes["cke-symbol"]&&14==h.index?"alpha":l,g=f.getSymbolInfo(a[k].attributes["cke-symbol"],
l),m=this.getListItemInfo(a[k]),(h.type!=g.type||e&&m.id!=e.id&&!this.isAListContinuation(a[k]))&&d.push([])):g=f.getSymbolInfo(a[k].attributes["cke-symbol"]);for(e=parseInt(a[k].attributes["cke-list-level"],10)+1;20>e;e++)c[e]&&delete c[e];c[a[k].attributes["cke-list-level"]]=g;d[d.length-1].push(a[k]);e=m}[].splice.apply(b,[].concat([n.indexOf(b,a),1],d))},isAListContinuation:function(a){var b=a;do if((b=b.previous)&&b.type===CKEDITOR.NODE_ELEMENT){if(void 0===b.attributes["cke-list-level"])break;
if(b.attributes["cke-list-level"]===a.attributes["cke-list-level"])return b.attributes["cke-list-id"]===a.attributes["cke-list-id"]}while(b);return!1},toArabic:function(a){return a.match(/[ivxl]/i)?a.match(/^l/i)?50+f.toArabic(a.slice(1)):a.match(/^lx/i)?40+f.toArabic(a.slice(1)):a.match(/^x/i)?10+f.toArabic(a.slice(1)):a.match(/^ix/i)?9+f.toArabic(a.slice(2)):a.match(/^v/i)?5+f.toArabic(a.slice(1)):a.match(/^iv/i)?4+f.toArabic(a.slice(2)):a.match(/^i/i)?1+f.toArabic(a.slice(1)):f.toArabic(a.slice(1)):
0},getSymbolInfo:function(a,b){var c=a.toUpperCase()==a?"upper-":"lower-",d={"·":["disc",-1],o:["circle",-2],"§":["square",-3]};if(a in d||b&&b.match(/(disc|circle|square)/))return{index:d[a][1],type:d[a][0]};if(a.match(/\d/))return{index:a?parseInt(f.getSubsectionSymbol(a),10):0,type:"decimal"};a=a.replace(/\W/g,"").toLowerCase();return!b&&a.match(/[ivxl]+/i)||b&&"alpha"!=b||"roman"==b?{index:f.toArabic(a),type:c+"roman"}:a.match(/[a-z]/i)?{index:a.charCodeAt(0)-97,type:c+"alpha"}:{index:-1,type:"disc"}},
getListItemInfo:function(a){if(void 0!==a.attributes["cke-list-id"])return{id:a.attributes["cke-list-id"],level:a.attributes["cke-list-level"]};var b=n.parseCssText(a.attributes.style)["mso-list"],c={id:"0",level:"1"};b&&(b+=" ",c.level=b.match(/level(.+?)\s+/)[1],c.id=b.match(/l(\d+?)\s+/)[1]);a.attributes["cke-list-level"]=void 0!==a.attributes["cke-list-level"]?a.attributes["cke-list-level"]:c.level;a.attributes["cke-list-id"]=c.id;return c}};f=q.lists;q.images={extractFromRtf:function(a){var b=
[],c=/\{\\pict[\s\S]+?\\bliptag\-?\d+(\\blipupi\-?\d+)?(\{\\\*\\blipuid\s?[\da-fA-F]+)?[\s\}]*?/,d;a=a.match(new RegExp("(?:("+c.source+"))([\\da-fA-F\\s]+)\\}","g"));if(!a)return b;for(var e=0;e<a.length;e++)if(c.test(a[e])){if(-1!==a[e].indexOf("\\pngblip"))d="image/png";else if(-1!==a[e].indexOf("\\jpegblip"))d="image/jpeg";else continue;b.push({hex:d?a[e].replace(c,"").replace(/[^\da-fA-F]/g,""):null,type:d})}return b},extractTagsFromHtml:function(a){for(var b=/<img[^>]+src="([^"]+)[^>]+/g,c=
[],d;d=b.exec(a);)c.push(d[1]);return c}};q.heuristics={isEdgeListItem:function(a,b){if(!CKEDITOR.env.edge||!a.config.pasteFromWord_heuristicsEdgeList)return!1;var c="";b.forEach&&b.forEach(function(a){c+=a.value},CKEDITOR.NODE_TEXT);return c.match(/^(?: |&nbsp;)*\(?[a-zA-Z0-9]+?[\.\)](?: |&nbsp;){2,}/)?!0:p.isDegenerateListItem(a,b)},cleanupEdgeListItem:function(a){var b=!1;a.forEach(function(a){b||(a.value=a.value.replace(/^(?:&nbsp;|[\s])+/,""),a.value.length&&(b=!0))},CKEDITOR.NODE_TEXT)},isDegenerateListItem:function(a,
b){return!!b.attributes["cke-list-level"]||b.attributes.style&&!b.attributes.style.match(/mso\-list/)&&!!b.find(function(a){if(a.type==CKEDITOR.NODE_ELEMENT&&b.name.match(/h\d/i)&&a.getHtml().match(/^[a-zA-Z0-9]+?[\.\)]$/))return!0;var d=n.parseCssText(a.attributes&&a.attributes.style,!0);if(!d)return!1;var e=d["font-family"]||"";return(d.font||d["font-size"]||"").match(/7pt/i)&&!!a.previous||e.match(/symbol/i)},!0).length},assignListLevels:function(a,b){if(!b.attributes||void 0===b.attributes["cke-list-level"]){for(var c=
[z(b)],d=[b],e=[],f=CKEDITOR.tools.array,h=f.map;b.next&&b.next.attributes&&!b.next.attributes["cke-list-level"]&&p.isDegenerateListItem(a,b.next);)b=b.next,c.push(z(b)),d.push(b);var m=h(c,function(a,b){return 0===b?0:a-c[b-1]}),g=this.guessIndentationStep(f.filter(c,function(a){return 0!==a})),e=h(c,function(a){return Math.round(a/g)});-1!==f.indexOf(e,0)&&(e=h(e,function(a){return a+1}));f.forEach(d,function(a,b){a.attributes["cke-list-level"]=e[b]});return{indents:c,levels:e,diffs:m}}},guessIndentationStep:function(a){return a.length?
Math.min.apply(null,a):null},correctLevelShift:function(a){if(this.isShifted(a)){var b=CKEDITOR.tools.array.filter(a.children,function(a){return"ul"==a.name||"ol"==a.name}),c=CKEDITOR.tools.array.reduce(b,function(a,b){return(b.children&&1==b.children.length&&p.isShifted(b.children[0])?[b]:b.children).concat(a)},[]);CKEDITOR.tools.array.forEach(b,function(a){a.remove()});CKEDITOR.tools.array.forEach(c,function(b){a.add(b)});delete a.name}},isShifted:function(a){return"li"!==a.name?!1:0===CKEDITOR.tools.array.filter(a.children,
function(a){return a.name&&("ul"==a.name||"ol"==a.name||"p"==a.name&&0===a.children.length)?!1:!0}).length}};p=q.heuristics;f.setListSymbol.removeRedundancies=function(a,b){(1===b&&"disc"===a["list-style-type"]||"decimal"===a["list-style-type"])&&delete a["list-style-type"]};CKEDITOR.cleanWord=CKEDITOR.pasteFilters.word=B.createFilter({rules:[t.rules,q.rules],additionalTransforms:function(a){CKEDITOR.plugins.clipboard.isCustomDataTypesSupported&&(a=t.styles.inliner.inline(a).getBody().getHtml());
return a.replace(/<!\[/g,"\x3c!--[").replace(/\]>/g,"]--\x3e")}});CKEDITOR.config.pasteFromWord_heuristicsEdgeList=!0})();