package it.eng.dm.sira.entity;

// Generated 11-mag-2015 13.05.01 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Lob;
import javax.persistence.Table;

import org.hibernate.annotations.Type;
import org.hibernate.type.LobType;

/**
 * ActGeBytearray generated by hbm2java
 */
@Entity
@Table(name = "ACT_GE_BYTEARRAY")
public class ActGeBytearray implements java.io.Serializable {

	private String id;

	private BigDecimal rev;

	private String name;

	private String deploymentId;

	private  byte[] bytes;

	private Boolean generated;

	public ActGeBytearray() {
	}

	public ActGeBytearray(String id) {
		this.id = id;
	}

	public ActGeBytearray(String id, BigDecimal rev, String name, String deploymentId, byte[] bytes, Boolean generated) {
		this.id = id;
		this.rev = rev;
		this.name = name;
		this.deploymentId = deploymentId;
		this.bytes = bytes;
		this.generated = generated;
	}

	@Id
	@Column(name = "ID_", unique = true, nullable = false, length = 128)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "REV_", precision = 22, scale = 0)
	public BigDecimal getRev() {
		return this.rev;
	}

	public void setRev(BigDecimal rev) {
		this.rev = rev;
	}

	@Column(name = "NAME_", length = 510)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "DEPLOYMENT_ID_", length = 128)
	public String getDeploymentId() {
		return this.deploymentId;
	}

	public void setDeploymentId(String deploymentId) {
		this.deploymentId = deploymentId;
	}

	@Column(name = "GENERATED_", precision = 1, scale = 0)
	public Boolean getGenerated() {
		return this.generated;
	}

	public void setGenerated(Boolean generated) {
		this.generated = generated;
	}
	
	@Column(name = "BYTES_")
	@Type(type="binary")
	public byte[] getBytes() {
		return bytes;
	}

	public void setBytes(byte[] bytes) {
		this.bytes = bytes;
	}

}
