package it.eng.dm.sira.entity;

// Generated 11-mag-2015 13.06.23 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ActReDeployment generated by hbm2java
 */
@Entity
@Table(name = "ACT_RE_DEPLOYMENT")
public class ActReDeployment implements java.io.Serializable {

	private String id;

	private String name;

	private String category;

	private Date deployTime;

	private String tenantId;

	public ActReDeployment() {
	}

	public ActReDeployment(String id) {
		this.id = id;
	}

	public ActReDeployment(String id, String name, String category, Date deployTime, String tenantId) {
		this.id = id;
		this.name = name;
		this.category = category;
		this.deployTime = deployTime;
		this.tenantId = tenantId;
	}

	@Id
	@Column(name = "ID_", unique = true, nullable = false, length = 128)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "NAME_", length = 510)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "CATEGORY_", length = 510)
	public String getCategory() {
		return this.category;
	}

	public void setCategory(String category) {
		this.category = category;
	}

	@Column(name = "DEPLOY_TIME_")
	public Date getDeployTime() {
		return this.deployTime;
	}

	public void setDeployTime(Date deployTime) {
		this.deployTime = deployTime;
	}

	@Column(name = "TENANT_ID_", length = 510)
	public String getTenantId() {
		return this.tenantId;
	}

	public void setTenantId(String tenantId) {
		this.tenantId = tenantId;
	}

}
