package it.eng.dm.sira.entity;

// Generated 11-mag-2015 13.06.41 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * ActReProcdef generated by hbm2java
 */
@Entity
@Table(name = "ACT_RE_PROCDEF", uniqueConstraints = @UniqueConstraint(columnNames = { "KEY_", "VERSION_", "TENANT_ID_" }))
public class ActReProcdef implements java.io.Serializable {

	private String id;

	private BigDecimal rev;

	private String category;

	private String name;

	private String key;

	private BigDecimal version;

	private String deploymentId;

	private String resourceName;

	private String dgrmResourceName;

	private String description;

	private Boolean hasStartFormKey;

	private BigDecimal suspensionState;

	private String tenantId;

	public ActReProcdef() {
	}

	public ActReProcdef(String id, String key, BigDecimal version) {
		this.id = id;
		this.key = key;
		this.version = version;
	}

	public ActReProcdef(String id, BigDecimal rev, String category, String name, String key, BigDecimal version, String deploymentId,
			String resourceName, String dgrmResourceName, String description, Boolean hasStartFormKey, BigDecimal suspensionState,
			String tenantId) {
		this.id = id;
		this.rev = rev;
		this.category = category;
		this.name = name;
		this.key = key;
		this.version = version;
		this.deploymentId = deploymentId;
		this.resourceName = resourceName;
		this.dgrmResourceName = dgrmResourceName;
		this.description = description;
		this.hasStartFormKey = hasStartFormKey;
		this.suspensionState = suspensionState;
		this.tenantId = tenantId;
	}

	@Id
	@Column(name = "ID_", unique = true, nullable = false, length = 128)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "REV_", precision = 22, scale = 0)
	public BigDecimal getRev() {
		return this.rev;
	}

	public void setRev(BigDecimal rev) {
		this.rev = rev;
	}

	@Column(name = "CATEGORY_", length = 510)
	public String getCategory() {
		return this.category;
	}

	public void setCategory(String category) {
		this.category = category;
	}

	@Column(name = "NAME_", length = 510)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "KEY_", nullable = false, length = 510)
	public String getKey() {
		return this.key;
	}

	public void setKey(String key) {
		this.key = key;
	}

	@Column(name = "VERSION_", nullable = false, precision = 22, scale = 0)
	public BigDecimal getVersion() {
		return this.version;
	}

	public void setVersion(BigDecimal version) {
		this.version = version;
	}

	@Column(name = "DEPLOYMENT_ID_", length = 128)
	public String getDeploymentId() {
		return this.deploymentId;
	}

	public void setDeploymentId(String deploymentId) {
		this.deploymentId = deploymentId;
	}

	@Column(name = "RESOURCE_NAME_", length = 4000)
	public String getResourceName() {
		return this.resourceName;
	}

	public void setResourceName(String resourceName) {
		this.resourceName = resourceName;
	}

	@Column(name = "DGRM_RESOURCE_NAME_", length = 4000)
	public String getDgrmResourceName() {
		return this.dgrmResourceName;
	}

	public void setDgrmResourceName(String dgrmResourceName) {
		this.dgrmResourceName = dgrmResourceName;
	}

	@Column(name = "DESCRIPTION_", length = 4000)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "HAS_START_FORM_KEY_", precision = 1, scale = 0)
	public Boolean getHasStartFormKey() {
		return this.hasStartFormKey;
	}

	public void setHasStartFormKey(Boolean hasStartFormKey) {
		this.hasStartFormKey = hasStartFormKey;
	}

	@Column(name = "SUSPENSION_STATE_", precision = 22, scale = 0)
	public BigDecimal getSuspensionState() {
		return this.suspensionState;
	}

	public void setSuspensionState(BigDecimal suspensionState) {
		this.suspensionState = suspensionState;
	}

	@Column(name = "TENANT_ID_", length = 510)
	public String getTenantId() {
		return this.tenantId;
	}

	public void setTenantId(String tenantId) {
		this.tenantId = tenantId;
	}

}
