package it.eng.dm.sira.entity;

// Generated 7-feb-2014 12.08.50 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ComuniItalia generated by hbm2java
 */
@Entity
@Table(name = "COMUNI_ITALIA")
public class ComuniItalia implements java.io.Serializable {

	private ComuniItaliaId id;

	private String kcomune;

	private Double abitanti;

	private String siglaprov;

	private String siglareg;

	private String zona;

	private String ordineZona;

	private String regione;

	private String istat;

	private String provincia;

	private String comune;

	private String atoRifTosc;

	private String codsel;

	private String densel;

	private String codselquad;

	private String denselquad;

	private String diptoArpat;

	private String codMinFinanze;

	private Double estGbFoCentroide;

	private Double nordGbFoCentroide;

	private String comuneMin;

	private String cap;

	private Double sup;

	private String prefTel;

	private String codfiscale;

	private String tipostrada;

	private String nomestrada;

	private String numerocivico;

	private String localita;

	private BigDecimal indicestradario;

	private String denAtoRifTosc;

	public ComuniItalia() {
	}

	public ComuniItalia(ComuniItaliaId id) {
		this.id = id;
	}

	public ComuniItalia(ComuniItaliaId id, String kcomune, Double abitanti, String siglaprov, String siglareg, String zona,
			String ordineZona, String regione, String istat, String provincia, String comune, String atoRifTosc, String codsel,
			String densel, String codselquad, String denselquad, String diptoArpat, String codMinFinanze, Double estGbFoCentroide,
			Double nordGbFoCentroide, String comuneMin, String cap, Double sup, String prefTel, String codfiscale, String tipostrada,
			String nomestrada, String numerocivico, String localita, BigDecimal indicestradario, String denAtoRifTosc) {
		this.id = id;
		this.kcomune = kcomune;
		this.abitanti = abitanti;
		this.siglaprov = siglaprov;
		this.siglareg = siglareg;
		this.zona = zona;
		this.ordineZona = ordineZona;
		this.regione = regione;
		this.istat = istat;
		this.provincia = provincia;
		this.comune = comune;
		this.atoRifTosc = atoRifTosc;
		this.codsel = codsel;
		this.densel = densel;
		this.codselquad = codselquad;
		this.denselquad = denselquad;
		this.diptoArpat = diptoArpat;
		this.codMinFinanze = codMinFinanze;
		this.estGbFoCentroide = estGbFoCentroide;
		this.nordGbFoCentroide = nordGbFoCentroide;
		this.comuneMin = comuneMin;
		this.cap = cap;
		this.sup = sup;
		this.prefTel = prefTel;
		this.codfiscale = codfiscale;
		this.tipostrada = tipostrada;
		this.nomestrada = nomestrada;
		this.numerocivico = numerocivico;
		this.localita = localita;
		this.indicestradario = indicestradario;
		this.denAtoRifTosc = denAtoRifTosc;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "istatReg", column = @Column(name = "ISTAT_REG", nullable = false, length = 2)),
			@AttributeOverride(name = "istatProv", column = @Column(name = "ISTAT_PROV", nullable = false, length = 3)),
			@AttributeOverride(name = "istatCom", column = @Column(name = "ISTAT_COM", nullable = false, length = 3)) })
	public ComuniItaliaId getId() {
		return this.id;
	}

	public void setId(ComuniItaliaId id) {
		this.id = id;
	}

	@Column(name = "KCOMUNE", length = 6)
	public String getKcomune() {
		return this.kcomune;
	}

	public void setKcomune(String kcomune) {
		this.kcomune = kcomune;
	}

	@Column(name = "ABITANTI", precision = 126, scale = 0)
	public Double getAbitanti() {
		return this.abitanti;
	}

	public void setAbitanti(Double abitanti) {
		this.abitanti = abitanti;
	}

	@Column(name = "SIGLAPROV", length = 12)
	public String getSiglaprov() {
		return this.siglaprov;
	}

	public void setSiglaprov(String siglaprov) {
		this.siglaprov = siglaprov;
	}

	@Column(name = "SIGLAREG", length = 10)
	public String getSiglareg() {
		return this.siglareg;
	}

	public void setSiglareg(String siglareg) {
		this.siglareg = siglareg;
	}

	@Column(name = "ZONA", length = 6)
	public String getZona() {
		return this.zona;
	}

	public void setZona(String zona) {
		this.zona = zona;
	}

	@Column(name = "ORDINE_ZONA", length = 3)
	public String getOrdineZona() {
		return this.ordineZona;
	}

	public void setOrdineZona(String ordineZona) {
		this.ordineZona = ordineZona;
	}

	@Column(name = "REGIONE", length = 50)
	public String getRegione() {
		return this.regione;
	}

	public void setRegione(String regione) {
		this.regione = regione;
	}

	@Column(name = "ISTAT", length = 9)
	public String getIstat() {
		return this.istat;
	}

	public void setIstat(String istat) {
		this.istat = istat;
	}

	@Column(name = "PROVINCIA", length = 50)
	public String getProvincia() {
		return this.provincia;
	}

	public void setProvincia(String provincia) {
		this.provincia = provincia;
	}

	@Column(name = "COMUNE", length = 75)
	public String getComune() {
		return this.comune;
	}

	public void setComune(String comune) {
		this.comune = comune;
	}

	@Column(name = "ATO_RIF_TOSC", length = 2)
	public String getAtoRifTosc() {
		return this.atoRifTosc;
	}

	public void setAtoRifTosc(String atoRifTosc) {
		this.atoRifTosc = atoRifTosc;
	}

	@Column(name = "CODSEL", length = 2)
	public String getCodsel() {
		return this.codsel;
	}

	public void setCodsel(String codsel) {
		this.codsel = codsel;
	}

	@Column(name = "DENSEL", length = 26)
	public String getDensel() {
		return this.densel;
	}

	public void setDensel(String densel) {
		this.densel = densel;
	}

	@Column(name = "CODSELQUAD", length = 4)
	public String getCodselquad() {
		return this.codselquad;
	}

	public void setCodselquad(String codselquad) {
		this.codselquad = codselquad;
	}

	@Column(name = "DENSELQUAD", length = 33)
	public String getDenselquad() {
		return this.denselquad;
	}

	public void setDenselquad(String denselquad) {
		this.denselquad = denselquad;
	}

	@Column(name = "DIPTO_ARPAT", length = 30)
	public String getDiptoArpat() {
		return this.diptoArpat;
	}

	public void setDiptoArpat(String diptoArpat) {
		this.diptoArpat = diptoArpat;
	}

	@Column(name = "COD_MIN_FINANZE", length = 4)
	public String getCodMinFinanze() {
		return this.codMinFinanze;
	}

	public void setCodMinFinanze(String codMinFinanze) {
		this.codMinFinanze = codMinFinanze;
	}

	@Column(name = "EST_GB_FO_CENTROIDE", precision = 126, scale = 0)
	public Double getEstGbFoCentroide() {
		return this.estGbFoCentroide;
	}

	public void setEstGbFoCentroide(Double estGbFoCentroide) {
		this.estGbFoCentroide = estGbFoCentroide;
	}

	@Column(name = "NORD_GB_FO_CENTROIDE", precision = 126, scale = 0)
	public Double getNordGbFoCentroide() {
		return this.nordGbFoCentroide;
	}

	public void setNordGbFoCentroide(Double nordGbFoCentroide) {
		this.nordGbFoCentroide = nordGbFoCentroide;
	}

	@Column(name = "COMUNE_MIN", length = 75)
	public String getComuneMin() {
		return this.comuneMin;
	}

	public void setComuneMin(String comuneMin) {
		this.comuneMin = comuneMin;
	}

	@Column(name = "CAP", length = 50)
	public String getCap() {
		return this.cap;
	}

	public void setCap(String cap) {
		this.cap = cap;
	}

	@Column(name = "SUP", precision = 126, scale = 0)
	public Double getSup() {
		return this.sup;
	}

	public void setSup(Double sup) {
		this.sup = sup;
	}

	@Column(name = "PREF_TEL", length = 5)
	public String getPrefTel() {
		return this.prefTel;
	}

	public void setPrefTel(String prefTel) {
		this.prefTel = prefTel;
	}

	@Column(name = "CODFISCALE", length = 16)
	public String getCodfiscale() {
		return this.codfiscale;
	}

	public void setCodfiscale(String codfiscale) {
		this.codfiscale = codfiscale;
	}

	@Column(name = "TIPOSTRADA", length = 25)
	public String getTipostrada() {
		return this.tipostrada;
	}

	public void setTipostrada(String tipostrada) {
		this.tipostrada = tipostrada;
	}

	@Column(name = "NOMESTRADA", length = 50)
	public String getNomestrada() {
		return this.nomestrada;
	}

	public void setNomestrada(String nomestrada) {
		this.nomestrada = nomestrada;
	}

	@Column(name = "NUMEROCIVICO", length = 6)
	public String getNumerocivico() {
		return this.numerocivico;
	}

	public void setNumerocivico(String numerocivico) {
		this.numerocivico = numerocivico;
	}

	@Column(name = "LOCALITA", length = 50)
	public String getLocalita() {
		return this.localita;
	}

	public void setLocalita(String localita) {
		this.localita = localita;
	}

	@Column(name = "INDICESTRADARIO", precision = 38, scale = 0)
	public BigDecimal getIndicestradario() {
		return this.indicestradario;
	}

	public void setIndicestradario(BigDecimal indicestradario) {
		this.indicestradario = indicestradario;
	}

	@Column(name = "DEN_ATO_RIF_TOSC", length = 50)
	public String getDenAtoRifTosc() {
		return this.denAtoRifTosc;
	}

	public void setDenAtoRifTosc(String denAtoRifTosc) {
		this.denAtoRifTosc = denAtoRifTosc;
	}

}
