package it.eng.dm.sira.entity;

// Generated 20-nov-2014 16.32.27 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * DmtDictionaryEntries generated by hbm2java
 */
@Entity
@Table(name = "DMT_DICTIONARY_ENTRIES")
public class DmtDictionaryEntries implements java.io.Serializable {

	private String dictionaryEntry;

	private DmtDictionaryEntries dmtDictionaryEntries;

	private String meaning;

	private String codApplOwner;

	private String codIstApplOwner;

	public DmtDictionaryEntries() {
	}

	public DmtDictionaryEntries(String dictionaryEntry, String meaning) {
		this.dictionaryEntry = dictionaryEntry;
		this.meaning = meaning;
	}

	public DmtDictionaryEntries(String dictionaryEntry, DmtDictionaryEntries dmtDictionaryEntries, String meaning, String codApplOwner,
			String codIstApplOwner, Set<DmtDictionaryEntries> dmtDictionaryEntrieses, Set<DmtDizionario> dmtDizionarios) {
		this.dictionaryEntry = dictionaryEntry;
		this.dmtDictionaryEntries = dmtDictionaryEntries;
		this.meaning = meaning;
		this.codApplOwner = codApplOwner;
		this.codIstApplOwner = codIstApplOwner;
	}

	@Id
	@Column(name = "DICTIONARY_ENTRY", unique = true, nullable = false, length = 30)
	public String getDictionaryEntry() {
		return this.dictionaryEntry;
	}

	public void setDictionaryEntry(String dictionaryEntry) {
		this.dictionaryEntry = dictionaryEntry;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DETT_DI_DICT_ENTRY")
	public DmtDictionaryEntries getDmtDictionaryEntries() {
		return this.dmtDictionaryEntries;
	}

	public void setDmtDictionaryEntries(DmtDictionaryEntries dmtDictionaryEntries) {
		this.dmtDictionaryEntries = dmtDictionaryEntries;
	}

	@Column(name = "MEANING", nullable = false, length = 250)
	public String getMeaning() {
		return this.meaning;
	}

	public void setMeaning(String meaning) {
		this.meaning = meaning;
	}

	@Column(name = "COD_APPL_OWNER", length = 30)
	public String getCodApplOwner() {
		return this.codApplOwner;
	}

	public void setCodApplOwner(String codApplOwner) {
		this.codApplOwner = codApplOwner;
	}

	@Column(name = "COD_IST_APPL_OWNER", length = 30)
	public String getCodIstApplOwner() {
		return this.codIstApplOwner;
	}

	public void setCodIstApplOwner(String codIstApplOwner) {
		this.codIstApplOwner = codIstApplOwner;
	}
}
