package it.eng.dm.sira.entity;

// Generated 20-mar-2015 17.59.26 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * DmtProcessTypeEvents generated by hbm2java
 */
@Entity
@Table(name = "DMT_PROCESS_TYPE_EVENTS")
public class DmtProcessTypeEvents implements java.io.Serializable {

	private DmtProcessTypeEventsId id;
	private DmtProcessTypes dmtProcessTypes;
	private DmtEventTypes dmtEventTypes;
	private BigDecimal nroPosizione;
	private Boolean flgLocked;
	private Date tsIns;
	private BigDecimal idUserIns;
	private Date tsLastUpd;
	private BigDecimal idUserLastUpd;

	public DmtProcessTypeEvents() {
	}

	public DmtProcessTypeEvents(DmtProcessTypeEventsId id,
			DmtProcessTypes dmtProcessTypes, DmtEventTypes dmtEventTypes,
			BigDecimal nroPosizione) {
		this.id = id;
		this.dmtProcessTypes = dmtProcessTypes;
		this.dmtEventTypes = dmtEventTypes;
		this.nroPosizione = nroPosizione;
	}

	public DmtProcessTypeEvents(DmtProcessTypeEventsId id,
			DmtProcessTypes dmtProcessTypes, DmtEventTypes dmtEventTypes,
			BigDecimal nroPosizione, Boolean flgLocked,
			Date tsIns, BigDecimal idUserIns, Date tsLastUpd,
			BigDecimal idUserLastUpd) {
		this.id = id;
		this.dmtProcessTypes = dmtProcessTypes;
		this.dmtEventTypes = dmtEventTypes;
		this.nroPosizione = nroPosizione;
		this.flgLocked = flgLocked;
		this.tsIns = tsIns;
		this.idUserIns = idUserIns;
		this.tsLastUpd = tsLastUpd;
		this.idUserLastUpd = idUserLastUpd;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "idProcessType", column = @Column(name = "ID_PROCESS_TYPE", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "idEventType", column = @Column(name = "ID_EVENT_TYPE", nullable = false, precision = 22, scale = 0)) })
	public DmtProcessTypeEventsId getId() {
		return this.id;
	}

	public void setId(DmtProcessTypeEventsId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_PROCESS_TYPE", nullable = false, insertable = false, updatable = false)
	public DmtProcessTypes getDmtProcessTypes() {
		return this.dmtProcessTypes;
	}

	public void setDmtProcessTypes(DmtProcessTypes dmtProcessTypes) {
		this.dmtProcessTypes = dmtProcessTypes;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_EVENT_TYPE", nullable = false, insertable = false, updatable = false)
	public DmtEventTypes getDmtEventTypes() {
		return this.dmtEventTypes;
	}

	public void setDmtEventTypes(DmtEventTypes dmtEventTypes) {
		this.dmtEventTypes = dmtEventTypes;
	}

	@Column(name = "NRO_POSIZIONE", nullable = false, precision = 22, scale = 0)
	public BigDecimal getNroPosizione() {
		return this.nroPosizione;
	}

	public void setNroPosizione(BigDecimal nroPosizione) {
		this.nroPosizione = nroPosizione;
	}

	@Column(name = "FLG_LOCKED", precision = 1, scale = 0)
	public Boolean getFlgLocked() {
		return this.flgLocked;
	}

	public void setFlgLocked(Boolean flgLocked) {
		this.flgLocked = flgLocked;
	}

	@Column(name = "TS_INS", length = 7)
	public Date getTsIns() {
		return this.tsIns;
	}

	public void setTsIns(Date tsIns) {
		this.tsIns = tsIns;
	}

	@Column(name = "ID_USER_INS", precision = 22, scale = 0)
	public BigDecimal getIdUserIns() {
		return this.idUserIns;
	}

	public void setIdUserIns(BigDecimal idUserIns) {
		this.idUserIns = idUserIns;
	}

	@Column(name = "TS_LAST_UPD", length = 7)
	public Date getTsLastUpd() {
		return this.tsLastUpd;
	}

	public void setTsLastUpd(Date tsLastUpd) {
		this.tsLastUpd = tsLastUpd;
	}

	@Column(name = "ID_USER_LAST_UPD", precision = 22, scale = 0)
	public BigDecimal getIdUserLastUpd() {
		return this.idUserLastUpd;
	}

	public void setIdUserLastUpd(BigDecimal idUserLastUpd) {
		this.idUserLastUpd = idUserLastUpd;
	}

}
