package it.eng.dm.sira.entity;

// Generated 16-giu-2015 15.59.51 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * TAttributesFilter generated by hbm2java
 */
@Entity
@Table(name = "T_ATTRIBUTES_FILTER")
public class TAttributesFilter implements java.io.Serializable {

	private TAttributesFilterId id;

	private String flgStatus;

	private Date tsIns;

	private BigDecimal idUserIns;

	private Date tsLastUpd;

	private BigDecimal idUserLastUpd;

	private String flgProv;

	public TAttributesFilter() {
	}

	public TAttributesFilter(TAttributesFilterId id, String flgStatus, String flgProv) {
		this.id = id;
		this.flgStatus = flgStatus;
		this.flgProv = flgProv;
	}

	public TAttributesFilter(TAttributesFilterId id, String flgStatus, Date tsIns, BigDecimal idUserIns, Date tsLastUpd,
			BigDecimal idUserLastUpd, String flgProv) {
		this.id = id;
		this.flgStatus = flgStatus;
		this.tsIns = tsIns;
		this.idUserIns = idUserIns;
		this.tsLastUpd = tsLastUpd;
		this.idUserLastUpd = idUserLastUpd;
		this.flgProv = flgProv;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "idProcessType", column = @Column(name = "ID_PROCESS_TYPE", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "attrName", column = @Column(name = "ATTR_NAME", nullable = false, length = 250)),
			@AttributeOverride(name = "flgAnn", column = @Column(name = "FLG_ANN", nullable = false, length = 1)) })
	public TAttributesFilterId getId() {
		return this.id;
	}

	public void setId(TAttributesFilterId id) {
		this.id = id;
	}

	@Column(name = "FLG_STATUS", nullable = false, length = 1)
	public String getFlgStatus() {
		return this.flgStatus;
	}

	public void setFlgStatus(String flgStatus) {
		this.flgStatus = flgStatus;
	}

	@Column(name = "TS_INS", length = 7)
	public Date getTsIns() {
		return this.tsIns;
	}

	public void setTsIns(Date tsIns) {
		this.tsIns = tsIns;
	}

	@Column(name = "ID_USER_INS", precision = 22, scale = 0)
	public BigDecimal getIdUserIns() {
		return this.idUserIns;
	}

	public void setIdUserIns(BigDecimal idUserIns) {
		this.idUserIns = idUserIns;
	}

	@Column(name = "TS_LAST_UPD", length = 7)
	public Date getTsLastUpd() {
		return this.tsLastUpd;
	}

	public void setTsLastUpd(Date tsLastUpd) {
		this.tsLastUpd = tsLastUpd;
	}

	@Column(name = "ID_USER_LAST_UPD", precision = 22, scale = 0)
	public BigDecimal getIdUserLastUpd() {
		return this.idUserLastUpd;
	}

	public void setIdUserLastUpd(BigDecimal idUserLastUpd) {
		this.idUserLastUpd = idUserLastUpd;
	}

	@Column(name = "FLG_PROV", nullable = false, length = 2)
	public String getFlgProv() {
		return this.flgProv;
	}

	public void setFlgProv(String flgProv) {
		this.flgProv = flgProv;
	}

}
