package it.eng.dm.sira.entity;

// Generated 12-nov-2014 15.35.36 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * VMguOrganigramma generated by hbm2java
 */
@Entity
@Table(name = "V_MGU_ORGANIGRAMMA")
public class VMguOrganigramma implements java.io.Serializable {
	
	private String settorePadre;

	private Long idPadre;

	private Long dominio;

	private String descrizione;

	private Date dtInizio;

	private Date dtFine;

	private String stato;
	
	private String livello;
	
	public VMguOrganigramma() {
	}

	@Column(name = "ID_PADRE", precision = 11, scale = 0)
	public Long getIdPadre() {
		return this.idPadre;
	}

	public void setIdPadre(Long idPadre) {
		this.idPadre = idPadre;
	}
	
	@Id
	@Column(name = "DOMINIO", nullable = false, precision = 11, scale = 0)
	public Long getDominio() {
		return this.dominio;
	}

	public void setDominio(Long dominio) {
		this.dominio = dominio;
	}

	@Column(name = "DESCRIZIONE", nullable = false, length = 500)
	public String getDescrizione() {
		return this.descrizione;
	}

	public void setDescrizione(String descrizione) {
		this.descrizione = descrizione;
	}

	@Column(name = "DT_INIZIO", length = 7)
	public Date getDtInizio() {
		return this.dtInizio;
	}

	public void setDtInizio(Date dtInizio) {
		this.dtInizio = dtInizio;
	}

	@Column(name = "DT_FINE", length = 7)
	public Date getDtFine() {
		return this.dtFine;
	}

	public void setDtFine(Date dtFine) {
		this.dtFine = dtFine;
	}

	@Column(name = "STATO", nullable = false, length = 32)
	public String getStato() {
		return this.stato;
	}

	public void setStato(String stato) {
		this.stato = stato;
	}
	
	@Column(name = "LIVELLO", length = 6)
	public String getLivello() {
		return this.livello;
	}

	public void setLivello(String livello) {
		this.livello = livello;
	}
	
	@Transient
	public String getSettorePadre() {
		return settorePadre;
	}

	public void setSettorePadre(String settorePadre) {
		this.settorePadre = settorePadre;
	}


}
