package it.eng.dm.sira.entity;

// Generated 25-nov-2014 17.11.46 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * VVocTipoAda generated by hbm2java
 */
@Entity
@Table(name = "V_VOC_TIPO_ADA")
public class VVocTipoAda implements java.io.Serializable {

	private BigDecimal codice;

	private String descrizione;

	private BigDecimal blocco;

	private BigDecimal attivo;

	public VVocTipoAda() {
	}
	
	@Id
	@Column(name = "CODICE", nullable = false, precision = 22, scale = 0)
	public BigDecimal getCodice() {
		return this.codice;
	}

	public void setCodice(BigDecimal codice) {
		this.codice = codice;
	}

	@Column(name = "DESCRIZIONE", length = 4000)
	public String getDescrizione() {
		return this.descrizione;
	}

	public void setDescrizione(String descrizione) {
		this.descrizione = descrizione;
	}

	@Column(name = "BLOCCO", precision = 22, scale = 0)
	public BigDecimal getBlocco() {
		return this.blocco;
	}

	public void setBlocco(BigDecimal blocco) {
		this.blocco = blocco;
	}

	@Column(name = "ATTIVO", precision = 22, scale = 0)
	public BigDecimal getAttivo() {
		return this.attivo;
	}

	public void setAttivo(BigDecimal attivo) {
		this.attivo = attivo;
	}

}
