/* * SPDX-License-Identifier: AGPL-3.0-or-later * * C Copyright 2023 Regione Piemonte * */
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-b10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.11.29 at 11:33:13 AM CET 
//


package it.eng.auriga.repository2.jaxws.webservices.A2A.utente.bean;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Utente" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Cid" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Cognome" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Nome" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Attivo" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                   &lt;element name="DataAttivazione" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *                   &lt;element name="DataCessazione" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *                   &lt;element name="CodQualifica" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="DesQualifica" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="IndirizzoEmailAziendale" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="InOrganigramma">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="PosizioneInOrganigramma" maxOccurs="unbounded" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="CidNodoOrganigramma" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="FlgRelazionePrimaria" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *                                       &lt;element name="DataInizio" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *                                       &lt;element name="DataFine" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *                                       &lt;element name="NomeBusinessUnit" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                                       &lt;element name="Sede" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="Modalita" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;pattern value="completa"/>
 *             &lt;pattern value="incrementale"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "utente"
})
@XmlRootElement(name = "Lista")
public class Lista {

    @XmlElement(name = "Utente")
    protected List<Lista.Utente> utente;
    @XmlAttribute(name = "Modalita", required = true)
    protected String modalita;

    /**
     * Gets the value of the utente property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the utente property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getUtente().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Lista.Utente }
     * 
     * 
     */
    public List<Lista.Utente> getUtente() {
        if (utente == null) {
            utente = new ArrayList<Lista.Utente>();
        }
        return this.utente;
    }

    /**
     * Gets the value of the modalita property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModalita() {
        return modalita;
    }

    /**
     * Sets the value of the modalita property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModalita(String value) {
        this.modalita = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Cid" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Cognome" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Nome" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Attivo" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *         &lt;element name="DataAttivazione" type="{http://www.w3.org/2001/XMLSchema}date"/>
     *         &lt;element name="DataCessazione" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
     *         &lt;element name="CodQualifica" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="DesQualifica" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="IndirizzoEmailAziendale" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="InOrganigramma">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="PosizioneInOrganigramma" maxOccurs="unbounded" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="CidNodoOrganigramma" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="FlgRelazionePrimaria" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
     *                             &lt;element name="DataInizio" type="{http://www.w3.org/2001/XMLSchema}date"/>
     *                             &lt;element name="DataFine" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
     *                             &lt;element name="NomeBusinessUnit" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                             &lt;element name="Sede" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "cid",
        "cognome",
        "nome",
        "attivo",
        "dataAttivazione",
        "dataCessazione",
        "codQualifica",
        "desQualifica",
        "indirizzoEmailAziendale",
        "inOrganigramma"
    })
    public static class Utente {

        @XmlElement(name = "Cid", required = true)
        protected String cid;
        @XmlElement(name = "Cognome", required = true)
        protected String cognome;
        @XmlElement(name = "Nome", required = true)
        protected String nome;
        @XmlElement(name = "Attivo")
        protected boolean attivo;
        @XmlElement(name = "DataAttivazione", required = true)
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar dataAttivazione;
        @XmlElement(name = "DataCessazione")
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar dataCessazione;
        @XmlElement(name = "CodQualifica")
        protected String codQualifica;
        @XmlElement(name = "DesQualifica")
        protected String desQualifica;
        @XmlElement(name = "IndirizzoEmailAziendale")
        protected String indirizzoEmailAziendale;
        @XmlElement(name = "InOrganigramma", required = true)
        protected Lista.Utente.InOrganigramma inOrganigramma;

        /**
         * Gets the value of the cid property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCid() {
            return cid;
        }

        /**
         * Sets the value of the cid property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCid(String value) {
            this.cid = value;
        }

        /**
         * Gets the value of the cognome property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCognome() {
            return cognome;
        }

        /**
         * Sets the value of the cognome property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCognome(String value) {
            this.cognome = value;
        }

        /**
         * Gets the value of the nome property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNome() {
            return nome;
        }

        /**
         * Sets the value of the nome property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNome(String value) {
            this.nome = value;
        }

        /**
         * Gets the value of the attivo property.
         * 
         */
        public boolean isAttivo() {
            return attivo;
        }

        /**
         * Sets the value of the attivo property.
         * 
         */
        public void setAttivo(boolean value) {
            this.attivo = value;
        }

        /**
         * Gets the value of the dataAttivazione property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getDataAttivazione() {
            return dataAttivazione;
        }

        /**
         * Sets the value of the dataAttivazione property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setDataAttivazione(XMLGregorianCalendar value) {
            this.dataAttivazione = value;
        }

        /**
         * Gets the value of the dataCessazione property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getDataCessazione() {
            return dataCessazione;
        }

        /**
         * Sets the value of the dataCessazione property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setDataCessazione(XMLGregorianCalendar value) {
            this.dataCessazione = value;
        }

        /**
         * Gets the value of the codQualifica property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCodQualifica() {
            return codQualifica;
        }

        /**
         * Sets the value of the codQualifica property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCodQualifica(String value) {
            this.codQualifica = value;
        }

        /**
         * Gets the value of the desQualifica property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDesQualifica() {
            return desQualifica;
        }

        /**
         * Sets the value of the desQualifica property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDesQualifica(String value) {
            this.desQualifica = value;
        }

        /**
         * Gets the value of the indirizzoEmailAziendale property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getIndirizzoEmailAziendale() {
            return indirizzoEmailAziendale;
        }

        /**
         * Sets the value of the indirizzoEmailAziendale property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setIndirizzoEmailAziendale(String value) {
            this.indirizzoEmailAziendale = value;
        }

        /**
         * Gets the value of the inOrganigramma property.
         * 
         * @return
         *     possible object is
         *     {@link Lista.Utente.InOrganigramma }
         *     
         */
        public Lista.Utente.InOrganigramma getInOrganigramma() {
            return inOrganigramma;
        }

        /**
         * Sets the value of the inOrganigramma property.
         * 
         * @param value
         *     allowed object is
         *     {@link Lista.Utente.InOrganigramma }
         *     
         */
        public void setInOrganigramma(Lista.Utente.InOrganigramma value) {
            this.inOrganigramma = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="PosizioneInOrganigramma" maxOccurs="unbounded" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="CidNodoOrganigramma" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="FlgRelazionePrimaria" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
         *                   &lt;element name="DataInizio" type="{http://www.w3.org/2001/XMLSchema}date"/>
         *                   &lt;element name="DataFine" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
         *                   &lt;element name="NomeBusinessUnit" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *                   &lt;element name="Sede" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "posizioneInOrganigramma"
        })
        public static class InOrganigramma {

            @XmlElement(name = "PosizioneInOrganigramma")
            protected List<Lista.Utente.InOrganigramma.PosizioneInOrganigramma> posizioneInOrganigramma;

            /**
             * Gets the value of the posizioneInOrganigramma property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the posizioneInOrganigramma property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getPosizioneInOrganigramma().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Lista.Utente.InOrganigramma.PosizioneInOrganigramma }
             * 
             * 
             */
            public List<Lista.Utente.InOrganigramma.PosizioneInOrganigramma> getPosizioneInOrganigramma() {
                if (posizioneInOrganigramma == null) {
                    posizioneInOrganigramma = new ArrayList<Lista.Utente.InOrganigramma.PosizioneInOrganigramma>();
                }
                return this.posizioneInOrganigramma;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="CidNodoOrganigramma" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="FlgRelazionePrimaria" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
             *         &lt;element name="DataInizio" type="{http://www.w3.org/2001/XMLSchema}date"/>
             *         &lt;element name="DataFine" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
             *         &lt;element name="NomeBusinessUnit" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
             *         &lt;element name="Sede" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "cidNodoOrganigramma",
                "flgRelazionePrimaria",
                "dataInizio",
                "dataFine",
                "nomeBusinessUnit",
                "sede"
            })
            public static class PosizioneInOrganigramma {

                @XmlElement(name = "CidNodoOrganigramma", required = true)
                protected String cidNodoOrganigramma;
                @XmlElement(name = "FlgRelazionePrimaria", defaultValue = "false")
                protected Boolean flgRelazionePrimaria;
                @XmlElement(name = "DataInizio", required = true)
                @XmlSchemaType(name = "date")
                protected XMLGregorianCalendar dataInizio;
                @XmlElement(name = "DataFine")
                @XmlSchemaType(name = "date")
                protected XMLGregorianCalendar dataFine;
                @XmlElement(name = "NomeBusinessUnit")
                protected String nomeBusinessUnit;
                @XmlElement(name = "Sede")
                protected String sede;

                /**
                 * Gets the value of the cidNodoOrganigramma property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getCidNodoOrganigramma() {
                    return cidNodoOrganigramma;
                }

                /**
                 * Sets the value of the cidNodoOrganigramma property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setCidNodoOrganigramma(String value) {
                    this.cidNodoOrganigramma = value;
                }

                /**
                 * Gets the value of the flgRelazionePrimaria property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Boolean }
                 *     
                 */
                public Boolean isFlgRelazionePrimaria() {
                    return flgRelazionePrimaria;
                }

                /**
                 * Sets the value of the flgRelazionePrimaria property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Boolean }
                 *     
                 */
                public void setFlgRelazionePrimaria(Boolean value) {
                    this.flgRelazionePrimaria = value;
                }

                /**
                 * Gets the value of the dataInizio property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link XMLGregorianCalendar }
                 *     
                 */
                public XMLGregorianCalendar getDataInizio() {
                    return dataInizio;
                }

                /**
                 * Sets the value of the dataInizio property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link XMLGregorianCalendar }
                 *     
                 */
                public void setDataInizio(XMLGregorianCalendar value) {
                    this.dataInizio = value;
                }

                /**
                 * Gets the value of the dataFine property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link XMLGregorianCalendar }
                 *     
                 */
                public XMLGregorianCalendar getDataFine() {
                    return dataFine;
                }

                /**
                 * Sets the value of the dataFine property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link XMLGregorianCalendar }
                 *     
                 */
                public void setDataFine(XMLGregorianCalendar value) {
                    this.dataFine = value;
                }

                /**
                 * Gets the value of the nomeBusinessUnit property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getNomeBusinessUnit() {
                    return nomeBusinessUnit;
                }

                /**
                 * Sets the value of the nomeBusinessUnit property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setNomeBusinessUnit(String value) {
                    this.nomeBusinessUnit = value;
                }

                /**
                 * Gets the value of the sede property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getSede() {
                    return sede;
                }

                /**
                 * Sets the value of the sede property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setSede(String value) {
                    this.sede = value;
                }

            }

        }

    }

}
