// 
// Decompiled by Procyon v0.5.36
// 

package org.apache.batik.apps.svgbrowser;

import java.lang.reflect.Field;
import java.util.HashMap;
import java.util.ArrayList;
import java.util.Map;

public class NodeTemplates
{
    public static final String VALUE = "Value";
    public static final String NAME = "Name";
    public static final String TYPE = "Type";
    public static final String DESCRIPTION = "Description";
    public static final String CATEGORY = "Category";
    public static final String BASIC_SHAPES = "Basic Shapes";
    public static final String LINKING = "Linking";
    public static final String TEXT = "Text";
    public static final String ANIMATION = "Animation";
    public static final String CLIP_MASK_COMPOSITE = "Clipping, Masking and Compositing";
    public static final String COLOR = "Color";
    public static final String INTERACTIVITY = "Interactivity";
    public static final String FONTS = "Fonts";
    public static final String DOCUMENT_STRUCTURE = "Document Structure";
    public static final String FILTER_EFFECTS = "Filter Effects";
    public static final String EXTENSIBILITY = "Extensibility";
    public static final String GRADIENTS_AND_PATTERNS = "Gradients and Patterns";
    public static final String PAINTING = "Painting: Filling, Stroking and Marker Symbols";
    public static final String METADATA = "Metadata";
    public static final String PATHS = "Paths";
    public static final String SCRIPTING = "Scripting";
    public static final String STYLING = "Styling";
    private Map nodeTemplatesMap;
    private ArrayList categoriesList;
    public static String rectMemberName;
    public static String rectElementValue;
    public static String rectElementName;
    public static short rectElementType;
    public static String rectElementCategory;
    public static String rectElementDescription;
    public static String circleMemberName;
    public static String circleElementValue;
    public static String circleElementName;
    public short circleElementType;
    public static String circleElementCategory;
    public static String circleElementDescription;
    public static String lineElementMemberName;
    public static String lineElementName;
    public static String lineElementValue;
    public static short lineElementType;
    public static String lineElementCategory;
    public static String lineElementDescription;
    public static String pathElementMemberName;
    public static String pathElementName;
    public static String pathElementValue;
    public static short pathElementType;
    public static String pathElementCategory;
    public static String pathElementDescription;
    public static String groupElementMemberName;
    public static String groupElementName;
    public static String groupElementValue;
    public static short groupElementType;
    public static String groupElementCategory;
    public static String groupElementDescription;
    public static String ellipseElementMemberName;
    public static String ellipseElementName;
    public static String ellipseElementValue;
    public static short ellipseElementType;
    public static String ellipseElementCategory;
    public static String ellipseElementDescription;
    public static String imageElementMemberName;
    public static String imageElementName;
    public static String imageElementValue;
    public static short imageElementType;
    public static String imageElementCategory;
    public static String imageElementDescription;
    public static String polygonElementMemberName;
    public static String polygonElementName;
    public static String polygonElementValue;
    public static short polygonElementType;
    public static String polygonElementCategory;
    public static String polygonElementDescription;
    public static String polylineElementMemberName;
    public static String polylineElementName;
    public static String polylineElementValue;
    public static short polylineElementType;
    public static String polylineElementCategory;
    public static String polylineElementDescription;
    public static String textElementMemberName;
    public static String textElementName;
    public static String textElementValue;
    public static short textElementType;
    public static String textElementCategory;
    public static String textElementDescription;
    public static String tRefElementMemberName;
    public static String tRefElementName;
    public static String tRefElementValue;
    public static short tRefElementType;
    public static String tRefElementCategory;
    public static String tRefElementDescription;
    public static String tspanElementMemberName;
    public static String tspanElementName;
    public static String tspanElementValue;
    public static short tspanElementType;
    public static String tspanElementCategory;
    public static String tspanElementDescription;
    public static String textPathElementMemberName;
    public static String textPathElementName;
    public static String textPathElementValue;
    public static short textPathElementType;
    public static String textPathElementCategory;
    public static String textPathElementDescription;
    public static String svgElementMemberName;
    public static String svgElementName;
    public static String svgElementValue;
    public static short svgElementType;
    public static String svgElementCategory;
    public static String svgElementDescription;
    public static String feBlendElementMemberName;
    public static String feBlendElementName;
    public static String feBlendElementValue;
    public static short feBlendElementType;
    public static String feBlendElementCategory;
    public static String feBlendElementDescription;
    public static String feColorMatrixElementMemberName;
    public static String feColorMatrixElementName;
    public static String feColorMatrixElementValue;
    public static short feColorMatrixElementType;
    public static String feColorMatrixElementCategory;
    public static String feColorMatrixElementDescription;
    public static String feComponentTransferElementMemberName;
    public static String feComponentTransferElementName;
    public static String feComponentTransferElementValue;
    public static short feComponentTransferElementType;
    public static String feComponentTransferElementCategory;
    public static String feComponentTransferElementDescription;
    public static String feCompositeElementMemberName;
    public static String feCompositeElementName;
    public static String feCompositeElementValue;
    public static short feCompositeElementType;
    public static String feCompositeElementCategory;
    public static String feCompositeElementDescription;
    public static String feConvolveMatrixElementMemberName;
    public static String feConvolveMatrixElementName;
    public static String feConvolveMatrixElementValue;
    public static short feConvolveMatrixElementType;
    public static String feConvolveMatrixElementCategory;
    public static String feConvolveMatrixElementDescription;
    public static String feDiffuseLightingElementMemberName;
    public static String feDiffuseLightingElementName;
    public static String feDiffuseLightingElementValue;
    public static short feDiffuseLightingElementType;
    public static String feDiffuseLightingElementCategory;
    public static String feDiffuseLightingElementDescription;
    public static String feDisplacementMapElementMemberName;
    public static String feDisplacementMapElementName;
    public static String feDisplacementMapElementValue;
    public static short feDisplacementMapElementType;
    public static String feDisplacementMapElementCategory;
    public static String feDisplacementMapElementDescription;
    public static String feDistantLightElementMemberName;
    public static String feDistantLightElementName;
    public static String feDistantLightElementValue;
    public static short feDistantLightElementType;
    public static String feDistantLightElementCategory;
    public static String feDistantLightElementDescription;
    public static String feFloodElementMemberName;
    public static String feFloodElementName;
    public static String feFloodElementValue;
    public static short feFloodElementType;
    public static String feFloodElementCategory;
    public static String feFloodElementDescription;
    public static String feFuncAElementMemberName;
    public static String feFuncAElementName;
    public static String feFuncAElementValue;
    public static short feFuncAElementType;
    public static String feFuncAElementCategory;
    public static String feFuncAElementDescription;
    public static String feFuncBElementMemberName;
    public static String feFuncBElementName;
    public static String feFuncBElementValue;
    public static short feFuncBElementType;
    public static String feFuncBElementCategory;
    public static String feFuncBElementDescription;
    public static String feFuncGElementMemberName;
    public static String feFuncGElementName;
    public static String feFuncGElementValue;
    public static short feFuncGElementType;
    public static String feFuncGElementCategory;
    public static String feFuncGElementDescription;
    public static String feFuncRElementMemberName;
    public static String feFuncRElementName;
    public static String feFuncRElementValue;
    public static short feFuncRElementType;
    public static String feFuncRElementCategory;
    public static String feFuncRElementDescription;
    public static String feGaussianBlurElementMemberName;
    public static String feGaussianBlurElementName;
    public static String feGaussianBlurElementValue;
    public static short feGaussianBlurElementType;
    public static String feGaussianBlurElementCategory;
    public static String feGaussianBlurElementDescription;
    public static String feImageElementMemberName;
    public static String feImageElementName;
    public static String feImageElementValue;
    public static short feImageElementType;
    public static String feImageElementCategory;
    public static String feImageElementDescription;
    public static String feMergeElementMemberName;
    public static String feMergeElementName;
    public static String feMergeElementValue;
    public static short feMergeElementType;
    public static String feMergeElementCategory;
    public static String feMergeElementDescription;
    public static String feMergeNodeElementMemberName;
    public static String feMergeNodeElementName;
    public static String feMergeNodeElementValue;
    public static short feMergeNodeElementType;
    public static String feMergeNodeElementCategory;
    public static String feMergeNodeElementDescription;
    public static String feMorphologyElementMemberName;
    public static String feMorphologyElementName;
    public static String feMorphologyElementValue;
    public static short feMorphologyElementType;
    public static String feMorphologyElementCategory;
    public static String feMorphologyElementDescription;
    public static String feOffsetElementMemberName;
    public static String feOffsetElementName;
    public static String feOffsetElementValue;
    public static short feOffsetElementType;
    public static String feOffsetElementCategory;
    public static String feOffsetElementDescription;
    public static String fePointLightElementMemberName;
    public static String fePointLightElementName;
    public static String fePointLightElementValue;
    public static short fePointLightElementType;
    public static String fePointLightElementCategory;
    public static String fePointLightElementDescription;
    public static String feSpecularLightingElementMemberName;
    public static String feSpecularLightingElementName;
    public static String feSpecularLightingElementValue;
    public static short feSpecularLightingElementType;
    public static String feSpecularLightingElementCategory;
    public static String feSpecularLightingElementDescription;
    public static String feSpotLightElementMemberName;
    public static String feSpotLightElementName;
    public static String feSpotLightElementValue;
    public static short feSpotLightElementType;
    public static String feSpotLightElementCategory;
    public static String feSpotLightElementDescription;
    public static String feTileElementMemberName;
    public static String feTileElementName;
    public static String feTileElementValue;
    public static short feTileElementType;
    public static String feTileElementCategory;
    public static String feTileElementDescription;
    public static String feTurbulenceElementMemberName;
    public static String feTurbulenceElementName;
    public static String feTurbulenceElementValue;
    public static short feTurbulenceElementType;
    public static String feTurbulenceElementCategory;
    public static String feTurbulenceElementDescription;
    public static String filterElementMemberName;
    public static String filterElementName;
    public static String filterElementValue;
    public static short filterElementType;
    public static String filterElementCategory;
    public static String filterElementDescription;
    public static String aElementMemberName;
    public static String aElementName;
    public static String aElementValue;
    public static short aElementType;
    public static String aElementCategory;
    public static String aElementDescription;
    public static String altGlyphElementMemberName;
    public static String altGlyphElementName;
    public static String altGlyphElementValue;
    public static short altGlyphElementType;
    public static String altGlyphElementCategory;
    public static String altGlyphElementDescription;
    public static String altGlyphDefElementMemberName;
    public static String altGlyphDefElementName;
    public static String altGlyphDefElementValue;
    public static short altGlyphDefElementType;
    public static String altGlyphDefElementCategory;
    public static String altGlyphDefElementDescription;
    public static String altGlyphItemElementMemberName;
    public static String altGlyphItemElementName;
    public static String altGlyphItemElementValue;
    public static short altGlyphItemElementType;
    public static String altGlyphItemElementCategory;
    public static String altGlyphItemElementDescription;
    public static String clipPathElementMemberName;
    public static String clipPathElementName;
    public static String clipPathElementValue;
    public static short clipPathElementType;
    public static String clipPathElementCategory;
    public static String clipPathElementDescription;
    public static String colorProfileElementMemberName;
    public static String colorProfileElementName;
    public static String colorProfileElementValue;
    public static short colorProfileElementType;
    public static String colorProfileElementCategory;
    public static String colorProfileElementDescription;
    public static String cursorElementMemberName;
    public static String cursorElementName;
    public static String cursorElementValue;
    public static short cursorElementType;
    public static String cursorElementCategory;
    public static String cursorElementDescription;
    public static String definitionSrcElementMemberName;
    public static String definitionSrcElementName;
    public static String definitionSrcElementValue;
    public static short definitionSrcElementType;
    public static String definitionSrcElementCategory;
    public static String definitionSrcElementDescription;
    public static String defsElementMemberName;
    public static String defsElementName;
    public static String defsElementValue;
    public static short defsElementType;
    public static String defsElementCategory;
    public static String defsElementDescription;
    public static String descElementMemberName;
    public static String descElementName;
    public static String descElementValue;
    public static short descElementType;
    public static String descElementCategory;
    public static String descElementDescription;
    public static String foreignObjectElementMemberName;
    public static String foreignObjectElementName;
    public static String foreignObjectElementValue;
    public static short foreignObjectElementType;
    public static String foreignObjectElementCategory;
    public static String foreignObjectElementDescription;
    public static String glyphElementMemberName;
    public static String glyphElementName;
    public static String glyphElementValue;
    public static short glyphElementType;
    public static String glyphElementCategory;
    public static String glyphElementDescription;
    public static String glyphRefElementMemberName;
    public static String glyphRefElementName;
    public static String glyphRefElementValue;
    public static short glyphRefElementType;
    public static String glyphRefElementCategory;
    public static String glyphRefElementDescription;
    public static String hkernElementMemberName;
    public static String hkernElementName;
    public static String hkernElementValue;
    public static short hkernElementType;
    public static String hkernElementCategory;
    public static String hkernElementDescription;
    public static String linearGradientElementMemberName;
    public static String linearGradientElementName;
    public static String linearGradientElementValue;
    public static short linearGradientElementType;
    public static String linearGradientElementCategory;
    public static String linearGradientElementDescription;
    public static String markerElementMemberName;
    public static String markerElementName;
    public static String markerElementValue;
    public static short markerElementType;
    public static String markerElementCategory;
    public static String markerElementDescription;
    public static String maskElementMemberName;
    public static String maskElementName;
    public static String maskElementValue;
    public static short maskElementType;
    public static String maskElementCategory;
    public static String maskElementDescription;
    public static String metadataElementMemberName;
    public static String metadataElementName;
    public static String metadataElementValue;
    public static short metadataElementType;
    public static String metadataElementCategory;
    public static String metadataElementDescription;
    public static String missingGlyphElementMemberName;
    public static String missingGlyphElementName;
    public static String missingGlyphElementValue;
    public static short missingGlyphElementType;
    public static String missingGlyphElementCategory;
    public static String missingGlyphElementDescription;
    public static String mpathElementMemberName;
    public static String mpathElementName;
    public static String mpathElementValue;
    public static short mpathElementType;
    public static String mpathElementCategory;
    public static String mpathElementDescription;
    public static String patternElementMemberName;
    public static String patternElementName;
    public static String patternElementValue;
    public static short patternElementType;
    public static String patternElementCategory;
    public static String patternElementDescription;
    public static String radialGradientElementMemberName;
    public static String radialGradientElementName;
    public static String radialGradientElementValue;
    public static short radialGradientElementType;
    public static String radialGradientElementCategory;
    public static String radialGradientElementDescription;
    public static String scriptElementMemberName;
    public static String scriptElementName;
    public static String scriptElementValue;
    public static short scriptElementType;
    public static String scriptElementCategory;
    public static String scriptElementDescription;
    public static String setElementMemberName;
    public static String setElementName;
    public static String setElementValue;
    public static short setElementType;
    public static String setElementCategory;
    public static String setElementDescription;
    public static String stopElementMemberName;
    public static String stopElementName;
    public static String stopElementValue;
    public static short stopElementType;
    public static String stopElementCategory;
    public static String stopElementDescription;
    public static String styleElementMemberName;
    public static String styleElementName;
    public static String styleElementValue;
    public static short styleElementType;
    public static String styleElementCategory;
    public static String styleElementDescription;
    public static String switchElementMemberName;
    public static String switchElementName;
    public static String switchElementValue;
    public static short switchElementType;
    public static String switchElementCategory;
    public static String switchElementDescription;
    public static String symbolElementMemberName;
    public static String symbolElementName;
    public static String symbolElementValue;
    public static short symbolElementType;
    public static String symbolElementCategory;
    public static String symbolElementDescription;
    public static String titleElementMemberName;
    public static String titleElementName;
    public static String titleElementValue;
    public static short titleElementType;
    public static String titleElementCategory;
    public static String titleElementDescription;
    public static String useElementMemberName;
    public static String useElementName;
    public static String useElementValue;
    public static short useElementType;
    public static String useElementCategory;
    public static String useElementDescription;
    public static String viewElementMemberName;
    public static String viewElementName;
    public static String viewElementValue;
    public static short viewElementType;
    public static String viewElementCategory;
    public static String viewElementDescription;
    public static String vkernElementMemberName;
    public static String vkernElementName;
    public static String vkernElementValue;
    public static short vkernElementType;
    public static String vkernElementCategory;
    public static String vkernElementDescription;
    public static String fontElementMemberName;
    public static String fontElementName;
    public static String fontElementValue;
    public static short fontElementType;
    public static String fontElementCategory;
    public static String fontElementDescription;
    public static String fontFaceElementMemberName;
    public static String fontFaceElementName;
    public static String fontFaceElementValue;
    public static short fontFaceElementType;
    public static String fontFaceElementCategory;
    public static String fontFaceElementDescription;
    public static String fontFaceFormatElementMemberName;
    public static String fontFaceFormatElementName;
    public static String fontFaceFormatElementValue;
    public static short fontFaceFormatElementType;
    public static String fontFaceFormatElementCategory;
    public static String fontFaceFormatElementDescription;
    public static String fontFaceNameElementMemberName;
    public static String fontFaceNameElementName;
    public static String fontFaceNameElementValue;
    public static short fontFaceNameElementType;
    public static String fontFaceNameElementCategory;
    public static String fontFaceNameElementDescription;
    public static String fontFaceSrcElementMemberName;
    public static String fontFaceSrcElementName;
    public static String fontFaceSrcElementValue;
    public static short fontFaceSrcElementType;
    public static String fontFaceSrcElementCategory;
    public static String fontFaceSrcElementDescription;
    public static String fontFaceUriElementMemberName;
    public static String fontFaceUriElementName;
    public static String fontFaceUriElementValue;
    public static short fontFaceUriElementType;
    public static String fontFaceUriElementCategory;
    public static String fontFaceUriElementDescription;
    public static String animateElementMemberName;
    public static String animateElementName;
    public static String animateElementValue;
    public static short animateElementType;
    public static String animateElementCategory;
    public static String animateElementDescription;
    public static String animateColorElementMemberName;
    public static String animateColorElementName;
    public static String animateColorElementValue;
    public static short animateColorElementType;
    public static String animateColorElementCategory;
    public static String animateColorElementDescription;
    public static String animateMotionElementMemberName;
    public static String animateMotionElementName;
    public static String animateMotionElementValue;
    public static short animateMotionElementType;
    public static String animateMotionElementCategory;
    public static String animateMotionElementDescription;
    public static String animateTransformElementMemberName;
    public static String animateTransformElementName;
    public static String animateTransformElementValue;
    public static short animateTransformElementType;
    public static String animateTransformElementCategory;
    public static String animateTransformElementDescription;
    
    public NodeTemplates() {
        this.nodeTemplatesMap = new HashMap();
        this.categoriesList = new ArrayList();
        this.circleElementType = 1;
        this.categoriesList.add("Document Structure");
        this.categoriesList.add("Styling");
        this.categoriesList.add("Paths");
        this.categoriesList.add("Basic Shapes");
        this.categoriesList.add("Text");
        this.categoriesList.add("Painting: Filling, Stroking and Marker Symbols");
        this.categoriesList.add("Color");
        this.categoriesList.add("Gradients and Patterns");
        this.categoriesList.add("Clipping, Masking and Compositing");
        this.categoriesList.add("Filter Effects");
        this.categoriesList.add("Interactivity");
        this.categoriesList.add("Linking");
        this.categoriesList.add("Scripting");
        this.categoriesList.add("Animation");
        this.categoriesList.add("Fonts");
        this.categoriesList.add("Metadata");
        this.categoriesList.add("Extensibility");
        this.initializeTemplates();
    }
    
    private void initializeTemplates() {
        final Field[] declaredFields = this.getClass().getDeclaredFields();
        for (int i = 0; i < declaredFields.length; ++i) {
            final Field field = declaredFields[i];
            try {
                if (field.getType() == String.class && field.getName().endsWith("MemberName")) {
                    final boolean accessible = field.isAccessible();
                    field.setAccessible(true);
                    final String string = field.get(this).toString();
                    final NodeTemplateDescriptor nodeTemplateDescriptor = new NodeTemplateDescriptor(this.getClass().getField(string + "Name").get(this).toString(), this.getClass().getField(string + "Value").get(this).toString(), (short)this.getClass().getField(string + "Type").get(this), this.getClass().getField(string + "Category").get(this).toString(), this.getClass().getField(string + "Description").get(this).toString());
                    this.nodeTemplatesMap.put(nodeTemplateDescriptor.getName(), nodeTemplateDescriptor);
                    field.setAccessible(accessible);
                }
            }
            catch (IllegalArgumentException ex) {
                ex.printStackTrace();
            }
            catch (IllegalAccessException ex2) {
                ex2.printStackTrace();
            }
            catch (SecurityException ex3) {
                ex3.printStackTrace();
            }
            catch (NoSuchFieldException ex4) {
                ex4.printStackTrace();
            }
        }
    }
    
    public ArrayList getCategories() {
        return this.categoriesList;
    }
    
    public Map getNodeTemplatesMap() {
        return this.nodeTemplatesMap;
    }
    
    static {
        NodeTemplates.rectMemberName = "rectElement";
        NodeTemplates.rectElementValue = "<rect width=\"0\" height=\"0\"/>";
        NodeTemplates.rectElementName = "rect";
        NodeTemplates.rectElementType = 1;
        NodeTemplates.rectElementCategory = "Basic Shapes";
        NodeTemplates.rectElementDescription = "Rect";
        NodeTemplates.circleMemberName = "circleElement";
        NodeTemplates.circleElementValue = "<circle r=\"0\"/>";
        NodeTemplates.circleElementName = "circle";
        NodeTemplates.circleElementCategory = "Basic Shapes";
        NodeTemplates.circleElementDescription = "Circle";
        NodeTemplates.lineElementMemberName = "lineElement";
        NodeTemplates.lineElementName = "line";
        NodeTemplates.lineElementValue = "<line x1=\"0\" y1=\"0\" x2=\"0\" y2=\"0\"/>";
        NodeTemplates.lineElementType = 1;
        NodeTemplates.lineElementCategory = "Basic Shapes";
        NodeTemplates.lineElementDescription = "Text";
        NodeTemplates.pathElementMemberName = "pathElement";
        NodeTemplates.pathElementName = "path";
        NodeTemplates.pathElementValue = "<path d=\"M0,0\"/>";
        NodeTemplates.pathElementType = 1;
        NodeTemplates.pathElementCategory = "Paths";
        NodeTemplates.pathElementDescription = "Path";
        NodeTemplates.groupElementMemberName = "groupElement";
        NodeTemplates.groupElementName = "g";
        NodeTemplates.groupElementValue = "<g/>";
        NodeTemplates.groupElementType = 1;
        NodeTemplates.groupElementCategory = "Document Structure";
        NodeTemplates.groupElementDescription = "Group";
        NodeTemplates.ellipseElementMemberName = "ellipseElement";
        NodeTemplates.ellipseElementName = "ellipse";
        NodeTemplates.ellipseElementValue = "<ellipse/>";
        NodeTemplates.ellipseElementType = 1;
        NodeTemplates.ellipseElementCategory = "Basic Shapes";
        NodeTemplates.ellipseElementDescription = "Ellipse";
        NodeTemplates.imageElementMemberName = "imageElement";
        NodeTemplates.imageElementName = "image";
        NodeTemplates.imageElementValue = "<image xlink:href=\"file/c://\"/>";
        NodeTemplates.imageElementType = 1;
        NodeTemplates.imageElementCategory = "Document Structure";
        NodeTemplates.imageElementDescription = "Image";
        NodeTemplates.polygonElementMemberName = "polygonElement";
        NodeTemplates.polygonElementName = "polygon";
        NodeTemplates.polygonElementValue = "<polygon/>";
        NodeTemplates.polygonElementType = 1;
        NodeTemplates.polygonElementCategory = "Basic Shapes";
        NodeTemplates.polygonElementDescription = "Polygon";
        NodeTemplates.polylineElementMemberName = "polylineElement";
        NodeTemplates.polylineElementName = "polyline";
        NodeTemplates.polylineElementValue = "<polyline/>";
        NodeTemplates.polylineElementType = 1;
        NodeTemplates.polylineElementCategory = "Basic Shapes";
        NodeTemplates.polylineElementDescription = "Polyline";
        NodeTemplates.textElementMemberName = "textElement";
        NodeTemplates.textElementName = "text";
        NodeTemplates.textElementValue = "<text> </text>";
        NodeTemplates.textElementType = 1;
        NodeTemplates.textElementCategory = "Text";
        NodeTemplates.textElementDescription = "Text";
        NodeTemplates.tRefElementMemberName = "tRefElement";
        NodeTemplates.tRefElementName = "tref";
        NodeTemplates.tRefElementValue = "<tref/>";
        NodeTemplates.tRefElementType = 1;
        NodeTemplates.tRefElementCategory = "Text";
        NodeTemplates.tRefElementDescription = "TRef";
        NodeTemplates.tspanElementMemberName = "tspanElement";
        NodeTemplates.tspanElementName = "tspan";
        NodeTemplates.tspanElementValue = "<tspan/>";
        NodeTemplates.tspanElementType = 1;
        NodeTemplates.tspanElementCategory = "Text";
        NodeTemplates.tspanElementDescription = "TSpan";
        NodeTemplates.textPathElementMemberName = "textPathElement";
        NodeTemplates.textPathElementName = "textPath";
        NodeTemplates.textPathElementValue = "<textPath/>";
        NodeTemplates.textPathElementType = 1;
        NodeTemplates.textPathElementCategory = "Text";
        NodeTemplates.textPathElementDescription = "TextPath";
        NodeTemplates.svgElementMemberName = "svgElement";
        NodeTemplates.svgElementName = "svg";
        NodeTemplates.svgElementValue = "<svg/>";
        NodeTemplates.svgElementType = 1;
        NodeTemplates.svgElementCategory = "Document Structure";
        NodeTemplates.svgElementDescription = "svg";
        NodeTemplates.feBlendElementMemberName = "feBlendElement";
        NodeTemplates.feBlendElementName = "feBlend";
        NodeTemplates.feBlendElementValue = "<feBlend/>";
        NodeTemplates.feBlendElementType = 1;
        NodeTemplates.feBlendElementCategory = "Filter Effects";
        NodeTemplates.feBlendElementDescription = "FeBlend";
        NodeTemplates.feColorMatrixElementMemberName = "feColorMatrixElement";
        NodeTemplates.feColorMatrixElementName = "feColorMatrix";
        NodeTemplates.feColorMatrixElementValue = "<feColorMatrix/>";
        NodeTemplates.feColorMatrixElementType = 1;
        NodeTemplates.feColorMatrixElementCategory = "Filter Effects";
        NodeTemplates.feColorMatrixElementDescription = "FeColorMatrix";
        NodeTemplates.feComponentTransferElementMemberName = "feComponentTransferElement";
        NodeTemplates.feComponentTransferElementName = "feComponentTransfer";
        NodeTemplates.feComponentTransferElementValue = "<feComponentTransfer/>";
        NodeTemplates.feComponentTransferElementType = 1;
        NodeTemplates.feComponentTransferElementCategory = "Filter Effects";
        NodeTemplates.feComponentTransferElementDescription = "FeComponentTransfer";
        NodeTemplates.feCompositeElementMemberName = "feCompositeElement";
        NodeTemplates.feCompositeElementName = "feComposite";
        NodeTemplates.feCompositeElementValue = "<feComposite/>";
        NodeTemplates.feCompositeElementType = 1;
        NodeTemplates.feCompositeElementCategory = "Filter Effects";
        NodeTemplates.feCompositeElementDescription = "FeComposite";
        NodeTemplates.feConvolveMatrixElementMemberName = "feConvolveMatrixElement";
        NodeTemplates.feConvolveMatrixElementName = "feConvolveMatrix";
        NodeTemplates.feConvolveMatrixElementValue = "<feConvolveMatrix/>";
        NodeTemplates.feConvolveMatrixElementType = 1;
        NodeTemplates.feConvolveMatrixElementCategory = "Filter Effects";
        NodeTemplates.feConvolveMatrixElementDescription = "FeConvolveMatrix";
        NodeTemplates.feDiffuseLightingElementMemberName = "feDiffuseLightingElement";
        NodeTemplates.feDiffuseLightingElementName = "feDiffuseLighting";
        NodeTemplates.feDiffuseLightingElementValue = "<feDiffuseLighting/>";
        NodeTemplates.feDiffuseLightingElementType = 1;
        NodeTemplates.feDiffuseLightingElementCategory = "Filter Effects";
        NodeTemplates.feDiffuseLightingElementDescription = "FeDiffuseLighting";
        NodeTemplates.feDisplacementMapElementMemberName = "feDisplacementMapElement";
        NodeTemplates.feDisplacementMapElementName = "feDisplacementMap";
        NodeTemplates.feDisplacementMapElementValue = "<feDisplacementMap/>";
        NodeTemplates.feDisplacementMapElementType = 1;
        NodeTemplates.feDisplacementMapElementCategory = "Filter Effects";
        NodeTemplates.feDisplacementMapElementDescription = "FeDisplacementMap";
        NodeTemplates.feDistantLightElementMemberName = "feDistantLightElement";
        NodeTemplates.feDistantLightElementName = "feDistantLight";
        NodeTemplates.feDistantLightElementValue = "<feDistantLight/>";
        NodeTemplates.feDistantLightElementType = 1;
        NodeTemplates.feDistantLightElementCategory = "Filter Effects";
        NodeTemplates.feDistantLightElementDescription = "FeDistantLight";
        NodeTemplates.feFloodElementMemberName = "feFloodElement";
        NodeTemplates.feFloodElementName = "feFlood";
        NodeTemplates.feFloodElementValue = "<feFlood/>";
        NodeTemplates.feFloodElementType = 1;
        NodeTemplates.feFloodElementCategory = "Filter Effects";
        NodeTemplates.feFloodElementDescription = "FeFlood";
        NodeTemplates.feFuncAElementMemberName = "feFuncAElement";
        NodeTemplates.feFuncAElementName = "feFuncA";
        NodeTemplates.feFuncAElementValue = "<feFuncA/>";
        NodeTemplates.feFuncAElementType = 1;
        NodeTemplates.feFuncAElementCategory = "Filter Effects";
        NodeTemplates.feFuncAElementDescription = "FeFuncA";
        NodeTemplates.feFuncBElementMemberName = "feFuncBElement";
        NodeTemplates.feFuncBElementName = "feFuncB";
        NodeTemplates.feFuncBElementValue = "<feFuncB/>";
        NodeTemplates.feFuncBElementType = 1;
        NodeTemplates.feFuncBElementCategory = "Filter Effects";
        NodeTemplates.feFuncBElementDescription = "FeFuncB";
        NodeTemplates.feFuncGElementMemberName = "feFuncGElement";
        NodeTemplates.feFuncGElementName = "feFuncG";
        NodeTemplates.feFuncGElementValue = "<feFuncG/>";
        NodeTemplates.feFuncGElementType = 1;
        NodeTemplates.feFuncGElementCategory = "Filter Effects";
        NodeTemplates.feFuncGElementDescription = "FeFuncG";
        NodeTemplates.feFuncRElementMemberName = "feFuncRElement";
        NodeTemplates.feFuncRElementName = "feFuncR";
        NodeTemplates.feFuncRElementValue = "<feFuncR/>";
        NodeTemplates.feFuncRElementType = 1;
        NodeTemplates.feFuncRElementCategory = "Filter Effects";
        NodeTemplates.feFuncRElementDescription = "FeFuncR";
        NodeTemplates.feGaussianBlurElementMemberName = "feGaussianBlurElement";
        NodeTemplates.feGaussianBlurElementName = "feGaussianBlur";
        NodeTemplates.feGaussianBlurElementValue = "<feGaussianBlur/>";
        NodeTemplates.feGaussianBlurElementType = 1;
        NodeTemplates.feGaussianBlurElementCategory = "Filter Effects";
        NodeTemplates.feGaussianBlurElementDescription = "FeGaussianBlur";
        NodeTemplates.feImageElementMemberName = "feImageElement";
        NodeTemplates.feImageElementName = "feImage";
        NodeTemplates.feImageElementValue = "<feImage/>";
        NodeTemplates.feImageElementType = 1;
        NodeTemplates.feImageElementCategory = "Filter Effects";
        NodeTemplates.feImageElementDescription = "FeImage";
        NodeTemplates.feMergeElementMemberName = "feImageElement";
        NodeTemplates.feMergeElementName = "feMerge";
        NodeTemplates.feMergeElementValue = "<feMerge/>";
        NodeTemplates.feMergeElementType = 1;
        NodeTemplates.feMergeElementCategory = "Filter Effects";
        NodeTemplates.feMergeElementDescription = "FeMerge";
        NodeTemplates.feMergeNodeElementMemberName = "feMergeNodeElement";
        NodeTemplates.feMergeNodeElementName = "feMergeNode";
        NodeTemplates.feMergeNodeElementValue = "<feMergeNode/>";
        NodeTemplates.feMergeNodeElementType = 1;
        NodeTemplates.feMergeNodeElementCategory = "Filter Effects";
        NodeTemplates.feMergeNodeElementDescription = "FeMergeNode";
        NodeTemplates.feMorphologyElementMemberName = "feMorphologyElement";
        NodeTemplates.feMorphologyElementName = "feMorphology";
        NodeTemplates.feMorphologyElementValue = "<feMorphology/>";
        NodeTemplates.feMorphologyElementType = 1;
        NodeTemplates.feMorphologyElementCategory = "Filter Effects";
        NodeTemplates.feMorphologyElementDescription = "FeMorphology";
        NodeTemplates.feOffsetElementMemberName = "feMorphologyElement";
        NodeTemplates.feOffsetElementName = "feOffset";
        NodeTemplates.feOffsetElementValue = "<feOffset/>";
        NodeTemplates.feOffsetElementType = 1;
        NodeTemplates.feOffsetElementCategory = "Filter Effects";
        NodeTemplates.feOffsetElementDescription = "FeOffset";
        NodeTemplates.fePointLightElementMemberName = "fePointLightElement";
        NodeTemplates.fePointLightElementName = "fePointLight";
        NodeTemplates.fePointLightElementValue = "<fePointLight/>";
        NodeTemplates.fePointLightElementType = 1;
        NodeTemplates.fePointLightElementCategory = "Filter Effects";
        NodeTemplates.fePointLightElementDescription = "FePointLight";
        NodeTemplates.feSpecularLightingElementMemberName = "fePointLightElement";
        NodeTemplates.feSpecularLightingElementName = "feSpecularLighting";
        NodeTemplates.feSpecularLightingElementValue = "<feSpecularLighting/>";
        NodeTemplates.feSpecularLightingElementType = 1;
        NodeTemplates.feSpecularLightingElementCategory = "Filter Effects";
        NodeTemplates.feSpecularLightingElementDescription = "FeSpecularLighting";
        NodeTemplates.feSpotLightElementMemberName = "feSpotLightElement";
        NodeTemplates.feSpotLightElementName = "feSpotLight";
        NodeTemplates.feSpotLightElementValue = "<feSpotLight/>";
        NodeTemplates.feSpotLightElementType = 1;
        NodeTemplates.feSpotLightElementCategory = "Filter Effects";
        NodeTemplates.feSpotLightElementDescription = "FeSpotLight";
        NodeTemplates.feTileElementMemberName = "feTileElement";
        NodeTemplates.feTileElementName = "feTile";
        NodeTemplates.feTileElementValue = "<feTile/>";
        NodeTemplates.feTileElementType = 1;
        NodeTemplates.feTileElementCategory = "Filter Effects";
        NodeTemplates.feTileElementDescription = "FeTile";
        NodeTemplates.feTurbulenceElementMemberName = "feTurbulenceElement";
        NodeTemplates.feTurbulenceElementName = "feTurbulence";
        NodeTemplates.feTurbulenceElementValue = "<feTurbulence/>";
        NodeTemplates.feTurbulenceElementType = 1;
        NodeTemplates.feTurbulenceElementCategory = "Filter Effects";
        NodeTemplates.feTurbulenceElementDescription = "FeTurbulence";
        NodeTemplates.filterElementMemberName = "filterElement";
        NodeTemplates.filterElementName = "filter";
        NodeTemplates.filterElementValue = "<filter/>";
        NodeTemplates.filterElementType = 1;
        NodeTemplates.filterElementCategory = "Filter Effects";
        NodeTemplates.filterElementDescription = "Filter";
        NodeTemplates.aElementMemberName = "aElement";
        NodeTemplates.aElementName = "a";
        NodeTemplates.aElementValue = "<a/>";
        NodeTemplates.aElementType = 1;
        NodeTemplates.aElementCategory = "Linking";
        NodeTemplates.aElementDescription = "A";
        NodeTemplates.altGlyphElementMemberName = "altGlyphElement";
        NodeTemplates.altGlyphElementName = "altGlyph";
        NodeTemplates.altGlyphElementValue = "<altGlyph/>";
        NodeTemplates.altGlyphElementType = 1;
        NodeTemplates.altGlyphElementCategory = "Text";
        NodeTemplates.altGlyphElementDescription = "AltGlyph";
        NodeTemplates.altGlyphDefElementMemberName = "altGlyphDefElement";
        NodeTemplates.altGlyphDefElementName = "altGlyphDef";
        NodeTemplates.altGlyphDefElementValue = "<altGlyphDef/>";
        NodeTemplates.altGlyphDefElementType = 1;
        NodeTemplates.altGlyphDefElementCategory = "Text";
        NodeTemplates.altGlyphDefElementDescription = "AltGlyphDef";
        NodeTemplates.altGlyphItemElementMemberName = "altGlyphItemElement";
        NodeTemplates.altGlyphItemElementName = "altGlyphItem";
        NodeTemplates.altGlyphItemElementValue = "<altGlyphItem/>";
        NodeTemplates.altGlyphItemElementType = 1;
        NodeTemplates.altGlyphItemElementCategory = "Text";
        NodeTemplates.altGlyphItemElementDescription = "AltGlyphItem";
        NodeTemplates.clipPathElementMemberName = "clipPathElement";
        NodeTemplates.clipPathElementName = "clipPath";
        NodeTemplates.clipPathElementValue = "<clipPath/>";
        NodeTemplates.clipPathElementType = 1;
        NodeTemplates.clipPathElementCategory = "Clipping, Masking and Compositing";
        NodeTemplates.clipPathElementDescription = "ClipPath";
        NodeTemplates.colorProfileElementMemberName = "colorProfileElement";
        NodeTemplates.colorProfileElementName = "color-profile";
        NodeTemplates.colorProfileElementValue = "<color-profile/>";
        NodeTemplates.colorProfileElementType = 1;
        NodeTemplates.colorProfileElementCategory = "Color";
        NodeTemplates.colorProfileElementDescription = "ColorProfile";
        NodeTemplates.cursorElementMemberName = "cursorElement";
        NodeTemplates.cursorElementName = "cursor";
        NodeTemplates.cursorElementValue = "<cursor/>";
        NodeTemplates.cursorElementType = 1;
        NodeTemplates.cursorElementCategory = "Interactivity";
        NodeTemplates.cursorElementDescription = "Cursor";
        NodeTemplates.definitionSrcElementMemberName = "definitionSrcElement";
        NodeTemplates.definitionSrcElementName = "definition-src";
        NodeTemplates.definitionSrcElementValue = "<definition-src/>";
        NodeTemplates.definitionSrcElementType = 1;
        NodeTemplates.definitionSrcElementCategory = "Fonts";
        NodeTemplates.definitionSrcElementDescription = "DefinitionSrc";
        NodeTemplates.defsElementMemberName = "defsElement";
        NodeTemplates.defsElementName = "defs";
        NodeTemplates.defsElementValue = "<defs/>";
        NodeTemplates.defsElementType = 1;
        NodeTemplates.defsElementCategory = "Document Structure";
        NodeTemplates.defsElementDescription = "Defs";
        NodeTemplates.descElementMemberName = "descElement";
        NodeTemplates.descElementName = "desc";
        NodeTemplates.descElementValue = "<desc/>";
        NodeTemplates.descElementType = 1;
        NodeTemplates.descElementCategory = "Document Structure";
        NodeTemplates.descElementDescription = "Desc";
        NodeTemplates.foreignObjectElementMemberName = "foreignObjectElement";
        NodeTemplates.foreignObjectElementName = "foreignObject";
        NodeTemplates.foreignObjectElementValue = "<foreignObject/>";
        NodeTemplates.foreignObjectElementType = 1;
        NodeTemplates.foreignObjectElementCategory = "Extensibility";
        NodeTemplates.foreignObjectElementDescription = "ForeignObject";
        NodeTemplates.glyphElementMemberName = "glyphElement";
        NodeTemplates.glyphElementName = "glyph";
        NodeTemplates.glyphElementValue = "<glyph/>";
        NodeTemplates.glyphElementType = 1;
        NodeTemplates.glyphElementCategory = "Fonts";
        NodeTemplates.glyphElementDescription = "Glyph";
        NodeTemplates.glyphRefElementMemberName = "glyphRefElement";
        NodeTemplates.glyphRefElementName = "glyphRef";
        NodeTemplates.glyphRefElementValue = "<glyphRef/>";
        NodeTemplates.glyphRefElementType = 1;
        NodeTemplates.glyphRefElementCategory = "Text";
        NodeTemplates.glyphRefElementDescription = "GlyphRef";
        NodeTemplates.hkernElementMemberName = "hkernElement";
        NodeTemplates.hkernElementName = "hkern";
        NodeTemplates.hkernElementValue = "<hkern/>";
        NodeTemplates.hkernElementType = 1;
        NodeTemplates.hkernElementCategory = "Fonts";
        NodeTemplates.hkernElementDescription = "Hkern";
        NodeTemplates.linearGradientElementMemberName = "linearGradientElement";
        NodeTemplates.linearGradientElementName = "linearGradient";
        NodeTemplates.linearGradientElementValue = "<linearGradient/>";
        NodeTemplates.linearGradientElementType = 1;
        NodeTemplates.linearGradientElementCategory = "Gradients and Patterns";
        NodeTemplates.linearGradientElementDescription = "LinearGradient";
        NodeTemplates.markerElementMemberName = "markerElement";
        NodeTemplates.markerElementName = "marker";
        NodeTemplates.markerElementValue = "<marker/>";
        NodeTemplates.markerElementType = 1;
        NodeTemplates.markerElementCategory = "Painting: Filling, Stroking and Marker Symbols";
        NodeTemplates.markerElementDescription = "Marker";
        NodeTemplates.maskElementMemberName = "maskElement";
        NodeTemplates.maskElementName = "mask";
        NodeTemplates.maskElementValue = "<mask/>";
        NodeTemplates.maskElementType = 1;
        NodeTemplates.maskElementCategory = "Clipping, Masking and Compositing";
        NodeTemplates.maskElementDescription = "Mask";
        NodeTemplates.metadataElementMemberName = "metadataElement";
        NodeTemplates.metadataElementName = "metadata";
        NodeTemplates.metadataElementValue = "<metadata/>";
        NodeTemplates.metadataElementType = 1;
        NodeTemplates.metadataElementCategory = "Metadata";
        NodeTemplates.metadataElementDescription = "Metadata";
        NodeTemplates.missingGlyphElementMemberName = "missingGlyphElement";
        NodeTemplates.missingGlyphElementName = "missing-glyph";
        NodeTemplates.missingGlyphElementValue = "<missing-glyph/>";
        NodeTemplates.missingGlyphElementType = 1;
        NodeTemplates.missingGlyphElementCategory = "Fonts";
        NodeTemplates.missingGlyphElementDescription = "MissingGlyph";
        NodeTemplates.mpathElementMemberName = "mpathElement";
        NodeTemplates.mpathElementName = "mpath";
        NodeTemplates.mpathElementValue = "<mpath/>";
        NodeTemplates.mpathElementType = 1;
        NodeTemplates.mpathElementCategory = "Animation";
        NodeTemplates.mpathElementDescription = "Mpath";
        NodeTemplates.patternElementMemberName = "patternElement";
        NodeTemplates.patternElementName = "pattern";
        NodeTemplates.patternElementValue = "<pattern/>";
        NodeTemplates.patternElementType = 1;
        NodeTemplates.patternElementCategory = "Gradients and Patterns";
        NodeTemplates.patternElementDescription = "Pattern";
        NodeTemplates.radialGradientElementMemberName = "radialGradientElement";
        NodeTemplates.radialGradientElementName = "radialGradient";
        NodeTemplates.radialGradientElementValue = "<radialGradient/>";
        NodeTemplates.radialGradientElementType = 1;
        NodeTemplates.radialGradientElementCategory = "Gradients and Patterns";
        NodeTemplates.radialGradientElementDescription = "RadialGradient";
        NodeTemplates.scriptElementMemberName = "scriptElement";
        NodeTemplates.scriptElementName = "script";
        NodeTemplates.scriptElementValue = "<script/>";
        NodeTemplates.scriptElementType = 1;
        NodeTemplates.scriptElementCategory = "Scripting";
        NodeTemplates.scriptElementDescription = "script";
        NodeTemplates.setElementMemberName = "setElement";
        NodeTemplates.setElementName = "set";
        NodeTemplates.setElementValue = "<set attributeName=\"fill\" from=\"white\" to=\"black\" dur=\"1s\"/>";
        NodeTemplates.setElementType = 1;
        NodeTemplates.setElementCategory = "Animation";
        NodeTemplates.setElementDescription = "set";
        NodeTemplates.stopElementMemberName = "stopElement";
        NodeTemplates.stopElementName = "stop";
        NodeTemplates.stopElementValue = "<stop/>";
        NodeTemplates.stopElementType = 1;
        NodeTemplates.stopElementCategory = "Gradients and Patterns";
        NodeTemplates.stopElementDescription = "Stop";
        NodeTemplates.styleElementMemberName = "styleElement";
        NodeTemplates.styleElementName = "style";
        NodeTemplates.styleElementValue = "<style/>";
        NodeTemplates.styleElementType = 1;
        NodeTemplates.styleElementCategory = "Styling";
        NodeTemplates.styleElementDescription = "Style";
        NodeTemplates.switchElementMemberName = "switchElement";
        NodeTemplates.switchElementName = "switch";
        NodeTemplates.switchElementValue = "<switch/>";
        NodeTemplates.switchElementType = 1;
        NodeTemplates.switchElementCategory = "Document Structure";
        NodeTemplates.switchElementDescription = "Switch";
        NodeTemplates.symbolElementMemberName = "symbolElement";
        NodeTemplates.symbolElementName = "symbol";
        NodeTemplates.symbolElementValue = "<symbol/>";
        NodeTemplates.symbolElementType = 1;
        NodeTemplates.symbolElementCategory = "Document Structure";
        NodeTemplates.symbolElementDescription = "Symbol";
        NodeTemplates.titleElementMemberName = "titleElement";
        NodeTemplates.titleElementName = "title";
        NodeTemplates.titleElementValue = "<title/>";
        NodeTemplates.titleElementType = 1;
        NodeTemplates.titleElementCategory = "Document Structure";
        NodeTemplates.titleElementDescription = "Title";
        NodeTemplates.useElementMemberName = "useElement";
        NodeTemplates.useElementName = "use";
        NodeTemplates.useElementValue = "<use/>";
        NodeTemplates.useElementType = 1;
        NodeTemplates.useElementCategory = "Document Structure";
        NodeTemplates.useElementDescription = "Use";
        NodeTemplates.viewElementMemberName = "viewElement";
        NodeTemplates.viewElementName = "view";
        NodeTemplates.viewElementValue = "<view/>";
        NodeTemplates.viewElementType = 1;
        NodeTemplates.viewElementCategory = "Linking";
        NodeTemplates.viewElementDescription = "View";
        NodeTemplates.vkernElementMemberName = "vkernElement";
        NodeTemplates.vkernElementName = "vkern";
        NodeTemplates.vkernElementValue = "<vkern/>";
        NodeTemplates.vkernElementType = 1;
        NodeTemplates.vkernElementCategory = "Fonts";
        NodeTemplates.vkernElementDescription = "Vkern";
        NodeTemplates.fontElementMemberName = "fontElement";
        NodeTemplates.fontElementName = "font";
        NodeTemplates.fontElementValue = "<font/>";
        NodeTemplates.fontElementType = 1;
        NodeTemplates.fontElementCategory = "Fonts";
        NodeTemplates.fontElementDescription = "Font";
        NodeTemplates.fontFaceElementMemberName = "fontFaceElement";
        NodeTemplates.fontFaceElementName = "font-face";
        NodeTemplates.fontFaceElementValue = "<font-face/>";
        NodeTemplates.fontFaceElementType = 1;
        NodeTemplates.fontFaceElementCategory = "Fonts";
        NodeTemplates.fontFaceElementDescription = "FontFace";
        NodeTemplates.fontFaceFormatElementMemberName = "fontFaceFormatElement";
        NodeTemplates.fontFaceFormatElementName = "font-face-format";
        NodeTemplates.fontFaceFormatElementValue = "<font-face-format/>";
        NodeTemplates.fontFaceFormatElementType = 1;
        NodeTemplates.fontFaceFormatElementCategory = "Fonts";
        NodeTemplates.fontFaceFormatElementDescription = "FontFaceFormat";
        NodeTemplates.fontFaceNameElementMemberName = "fontFaceNameElement";
        NodeTemplates.fontFaceNameElementName = "font-face-name";
        NodeTemplates.fontFaceNameElementValue = "<font-face-name/>";
        NodeTemplates.fontFaceNameElementType = 1;
        NodeTemplates.fontFaceNameElementCategory = "Fonts";
        NodeTemplates.fontFaceNameElementDescription = "FontFaceName";
        NodeTemplates.fontFaceSrcElementMemberName = "fontFaceSrcElement";
        NodeTemplates.fontFaceSrcElementName = "font-face-src";
        NodeTemplates.fontFaceSrcElementValue = "<font-face-src/>";
        NodeTemplates.fontFaceSrcElementType = 1;
        NodeTemplates.fontFaceSrcElementCategory = "Fonts";
        NodeTemplates.fontFaceSrcElementDescription = "FontFaceSrc";
        NodeTemplates.fontFaceUriElementMemberName = "fontFaceUriElement";
        NodeTemplates.fontFaceUriElementName = "font-face-uri";
        NodeTemplates.fontFaceUriElementValue = "<font-face-uri/>";
        NodeTemplates.fontFaceUriElementType = 1;
        NodeTemplates.fontFaceUriElementCategory = "Fonts";
        NodeTemplates.fontFaceUriElementDescription = "FontFaceUri";
        NodeTemplates.animateElementMemberName = "fontFaceUriElement";
        NodeTemplates.animateElementName = "animate";
        NodeTemplates.animateElementValue = "<animate attributeName=\"fill\" from=\"white\" to=\"black\" dur=\"1s\"/>";
        NodeTemplates.animateElementType = 1;
        NodeTemplates.animateElementCategory = "Animation";
        NodeTemplates.animateElementDescription = "Animate";
        NodeTemplates.animateColorElementMemberName = "animateColorElement";
        NodeTemplates.animateColorElementName = "animateColor";
        NodeTemplates.animateColorElementValue = "<animateColor attributeName=\"fill\" from=\"white\" to=\"black\" dur=\"1s\"/>";
        NodeTemplates.animateColorElementType = 1;
        NodeTemplates.animateColorElementCategory = "Animation";
        NodeTemplates.animateColorElementDescription = "AnimateColor";
        NodeTemplates.animateMotionElementMemberName = "animateMotionElement";
        NodeTemplates.animateMotionElementName = "animateMotion";
        NodeTemplates.animateMotionElementValue = "<animateMotion dur=\"1s\" path=\"M0,0\"/>";
        NodeTemplates.animateMotionElementType = 1;
        NodeTemplates.animateMotionElementCategory = "Animation";
        NodeTemplates.animateMotionElementDescription = "AnimateMotion";
        NodeTemplates.animateTransformElementMemberName = "animateTransformElement";
        NodeTemplates.animateTransformElementName = "animateTransform";
        NodeTemplates.animateTransformElementValue = "<animateTransform attributeName=\"transform\" type=\"rotate\" from=\"0\" to=\"0\" dur=\"1s\"/>";
        NodeTemplates.animateTransformElementType = 1;
        NodeTemplates.animateTransformElementCategory = "Animation";
        NodeTemplates.animateTransformElementDescription = "AnimateTransform";
    }
    
    public static class NodeTemplateDescriptor
    {
        private String name;
        private String xmlValue;
        private short type;
        private String category;
        private String description;
        
        public NodeTemplateDescriptor(final String name, final String xmlValue, final short type, final String category, final String description) {
            this.name = name;
            this.xmlValue = xmlValue;
            this.type = type;
            this.category = category;
            this.description = description;
        }
        
        public String getCategory() {
            return this.category;
        }
        
        public void setCategory(final String category) {
            this.category = category;
        }
        
        public String getDescription() {
            return this.description;
        }
        
        public void setDescription(final String description) {
            this.description = description;
        }
        
        public String getName() {
            return this.name;
        }
        
        public void setName(final String name) {
            this.name = name;
        }
        
        public short getType() {
            return this.type;
        }
        
        public void setType(final short type) {
            this.type = type;
        }
        
        public String getXmlValue() {
            return this.xmlValue;
        }
        
        public void setXmlValue(final String xmlValue) {
            this.xmlValue = xmlValue;
        }
    }
}
