/* * SPDX-License-Identifier: AGPL-3.0-or-later * * C Copyright 2023 Regione Piemonte * */

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.5
 * 2020-05-26T19:01:17.182+02:00
 * Generated source version: 3.2.5
 *
 */
@WebServiceClient(name = "RicercaService",
                  wsdlLocation = "classpath:RicercaService.wsdl",
                  targetNamespace = "http://siac.csi.it/ricerche/svc/1.0")
public class RicercaService_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://siac.csi.it/ricerche/svc/1.0", "RicercaService");
    public final static QName RicercaServicePort = new QName("http://siac.csi.it/ricerche/svc/1.0", "RicercaServicePort");
    static {
        URL url = RicercaService_Service.class.getClassLoader().getResource("RicercaService.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(RicercaService_Service.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "classpath:RicercaService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public RicercaService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public RicercaService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RicercaService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }

    public RicercaService_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public RicercaService_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public RicercaService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns RicercaService
     */
    @WebEndpoint(name = "RicercaServicePort")
    public RicercaService getRicercaServicePort() {
        return super.getPort(RicercaServicePort, RicercaService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RicercaService
     */
    @WebEndpoint(name = "RicercaServicePort")
    public RicercaService getRicercaServicePort(WebServiceFeature... features) {
        return super.getPort(RicercaServicePort, RicercaService.class, features);
    }

}
