
package com.opentext.livelink.service.searchservice;

import java.net.URL;
import java.util.Map;

import javax.xml.namespace.QName;
import javax.xml.ws.BindingProvider;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SearchService", targetNamespace = "urn:SearchServices.service.livelink.opentext.com")
public class SearchService_Service
    extends Service
{

    private final static QName SEARCHSERVICE_QNAME = new QName("urn:SearchServices.service.livelink.opentext.com", "SearchService");

     public SearchService_Service(URL wsdlLocation) {
        super(wsdlLocation, SEARCHSERVICE_QNAME);
    }

    public SearchService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SEARCHSERVICE_QNAME, features);
    }

    public SearchService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SearchService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SearchService
     */
    @WebEndpoint(name = "BasicHttpBinding_SearchService")
    public SearchService getBasicHttpBindingSearchService(String endpoint) {
    	SearchService port = super.getPort(new QName("urn:SearchServices.service.livelink.opentext.com", "BasicHttpBinding_SearchService"), SearchService.class);
    	Map<String, Object> requestContext = ((BindingProvider) port).getRequestContext();
    	requestContext.put(BindingProvider.ENDPOINT_ADDRESS_PROPERTY, endpoint);
    	return port;
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SearchService
     */
    @WebEndpoint(name = "BasicHttpBinding_SearchService")
    public SearchService getBasicHttpBindingSearchService(String  endpoint,WebServiceFeature... features) {
    	SearchService port = super.getPort(new QName("urn:SearchServices.service.livelink.opentext.com", "BasicHttpBinding_SearchService"), SearchService.class, features);
    	Map<String, Object> requestContext = ((BindingProvider) port).getRequestContext();
    	requestContext.put(BindingProvider.ENDPOINT_ADDRESS_PROPERTY, endpoint);
       return port;
    }

}
